### ISSUE TITLE
[Feature request| Vim editor syntax highlighting

### ISSUE THREAD

**Issue by croessner** [rspamd/rspamd#1023]
It would be awesome to have syntax highlighting for rspamd's config files in Vim. Not sure, if this is the right place to ask for, but maybe you guys already have one file and like to provide it.

Thanks

Christian

**Comment by croessner** [comment]
I started: https://github.com/sys4/vim-rspamd-syntax

**Comment by andryyy** [comment]
The sys4 guys are coming. :-)

**Comment by xpunkt** [comment]
it would be nice if rspamd had a ucl to xml converter

wim, hmm would it be  possible to see a nanorc ?

**Comment by vstakhov** [comment]
As far as I see, you are trying to create a sort of Rspamd specific syntax highlight. Perhaps, it is worth to start from syntax highlight for [libucl](https://github.com/vstakhov/libucl)? I have already created rouge syntax highlighter for it: https://github.com/vstakhov/rouge/blob/master/lib/rouge/lexers/ucl.rb

**Comment by croessner** [comment]
@vstakhov thank you. I looked at this file and I see, you do a "general" highlighting for UCL. What I try to achieve is to register all known keywords in rspamd, sp you see directly syntax errors, if you edit a file.

**Comment by croessner** [comment]
I have some issues with /*...*/ comment blocks and with variables like DBCONF CONFDIR. Maybe someone likes to have a view at the current file and sees what I am missing?

**Comment by croessner** [comment]
@vstakhov , I spoke with Patrick. Maybe we could write a generic ucl vim syntax and inherit from it in rspamd.vim. I must read docs how to do that ;-)
