### ISSUE TITLE
[Feature request] [WebUI] Exception filter in History

### ISSUE THREAD

**Issue by dehnli** [rspamd/rspamd#1090]
I have a huge number of ham from some senders and it fills all lines in `History` section. It'd be nice to add exception filter to exclude such senders by i.e IP

**Comment by fatalbanana** [comment]
There is [task:set_flag('no_log')](https://rspamd.com/doc/lua/task.html#m09dd4) though this affects logging as well.

**Comment by dehnli** [comment]
Another trick to achive it is adding **minus sign** before `IP-address`, `Envelope From`, etc in `Search` field like this `-portal@rosreestr.ru`
