### ISSUE TITLE
Worker Web UI History tab: Subject, header details, submit as spam

### ISSUE THREAD

**Issue by darkpixel** [rspamd/rspamd#1093]
I had a few suggestions for the History tab in the Web UI.

It would be handy to see the subject of an e-mail and maybe have a 'details' button that shows header information.  Maybe even a config toggl for storing/displaying the entire message.

If the entire message were stored, it would be nice to have a 'submit as spam' and 'submit as ham' button that submits the message as if you pasted it in to the "Insert raw SPAM source" box on the Learning tab.

**Comment by vstakhov** [comment]
That's a big task I'm afraid. However, I have it in my long todo list.

**Comment by z-jun** [comment]
Store and display headers is very good idea. Now it's impossible to get in web ui real recipient of email with nonstandart headers. Headers are small enough to store in database.

On disk archive of entire messages and buttons to "release (rejected/grey listed)", "lear ham", "learn spam" will help a lot. No need to display content.
