### ISSUE TITLE
[WebUI] Empty bayes spam/ham probability value

### ISSUE THREAD

**Issue by dehnli** [rspamd/rspamd#1322]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
`1.5.0-git.95f9bd8`

### Operation system, CPU, memory and environment:
`FreeBSD 10.3-RELEASE-p11 amd64 GENERIC/Mozilla Firefox 50.1.0`

### Description (Please provide a descriptive summary of the issue):
Empty bayes spam/ham probability value hint in `Scan results`

### Steps to reproduce:
1. Log in WebUI interface
2. Scan message which has `BAYES_SPAM` or `BAYES_HAM` symbol
3. Hover on `BAYES_SPAM:` or `BAYES_HAM:`symbol  

### Expected results:
Display bayes spam/ham probability ie `Message probably spam, probability: 99.99%`

### Actual results:
![rspamd-webui-scan-results-bug](https://cloud.githubusercontent.com/assets/14199981/21752565/fc479ab0-d5f3-11e6-82e7-02baa31a7b16.png)

**Comment by fatalbanana** [comment]
Descriptions for these symbols in metric are a bit strange:

```
        symbol "BAYES_SPAM" {
            weight = 4.0;
            description = "Message probably spam, probability: ";
        }
```

Probability is returned in `options`, which are not part of history.

**Comment by dehnli** [comment]
@fatalbanana it turns out it's typo?
