### ISSUE TITLE
Incorrect error messages on RRD architecture mismatch

### ISSUE THREAD

**Issue by moisseev** [rspamd/rspamd#1383]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
any

### Description (Please provide a descriptive summary of the issue):
When moving RRD between 32bit and 64bit architectures, incorrect error messages appear in the Rspamd log and WebUI.

### Expected results:
```
... csession; rspamd_controller_handle_graph: RRD was created on another architecture
```
```
Cannot receive throughput data: error 404 RRD was created on another architecture
```
### Actual results:
```
...; csession; rspamd_controller_handle_graph: no rrd configured
```
```
Cannot receive throughput data: error 404 No rrd configured for graphs
```

BTW Probably it should be `500` error instead of `404` as it is not a client error.

**Comment by vstakhov** [comment]
That will be quite hard to fix since RRD is opened before and independently from the graph command.
