### ISSUE TITLE
Backend UI Safari Browser Rendering

### ISSUE THREAD

**Issue by tleuxner** [rspamd/rspamd#1469]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.0
### Description (Please provide a descriptive summary of the issue):
UI columns and layout misplaced for Safari browsers in backend interface.

### Steps to reproduce:
Open backend in Safari/Safari Mobile (most current versions).

### Expected results:
Rendering was neat with previous 1.4.4 UI.

**Comment by fatalbanana** [comment]
Could you show a screenshot? And clarify which platforms/versions of Safari? It looks OK to me in 10.0.3 (11602.4.8.0.1) on OSX 10.11.6.

**Comment by tleuxner** [comment]
Sure. macOS 10.12.3 / Safari 10.0.3 (12602.4.8). iOS 10.2.1

It's most apparent on the symbol tab (attached)
![ui_macos_10_12_3](https://cloud.githubusercontent.com/assets/16303378/23546496/1b3e2dc2-0000-11e7-9b27-93e4925e5223.png)

**Comment by fatalbanana** [comment]
Seems to look better further to @andryyy's recent changes.

**Comment by tleuxner** [comment]
It looks a lot better now. Can only test with a Mobile Safari at the moment. I merged the git version interface directory. Not sure "Frequency" is work in progress under symbols, as it does not show values for now - all 0.00 (or is dependent on other changes).

**Comment by tleuxner** [comment]
On second thought, as the frequency was using a lot of decimals before, maybe this is due to new formatting n.nn. This way 0.001006 would not show at all like in the screenshot above for HAM. Shouldn't this be full numbers anyway e.g. 1006 HAM processed?

**Comment by fatalbanana** [comment]
Frequency appears to be hits/second, so possibly all could be near-zero.
