### ISSUE TITLE
History IP not working

### ISSUE THREAD

**Issue by mzummo** [rspamd/rspamd#1473]
web UI -> history 

IP Address column always shows 127.0.0.1 how is this fixed?

user always shows undefined as well

**Comment by fatalbanana** [comment]
If you're just scanning with `rspamc` it's expected. Does it scan actual mail? How do you integrate it? `User` will be populated if authenticated username was passed.

**Comment by mlzummo** [comment]
@fatalbanana im using the rmilter setup as described in the docs

**Comment by mlzummo** [comment]
would also be nice if we can see the to/from email address in the column?

**Comment by fatalbanana** [comment]
Have you correctly set [milter_mail_macros](https://rspamd.com/rmilter/)? (assuming you use Postfix)

You could check IP address passed to rspamd (or lack thereof) by capturing communication between rmitler and rspamd with `tcpflow` or similar, it should be the same address the mailer received the connection from.

**Comment by mlzummo** [comment]
@fatalbanana i agree that its probably not being passed (just not sure how to make sure it is passed correctly) ... is this something that needs to be set in master.cf?

**Comment by moisseev** [comment]
@mlzummo [Configuring Postfix](https://rspamd.com/doc/integration.html#configuring-postfix)

**Comment by mlzummo** [comment]
![image](https://cloud.githubusercontent.com/assets/1057527/23555297/69337546-fff6-11e6-8e37-4d2b37a1a098.png)

**Comment by mlzummo** [comment]
where client_addr (which is likely 127.0.0.1 being passed) and auth_authen is the authenticated username

**Comment by moisseev** [comment]
What is logged as the client IP in Postfix and Rmilter log?

**Comment by mlzummo** [comment]
Mar  3 11:41:32 TTT-mx-1 postfix/postscreen[2050]: CONNECT from [209.85.220.174]:35739 to [72.35.XX.XXX]:25
Mar  3 11:41:32 TTT-mx-1 postfix/dnsblog[2051]: addr 209.85.220.174 listed by domain dnsbl.sorbs.net as 127.0.0.6
Mar  3 11:41:32 TTT-mx-1 postfix/dnsblog[2058]: addr 209.85.220.174 listed by domain wl.mailspike.net as 127.0.0.18
Mar  3 11:41:32 TTT-mx-1 postfix/dnsblog[2051]: addr 209.85.220.174 listed by domain hostkarma.junkemailfilter.com as 127.0.0.1
Mar  3 11:41:32 TTT-mx-1 postfix/dnsblog[2051]: addr 209.85.220.174 listed by domain hostkarma.junkemailfilter.com as 127.0.0.3
Mar  3 11:41:32 TTT-mx-1 postfix/dnsblog[2051]: addr 209.85.220.174 listed by domain hostkarma.junkemailfilter.com as 127.0.1.1
Mar  3 11:41:32 TTT-mx-1 postfix/postscreen[2050]: PASS OLD [209.85.220.174]:35739
Mar  3 11:41:33 TTT-mx-1 postfix/smtpd[2059]: connect from mail-qk0-f174.google.com[209.85.220.174]
Mar  3 11:41:33 TTT-mx-1 rmilter[474]: <5a74585a8d>; accepted connection from TTT-mx-1.example.com; client: 209.85.220.174:35739 (mail-qk0-f174.google.com)
Mar  3 11:41:33 TTT-mx-1 postfix/smtpd[2059]: Anonymous TLS connection established from mail-qk0-f174.google.com[209.85.220.174]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Mar  3 11:41:33 TTT-mx-1 postfix/smtpd[2059]: NOQUEUE: client=mail-qk0-f174.google.com[209.85.220.174]
Mar  3 11:41:33 TTT-mx-1 rmilter[474]: <5a74585a8d>; mlfi_data: cannot get queue id, set to 'NOQUEUE'
Mar  3 11:41:34 TTT-mx-1 postfix/smtpd[2081]: connect from localhost[127.0.0.1]
Mar  3 11:41:34 TTT-mx-1 rmilter[474]: <cd3e917563>; accepted connection from TTT-mx-1.example.com; client: 127.0.0.1:54852 (localhost)
Mar  3 11:41:34 TTT-mx-1 postfix/cleanup[2082]: error: open /etc/postfix/header_checks: No such file or directory
Mar  3 11:41:34 TTT-mx-1 postfix/smtpd[2081]: C4F9B2A1248: client=localhost[127.0.0.1], orig_client=mail-qk0-f174.google.com[209.85.220.174]
Mar  3 11:41:34 TTT-mx-1 rmilter[474]: <cd3e917563>; mlfi_data: queue id: <C4F9B2A1248>
Mar  3 11:41:34 TTT-mx-1 postfix/cleanup[2082]: C4F9B2A1248: message-id=<CAB4+Ve6Mwt11-B5GskE+nwVYigSoXAkCiR4UTgV0Z-Jz2zB5hQ@mail.gmail.com>
Mar  3 11:41:34 TTT-mx-1 rmilter[474]: <cd3e917563>; mlfi_eom: tempfile=/tmp/msg.XXaEDINC, size=3303
Mar  3 11:41:34 TTT-mx-1 rmilter[474]: <cd3e917563>; spamdscan: start scanning message on 127.0.0.1
Mar  3 11:41:34 TTT-mx-1 rmilter[474]: <cd3e917563>; spamdscan: finish scanning message on 127.0.0.1
Mar  3 11:41:34 TTT-mx-1 rmilter[474]: <cd3e917563>; spamdscan: scan, time: 0.019, server: 127.0.0.1, metric: default: [0.400 / 15.000], symbols: PREVIOUSLY_DELIVERED(0.00)[test@example.com], FROM_EQ_ENVFROM(0.00)[], TO_MATCH_ENVRCPT_ALL(0.00)[], RCVD_COUNT_5(0.00)[], FREEMAIL_FROM(0.00)[gmail.com], R_PARTS_DIFFER(0.50)[100.0%], FROM_HAS_DN(0.00)[], FREEMAIL_ENVFROM(0.00)[gmail.com], RCPT_COUNT_1(0.00)[], MIME_GOOD(-0.10)[multipart/alternative, text/plain], TO_DN_ALL(0.00)[]
Mar  3 11:41:34 TTT-mx-1 rmilter[474]: <cd3e917563>; msg done: queue_id: <C4F9B2A1248>; message id: <CAB4+Ve6Mwt11-B5GskE+nwVYigSoXAkCiR4UTgV0Z-Jz2zB5hQ@mail.gmail.com>; ip: 127.0.0.1; from: <test-user@gmail.com>; rcpt: <test@example.com> (1 total); user: unauthorized; spam scan: no spam; virus scan: skipped, no av servers; dkim: not signed, ignored
Mar  3 11:41:34 TTT-mx-1 postfix/qmgr[1566]: C4F9B2A1248: from=<test-user@gmail.com>, size=3406, nrcpt=1 (queue active)
Mar  3 11:41:34 TTT-mx-1 amavis[1626]: (01626-01) Passed CLEAN {RelayedInbound}, [209.85.220.174]:35739 [209.85.220.174] <test-user@gmail.com> -> <test@example.com>, Message-ID: <CAB4+Ve6Mwt11-B5GskE+nwVYigSoXAkCiR4UTgV0Z-Jz2zB5hQ@mail.gmail.com>, mail_id: hiSih20VPFNW, Hits: -0.117, size: 2560, queued_as: C4F9B2A1248, 1332 ms
Mar  3 11:41:34 TTT-mx-1 dovecot: lmtp(2084): Connect from local
Mar  3 11:41:34 TTT-mx-1 postfix/smtpd[2059]: proxy-accept: END-OF-MESSAGE: 250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as C4F9B2A1248; from=<test-user@gmail.com> to=<test@example.com> proto=ESMTP helo=<mail-qk0-f174.google.com>
Mar  3 11:41:34 TTT-mx-1 dovecot: lmtp(2084, test@example.com): EQ6bN76cuVgkCAAAApY8PQ: sieve: msgid=<CAB4+Ve6Mwt11-B5GskE+nwVYigSoXAkCiR4UTgV0Z-Jz2zB5hQ@mail.gmail.com>: stored mail into mailbox 'INBOX'
Mar  3 11:41:34 TTT-mx-1 postfix/smtpd[2059]: disconnect from mail-qk0-f174.google.com[209.85.220.174]
Mar  3 11:41:35 TTT-mx-1 dovecot: lmtp(2084): Disconnect from local: Successful quit
Mar  3 11:41:35 TTT-mx-1 postfix/lmtp[2083]: C4F9B2A1248: to=<test@example.com>, relay=TTT-mx-1.example.com[private/dovecot-lmtp], delay=0.22, delays=0.1/0.03/0.02/0.07, dsn=2.0.0, status=sent (250 2.0.0 <test@example.com> EQ6bN76cuVgkCAAAApY8PQ Saved)
Mar  3 11:41:35 TTT-mx-1 postfix/qmgr[1566]: C4F9B2A1248: removed
Mar  3 11:42:03 TTT-mx-1 dovecot: imap-login: Login: user=<test@example.com>, method=PLAIN, rip=::1, lip=::1, mpid=2116, secured, session=<BIGyOdZJLwAAAAAAAAAAAAAAAAAAAAAB>
Mar  3 11:42:03 TTT-mx-1 dovecot: imap(test@example.com): Disconnected: Logged out in=383 out=15879
Mar  3 11:42:29 TTT-mx-1 dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=50.240.52.123, lip=72.35.XX.XXX, TLS: Disconnected, session=<UFA9O9ZJUAAy8DR7>
Mar  3 11:42:29 TTT-mx-1 dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=50.240.52.123, lip=72.35.XX.XXX, TLS: Disconnected, session=<HG1BO9ZJIwAy8DR7>
Mar  3 11:42:31 TTT-mx-1 dovecot: imap-login: Aborted login (auth failed, 1 attempts in 2 secs): user=<mail.example.com>, method=PLAIN, rip=50.240.52.123, lip=72.35.XX.XXX, TLS, session=<xAlGO9ZJrAAy8DR7>
Mar  3 11:43:03 TTT-mx-1 dovecot: imap-login: Login: user=<test@example.com>, method=PLAIN, rip=::1, lip=::1, mpid=2171, secured, session=<z1pMPdZJTQAAAAAAAAAAAAAAAAAAAAAB>
Mar  3 11:43:03 TTT-mx-1 dovecot: imap(test@example.com): Disconnected: Logged out in=139 out=1918
Mar  3 11:43:12 TTT-mx-1 postfix/postscreen[2050]: close database /var/lib/postfix/postscreen_cache.db: No such file or directory (possible Berkeley DB bug)
Mar  3 11:43:35 TTT-mx-1 dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=50.240.52.123, lip=72.35.XX.XXX, TLS: Disconnected, session=<Vqc0P9ZJXAAy8DR7>
Mar  3 11:43:35 TTT-mx-1 dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=50.240.52.123, lip=72.35.XX.XXX, TLS: Disconnected, session=<QYo1P9ZJWgAy8DR7>
Mar  3 11:43:38 TTT-mx-1 dovecot: imap-login: Aborted login (auth failed, 1 attempts in 2 secs): user=<mail.example.com>, method=PLAIN, rip=50.240.52.123, lip=72.35.XX.XXX, TLS, session=<rHU4P9ZJ5wAy8DR7>
Mar  3 11:44:04 TTT-mx-1 dovecot: imap-login: Login: user=<test@example.com>, method=PLAIN, rip=::1, lip=::1, mpid=2255, secured, session=<ybPoQNZJdQAAAAAAAAAAAAAAAAAAAAAB>
Mar  3 11:44:04 TTT-mx-1 dovecot: imap(test@example.com): Disconnected: Logged out in=139 out=1918
Mar  3 11:44:39 TTT-mx-1 dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=50.240.52.123, lip=72.35.XX.XXX, TLS: Disconnected, session=<mPEBQ9ZJGQAy8DR7>
Mar  3 11:44:39 TTT-mx-1 dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=50.240.52.123, lip=72.35.XX.XXX, TLS: Disconnected, session=<duoEQ9ZJhQAy8DR7>
Mar  3 11:44:42 TTT-mx-1 dovecot: imap-login: Aborted login (auth failed, 1 attempts in 2 secs): user=<mail.example.com>, method=PLAIN, rip=50.240.52.123, lip=72.35.XX.XXX, TLS, session=<S3EJQ9ZJJQAy8DR7>
Mar  3 11:44:55 TTT-mx-1 postfix/anvil[2062]: statistics: max connection rate 1/60s for (smtpd:209.85.220.174) at Mar  3 11:41:33
Mar  3 11:44:55 TTT-mx-1 postfix/anvil[2062]: statistics: max connection count 1 for (smtpd:209.85.220.174) at Mar  3 11:41:33
Mar  3 11:44:55 TTT-mx-1 postfix/anvil[2062]: statistics: max cache size 1 at Mar  3 11:41:33
Mar  3 11:45:03 TTT-mx-1 dovecot: imap-login: Login: user=<test@example.com>, method=PLAIN, rip=::1, lip=::1, mpid=2319, secured, session=<dbJsRNZJkAAAAAAAAAAAAAAAAAAAAAAB>
Mar  3 11:45:03 TTT-mx-1 dovecot: imap(test@example.com): Disconnected: Logged out in=139 out=1918


(domains/emails replaced for anonymity)

**Comment by mlzummo** [comment]
r  3 11:41:34 jjl-mx-1 postfix/smtpd[2081]: C4F9B2A1248: client=localhost[127.0.0.1], orig_client=mail-qk0-f174.google.com[209.85.220.174]

is it not reading the orig_client?
