### ISSUE TITLE
Read map file many errors

### ISSUE THREAD

**Issue by AlexeySa** [rspamd/rspamd#1474]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.1 (git)

### Operation system, CPU, memory and environment:
Centos 6.8 x64

### Description (Please provide a descriptive summary of the issue):
I am get errors after start rspamd (log level "warning"):
rspamd[314244]: <jj87b9>; map; read_map_file: map file is unavailable for reading
rspamd[314243]: <emf1n5>; map; read_map_file: map file is unavailable for reading
rspamd[314245]: <jj87b9>; map; read_map_file: map file is unavailable for reading
rspamd[314245]: <emf1n5>; map; read_map_file: map file is unavailable for reading
rspamd[314248]: <bf4sun>; map; read_map_file: map file is unavailable for reading

If level = "debug" no this error.

Please help.

**Comment by fatalbanana** [comment]
You will see this **on startup** for map files that don't exist (which is expected):

```2017-03-02 12:46:15 #16872(fuzzy) <35rhob>; map; rspamd_map_file_read_callback: rereading map file /etc/rspamd/local.d/mid.inc
2017-03-02 12:46:15 #16872(fuzzy) <35rhob>; map; read_map_file: map file is unavailable for reading```

**Comment by AlexeySa** [comment]
I understood in what a problem. Rspamd put error if map file is empty.

```
map; read_map_file: can't open map /usr/local/rspamd/etc/rspamd/local.d/redirectors.inc: Success
```

```
stat /usr/local/rspamd/etc/rspamd/local.d/redirectors.inc
  File: `/usr/local/rspamd/etc/rspamd/local.d/redirectors.inc'
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
```

**Comment by moisseev** [comment]
@AlexeySa You can add a commented line as workaround.

**Comment by neuraload** [comment]
I'm getting this if map file is empty. Should be ignored if its empy imo.

csession; rspamd_controller_handle_get_map: cannot read map /etc/rspamd/local.d/blacklist.domain.map: Invalid argument

**Comment by LucaDev** [comment]
Looking forward to getting this fixed! It's really annoying...

**Comment by stephdl** [comment]
Is it possible to make a PR concerning these map to the GH rspamd repository, what are the drawbacks if you did not do it before ?
