### ISSUE TITLE
Documentation request: Rspamd as an antispam gateway

### ISSUE THREAD

**Issue by MrDrMcCoy** [rspamd/rspamd#1542]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [X] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [X] Not applicable

### Description (Please provide a descriptive summary of the issue):

Most of the documentation for Rspamd is centered around a direct integration with one's email server. For situations where the email server cannot be modified, it would be helpful to have Rspamd configured as a separate box that forwards clean messages to wherever the real email server lives. Essentially, I am looking for enough information to build my own Rspamd-based [EFA](https://efa-project.org/). I'm sure such instructions would be useful to lots of people.

**Comment by vstakhov** [comment]
You still need MTA in this mode. I don't understand what are you looking for.

**Comment by fatalbanana** [comment]
This is MTA-specific indeed. Exim configuration for a filtering gateway using Rspamd could look something like [this](http://org.org.za/exim-configs/exim-filtering-gw.conf).

**Comment by MrDrMcCoy** [comment]
@vstakhov I realize that an MTA would still be required, as Postfix is a part of the [EFA](https://efa-project.org/) example I gave. However, EFA does not have an MDA like Dovecot, and messages that EFA's SpamAssassin decides are clear are passed along to another MTA. What I am looking for is enough documentation to set up something like this with Rspamd.

@fatalbanana I'm not super familiar with Exim's configuration. Am I correct in my reading that `  route_list = "* 192.168.100.1 byname"` is the line that forwards to another MTA?

**Comment by fatalbanana** [comment]
@MrDrMcCoy yes; if you're interested in using Exim I'd recommend getting hands on the [book](https://www.uit.co.uk/the-exim-smtp-mail-server), which provides a very good introduction and covers the majority of information contained in the [spec](http://www.exim.org/exim-html-current/doc/html/spec_html/) - which is not as good a read but is freely available and could tell you roughly all there is to know.

How mail is ultimately handled is up to MTA and/or Rmilter/similar. Rspamd merely makes a recommendation based on its opinion of a message, which does not have to be interpreted literally. How to achieve your desired setup will vary according to each MTA/integration method.

**Comment by smfreegard** [comment]
@MrDrMcCoy - EFA uses MailScanner, which integrates SpamAssassin, to use RSpamd instead, you'll need to write a MailScanner 'Custom Spam Scanner' of which examples exist in the MailScanner documentation.

**Comment by fatalbanana** [comment]
That won't work well without some efforts; Rspamd would like to have a little [more metadata](https://rspamd.com/doc/architecture/protocol.html#http-headers) than seems to be [available for this purpose](https://www.mailscanner.info/MailScanner.conf.index.html#Use%20Custom%20Spam%20Scanner).

**Comment by vstakhov** [comment]
In fact, it can extract something from the Received headers if needed.

**Comment by smfreegard** [comment]
Indeed - however having just looked at the MailScanner code that calls this, it's easy to extend it to pass additional metadata items.
