### ISSUE TITLE
[Enhancement] DMARC Reporting: add receiving domain from "to"-Header

### ISSUE THREAD

**Issue by wackerm** [rspamd/rspamd#1544]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [x] Enhancement

### DMARC Reporting: add receiving domain from "to"-Header

I am using the build in dmarc redis feature and i am implementing a simple report generator script with php.
But now i miss some important details in the dmarc entries in redis: the domain/subdomain of the receiving address ("to" address from email header/envelope).
At the moment the redis list for the dmarc entries has the following fields:

> unixtime,ip,spf_result,dkim_result,dmarc_disposition

Since i am using multi-domain setup i need to know the receiving domain for which the dmarc report should be generated.

The simplest solution would be to add the receiving domain (including subdomain if used) as another field to the list. Of course this change would grow the size in redis since a lot of entries will have the same domain values.

This is also necessary to fullfill the necessary information in the report:

> The report SHOULD include the following data:
> 
> - Enough information for the report consumer to re-calculate DMARC disposition based on the published policy, message dispositon, and SPF, DKIM, and identifier alignment results. {R12}
> - Data for each sender subdomain separately from mail from the sender's organizational domain, even if no subdomain policy is applied. {R13}
> - Sending and receiving domains {R17}
> - The policy requested by the Domain Owner and the policy actually applied (if different) {R18}
> - The number of successful authentications {R19}
> - The counts of messages based on all messages received even if their delivery is ultimately blocked by other filtering agents {R20}

https://dmarc.org/draft-dmarc-base-00-01.html#fb_aggregate

**Comment by fatalbanana** [comment]
DMARC reporting stuff could use improvement (and a reporting tool) indeed. It might be done for Google Summer of Code this year.
