### ISSUE TITLE
[webUI] Uncaught TypeError: Cannot use 'in' operator to search for 'config_id' in <!DOCTYPE html>

### ISSUE THREAD

**Issue by Siebjee** [rspamd/rspamd#1552]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [X] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.3-2~trusty

### Operation system, CPU, memory and environment:
Ubuntu 14.04.3 LTS, 8Cores, 16GB memory

### Description (Please provide a descriptive summary of the issue):
After changing spam values in the webUI > Config, it started to throw errors in the console.

### Steps to reproduce:
Change any number of value in the webui > config. And click save.

### Expected results:
Values changed, and no errors in console.

### Actual results:
Values unchanged, and console full of errors.

### Configuration:
Configuration as described throuhg: https://rspamd.com/doc/quickstart.html

### Additional information:
Did a complete purge of rspamd, and reinstalled it. No change.

console log:

```
stats.js:105 Uncaught TypeError: Cannot use 'in' operator to search for 'config_id' in <!DOCTYPE html>
[...]
    at Object.<anonymous> (/js/app/stats.js:105)
    at Function.each (/js/lib/jquery-3.1.1.min.js:2)
    at displayStatWidgets (/js/app/stats.js:102)
    at rspamd.queryNeighbours.alert_status (/js/app/stats.js:219)
    at Object.success (/js/app/rspamd.js:403)
    at i (/js/lib/jquery-3.1.1.min.js:2)
    at Object.fireWith [as resolveWith] (/js/lib/jquery-3.1.1.min.js:2)
    at A (/js/lib/jquery-3.1.1.min.js:4)
    at XMLHttpRequest.<anonymous> (/js/lib/jquery-3.1.1.min.js:4)
```

**Comment by andryyy** [comment]
Does the URL look like *rspamd/#something when this happens?

**Comment by Siebjee** [comment]
As it turns out, its something in the cookie or cache that is preventing the webui to work.
Clearing cache, cookies and a full browser restart solved the issue for me.

However, changing values again causes the same symptoms. And the same fix stated above fixes the webui again. But the values changed in the configuration aren't changed.

To answer your question, no. The URL doesnt change. I don't have the folder setup, i enabled a new sub-domain just for the interface.

**Comment by fibis** [comment]
@andryyy yes this problem comes with *rspamd/#something always in my mailcow installation

**Comment by vslinuxdotnet** [comment]
Hello, just to say that this issue still exists.

**Comment by JensErat** [comment]
Also experiencing this issue. Looking into Session Storage, I can see `Credentials.local.data` has the rspamd index page contained (which you would usually get through accessing `<url>/`).

I can confirm this happens if the URI ended in `/`, and it works again (without deleting cache/session cookies) when requesting the URI without `/`. In firebug's network pane, I see interesting requests on the neighbors endpoint (returning the empty dict `{}`) and after that a request to `/` which returns the index page then stored in `local.data`.
