### ISSUE TITLE
[FEATURE] Webhooks for 3rd party services like Sendgrid / Mandrill

### ISSUE THREAD

**Issue by JonTheWong** [rspamd/rspamd#1560]
### Classification (Please choose *one* option):
* [ X ] Feature

### Reproducibility (Please choose *one* option):
* [x] Not applicable

### Rspamd version:
Ideally the next version >:)

### Description (Please provide a descriptive summary of the issue):
This might be outside the score of this project.
But since i'm trying to integrate rspamd as not just a spam filter but as a full filtering system (using redis scores and other data to eventually match with different kinds of rbls and 3rd party data)

I'd like to have rspam support incoming web hooks for systems like send grid.
https://sendgrid.com/docs/API_Reference/Webhooks/inbound_email.html

This would allow send grids SPAM filtering to post what they block to rspamd.
Centralizing spam logs.

### Expected results:
Login in to Sendgrid; Settings; Mail Settings -> Spam Checker
URL TO POST SPAM MESSAGES TO -> http://rspamd:11334/webhook/sendgrid

When logging in to rspamd web gui / have a new tab "external results"
With a list of received messages that were blocked by outgoing Sendgrid Spam checking.

**Comment by vstakhov** [comment]
I don't understand this issue. Rspamd can query external services using `lua_http` or `lua_tcp`. There are no plans to add something like webhooks in the WebUI.
