### ISSUE TITLE
Incorrect url_len in hfilter.lua plugin

### ISSUE THREAD

**Issue by moisseev** [rspamd/rspamd#1565]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.5-git.aae8be4

### Steps to reproduce:
```
# rspamc
MIME-Version: 1.0
Content-Type: text/plain

www.example.com
Results for file: stdin (2.913 seconds)
[Metric: default]
Spam: true
Score: 23.73 / 15.00
Action: reject
Symbol: DMARC_NA (0.00)[No From header]
Symbol: HFILTER_URL_ONELINE (2.50)[plain:1:1]
Symbol: HFILTER_URL_ONLY (11.82)[1.875]
...
```
`rel=1.875` is way too much
`url_len=30` > `plen=16`

**Comment by fatalbanana** [comment]
This is `((url_len / plen_len) - 0.8) * 5`.

**Comment by fatalbanana** [comment]
I don't suppose that's fixed.
