### ISSUE TITLE
what's the utility of the BAD_CTE_7BIT check?

### ISSUE THREAD

**Issue by fauno** [rspamd/rspamd#1590]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

1.5.3

### Operation system, CPU, memory and environment:

Parabola GNU/Linux-libre

### Description (Please provide a descriptive summary of the issue):

While helping loomio debug why some of their email notifications are being classified as spam by rspamd, I found multipart emails with mixed Content-Transfer-Encoding headers are given 3 points for BAD_CTE_7BIT.  For instance, main CTE is set as 7bit and also the text/plain part, but the text/html is quoted-printable.  I don't understand much C but I think it's because of the mixed CTE headers? If that's so, I looked for some github notifications with non-ascii characters and I found they were also given this score because of main CTE 7bit and both parts being quoted-printable.  Is this a bad practice on their side? I couldn't find any recommendation otherwise (I don't know the proper RFCs)

References:

* https://github.com/loomio/loomio/issues/4022
* https://github.com/loomio/loomio/pull/4023
* https://github.com/vstakhov/rspamd/blob/master/src/libmime/mime_expressions.c#L1277

### Steps to reproduce:

Look for Content-Transfer-Encoding and X-Spamd-Result headers 

### Configuration:

Stock configuration

**Comment by gdpelican** [comment]
@vstakhov Can this be considered resolved with the new commits? What was the issue to begin with?
