### ISSUE TITLE
[Feature request] Print warning at startup for unknown config files

### ISSUE THREAD

**Issue by croessner** [rspamd/rspamd#1598]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [X] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

If you have several files under /etc/rspamd/local.d, ...override.d or even some files just known in ending of .local or .override, it would be very helpful to pront out a warning or to log to syslog, if config files are unknown and not used.

Examples for doing it wrong:

statistic.conf <-> statistics.conf
force_action.conf <-> force_actions.conf

Even *.inc versus *,conf typos

**Comment by vstakhov** [comment]
Rspamd has no such thing as embedded files list. Hence, there is no way to do it without some ugly hacks.

**Comment by mpizzoli** [comment]
In the feature request I would add the request to log files not loaded due
to the missing read permissions... I fell in that issue at least twice...

Thanks
Marco

**Comment by croessner** [comment]
Maybe ths could be a task for "rspamadm configtest". It could load the default config file and follow all includes. That way it would build a tree containing several (hopefully all) config files. Then it could diff it to the real file list (some kind of globbing inside $LOCAL_CONF.

Not sure about the modules.d folder while writing here...

But maybe this would be a solution, is it?

**Comment by vstakhov** [comment]
There is no sollution to do it in a straightforward way. Why not write some perl/shell/lua script for these purposes? Fixing of sysadmins mistakes is not Rspamd task.

**Comment by croessner** [comment]
Good point. I think I could do this in Python. I will think about it...
