### ISSUE TITLE
Autolearning with Redis backend fails with "Unknown statistics error"

### ISSUE THREAD

**Issue by mundschenk-at** [rspamd/rspamd#1617]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.5.7

### Operation system, CPU, memory and environment:
FreeBSD 11, Intel Xeon E3-1275, 64 GB

### Description (Please provide a descriptive summary of the issue):
Autolearning bayes statistics with Redis backend fails with `learn error: Unknown statistics error`. Manual learning via `rspamc` seems to work fine.

### Steps to reproduce:
Statistics module set up for Redis according to [documentation](https://rspamd.com/doc/configuration/statistic.html). Initial training via `rspamc` was successful. Output of `rspamc stat`:

```
Results for command: stat (0.001 seconds)
Messages scanned: 79
Messages with action reject: 17, 21.52%
Messages with action soft reject: 0, 0.00%
Messages with action rewrite subject: 0, 0.00%
Messages with action add header: 3, 3.80%
Messages with action greylist: 2, 2.53%
Messages with action no action: 57, 72.15%
Messages treated as spam: 20, 25.32%
Messages treated as ham: 59, 74.68%
Messages learned: 1581
Connections count: 533
Control connections count: 12
Pools allocated: 1723
Pools freed: 1787
Bytes allocated: 3.99G
Memory chunks allocated: 4294966478
Shared chunks allocated: 30
Chunks freed: 0
Oversized chunks: 261
Fuzzy hashes in storage "rspamd.com": 366296987
Fuzzy hashes stored: 366296987
Statfile: BAYES_SPAM type: redis; length: 11.24M; free blocks: 0; total blocks: 295.76k; free: 0.00%; learned: 1012; users: 1; languages: 0
Statfile: BAYES_HAM type: redis; length: 7.36M; free blocks: 0; total blocks: 193.78k; free: 0.00%; learned: 657; users: 1; languages: 0
Total learns: 1669
```
(`Messages scanned` seems to reset with every config reload, is this intended?)

### Expected results:
Successful autolearning of spam and ham.

### Actual results:
All autolearning actions in the logfile look like this:
```
2017-05-07 13:52:15 #24276(normal) <f0d8bc>; task; rspamd_stat_check_autolearn: <20170507115215.A92CA5BFF50@some.domain>: autolearn ham for classifier 'bayes' as message's score is negative: -10.00
2017-05-07 13:52:15 #24276(normal) <f0d8bc>; task; rspamd_task_process: learn error: Unknown statistics error
```

### Configuration:
`local.d/statistics.conf` looks like this:
```
classifier "bayes" {
    tokenizer {
        name = "osb";
    }

    backend = "redis";
    # servers = "127.0.0.1:6379";
    servers = "/var/run/redis/redis.sock";
    min_tokens = 11;
    min_learns = 200;
    autolearn = true;

    per_user = <<EOD
return function(task)
    local rcpt = task:get_recipients(1)

if rcpt then
    local one_rcpt = rcpt[1]
    if one_rcpt['domain'] then
        return one_rcpt['domain']
    end
end

return nil
end
EOD

    statfile {
        symbol = "BAYES_HAM";
        spam = false;
    }
    statfile {
        symbol = "BAYES_SPAM";
        spam = true;
    }
    learn_condition =<<EOD
return function(task, is_spam, is_unlearn)
    local prob = task:get_mempool():get_variable('bayes_prob', 'double')

    if prob then
        local in_class = false
        local cl
        if is_spam then
            cl = 'spam'
            in_class = prob >= 0.95
        else
            cl = 'ham'
            in_class = prob <= 0.05
        end

        if in_class then
            return false,string.format('already in class %s; probability %.2f%%',
            cl, math.abs((prob - 0.5) * 200.0))
        end
    end

    return true
end
EOD
}
```

**Comment by fatalbanana** [comment]
Do you have global redis settings too?

I was unable to replicate it.

**Comment by mundschenk-at** [comment]
Yes, there are global redis settings (to the same Redis instance). From reading the documentation, I was under the impression that the statistics module is an exception and does not use the global settings?

**Comment by fatalbanana** [comment]
There is no such exception these days. Given settings are consistent I don't see any probable issue there.

**Comment by mundschenk-at** [comment]
Ah. Then the docs should probably be [modified accordingly](https://github.com/vstakhov/rspamd.com/blame/master/doc/configuration/redis.md#L84).

Anyway, as for actual problem, is there any way to gain more information about what exactly is going wrong? I've already enabled logging for the `lua` and `statistics` modules, but those two lines are all I get (around the error situation, all in all, Rspamd can be quite talkactive ;).

**Comment by mundschenk-at** [comment]
`local.d/redis.conf` contains just this line:

```
servers = "/var/run/redis/redis.sock";
```

I tried running `redis-cli monitor`, but I can't make sense of the output. I didn't see any `SET`-like commands for the `BAYES_*`keys when I sent a sample ham mail (just a lot of `HLEN` and `HGET`.

**Comment by smfreegard** [comment]
I've just hit this problem too.   I'm using redis.conf in local.d for the first time - I've commented out the servers= section in statistic.conf and now I'm seeing the `Unknown statistics error`.

**Comment by smfreegard** [comment]
If it helps - I see this output in the logs:

`````
May 09 16:28:43 mx-sfo2-01 rspamd[19559]: (controller) <584f8n>; cfg; rspamd_redis_init: cannot init redis backend for BAYES_HAM
May 09 16:28:43 mx-sfo2-01 rspamd[19559]: (controller) <584f8n>; cfg; rspamd_stat_cache_redis_init: cannot init redis cache for BAYES_HAM
May 09 16:28:43 mx-sfo2-01 rspamd[19559]: (controller) <584f8n>; cfg; rspamd_stat_init: error adding cache redis for symbol BAYES_HAM
May 09 16:28:43 mx-sfo2-01 rspamd[19559]: (controller) <584f8n>; cfg; rspamd_stat_init: cannot init backend redis for statfile BAYES_HAM
May 09 16:28:43 mx-sfo2-01 rspamd[19559]: (controller) <584f8n>; cfg; rspamd_redis_init: cannot init redis backend for BAYES_SPAM
May 09 16:28:43 mx-sfo2-01 rspamd[19559]: (controller) <584f8n>; cfg; rspamd_stat_cache_redis_init: cannot init redis cache for BAYES_SPAM
May 09 16:28:43 mx-sfo2-01 rspamd[19559]: (controller) <584f8n>; cfg; rspamd_stat_init: error adding cache redis for symbol BAYES_SPAM
May 09 16:28:43 mx-sfo2-01 rspamd[19559]: (controller) <584f8n>; cfg; rspamd_stat_init: cannot init backend redis for statfile BAYES_SPAM
May 09 16:28:43 mx-sfo2-01 rspamd[19559]: (controller) <mb4rmx>; map; read_map_file: map file is unavailable for reading
`````

**Comment by mundschenk-at** [comment]
@fatalbanana I've tried enabling some additional logging and get the following output:

```
2017-05-09 22:39:14 #4313(normal) <4f7f8e>; task; rspamd_stat_check_autolearn: <20170509203914.C0CF3468A5@some.domain>: autolearn ham for classifier 'bayes' as message's score is negative: -10.00
2017-05-09 22:39:14 #4313(normal) <4f7f8e>; task; rspamd_task_process: completed stage 512
2017-05-09 22:39:14 #4313(normal) <4f7f8e>; task; rspamd_task_process: need more work on stage 1024
2017-05-09 22:39:14 #4313(normal) <4f7f8e>; bayes; bayes_learn_spam: token 5100525729652893600 <could:messag>: window: 2, total_count: 1, spam_count: 0, ham_count: 1

[...]

2017-05-09 22:39:14 #4313(normal) <4f7f8e>; bayes; bayes_learn_spam: token 2657955434382563728 <multipart/report; report-type=delivery-status; boundary="65B2C46895.1494362354/some.domain":english>: window: 5, total_count: 1, spam_count: 0, ham_count: 1
2017-05-09 22:39:14 #4313(normal) <4f7f8e>; task; rspamd_task_process: learn error: Unknown statistics error
2017-05-09 22:39:14 #4313(normal) <4f7f8e>; task; rspamd_task_process: task is processed
```

**Comment by mundschenk-at** [comment]
I've grepped through more log files and it might be that the problem only occurs with bounce messages (that are filtered for signing mainly). Is it possible that the learning functions don't like the empty envelope of bounce messages?

**Comment by mundschenk-at** [comment]
Do you still need additional information for this?

**Comment by mundschenk-at** [comment]
It looks like the error does not occur anymore (noted as of Rspamd 1.9.4, but probably since an earlier version).

**Comment by Progressed36** [comment]
The error does occur. 
`2020-04-22 19:18:34 #6651(normal) <093e95>; task; rspamd_stat_backends_learn: no runtime for backend redis; classifier bayes; symbol BAYES_SPAM
2020-04-22 19:18:34 #6651(normal) <093e95>; task; rspamd_stat_backends_learn: no runtime for backend redis; classifier bayes; symbol BAYES_HAM
2020-04-22 19:18:34 #6651(normal) <093e95>; task; rspamd_task_process: learn error: Unknown statistics error, found when storing data on backend; classifier: bayes
`

**Comment by t0rzz** [comment]
Still happening with very latest version of rspam on Debian 10.

`learn error: Unknown statistics error, found when storing data on backend; classifier: bayes`

Backend is redis and it was working with the previous version of rspam. Also every configuration file is fine, as it was before the update.

**Comment by DiveSurfer** [comment]
I also get this message displayed. "learn error: Unknown statistics error, found when storing data on backend; classifier: bayes"

Rspamd daemon version 2.5
Ubuntu 18.04.4 LTS

**Comment by TheBilism** [comment]
Solution writed on directadmin forums for redis.
[Cllick Here](https://forum.directadmin.com/threads/release-rspamd-web-interface-plugin-for-directadmin-v0-1.57856/page-3#post-304480)


yum install -y redis
nano -w /etc/redis.conf (uncomment requirepass and set a password to it)
systemctl restart redis

nano -w /etc/rspamd/local.d/redis.conf
Code:
  servers = "127.0.0.1"; # Read servers (unless write_servers are unspecified)
  write_servers = "127.0.0.1"; # Servers to write data
  disabled_modules = ["ratelimit"]; # List of modules that should not use redis from this section
  timeout = 1s;
  db = "0";
  password = "replace_with_the_password_you_set_in_redis_config";
systemctl restart rspamd

**Comment by mundschenk-at** [comment]
I also noticed the error still occurs with rspamd 2.5, but much less often.

**Comment by skroczek** [comment]
It seems to me that when the Bayes filter is disabled due to a user setting, this error occurs.
I have this setting that I try to use to disable the Bayes filter for non-system/foreign domains:

```
# File: /etc/rspamd/local.d/settings.conf
# [...]
# Disable some checks for authenticated users
authenticated {
        priority = high;
        authenticated = yes;
        apply {
                groups_disabled = ["rbl", "spf"];
                # The attempt to disable the bayes filter for foreign domains.
                symbols_disabled = ["BAYES_SPAM", "BAYES_HAM"];
        }
}
# [...]
```

And as far as I can see the error always happens when this rule also applies. Can anyone confirm this?
