### ISSUE TITLE
DKIM / DKIM_SIGNING: Multiple signing feature

### ISSUE THREAD

**Issue by mpizzoli** [rspamd/rspamd#1692]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.1

### Operation system, CPU, memory and environment:
RHEL7

### Description (Please provide a descriptive summary of the issue):
I would like to dkim-sign my emails at least twice. 
Reason for this is:
1. I have to comply with an external requirement asking me to sign according to their specifications
2. I want to sign according to a relaxed set of headers safer in case of email mangling by receivers: subject editing, etc...

### Compile errors (if any):
N/A

### Steps to reproduce:
Try to sign a single email twice

### Expected results:
An email signed twice, with different keys and/or different (d=)domain and/or with a different signed header-set (Issue #1691)

### Actual results:
No way to sign emails more than once

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
N/A

### Configuration:
N/A

### Additional information:
N/A

**Comment by vstakhov** [comment]
There is no support of multiple signing in Rspamd. You can pass a message twice with some help of lua and `sign_condition`.

**Comment by mpizzoli** [comment]
Excuse me @vstakhov, could you tell me if this feature is something you are going to implement in a future  release? Just to understand if I need to start investigating the work-around you suggested or I can wait for it. Thank you

**Comment by vstakhov** [comment]
I have no plans to implement it since I don't think this is useful for somebody else but in your particular case.

**Comment by mpizzoli** [comment]
Hi Vsevolod,
I found another important use case for the multiple signing feature: Gmail's Feedback Loop.
Its implementation is different than others': https://www.sparkpost.com/blog/all-you-need-to-know-about-gmail-feedback-loop-offering/
It is required the ESP's signature is added to the original one.
