### ISSUE TITLE
proxy_milter: error: invalid macro command (no name)

### ISSUE THREAD

**Issue by tleuxner** [rspamd/rspamd#1708]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [X] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

`1.6.2-0~git6~fd74eaf0d~jessie`

### Description (Please provide a descriptive summary of the issue):

```
Jun 25 21:43:05 edi rspamd[3474]: <79f08b>; proxy; proxy_accept_socket: accepted milter connection from /var/spool/postfix/public/rspamd port 0
Jun 25 21:43:05 edi rspamd[3474]: <79f08b>; milter; rspamd_milter_process_command: got connection from [2001:41b8:202:deb:216:36ff:fe40:4002]:47462
Jun 25 21:43:05 edi rspamd[3474]: <79f08b>; proxy; proxy_milter_error_handler: abnormally closing milter connection from: /var/spool/postfix/public/rspamd, error: invalid macro command (no name)
```

`Jun 25 21:43:05 edi postfix/smtpd-in/cleanup[31978]: warning: milter unix:public/rspamd: can't read SMFIC_BODYEOB reply packet header: Connection reset by peer`

### Additional information:

Mails affected by this issue will not be scanned and passed to Postfix without Rspamd processing.

**Comment by vstakhov** [comment]
I need a `tcpflow` output for this particular issue. You cannot use it for unix sockets. Without traffic dump I cannot say anything.

**Comment by tleuxner** [comment]
I captured the INET stream for 2 days now and wasn't able to reproduce the errors over TCP. Will let it run some more but the problem appears to specific to UNIX sockets.

**Comment by tleuxner** [comment]
tcpflow capture sent separately.

**Comment by vstakhov** [comment]
Do you have any updates?

**Comment by tleuxner** [comment]
I wasn't able to capture a new transaction with binary logging yet. Still running packet capturing.
