### ISSUE TITLE
Github releases

### ISSUE THREAD

**Issue by hdezela** [rspamd/rspamd#1725]
Would it be possible for you to make releases the "github" way so that the API catches them? At the moment the releases response for rspamd is empty. I know this is a tiny and unrelated issue but I have a few clients with automated install/testing and this issue is holding me back from implementing rspamd, and I really want to!

https://help.github.com/articles/about-releases/

**Comment by vstakhov** [comment]
But I can see all Releases on the github page. Isn't it enough?
