### ISSUE TITLE
Disable IP_SCORE for FREEMAIL

### ISSUE THREAD

**Issue by mspenkov** [rspamd/rspamd#1726]
I want to disable IP_SCORE module or remove weight from IP_SCORE symbol if mail from freemail. How I can do this? Composite is not working:
 `    FREEMAIL_FROM_IPSCORE {
        expression = "FREEMAIL_FROM & IP_SCORE";
        policy = "remove_weight";
    }
`

**Comment by vstakhov** [comment]
It should be possible to do now (with some limitations).
