### ISSUE TITLE
Strange "cannot get keys to gather stat" error in log

### ISSUE THREAD

**Issue by athanp** [rspamd/rspamd#1777]
What this error message really means? Never seen that in log before the latest rspamd release
`rspamd_redis_stat_keys: cannot get keys to gather stat: Connection refused`

**Comment by athanp** [comment]
BTW my local statistics.conf follows; not very different than the default...
```
classifier "bayes" {
  tokenizer {
    name = "osb";
  }

  backend = "redis";
  servers = "127.0.0.1:6379";
  min_tokens = 11;
  min_learns = 20;
  languages_enabled = false;

  autolearn = true;
  per_language = false;
  per_user = false;

  statfile {
    symbol = "BAYES_HAM";
    spam = false;
  }
  statfile {
    symbol = "BAYES_SPAM";
    spam = true;
  }

  learn_condition =<<EOD
return function(task, is_spam, is_unlearn)
  local prob = task:get_mempool():get_variable('bayes_prob', 'double')

  if prob then
    local in_class = false
    local cl
    if is_spam then
      cl = 'spam'
      in_class = prob >= 0.95
    else
      cl = 'ham'
      in_class = prob <= 0.05
    end

    if in_class then
      return false,string.format('already in class %s; probability %.2f%%',
        cl, math.abs((prob - 0.5) * 200.0))
    end
  end

  return true
end
EOD

  .include(try=true; priority=1) "$LOCAL_CONFDIR/local.d/classifier-bayes.conf"
  .include(try=true; priority=10) "$LOCAL_CONFDIR/override.d/classifier-bayes.conf"
}
```

**Comment by fatalbanana** [comment]
You could try `rspamadm configdump` to check the effective configuration. The error message suggests redis was not connectable for some reason (maybe not running or firewalled).

**Comment by athanp** [comment]
Thanks for the tips @fatalbanana
However redis was running and accessible on localhost when this error first appeared (four times so far).
Since then I've restarted rspamd and redis and I keep an eye in logs to see if that will happen again.

**Comment by vstakhov** [comment]
It can be ipv4/ipv6 disaster: e.g. if you call localhost which is both v4 and v6 but Redis listens on 127.0.0.1 only. The best solution, namely to kill IPv6 with fire is sadly not possible so far...
