### ISSUE TITLE
Sender Rewrite Schema (SRS) implementation

### ISSUE THREAD

**Issue by mpizzoli** [rspamd/rspamd#1789]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [X] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.3

### Operation system, CPU, memory and environment:
EL7

### Description (Please provide a descriptive summary of the issue):
Having now rspamd a milter interface, one interesting feature to implement would be SRS, so the ability to make the envelope sender address being modified when the email gets forwarded by the MTA.

According to Postfix's author (Wietse Wenema), that can effectively be achieved leveraging the milter interface: http://postfix.1071664.n5.nabble.com/Changing-quot-mail-from-quot-td90765.html 

### Compile errors (if any):
N/A

### Steps to reproduce:
N/A

### Expected results:
Possibility to define rules for changing the envelope from addresses 

### Actual results:
simply missing feature

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
N/A

### Configuration:
N/A

### Additional information:
N/A

**Comment by vstakhov** [comment]
You can set from via Lua: https://rspamd.com/doc/lua/task.html#m91c24

**Comment by mpizzoli** [comment]
Ok, good to know. I did not noticed. Thank you very much.

Could it be that that function permits only to alter the From: and not also the envelope sender?

**Comment by gibzer** [comment]
Seems function ```task:set_from``` doesn't work.
I wrote LUA script which changes both ```From``` (SMTP and MIME) for authenticated users. In example I authenticated by ```new@example.com```, but set ```From``` to ```old@example.com```. So I want rewrite ```From``` to authenticated user.
```
rspamd_config.MODIFY_FROM_AUTH = {
  callback = function(task)
    local rspamd_logger = require "rspamd_logger"
    local rspamd_util = require "rspamd_util"
    local auth_user = task:get_user()

    if auth_user then
      local parsed_auth_user = rspamd_util.parse_mail_address(auth_user)[1]
      rspamd_logger.infox(task, 'Parsed AUTH: %s', parsed_auth_user)

      local changed_smtp = false
      local from_smtp = task:get_from('smtp')[1]
      if from_smtp then
        if string.lower(from_smtp['addr']) ~= string.lower(auth_user) then
          rspamd_logger.infox(task, 'SMTP From: %s', from_smtp)
          from_smtp["addr"] = auth_user
          from_smtp["user"] = parsed_auth_user["user"]
          from_smtp["domain"] = parsed_auth_user["domain"]
          rspamd_logger.infox(task, 'SMTP From tried to: %s', from_smtp)
          changed_smtp = task:set_from('smtp', from_smtp)
          from_smtp = task:get_from('smtp')[1]
          rspamd_logger.infox(task, 'SMTP From after: %s, status: %s', from_smtp, changed_smtp)
        end
      end

      local changed_mime = false
      local from_mime = task:get_from('mime')[1]
      if from_mime then
        if string.lower(from_mime['addr']) ~= string.lower(auth_user) then
          rspamd_logger.infox(task, 'MIME From: %s', from_mime)
          from_mime["addr"] = auth_user
          from_mime["user"] = parsed_auth_user["user"]
          from_mime["domain"] = parsed_auth_user["domain"]
          rspamd_logger.infox(task, 'MIME From tried to: %s', from_mime)
          changed_mime = task:set_from('mime', from_mime)
          from_mime = task:get_from('mime')[1]
          rspamd_logger.infox(task, 'MIME From after: %s, status: %s', from_mime, changed_mime)
        end
      end

      return changed_smtp or changed_mime
    end

    return false
  end,
  description = 'Change FROM to AUTH_USER',
}
```
But it didn't work, even if function ```task:set_from``` returns ```true```. Neither ```SMTP From``` nor ```MIME From``` was changed.
Rspamd log:
```
lua; rspamd.local.lua:9: Parsed AUTH: {[addr] = new@example.com, [flags] = {[valid] = true}, [user] = new, [name] = , [domain] = example.com}
lua; rspamd.local.lua:14: SMTP From: {[addr] = old@example.com, [flags] = {[braced] = true, [valid] = true}, [user] = old, [name] = , [domain] = example.com}
lua; rspamd.local.lua:18: SMTP From tried to: {[addr] = new@example.com, [flags] = {[braced] = true, [valid] = true}, [user] = new, [name] = , [domain] = example.com}
lua; rspamd.local.lua:21: SMTP From after: {[addr] = new@example.com, [flags] = {[valid] = true}, [user] = new, [name] = , [domain] = example.com}, status: true
lua; rspamd.local.lua:30: MIME From: {[addr] = old@example.com, [flags] = {[braced] = true, [valid] = true}, [user] = old, [name] = NAME, [domain] = example.com}
lua; rspamd.local.lua:34: MIME From tried to: {[addr] = new@example.com, [flags] = {[braced] = true, [valid] = true}, [user] = new, [name] = NAME, [domain] = example.com}
lua; rspamd.local.lua:37: MIME From after: {[addr] = new@example.com, [flags] = {[valid] = true}, [user] = new, [name] = NAME, [domain] = example.com}, status: true
```
Postfix doesn't have any errors in its log.

**Comment by vstakhov** [comment]
It is now possible to do it via `task:set_milter_reply` as following:

```lua
task:set_milter_reply{
  add_headers = [
     From = "xxx", -- Mime from
  ],
  remove_headers = [
    From = 0,
  ],
  change_from = "xxx" -- SMTP from
}
```

**Comment by gibzer** [comment]
Yes, it works, but DKIM and ARC signatures are broken. Seems LUA script changes headers after DKIM and ARC signing...

**Comment by vstakhov** [comment]
Yes, DKIM won't see changed headers. I see no easy way to fix it I'm afraid.

**Comment by vstakhov** [comment]
Increasing priority

**Comment by stephtr** [comment]
Yesterday I had a similar problem, but when registering the function as prefilter, one can call on one side `task:set_milter_reply` for actually changing the sender and the other side additionally `task:set_from` such that DKIM sees the changed from.

**Comment by julian-klode** [comment]
So, SRS does not require rewriting the MIME from, only the SMTP from, it should thus be trivial to do this.

**Comment by j-schumann** [comment]
Is there any working example for the forward part (with `task:set_from` for DKIM)?
Or any other news on this topic?
Thanks in advance!

**Comment by vstakhov** [comment]
The question from my side is how to deal with rfc2047 encoding for from names?

**Comment by julian-klode** [comment]
> The question from my side is how to deal with rfc2047 encoding for from names?

Does this affect addresses as well? I mean, names don't need any recoding, only addresses do.

**Comment by JeroenvO** [comment]
This is still a wanted feature i suppose

**Comment by vstakhov** [comment]
Nobody can explain me what needs to be done in Rspamd.

**Comment by kwisatz** [comment]
The link above unfortunately 404s, and so does any mention of map in the rspamd docs, e.g. https://rspamd.com/doc/lua/rspamd_map.html

**Comment by kwisatz** [comment]
I tried the example given by @vstakhov above, but it gives me:

```
2019-06-25 16:58:39 #14(controller) <8ccmoa>; lua; settings.lua:753: cannot parse settings map: memory:33 object closed with } is not opened with { at line 1
2019-06-25 16:58:39 #12(fuzzy) <8ccmoa>; lua; settings.lua:753: cannot parse settings map: memory:33 object closed with } is not opened with { at line 1
2019-06-25 16:58:40 #13(rspamd_proxy) <8ccmoa>; lua; settings.lua:753: cannot parse settings map: memory:33 object closed with } is not opened with { at line 1
2019-06-25 16:58:43 #11(fuzzy) <8ccmoa>; lua; settings.lua:753: cannot parse settings map: memory:33 object closed with } is not opened with { at line 1
2019-06-25 16:58:44 #15(normal) <8ccmoa>; lua; settings.lua:753: cannot parse settings map: memory:33 object closed with } is not opened with { at line 1
```
