### ISSUE TITLE
Maps in user settings match lists

### ISSUE THREAD

**Issue by gibzer** [rspamd/rspamd#1802]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [x] Enhancement

### Rspamd version:
1.6.3
### Description (Please provide a descriptive summary of the issue):
Is it possible to use maps in user settings (https://rspamd.com/doc/configuration/settings.html) match lists (from, rcpt, ip etc.)?
Like this:
```
settings {
	some_users {
		from = "${LOCAL_CONFDIR}/from.map";
		rcpt = "${LOCAL_CONFDIR}/rcpt.map";
		ip = "${LOCAL_CONFDIR}/ip.map";
		apply "default" {
			actions {
				reject = 100.0;
				greylist = 10.0;
			}
		}
	}
}
```

**Comment by fatalbanana** [comment]
The whole of settings can be a map:
`settings = "/path/to/settings"`

**Comment by gibzer** [comment]
it's a pity. Because sometimes match list may be very long and it's very convenient to move it to separate map file and dynamically update by external script (instead of generating whole file with user settings).

**Comment by vstakhov** [comment]
Unfortunately, that's not easy to implement. Reading files is not hard to add, but it does not scale well. Adding maps implies that they would be constantly monitored by Rspamd. I see no ways to do it dynamically I'm afraid. Perhaps, we can add some lua table that defines map like objects in the main config and then reuse them in settings. That's doable.

**Comment by gibzer** [comment]
I understand. Right now I generate part of settings in separate file and then ```.include``` it in config as workaround. You may close issue. Thanks.

**Comment by jonmz** [comment]
@vstakhov I have seen your commit https://github.com/rspamd/rspamd/commit/dc3fd1d5f97aa70c8c0429ea4958792031b4976a for "[Feature] Allow to use global lua maps in settings", but unfortunately I don't understand how this feature is about to be used.

I have tried to define a map in `local.d/rspamd.lua` like that:
```
local forwarded_addresses_map = rspamd_config:add_map({
  type = "set",
  url = "/etc/rspamd/local.d/forwarded_addresses.map",
  description = "List of addresses that forward externally",
})
```
I then tried to use this map in `local.d/settings.conf` like that:
```
local_forwards {
  priority = high;
  rcpt = "map:forwarded_addresses_map";
  apply {
    actions {
      reject = 5;
    }
  }
}
```

With `rcpt` being set to a specific recipient, this works fine, but I was not able to reference the map in any way. The description of the feature commit sounds like I _should_ be able to somehow use a map. Could you please add some instructions on that?
