### ISSUE TITLE
rspamd crash assertion failed in glibghash.c

### ISSUE THREAD

**Issue by sabelka** [rspamd/rspamd#1810]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss

### Reproducibility (Please choose *one* option):

* [X ] Rarely

### Operation system, CPU, memory and environment:
Ubuntu 16.04.3 x86_64  Linux 4.4.0-92-generic

### Description (Please provide a descriptive summary of the issue):

rspamd_proxy crashed when scanning a email containing the EICAR test virus

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
From /var/log/rspamd/rspamd.log:

2017-08-24 14:28:21 #5482(rspamd_proxy) glib; rspamd_glib_printerr_function: **
GLib:ERROR:/build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/ghash.c:373:g_hash_table_lookup_node: assertion failed: (hash_table->ref_count > 0)
2017-08-24 14:28:27 #5478(main) <c25775>; main; rspamd_cld_handler: rspamd_proxy process 5482 terminated abnormally by signal: Aborted and created core file

### Additional information:

Unforunately, this crash is not easily reproducible. Sending the same message again just worked.

**Comment by vstakhov** [comment]
Do you have the core? Please read the FAQ section about how to obtain core files and how to use them.

**Comment by sabelka** [comment]
Yes I found the core now (was hidden in a crashdump saved by Ubunut's apport).
Backtrace uploaded, if required I could also send the whole core per private mail.
[backtrace.txt](https://github.com/vstakhov/rspamd/files/1266231/backtrace.txt)
