### ISSUE TITLE
access to milter protocol commands from lua

### ISSUE THREAD

**Issue by minaevmike** [rspamd/rspamd#1811]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
Rspamd daemon version 1.6.3

### Operation system, CPU, memory and environment:
$ uname -a
Linux mike 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Description (Please provide a descriptive summary of the issue):
i need access to milter protocol commands (like rcpt to) from lua. 

### Additional information:
My case is:
i have a rcpt to command like `RCPT TO: <test_user_0@example.ru> NOTIFY=SUCCESS,FAILURE,DELAY ORCPT=rfc822;abc@gmail.com`.
From lua i want to have access to information about notify and orcpt. 
But now i have only access to smtp email addreess. Is it possible to get this information from lua module?

**Comment by vstakhov** [comment]
This data is not currently processed at all.
