### ISSUE TITLE
FWD_GOOGLE doesn't work

### ISSUE THREAD

**Issue by Hello71** [rspamd/rspamd#1815]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

1.6.3

### Operation system, CPU, memory and environment:

Arch Linux

### Description (Please provide a descriptive summary of the issue):

task get_from gets only the part before `+`, so `+caf_` will never be matched

### Steps to reproduce:

try to forward gmail

### Expected results:

FWD_GOOGLE is added

### Actual results:

FWD_GOOGLE is not added

**Comment by Hello71** [comment]
`EMAIL_PLUS_ALIASES` callback erases original `ENVFROM`

**Comment by Hello71** [comment]
I commented `task:set_from` in `misc.lua` and `FORGED_RECIPIENTS_FORWARDING` and `FORGED_SENDER_FORWARDING` were correctly applied.

**Comment by vstakhov** [comment]
Yes, aliases are removed indeed. Perhaps, this rule should be removed as well.

**Comment by fatalbanana** [comment]
We should be preserving original addresses somehow I suppose (or not modifying them & using normalised addresses where we need/want them).

**Comment by Hello71** [comment]
sigh
