### ISSUE TITLE
module whitelist, blacklist does not work for 

### ISSUE THREAD

**Issue by ChessSpider** [rspamd/rspamd#1824]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] Serious bug
* [ ] WebUI/Usability
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

Rspamd daemon version 1.6.3

### Operation system, CPU, memory and environment:
root@rspamd:/# uname -a
Linux rspamd 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 GNU/Linux

inside docker container
### Description (Please provide a descriptive summary of the issue):

blacklist for ```valid_dkim``` doesnt work

### Compile errors (if any):
n/a
### Steps to reproduce:

1. Make blacklist for domain, e.g.

local.d/whitelist.conf:
```
    rules {
        "BLACKLIST_SPF" = {
            valid_spf = true;
            valid_dkim = true;
            valid_dmarc = true;
            domains = [
                "example.com",
            ];
            score = 20.0;
            blacklist = true;
            description = "Mail comes from the blacklisted domain with invalid spf";
        }
    }
```` 
2. Send an email from example.com triggering the blacklist

### Expected results:

Symbol assigned and no error in log

### Actual results:

Symbol not assigned and error in log:
```call to (BLACKLIST_SPF) failed (2): /usr/share/rspamd/lua/whitelist.lua:127: attempt to index local 'sym' (a nil value); trace: [1]:{/usr/share/rspamd/lua/whitelist.lua:127 - whitelist_cb [Lua]}; [2]:{/usr/share/rspamd/lua/whitelist.lua:189 - [Lua]};```

### Additional information:

Error seems to be use of non-existent variable in 
https://github.com/vstakhov/rspamd/blame/master/src/plugins/lua/whitelist.lua#L127

**Comment by ChessSpider** [comment]
I noticed some extra problems..

There are a lot of 
``` if not rule['blacklist'] or rule['strict'] then ```
I believe that should be:
``` if not rule['blacklist'] and not rule['strict'] then```
in most cases. Strict works a lot better that way. 
Additionally, it seems the dmarc-check does not work at all.

If i print all symbols in the valid_dmarc function, i get:

task:get_symbols() :
```symbols: {[1] = FROM_HAS_DN, [2] = RCVD_COUNT_TWO, [3] = PREVIOUSLY_DELIVERED, [4] = R_PARTS_DIFFER, [5] = RCPT_COUNT_ONE, [6] = RCPT_MAILCOW_DOMAIN, [7] = R_DKIM_ALLOW, [8] = R_SPF_ALLOW, [9] = HAS_REPLYTO, [10] = ARC_NA, [11] = TRUST_DOMAINS, [12] = HTML_SHORT_LINK_IMG_1, [13] = SUBJ_EXCESS_QP, [14] = FROM_EXCESS_QP, [15] = ENVFROM_VERP, [16] = ASN, [17] = URI_COUNT_ODD, [18] = RCVD_NO_TLS_LAST, [19] = FORGED_SENDER, [20] = FROM_NEQ_ENVFROM, [21] = TO_DN_NONE, [22] = TO_MATCH_ENVRCPT_ALL, [23] = MIME_GOOD, [24] = REPLYTO_EXCESS_QP, [25] = REPLYTO_EQ_FROM}``` 

note the ```DMARC_POLICY_ALLOW``` is missing. 

while in the final verdict i do get the DMARC_POLICY_ALLOW:

```[WHITELIST_SPF_DKIM(-3.00),HTML_SHORT_LINK_IMG_1(2.00),FROM_EXCESS_QP(1.20),FORGED_SENDER(0.30),DMARC_POLICY_ALLOW(-0.25),R_DKIM_ALLOW(-0.20),R_SPF_ALLOW(-0.20),MIME_GOOD(-0.10),MX_GOOD(-0.10),ARC_NA(0.00),ASN(0.00),FROM_HAS_DN(0.00),FROM_NEQ_ENVFROM(0.00),IP_SCORE(0.00),PREVIOUSLY_DELIVERED(0.00),RCPT_COUNT_ONE(0.00),RCPT_MAILCOW_DOMAIN(0.00),RCVD_COUNT_TWO(0.00),RCVD_IN_DNSWL_NONE(0.00),RCVD_NO_TLS_LAST(0.00),TO_DN_NONE(0.00),TO_MATCH_ENVRCPT_ALL(0.00)])```


I will and fix the whitelist's function but I don't know how to fix the dmarc-policy check as 

also, am i the only one who uses the whitelist module 😕 ?

**Comment by fatalbanana** [comment]
DKIM/DMARC/SPF is disabled for local IPs and `rspamc` passes `127.0.0.1` as the default IP, so you need to use something like `rspamc -i 1.2.3.4 -F foo@example.com ~/blah.eml` for testing.

**Comment by ChessSpider** [comment]
im not doing local testing, im actually using production testing 👍

**Comment by vstakhov** [comment]
Probably, you are the only who uses this module in blacklist mode. I'll check that later today.

**Comment by ChessSpider** [comment]
cool you're the best 😀 

so far I noticed these bugs:

- [ ] Blacklist SPF for valid_dkim does not work 
- [ ] 'Strict' does not work (due to ```or rules['strict']``` => exit)
- [ ] DMARC_POLICY_ALLOW missing from symbols during whitelist-execution 

I can easily fix the 'strict not working', but dont know where to start for the blacklist dkim crash & missing symbol dmarc_policy_allow

**Comment by ChessSpider** [comment]
i think you got them all. Code looks good, will test tomorrow. Thanks!

**Comment by ChessSpider** [comment]
hi,
can you please double check of the DMARC_POLICY_ALLOW is present in your tests? 
I just re-ran the test for strict +```valid_dmarc = true;``` and it seems to be missing in whitelist.lua but present in final verdict.

strict with valid_dkim also doesnt seem to apply policy when receiving invalid email :(

did the changes work for you?
