### ISSUE TITLE
OMOGRAPH_URL false positive

### ISSUE THREAD

**Issue by moisseev** [rspamd/rspamd#1830]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [x] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.0-git.7b207cf

### Steps to reproduce:
[7ya.tv.eml.zip](https://github.com/vstakhov/rspamd/files/1289675/7ya.tv.eml.zip)

```nginx
# rspamc -h localhost:11334 7ya.tv.eml | fgrep OMOGRAPH
Symbol: OMOGRAPH_URL (2.50)[7я.tv]
```

**Comment by vstakhov** [comment]
I think it will be very hard to fix counting how libicu works...

**Comment by vstakhov** [comment]
And the score is 2.50 and not 5.0, meaning that Rspamd is just suspicious about this domain...

**Comment by moisseev** [comment]
ok, I can live with it. But if you don't mind I'd keep this issue open so I wouldn't forget.
