### ISSUE TITLE
Startup/Restart Error: rspamd_proxy | 12409 | glib |   | **\nERROR:/rspamd-1.6.4/src/libutil/map.c:2220:rspamd_parse_kv_list: assertion failed: (key != NULL)\n

### ISSUE THREAD

**Issue by mxoneil** [rspamd/rspamd#1834]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Compile errors (if any):

rspamd_proxy | 12409 | glib |   | **\nERROR:/rspamd-1.6.4/src/libutil/map.c:2220:rspamd_parse_kv_list: assertion failed: (key != NULL)\n

### Actual results: 

rspamd_proxy | 12409 | glib |   | **\nERROR:/rspamd-1.6.4/src/libutil/map.c:2220:rspamd_parse_kv_list: assertion failed: (key != NULL)\n

**Comment by vstakhov** [comment]
Some of your maps has some broken data. I cannot tell more from your problem description.
