### ISSUE TITLE
Outgoing Mails are processed multiple times (Mailserver with Mailman)

### ISSUE THREAD

**Issue by jnhmn** [rspamd/rspamd#1839]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.4 / 1.6.3
### Description (Please provide a descriptive summary of the issue):
Since I switched from rmilter to proxy-worker, every mail sent by our mailman server are checked separately for each recipient. Since we have not that much traffic, it it's not a big problem for us.

### Expected results:
Every mail should be checked once it is received by postfix to calculate spam score.
Every mail should be processed when it's leaving mailman to add DKIM (and ARC) signatures.
### Actual results:
Every mail is checked when received
Every mail is processed separately for each list member.
### Configuration:

[local_override.zip](https://github.com/vstakhov/rspamd/files/1314087/local_override.zip)

### Additional information:
With rmilter we didn't have that problem. I just replaced the milter socket in postfix/main.cf with the proxy-worker

**Comment by vstakhov** [comment]
I don't understand the issue. There is no difference in how email is processed between Rmilter and Rspamd milter to my understanding. Could you please enable debug for milter: `debug_modules = ["milter"] ` in `local.d/logging.inc`.

**Comment by jnhmn** [comment]
Here is an other sample of a message checked multiple times.
It was send by an authenticated user and then relayed to several external servers...


What information do you need to further investigate this issue?
I've just enabled logging for the milter module.

![screenshot-2017-10-23 rspamd web interface 1](https://user-images.githubusercontent.com/13154537/31867496-27e7b144-b791-11e7-9dd5-de359ee6c009.png)

**Comment by fatalbanana** [comment]
It's likely MTA config issue. There is a similar report at #1853

**Comment by fatalbanana** [comment]
Or maybe that's just expected behaviour & you need special "settings" for mails entering/leaving mailman I suppose. https://rspamd.com/doc/configuration/settings.html

**Comment by jnhmn** [comment]
How do I prevent mails from being scored while the dkim-signing rules stay unaffected?
And can I match the "envelope-from" instead of the "mail from" field? Since the envelope is always from mailman while the From can contain the original sender.

**Comment by fatalbanana** [comment]
You can use [settings](https://rspamd.com/doc/configuration/settings.html) - ie. to enable merely `DKIM_SIGNED` symbol supposing you use [DKIM signing module](https://rspamd.com/doc/modules/dkim_signing.html) for signing. `from` here is SMTP From. You can use Redis settings and/or Lua if you need more complex conditions for settings.

**Comment by heraklit256** [comment]
I experience similar problems, especially when it comes to ARC:

1. A mail is received by a mail server and processed with rspamd. ARC signature added.
2. Mail is locally relayed through Mailman and modified somehow.
3. Mail is sent to mailing list recipients with broken ARC signature since it was modified.

Not sure how to solve this, but maybe it is too ARC-focussed anyway. A possible solution might be to sign mails received via localhost (or the Mailmans server IP) only, using the original recipient address for selecting ARC key.

Has anybody a better idea?
