### ISSUE TITLE
User settings authenticated=no

### ISSUE THREAD

**Issue by f9000** [rspamd/rspamd#1859]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.4

### Description (Please provide a descriptive summary of the issue):
User settings match list includes "authenticated = yes;"
But "authenticated = no;" does not work

### Steps to reproduce:
Add "authenticated = no;" to a previously functional user setting
Send email from external location when setting would normally match

### Expected results:
Setting should match

### Actual results:
Setting no longer matches

### Configuration:
Eg.
settings {
	some_users {
		id = "some_users";
		priority = high;
		rcpt = "/user.*/";
		authenticated = no;
		apply "default" {
			symbol1 = 10.0;
		}
		symbols [
			"symbol2", "symbol4"
		]
	}
}

**Comment by vstakhov** [comment]
That is not intended to work.

**Comment by f9000** [comment]
Please consider it a enhancement request.
