### ISSUE TITLE
Dmarc несколько доменов.

### ISSUE THREAD

**Issue by brestows** [rspamd/rspamd#1871]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.4
### Operation system, CPU, memory and environment:
CentOS 6 x64
### Description (Please provide a descriptive summary of the issue):
В документации не смог найти как настроить рассылку dmarc отчетов, если обслуживается более одного домена, для одного домена я указываю:

```
report_settings {
        org_name = "Example Company";
        domain = "example.com";
        email = "postmaster@example.com";
 }
```
Но когда у тебя несколько доменов, то получается что рассылать будет не правильно. Пробовал указывать так:

```
report_settings {
    report_settings1 = {
        org_name = "Example Company";
        domain = "example.com";
        email = "postmaster@example.com";
    }
    report_settings2 = {
        org_name = "Example2 Company";
        domain = "example2.com";
        email = "postmaster@example2.com";
    }
}
```
Но конфиг не корректный:

> [root@mail rspamd]# rspamadm configtest
> 2017-10-20 13:08:41 #28774(configtest) <sgfyqj>; lua; dmarc.lua:1231: Missing required setting: report_settings.email
> 2017-10-20 13:08:41 #28774(configtest) <sgfyqj>; symcache; rspamd_symbols_cache_post_init: cannot register delayed condition for DMARC_POLICY_ALLOW
> 2017-10-20 13:08:41 #28774(configtest) <sgfyqj>; symcache; rspamd_symbols_cache_post_init: cannot find dependency on symbol DMARC_CALLBACK
> 2017-10-20 13:08:41 #28774(configtest) <sgfyqj>; symcache; rspamd_symbols_cache_validate: symbol 'DMARC_POLICY_ALLOW' has its score defined but there is no corresponding rule registered
> 2017-10-20 13:08:41 #28774(configtest) <sgfyqj>; symcache; rspamd_symbols_cache_validate: symbol 'DMARC_POLICY_QUARANTINE' has its score defined but there is no corresponding rule registered
> 2017-10-20 13:08:41 #28774(configtest) <sgfyqj>; symcache; rspamd_symbols_cache_validate: symbol 'DMARC_POLICY_REJECT' has its score defined but there is no corresponding rule registered
> 2017-10-20 13:08:41 #28774(configtest) <sgfyqj>; symcache; rspamd_symbols_cache_validate: symbol 'DMARC_POLICY_SOFTFAIL' has its score defined but there is no corresponding rule registered

Возможно ли в данный момент настроить уведомление dmarc для нескольких доменов ?

Спасибо.

**Comment by fatalbanana** [comment]
There is support for merely one DMARC 'organisation' which reports on all mail received.

In case we have mail destined to multiple recipients, who is responsible for reporting?

**Comment by brestows** [comment]
Если я правильно понимаю, то если мой сервер обслуживает несколько доменов, то, отправлять он должен от лица каждого домена который он обслуживает, ведь dmarc привязывается к домену а не к серверу. 
В таком случае если  письмо с ящика user@test.com пришло на мой сервер который обслуживает  example.com и example.ru а в получателях были указаны пользователи с доменов example.com и example.ru  то сервер должен отправить отчет на сервер который обслуживает test.com  два отчета, от лица example.com и от лица example.ru. 

Если я что-то не так понимаю в технологии dmarc, буду рад получить объяснение. 
Спасибо.

**Comment by fatalbanana** [comment]
AFAICT it's wrong expectation that it should work like this - which is not to say it could not - we just currently lack support for such. I don't think it'd be wise to report a single transmission multiple times - rather we could just use domain of the first recipient. Issue is similar to #1544.

**Comment by brestows** [comment]
Простите, а если я пишу письмо в получателях ставлю два разных домена и они обслуживаются разными серверами, то я с обоих доменов получу отчет. Разницы особой нет сколько серверов обслуживает получателей, если по одному серверу на получателя, то сервер с которого я пишу все равно получит несколько отчетов, по одному с каждого сервера.
