### ISSUE TITLE
rspamd cannot parse resolv.conf with link-local ipv6 nameservers

### ISSUE THREAD

**Issue by Prototik** [rspamd/rspamd#1873]
### Classification

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):
In #1681 it was added support for ipv6 unicast nameservers, but exists some configurations with link-local addresses with interface number:
```
rspamd[20410]: rdns: rdns_resolver_parse_resolv_conf_cb: rdns_resolver_parse_resolv_conf: cannot parse line: nameserver fe80::822a:a8ff:fe5d:1db3%2
```

**Comment by vstakhov** [comment]
Well, I would accept a patch that fixes this issue but I won't likely work on it by myself: IPv6 is an ugly protocol and I'd personally not recommend to use it.

**Comment by svmhdvn** [comment]
This issue still exists and there are many (like myself) who use link-local resolvers in production. For example, in FreeBSD, a system can have multiple jails with a recursive resolver such as unbound in one jail, and rspamd in another. These can be connected by a single 'lo0' loopback interface and tied with link-local IPv6 addresses.
