### ISSUE TITLE
[Documentation] Wrong module name

### ISSUE THREAD

**Issue by azurit** [rspamd/rspamd#1887]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5

### Description (Please provide a descriptive summary of the issue):
Documentation says the name of greylisting module is 'greylisting' ( https://rspamd.com/doc/modules/ https://rspamd.com/doc/modules/greylisting.html ) but, in fact, it's called 'greylist' (according to config files in modules.d). First i thought it's an issue #1683 (unable to disable greylisting) but then i noticed i must disable it in file local.d/greylist.conf instead of local.d/greylisting.conf .

**Comment by MoritzFago** [comment]
Please fix that or tell where to report instead. This is unacceptable.
