### ISSUE TITLE
False positives with HTML_SHORT_LINK_IMG_1 

### ISSUE THREAD

**Issue by azurit** [rspamd/rspamd#1889]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5

### Operation system, CPU, memory and environment:
Debian Jessie

### Description (Please provide a descriptive summary of the issue):
I don't know how HTML_SHORT_LINK_IMG_1  is supposed to work but in version 1.6.5 it is stripping all html tags and counting only bare text from html (which is usually shorter than 1024 characters). It is extremely easy to trigger this rule, just write simple html e-mail with small image in signature (our client is triggering this with small icons linking to Facebook etc.).

**Comment by azurit** [comment]
Just link it with really weird URI_COUNT_ODD (is it really just counting URLs?) and you are halfway to spam folder (small html reply with image and URL in signature = score 3, hm).

**Comment by Hello71** [comment]
there is already replies module. if you have a suggestion for how to better block spams that just put the text in a picture, feel free to raise it

**Comment by vstakhov** [comment]
Agree, this sort of spam is very common and annoying. Rspamd already has some sort of protection against a small image + decent amount of text. However, it seems to be a reasonable trade-off.

**Comment by Hello71** [comment]
I came up with a stupid solution, rspamd could fetch the image and check the size. if it is a very short (small height, say <200px) image, it is probably a signature image. (or you could run OCR to get the text out for scanning... but that seems like too much work and also far too CPU consuming...) but any way, I think this is fairly low priority. @azurit you get to code it :P

**Comment by Hello71** [comment]
unfortunately, I think that option will increase the amount of spam received, since spammers will think that the spams are being viewed because their tracking images are being loaded.

**Comment by azurit** [comment]
@vstakhov most of the HTML messages with images are triggering HTML_SHORT_LINK_IMG_1 so i don't see how is this usefull :) why don't you simply add 2 points to all messages?

**Comment by codycoggins-virtru** [comment]
We are running into this issue in 2019, rspamd is getting false positives due to the HTML_SHORT_LINK_IMG_1 rule

**Comment by warnerbryce** [comment]
I have also this issue.

**Comment by Hello71** [comment]
if on your particular mails it doesn't work well, you can adjust the scores. there is also rescore module to automatically learn correct scores for your mail set. I think the default is good here for most people, even if it has some false positives for many people.
