### ISSUE TITLE
SPOOF_REPLYTO has too high score

### ISSUE THREAD

**Issue by azurit** [rspamd/rspamd#1891]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5

### Description (Please provide a descriptive summary of the issue):
SPOOF_REPLYTO has default score 6, which is the default for adding a header action (=moving message to spam folder). This doesn't have much sense to me because setting a Reply-To header to completely different e-mail address has legitimate use-cases. For example, we are using it to correctly send messages from various web contact forms were you cannot simply send such e-mails using users e-mail address because of SPF (our servers, usually, are not permitted for sending e-mails from gmail.com and so on). In such cases, we are sending e-mails from our own address and putting users address into Reply-To, so we can easily just reply to it.

Can you explain what is the correct way for sending web contact forms e-mails? Because:
 - you cannot use users address because of SPF
 - you cannot put users address into Reply-To because of SPOOF_REPLYTO

Also, consider score values of these symbols:
SPOOF_REPLYTO: 6 (have, in general, nothing to do with spam)
R_SPF_FAIL: 1 (mechanism created for fighting spam)
R_DKIM_REJECT: 1 (mechanism created for fighting spam)

**Comment by azurit** [comment]
Can anyone react to this? Thank you.

**Comment by vstakhov** [comment]
I've not see any FP for this rule. But DKIM/DMARC and SPF are obviously not a sign of non-spam email these days: spammers are now better than legit senders in following these standards...

**Comment by azurit** [comment]
I didn't mean marking e-mails as non-spam based on DKIM/SPF but marking them as spam if SPF/DKIM fails - but forget it, i just wanted to make an examle how high SPOOF_REPLYTO score is (even much higher than failed SPF check, which doesn't make sense to me).

Can you explain how exactly is SPOOF_REPLYTO working? Exactly when it is triggered? I was reading the source code but i'm not able to fully understand it. Thank you.

**Comment by stevenmunro** [comment]
It also appears that setting SPOOF_REPLYTO in symbols (rspamd web interface) has no effect.

**Comment by azurit** [comment]
stevenmunro add this:


symbol "SPOOF_REPLYTO" {
        weight = 2;
}


into:
local.d/metrics.conf

**Comment by yogitea** [comment]
I am fighting the same issue with a SYMPA mailing list that I have set up on its own domain. All messages are flagged as SPAM because of SPOOF_REPLYTO.
Changing the value in the web interface seems broken. Changing it has not effect.

Can you recategorize this as a bug and fix the two issues?

**Comment by olia-bn** [comment]
If anyone runs into this issue:

The check for set reply-to (which Rsmapd considers a spoof attack) is skipped if From and To are equal as that 'validates the use case' of invisibly redirecting emails because it puts the burden on the sender address to be secured.

We just verified that using the following configuration removed the SPOOF_REPLYTO penalty:
```
From: no-reply@example.org
To: info@example.org
Reply-To: end-user@hotmail.com
```

**Comment by stevenmunro** [comment]
Thanks for the heads up
