### ISSUE TITLE
Replies module doesn't work without url_redirector

### ISSUE THREAD

**Issue by azurit** [rspamd/rspamd#1901]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5

### Description (Please provide a descriptive summary of the issue):
When trying to use replies module without url_redirector, it simply doesn't work with this error message in log:

<57cbe6>; proxy; lua_metric_symbol_callback: call to (REPLIES_CHECK) failed (2): /usr/share/rspamd/lua/url_redirector.lua:260: attempt to index local 'url' (a nil value); trace: [1]:{/usr/share/rspamd/lua/url_redirector.lua:260 - <unknown> [Lua]};

**Comment by fatalbanana** [comment]
It seems something is very screwed up. It doesn't make sense that url_redirector has `REPLIES_CHECK` symbol or that it gets called with nil parameter here.

**Comment by fatalbanana** [comment]
https://groups.google.com/forum/#!topic/rspamd/9iI0hh4x2b4 might hint at the relevant problem.

**Comment by vstakhov** [comment]
So it happens when you **enable** `replies` and **disable** `url_redirector`?
