### ISSUE TITLE
Rspamd webui login error message "Not found"

### ISSUE THREAD

**Issue by szzr** [rspamd/rspamd#1902]
Hey, i have problem with Rspamd version 1.6.4.
When i tryng to login WEBUI, then error mesaage "not found".
I use ubuntu server 16.04 and apache2.
apache2 conf:
<IfModule proxy_module>
    ProxyPass /rspamd http://localhost:11336
    ProxyPassReverse /rspamd http://localhost:11336
</IfModule>

Alias /rspamdadmin "/usr/share/rspamd/www"
<Directory "/usr/share/rspamd/www">
    Options none
    AllowOverride Limit
    Order Deny,Allow
     Deny from all
    Allow from 127.0.0.1
    Allow from all
</Directory>

Screenshot:
https://pilv.addit.ee/index.php/s/m9aP9PgJguFvc82

**Comment by fatalbanana** [comment]
Is controller really running on port `11336` and not `11334` (default)?

**Comment by szzr** [comment]
Hey, these Apache conf not exist Alias:
<Location /rspamd>
	Order allow,deny
	Allow from all
</Location>
RewriteRule ^/rspamd$ /rspamd/ [R,L]
RewriteRule ^/rspamd/(.*) http://localhost:11334/$1 [P,L]
