### ISSUE TITLE
rspamc --mime does not rewrite subject

### ISSUE THREAD

**Issue by UCIS** [rspamd/rspamd#1907]
### Classification (Please choose *one* option):

* [x] Feature

### Reproducibility (Please choose *one* option):

* [X] Always

### Rspamd version:

1.6.5

### Operation system, CPU, memory and environment:

Debian i386

### Description (Please provide a descriptive summary of the issue):

rspamc --mime does not rewrite the subject header even though the rewrite_subject action is selected and the replacement subject is defined.

### Steps to reproduce:

(see Configuration)
echo -en 'Subject: test\r\n\r\ntest' | rspamc --mime

### Expected results:

The Subject header in the output should be modified as configured ("Subject: [SPAM] test" in the example).

### Actual results:

The Subject header in the output is not modified. The instruction on how to modify the subject line is not available either. The output does contain the "X-Spam-Action: rewrite subject" header line.

### Configuration:

/etc/rspamd/local.d/metrics.conf
```
subject = "[SPAM] %s";
actions {
  reject = 15;
  rewrite_subject = 7;
}
```

### Additional information:

I think modifying the Subject header in --mime mode is the right thing to do, since the --mime option is generally used when external rewriting is not desired.

**Comment by vstakhov** [comment]
`rspamc --mime` is the last resort when all other connection methods are impossible. It is not intended to be a fully functional integration mode and its functionality extension has very low priority in my tasks list. Hence, I'd recommend to change your integration method if possible (or, of course, send patches).

**Comment by UCIS** [comment]
Thanks for your prompt reply. I'm using the XMail mailserver, so I don't think other connection methods are directly possible. I would like to ask you to at least clarify the limitation of the --mime option in the documentation, it's very confusing that it doesn't "just work".

I will probably try to write a client to the HTTP protocol in PHP instead since there's a PHP wrapper script in place already, although I was hoping I would not have to deal with e-mail headers myself.

**Comment by vstakhov** [comment]
HTTP wrapper should be trivial I think. I did that for CommunigatePro once. The problem here is that dealing with mime/http/json is usually easy from any scripting language (but slow!). C parts of  Rspamd are intended to **parse** MIME fast but they are not intended to modify messages as their original structure is not 100% preserved to deal with broken messages etc. That's why I always recommend to write a helper for all but performance oriented systems where overhead of, let's say, a Python HTTP client is not affordable...

**Comment by sven337** [comment]
I like rspamc --mime as an almost drop-in replacement of spamassassin in a procmail setup (no MTA involved). 
fetchmail delivers to procmail which calls rspamc - no need to involve Postfix or similar. In that setup, having rspamc able to rewrite subjects would be very useful. Is this something you could consider?

Thanks
