### ISSUE TITLE
[Feature request] Implement support for S/MIME - signing & ciphering

### ISSUE THREAD

**Issue by mpizzoli** [rspamd/rspamd#1912]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.x

### Operation system, CPU, memory and environment:
Linux EL7 x86_64

### Description (Please provide a descriptive summary of the issue):
This request is for getting  S/MIME support in Rspamd both for signing & ciphering emails.

The wish is to get this feature available and permitting it to be used together with dkim_signing.

### Compile errors (if any):
N/A

### Steps to reproduce:
N/A

### Expected results:
N/A

### Actual results:
N/A

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
N/A

### Configuration:
N/A

### Additional information:
N/A

**Comment by vstakhov** [comment]
This feature is very hard to implement and lays slightly out of Rspamd main focus. I doubt it will be useful for many of Rspamd users.

**Comment by ChessSpider** [comment]
👍 I would like this feature. 
Maybe rspamd could have an encrypt and decrypt handler which handles the encryption of decryption of email when respectively sending and receiving email? This could then be invoked at the right time when sending or receiving email. 
This would leave the implementation of smime or pgp or whatever to a third party
