### ISSUE TITLE
Maildir folder to learn spam

### ISSUE THREAD

**Issue by szepeviktor** [rspamd/rspamd#1923]
It there a way for IMAP-only users to report spam instead of the documented *passing messages to a certain email address*?

I can think of inotify (incron) + rspamc for every new file in the user's Spam folder but I do not consider myself an MTA expert.

**Comment by moisseev** [comment]
You can use IMAPSieve: [AntispamWithSieve](https://wiki.dovecot.org/HowTo/AntispamWithSieve)

**Comment by szepeviktor** [comment]
Thank you.
I am a courier-only user.
