### ISSUE TITLE
Avoid parsing of html body when no anti-spam module is enabled

### ISSUE THREAD

**Issue by mpizzoli** [rspamd/rspamd#1928]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5

### Operation system, CPU, memory and environment:
Any

### Description (Please provide a descriptive summary of the issue):
As confirmed by @vstakhov : https://groups.google.com/forum/#!topic/rspamd/PozjLW9nwdA
Even when the only module enabled is dkim_signing, rspamd does the full parsing of the html body of the message. This should be avoided in order to make rspamd processing faster the email.

### Compile errors (if any):
N/A

### Steps to reproduce:
Disable all modules except dkim_signing and check that the "rspamd_html_process_part_full" procedure gets executed.

### Expected results:
No parsing of the message body 

### Actual results:
Message body parsed. Useless CPU time spent.

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
N/A

### Configuration:
dkim_signing:
enabled: no

### Additional information:
N/A

**Comment by mpizzoli** [comment]
@vstakhov 
This improvement would be very helpful for my use-case.
Could I ask you to raise its priority?

**Comment by mpizzoli** [comment]
@vstakhov 
This is the ticket I was reminding you today

**Comment by vstakhov** [comment]
That's now implemented. You can set it via settings:

```
settings {
   foo {
     apply {
       symbols_enabled = ["DKIM_SIGNED"];
       flags = ["skip_process"];
     }
   }
}
```

**Comment by mpizzoli** [comment]
Today I got the time to thoroughly testing it.

Now it seems to me that the function rspamd_html_process_part_full is
causing less cpu load.
Now I see another function bumping up in the "perf top" output:
rspamd_language_detector_try_ngramm.constprop.9

Is this the expected behaviour?

Thank you very much again
Marco
