### ISSUE TITLE
RBL list scores

### ISSUE THREAD

**Issue by MisterM74** [rspamd/rspamd#1929]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5
### Additional information:
Hello
when you add a new RBL, how to determine the score you will add?
Thank you
Mz

**Comment by heraklit256** [comment]
Maybe https://rspamd.com/doc/modules/rbl.html and the contents of "modules.d/rbl.conf" (RBL symbols) and "scores.d/rbl_group.conf" (symbol scoring) is helpful here.
