### ISSUE TITLE
Rspamd issue on Xeon/Skylake

### ISSUE THREAD

**Issue by lasalesi** [rspamd/rspamd#1935]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
Rspamd daemon version 1.6.5

### Operation system, CPU, memory and environment:
Debian 9/Stretch amd64, Xeon Skylake (KVM, on 2 cores, 4 GB RAM)

### Description (Please provide a descriptive summary of the issue):
Rspamd hangs (visible on permanent 100% CPU usage of one core)

When trying to execute rspamadm pw it fails with 

    2017-11-28 08:33:38 #1365(rspamadm) glib; rspamd_glib_printerr_function: **
    ERROR:/rspamd-1.6.5/src/libutil/multipattern.c:578:rspamd_multipattern_compile: assertion failed: 
    (hs_alloc_scratch (mp->db, &mp->scratch[i]) == HS_SUCCESS)
     
    Aborted

### Compile errors (if any):
n/a

### Steps to reproduce:
Use a virtual machine running on a Xeon Skylake arch. Switch KVM to Skylake. Boot system and observe CPU usage.

Compare against switching the KVM into e.g. IvyBridge. System works without issues.

### Expected results:
Normal CPU consumption, function work.

### Actual results:
Permanent CPU load, functions fail.

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
n/a

### Configuration:
Virtual KVM system on Xeon Skylake, Debian Stretch (vanilla), Rspamd from

    deb http://rspamd.com/apt-stable/ stretch main
    deb-src http://rspamd.com/apt-stable/ stretch main

### Additional information:
Workaround: use IvyBridge or Broadwell emulation

**Comment by vstakhov** [comment]
It seems to be hyperscan issue.
