### ISSUE TITLE
controller process causes high CPU & RAM usage by viewing the "history" tab in WebUI

### ISSUE THREAD

**Issue by WRMSRwasTaken** [rspamd/rspamd#1952]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5

### Operation system, CPU, memory and environment:
Arch Linux
24GB, 8Core on KVM
cpuinfo reports:  Xeon(R) CPU E5-2680 v4 @ 2.40GHz

### Description (Please provide a descriptive summary of the issue):
By clicking on the "History" Tab in the WebUI, the controller process eats 100% of one core, and the memory usage spikes at around 13%, then goes back to 1%, repeating on endlessly, until restart

### Compile errors (if any):
none

### Steps to reproduce:
By clicking the "History"-Tab in the WebUI

### Expected results:
Getting the actual history listed

### Actual results:
CPU & RAM spikes, no history displayed, the WebUI displays: `Cannot receive data from rspamd1: timeout`

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
n/a, no crashes at all

### Configuration:
compiled from AUR: https://aur.archlinux.org/packages/rspamd/
Local proxy worker active + 1 normal worker

### Additional information:
Might be related to #1935 ?

**Comment by vstakhov** [comment]
Not enough information: are you using history redis? What Rspamd controller process does (strace -p, gdb -p, etc)?

**Comment by WRMSRwasTaken** [comment]
Yes, using Redis history. The history quicklist has a length of 2000 items.

The strace output is attached:
[strace.txt](https://github.com/vstakhov/rspamd/files/1544657/strace.txt)

**Comment by vstakhov** [comment]
Ok, it seems that 2000 entries is completely unreasonable default. So far, it receives several megs of compressed data from Redis and tries to decompress it:

```
mmap(NULL, 1305968640, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f36a9d6e000
mmap(NULL, 5223866368, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f3572790000
mmap(NULL, 1305968640, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f3524a18000
munmap(0x7f3524a18000, 1305968640)      = 0
munmap(0x7f3572790000, 5223866368)      = 0
munmap(0x7f36a9d6e000, 1305968640)      = 0
```

This is around 7Gb of memory requested and immediately freed. Can you do it with timestamps btw `strace -tt`?

**Comment by WRMSRwasTaken** [comment]
This time, accessing the history did work, nothing changed except a process restart.
[strace.txt](https://github.com/vstakhov/rspamd/files/1544800/strace.txt)

**Comment by WRMSRwasTaken** [comment]
I managed to to a `strace -tt` while having this problem again: [strace.txt](https://github.com/vstakhov/rspamd/files/1665222/strace.txt)

This is a bit strange, because this problem comes by itself and disappears on its own again. I'm not deleting anything in redis.

On my other node, there was an JOSN Error while retrieving history data, so I had to delete the redis history list fot this node to get the history running again.

**Comment by sander85** [comment]
I'm having the same problem. But on my server the it seems that the process uses so much memory that it fills also all the swap and then crashes the server. Didn't happen with 1.6.3 and I didn't change anything in conf during upgrade. I'm also using redis for history, but the system seems to crash also when history is not viewed :/

**Comment by macgeneral** [comment]
I run into the same problem from time to time. The rspamd controller process starts eating up all RAM until none is left and then seems to crash/restart.

It seems to occur often after restarting the server when redis and rspamd are started shortly after one and another (even though in the correct order). Stopping rspamd, restarting redis and then starting rspamd again usually solves it for me.

I also reduced the history size to 200 but that didn't help at all.

[strace_p.txt](https://github.com/vstakhov/rspamd/files/1701440/strace_p.txt)

**Comment by stephdl** [comment]
same problem here with rspamd 1.6.5, the load goes to 50 and the ram is full by the rspamd process (83% by the service)

**Comment by DavidePrincipi** [comment]
@macgeneral, @stephdl I cannot reproduce it (by now) here. Just a shot in the dark: set `false` the compress option:

```text
# rspamadm configdump history_redis
*** Section history_redis ***
key_prefix = "rs_history";
nrows = 200;
compress = false;
servers = "/var/run/redis-rspamd/rspamd";

*** End of section history_redis **
```

**Comment by bennnn** [comment]
Just commening to say I'm experiencing the same high CPU/mem - disabling compression worked for now. 

Trying to debug, find something useful but nothing so far. Only things to note for my install (only 1 of 2 affected) that I did have the #1872 bug (cleared history, now ok), and that now and then all emails get BAYES_SPAM symbol regardless - a rspamd restart fixes this. (I know its not directly related, but who knows if theres some loose correlation under the hood...)

Keep it up!

**Comment by stephdl** [comment]
I try to get the `worker = 1` and keep the `compress = true` for now, it is workable

```
[root@prometheus ~]#  rspamadm configdump worker
2018-02-09 11:25:42 #27972(rspamadm) cfg; rspamd_config_post_load: CPU doesn't have SSSE3 instructions set required for hyperscan, disable it
*** Section worker ***
bind_socket = "localhost:11335";
type = "fuzzy";
hash_file = "/var/lib/rspamd/fuzzy.db";
expire = 7776000.0;
allow_update [
    "localhost",
    "127.0.0.1",
]
count = 2;
backend = "redis";
sync = 60.0;

*** End of section worker ***
*** Section worker ***
log_helper {
    count = 1;
}

*** End of section worker ***
*** Section worker ***
bind_socket = "/var/run/rspamd/worker-normal mode=0770 owner=_rspamd group=mail";
count = 1;
type = "normal";
mime = true;
task_timeout = 8.0;

*** End of section worker ***
*** Section worker ***
bind_socket = "*:11334";
password = "PASSWORD";
enable_password = "PASSWORD";
count = 1;
type = "controller";
secure_ip = "127.0.0.1";
static_dir = "/usr/share/rspamd/www";

*** End of section worker ***
*** Section worker ***
rspamd_proxy {
    bind_socket = "/var/run/rspamd/worker-proxy mode=0770 owner=_rspamd group=mail";
    milter = true;
    timeout = 120.0;
    upstream {
        local {
            default = true;
            self_scan = true;
            hosts = "localhost";
        }
    }
    count = 1;
    type = "proxy";
}

*** End of section worker ***
*** Section worker ***
bind_socket = "localhost:11335";
type = "fuzzy";
count = 1;
backend = "redis";
expire = 7776000.0;
sync = 60.0;
allow_update [
    "127.0.0.1",
]

*** End of section worker ***
*** Section worker ***
log_helper {
    count = 1;
}

*** End of section worker ***
```

**Comment by stephdl** [comment]
I hit today the history bug, see gist file about what it happen
strace
https://gist.github.com/stephdl/8b33e645879d01a6fd3357e78ec01667

lsof
https://gist.github.com/stephdl/33dbf5992571183788f43af8684f16cc

what do we need more to understand ?

**Comment by stephdl** [comment]
strace with -tt
https://gist.github.com/stephdl/8665ea502db66d8257d21fe7295837d0

**Comment by stephdl** [comment]
strace with -tt when the bug is hit via curl

https://gist.github.com/stephdl/76b3fd89999492c7e32e85d59025eacf

**Comment by WRMSRwasTaken** [comment]
I'm seeing a memory leak with the enabled phishing module. 

![firefox_2018-02-17_01-25-49](https://user-images.githubusercontent.com/4244869/36335623-a40405f6-1381-11e8-9638-d01f02c0fafa.png)

```
*** Section phishing ***
symbol = "PHISHING";
openphish_enabled = true;
openphish_premium = false;
openphish_map = "https://www.openphish.com/feed.txt";
phishtank_enabled = true;
phishtank_map = "https://rspamd.com/phishtank/online-valid.json.zst";
redirector_domains [
    "/etc/rspamd/redirectors.inc:REDIRECTOR_FALSE",
    "/etc/rspamd/local.d/redirectors.inc:LOCAL_REDIRECTOR_FALSE",
]

*** End of section phishing ***
```

This could be related to this issue, as I'm using the rspamd mirror for phishtank, which uses `zstd` for compression too. 

I'm going to disable the phishtank url and report again.

**Comment by macgeneral** [comment]
I don't know if it helps, but here are some more straces...
I noticed that the output of strace stops at parts like these:

`madvise(0x7fa7cc2d9000, 6442463232, MADV_DONTNEED) = 0
madvise(0x7faa8d5df000, 8192, MADV_DONTNEED) = 0
madvise(0x7faa8d17b000, 4096, MADV_DONTNEED) = 0
madvise(0x7faa8d181000, 8192, MADV_DONTNEED) = 0
madvise(0x7faa8d17f000, 4096, MADV_DONTNEED) = 0
madvise(0x7faa8d184000, 782336, MADV_DONTNEED) = 0
madvise(0x7faa8d150000, 4096, MADV_DONTNEED) = 0
madvise(0x7faa8d248000, 626688, MADV_DONTNEED) = 0
madvise(0x7faa8d2e4000, 1740800, MADV_DONTNEED) = 0
madvise(0x7faa8d576000, 8192, MADV_DONTNEED) = 0
madvise(0x7faa8d556000, 57344, MADV_DONTNEED) = 0
madvise(0x7faa8d57a000, 16384, MADV_DONTNEED) = 0
madvise(0x7faa8d581000, 45056, MADV_DONTNEED) = 0
madvise(0x7faa8d58d000, 12288, MADV_DONTNEED) = 0
madvise(0x7faa8d5ac000, 4096, MADV_DONTNEED) = 0
madvise(0x7faa8d5ae000, 8192, MADV_DONTNEED) = 0
madvise(0x7faa8d5b5000, 4096, MADV_DONTNEED) = 0
madvise(0x7faa8d5b1000, 4096, MADV_DONTNEED) = 0
madvise(0x7faa8d567000, 57344, MADV_DONTNEED) = 0
madvise(0x7faa8d5b9000, 4096, MADV_DONTNEED) = 0
madvise(0x7faa8d5b7000, 4096, MADV_DONTNEED) = 0
madvise(0x7faa8d5aa000, 4096, MADV_DONTNEED) = 0
madvise(0x7faa8d5be000, 4096, MADV_DONTNEED) = 0
madvise(0x7faa8d492000, 512000, MADV_DONTNEED) = 0
madvise(0x7faa8d5bb000, 8192, MADV_DONTNEED) = 0
madvise(0x7faa8d593000, 81920, MADV_DONTNEED) = 0
madvise(0x7faa8d5c5000, 4096, MADV_DONTNEED) = 0
madvise(0x7faa8d5c0000, 16384, MADV_DONTNEED) = 0
madvise(0x7faa8d510000, 266240, MADV_DONTNEED) = 0
madvise(0x7faa8d5cf000, 4096, MADV_DONTNEED) = 0
madvise(0x7faa8d5cc000, 8192, MADV_DONTNEED) = 0
madvise(0x7faa8d5c8000, 4096, MADV_DONTNEED) = 0
madvise(0x7faa8d5d3000, 4096, MADV_DONTNEED) = 0
madvise(0x7faa8cc87000, 8192, MADV_DONTNEED) = 0
madvise(0x7faaffdae000, 8192, MADV_DONTNEED) = 0
madvise(0x7faafbf7c000, 8192, MADV_DONTNEED) = 0
madvise(0x7faa8d675000, 708608, MADV_DONTNEED) = 0
madvise(0x7faa8d61a000, 114688, MADV_DONTNEED) = 0`

And resumes when the CPU load of the controller process returns to normal (from 100%). It appeared every time when I clicked on the history tab while this bug occured so the interesting parts might be right upfront.

(PS: used the latest version 1.6.6 for those traces, the history is limited to 200 entries and still I'm occasionally hit by this bug but it's not easy to trigger it manually)

[strace_p.txt](https://github.com/vstakhov/rspamd/files/1749353/strace_p.txt)
[strace_tt.txt](https://github.com/vstakhov/rspamd/files/1749354/strace_tt.txt)
[lsof.txt](https://github.com/vstakhov/rspamd/files/1749357/lsof.txt)

**Comment by stephdl** [comment]
hi @vstakhov 
I would be pleased if you can enlighten me about this bug, sometime ago you found a missing c library ( jemalloc) for centos, did you recompile rspamd with it ?

`[root@prometheus ~]# ldd /usr/bin/rspamd | grep jemalloc`

I do still have this noisy bug on centos7

**Comment by fm81** [comment]
Same history page problem here with  rspamd-1.7.0-120.git5e9608de5.x86_64 from centos-7 experimental repository.

**Comment by vstakhov** [comment]
No ideas, I cannot reproduce it on debian based distros. I have no CentOS setups to debug it.

**Comment by DavidePrincipi** [comment]
Could you suggest some commands to gather relevant information when I hit the bug?

Should I install debuginfo package?
