### ISSUE TITLE
fann_redis not starting when configured

### ISSUE THREAD

**Issue by kobuki** [rspamd/rspamd#1955]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5
### Description (Please provide a descriptive summary of the issue):
I configured the module [per instructions](https://www.rspamd.com/doc/modules/fann.html). The module is not starting, at every startup below lines are printed in the log. Redis is working properly for all other modules.
```
2017-12-10 22:45:32 #30049(main) <cz8cy1>; cfg; rspamd_config_is_module_enabled: lua module fann_classifier is enabled but has not been configured
2017-12-10 22:45:32 #30049(main) <cz8cy1>; cfg; rspamd_config_is_module_enabled: fann_classifier disabling unconfigured lua module
2017-12-10 22:45:32 #30049(main) <cz8cy1>; cfg; rspamd_init_lua_filters: init lua module fann_redis
2017-12-10 22:45:32 #30049(main) <cz8cy1>; cfg; rspamd_config_is_module_enabled: lua module fann_scores is enabled but has not been configured
2017-12-10 22:45:32 #30049(main) <cz8cy1>; cfg; rspamd_config_is_module_enabled: fann_scores disabling unconfigured lua module
```
### Configuration:
```
# rspamadm configdump fann_redis
*** Section fann_redis ***
train {
    max_train = 10000;
    max_usages = 10;
    spam_score = 8;
    ham_score = -2;
}
use_settings = false;
servers = "127.0.0.1:6379";

*** End of section fann_redis ***
# rspamadm configdump redis
*** Section redis ***
servers = "127.0.0.1";

*** End of section redis ***
```

**Comment by vstakhov** [comment]
This module is starting:

```
2017-12-10 22:45:32 #30049(main) <cz8cy1>; cfg; rspamd_init_lua_filters: init lua module fann_redis
```

**Comment by kobuki** [comment]
OK, thanks, that's reassuring. But I don't get those cryptic log messages. What do they mean, or should I worry about them at all?

**Comment by vstakhov** [comment]
That are experimental or outdated modules that are disabled by default. Nothing to worry about.

**Comment by kobuki** [comment]
Thanks for the explanation. I'll close this then.

**Comment by kobuki** [comment]
Sorry to reopen this again, this could either be an application bug or a documentation bug. Despite the claim that the FANN module has been loaded and started, it apparently doesn't do anything. No related lines in the log, nor entries in redis. I'm getting scores above and below the autolearn thresholds of the module.

```
# redis-cli
127.0.0.1:6379> keys "RFANN0_*"
(empty list or set)
```
What could be the issue?

**Comment by kobuki** [comment]
Additional info, see below. Does this mean that the module is working after all?
```
127.0.0.1:6379> keys "*FANN0_*"
(empty list or set)
127.0.0.1:6379> keys "*FANN*"
1) "RFANN90626818C57C68900_ham"
2) "RFANN90626818C57C6890"
3) "RFANNEDE2CEDE528F6835"
4) "RFANN90626818C57C68900_spam"
5) "RFANNEDE2CEDE528F68350_ham"
6) "RFANNEDE2CEDE528F68350_spam"
```
Neural networks are already the present and the future of machine learning, I think it's a very good thing to have this module here, and a little more documentation and examples would help tremendously.
