### ISSUE TITLE
exempt pgp encrypted messages from bayes filtering

### ISSUE THREAD

**Issue by philfry** [rspamd/rspamd#1960]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [X] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

1.6.5

### Operation system, CPU, memory and environment:

n/a

### Description (Please provide a descriptive summary of the issue):

pgp encrypted messages usually contain no valueable text for bayes spam analysis. Still, rspamd classified an encrypted message as spam.
Didn't test for s/mime encrypted mails.

### Steps to reproduce:

1. train bayes filter
2. receive pgp encrypted message
3. profit.

### Expected results:

text between `-----BEGIN PGP MESSAGE-----` and `-----END PGP MESSAGE-----` being excluded from bayes analysis.

### Actual results:

`BAYES_SPAM(7.99)[99.98%]`

**Comment by vstakhov** [comment]
Can be an introductionary gsoc task.
