### ISSUE TITLE
WebUI history empty on slower network connection

### ISSUE THREAD

**Issue by gramels** [rspamd/rspamd#1967]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
ii  rspamd                          1.6.5-2~jessie                 amd64        Rapid spam filtering system

### Operation system, CPU, memory and environment:
Linux mailfilter 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3 (2017-12-03) x86_64 GNU/Linux

### Description (Please provide a descriptive summary of the issue):
WebUI made available using nginx proxy

WebUI history empty on slower network connection.
on local LAN connection or faster network all fine.

likely a timeout issue

Is there a possibility to increase timeout?

### Steps to reproduce:
1) connect locally, all fine
2) connect remote (eg via VPN) history stays empty

### Expected results:
history always shown

**Comment by dimejo** [comment]
> WebUI made available using nginx proxy
> 
> WebUI history empty on slower network connection.
> on local LAN connection or faster network all fine.
> 
> likely a timeout issue
> 
> Is there a possibility to increase timeout?

Take a look at the various timeout directives for the proxy module.
http://nginx.org/en/docs/http/ngx_http_proxy_module.html

But I doubt it will solve your problem. The default for these directives is already 60s, which should be long enough to get a response. You might need to get keep-alive connections working.
https://stackoverflow.com/questions/10395807/nginx-close-upstream-connection-after-request

**Comment by vstakhov** [comment]
JS interface has it's own unconfigurable timeout. We need to deal with the history properly but I have nobody who knows how to deal with JS DataTables, specifically about how to load data in portions. I have neither desire nor time to implement this. You can increase JS timeout or reduce number of history rows being stored as a workaround.

**Comment by AndrewSav** [comment]
This does not seem to be fixed. This issue is most prominent when cpu/memory is scarce,

**Comment by moisseev** [comment]
@vstakhov We can load history data in FooTable dynamically, but the main problem is that filtering/searching/sorting/etc will be limited to loaded data. I'm afraid, it should be implemented in controller in this case.

**Comment by AndrewSav** [comment]
So can this be solved?

**Comment by vstakhov** [comment]
It can be done theoretically but nobody will do it most likely. You can use other tools (e.g. Clickhouse) or suggest your patches to WebUI. I'm closing this issue as there are no chances for it to be ever fixed.
