### ISSUE TITLE
[Feature] Add ability to detect obfuscated file names in attachments

### ISSUE THREAD

**Issue by moisseev** [rspamd/rspamd#1969]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [x] Not applicable

### Description (Please provide a descriptive summary of the issue):

Currently `mime_part:get_filename()` cannot extract such filenames at all  [4, 5] or extacts filenames without extensions [6, 7].

It would be good to:
- add ability to extract these file names and extensions
- provide some indication that the file name is obfuscated

Obfuscated filename samples from http://www.emailsecuritycheck.net/:

test mail 4/7
```
--XXX
Content-Type: application/x-msdownload;
 name*0*="''attached%2E";
 name*1*="%62";
 name*2=at
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment;
 filename*0*="''attached%2E";
 filename*1*="%62";
 filename*2=at

echo Your system is vulnerable
pause

--XXX--
```
test mail 5/7
```
--XXX
Content-Type: application/x-msdownload;
 name=attached.()bat
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment;
 filename=attached.()bat

echo Your system is vulnerable
pause

--XXX--
```

test mail 6/7
```
--XXX
Content-Type: application/x-msdownload;
 "name"=attached.bat
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment;
 "filename"=attached.bat

echo Your system is vulnerable
pause

--XXX--
```
test mail 7/7
```
--XXX
Content-Type: application/x-msdownload;
 name=attached\
.bat
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment;
 filename=attached\
.bat

echo Your system is vulnerable
pause

--XXX--
```

**Comment by vstakhov** [comment]
Well, all these cases, besides of (5), are not RFC conformant. What MUA support that?

**Comment by vstakhov** [comment]
Even (5) is not RFC conformant. Yes, we can add pile of workarounds to parse this shit but I want to know who are affected by these 'vulnerabilities'. Unfortunately, I have to treat bugs in clients as real bugs...

**Comment by moisseev** [comment]
I haven't done much research about it, but Roundcube and Yandex web mail clients are vulnerable.

**Comment by heraklit256** [comment]
From Efail, we learnt MUAs are usually processing non RFC compliant mails. :-( Filtering these might break some poorly written software but also attacks using broken mail syntax.

+1 for this.
