### ISSUE TITLE
debian build always produces package version 1.0.2

### ISSUE THREAD

**Issue by neonknight** [rspamd/rspamd#1983]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5

### Operation system, CPU, memory and environment:
Debian Stretch 9.3

### Description (Please provide a descriptive summary of the issue):
When building rspamd 1.6.5 release on Debian the resulting .deb still claims to be version 1.0.2:
rspamd_1.0.2_amd64.deb

### Steps to reproduce:
wget https://codeload.github.com/vstakhov/rspamd/tar.gz/1.6.5
tar -zxf 1.6.5
cd rspamd-1.6.5
dpkg-buildpackage -rfakeroot -uc -b
cd ..
ls

### Expected results:
resulting .deb package should be version 1.6.5.: rspamd_1.6.5_amd64.de

### Actual results:
resulting .deb package claims to be of old version: rspamd_1.0.2_amd64.deb

**Comment by fatalbanana** [comment]
Version numbers in DEB/RPM packaging don't get bumped: the reason is the search & replace story that happens in [the build scripts](https://github.com/vstakhov/rspamd-build-scripts)- we'd have to do something about that to fix this.
