### ISSUE TITLE
SMTPUTF8 mails for IDN domains are marked as spam

### ISSUE THREAD

**Issue by jpguerard** [rspamd/rspamd#1991]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [X] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

1.6.5-4~jessie

### Operation system, CPU, memory and environment:

Debian 9.3
Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz
16 GB RAM
Postfix 3.1.6-0+deb9u1 (with smtputf-8 enabled) + Rmilter + Rspamd
The server domain is an IDN.

### Description (Please provide a descriptive summary of the issue):

Mail received from an SMTPUTF8 compatible server (for example gmail.com) are marked as spam for having BROKEN_HEADERS and RCVD_ILLEGAL_CHARS. Indeed they contain headers using an UTF-8 encoding for the recipient domain name (X-Original-To, Delivered-To, Received). 

### Steps to reproduce:

Send an e-mail from a gmail account to an IDN domain using rspamd.

### Expected results:

Both BROKEN_HEADERS and RCVD_ILLEGAL_CHARS do not apply.

### Actual results:

Both BROKEN_HEADERS and RCVD_ILLEGAL_CHARS do apply.

**Comment by vstakhov** [comment]
Neither SMTPUTF8 nor IDN domains are supported in Rspamd, so that is expected.

**Comment by smitgd** [comment]
This has also caused an issue in Thunderbird. See https://bugzilla.mozilla.org/show_bug.cgi?id=1710224#c77

**Comment by silverasu** [comment]
We also have this issue. All IDN domains will get 14 points (RCVD_ILLEGAL_CHARS(4) and BROKEN_HEADERS(10)) from Gmail e-mails. For workaround we lowered those symbol scores.

Can we please open this ticket?

**Comment by pcaceres-hazloagil** [comment]
@silverasu @vstakhov
I need Help with it problem... 
do you have any idea how to do it?
