### ISSUE TITLE
exited on signal 11 (core dumped)

### ISSUE THREAD

**Issue by ents-hqx** [rspamd/rspamd#2014]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [X] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5
### Operation system, CPU, memory and environment:
FreeBSD 11.1-RELEASE-p4, Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz,RAM: 8GB, Xen guest
### Description (Please provide a descriptive summary of the issue):
rspamd_proxy process terminates abnormally
### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...

warning: core file may not match specified executable file.
Core was generated by `rspamd: rspamd_proxy process'.
Program terminated with signal 11, Segmentation fault.
Reading symbols from /usr/local/lib/libfann.so.2...done.
Loaded symbols for /usr/local/lib/libfann.so.2
Reading symbols from /usr/local/lib/libhs.so.4...done.
Loaded symbols for /usr/local/lib/libhs.so.4
Reading symbols from /lib/libutil.so.9...done.
Loaded symbols for /lib/libutil.so.9
Reading symbols from /usr/local/lib/libgthread-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgthread-2.0.so.0
Reading symbols from /usr/local/lib/libglib-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libglib-2.0.so.0
Reading symbols from /usr/local/lib/libintl.so.8...done.
Loaded symbols for /usr/local/lib/libintl.so.8
Reading symbols from /usr/local/lib/libpcre.so.1...done.
Loaded symbols for /usr/local/lib/libpcre.so.1
Reading symbols from /usr/local/lib/libevent-2.1.so.6...done.
Loaded symbols for /usr/local/lib/libevent-2.1.so.6
Reading symbols from /usr/local/lib/libsqlite3.so.0...done.
Loaded symbols for /usr/local/lib/libsqlite3.so.0
Reading symbols from /usr/local/lib/libicui18n.so.60...done.
Loaded symbols for /usr/local/lib/libicui18n.so.60
Reading symbols from /usr/local/lib/libicuuc.so.60...done.
Loaded symbols for /usr/local/lib/libicuuc.so.60
Reading symbols from /usr/local/lib/libicudata.so.60...
warning: Lowest section in /usr/local/lib/libicudata.so.60 is .hash at 0000000000000120
done.
Loaded symbols for /usr/local/lib/libicudata.so.60
Reading symbols from /lib/libcrypto.so.8...done.
Loaded symbols for /lib/libcrypto.so.8
Reading symbols from /usr/lib/libssl.so.8...done.
Loaded symbols for /usr/lib/libssl.so.8
Reading symbols from /usr/lib/libmagic.so.4...done.
Loaded symbols for /usr/lib/libmagic.so.4
Reading symbols from /lib/libm.so.5...done.
Loaded symbols for /lib/libm.so.5
Reading symbols from /lib/libthr.so.3...done.
Loaded symbols for /lib/libthr.so.3
Reading symbols from /usr/local/lib/rspamd/librspamd-actrie.so...done.
Loaded symbols for /usr/local/lib/rspamd/librspamd-actrie.so
Reading symbols from /usr/local/lib/libluajit-5.1.so.2...done.
Loaded symbols for /usr/local/lib/libluajit-5.1.so.2
Reading symbols from /usr/lib/libc++.so.1...done.
Loaded symbols for /usr/lib/libc++.so.1
Reading symbols from /lib/libcxxrt.so.1...done.
Loaded symbols for /lib/libcxxrt.so.1
Reading symbols from /lib/libc.so.7...done.
Loaded symbols for /lib/libc.so.7
Reading symbols from /lib/libgcc_s.so.1...done.
Loaded symbols for /lib/libgcc_s.so.1
Reading symbols from /usr/local/lib/libiconv.so.2...done.
Loaded symbols for /usr/local/lib/libiconv.so.2
Reading symbols from /lib/libz.so.6...done.
Loaded symbols for /lib/libz.so.6
Reading symbols from /libexec/ld-elf.so.1...done.
Loaded symbols for /libexec/ld-elf.so.1
#0  0x00000000004c0dca in rspamd_tokenizer_get_word (buf=0x0, cur=0x7fffffffdc98, token=0x7fffffffdc50, exceptions=<value optimized out>, is_utf=1, rl=0x7fffffffdc70, check_signature=<value optimized out>)
    at /construction/xports/mail/rspamd/work/rspamd-1.6.5/src/libstat/tokenizers/tokenizers.c:203
203     /construction/xports/mail/rspamd/work/rspamd-1.6.5/src/libstat/tokenizers/tokenizers.c: No such file or directory.
        in /construction/xports/mail/rspamd/work/rspamd-1.6.5/src/libstat/tokenizers/tokenizers.c
(gdb) bt full
#0  0x00000000004c0dca in rspamd_tokenizer_get_word (buf=0x0, cur=0x7fffffffdc98, token=0x7fffffffdc50, exceptions=<value optimized out>, is_utf=1, rl=0x7fffffffdc70, check_signature=<value optimized out>)
    at /construction/xports/mail/rspamd/work/rspamd-1.6.5/src/libstat/tokenizers/tokenizers.c:203
        siglen = Cannot access memory at address 0x0
Current language:  auto; currently minimal

**Comment by fatalbanana** [comment]
That's fixed in the master & rspamd-1.6 branch I believe.
