### ISSUE TITLE
Custom RBL has no weight altough configured

### ISSUE THREAD

**Issue by mhonicat** [rspamd/rspamd#2022]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5-4~jessie

### Operation system, CPU, memory and environment:
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.10 (jessie)
Release:	8.10
Codename:	jessie
### Description (Please provide a descriptive summary of the issue):

I added a custom RBL and for some reason the weight is always 0 when the IP is found in the RBL. My config looks like this:

#local.d/metrics.conf 
symbol "NIXSPAM_BL" {
    weight = 4.0;
    description = "From address is listed in dnsbl.manitu.net BL";
}
symbol "NIXSPAM" {
    weight = 4.0;
    description = "From address is listed in dnsbl.manitu.net BL";
}

#local.d/rbl.conf
rbls {

  nixspam {
    symbol = "NIXSPAM";
    rbl = "ix.dnsbl.manitu.net";
    returncodes {
    NIXSPAM_BL = "127.0.0.2";
    }
  }

Adding the "returncodes" Section was just to rule out some error here with the returncodes, but obviously it makes no difference. Score is always zero for that Symbol, no matter what i do. Also this Symbols weight is not overwritten somewhere else.

### Expected results:
Some Weigth added

### Actual results:
NIXSPAM_BL(0.00){194.42.7.8.ix.dnsbl.manitu.net : 127.0.0.2;}

**Comment by M4RC-J** [comment]
+1

**Comment by heraklit256** [comment]
Have you tried renaming "local.d/metrics.conf" to "local.d/rbl_group.conf"? Works here.

**Comment by ulab** [comment]
So funktioniert es bei mir:

local.d/rbl.conf
````
rbls {
   nixspam {
       symbol = "RBL_NIXSPAM";
       rbl = "ix.dnsbl.manitu.net";
   }
}
````

local.d/rbl_group.conf
````
symbols = {
    "RBL_NIXSPAM" {
        weight = 4.0;
        description = "From address is listed in NIXSPAM BL";
    }
}
````
