### ISSUE TITLE
Problems with WebUI: failing cause by mixed mode content

### ISSUE THREAD

**Issue by golodhrim** [rspamd/rspamd#2025]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5
### Description (Please provide a descriptive summary of the issue):
If you setup rspamd as described, and add nginx as a reverse proxy infront with ssl and a permanent redirect from port 80 to 443, and you setup the neighbours option in local.d/options.inc it is not displaying the neighbours cause of an mixed mode content problem that started to be blocked as of version 23 in firefox, IE 9 and Chrome short after ff23. A fix here would be to have an option to allow you to specify the protocol with which you like to get the information in neighbours.

### Steps to reproduce:
1. setup rspamd
2. configure nginx as reverse proxy with https for site
3. setup neighbours for both rspamds
4. try to access https site of rspamd's webui

### Expected results:
the Neighbours would be seen and their status and results would be displayed in the webui

### Actual results:
only an error is shown that the data couldn't be collected and that's it.

**Comment by moisseev** [comment]
You need to explicitly specify the protocol and port in the `host` directive:
```cfg
neighbours {
    server1 { host = "https://host1.example.com:443"; }
    server2 { host = "https://host2.example.com:443"; }
}
```
Otherwise it defaults to `http` and `11334` respectively.
