### ISSUE TITLE
Exits with error when given multiple sockets by systemd

### ISSUE THREAD

**Issue by argv-minus-one** [rspamd/rspamd#2034]
### Classification:

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility:

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

`1.7.0-0~git115~395c1e684~sid`

### Operation system, CPU, memory and environment:

Debian sid, Linux, x86-64, 16GB

### Description:

I wanted a setup where rspamd would listen on three worker sockets, all of which would be provided by systemd. However, it instead exits with a peculiar error.

### Steps to reproduce:

1. Install rspamd 1.7.0 like the Debian package (from `http://rspamd.com/apt/`) does.
2. Place the configuration files below.
3. `systemctl daemon-reload`
4. `systemctl start rspamd`

### Expected results:

Running rspamd.

### Actual results:

	Feb 22 18:35:21 rspamd[19126]: (main) <dee471>; main; systemd_get_socket: systemd LISTEN_FDS does not contain the expected fd: 3
	Feb 22 18:35:21 rspamd[19126]: (main) <dee471>; main; spawn_workers: cannot listen on systemd socket systemd:3: Value too large for defined data type
	Feb 22 18:35:21 rspamd[19126]: (main) <dee471>; main; spawn_workers: cannot create listen socket for controller at systemd:3
	Feb 22 18:35:21 rspamd[19126]: (main) <dee471>; main; rspamd_hard_terminate: kill worker 19127 as Rspamd is terminating due to an unrecoverable error
	Feb 22 18:35:21 rspamd[19126]: (main) <dee471>; main; rspamd_hard_terminate: shutting down Rspamd due to fatal error

`/proc/<pid>/environ` on the process (right before it exits) shows that systemd *did* supply 3 sockets:

	LANG=en_US.UTF-8
	PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
	LISTEN_PID=5113
	LISTEN_FDS=3
	LISTEN_FDNAMES=milter:scan:control
	HOME=/var/lib/rspamd
	LOGNAME=_rspamd
	USER=_rspamd
	SHELL=/bin/false
	INVOCATION_ID=2a41903ac33c4a6cbffaaf31e8afeb61
	JOURNAL_STREAM=9:236344

### Configuration:

	# /etc/rspamd/override.d/worker-controller.inc

	bind_socket = "systemd:3";

	# /etc/rspamd/override.d/worker-normal.inc

	bind_socket = "systemd:1";

	# /etc/rspamd/override.d/worker-proxy.inc

	bind_socket = "systemd:2";
	milter = yes;
	timeout = 120s;
	upstream "local" {
		default = yes;
		self_scan = yes;
	}

	# /etc/systemd/system/rspamd-control.socket

	[Unit]
	Description=rspamd control socket
	PartOf=rspamd.service

	[Socket]
	Service=rspamd.service
	ListenStream=%t/rspamd/control.socket
	SocketUser=_rspamd
	SocketGroup=rspamd-control-clients
	SocketMode=0660
	DirectoryMode=0711
	FileDescriptorName=control

	# /etc/systemd/system/rspamd-milter.socket

	[Unit]
	Description=rspamd milter socket
	PartOf=rspamd.service

	[Socket]
	Service=rspamd.service
	ListenStream=%t/rspamd/milter.socket
	SocketUser=_rspamd
	SocketGroup=rspamd-scan-clients
	SocketMode=0660
	DirectoryMode=0711
	FileDescriptorName=milter

	# /etc/systemd/system/rspamd-scan.socket

	[Unit]
	Description=rspamd scanning socket
	PartOf=rspamd.service

	[Socket]
	Service=rspamd.service
	ListenStream=%t/rspamd/scan.socket
	SocketUser=_rspamd
	SocketGroup=rspamd-scan-clients
	SocketMode=0660
	DirectoryMode=0711
	FileDescriptorName=scan

	# /etc/systemd/system/rspamd.service.d/override.conf

	[Service]
	Sockets=rspamd-scan.socket rspamd-milter.socket rspamd-control.socket

**Comment by fatalbanana** [comment]
Hi,

```Feb 22 18:35:21 rspamd[19126]: (main) <dee471>; main; systemd_get_socket: systemd LISTEN_FDS does not contain the expected fd: 3```

The rspamd service was started wrongly (not by socket activation). Socket activation works last I checked but does not play well with packaging (which wants to start the service): hence I would not recommend using it unless you're using your own builds.

Best,
-AL.

**Comment by argv-minus-one** [comment]
Being started from the service is not the problem. As you can see from the `/proc/*/environ` dump, systemd handed rspamd 3 socket FDs. (`LISTEN_FDS=3`) Also, the output of `ls -l /proc/*/fd` on the rspamd process shows that the 3 socket FDs (3, 4, and 5) are indeed open:

	total 0
	lr-x------ 1 _rspamd _rspamd 64 Feb 26 17:16 0 -> /dev/null
	lrwx------ 1 _rspamd _rspamd 64 Feb 26 17:16 1 -> socket:[216514]
	lrwx------ 1 _rspamd _rspamd 64 Feb 26 17:16 2 -> socket:[216514]
	lrwx------ 1 _rspamd _rspamd 64 Feb 26 17:16 3 -> socket:[216393]
	lrwx------ 1 _rspamd _rspamd 64 Feb 26 17:16 4 -> socket:[216398]
	lrwx------ 1 _rspamd _rspamd 64 Feb 26 17:16 5 -> socket:[216396]

This works because `Sockets=` on the service creates implicit dependencies on the socket units, so they get activated with the service anyway.

Also, I tried giving it a fourth dummy socket, and then rspamd started up without crashing. This suggests that there's an off-by-one bug in the code that handles looking up systemd-provided sockets.

**Comment by Lekensteyn** [comment]
This is not a bug.

For future readers, the problem is that the number is 0-based as opposed to 1-based. See https://www.rspamd.com/doc/workers/
```
bind_socket = "systemd:0"; # the first socket passed by systemd through environment (named sockets aren't supported)
```

The `Value too large for defined data type` error is shown when the requested file descriptor **index** is not present. Indeed, `systemd:3` is not present when `LISTEN_FDS=3`, the available options are `systemd:0`, `systemd:1`, and `systemd:2`.
