### ISSUE TITLE
Failed to start rspamd service due to nonexistent configuration file.

### ISSUE THREAD

**Issue by cosmo0920** [rspamd/rspamd#2044]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

rspamd.x86_64 0:1.6.6-4

### Operation system, CPU, memory and environment:

```log
$ cat /etc/redhat-release 
CentOS release 6.9 (Final)
```

### Description (Please provide a descriptive summary of the issue):

Failed to start rspamd service due to not found configuration file.

### Compile errors (if any):

None.

### Steps to reproduce:

1. Install from rspamd package from official rspamd repository.
   1. I've followed this installation instruction: https://rspamd.com/downloads.html
2. sudo service rspamd start

### Expected results:

Launch rspamd successfully.

### Actual results:

```
$ sudo service rspamd start
Starting rspamd: 2018-03-01 05:21:18 #13632(main) cfg; rspamd_config_read: cannot stat /etc/rspamd/rspamd.sysvinit.conf: No such file or directory
                                                           [FAILED]
```

### Configuration:

None. None of configuration is not modified.

### Additional information:

```log
$ LANG=C ls /etc/rspamd/rspamd.sysvinit.conf
ls: cannot access /etc/rspamd/rspamd.sysvinit.conf: No such file or directory
```

In `/etc/init.d/rspamd`, nonexistent `/etc/rspamd/rspamd.sysvinit.conf` is still referenced.

```conf
# ...
rspamd="/usr/bin/rspamd"
rspamadm="/usr/bin/rspamadm"
prog=$(basename $rspamd)

RSPAMD_CONF_FILE="/etc/rspamd/rspamd.sysvinit.conf"
RSPAMD_USER="_rspamd"
RSPAMD_GROUP="_rspamd"
```

`/etc/rspamd/rspamd.conf` should be used instead of old `/etc/rspamd/rspamd.sysvinit.conf` place.

**Comment by dajones70** [comment]
Still a problem with 1.7.3.  The /etc/init.d/rspamd script needs to have this line changed:
RSPAMD_CONF_FILE="/etc/rspamd/rspamd.sysvinit.conf"
to 
RSPAMD_CONF_FILE="/etc/rspamd/rspamd.conf"
