### ISSUE TITLE
add support for BitDefender Security for Mail Servers

### ISSUE THREAD

**Issue by s3rj1k** [rspamd/rspamd#2047]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [X] Not applicable

### Description (Please provide a descriptive summary of the issue):
Upstream binary:
http://download.bitdefender.com/SMB/Mail_Server_Security/BitDefender_Security_for_Mail_Servers/Unix/Current/EN/Linux/64bit/

Upstream doc:
http://download.bitdefender.com/SMB/Mail_Server_Security/BitDefender_Security_for_Mail_Servers/Unix/Current/EN/Documentation/Bitdefender_Security_for_Mail_Servers_UNIX_AdministratorsGuide.pdf

**Comment by celevra** [comment]
+1

**Comment by wojtekblazalek** [comment]
+1
