### ISSUE TITLE
History of "ALL SERVERS" not working

### ISSUE THREAD

**Issue by viktor-wbc** [rspamd/rspamd#2049]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [x] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.6.
### Operation system, CPU, memory and environment:
Ubuntu 16.04, 4 CPU Cores, 4096 MB RAM
### Description (Please provide a descriptive summary of the issue):
We're using 3 rspamd-Server. All of them are configured als neighbours. Since updating rspamd to 1.6.6. we get the error message

"Neighbours history backend versions do not match. Cannot display history."
 
when viewing the history of "ALL SERVERS". This happens no matter on which server I'm logged in on the WebGUI. Viewing the history of a single server works fine.

I double checked the rspamd version. All servers run on 1.6.6.

Please let me know, if you need further information!

Kind regards,

Viktor
### Configuration:
cat local.d/options.inc

neighbours {
  spamfilter10.domain.tld { host = "spamfilter10.domain.tld:11334"; }
  spamfilter11.domain.tld { host = "spamfilter11.domain.tld:11334"; }
  spamfilter12.domain.tld { host = "spamfilter12.domain.tld:11334"; }
}

cat local.d/redis.conf

write_servers = "spamfilter10.domain.tld";

read_servers = "round-robin:spamfilter10.domain.tld,spamfilter11.domain.tld,spamfilter12.domain.tld";

timeout = 60s;

**Comment by moisseev** [comment]
It is not about Rspamd versions, that message means the neighbors have different history backends. Check **history** versions:
```sh
curl --compressed -H "Password: XXXX" https://spamfilter10.domain.tld/history | head -c 20
curl --compressed -H "Password: XXXX" https://spamfilter11.domain.tld/history | head -c 20
curl --compressed -H "Password: XXXX" https://spamfilter12.domain.tld/history | head -c 20
```

**Comment by hensema** [comment]
I've got the same problem. On our 01 server there is no "version" property in the output, our 02 server has a version=2.

Both rspamd servers were installed simultaneously with identical config. For now they both use the same redis server; this will become a cluster before the rspamd cluster will enter production.

What could be going on here? How to remedy the problem?

**Comment by hensema** [comment]
Ok, solved it. Apparently the servers were running slightly different patchlevels of Ubuntu 18.04. After running updates the 01 server also has a version=2 property in the json. Note that rspamd itself wasn't updated.
