### ISSUE TITLE
skip duplicate symbol registration for FUZZY_PROB

### ISSUE THREAD

**Issue by ghost** [rspamd/rspamd#2068]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.0
### Operation system, CPU, memory and environment:
Debian 9, 2 * x5675, 48gb ecc, xenserver VM
### Description (Please provide a descriptive summary of the issue):
Logging:
skip duplicate symbol registration for FUZZY_PROB
skip duplicate symbol registration for FUZZY_DENIED
skip duplicate symbol registration for FUZZY_WHITE
skip duplicate symbol registration for FUZZY_UNKNOWN

After creating file: /local.d/fuzzy_check.conf and enabling:

    fuzzy_map = {
        FUZZY_DENIED {
            max_score = 20.0;
            flag = 1;
        }
        FUZZY_PROB {
            max_score = 10.0;
            flag = 2;
        }
        FUZZY_WHITE {
            max_score = 2.0;
            flag = 3;
        }

for my local fuzzy storage this log entrys appear in the top. fuzzy_map seems to no like that the symbols used are also defined in rule "rspamd.com" 

### Compile errors (if any):
no
### Steps to reproduce:
enable fuzzy check module and use fuzzy_map
### Expected results:
It should be possible to have symbols with same name in different fuzzy_maps in different rules without logging this errors
### Actual results:
skip duplicate symbols
### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
no
### Configuration:
# Rule for local fuzzy_worker 

rule "FUZZY_LOCAL" {
    # Fast hash type
    algorithm = "mumhash";

    # List of servers, can be an array or multi-value item
    servers = "127.0.0.1:11335";

    # Default symbol to insert (if no flags matches)
    symbol = "FUZZY_UNKNOWN";

    # List of additional mime types to be checked in this fuzzy ("*" for any)
    mime_types = ["*'"];

    # Maximum global score for all maps
    max_score = 20.0;

    # If this value is false, then allow learning for this fuzzy rule
    read_only = no;

    # Ignore flags that are not listed in maps for this rule
    skip_unknown = yes;

    fuzzy_map = {
        FUZZY_DENIED {
            max_score = 20.0;
            flag = 1;
        }
        FUZZY_PROB {
            max_score = 10.0;
            flag = 2;
        }
        FUZZY_WHITE {
            max_score = 2.0;
            flag = 3;
        }
    }

}

**Comment by vstakhov** [comment]
You cannot use the same symbols in different fuzzy rules.

**Comment by prilly** [comment]
That explain alot.

**Comment by vstakhov** [comment]
Well, in fact, you can, but you will see this notice about duplicate registration.
