### ISSUE TITLE
Reload causes lua_metric_symbol_callback error

### ISSUE THREAD

**Issue by tleuxner** [rspamd/rspamd#2069]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [X] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.0-1~stretch

### Description (Please provide a descriptive summary of the issue):
Reload causes lua_metric_symbol_callback error:

```
Mar 13 10:09:49 edi rspamd[13862]: <dae70c>; proxy; lua_metric_symbol_callback: call to (PHISHING) failed (2): /usr/share/rspamd/lua/url_redirector.lua:261: attempt to index local 'url' (a nil value); trace:
 [1]:{/usr/share/rspamd/lua/url_redirector.lua:261 - <unknown> [Lua]};
```

### Steps to reproduce:
systemctl reload rspamd

**Comment by vstakhov** [comment]
Oh no, not again. It means some Lua stack corruption which is literally impossible to find. Does it happen with 1.6.6?

**Comment by tleuxner** [comment]
I haven't noticed with 1.6.6 but it could be that I didn't have to reload the config as I didn't have to adapt new settings. Being on 1.7.0 with redis schemes converted I'm not sure I can provide more useful information.

**Comment by 1358** [comment]
I see this error in the logs for *every* mail, too. (rspamd 1.7.2)
```
10.4.2018, 07:29:58 | normal | 24067 | task | 78e282 | call to (SETTINGS_CHECK) failed (2): /usr/share/rspamd/lua/url_redirector.lua:261: attempt to index local 'url' (a nil value); trace: [1]:{/usr/share/rspamd/lua/url_redirector.lua:261 - [Lua]};
```
However, only one new rspamd instance (that was installed two weeks ago) is affected. Another one (1.7.2, too), that is running for about a year now and that was updated regularly, is *not* affected. Everything works fine there.

**Comment by ericmathison007** [comment]
I'm also seeing this error for every email. (rspamd 1.7.2)

> normal | 15447 | task | 42ac9c | call  to (SETTINGS_CHECK) failed (2):  /usr/share/rspamd/lua/url_redirector.lua:261: attempt to index local  'url' (a nil value); trace:  [1]:{/usr/share/rspamd/lua/url_redirector.lua:261 -  [Lua]};

**Comment by vstakhov** [comment]
All I can say is that this issue is almost impossible to debug and fix. @1358, are there any differences in config/rules between these two servers?

**Comment by ericmathison007** [comment]
@vstakhov is this error being caused by the URL redirector module? If so, does it mean that it isn't actually checking URLs for redirects? Do you suggest disabling the URL redirector module or just ignoring the error message?

**Comment by vstakhov** [comment]
No, it is caused by some hidden corruption deeply inside Lua/C API. From the experiences in the past, it was extremely hard to find and each time it was caused by a completely unrelated issue somewhere in the code.

**Comment by hildeb** [comment]
Just wanted to chime in that I'm also seeing this in 1.7.5 :/

**Comment by vstakhov** [comment]
Do you have any differences from the vanilla config?

**Comment by hildeb** [comment]
Yes, it's enabled

-rw-r--r-- 1 root root 3514 May 22 15:26 antivirus.conf
-rw-r--r-- 1 root root  123 May 17 00:00 classifier-bayes.conf
-rw-r--r-- 1 root root 1883 May 16 16:12 dkim_signing.conf
-rw-r--r-- 1 root root  407 May 23 15:53 options.inc
-rw-r--r-- 1 root root   57 May 16 13:27 redis.conf
-rw-r--r-- 1 root root   54 May 17 00:01 surbl.conf
-rw-r--r-- 1 root root  405 May 16 23:58 url_redirector.conf
-rw-r--r-- 1 root root  835 May 17 00:03 url_reputation.conf
-rw-r--r-- 1 root root  197 May 17 00:04 url_tags.conf
-rw-r--r-- 1 root root  103 May 16 13:27 worker-controller.inc
-rw-r--r-- 1 root root  672 May 18 10:06 worker-proxy.inc


Am Mi., 23. Mai 2018 um 17:01 Uhr schrieb Vsevolod Stakhov <
notifications@github.com>:

**Comment by vstakhov** [comment]
I need all custom configuration options you've set I'm afraid (you can send those to me privately if you want).

**Comment by hildeb** [comment]
I sent it to your highsecure.ru address...

**Comment by TheTesla** [comment]
Maybe it is related to: #2716 - systemctl reload rspamd spawns addtional processes and many processes in parallel access/manipulate the same state of the lua programm. This creates state conflicts.
