### ISSUE TITLE
Filebased Virus Scanner

### ISSUE THREAD

**Issue by nire2018** [rspamd/rspamd#2071]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [x] Not applicable

### Rspamd version:
all

### Operation system, CPU, memory and environment:
Linux

### Description (Please provide a descriptive summary of the issue):
Would it be possible to use a filebased virus scanner?

### Additional information:
For example like it is possible in Amavis:
['Sophos Anti Virus (sweep)', '/usr/local/bin/sweep',
   '-nb -f -all -rec -ss -sc -archive {}',
   [0,2], qr/Virus .*? found/,
   qr/^>>> Virus(?:(?: fragment)? '?(.+?)'? found)/,
 sub {$ENV{SAV_IDE}='/usr/local/sav'},
 ],

**Comment by vstakhov** [comment]
No it won't: it is unsafe, slow and stupid.
