### ISSUE TITLE
Empty headers can't be matched by regexp

### ISSUE THREAD

**Issue by smfreegard** [rspamd/rspamd#2077]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

1.7.1

### Operation system, CPU, memory and environment:

Linux

### Description (Please provide a descriptive summary of the issue):

It's not possible to look for empty headers using regexp:

-- Detects empty Subject header
reconf['EMPTY_SUBJECT'] = {
  re = 'Subject=/^\\s*$/H',
  score = 1.0,
  description = 'Subject header is empty',
  group = 'header'
}

### Steps to reproduce:

Install the rule above and create a message with a Subject: header that is empty or that contains spaces/tabs.

### Expected results:

EMPTY_MESSAGE symbol match

### Actual results:

Symbol does not fire.

**Comment by fatalbanana** [comment]
`header_exists(Subject) && !Subject=/.*/H` works for identifying both empty subject & subject containing only spaces though that doesn't seem like an ideal solution to me.

**Comment by vstakhov** [comment]
I don't understand the issue completely, I'm afraid.

**Comment by fatalbanana** [comment]
@smfreegard's question, AFAICT, is how does one match a header which is empty or contains only whitespace & I think I've answered that but I can't tell how to distinguish these cases (maybe that's fine).

**Comment by vstakhov** [comment]
But even an empty header should return `true` for header_exists.

**Comment by vstakhov** [comment]
Ah, I see the issue. You can use raw headers presumably.

**Comment by vstakhov** [comment]
In fact, if you have something like `Header:<space><crlf>` it won't be different from `Header:<crlf>` or from `Header:<space>*<crlf>` where * is Kleine-star.

**Comment by fatalbanana** [comment]
I managed not to think of using `/X` but it doesn't seem to help.

The problem seems to be that the spaces become part of the separator.

**Comment by vstakhov** [comment]
Agree, they should be moved to the value in case of empty headers.

**Comment by smfreegard** [comment]
Based on the corpus testing MISSING_SUBJECT .vs. EMPTY_SUBJECT will score significantly differently WRT hits on spam .vs. ham which is why I was trying to separate them into to  (as currently MISSING_SUBJECT will fire for both cases at the moment).

**Comment by smfreegard** [comment]
`````
root@localhost logs]# grep MISSING_SUBJECT smf.smf
MISSING_SUBJECT_NEW                         221     17   0.03    204   0.25   0.88   0.17
MISSING_SUBJECT                             423     71   0.14    352   0.44   0.75   0.32
`````

As you can see MISSING_SUBJECT_NEW is significantly better as it only tests for a missing header and not an empty header.
