### ISSUE TITLE
task:get_emails() doesn't get e-mail addresses from HTML message body

### ISSUE THREAD

**Issue by smfreegard** [rspamd/rspamd#2081]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

1.7.1

### Operation system, CPU, memory and environment:

Linux 

### Description (Please provide a descriptive summary of the issue):

I've been debugging a rule to count e-mail addresses in the message body that I'm getting poor corpus_test results for.

I've found that it isn't working properly if an HTML MIME part is being scanned.

### Steps to reproduce:

Run this message through rspamc:

````
Date: 2018-03-16 17:48:50 -0000
From: "Steve Freegard" <smf@fsl.com>
To: "Steve Freegard" <smf@fsl.com>
Subject: rspamd test
MIME-Version: 1.0
Content-Type: text/html; charset=us-ascii

<html>
<body>
This is a test

smf@fsl.com
smf@fsl.com

1.2.3.4
</body>
</html>
````

### Expected results:

emails = { 
    smf@fsl.com 
}

### Actual results:

No emails are found.  However if you change the Content-Type to text/plain, then they are correctly found.

For get_urls(), it will find URLs in the message body and in HREFs, but get_emails() doesn't work in the equivalent way, which is what I was expecting it to given that it returns `rspamd_url`

**Comment by vstakhov** [comment]
It is expected as all mail clients won't highlight URLs/Emails that are not decorated with <a> tag in HTML parts. Text parts are different however.

**Comment by smfreegard** [comment]
Ok - can we enhance this like urls then, allow them to be picked up by they would set is_html_displayed() == false?
