### ISSUE TITLE
Statistics on web interface are no longer shown since version 1.7

### ISSUE THREAD

**Issue by MHerbst** [rspamd/rspamd#2085]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [X] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7

### Operation system, CPU, memory and environment:
Ubuntu 16.04.1 VM running on Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz, 4 cores with 8 GB RAM

### Description (Please provide a descriptive summary of the issue):
I have configured a proxy (on caddy web server) for the web interface in order to access it from remote. Since the update to version 1.7 the pages "Status" and "Throughput" are no longer showing any information. Instead a short error message appears.
The display on pages "Configuration", "Symbols" and "History" are OK.

In the console of the Chrome browser I can see the following error when opening page "Throughput":
 ```
GET https://example.de/rspamd/stat 403 ()
```
The rspamd log shows the following message:
```
2018-03-17 15:11:52 #13025(controller) <ec9de1>; csession; rspamd_controller_handle_graph: absent graph type query                                                                                        
2018-03-17 15:12:12 #13025(controller) <b24df2>; csession; rspamd_controller_check_password: absent password has been specified  
```
In local.d/work-controller.inc I have defined password, enable_password and alos tried to set secure_ip to the local IP address of the rspamd server. But nothing help.

### Compile errors (if any):
-
### Steps to reproduce:
Login to WebUI and open pages "Stat", "Throuput"

### Expected results:
Display of statistics and graphs.

### Actual results:
Nothing shown.

**Comment by MHerbst** [comment]
With version 1.7.3 the behaviour has changed a bit:

- page "Througput" now works
- The result of `GET https://example.de/rspamd/stat` is status code 403
- The result of `GET https://example.de/rspamd/errors` is also status code 403

**Comment by soerenkornetzki** [comment]
I can confirm this issue. Since my Debian Stretch machine updated rspamd to the 1.7.x version tree, statistics etc. are gone.

When the GUI is loaded, the password is queried. When a wrong password is entered, the GUI will notify the user about the wrong password. When the correct password is entered, the GUI will let the user enter but there is no data at all.

Within the error log I have the following (as MHerbst):

    csession; rspamd_controller_check_password: absent password has been specified
