### ISSUE TITLE
Cannot override default actions since 1.7.0

### ISSUE THREAD

**Issue by azurit** [rspamd/rspamd#2088]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.0

### Steps to reproduce:
I'm trying to completely disable 'reject' and 'greylist' actions. Until 1.7.0, it was possible with this:
override.d/metrics.conf:
actions {
        add_header = 6;
}

Since 1.7.0, this doesn't work anymore. I also tried these, none worked:

override.d/actions.conf:
add_header = 6;

actions.conf.override:
actions {
    add_header = 6;

    .include(try=true; priority=1; duplicate=merge) "$LOCAL_CONFDIR/local.d/actions.conf"
    .include(try=true; priority=10) "$LOCAL_CONFDIR/override.d/actions.conf"
}

The only way how to do this in 1.7.0 seems to be directly editing actions.conf.

**Comment by vstakhov** [comment]
You should be able to specify `reject = null` from 1.7.1.

**Comment by johnwmail** [comment]
After upgrade to 1.7.1, I tried config  greylist = null in local.d/actions.conf
then run rspamadm configtest, it show error messages like this

call to rspamadm lua script failed (2): /usr/local/share/rspamd/lib/lua_cfg_transform.lua:272: attempt to compare userdata with number; trace: [1]:{/usr/local/share/rspamd/lib/lua_cfg_transform.lua:272 - <unknown> [Lua]};
symbol 'ARC_INVALID' has its score defined but there is no corresponding rule registered
symbol 'ARC_NA' has its score defined but there is no corresponding rule registered
symbol 'ARC_DNSFAIL' has its score defined but there is no corresponding rule registered
symbol 'ARC_REJECT' has its score defined but there is no corresponding rule registered
symbol 'ARC_ALLOW' has its score defined but there is no corresponding rule registered
syntax OK

If I remove greylist = null, the error message "lua script failed" will gone
call to rspamadm lua script failed (2): /usr/local/share/rspamd/lib/lua_cfg_transform.lua:272: attempt to compare userdata with number; trace: [1]:{/usr/local/share/rspamd/lib/lua_cfg_transform.lua:272 - <unknown> [Lua]};

Is this OK?
Thanks.

**Comment by johnwmail** [comment]
Sorry for my english,

I mean rspamadm configtest show the error, if I set greylist = null in local.d/actions.conf

call to rspamadm lua script failed (2): /usr/local/share/rspamd/lib/lua_cfg_transform.lua:272: attempt to compare userdata with number; trace: [1]:{/usr/local/share/rspamd/lib/lua_cfg_transform.lua:272 - [Lua]};

Is it normal and expected?
rspamd version is 1.7.1
Thanks.

**Comment by moisseev** [comment]
It was fixed in 1.7.2 with https://github.com/vstakhov/rspamd/commit/c32c0ca0ee8727633bef81a2188135c20f1e1329

**Comment by johnwmail** [comment]
Yes, patch this on fixed, thank you.

https://github.com/vstakhov/rspamd/commit/c32c0ca0ee8727633bef81a2188135c20f1e1329
