### ISSUE TITLE
rspamd profile for AppArmor

### ISSUE THREAD

**Issue by arodier** [rspamd/rspamd#2099]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [x] Not applicable

### Rspamd version:
Debian package

### Operation system, CPU, memory and environment:
Debian

### Description (Please provide a descriptive summary of the issue):
I have added an rspamd profile for AppArmor, you can find the last version here:
https://github.com/progmaticltd/homebox/blob/master/install/playbooks/roles/rspamd/templates/apparmor.d/usr.bin.rspamd

### Additional information:
Can this profile be included into the Debian package, by any chance?

**Comment by vstakhov** [comment]
Hum, I'm not very familiar with AppArmor I'm afraid. Is there any possible impact for a wide range of Debian or Ubuntu users if adding that to the packages?

**Comment by fatalbanana** [comment]
Possible issue is users who might not know they are using AppArmor or be familiar with it (it's default-enabled on Ubuntu) might try have Rspamd read files from unusual places & not know why it doesn't work.

Another issue is versioning: the policy may need changes for different versions of AppArmor/platforms. That situation may be better in future with introduction of policy versioning.

Policy may also need to be updated if Rspamd starts doing something new or reading different paths for some reason.

I've been running Rspamd confined with AppArmor for a long time without issue but I'm not sure it'd be wise to enable it in the distribution at this point.

**Comment by arodier** [comment]
I agree it should not be enabled by default, but maybe as part of the documentation, for instance in /usr/share/doc/rspamd/usr.bin.apparmor-sample
Maybe even in complain mode.
It will be helpful for those who want to use AppArmor and not want to write the profile from scratch.
I agree you would have to update it every time rspamd do something different.

**Comment by arodier** [comment]
AppArmor is going to be enabled by default on Debian. I will provide my AppArmor profile for you to put in the Documentation.

@fatalbanana, if the user is adventurous enough to change the default location of the executables, then he is probably proficient in Linux and have some basic knowledge of AppArmor.
