### ISSUE TITLE
Cannot reset web history - rspamd_controller_check_password: using password as enable_password for a privileged command

### ISSUE THREAD

**Issue by ghost** [rspamd/rspamd#2112]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [X] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [x] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
* 1.7.1

### Operation system, CPU, memory and environment:
* Debian Stretch
* Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz
* 32GB RAM

### Description (Please provide a descriptive summary of the issue):
When I click on the red "Reset" button above the history in Rspamd, the history does not get deleted. The web ui does not report anything at all, but in the server log I find a couple of lines all saying

`rspamd_controller_check_password: using password as enable_password for a privileged command`

I am logged in with the password created at installation. The installation was done using the recommended guide at https://thomas-leister.de/mailserver-debian-stretch/

### Compile errors (if any):
n/a

### Steps to reproduce:
* Open Rspamd in browser
* Click History
* Click Reset

### Expected results:
* History list empty

### Actual results:
* Nothing changes

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
n/a

### Configuration:
See https://thomas-leister.de/mailserver-debian-stretch/

### Additional information:
n/a

**Comment by hettipeti** [comment]
This also happens to me on Rspamd 1.7.5.
Just installed on Debian.

**Comment by VolFestion** [comment]
Quick and simple and not right way is deleting file: `/var/lib/rspamd/rspamd.history`
```
systemctl stop rspamd
rm -rf /var/lib/rspamd/rspamd.history
systemctl start rspamd

```
Legacy way is using `rspamd /historyreset` command. But I can not work it.
See docs here: 
https://rspamd.com/doc/workers/controller.html#supported-commands
