### ISSUE TITLE
Bayes tokens have to be relearned after Restarts

### ISSUE THREAD

**Issue by tleuxner** [rspamd/rspamd#2131]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.2-2~stretch
### Description (Please provide a descriptive summary of the issue):
After Rspamd is restarted it will require new learns for Bayes classes it previously had enough learns:
 
`Mar 30 08:39:06 edi rspamd[7861]: <edbb4e>; proxy; bayes_classify: skip classification as ham class has not enough learns: 21, 200 required`

This behavior leads to periods of time where the Bayes classification will not take place although there should be enough tokens there already.
### Steps to reproduce:
Restart or upgrade Rspamd.
### Expected results:
Bayes classification continues to work as before and does not require new learns.

**Comment by vstakhov** [comment]
That's very weird. What backend are you using?

**Comment by tleuxner** [comment]
redis:

```
classifier "bayes" {
  tokenizer {
    name = "osb";
  }

  min_tokens = 11;
  backend = "redis";
  min_learns = 200;
  autolearn = true;

  statfile {
    symbol = "BAYES_HAM";
    spam = false;
  }
  statfile {
    symbol = "BAYES_SPAM";
    spam = true;
  }
  new_schema = true;
  per_user = true;
  expire = 100d;
  
  learn_condition =<<EOD
return function(task, is_spam, is_unlearn)
  local prob = task:get_mempool():get_variable('bayes_prob', 'double')

  if prob then
    local in_class = false
    local cl
    if is_spam then
      cl = 'spam'
      in_class = prob >= 0.95
    else
      cl = 'ham'
      in_class = prob <= 0.05
    end

    if in_class then
      return false,string.format('already in class %s; probability %.2f%%',
        cl, math.abs((prob - 0.5) * 200.0))
    end
  end

  return true
end
EOD
}
```

**Comment by tokred** [comment]
Not sure if same problem, but after updating from 1.6.6 to 1.7.2 I ran `rspamadm configwizard` as instructed and it said something about converting 20k+ Bayes pattern to new schema.

However, now rspamc stats tells me there is nothing learned:

```
Statfile: BAYES_SPAM type: redis; length: 76; free blocks: 0; total blocks: 2; free: 0.00%; learned: 0; users: 1; languages: 0
Statfile: BAYES_HAM type: redis; length: 76; free blocks: 0; total blocks: 2; free: 0.00%; learned: 0; users: 1; languages: 0
```

:(

**Comment by r0one** [comment]
please reopen this issue :(

**Comment by r0one** [comment]
PS: I actually don't have this issue. I'm only in [this case](https://github.com/rspamd/rspamd/issues/3105): redis backend always prints `length: 0`, but my learned emails are kept.

**Comment by Routhinator** [comment]
This still seems to be a problem in 2024. I am wondering if this is because the keys are somehow related to the hostname in some way as in my case the rspamd instance is in K8S pods, so the podname (hostname) changes on restart.
