### ISSUE TITLE
auth_only -> sign_auth

### ISSUE THREAD

**Issue by bjoe2k4** [rspamd/rspamd#2137]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Additional information:
The `auth_only` directive for DKIM related modules should be renamed to `sign_auth` to be compatible with `sign_local`, `sign_networks` and `sign_inbound` and to avoid ambiguity (the name `auth_only` may suggest that authenticated users are signed exclusively). For backwards compatibility it should be checked for both. 

If desired i could submit a pull request.

**Comment by vstakhov** [comment]
The problem is that there is no way to distinguish absent value and `false` stored in Lua table.
