### ISSUE TITLE
Add ed25519-sha256 DKIM alogrithm

### ISSUE THREAD

**Issue by bjoe2k4** [rspamd/rspamd#2147]
### Classification (Please choose *one* option):

* [x] Enhancement

### Additional information:
- should have low priority as not yet final rfc.
- Current progress: https://datatracker.ietf.org/doc/draft-ietf-dcrup-dkim-crypto/
- rspamd already has some ed25519 implementation, not sure if it can be reused?
- if implemented, there should be an option to include rsa signature as well (double signing).

**Comment by vstakhov** [comment]
They use slightly different ed25519 AFAIR but I might be wrong.

**Comment by andreasschulze** [comment]
I'm running a ed25519 capable signer and verifier if you're interested in interop tests one day..

**Comment by vstakhov** [comment]
It is added now.

**Comment by bjoe2k4** [comment]
Is it possible to sign with both rsa-sha256 and ed25519-sha256? Afaict, there is option to advise rspamd to do double signing.

**Comment by vstakhov** [comment]
Signing supports RSA only so far.

**Comment by bjoe2k4** [comment]
I think there is something wrong with the current implementation (or just the tests are wrong). See my comment in 15a5ad7fa3b877472b5ee7e14883623763eb2bed.

**Comment by vstakhov** [comment]
It contradicts with 4.1 in the same document then.

**Comment by andreasschulze** [comment]
@bjoe2k4 seeb to be correct
https://tools.ietf.org/html/draft-ietf-dcrup-dkim-crypto-13#section-4.1 define sig-a-tag-k =/ "ed25519"
https://tools.ietf.org/html/rfc6376#section-3.5 define sig-a-tag-alg  = sig-a-tag-k "-" sig-a-tag-h
so the a=ed25519-sha256, not only a=ed25519

**Comment by bjoe2k4** [comment]
Now that RFC 8463 is out of the door, there should be an easy way to sign with both ed25519 and rsa. :->
