### ISSUE TITLE
hundreds of connections to port 53

### ISSUE THREAD

**Issue by flixman** [rspamd/rspamd#2148]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.2

### Operation system, CPU, memory and environment:
Debian

### Description (Please provide a descriptive summary of the issue):
Rspamd establishes and keeps open a number of UDP connections (so far, 200), to port 53.

### Steps to reproduce:
Start using Rspamd, and wait some minutes before running netstat

### Expected results:
No connections are kept alive (although this might be expected behavior?).

### Actual results:
Getting around 200 result lines from "netstat -puta" like:
udp        0      0 192.168.1.2:44148       62.81.16.148:53         ESTABLISHED 24964/rspamd: norma

**Comment by vstakhov** [comment]
UDP has no connections obviously so there is nothing wrong about this behaviour. Rspamd uses socket pool to provide source port randomisation when doing a DNS request.

**Comment by flixman** [comment]
Indeed, UDP has no connections. However, as reported [here](https://stackoverflow.com/a/10841788/2602550), UDP sockets connected via the connect call will accept only packets from the named connection, and appear with the status "ESTABLISHED".

After some more research, all the lines displayed by netstat for rspamd can be reduced to 4, with 48 connections for each one of my nameservers in /etc/resolv.conf. Why is needed to create and maintain so many sockets for each one of 4 servers? (By the way, thank you for answering. I really appreciate your time for rspamd and these issues).

**Comment by vstakhov** [comment]
I have explained the reason why the pool of sockets is created. I don't understand why do you care about that.

**Comment by flixman** [comment]
I am trying to understand why there is a need for a pool of UDP sockets to a reduced number of DNS servers. What is its purpose? Network performance?

**Comment by fabianfrz** [comment]
@flixman The system may reuse the same source port as for the previous connection. In that case, the port number would not be random anymore and it would be easy to spoof DNS answers (to manipulate the result).
That is what @vstakhov probably wants to tell you.

**Comment by flixman** [comment]
Thank you very much for the explanation :-) I did not know it was "that" easy to spoof DNS answers.
