### ISSUE TITLE
rspamd_dynamic map is not well generated

### ISSUE THREAD

**Issue by stephdl** [rspamd/rspamd#2154]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [x] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.2

### Operation system, CPU, memory and environment:
Centos7

### Description (Please provide a descriptive summary of the issue):
The rspamd_dynamic map is not well generated/rewritten whereas the ucl sent the good parameters ([20,11,10,4] for example) all the time

### Steps to reproduce:
In the ucl 

- increment the grey,spam,add,rewrite  score (one or more settings at each time)
- save
- refresh the page
- check the rspamd_dynamic map

Do it several time and you will see only the last modification written in the map

### Expected results:
all modified scores in the ucl (from the static configuration) are written to the rspamd_dynamic

### Actual results:
only the last score modification is added to the rspamd_dynamic map, my concern is that if you restart rspamd when the rspamd_dynamic is false , then the old scores from the static file are reloaded and used.

**Comment by stephdl** [comment]
I started again with a stock rspamd without configuration by my onw, thank  to `rspamadm configwizard`. I just added a standard configuration to use the ucl
```
password = "$2$x8q3rb5uyu3sbbu199rwr5c1kwgxhxac$xc8crc5ccubn4m958ndnah3r389p31jfxdoyyqkti4ab1iho9msb";
enable_password = "$2$x8q3rb5uyu3sbbu199rwr5c1kwgxhxac$xc8crc5ccubn4m958ndnah3r389p31jfxdoyyqkti4ab1iho9msb";
    # socket for worker-controller
    bind_socket = "*:11334";
```
I wanted to be sure that my configuration could not be the source of the issue    

Then in the ucl I modified symbols, scores and I can reproduce the topic of the issue, the rspamd_dynamic doesn't store the full modified settings, just modify, save, refresh, check rspamd_dynamic.
My concern is if you don't restart the service, probably there is no issue, but when restarting static configuration are applied.
Where I'm wrong please, something odd here

**Comment by bjoe2k4** [comment]
I am confused. ucl = Universal control language. I think you mean WebUI. 

Anyways, i can confirm this bug.

**Comment by vstakhov** [comment]
Yes, this is a long living issue and I see no good solution for it.

**Comment by stephdl** [comment]
Would you please give some pointers to understand what it occurs. Since the rspamdUI gets the precedence on the static configuration file, it could bring some issues and some bug reports
