### ISSUE TITLE
rspamc learn_ham / learn_spam did not train Neural network module

### ISSUE THREAD

**Issue by paede81** [rspamd/rspamd#2160]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.2
### Operation system, CPU, memory and environment:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
### Description (Please provide a descriptive summary of the issue):
It's not possible to train the Neural network module with some spam/ham mail samples via rspamc
### Steps to reproduce:
run rspamc learn_ham / learn_spam with some mail samples
### Expected results:
learn vectors increase
### Actual results:
learn vectors did not increase:
2018-04-10 15:30:05 #12661(controller) <tzdcjf>; lua; neural.lua:825: no need to learn ANN tSHORTDE985A2DA858C801260 6 learn vectors (30 required)
2018-04-10 15:30:05 #12661(controller) <tzdcjf>; lua; neural.lua:825: no need to learn ANN tLONGDE985A2DA858C801260 36 learn vectors (100 required)
just increase when new mail arrive and it's within defined score

**Comment by Koopman** [comment]
This happens for me as well on 1.7.5. Is this a bug or a feature (maybe the message means something else)?

**Comment by heraklit256** [comment]
I am also interested in this. Seems like `rspamc` needs another classifier name for the neural network but it does not became clear what it is.

**Comment by allliv** [comment]
+1 moving messages from Spam to Inbox and from Inbox to Spam, but learn vectors did not increase...

**Comment by heraklit256** [comment]
`- ping -`

Solving this issue would really help me a lot, as there are many spam mails classified as such in Bayes, but neural network says they are ham and adds some negative score.

**Comment by phaoost** [comment]
I am getting this in the recent release also
