### ISSUE TITLE
Logrotate is not working anymore

### ISSUE THREAD

**Issue by sschindel** [rspamd/rspamd#2189]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.3-1~stretch

### Operation system, CPU, memory and environment:
Debian Stretch

### Description (Please provide a descriptive summary of the issue):
Logrotate is not working anymore, more precisely /etc/init.d/rspamd reopenlog is not working anymore. I guess this is related to #2166. No PIDfile -> no reopenlog...

### Expected results:
Logrotate should work again :)

**Comment by vstakhov** [comment]
That should be fixed in 1.7.3-2

**Comment by sschindel** [comment]
Thanks! I'll close this issue. It has been fixed.

**Comment by iq180** [comment]
Are you sure it's fixed? I get the same error in 1.7.5.

**Comment by vstakhov** [comment]
It is system depending, so I don't know what is broken in your case

**Comment by iq180** [comment]
As in this <https://github.com/vstakhov/rspamd/issues/2166>  case –

 

«ExecStart» contains «–f»

and

«Type=forking» is absent

 

in the .service file.

**Comment by vstakhov** [comment]
Perhaps we need to invite Lennart to fix this .service file. I have no fucking idea about how it should be written I'm afraid.

**Comment by vstakhov** [comment]
And, btw, it works just fine in Debian/Centos7 so far.
