### ISSUE TITLE
ONCE_RECEIVED_STRICT triggers if sender has unknown hostname - HFILTER_HOSTNAME_UNKNOWN

### ISSUE THREAD

**Issue by Jayd603** [rspamd/rspamd#2190]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):

If HFILTER_HOSTNAME_UNKNOWN is triggered, ONCE_RECEIVED_STRICT also triggers despite there being multiple received headers.  This leads to a much higher score than expected and in the case I saw, resulted in mail going to spam folder when it should have still made it to the inbox.

**Comment by vstakhov** [comment]
Some Received headers do not have any sane data, such as relay addresses or other details (e.g. Received from qmail MTA). These headers are not evaluated by Rspamd.

**Comment by MinerGuy1111** [comment]
These are the received headers from the senders side, this doesn't include the few that are added on my end.  I got the sender to fix the unknown hostname and the ONCE_RECEIVED_STRICT went away and of course the unknown hostname trigger. Nothing else appeared to have changed with the headers other than one hostname no longer showing as unknown.

Received: from dmzservice.REDACTED.com (unknown [72.71.190.26])
	by web.redacted.com (Postfix) with ESMTP id 96D5997B5D
	for <receiver@redacted.net>; Tue, 17 Apr 2018 09:47:31 -0400 (EDT)
Received: from mailhost.REDACTED.com (unknown [10.10.0.104])
	by dmzservice.REDACTED.com (Postfix) with ESMTP id E003F800A3
	for <receiver@redacted.net>; Tue, 17 Apr 2018 09:39:16 -0400 (EDT)
Received: from mailhost.REDACTED.com (localhost [127.0.0.1])
	by mailhost.REDACTED.com (Postfix) with ESMTP id BC3B851C13
	for <receiver@redacted.net>; Tue, 17 Apr 2018 09:39:16 -0400 (EDT)
Received: from [10.8.0.46] (unknown [10.8.0.46])
	by mailhost.REDACTED.com (Postfix) with ESMTPS id 9FD1F51C12
	for <receiver@redacted.net>; Tue, 17 Apr 2018 09:39:16 -0400 (EDT)

X-Spamd-Result: default: False [10.24 / 12.00];
	 RCVD_NO_TLS_LAST(0.00)[];
	 HFILTER_HOSTNAME_UNKNOWN(2.50)[];
	 MIME_GOOD(-0.10)[text/plain];
	 ARC_NA(0.00)[];
	 DMARC_NA(0.00)[REDACTED.net];
	 ASN(0.00)[asn:13672, ipnet:72.71.190.0/18, country:US];
	 TO_MATCH_ENVRCPT_ALL(0.00)[];
	 FROM_EQ_ENVFROM(0.00)[];
	 RCVD_COUNT_THREE(0.00)[4];
	 TO_DN_ALL(0.00)[];
	 PREVIOUSLY_DELIVERED(0.00)[receiver@redacted.net];
	 HFILTER_HELO_NORES_A_OR_MX(0.30)[dmzservice.REDACTED.com];
	 IP_SCORE(0.44)[ip: (1.13), ipnet: 72.71.190.0/18(0.56), asn: 13672(0.45), country: US(0.05)];
	 HFILTER_HELO_IP_A(1.00)[dmzservice.REDACTED.com];
	 RCPT_COUNT_ONE(0.00)[1];
	 ONCE_RECEIVED_STRICT(4.00)[static];
	 FROM_HAS_DN(0.00)[];
	 R_SPF_NA(0.00)[];
	 AUTH_NA(2.00)[];
	 R_DKIM_NA(0.00)[];
	 GREYLIST(0.00)[pass,body];
	 MID_RHS_MATCH_FROM(0.00)[];
	 ONCE_RECEIVED(0.10)[]

**Comment by vstakhov** [comment]
I cannot say anything without the exact email samples I'm afraid.

**Comment by MinerGuy1111** [comment]
I will need to message you directly. 

Is vsevolod@highsecure.ru acceptable?

**Comment by vstakhov** [comment]
Yes, you can use my gpg key to encrypt messages if something is sensitive there.
