### ISSUE TITLE
UTF Error 'invalid utf escape'

### ISSUE THREAD

**Issue by pkalemba** [rspamd/rspamd#2194]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [X] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.3 ,master
### Operation system, CPU, memory and environment:
Debian 8 ,
### Description (Please provide a descriptive summary of the issue):
Rspamd cannot parse input 
Logs:
`rspamd[7235]: (rspamd_proxy) <f78acf>; proxy; proxy_backend_parse_results: cannot parse input: error while parsing <unknown>: line: 1, column: 763 - 'invalid utf escape', character: 'p'
rspamd[7235]: (rspamd_proxy) <f78acf>; proxy; proxy_backend_master_finish_handler: cannot parse results from the master backend
rspamd[7235]: (rspamd_proxy) <f78acf>; milter; rspamd_milter_send_task_results: cannot find scan results, tempfail
`
### Steps to reproduce:
Send mail with '%1e' string in url
SMTP Transaction:
`<-  220 test2  ESMTP
 -> EHLO test
<-  250-test2
<-  250-PIPELINING
<-  250-SIZE 104850000
<-  250-ETRN
<-  250-ENHANCEDSTATUSCODES
<-  250-8BITMIME
<-  250 DSN
 -> MAIL FROM:<null@example.com>
<-  250 2.1.0 Ok
 -> RCPT TO:<test2@example.com>
<-  250 2.1.5 Ok
 -> DATA
<-  354 End data with <CR><LF>.<CR><LF>
 -> Date: Mon, 23 Apr 2018 15:22:03 +0200
 -> To: test2@example.com
 -> From: null@example.com
 -> Subject: test Mon, 23 Apr 2018 15:22:03 +0200
 -> X-Mailer: swaks v20130209.0 jetmore.org/john/code/swaks/
 ->
 -> https://foo%1epoo.com
 ->
 -> .
<** 451 4.7.1 Service unavailable - try again later
 -> QUIT
<-  221 2.0.0 Bye
=== Connection closed with remote host.
`
### Expected results:
Mail should be accepted. No errors.
### Actual results:
Rspamd respond with tempfail.

### Additional info:
Tested on strings. If after %1e is character from a-f it works for the rest it fail like on list:
```
a OK
b OK
c OK
d OK
e OK
f OK
g FAIL
h FAIL
i FAIL
j FAIL
k FAIL
l FAIL
m FAIL
n FAIL
o FAIL
p FAIL
q FAIL
r FAIL
s FAIL
t FAIL
u FAIL
v FAIL
w FAIL
x FAIL
y FAIL
z FAIL

```

**Comment by normanu** [comment]
I'm still seeing this error https://github.com/mailcow/mailcow-dockerized/issues/1377#issuecomment-388285931

Although in the mail I don't see a link with %1e in it.

**Comment by andryyy** [comment]
We are not yet using this fix.

**Comment by normanu** [comment]
@andryyy aha that explains that :)
