### ISSUE TITLE
antivirus quarantine not working or i don't know how to configure

### ISSUE THREAD

**Issue by markusweb** [rspamd/rspamd#2197]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug/Question
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.3

### Operation system, CPU, memory and environment:
ubuntu 16.04 LTS

### Description (Please provide a descriptive summary of the issue):
how to put mails with viruses in quarantine? i have the following config:

```
antivirus {
    clamav {
        attachments_only = false;
        patterns {
            JUST_EICAR = "^Eicar-Test-Signature$";
        }
        symbol = "CLAM_VIRUS";
        type = "clamav";
        action = "quarantine";
        servers = "/var/run/clamav/clamd.ctl";
        whitelist = "/etc/rspamd/antivirus.wl";
    }
}

```
with action "reject" the mail is correctly rejected:
mail.log shows:
 milter-reject: END-OF-MESSAGE from web.heise.de[193.99.144.71]: 5.7.1 clamav: virus found: \"Eicar-Test-Signature\"; from=<emailcheck-robot@ct.de> to=<tickethilfe@wuppertallive.de> proto=ESMTP helo=<web.heise.de>

if i change action to "quarantine" then
mail.log
`Apr 25 12:55:13 xxx postfix/lmtp[10677]: 9515A1A0488: to=<zzz@xxx.de>, relay=xxx..de[private/dovecot-lmtp], delay=0.41, delays=0.39/0/0/0.02, dsn=2.0.0, status=sent (250 2.0.0 <zzz@xxx.de> mLGTO5Be4Fq2KQAABLa3ug:2 Saved)`
clamav.logs:
`Wed Apr 25 12:55:12 2018 -> instream(local): Eicar-Test-Signature(eefde7ec2f536d390c8c9ea00a7c3716:1913) FOUND`

mail is in my inbox

how can i change this so that mails are put in quarantine? best would be if they are stored let's say under /var/vmail/quarantine

is this a rspamd problem or do i have to change postfix config?

thanxs

markus

**Comment by ashceryth** [comment]
Please correct me if I'm wrong, but I don't think that there is an action "quarantine" in Rspamd. Take a look here: https://rspamd.com/doc/configuration/metrics.html

**Comment by ashceryth** [comment]
Maybe you can try to achieve something like a "quarantine" with Postfix milter_header_checks (http://www.postfix.org/postconf.5.html#milter_header_checks) filtering on the CLAM_VIRUS symbol in X-Spamd-Result header.

**Comment by vstakhov** [comment]
You can replace `reject` action by `quarantine` if you are using Rspamd proxy. Just set:

```
# local.d/worker-proxy.inc
quarantine_on_reject = true;
```

It will tell your MTA to quarantine messages with scores above `reject` threshold.

**Comment by croessner** [comment]
Search for rspamd-quarantine here on Github 😉

**Comment by croessner** [comment]
https://github.com/sys4/rspamd-quarantine

I haven written this as an example that works very well
