### ISSUE TITLE
Solaris Intel, failure to identify endian results in DNS lookup failure

### ISSUE THREAD

**Issue by beiDei8z** [rspamd/rspamd#2204]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [X] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.3

### Operation system, CPU:
Solaris 11.3, Intel little endian

### Description:
Compilation fails to identify the big/little endian value. This means a default of big endian is used.  This causes the DNS header to be corrupted, a "recursion desired" value of 128 not 1 is sent and so no reply is received.  No DNS look-ups are done and rspamd is limited(!).

### Expected results:
src/config.h (from config.h.in) should define on Intel:
 #define LITTLE_ENDIAN   1234
 #define BIG_ENDIAN      4321
 #define BYTE_ORDER LITTLE_ENDIAN
and on Sparc:
 #define BYTE_ORDER BIG_ENDIAN

### Actual results:
No define for LITTLE_ENDIAN nor BIG_ENDIAN and "#if BYTE_ORDER == BIG_ENDIAN" in "contrib/librdns/dns_private.h" defaults to true.

### Additional information:
[patch.txt](https://github.com/vstakhov/rspamd/files/1958657/patch.txt)

I have edited "config.h.in" to include:
#elif defined(__sun)
 #include <sys/byteorder.h>
 #define LITTLE_ENDIAN   1234
 #define BIG_ENDIAN      4321
 #ifdef _LITTLE_ENDIAN
  #define BYTE_ORDER LITTLE_ENDIAN
 #else
  #define BYTE_ORDER BIG_ENDIAN
 #endif

and added "config.h" to "contrib/librdns/dns_private.h".  There is some other little/big endian code in "contrib/t1ha/t1ha.h" which I have not tried to understand.

**Comment by beiDei8z** [comment]
The "stale bot" added "wontfix", wrong, a fix has been applied so it's already been fixed.

**Comment by vstakhov** [comment]
So why cannot you close this? Or should I manually check each of ~300 issues that are in the opened state? I know that I could use something like `Closes: #2204` in the commit message but I forget to do that from time to time :(

**Comment by beiDei8z** [comment]
I'm sorry but I did not see it as my place to close until you were satisfied.  I run projects on a ticking systems and in those the polite form is to request feedback then close when all parties are happy.
The initial fix was applied upstream ad not to a release, in my opinion the issue is not fixed until it is publicly released.  As I have more to do that run your project that moment passed me by.
Спасибо.

**Comment by vstakhov** [comment]
No need to apologise, thank you for your contributions! I'm just trying to remove stale or fixed issues. The list of 300 entries has turned to be completely unmanageable.
