### ISSUE TITLE
rspamd will NOT start after upgrade to 1.7.4

### ISSUE THREAD

**Issue by ghost** [rspamd/rspamd#2210]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.4
### Operation system, CPU, memory and environment:
Debian 9 - Xen VM
### Description (Please provide a descriptive summary of the issue):
Rspamd will not start - Systemctl status rspamd.service gives this:

May 01 21:17:32 mx1 systemd[1]: rspamd.service: Failed with result 'exit-code'.
May 01 21:17:33 mx1 systemd[1]: rspamd.service: Service hold-off time over, scheduling restart.
May 01 21:17:33 mx1 systemd[1]: Stopped rapid spam filtering system.
May 01 21:17:33 mx1 systemd[1]: rspamd.service: Start request repeated too quickly.
May 01 21:17:33 mx1 systemd[1]: Failed to start rapid spam filtering system.
May 01 21:17:33 mx1 systemd[1]: rspamd.service: Unit entered failed state.
May 01 21:17:33 mx1 systemd[1]: rspamd.service: Failed with result 'exit-code'.

### Compile errors (if any):
pre built .deb
### Steps to reproduce:
systemctl start rspamd.service
### Expected results:
starting rspamd
### Actual results:
fails to start

**Comment by prilly** [comment]
rspamd log:

2018-05-01 21:23:03 #1565(main) <nts5yo>; cfg; rspamd_config_read: rcl parse error: required attribute 'type' is missing for section 'worker', current key: backend = "redis";
expire = 7776000;
allow_update [
    "localhost",
    "127.0.0.1",
    "::1",
]
bind_socket = "localhost:11335";
sync = 60;

**Comment by prilly** [comment]
inside rspamd.conf

# Local fuzzy storage is disabled by default

worker "fuzzy" {
    bind_socket = "localhost:11335";
    count = -1; # Disable by default
    .include "$CONFDIR/worker-fuzzy.inc"
    .include(try=true; priority=1,duplicate=merge) "$LOCAL_CONFDIR/local.d/worker-fuzzy.inc"
    .include(try=true; priority=10) "$LOCAL_CONFDIR/override.d/worker-fuzzy.inc"
}

I have enabled worker "fuzzy" by creating the file rspamd.conf.local and iam adding this:

# Local fuzzy storage

worker {
    bind_socket = "*:11335";
    .include "$CONFDIR/worker-fuzzy.inc"
    .include(try=true; priority=1,duplicate=merge) "$LOCAL_CONFDIR/local.d/worker-fuzzy.inc"
    .include(try=true; priority=10) "$LOCAL_CONFDIR/override.d/worker-fuzzy.inc"
}

on your page: https://rspamd.com/doc/workers/fuzzy_storage.html you provide this example for worker fuzzy: 

worker {
   type = "fuzzy";
   bind_socket = "*:11335";
   hashfile = "${DBDIR}/fuzzy.db"
   expire = 90d;
   allow_update = ["127.0.0.1", "::1"];
}

The parameter: type = "fuzzy"; and expire = 90d; are missing from the default rspamd.conf file. the old versionof this the worker fuzzy was commented out and not disabled with count= -1
adding the paramter type = "fuzzy"; to rspamd.conf.local fuzzy worker makes rspamd start again.

**Comment by vstakhov** [comment]
That is the obsolete syntax. I've removed it in the default config after about 2 years of being obsoleted. The correct syntax is:

```
worker "<type>" {
...
}
```

**Comment by himbeere** [comment]
Got that error too. had to switch back to 1.7.3 to sort things out first.

```
nested section: phishing { phishing { ... } }, it is likely a configuration error
nested section: greylist { greylist { ... } }, it is likely a configuration error
rcl parse error: required attribute 'type' is missing for section 'worker', current key: task_timeout = 8;
bind_socket = "localhost:11333";
mime = true;
```

**Comment by himbeere** [comment]
Ok. Got that "required attribute 'type' is missing for section 'worker'" sorted out. The "nested section" errors seem to be a little bit more trickier.

**Comment by prilly** [comment]
Please update example configuration of fuzzy storage:  https://rspamd.com/doc/workers/fuzzy_storage.html
If its 2 years sins this has been absolute, you need to consider a reworok of the docs.. as long as the documentations says it should be type = "fuzzy"; then that is the correct way.

**Comment by prilly** [comment]
in the rspamd.conf section under logging. type is also used.
https://github.com/vstakhov/rspamd/blob/master/conf/rspamd.conf

Please be consistent in configuration and docs.

**Comment by prilly** [comment]
yes for shure. can you provide a how to for that?

**Comment by moisseev** [comment]
[Contributing to rspamd.com web-site](https://rspamd.com/doc/tutorials/site_contributing.html). btw, this article can be improved as well ;)

**Comment by gramels** [comment]
Hi this update broke my setup.
I need some hints where to look to fix it.
