### ISSUE TITLE
Build fail of 1.7.4 on ARM32

### ISSUE THREAD

**Issue by mattreeve** [rspamd/rspamd#2214]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.4

### Operation system, CPU, memory and environment:
Debian Stretch, ARM32 (Odroid XU4), 2GB RAM

### Description (Please provide a descriptive summary of the issue):
Version 1.7.4 is failing to build, 1.7.3 was fine as were previous versions.

### Compile errors (if any):
In file included from /usr/lib/arm-linux-gnueabihf/glib-2.0/include/glibconfig.h:9:0,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /home/matt/scratch/rspamd.174/src/config.h:301,
                 from /home/matt/scratch/rspamd/src/libcryptobox/cryptobox.c:22:
/home/matt/scratch/rspamd/src/libcryptobox/cryptobox.c: At top level:
/usr/include/glib-2.0/glib/gmacros.h:232:53: error: size of array ‘_GStaticAssertCompileTimeAssertion_1’ is negative
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED
                                                     ^
/usr/include/glib-2.0/glib/gmacros.h:229:47: note: in definition of macro ‘G_PASTE_ARGS’
 #define G_PASTE_ARGS(identifier1,identifier2) identifier1 ## identifier2
                                               ^~~~~~~~~~~
/usr/include/glib-2.0/glib/gmacros.h:232:44: note: in expansion of macro ‘G_PASTE’
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED
                                            ^~~~~~~
/home/matt/scratch/rspamd/src/libcryptobox/cryptobox.c:1480:1: note: in expansion of macro ‘G_STATIC_ASSERT’
 G_STATIC_ASSERT (sizeof (t1ha_context_t) ==
 ^~~~~~~~~~~~~~~
src/CMakeFiles/rspamd-server.dir/build.make:112: recipe for target 'src/CMakeFiles/rspamd-server.dir/libcryptobox/cryptobox.c.o' failed
make[2]: *** [src/CMakeFiles/rspamd-server.dir/libcryptobox/cryptobox.c.o] Error 1
CMakeFiles/Makefile2:1608: recipe for target 'src/CMakeFiles/rspamd-server.dir/all' failed
make[1]: *** [src/CMakeFiles/rspamd-server.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

### Steps to reproduce:
Build on an ARM32 platform.

### Expected results:
Successful build

### Actual results:
Failed build

### Additional information:
Something to do with the platform being 32 bit I suspect, or some other hardware dependent thing?

**Comment by Mattpenfold** [comment]
Can confirm the same issue building on Raspbian Stretch on a Raspberry Pi 3 (based on Debian Stretch). The OS is 32 bit.
