### ISSUE TITLE
Feature: Integrate alterMIME support to Rspamd

### ISSUE THREAD

**Issue by tachtler** [rspamd/rspamd#2221]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [x] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [x] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):
Please intergrate alterMIME support into Rspamd like done in AMaViS.

### Expected results:
Integration of alterMIME.

### Actual results:
No possibility to add a Footer on outgoing email before DKIM-signing.

**Comment by vstakhov** [comment]
I don't think it will be supported, I'm afraid. Rspamd is not intended to modify message parts in any way.

**Comment by tachtler** [comment]
Hi Vsevolod,

thank you for your reply. 

If you take it exactly, rspamd should not change the e-mail, but only offer the possibility to call "alterMIME".

When adding X-Headers, will the email actually change? Yes, OK not the content or the body, but the header?

What do you think?
Klaus.

**Comment by mpizzoli** [comment]
Hi,
I am writing just as an rspamd user that would benefit from this feature
for sure.
This would open up a whole set of opportunities.

+1 for me

Marco

**Comment by zimnysbrain** [comment]
I believe that without this functionality we can’t consider rspamd for wide or commercial use
Pointless 
Admin is responsible for domain control ex disclaimer etc
This task can’t be from the user side (through signature example)
Can’t believe that we give up open source idea agains MS solutions just because someone developed great peace of software without any support from the other coders

**Comment by croessner** [comment]
Why should alterMIME be a task for Rspamd? Why do you not write a small Milter for this?

**Comment by andryyy** [comment]
What the schmuck...

I don’t see this as a function for a spam filter, too.

**Comment by tachtler** [comment]
Hi Christian,

if I were such a gifted programmer like you, but maybe you'll accept this challenge for yourself?

Thank you in advance
Klaus. :1st_place_medal:

**Comment by croessner** [comment]
Off topic: What about this solution:

https://www.google.de/amp/s/www.howtoforge.com/how-to-automatically-add-a-disclaimer-to-outgoing-emails-with-altermime-postfix-on-debian-squeeze/amp/

I did not test this. Just quickly used Google

**Comment by tachtler** [comment]
Hi Christian,

add a disclaimer after DKIM signing (by rspmad) seems not a really good idea?

Or I'm wrong with the example you google'd?

Thank you
Klaus.

**Comment by andryyy** [comment]
That's a good point. :-)

**Comment by tachtler** [comment]
Hi,

if I had a wish, I would wish for the following:

`/etc/postix/master.cf`
```
smtpd     pass  -       -       n       -       -       smtpd
  -o smtpd_milters=${spf_milter},${opendkim_milter},${opendmarc_milter},
      ${altermime_milter_by_christian_roessner},${rspamd_milter}
```
**AND**

`/etc/postfix/main.cf`
```
# SPF (spf-milter)
spf_milter = inet:192.168.0.70:10011
# OpenDKIM (opendkim-milter)
opendkim_milter = inet:192.168.0.70:10012
# OpenDMARC (opendmarc-milter)
opendmarc_milter = inet:192.168.0.70:10013
# alterMIME (altermime_milter_by_christian_roessner})
altermime_milter_by_christian_roessner}= inet:192.168.070:10014
# RSpamd (rspamd-milter)
rspamd_milter = inet:192.168.070:10015
```

Thank you "Santa Claus"
Klaus.

**Comment by vstakhov** [comment]
Why do you need spf-milter, opendkim milter and opendmark milter? If you have extra CPU resources you can mine some cryptocurrencies for me and leave the rest on Rspamd.

**Comment by andryyy** [comment]
You could also use multiple hops to first use a content_filter (and maybe default_filter_nexthop to define the milter-activated smtpd as next-hop) or check this out: https://github.com/dploeger/disclaimr

**Comment by tachtler** [comment]
Hi Vsevolod,

it was an example from my existing AMaViS installation, and yes your're right the spf-milter, opendkim_milter and the opendmarc_milter will be obsolet with rspamd.

Thank you
Klaus.

**Comment by tachtler** [comment]
Hi André,

thank you for the link, the project seems to be great, BUT a simple solution without DJANGO-Framework, WEB-GUI etc. will be o.k. for me.

A possible alterMIME-milter will be a resource solving solution for me!

But thank you for the link!
Klaus.

**Comment by croessner** [comment]
@tachtler, you could ask Patrick and I could write you the Milter for alterMIME.

**Comment by andryyy** [comment]
@patrickbenkoetter *trigger*

**Comment by yoshimo** [comment]
> I believe that without this functionality we can’t consider rspamd for wide or commercial use
>Pointless
>Admin is responsible for domain control ex disclaimer etc
>This task can’t be from the user side (through signature example)
Why can't you do that as a client-side "signature" ?

**Comment by tachtler** [comment]
Hi yoshimo,

it was NOT my post, but configure a signature for a few clients o.k - BUT if you have more clients (2.000 or more) you whish to have a solution like alterMIME...

Klaus.

**Comment by vstakhov** [comment]
I'm now playing with `rspamadm mime` tool. Probably, I'll be able to create mime structure from a task. If that goes fine, then there will be couple of small steps to implement MIME modifications functions. The main problem is to restore MIME structure for complex messages.

**Comment by tachtler** [comment]
Hi Vsevolod,

nice to hear that, hope you will be successful"

Thank you!
Klaus.

**Comment by vstakhov** [comment]
This is now done: Rspamd can add headers, remove headers, add HTML signature, add plain text signature using new `rspamadm mime modify` routine. It is also clever enough to skip pgp signed parts not to break pgp/smime signatures.

**Comment by tachtler** [comment]
Hi Vsevolod,

thank you for the implementation!

Klaus.

**Comment by HelloooNanny** [comment]
I am struggling to make the mime modify command work.

Rspamd was installed as a part of a mailcow server on a VPS. Running all the latest versions.

This is what I have done:

cd /root/mailcow-dockerized

Then created footer.txt and footer.html in this folder. Then:

docker-compose exec rspamd-mailcow rspamadm mime modify -t footer.txt -H footer.html

ButI have the following error:

Usage: rspamadm mime modify [-h] [-a <header=value>] [-r <header>]
[-R <header=pattern>] [-t <file>] [-H <file>]
<file> [<file>] …

Error: missing argument ‘file’
ERROR: 1

It would be great if someone could help me.

Thanks

**Comment by am1github** [comment]
I was trying to implement this with a `content_filter` for `submission` in Postfix `master.cf`, but i think this is the wrong way, because `content_filter` is an **AFTER_QUEUE** filter in Postfix, while `smtpd_milters` is a **BEFORE_QUEUE** filter.

So the **DKIM signature** will break/fail or not?

@vstakhov 
Can you give me a hint how to use that the right way?
I think this must be running before the DKIM signing is reached...

@tachtler 
Did you implement this? How? PS: I wrote you an email thru GMail. :-)

Thanks in advance guys!

**Comment by m3nu** [comment]
You ever found a solution, @am1github ? Been looking for one too. Even opendkim would be a milter.

**Comment by m3nu** [comment]
Thanks for sharing this project, @tachtler 🙏

Works well. Finally I can sign AND have a disclaimer.

Also great documentation. The only thing I changed was to run the Systemd service with reduced privileges and as service user.

**Comment by aqs-pau** [comment]
Thanks for this, works good.
However when I enable it my dkim sign from rspamd isn't applied anymore.

Any idea?

**Comment by m3nu** [comment]
Maybe a setting in rspamd?

I had issues with attachments that suddenly showed up in the message as normal text. So went back to altermime for now.

**Comment by aqs-pau** [comment]
I fix my issue. actually rspamd was set up in the main.cf with the smtpd_milters and it was the same parameter used in the master.cf to enable FooterMilter, so as the master overwrite the main, the dkim sign was not applied.
