### ISSUE TITLE
BASE64 errors from rspamd dmarc reporting

### ISSUE THREAD

**Issue by xpunkt** [rspamd/rspamd#2225]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):

X-Spam-Report: 
	*  1.1 DMARC_NONE DMARC check neutral
	* -0.1 SPF_PASS SPF: sender matches SPF record
	*  0.7 SPF_HELO_NONE SPF: HELO does not publish an SPF Record
	*  0.1 FROM_IN_TO From: does match To:
	*  2.7 BASE64_LENGTH_78_79 BODY: No description available.
	* -1.9 BAYES_00 BODY: Bayes spam probability is 0 to 1%
	*      [score: 0.0000]
	*  1.5 BASE64_LENGTH_79_INF BODY: base64 encoded email part uses line
	*      length greater than 79 characters
	*  1.1 DCC_CHECK Detected as bulk mail by DCC (dcc-servers.net)

### Steps to reproduce:

wait for rspamd dmarc report

### Expected results:

it should not make base64 errors in spamassassin

### Actual results:

reports does not import in Mail::DMARC cpan module

**Comment by vstakhov** [comment]
I cannot tell you anything without samples. From the code, I can definitely say that Rspamd should fold base64 encoded messages on 78 characters boundary. Furthermore, it is not 'base64 error', it is some SA rule which is irrelevant to the issue. Finally, I have no ideas what is `Mail::DMARC` CPAN module and I cannot process further without message sample.

**Comment by vstakhov** [comment]
Oh, I know the reason about line length.
