### ISSUE TITLE
Millions of dollars rule

### ISSUE THREAD

**Issue by robertboyl** [rspamd/rspamd#2232]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [x ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):

consider a "a lot of money", million dollars rule.

was discussed in rspamd list, with subject [rspamd] repost (no reply) about Lots of money rules, pls reply :))"

see https://pastebin.com/dY6iFeYL

Thanks.

**Comment by andryyy** [comment]
You can easily set this up yourself with multimap, like...

```
BAD_CONTENT {
    type = "content";
    filter = "text";
    map = "${LOCAL_CONFDIR}/maps/bad_content.map";
    regexp = true;
    score = 10.00;
}
```

Just a very basic example. Also see https://rspamd.com/doc/modules/multimap.html

**Comment by robertboyl** [comment]
Thanks! Will try.

But not good to have by default in rspamd?


2018-05-07 15:51 GMT-03:00 André Peters <notifications@github.com>:

**Comment by robertboyl** [comment]
One more, where rspamd didnt detect a major spam, Spamassassin surely has rules for this type of spam. Can you guys pls add something?

See

X-Rspamd-Report: 	R_DKIM_ALLOW(-0.2) R_SPF_ALLOW(-0.2) MIME_GOOD(-0.1) DMARC_POLICY_ALLOW(-0.5) MISSING_TO(2) IP_SCORE(-0.806362) INTRODUCTION(2)
X-Rspamd-Score: 	2.193638
X-EmailArray-EnvFrom: 	boa.i@yahoo.com

Dear friend,

I never forget you,I am Mr.Julius gull, an auditing debt manager ( B.O.A ) Bank of Africa, i contacted you for deal last time, i just want to let you know that i have executed the deal and i kept some money for your compensation, meanwhile contact my secretary through this email address ( info.payment007@gmail.com ) so she will send you visa card worth's sum of (€400.000.00Euro), her name is MS YENTCHABRE YENDOUKOI.

Mr.Julius gull.

**Comment by andryyy** [comment]
Maybe Julius is just very generous.

**Comment by robertboyl** [comment]
1 more case, false negative, hoax, that mentions a large sum of money.

https://pastebin.com/PXMeCQ2G

**Comment by robertboyl** [comment]
1 more, see https://pastebin.com/SAn1t0Rr

sample:

This is why I am contacting you. With the trend of events in Sao Tome and Principe, we shall be able to lift a minimum of 300,000 barrels of BLCO per month. This will fetch us an average of US$28 million per month.

**Comment by robertboyl** [comment]
one more: https://pastebin.com/GYdvWibu

**Comment by robertboyl** [comment]
one more: https://pastebin.com/Maebqi3X

**Comment by robertboyl** [comment]
https://pastebin.com/3A8ax1FY

**Comment by robertboyl** [comment]
https://pastebin.com/AY1eNJJf

**Comment by robertboyl** [comment]
https://pastebin.com/ZwSaGp5g
