### ISSUE TITLE
Disable checking outbound mail

### ISSUE THREAD

**Issue by VolFestion** [rspamd/rspamd#2234]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ X ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.4

### Operation system, CPU, memory and environment:
Ubuntu, CentOS

### Description (Please provide a descriptive summary of the issue):
When I use user settings module then outbound mail do not check and score = 0.00/6 with no symbols.
But the reply module do not work also.
How can I check outbound mail flow only for reply module?

### Expected results:
RSPMAD do not apply any checks for outbound mail except reply module one.

### Configuration:
*** Section settings ***
authenticated {
    apply {
        default {
            symbols_enabled [
                "REPLY",
            ]
        }
    }
    priority = "high";
    ip = "10.0.0.0/16";
    ip = "192.168.0.0/24";
}

*** End of section settings ***

**Comment by croessner** [comment]
It looks like your settings are incorrect. Please compare yours with the documentation:

https://rspamd.com/doc/configuration/settings.html

**Comment by VolFestion** [comment]
I do not see any misconfiguration user settings.
But it works strange in my case.
For example, if it uses set of symbols_disabled for outbound mail them do not apply to messages.
So I do not understand how to config the module right.
