### ISSUE TITLE
High CPU load with neural.lua

### ISSUE THREAD

**Issue by amotl** [rspamd/rspamd#2242]
Dear Vsevolod, Andrew and the whole Rspamd community,

first things first: Thank you so much for conceiving and maintaining such a nice piece of software. We have been looking for a replacement to our MIMEDefang/SpamAssassin-based antispam subsystem, found Rspamd and did not have to look any further.

After getting started, looking at the architecture and operating it for a while, we have the pleasure to say
> ## Rspamd is to Antispam what Nginx is to the Web.

However, after running Rspamd for some weeks, we ran into an issue with version 1.7.4 on one of our machines and will do our best to describe it using the form below.

----

### Classification:

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [X] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility:

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
    $ rspamd --version
    Rspamd daemon version 1.7.4

### Operation system, CPU, memory and environment:

    $ hostnamectl
    Chassis: vm
    Virtualization: xen
    Operating System: Debian GNU/Linux 8 (jessie)
    Kernel: Linux 3.16.0-6-amd64
    Architecture: x86-64

    $ free -m
                 total       used       free     shared    buffers     cached
    Mem:          5019       3504       1515         31        314        536
    -/+ buffers/cache:       2653       2366
    Swap:         1023        901        122

    $ nproc
    4

### Description:
The Rspamd controller processes suddenly started hogging CPU on one of our machines. We found #1256, #1952 and #2079, but this one is different. It happens after running Rspamd for some minutes and seems to be related to the training subsystem as the processes in question leave these traces in `/var/log/rspamd/rspamd.log`:

    2018-05-15 06:55:39 #6810(controller) <7scw3d>; lua; neural.lua:677: learned 1 iterations, error: 0.132674
    2018-05-15 06:57:19 #6810(controller) <7scw3d>; lua; neural.lua:677: learned 2 iterations, error: 0.030800

After all, the CPU usage starts increasing **after** new child processes have been spawned from the `rspamd: controller process`.

In this screenshot, you can see three Rspamd controller processes at 100% each. This is about 15 minutes after restarting Rspamd, as each of the child processes spawned for neural network training appears in a succession of - let's say - 5 minutes?

![image](https://user-images.githubusercontent.com/453543/40037861-b0af5058-580f-11e8-93ef-811d269f4dc0.png)

The behavior appeared this morning out of the blue. As we fear Rspamd will continue to create more worker processes of this nature in intervals of 5 minutes, killing them infrequently currently keeps us busy ;].

Do you have any ideas what could possibly have gone wrong with our Rspamd setup? 

Thanks in advance for your efforts!

With kind regards,
Andreas.

**Comment by amotl** [comment]
In fact the controller process spawned yet another child, each maxing out one of the four available cores:

![image](https://user-images.githubusercontent.com/453543/40041691-2bad1e0c-581f-11e8-9d55-d393de96a375.png)

**Comment by amotl** [comment]
## Problem
> As we fear Rspamd will continue to create more worker processes of this nature in intervals of 5 minutes, killing them infrequently currently keeps us busy ;].

Literally. This had to stop ;].

## Workaround
We used the excellent [Monit](https://mmonit.com/monit/) program to monitor the Rspamd process and kill the controller process children going haywire and want to share its configuration.

### /etc/monit/conf.d/rspamd
```bash
# Tame Rspamd controller processes going haywire
#
# Watch all "rspamd: controller process" instances and trigger an action
# if one of them uses 100% CPU. As this machine currently has 4 CPUs, this
# event will yield a total cpu usage of 24.9%, so we just trigger at 23%.
#
# The script "/usr/local/bin/tame-rspamd" will just kill all child processes
# of the master "rspamd: controller process" process instance.

check process rspamd matching "rspamd: controller process"
    if total cpu usage > 23% for 2 cycles then exec "/usr/local/bin/tame-rspamd"
```

### /usr/local/bin/tame-rspamd
```bash
#!/bin/sh
#
# Tame Rspamd controller processes going haywire
#
# The monit configuration snippet "/etc/monit/conf.d/rspamd" will watch all
# "rspamd: controller process" instances and trigger an action (this script)
# if one of them uses 100% CPU. This script will just kill all child processes
# of the master "rspamd: controller process" instance.

# We can't use $MONIT_PROCESS_PID here, as this would be an *arbitrary* one of
# the multiple "rspamd: controller process" instances on the system,
# most probably *not* the parent process upon the "pkill" invocation should occur.

# Kill all child processes of the master "rspamd: controller process"
for pid in $( pgrep --full 'rspamd: controller process' ); do
    pkill --signal TERM --parent $pid
done
```

**Comment by c-rosenberg** [comment]
We had the same issue when using the example with long and short and I learned from Vsevolod we had to many max_trains with to many symbols in the long part. So one learn cycle could not be finished before another starts. For now we reduced max_trains to 500 and the problem is gone.

**Comment by amotl** [comment]
Thanks a bunch, @c-rosenberg. Will give this a shot.

**Comment by amotl** [comment]
Hey @c-rosenberg and @vstakhov,

we finally found some time to follow up on this and we are happy to describe our findings.

## Your recommendations
### Decrease `max_train` setting in `neural.conf`
we finally had the chance to apply your suggestions to our configuration:
```diff
diff -u /etc/rspamd/modules.d/neural.conf.dist /etc/rspamd/modules.d/neural.conf

@@ -17,7 +17,15 @@
   #servers = 127.0.0.1:6379; # Redis server to store learning data and ANN

   train {
-    max_train = 1k; # Number of trains per epoch
+
+    # Original setting
+    #max_train = 1k; # Number of trains per epoch
+
+    # Mitigate "High CPU load with neural.lua"
+    # Thanks, c-rosenberg and Vsevolod!
+    # See also: https://github.com/vstakhov/rspamd/issues/2242#issuecomment-389078551
+    max_train = 500; # High CPU load with neural.lua.
```

## Our observations
Unfortunately, the behavior still exists. We tried to collect some more information, maybe this helps to get hold of the issue.

### What is being learned by `neural.lua`

It is all about learning the single `ANN tRFANN417CB51E3C7A88C3260`:
```
2018-07-12 17:25:59 #22594(controller) <erbn63>; lua; neural.lua:810: check ANN tRFANN417CB51E3C7A88C3260
2018-07-12 17:25:59 #22594(controller) <erbn63>; lua; neural.lua:817: need to learn ANN tRFANN417CB51E3C7A88C3260 after 1015 learn vectors (500 required)
2018-07-12 17:22:59 #22594(controller) <erbn63>; lua; neural.lua:787: lock ANN tRFANN417CB51E3C7A88C3260 for learning
```

Different processes seem to work on that job over a while:
```
$ tail -n5000 /var/log/rspamd/*.log | grep learned
2018-07-12 17:13:41 # 4774(controller) <erbn63>; lua; neural.lua:674: learned 1 iterations, error: 0.097172
2018-07-12 17:19:32 #25492(controller) <erbn63>; lua; neural.lua:674: learned 17 iterations, error: 0.005676
2018-07-12 17:20:29 #32478(controller) <erbn63>; lua; neural.lua:674: learned 4 iterations, error: 0.017189
2018-07-12 17:20:45 #27225(controller) <erbn63>; lua; neural.lua:674: learned 11 iterations, error: 0.017772
2018-07-12 17:21:54 #28979(controller) <erbn63>; lua; neural.lua:674: learned 8 iterations, error: 0.015013
2018-07-12 17:23:57 # 1785(controller) <erbn63>; lua; neural.lua:674: learned 3 iterations, error: 0.029340
2018-07-12 17:24:13 #30709(controller) <erbn63>; lua; neural.lua:674: learned 6 iterations, error: 0.010706
2018-07-12 17:25:45 # 4774(controller) <erbn63>; lua; neural.lua:674: learned 2 iterations, error: 0.032655
2018-07-12 17:26:03 # 6448(controller) <erbn63>; lua; neural.lua:674: learned 1 iterations, error: 0.097172
```

while others trying to chime in will get locked out:
```
2018-07-12 17:24:59 #22594(controller) <erbn63>; lua; neural.lua:789: do not learn ANN tRFANN417CB51E3C7A88C3260, locked by another process
```

So far so good, right?

### What this leaves behind
On our _Debian GNU/Linux 8 (jessie)_ machine with _Linux Kernel 3.16.56-1+deb8u1_ running _Rspamd version 1.7.7_, the learning process seems to leave the very same worker processes behind which have been involved in successful learning (deduced from `neural.lua:674: learned 4 iterations`), as can be seen in this process tree:
```
ps axf | grep rspamd
22588 ?        Ss     0:01 rspamd: main process
22593 ?        S      0:01  \_ rspamd: rspamd_proxy process (localhost:11332)
22594 ?        S      1:02  \_ rspamd: controller process (localhost:11334)
25492 ?        R     67:24  |   \_ rspamd: controller process (localhost:11334)
27225 ?        R     56:46  |   \_ rspamd: controller process (localhost:11334)
28979 ?        R     47:05  |   \_ rspamd: controller process (localhost:11334)
30709 ?        R     37:23  |   \_ rspamd: controller process (localhost:11334)
32478 ?        R     27:48  |   \_ rspamd: controller process (localhost:11334)
 1785 ?        R     20:19  |   \_ rspamd: controller process (localhost:11334)
 4774 ?        R     13:42  |   \_ rspamd: controller process (localhost:11334)
 6448 ?        R      7:40  |   \_ rspamd: controller process (localhost:11334)
 8223 ?        R      2:29  |   \_ rspamd: controller process (localhost:11334)
22595 ?        SL     0:03  \_ rspamd: normal process (localhost:11333)
22596 ?        SL     0:10  \_ rspamd: normal process (localhost:11333)
22597 ?        S      0:05  \_ rspamd: hs_helper process
```
Unfortunately, each of these worker processes is consuming 100% CPU and the processes keep spawning moderately, so this will exhaust the 4-core machine after 45-90 minutes.

## Disclaimer
We completely admit we actually don't know what we are doing and maybe your recommendation would be to disable the FANN feature completely unless we actually will know what we are doing. However, we are running Rspamd with mostly vanilla settings and we thought you might be interested what is going on with our instance - at least we would like to ;].

## Question
Do you have any ideas what we could do to get hold of the problem or to get deeper into debugging this specific feature? Maybe you already have an idea about what we are running into we are humbly asking to share with us.

## Credits
Last but not least, thanks again for your great work on Rspamd, @vstakhov and all contributors!

**Comment by amotl** [comment]
For all others coming here in search for a quick solution:

We disabled the ANN learning completely by configuring in `/etc/rspamd/local.d/neural.conf`:
```
# Disable ANN learning due to high CPU load
# See also: https://github.com/vstakhov/rspamd/issues/2242
enabled = false;
```

However, we still would be interested to find out what might be going wrong with our setup.
