### ISSUE TITLE
Meaningful rspamc exit codes

### ISSUE THREAD

**Issue by DavidePrincipi** [rspamd/rspamd#2274]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

```text
[root@vm8 ~]# rpm -q rspamd
rspamd-1.7.5-1.x86_64
```

### Operation system, CPU, memory and environment:

```text
[root@vm8 ~]# uname -a
Linux vm8.dpnet.nethesis.it 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@vm8 ~]# free -mh
              total        used        free      shared  buff/cache   available
Mem:           991M        609M        115M        2.9M        266M        202M
Swap:          1.0G        401M        622M
```

### Description

The `rspamc` command always exits with 0, even if it fails to connect the rspamd server which is an error condition. Providing a non-zero exit code would help to integrate it with other tools, like getmail.

### Steps to reproduce:

- stop the rspamd service
- run rspamc 
- `echo $?`

### Expected results:

I'd expect a non-zero exit code if the connection fails for any reason. Furthermore I'd expect the error message is sent to stderr.

### Actual results:

rspamc exits with 0 exit code and prints 

```text
[root@vm8 ~]# rspamc
helloworld
Results for file: stdin (0.004 seconds)
IO write error: Connection refused
```

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):

n/a

### Configuration:

n/a

### Additional information:

Running on NethServer/CentOS

**Comment by vstakhov** [comment]
That would be very hard to implement as `rspamc` can scan multiple files/directories etc.

**Comment by DavidePrincipi** [comment]
Thank you for your answer, but sorry I don't understand :blush:
