### ISSUE TITLE
Received IPs are sometimes not parsed correctly

### ISSUE THREAD

**Issue by heraklit256** [rspamd/rspamd#2275]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [X] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.5

### Operation system, CPU, memory and environment:
all

### Description (Please provide a descriptive summary of the issue):
Some providers such as GMail use a quite strange syntax to encode the IP address a message was received from:

    Received: from ?IPv6:::ffff:192.168.XXX.XXX? (p5B2XXXXX.dip0.t-ipconnect.de. [91.40.XXX.XXX])
         by smtp.gmail.com with ESMTPSA id h7-v6sm40[redacted]
         for <[redacted]>
         (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
         Sat, 02 Jun 2018 09:29:35 -0700 (PDT)

91.40.XXX.XXX, however, is listed at Spamhaus ZEN since it is a dial-up IP. Seems like rspamd is only parsing the first clutter, and not the actual IP listed in brackets. As far as I am concerned, this one should be checked always.

### Expected results:
RECEIVED_SPAMHAUS symbol since 91.40.XXX.XXX is listed.

**Comment by oxc** [comment]
Without having a closer look at the code, this is in fact the IP-address I would expect it to parse from this header.
Which part of the header did you expect it to parse?
There should be another `Received` header above this one, right?

**Comment by heraklit256** [comment]
Yes, there are several other headers, too - I just listed the relevant one here.

The syntax of such an `Received`-Header usually is:

    Received: from [provided EHLO name] ([PTR/rDNS of client IP] [actual client IP])
        [some other data here]

Since any client could send any EHLO, I prefer parsing the last one since this is what the mailserver actually saw.

**Comment by vstakhov** [comment]
It is not HELO generally: https://tools.ietf.org/html/rfc2821#section-4.4

**Comment by heraklit256** [comment]
I see, thanks.

If I understand it right, a spammer could use a fake IP (such as RFC1918) as a EHLO name, and `rspamd` would only parse this one - even if the _real_ IP is listed in some RBLs etc. - Sounds not good.

**Comment by heraklit256** [comment]
Here is another example:

    Received: from [127.0.0.1] ([77.247.181.162]) by smtp.web.de (mrweb003
     [213.165.67.108]) with ESMTPSA (Nemesis) id 0LgpIE-1fZMxq0c0U-XXXXXX for
     <redacted>; Sat, 25 Aug 2018 15:28:56 +0200

`77.247.181.162` is listed at Spamhaus XBL (see: https://bgp.he.net/ip/77.247.181.162#_rbl), but the `RECEIVED_SPAMHAUS_XBL` symbol does not show up in `rspamd` results:

    X-Spamd-Result: default: False [-5.15 / 11.00];
	 ARC_NA(0.00)[];
	 RCVD_VIA_SMTP_AUTH(0.00)[];
	 RCVD_TLS_ALL(0.00)[];
	 FROM_HAS_DN(0.00)[];
	 R_SPF_ALLOW(-0.20)[+ip4:212.227.15.0/25];
	 FREEMAIL_FROM(0.00)[web.de];
	 MIME_GOOD(-0.20)[text/plain];
	 PREVIOUSLY_DELIVERED(0.00)[redacted];
	 DMARC_NA(0.00)[web.de];
	 RCPT_COUNT_ONE(0.00)[1];
	 RCVD_IN_DNSWL_LOW(-0.50)[3.15.227.212.list.dnswl.org : 127.0.5.1];
	 IP_SCORE(-3.74)[ip: (-9.85), ipnet: 212.227.0.0/16(-4.87), asn: 8560(-3.90), country: DE(-0.09)];
	 TO_DN_ALL(0.00)[];
	 MX_GOOD(-0.01)[cached: mx-ha03.web.de];
	 TO_MATCH_ENVRCPT_ALL(0.00)[];
	 FROM_EQ_ENVFROM(0.00)[];
	 R_DKIM_NA(0.00)[];
	 FREEMAIL_ENVFROM(0.00)[web.de];
	 ASN(0.00)[asn:8560, ipnet:212.227.0.0/16, country:DE];
	 MID_RHS_MATCH_FROM(0.00)[];
	 RCVD_COUNT_TWO(0.00)[2]

Since the client apparently uses `127.0.0.1` as HELO name, no lookup to the actual IP is performed.

As this allowes an attacker to bypass RBL lookups, I strongly think this is a bug and should be changed.

**Comment by heraklit256** [comment]
Another example:

    Received: from [2.247.254.XX] ([2.247.254.XX]) by web-mail.web.de
     (3c-app-webde-bap46.server.lan [172.19.172.46]) (via HTTP); Sun, 9 Sep 2018
     14:47:35 +0200

`2.247.254.XX` is listed in Spamhaus PBL, but the symbol does not show up. It seems like this is a bigger problem while parsing `Received`-headers.

**Comment by vstakhov** [comment]
Rspamd does not parse non RFC conformant received headers like this one.

**Comment by heraklit256** [comment]
I see, thank you for the reply.

I guess parsing non-RFC conformant lines is a security risk, so there seems to be little we can do here. Or am I wrong?

**Comment by heraklit256** [comment]
Closing this issue since there seems to be no elegant way this can be fixed.

Please reopen if necessary.
