### ISSUE TITLE
ICAP Support Antivirus Module

### ISSUE THREAD

**Issue by Schroeffu** [rspamd/rspamd#2284]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [x] Enhancement

Rspamd has only limited Antivirus support, so far.

It would be very nice to support the ICAP (Internet Content Adaptation Protocol) Protocol, this way some more proprietary enterprise ready Antivirus scanners can be used in connection with Rspamd. For example F-Secure Internet Gatekeeper supports ICAP too, the scanner we prefer.

**Comment by twesterhever** [comment]
I would be interested in this, too.

**Comment by heraklit256** [comment]
+1

**Comment by rseffner** [comment]
+1

**Comment by croessner** [comment]
@vstakhov, I would like to have a closer look at the ICAP specs and implement it in the module. It seems to be a request/response protocol similar to HTTP. 

Does someone have a test license for such a virus scanner, so I could test the functionality?

**Comment by hildeb** [comment]
You can use c-icap

On Jun 26, 2018 19:32, "Christian Rößner" <notifications@github.com> wrote:

@vstakhov <https://github.com/vstakhov>, I would like to have a closer look
at the ICAP specs and implement it in the module. It seems to be a
request/response protocol similar to HTTP.

Does someone have a test license for such a virus scanner, so I could test
the functionality?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/vstakhov/rspamd/issues/2284#issuecomment-400399089>,
or mute
the thread

**Comment by Schroeffu** [comment]
@croessner i think using f-secure internet gatekeeper icap-feature would be simple for testing. This product (FSIGK) is activating a test-license for 1-3 month automatically, so you don't need any key/serial.

Download: https://www.f-secure.com/en/web/business_global/downloads/internet-gatekeeper (i would prefer .tar.gz version)
Install FSIGK .tar.gz version: https://help.f-secure.com/product.html#business/igk/5.50/en/task_CA4AF1E42BC1448AB9E373794A92D541-5.50-en

Now just enable the ICAP Port in fsgik.ini & restart fsigk, or simple via WebUI http://ip:9012 (admin/admin creds by default), see: https://help.f-secure.com/product.html#business/igk/5.50/en/task_7A7BD377975B4264808160BE3EACE25B-5.50-en and ICAP docs: https://help.f-secure.com/product.html#business/igk/5.50/en/concept_DB341A732E4B46108B5F76D20DAD382F-5.50-en

**Comment by croessner** [comment]
I fear, I don't really know how to implement this. I read through RFC3507 and I think I have a basic understanding of REQMOD and RESPMOD now. But if I did understand the text, a HTTP request is encapsulated into a ICAP request. Does that mean that the ICAP server itself requires an origin-sevrer serving HTTP to it? If so, I fear I have no idea on how to implement this :-(

**Comment by croessner** [comment]
Maybe RESPMOD. Unsure. Do some of you guys know which mode the antivirus services speak?

**Comment by vstakhov** [comment]
Implemented by @c-rosenberg
