### ISSUE TITLE
rspamd_proxy cannot communicate with milter manager

### ISSUE THREAD

**Issue by okkez** [rspamd/rspamd#2315]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [X] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always

### Rspamd version:

```
$ rpm -qa | grep rspamd
rspamd-1.7.6-3.x86_64
```

### Operation system, CPU, memory and environment:

```
$ cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core) 
```

On virtual machine.

### Description (Please provide a descriptive summary of the issue):

I'm using RSpamd with rmilter on CentOS6 .
```
$ rpm -qa | grep rspamd
rspamd-1.7.6-3.x86_64
$ rpm -qa | grep rmilter
rmilter-1.10.0-4.x86_64
```

My mail system on CentOS6 is like following:

![centos6](https://user-images.githubusercontent.com/33111/42027000-9427c368-7b03-11e8-914b-25e9ef5e818f.png)

This is working as I expected.

I want to upgrade to CentOS7 and upgrade RSpamd version.
I want to drop rmilter because rmilter has been deprecated and. move to rspamd_proxy as a milter.

My mail system on CentOS7 is like following:

![centos7](https://user-images.githubusercontent.com/33111/42027030-a7a117d2-7b03-11e8-9ac2-d8082ecde0eb.png)

This is not working as I expected.

Additional information, I've tried to use rspamd_proxy with milter-manager on CentOS6, but it didn't work, too.

[milter-manager](https://milter-manager.osdn.jp/reference/introduction.html) manages some milters on both CentOS6 and CentOS7.

### Steps to reproduce:

1. Install milter-manager
   * https://milter-manager.osdn.jp/reference/install-to-centos6.html
   * https://milter-manager.osdn.jp/reference/install-to-centos.html
1. Install RSpamd (and rmilter on CentOS6)
1. Configure milter-manager and rspamd/rmilter
   * Configuration for CentOS7
      * https://gist.github.com/okkez/a6af03127197a69a80214ffd8383ad8e
   * Configuration for CentOS6
      * https://gist.github.com/okkez/8efe09c6c60d05e4bfb32addf52c949a
1. Start milter-manager, RSpamd, rmilter
1. Run following commands
   ```
   $ milter-test-server -s inet:11332 --output-message
   $ sudo -u milter-manager milter-test-server -s unix:/var/run/milter-manager/milter-manager.sock --output-message
   ```
   * milter-test-server is a utility command to test milter protocol witout MTA.
1. Check result

### Expected results:

Added `X-Spam: Yes` both via milter-manager w/ rpamd_proxy and rspamd_proxy w/o milter-manager.
(Maybe other extended headers are added)

```
status: accept
elapsed-time: 0.56684 seconds

Envelope:------------------------------
  MAIL FROM:<sender@example.com>
  RCPT TO:<receiver@example.org>
Header:--------------------------------
  From: <sender@example.com>
  To: <receiver@example.org>
+ X-Spam: Yes
Body:----------------------------------
La de da de da 1.
La de da de da 2.
La de da de da 3.
La de da de da 4.
```
### Actual results:

Not added `X-Spam: Yes` via milter-manager w/ rspamd_proxy.
Added `X-Spam: Yes` via rspamd_proxy w/o milter-manager.

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):

Nothing.

**Comment by vstakhov** [comment]
I'm inclined to close this issue as there is no debugging information provided.

**Comment by vstakhov** [comment]
https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd - you need at least `milter` there.

**Comment by okkez** [comment]
Debugging information with following config:

/etc/rspamd/local.d/logging.inc:
```
level = "info";
debug_modules = ["milter"];
```

https://gist.github.com/okkez/97d96b0e9b931524883eb607b4723dee
