### ISSUE TITLE
StochasticGradient : training error

### ISSUE THREAD

**Issue by rseffner** [rspamd/rspamd#2329]
### Classification (Please choose *one* option):

* [X ] Other bug

### Reproducibility (Please choose *one* option):

* [X] I didn’t try

### Rspamd version:

1.7.7

### Operation system, CPU, memory and environment:

debian 8.11
Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
32gb non-ECC

### Description (Please provide a descriptive summary of the issue):

logcheck process found this after about 2 weeks (only a few days unter 1.7.7) at one of two machines

### Expected results:

no "error"-containing log messages

### Actual results:

Jul  6 16:09:28 ns2 rspamd[4554]: # StochasticGradient: training
Jul  6 16:09:28 ns2 rspamd[4554]: # StochasticGradient: you have reached the maximum number of iterations
Jul  6 16:09:28 ns2 rspamd[4554]: # training error = 9.1011105768379e-05

### Configuration:

As delivered with debian package with following values in /etc/rspamd/local.d/*

antivirus.conf
clamav {
    action = "rewrite subject";
}

arc.conf and dkim-signing.conf
allow_envfrom_empty = true;
allow_hdrfrom_mismatch = true;
allow_hdrfrom_multiple = false;
allow_username_mismatch = true;
sign_local = true;
symbol = DKIM_SIGNED;
use_domain = envelope;
domain {
...
}

classifier-bayes.conf
backend = "redis";

history-redis.conf
servers = 127.0.0.1:6379;
key_prefix = "rs_history";
nrows = 2000;
compress = true;

logging.inc
type = "file";
filename = "/var/log/rspamd/rspamd.log";
level = "error";
debug_modules = [];

milter_headers.conf
use = ["x-spamd-bar", "x-spam-level", "authentication-results"];
authenticated_headers = ["authentication-results"];

options.inc
local_addrs = "127.0.0.0/8, ::1";
dns { nameserver = ["127.0.0.1:53:10"]; }
history_rows = 2000;
neighbours {
    server1 { host = "https://rspamd1.s***e:443"; }
    server2 { host = "https://rspamd2.s***e:443"; }
}

redis.conf
servers = "127.0.0.1";

replies.conf
action = "no action";

worker_controller.inc
password = "***";
enable_password = "***";

worker_normal.inc
bind_socket = "localhost:11333";
count = 8;

worker_proxy.inc
bind_socket = "localhost:11332";
milter = yes;
timeout = 120s;
upstream "local" {
    default = yes;
    self_scan = yes;
}

**Comment by rseffner** [comment]
I still got these errors using rspamd 1.7.9-1~jessie.

```
Sep  5 13:36:40 ns2 rspamd[4558]: # StochasticGradient: training
Sep  5 13:36:40 ns2 rspamd[4558]: # StochasticGradient: you have reached the maximum number of iterations
Sep  5 13:36:40 ns2 rspamd[4558]: # training error = 7.7385287943734e-05
```

**Comment by incal** [comment]
Idem in hardware/mailserver


# StochasticGradient: training

# StochasticGradient: you have reached the maximum number of iterations

# training error = 0.00083207718058818

# StochasticGradient: training

# StochasticGradient: you have reached the maximum number of iterations

# training error = 0.064932535430326
