### ISSUE TITLE
Separate worker for training only

### ISSUE THREAD

**Issue by argv-minus-one** [rspamd/rspamd#2330]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [X] Not applicable

### Rspamd version:

1.7.7-0\~git174\~5e8397496\~sid

### Operation system, CPU, memory and environment:

Debian, AMD Ryzen 3 1300X, 16GB, Postfix+Dovecot+Pigeonhole+rspamd supervised by systemd

### Description (Please provide a descriptive summary of the issue):

Currently, training the spam filter involves sending commands to the `controller` worker, but [it understands quite a few commands besides that](https://rspamd.com/doc/workers/controller.html#supported-commands).

A process that reports ham/spam (e.g. an IMAP server) does not need access to rspamd's web UI, graphs, symbol info, etc. It would be more secure if there were a separate worker, with a separate socket/key/password/etc, that *only* accepts `learnspam` and `learnham`.

This could also be accomplished by allowing there to be multiple controller workers, each with separate configuration, and with a per-worker setting to limit the set of commands it will accept.

### Compile errors (if any):

N/A

### Steps to reproduce:

N/A

### Expected results:

A worker *only* for spam training

### Actual results:

One controller worker for spam training *and* various other things

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):

N/A

### Configuration:

N/A

### Additional information:

N/A

**Comment by vstakhov** [comment]
It is highly unlikely that this would ever happen. You can filter your HTTP requests using Nginx for instance.
