### ISSUE TITLE
per_user function doesn't work as excepted with redis backend in statistics module

### ISSUE THREAD

**Issue by georgeandreev** [rspamd/rspamd#2345]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
Rspamd daemon version 1.7.8
### Operation system, CPU, memory and environment:
CentOS 7
MemTotal:        3145728 kB
MemFree:          806704 kB
Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz

### Configuration:

/etc/rspamd/override.d/statistic.conf:

classifier "bayes" {
  name = "bayes_user";

  tokenizer {
    name = "osb";
  }

  min_tokens = 8;
  backend = "redis";
  servers = "127.0.0.1:6379";

  per_user = <<EOD
return function(task)
    local logger=require "rspamd_logger" 
    local rcpt = task:get_recipients(1)

if rcpt then
    one_rcpt = rcpt[1]
    if one_rcpt['domain'] then
        logger.infox(task, 'Returning domain "%1" as user for "%2"', one_rcpt["domain"], one_rcpt["addr"])
        return one_rcpt['domain']
    end
end
logger.infox(task, 'No user found')

return nil
end
EOD

  statfile {
    symbol = "BAYES_HAM_USER";
    spam = false;
  }
  statfile {
    symbol = "BAYES_SPAM_USER";
    spam = true;
  }

### Description (Please provide a descriptive summary of the issue):

`per_user` LUA-function in the `bayes_user` classificator doesn't work as expected with redis backend. The code is executed, but metric is applied for all users (BAYES_USER_SPAM)

Test email:

`cat test1.eml`
`To: info@example.com
From: example@example.com
Subject: Good morning

Hello, how are you? Today is a very good day. Let's go walk. Bye.`

`rspamc learn_spam -c bayes_user -d test1@user1.com -r test1@user1.com test1.eml`
`Results for file: test1.eml (0.003 seconds)
success = true;
filename = "test1.eml";
scan_time = 0.002779;`

`rspamc stat | fgrep BAYES`
`Statfile: BAYES_SPAM_USER type: redis; length: 1.37k; free blocks: 0; total blocks: 36; free: 0.00%; learned: 1; users: 1; languages: 0
Statfile: BAYES_HAM_USER type: redis; length: 0; free blocks: 0; total blocks: 0; free: 0.00%; learned: 0; users: 0; languages: 0`

`rspamc symbols -d test1@user1.com -r test1@user1.com test1.eml | fgrep BAYES_`
`Symbol: BAYES_SPAM_USER (0.00)[100.00%]`

`tail /var/log/rspamd/rspamd.log | fgrep lua`
`2018-07-16 14:49:05 #9903(controller) <6fcb76>; lua; [string "return function(ta...:8: Returning domain "user1.com" as user for "test1@user1.com" 
2018-07-16 14:49:05 #9903(controller) <6fcb76>; lua; [string "return function(ta...:8: Returning domain "user1.com" as user for "test1@user1.com"`

Now metric is applied for all users:

`rspamc symbols -d test2@example.com -r test2@example.com test1.eml | fgrep BAYES_`
`Symbol: BAYES_SPAM_USER (0.00)[100.00%]`

`tail /var/log/rspamd/rspamd.log | fgrep lua`
`2018-07-16 14:50:51 #9903(controller) <62ce6c>; lua; [string "return function(ta...:8: Returning domain "example.com" as user for "test2@example.com" 
2018-07-16 14:50:51 #9903(controller) <62ce6c>; lua; [string "return function(ta...:8: Returning domain "example.com" as user for "test2@example.com"`

Now if we feed the same message as ham for the second user:

`rspamc learn_ham -c bayes_user -d user2@example.com -r user2@example.com test1.eml`
`Results for file: test1.eml (0.002 seconds)
success = true;
filename = "test1.eml";
scan_time = 0.001693;`

`tail /var/log/rspamd/rspamd.log | fgrep lua`
`2018-07-16 14:53:22 #9903(controller) <e40bef>; lua; [string "return function(ta...:8: Returning domain "example.com" as user for "user2@example.com" 
2018-07-16 14:53:22 #9903(controller) <e40bef>; lua; [string "return function(ta...:8: Returning domain "example.com" as user for "user2@example.com"`

Message is recognised as HAM for all users:

`rspamc symbols -d test2@example.com -r test2@example.com test1.eml | fgrep BAYES_`
`Symbol: BAYES_HAM_USER (0.00)[99.60%]`

`rspamc symbols -d test1@user1.com -r test1@user1.com test1.eml | fgrep BAYES_`
`Symbol: BAYES_HAM_USER (0.00)[98.10%]`

Besides, rspamc stat always shows "users: 1" 

`for i in `seq 1 10`; do rspamc learn_spam -d test@user$i.com -r test@user$i.com test1.eml; done`

`rspamc stat | fgrep BAYES`
`Statfile: BAYES_SPAM_USER type: redis; length: 1.37k; free blocks: 0; total blocks: 36; free: 0.00%; learned: 10; users: 1; languages: 0
Statfile: BAYES_HAM_USER type: redis; length: 1.37k; free blocks: 0; total blocks: 36; free: 0.00%; learned: 1; users: 1; languages: 0`

But if `per_user` is set to `true` in statistic.conf it works correctly. Metric is applied for single user.

for i in `seq 1 10`; do rspamc learn_spam -d test@user$i.com -r test@user$i.com test1.eml; done

`rspamc stat | fgrep BAYES`
`Statfile: BAYES_SPAM_USER type: redis; length: 13.68k; free blocks: 0; total blocks: 360; free: 0.00%; learned: 10; users: 10; languages: 0
Statfile: BAYES_HAM_USER type: redis; length: 0; free blocks: 0; total blocks: 0; free: 0.00%; learned: 0; users: 0; languages: 0`

`rspamc symbols -d test@user5.com -r test@user5.com test1.eml | fgrep BAYES`
`Symbol: BAYES_SPAM_USER (0.00)[100.00%]`

`rspamc symbols -d test@example.com -r test@example.com test1.eml | fgrep BAYES -c`
`0`

**Comment by vstakhov** [comment]
You need to set proper prefix if you are using custom lua function. The default prefix when `per_user` is `false` is `%s%l` and for `per_user=true` it is automatically set to `%s%l%r`. If you want the similar behaviour with the custom Lua script, you'd need to set it explicitly in the classifier config:

```
prefix = "%s%l%r";
```

**Comment by ppaeps** [comment]
As far as I can tell, `prefix` is not documented anywhere except in this bug report.  Perhaps it should be mentioned somewhere on the https://rspamd.com/doc/configuration/statistic.html document?

**Comment by vstakhov** [comment]
There is an `edit` button on that page...

**Comment by ppaeps** [comment]
I hadn't noticed that button. :-o
Thanks for pointing it out!

I'll edit the page.
