### ISSUE TITLE
regexp module: duplicate fields not merged

### ISSUE THREAD

**Issue by uvelokk** [rspamd/rspamd#2369]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.8-1~stretch

### Operation system, CPU, memory and environment:
Debian 9.5 x86_64

### Description (Please provide a descriptive summary of the issue):
Regexp module does not merge duplicate fields

### Steps to reproduce:
```
rot@blah:~# cat /etc/rspamd/modules.d/regexp.conf | grep -v ^#

regexp {
    max_size = 1M;

    .include(try=true,priority=5) "${DBDIR}/dynamic/regexp.conf"
    .include(try=true,priority=1,duplicate=merge) "$LOCAL_CONFDIR/local.d/regexp.conf"
    .include(try=true,priority=10) "$LOCAL_CONFDIR/override.d/regexp.conf"
}

rot@blah:~# cat /etc/rspamd/local.d/regexp.conf | grep -v ^#
MICROSOFT_SPAM {
  score = 7;
}

rot@blah:~# rspamadm configdump regexp | head
*** Section regexp ***
max_size = 1000000;
MICROSOFT_SPAM {
    score = 7;
    score = 4;
    re = "X-Forefront-Antispam-Report=/SFV:SPM/H";
    group = "upstream_spam_filters";
    description = "Microsoft says the message is spam";
}
HAS_X_SOURCE {
```

**Comment by vstakhov** [comment]
This score might be added from Lua - that's why it is not merged correctly. Rspamd will use value `7` actually.
