### ISSUE TITLE
url_redirector incorrect mapping

### ISSUE THREAD

**Issue by jendis** [rspamd/rspamd#2370]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [x] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.6 - 1.7.8
### Description (Please provide a descriptive summary of the issue):
url_redirector sometimes maps "url_shortener " -> "url_shortener "
### Expected results:
Working (e.g. not blocked) url shortener will be mapped to final url
### Actual results:
@400000005b57522c3773463c (controller) <9092b3>; lua; url_redirector.lua:214: found cached redirect from http://tiny.cc/bj6ivy to http://tiny.cc/bj6ivyu
### Configuration:
tiny.cc is default in /etc/rspamd/redirectors.inc 
### Additional information:
During creation of this issue was available only this log. Redirectors for which url_shortener fails in the way described above are various but their domains are listed in redirectors.inc

**Comment by vstakhov** [comment]
It might probably be related to some resolution error being cached.
