### ISSUE TITLE
URLBL catching common german signatures, add to surbl-whitelist.inc

### ISSUE THREAD

**Issue by adlerweb** [rspamd/rspamd#2379]
### Classification (Please choose *one* option):
* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.8

### Operation system, CPU, memory and environment:
irrelevant

### Description (Please provide a descriptive summary of the issue):
I saw a lot of incoming mails getting high scores due to "URIBL_SBL". It detects "co.kg" as a malware domain, which might technically be true, but also affects a lot of business communication. There is a german legal form called "GmbH & Co. KG" - while there should be a space between "Co." and "KG" a lot of people seem not to care and as such include the "URL" "Co.KG" in their signatures.

### Compile errors (if any):
irrelevant

### Steps to reproduce:

1. Send mail wit a signature like "MeineTolleFirma GmbH & Co.KG"
2. Notice high URIBL_SBL score
3. Fix users signature

### Expected results:

1. Mail is delivered without penalty

### Actual results:

1. Mail might not be delivered depending on metrics

### Configuration:
default

### Additional information:

http://co.kg itsels seems to be just a parked site. Might be worth considering to still add it to surbl-whitelist to avoid this problem.

**Comment by hildeb** [comment]
I'm whitelisting like this:

# local.d/surbl.conf
# List of domains that are not checked by surbl
whitelist = "file://$CONFDIR/surbl-whitelist.inc";

with surbl-whitelist.inc containing:
co.kg



Am Fr., 27. Juli 2018 um 13:13 Uhr schrieb Florian Knodt <
notifications@github.com>:

**Comment by vstakhov** [comment]
I have added it in https://github.com/rspamd/maps
