### ISSUE TITLE
Neighbour list in webui not it the order as defined

### ISSUE THREAD

**Issue by Hativ** [rspamd/rspamd#2389]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description:

The neighbours in the webui are not listed in the order as defined. That especially disturbs with numbers in the hostname.

### Steps to reproduce:
* Configure neighbours (see configuration section)
* Go to web ui
* Open server select box

### Expected results:

Order should be as defined:
- as1
- as2
- as3

### Actual results:

Order is not as defined:
- as1
- as3
- as2

### Debugging information:

The /neighbours request returns it in the wrong order, so it's not an issue on client side.
```
{
  "as2":{
    "host":"https://as2.example.com:443",
    "url":"https://as2.example.com:443/"
  },
  "as1":{
    "host":"https://as1.example.com:443",
    "url":"https://as1.example.com:443/"
  },
  "as3":{
    "host":"https://as3.example.com:443",
    "url":"https://as3.example.com:443/"
  }
}
```

### Configuration:
local.d/options.inc
```
neighbours {
    as1 { host = "https://as1.example.com:443"; }
    as2 { host = "https://as2.example.com:443"; }
    as3 { host = "https://as3.example.com:443"; }
}
```

**Comment by Hativ** [comment]
Alternatively, the servers could be sorted alphabetically on the client side.

**Comment by moisseev** [comment]
JSON objects do not preserve the order of properties. Yes, we can sort them on the client side.
Another possibility is to pass neighbours list to WebUI as an array if it is important to keep the configured order:
```
[
  "as1":{
    "host":"https://as1.example.com:443",
    "url":"https://as1.example.com:443/"
  },
  "as2":{
    "host":"https://as2.example.com:443",
    "url":"https://as2.example.com:443/"
  },
  "as3":{
    "host":"https://as3.example.com:443",
    "url":"https://as3.example.com:443/"
  }
]
```

**Comment by Hativ** [comment]
If it's possible I think it's better to use an array as you suggested, because then I can define the order myself.

**Comment by Hativ** [comment]
Shouldn't be closed.

**Comment by Hativ** [comment]
Shouldn't be closed.

**Comment by vstakhov** [comment]
Do you know somebody who is going to fix it?

**Comment by Hativ** [comment]
Currently not. I could look at it, but currently have no time. The issue should, in my opinion, stay here so it is not forgotten.

**Comment by ItsOnlyMeNL** [comment]
This shouldn't be closed agreed. its driving me nuts that the order of the servers list is always different. 
Hopefully this can be fixed
