### ISSUE TITLE
Web UI -- Throughput feature (rrd) -- Failed Request -- No rrd configured for graphs

### ISSUE THREAD

**Issue by nuxwin** [rspamd/rspamd#2405]
### Classification

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
```
# rspamd --version
Rspamd daemon version 1.7.9
```
```
# LANG=C apt-cache policy rspamd
rspamd:
  Installed: 1.7.9-1~jessie
  Candidate: 1.7.9-1~jessie
  Version table:
 *** 1.7.9-1~jessie 0
       1001 http://rspamd.com/apt-stable/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
     0.6.10 0
        500 http://deb.debian.org/debian/ jessie/main amd64 Packages
```
```
# cat /etc/apt/preferences.d/imscp 
# APT_PREFERENCES(5) configuration file - auto-generated by i-MSCP
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

Package: libmysqlclient18 mysql-client-5.5 mysql-common mysql-server-5.5
Pin: release o=Debian,n=jessie
Pin-Priority: 1001

Package: *
Pin: origin packages.sury.org
Pin-Priority: 1001

Package: *
Pin: release o=Rspamd,n=jessie
Pin-Priority: 1001
```
### Operation system, CPU, memory and environment:
```
root@jessie:/usr/share/rspamd# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.11 (jessie)
Release:	8.11
Codename:	jessie
```
### Description

When spawning more than one worker controller process, throughput feature doesn't work correct.

### Steps to reproduce:

Set the `count` parameter of worker controller to 2 (or more).

### Expected results:

No problem with throughput feature.

### Actual results:
```
Request failed...
local, error: No rrd configured for graphs...
```
### Configuration
/etc/rspamd/local.d/worker-controller.inc:
```
# RSPAMD(8) Worker controller configuration file - auto-generated by i-MSCP
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

# See https://rspamd.com/doc/workers/controller.html

# You can add your own configuration in the
# '$LOCAL_CONFDIR/local.d/worker-controller.inc.local file

enabled = true;
count = 2;
password = "<the passwordhash>";

.include(try=true,priority=2,duplicate=merge) "${LOCAL_CONFDIR}/local.d/worker-controller.inc.local"
```
/etc/rspamd/local.d/worker-normal.inc :
```
# RSPAMD(8) Worker controller configuration file - auto-generated by i-MSCP
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

# See https://rspamd.com/doc/workers/normal.html

# You can add your own configuration in the
# '$LOCAL_CONFDIR/local.d/worker-normal.inc.local file

# Disabled because we operate in self-scan mode.
# See https://rspamd.com/doc/workers/rspamd_proxy.html
enabled = false;

.include(try=true,priority=2,duplicate=merge) "${LOCAL_CONFDIR}/local.d/worker-normal.inc.local"
```
/etc/rspamd/local.d/worker-proxy.inc 
```
# RSPAMD(8) worker proxy configuration file - auto-generated by i-MSCP
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

# See https://rspamd.com/doc/workers/rspamd_proxy.html

# You can add your own configuration in the
# '$LOCAL_CONFDIR/local.d/worker-proxy.inc.local file

enabled = yes;
milter = yes;
timeout = 120s;

upstream "local" {
    default = yes;
    self_scan = yes;
}

.include(try=true,priority=2,duplicate=merge) "${LOCAL_CONFDIR}/local.d/worker-proxy.inc.local"
```
### Discussion

What the purpose of the `count` parameter for the worker controller exactly? My thinking was that it was for the number of processes to spawn for the WEB UI, something similar to PHP FPM max children... I'm wrong?

**Comment by nuxwin** [comment]
@vstakhov 

So, why do you provide the `count` parameter exactly? My thinking was that is was provided to make concurrency requests available (as far as I know, one process can only handle one request at time and of course, with XHR requests and similar, concurrency is often required to improve time answer).

Thank for your answer.

**Comment by vstakhov** [comment]
Rspamd works asynchronously and it can process thousands of requests per 
second using a single worker. Controller worker is designed for *trusted* 
access and performs multiple servicing tasks. You can have multiple 
controllers but it seems it breaks rrd. It is a bug in fact but I don't see 
any sane reasons to define more than one controller worker.

**Comment by nuxwin** [comment]
@vstakhov 

Thank for your clear answer;) You could maybe add a note in the documentation. This would avoid similar reports.
