### ISSUE TITLE
dkim_signing ignore domain{...} records

### ISSUE THREAD

**Issue by constin** [rspamd/rspamd#2410]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.9
### Operation system, CPU:
Ubuntu 18.04, KVM CPU
### Description (Please provide a descriptive summary of the issue):

rspamd ignore any addtitional special dlim_singing configurations in any place.
it use default separator from config and default template path to key.

reproduce:

default installation from repo.
$ rspamadm configwizard
...
Enter output directory for the keys [default: /var/lib/rspamd/dkim/]: 
Enter domain to sign: test.com
Enter selector [default: dkim]: mail
Do you want to create privkey /var/lib/rspamd/dkim/test.com.mail.key[Y/n]: 

logs:
2018-08-10 09:03:41 #15064(normal) <7a7d17>; dkim_signing; dkim_signing.lua:157: cannot read key from /var/lib/rspamd/dkim/test.com.dkim.key: No such file or directory
(it search file with "dkim" in filename)

cat /etc/rspamd/local.d/dkim_signing.conf
domain {
    test.com {
        key = "/var/lib/rspamd/dkim/test.com.mail.key";
	selector = "mail";
    }
}

if i will place /var/lib/rspamd/dkim/test.com.dkim.key with key. it will be singing with "dkim" separator not "mail"
i clould place domain {...}. in main dkim_signing.conf . it will be ignored too.

so rspamd ignore domain {...}  configuration.
...

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):

2018-08-10 09:03:41 #15064(normal) <7a7d17>; dkim_signing; dkim_signing.lua:157: cannot read key from /var/lib/rspamd/dkim/test.com.dkim.key: No such file or directory

### Configuration (e.g. `rspamadm configdump module`):

# rspamadm configdump dkim_signing
CPU doesn't have SSSE3 instructions set required for hyperscan, disable it
*** Section dkim_signing ***
use_esld = true;
allow_hdrfrom_mismatch = false;
selector = "dkim";
symbol = "DKIM_SIGNED";
auth_only = true;
allow_envfrom_empty = true;
try_fallback = true;
sign_networks [
    "127.2.4.7",
]
domain {
    test.com {
        key = "/var/lib/rspamd/dkim/test.com.mail.key";
        selector = "mail";
    }
}
use_redis = false;
allow_username_mismatch = false;
sign_local = true;
key_prefix = "DKIM_KEYS";
use_domain = "header";
allow_hdrfrom_multiple = false;

*** End of section dkim_signing ***

**Comment by constin** [comment]
Ubuntu 16.04 - same problem

**Comment by constin** [comment]
it works according your documentation:
store keys in redis or using maps.

but maybe then you need fix your wizard..

**Comment by vstakhov** [comment]
I think I need to fix dkim_signing. Probably, I've already fixed it, I'll check later.
