### ISSUE TITLE
rspamd not detect exim auth users

### ISSUE THREAD

**Issue by askovpen** [rspamd/rspamd#2425]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

latest

### Description (Please provide a descriptive summary of the issue):
i want scan authed users for spam, but get false positive:

```
R_DKIM_NA(0)
HFILTER_HOSTNAME_UNKNOWN(2.5)
HFILTER_HELO_BADIP(4.5)[x.x.x.x,1]
ASN(0)[asn:xxxx, ipnet:x.x.x.x.x/x, country:RU]
IP_SCORE(-0.018308)[country: RU(-0.09)]
RDNS_NONE(1)
DMARC_POLICY_REJECT(2)[xxxxx.xxx : No valid SPF, No valid DKIM,reject]
MIME_GOOD(-0.1)[text/plain]
MX_INVALID(0.5)[greylisted]
MID_RHS_MATCH_FROM(0)
FROM_EQ_ENVFROM(0)
TO_MATCH_ENVRCPT_ALL(0)
RCVD_TLS_ALL(0)
ARC_NA(0)
FROM_HAS_DN(0)
GREYLIST(0)[greylisted,Thu, 16 Aug 2018 19:44:55 GMT,new record]
RCPT_COUNT_ONE(0)[1]
R_SPF_PERMFAIL(0)[-all]
TO_DN_ALL(0)
RCVD_COUNT_TWO(0)[2]
RCVD_VIA_SMTP_AUTH(0)
```

### Actual results:

Can rspamd detect authed users?

**Comment by moisseev** [comment]
It should.  Probably your Rspamd is not properly integrated with MTA.
Please see the [MTA integration](https://rspamd.com/doc/integration.html) and [Scanning outbound mail](https://rspamd.com/doc/tutorials/scanning_outbound.html) articles.

**Comment by pilchita** [comment]
Hello Alexander, could you print the header "x-rspamd-server" in exim?

Regards,

**Comment by moisseev** [comment]
@pilchita Sorry, I'm using Postfix. I have no idea if it is possible in Exim. I guess it isn't.

**Comment by askovpen** [comment]
@moisseev i see articles. That's not something
