### ISSUE TITLE
rspamadm configwizard statistics fails to convert BAYES_SPAM

### ISSUE THREAD

**Issue by cryptomilk** [rspamd/rspamd#2427]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
rpsamd-1.7.9

### Operation system, CPU:
openSUSE 15.1

### Description (Please provide a descriptive summary of the issue):
```
Aug 17 08:43:00 milliways rspamd[14036]: (normal) <9qtg7q>; cfg; rspamd_redis_parse_classifier_opts: you are using old bayes schema for redis statistics, please consider
converting it to a new one by using 'rspamadm configwizard statistics'
```

```
rspamadm configwizard statistics
Key "RS_version" has not been found in Redis for BAYES_HAM/BAYES_SPAM
Do you wish to convert data to the new schema?[Y/n]:
Expire time for new tokens [100d]:
converted OK elements from symbol BAYES_SPAM
converted 0 elements from symbol BAYES_HAM
error converting metadata for symbol BAYES_SPAM
Conversion failed
No changes found, the wizard is finished now
```

The first strange this is:

converted OK elements

OK isn't a number ...

### Expected results:
`rspamadm configwizard statistics` converts the DB

### Actual results:
`rspamadm configwizard statistics` fails converting the DB

### Configuration (e.g. `rspamadm configdump module`):

cat local.d/classifier-bayes.conf
new_schema = true;
expire = 8640000;

**Comment by rsmarples** [comment]
I get a similar issue using rspamd-1.8.0 + commit 4dfe49bc169346ae120bafbda643f0477886da41 to get some output:

```
# rspamadm configwizard statistics
You are using an old schema version: 0 for BAYES_HAM/BAYES_SPAM
Do you wish to convert data to the new schema?[Y/n]: y
Expire time for new tokens [100d]:
error converting symbol BAYES_SPAM: Connection timed out
Conversion failed
No changes found, the wizard is finished now
#
```

I just cannot get rid of this annoying message in my logs!

**Comment by fezie** [comment]
I just got this problem too with 1.8.1-0~git233~6eef162a6
I have in local.d/classifier-bayes.conf "new_schema = true;"
And then I did a bunch of "rspamc learn_ham"
But still rspamadm configwizard said there was old data in the redis db. Conversion failed with a timeout.

**Comment by Oharahay** [comment]
Hi Guys 
I have a same problem 

rspamd version 1.8.1
Architecture   : FreeBSD:11:amd64


root@mx2/usr/local/etc/rspamd/local.d> rspamadm configwizard statistics
Key "RS_version" has not been found in Redis for BAYES_HAM/BAYES_SPAM
Do you wish to convert data to the new schema?[Y/n]: 
Expire time for new tokens [100d]: 
error converting symbol BAYES_SPAM: Operation timed out
Conversion failed
No changes found, the wizard is finished now
root@mx2/usr/local/etc/rspamd/local.d> 

018-10-25 10:00:43 #94512(controller) <53mmqq>; cfg; rspamd_redis_parse_classifier_opts: you are using old bayes schema for redis statistics, please consider converting it to a new one by using 'rspamadm configwizard statistics'
2018-10-25 10:00:43 #94512(controller) <53mmqq>; cfg; rspamd_redis_parse_classifier_opts: you are using old bayes schema for redis statistics, please consider converting it to a new one by using 'rspamadm configwizard statistics'
2018-10-25 10:00:43 #94511(rspamd_proxy) <53mmqq>; cfg; rspamd_redis_parse_classifier_opts: you are using old bayes schema for redis statistics, please consider converting it to a new one by using 'rspamadm configwizard statistics'
2018-10-25 10:00:43 #94511(rspamd_proxy) rspamd_worker_log_pipe_handler: added new log pipe

**Comment by pautiina** [comment]
I have a same problem on FreeBSD 11.2

**Comment by cryptomilk** [comment]
FYI: I've resolved this by completely removing the redis database, then the database is recreated with the new schema and bayes filters start to work again.
