### ISSUE TITLE
rejections regardless of reject = null;

### ISSUE THREAD

**Issue by MoritzFago** [rspamd/rspamd#2437]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):
according to https://rspamd.com/doc/tutorials/writing_rules.html this:
```sh
cat override.d/actions.conf
reject = null;
greylist = null;
```
should disable rejectionions and greylisting. If I send an email with the gtube pattern:"XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X", the email gets rejected 
```
<<< 554 5.7.1 Gtube pattern
554 5.0.0 Service unavailable
```
(extract of a bouce)

### Expected results:

no rejecting or greylisting (soft rejections)

### Actual results:

rejections and soft rejections

### Configuration (e.g. `rspamadm configdump module`):
```
rspamadm configdump actions
*** Section actions ***
add_header = 6;
greylist = null;
reject = null;

*** End of section actions ***

```

**Comment by vstakhov** [comment]
Gtube is always rejected.

**Comment by MohammedNoureldin** [comment]
Hi @vstakhov,

just to make it clear. Do all rejected emails not appear in the history? Or only the GTUBE? The only method I could achieve till now to test spam is to send GTUBE mail, which I understand is rejected always, and it increases the statistics, but I don't see it in the history. Is it only for GTUBE, or for all rejected?
