### ISSUE TITLE
Unable to parse outlook's ipv6 header correctly

### ISSUE THREAD

**Issue by rtakamura** [rspamd/rspamd#2452]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
ver1.7.9
### Operation system, CPU:
CentOS7.4.1708
### Description (Please provide a descriptive summary of the issue):
mail sent from Microsoft Outlook Server the IPv6 address of the "recieved header" can not be correctly extracted and an error occurs.

## Received header
Received: from KAXPR01MB0000.jpnprd01.prod.outlook.com
 ([fe80::d943:55cc:ec54:4033]) by KAXPR01MB0000.jpnprd01.prod.outlook.com ([fe80::d943:55cc:ec54:4033%9]]) with mapi id ******

### Relevant logs (see details [here](https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd)):
rspamd[28379]: <>; ; lua_ip_from_string: cannot parse ip: fe80::d943:55cc:ec54:4033]) by KAXPR01MB1029.jpnprd01.prod.outlook.com ([fe80::d943:55cc:ec54:4033%9]

**Comment by vstakhov** [comment]
It is likely fixed in the master.

**Comment by rtakamura** [comment]
I tried the same eml with the release version 1.8.0.
However, the same error appeared.

The header that is causing the error:
===
Received: from OSBPR01MB3029.jpnprd01.prod.outlook.com
 ([fe80::5535:9d89:d267:afc4]) by OSBPR01MB3029.jpnprd01.prod.outlook.com
 ([fe80::5535:9d89:d267:afc4%3]) with mapi id 15.20.1080.015; Wed, 29 Aug 2018
 09:17:43 +0000
===

rspamd.log:
===
rspamd[6444]: <>; ; lua_ip_from_string: cannot parse ip: fe80::5535:9d89:d267:afc4]) by OSBPR01MB3029.jpnprd01.prod.outlook.com ([fe80::5535:9d89:d267:afc4%3]

**Comment by rtakamura** [comment]
I tried the same eml with the release version 1.8.1.
These results didn't have any problem.
