### ISSUE TITLE
multimap type received with filter real_hostname not working

### ISSUE THREAD

**Issue by bolera** [rspamd/rspamd#2453]
### Classification (Please choose *one* option):
* [x ] Serious bug
### Reproducibility (Please choose *one* option):
* [X] Always
### Rspamd version:
1.7.9
### Operation system, CPU:
Ubuntu 16.04
### Description:
A multimap based on the received filter using real_hostname does not work. I tested the same client (sending MTA) with tld:real_hostname and it worked. I can assure 100% that the looked-up hostname is the one I put in the map. I can see the correct IP in the logs and postfix puts the correct hostname in the Received header.

Map setup:
this does not work with "something.example.com" in the map:
```
whitelist_from_hostname {
	description = "client hostname whitelist";
            type = "received";
            filter = "real_hostname";
            map = "file://$LOCAL_CONFDIR/maps.d/whitelist_from_hostname.txt";
            symbol = "WHITELIST_FROM_HOSTNAME";
            action = "accept"; # Prefilter mode
}
```
this one works with "example.com" in the map:
```
whitelist_from_hostname_sld {
	description = "client hostname whitelist";
            type = "received";
            filter = "tld:real_hostname";
            map = "file://$LOCAL_CONFDIR/maps.d/whitelist_from_hostname_sld.txt";
            symbol = "WHITELIST_FROM_HOSTNAME_SLD";
            action = "accept"; # Prefilter mode
}
```
Just tested with from_hostname. It's not working either.

**Comment by vstakhov** [comment]
I cannot reproduce your issue. In my case, both maps work fine.

**Comment by bolera** [comment]
So, how can I debug this? e.g. show in the log which names get used for lookup?

**Comment by bolera** [comment]
I have found the problem with debug logging. There is something wrong with the specification of "real_hostname" and "from_hostname". They seem to mean "hostname of the originating client".  If I check for "by_hostname" it works. But this is the directly delivering MTA! What does the "by_hostname" exactly specify? Just the last or all hops?
The documentation says:
```
from_hostname - string that represents hostname provided by a peer
real_hostname - hostname as resolved by MTA
tld:from_hostname - extract eSLD part from peer-provided hostname
tld:real_hostname - extract eSLD part from MTA-verified hostname
```
A peer is a directly connecting client. Any other MTA hops away and the originating client are *not* peers. from_hostname should contain the hostname as given by the connecting MTA (=helo), real_hostname should be the hostname we look up for the connecting IP. That doesn't seem to be the case. That the tld:real_hostname worked for me is due to the originating client having the same SLD as the delivering client. 
I think there's something wrong either in the logic of the code or the documentation.

**Comment by vstakhov** [comment]
All Received except the top most one if Rspamd knows that it is an 
artificial header (typically meaning added by our MTA). To get an 
originating ip/hostname you need corresponding multimap types, not 'received'.

**Comment by bolera** [comment]
It's not clear at all from the documentation that "received" acts only on the Received headers. Would be good if you could add this clarification to the docs, e.g. name it "Received header filter". Would have spared me some time. 
I do not want to get the originating hostname. I want to act on the connecting MTA. There is a hostname filter that seems to do that, but it doesn't work on full hostnames, only on SLD or top-level domain parts.
