### ISSUE TITLE
score log at 0.00 when soft reject by greylist module

### ISSUE THREAD

**Issue by nORKy54** [rspamd/rspamd#2459]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):

When a mail is "soft rejected" by greylist module, the total score is at 0.00 in log. I think it need to be at the real value calculated by symbols value.

### Relevant logs (see details [here](https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd)): (some value are hidden with XXX, and [..] put for clarity) 

#62069(rspamd_proxy) <8812c1>; proxy; rspamd_task_write_log: id: <1536136308f2ed6588b0fabbfa231bb42cd5ecf928@XXXX>, qid: <C748D1E81A>, ip: X.X.X.X, from: <web@XXX>, (default: F (soft reject): [0.00/20.00] [MIME_BAD_ATTACHMENT(4.00){pdf;} 

### Expected results:
#62069(rspamd_proxy) <8812c1>; proxy; rspamd_task_write_log: id: <1536136308f2ed6588b0fabbfa231bb42cd5ecf928@XXXX>, qid: <C748D1E81A>, ip: X.X.X.X, from: <web@XXX>, (default: F (soft reject): [13.20/20.00] [MIME_BAD_ATTACHMENT(4.00){pdf;} [...]

**Comment by vstakhov** [comment]
No, it doesn't: https://rspamd.com/doc/faq.html#why-do-i-have-zero-score-for-a-spam-message
