### ISSUE TITLE
Wong DKIM signature on emails with no utf-8 chaset

### ISSUE THREAD

**Issue by jirireischig** [rspamd/rspamd#2460]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.9
### Operation system, CPU:
CentOS7
### Description (Please provide a descriptive summary of the issue):
I have problem wich DKIM signature.
When the message is in Windows-1250 charset, the DKIM signature is false because of "wrong body hash"
For example this message:
[DKIM-signature-false.txt](https://github.com/rspamd/rspamd/files/2352485/DKIM-signature-false.txt)

When the message is in utf-8 chaset, DKIM signature is OK.
For example this message:
[DKIM-signature-good.txt](https://github.com/rspamd/rspamd/files/2352487/DKIM-signature-good.txt)

### Expected results:
DKIM signature is good for eny type of messages.

**Comment by vstakhov** [comment]
Do you have some samples?

**Comment by jirireischig** [comment]
Some samples are in my previous post.

I dive more into the problem and it look like more complicated.

It's look like the problem is not excactly in charsets (Windows-1250 or utf-8) but in 7bit / 8bit encoding.

Some software send 8bit emails with Content-Transfer-Encoding set to 7bit. Than some mail servers make automatic conversion from 8bit. This conversion broke DKIM signature.

Another problem is automatic conversion from 8bit to 7bit if recieving server does not support 8bit. This conversion broke DKIM signature. It's look like by design of DKIM (https://tools.ietf.org/html/rfc4871#section-5.3) because there is not any normalize definition in RFC.

So, the problem is not look like in Rspamd exactly but in DKIM.
