### ISSUE TITLE
local.d/settings.conf does not work

### ISSUE THREAD

**Issue by MuhKuh7** [rspamd/rspamd#2481]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.9

### Operation system, CPU:
Debian 9

### Description (Please provide a descriptive summary of the issue):
Configuration for the settings is ignored in local.d/settings.conf. The configuration only works in modules.d/settings.conf.

### Expected results:
local.d/settings.conf extends modules.d/settings.conf

### Actual results:
local.d/settings.conf is ignored

**Comment by vstakhov** [comment]
It is now fixed in the master.
