### ISSUE TITLE
Redis connexion failed / no connexion fail in redis log

### ISSUE THREAD

**Issue by goudal-emmk** [rspamd/rspamd#2490]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):
Redis 4.09
Got messages in log like :
2018-09-17 16:35:08 #21165(normal) <a0d663>; redis_pool; rspamd_redis_pool_new_connection: created new connection to ::1:6379
2018-09-17 16:35:08 #21165(normal) <8389a9>; redis_pool; rspamd_redis_pool_new_connection: created new connection to ::1:6379
2018-09-17 16:35:08 #21165(normal) lua_redis_callback: got reply from redis 00007FD3C5013C80 for query 00007FD3D93A57C0
2018-09-17 16:35:08 #21165(normal) <y5ftdy>; lua; lua_redis.lua:806: cannot upload script to 127.0.0.1: Connexion refusée
2018-09-17 16:35:08 #21165(normal) lua_redis_fin: finished redis query 00007FD3D93A57C0 from session 00007FD3C5013C80

Redis configured without password on localhost 
Redis logs show no refused connections, but show accepted connections...

Same setup run on another host with rspamd 1.7.2

### Additional information:

**Comment by vstakhov** [comment]
Connection refused is not an Rspamd issue.

**Comment by moisseev** [comment]
@goudal-emmk , It looks like a dual stack issue.
Check which socket (IPv4/IPv6) Redis is listening on and which socket Rspamd is trying to connect.

**Comment by goudal-emmk** [comment]
Ok.. I have just changed redis.conf from
read_server="127.0.0.1"
to
127.0.0.1:6379
And no more messages.
Btw on the precedent configuration, redis-cli monitor showed activity (and no other client than rspamd)...
Documentation is not complete on redis as it does not say you can add a port.

**Comment by goudal-emmk** [comment]
well it's not a rspamd issue, it's a rspamd documentation issue....

**Comment by rrauenza** [comment]
I also had this issue today.

Redis was definitely listening on localhost:6379, lsof confirmed it.  Log messages definitely said connection refused on 127.0.0.1:6379, and I was able to use netcat to connect to redis.

Problem went away when I explicitly changed redis.conf in rspamd to be:

read_servers = "127.0.0.1:6379";
write_servers = "127.0.0.1:6379";

from just "127.0.0.1"
