### ISSUE TITLE
[bug] bayes wrong value

### ISSUE THREAD

**Issue by askovpen** [rspamd/rspamd#2494]
### Classification (Please choose *one* option):

* [X] Serious bug

### Reproducibility (Please choose *one* option):

* [X] Always

### Description (Please provide a descriptive summary of the issue):
Message:
```
Message-Id: <20180918092404.4B6A2AC01A0@mail.livelib.ru>
X-Spamd-Result:
    ...
    BAYES_SPAM(0.04)[56.58%];
```
after i run `/usr/bin/rspamc learn_spam`, i get:
```
<26b65a>; csession; rspamd_task_process: learn error: <20180918092404.4B6A2AC01A0@mail.livelib.ru> is skipped for bayes classifier: already in class spam; probability 99.32%
```
56.58 != 99.32
what wrong?

**Comment by vstakhov** [comment]
The message might have been altered somehow. Bayes consider not just data but also metadata for a message.
