### ISSUE TITLE
[bug] Url not recognized

### ISSUE THREAD

**Issue by pkalemba** [rspamd/rspamd#2496]
### Classification (Please choose *one* option):

* [X ] Ordinary bug

### Reproducibility (Please choose *one* option):

* [X] Always

### Description (Please provide a descriptive summary of the issue):
Links as below are not parsed properly and not detected as phishing:

`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>

<body>
    <div style="FONT-SIZE: 11px; FONT-FAMILY: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; WHITE-SPACE: normal; WORD-SPACING: 0px; TEXT-TRANSFORM: none; FONT-WEIGHT: 400; COLOR: rgb(51,51,51); FONT-STYLE: normal; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: normal; BACKGROUND-COLOR: rgb(255,255,255); TEXT-INDENT: 0px; font-variant-ligatures: normal; font-variant-caps: normal; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial">
        <font size="1"><a style="COLOR: rgb(1,134,186)" href="badomain.com"
                rel="noreferrer" target="_blank">
                <font color="#800080" size="1">https://d<font face="Microsoft Uighur"></font>omain.com</font>
            </a>
            <font color="#800080" size="1"><u>/</u></font><a style="FONT-SIZE: 11px; FONT-FAMILY: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; WHITE-SPACE: normal; WORD-SPACING: 0px; TEXT-TRANSFORM: none; FONT-WEIGHT: 400; COLOR: rgb(1,134,186); FONT-STYLE: normal; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: normal; BACKGROUND-COLOR: rgb(255,255,255); TEXT-INDENT: 0px; font-variant-ligatures: normal; font-variant-caps: normal; -webkit-text-stroke-width: 0px"
                href="http://www.badomain.com" rel="noreferrer" target="_blank">
                <font color="#800080">path1<font size="2" face="Tahoma">&quot;<span>&nbsp;path2
                        </span>&quot;</font>path3</font>
            </a><a style="FONT-SIZE: 11px; FONT-FAMILY: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; WHITE-SPACE: normal; WORD-SPACING: 0px; TEXT-TRANSFORM: none; FONT-WEIGHT: 400; COLOR: rgb(1,134,186); FONT-STYLE: normal; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: normal; BACKGROUND-COLOR: rgb(255,255,255); TEXT-INDENT: 0px; font-variant-ligatures: normal; font-variant-caps: normal; -webkit-text-stroke-width: 0px"
                href="http://www.badomain.com" rel="noreferrer" target="_blank">
                <font color="#800080">path4</font>
            </a>
        </font>
    </div>
    <div style="FONT-SIZE: 11px; FONT-FAMILY: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; WHITE-SPACE: normal; WORD-SPACING: 0px; TEXT-TRANSFORM: none; FONT-WEIGHT: 400; COLOR: rgb(51,51,51); FONT-STYLE: normal; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: normal; BACKGROUND-COLOR: rgb(255,255,255); TEXT-INDENT: 0px; font-variant-ligatures: normal; font-variant-caps: normal; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial">&nbsp;</div>
    <div style="FONT-SIZE: 11px; FONT-FAMILY: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; WHITE-SPACE: normal; WORD-SPACING: 0px; TEXT-TRANSFORM: none; FONT-WEIGHT: 400; COLOR: rgb(51,51,51); FONT-STYLE: normal; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: normal; BACKGROUND-COLOR: rgb(255,255,255); TEXT-INDENT: 0px; font-variant-ligatures: normal; font-variant-caps: normal; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial">&nbsp;</div>
    <div style="FONT-SIZE: 11px; FONT-FAMILY: 'Lucida Grande', Verdana, Arial, Helvetica, sans-serif; WHITE-SPACE: normal; WORD-SPACING: 0px; TEXT-TRANSFORM: none; FONT-WEIGHT: 400; COLOR: rgb(51,51,51); FONT-STYLE: normal; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: normal; BACKGROUND-COLOR: rgb(255,255,255); TEXT-INDENT: 0px; font-variant-ligatures: normal; font-variant-caps: normal; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial">
</body>

</html>`
### Expected results:

Links should be parsed and detected as phishing/spam

**Comment by vstakhov** [comment]
I cannot parse them as well.
