### ISSUE TITLE
 How to get the current ratelimit values of a user

### ISSUE THREAD

**Issue by PHPGangsta** [rspamd/rspamd#2498]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [X] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.9

Hi,

I'm using the ratelimit-module, it works very good now. I wrote my own custom_keywords lua script which reads maps.

Now the only thing left is: How can I access the current ratelimit-status of a user? In my old system (policyd-based) the quota-status is stored in a MySQL database, that's easy to access (and run the leaky bucket algorithm in PHP to get the current value). I'm showing the value in my small Administration-Interface, something like:

33 / 1000 mails of user ratelimit used

I saw that the values in rspamd are stored in redis with a lua script, which also calculates the leaky bucket algorithm. I would like to do exactly the same, calculate the current content of the bucket, and return the current ratelimit-value of a user ("33 of 1000 mails user ratelimit"). So I would like to call the "bucket_check_script" somehow from my PHP application to get the values. Is that possible?

I'm not a lua or redis expert. rspamd calls it via EVALSHA if I see it correctly. But I don't know the Hash of that lua-script. And I don't know how to calculate the "user" parameter, it seems to be always starting with RLxxxx.

There are several possibilities I guess:
- I need to know the Hash of the lua-Script + how to calculate the parameters, then I can call it myself from PHP
- I will upload that same redis script from PHP myself, but then I get problems if rspamd changes something inside that calculation. And I need to know how to calculate the parameters
- A handy command is added to rspamadm, then I can easily call for example:  rspamadm ratelimit get mail@example.com
- A handy HTTP-API request where I can request the current ratelimit values of a user/email-address.

The last option would be my favorite of cause :-)

Anyone has a hint for me?

(I already asked the question on the mailing list, but nobody answered for 20 days, maybe I'm more successful here)

**Comment by vstakhov** [comment]
Github issues tracker is intended to be used for issues or suggestions, not for general questions. Closing.

**Comment by PHPGangsta** [comment]
Hi @vstakhov,
I marked it as a feature request, because as far as I know it's currently not possible to get the current ratelimit values. That's why I wrote about the use case, and tried to give some ideas how it could be achieved.

I thought you want feature requests here, that's why it's one of the available checkboxes at "Classification".

**Comment by vstakhov** [comment]
Ok, you are right.

**Comment by vstakhov** [comment]
In theory, each plugin can register endpoints in the controller REST API. It is just not implemented for Ratelimits.

**Comment by andryyy** [comment]
That's something I'd consider to sponsor.

**Comment by fabiorauber** [comment]
+1 for this issue, it is hard to debug when a user gets ratelimited, and we have no tool to check the current limit being applied (or to clear it).

**Comment by bajizs** [comment]
+1 for this issue, it is hard to debug when a user gets ratelimited, and we have no tool to check the current limit being applied (or to clear it).

**Comment by RealSebFox** [comment]
+1 for this issue. It should not only be possible to view current ratelimits, but also to clear ratelimits manually. Please reconsider this feature request!

**Comment by krzsztf1** [comment]
+1 for this issue.
