### ISSUE TITLE
Web UI -- History -- Symbols sort order score not working in Chromium

### ISSUE THREAD

**Issue by busybit** [rspamd/rspamd#2505]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.9
### Operation system, CPU:
Linux, AMD64
### Description (Please provide a descriptive summary of the issue):
When sort order "score" is selected in Web UI history, symbols are sorted random in Chromium. Firefox is ok. Looks like some incompatible Javascript. Sort order "name" is ok in Chromium.
### Expected results:
Symbols sorted by score, highest top.
### Actual results:
Random sort order.

**Comment by moisseev** [comment]
Fixed in 1.8.0: https://github.com/rspamd/rspamd/pull/2392/commits/0760edc8f450f1c7412980992f768d46bc136f95

**Comment by busybit** [comment]
Thanks for that hint. I patched my 1.7.9 and it works!
