### ISSUE TITLE
rspamd/maps repository and built package

### ISSUE THREAD

**Issue by andy-igoshin** [rspamd/rspamd#2532]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

1.8.0

### Operation system, CPU:

ubuntu 16.04.5, 64bit

### Description (Please provide a descriptive summary of the issue):

changes from rspamd/maps repository do not go into built package.

### Expected results:

changes from rspamd/maps repository should go into built package.

### Actual results:

changes from rspamd/maps repository do not go into built package.

**Comment by vstakhov** [comment]
They are dynamically loaded by Rspamd, there is no need to sync the package's data. However, we will sync it from time to time in future.
