### ISSUE TITLE
Language detection: pt being detected as fr or ro after upgrade to 1.8.0

### ISSUE THREAD

**Issue by fabiodemartin** [rspamd/rspamd#2541]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.8.0
### Operation system, CPU:
Linux Centos 7 x86_64
### Description (Please provide a descriptive summary of the issue):

Most of pt (portuguese/portuguese-br) parts are being detected as fr or ro after upgrade to 1.8.0 
As I can see on changelog, many changes has been made on language detector:
* [Fix] Fix various corner cases for language detection
* [Project] Improve language detector: cleanup unused files, categorize
* [Rework] Rework language detector

**Comment by vstakhov** [comment]
I need some samples. You can send those to me via my private email.
