### ISSUE TITLE
Get Palo Alto Wildfire Sandbox Support to rspamd as a virusscanner

### ISSUE THREAD

**Issue by nacho26** [rspamd/rspamd#2542]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [x] Not applicable

### Rspamd version:
1.7.9

### Operation system, CPU:
Debian 9
### Description (Please provide a descriptive summary of the issue):
Hi,
I wrote a little Bashscript to get the PaloAlto Wildfire Cloud as a Virusscanner to amavid-new. Link to script: https://github.com/nacho26/av-amavisd-new-wildfire
Wich way were the best to get that function into rspamd? A lua Script or something else?

Regards Marc

### Expected results:
rspamd with Wildfire Support
### Actual results:
rspamd without Wildfire Support

**Comment by vstakhov** [comment]
Your script just calls some python module. I have totally no ideas about how it calls that AV. All other things (caching, files scan etc) are already implemented in Rspamd antivirus module.

**Comment by nacho26** [comment]
Yes not enough info from me. Palo Alto Networks offers an API to the Wildfire Sandbox to their customers. You can access the api with a api key. Basicly you comute a sha256 hash of a suported file type (exe, Worddokument etc) and send it via http request to the api. From the api you get a verdict of that file like benign or malware or unknown or analysing. I store that verdict to a file in a redis so I don't need to do the query ervery time for the same file. In case the answer is unknown the script uploads the sample to the Sandbox to get analysed. If the verdict is malware the mail gets reject if its unknown or analysed the mail temp. fail with 450.

**Comment by nacho26** [comment]
You have a idear where to start to get such a function into rspamd? maybe rspamd can send the http requests direct to the wildfire api?

**Comment by c-rosenberg** [comment]
For getting attachments, their hashes and doing redis caching you can have a look to
https://github.com/rspamd/rspamd/blob/master/src/plugins/lua/antivirus.lua

For HTTP requests here https://rspamd.com/doc/lua/rspamd_http.html

**Comment by nacho26** [comment]
thanks, that means I can put that together in an own lua script for rspamd? nice

**Comment by c-rosenberg** [comment]
@nacho26 do you have some details about the Palo API? I maybe could help you with the integration.

**Comment by nacho26** [comment]
@c-rosenberg that would be nice. I have to learn lua at first :-).

The reference ist here https://www.paloaltonetworks.com/documentation/80/wildfire/wf_api/get-wildfire-information-through-the-wildfire-api

The first important step is to get a vedict of known malware via : https://www.paloaltonetworks.com/documentation/80/wildfire/wf_api/get-wildfire-information-through-the-wildfire-api/get-a-wildfire-verdict-wildfire-api#id1505c396-aab8-486e-815e-f800628881b7

If the file is unknown then it should be uploaded (only for Supported [filestypes](https://www.paloaltonetworks.com/documentation/80/wildfire/wf_admin/wildfire-overview/wildfire-file-type-support)):

https://www.paloaltonetworks.com/documentation/80/wildfire/wf_api/submit-files-and-links-through-the-wildfire-api/submit-a-local-file-to-wildfire-api#idee6e82be-eaa8-4d9e-8b7c-e7fb928cee92

And it would be great if the mail temp.fail with 450 if the attachement hasn't a verdict or is analysed at the moment.

**Comment by nacho26** [comment]
The verdicts/hashes that have been retrieved from the cloud should been cached in redis because of daily upload limits of the wf api.

**Comment by c-rosenberg** [comment]
Thanks for the docs. As it's similar I would start with virustotal api.

**Comment by nacho26** [comment]
> Thanks for the docs. As it's similar I would start with virustotal api.

We would like to switch to rspamd from amavis. But we need the wildfire support. You will add that as a feature in a comming release or do I need to figure it out myself?

If it's an offical feature will it be in 1.8 or in 1.9?

**Comment by nacho26** [comment]
> Thanks for the docs. As it's similar I would start with virustotal api.

**Comment by c-rosenberg** [comment]
Sorry for the late answer. As I am a bit out of time, this will take some weeks. If the plugins will be added is @vstakhov decision then ;)
