### ISSUE TITLE
configuration not writable/save in webUI

### ISSUE THREAD

**Issue by SandraCCH** [rspamd/rspamd#2555]
* [x] WebUI/Usability
* [X] Always

### Rspamd version:
newest

I have installed a fresh rspamd with map files. In webUI I see all my maps and other files and can read it. but I can't edit this files, and can't save points for Action (greylist/spam)

In rspamd I see this:
2018-10-01 15:56:36 #24123(main) <e7whgq>; map; rspamd_re_map_finalize: regexp map is empty
But I think this is an other problem.

**Comment by KodaCCH** [comment]
Ok. I found the Solution
Edit /etc/rspamd/local.d/worker-controller.inc
change password = to enable_password
