### ISSUE TITLE
Support having rspamd.local.lua in LOCAL_CONFDIR

### ISSUE THREAD

**Issue by griff** [rspamd/rspamd#2568]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [X] Not applicable

### Rspamd version:
1.8.0

### Operation system, CPU:
N/A

### Description (Please provide a descriptive summary of the issue):
Right now `rspamd.local.lua` is located in `$CONFDIR` and only there.

For other parts of the configuration rspamd supports having separate `$CONFDIR` and `$LOCAL_CONFDIR` and this makes it possible on NixOS to have `$CONFDIR` point to the read-only rspamd package and `$LOCAL_CONFDIR` point somewhere where user generated files can be installed.

But because `rspamd.local.lua` can only be in `$CONFDIR` you can't have custom Lua rules on NixOS without building a custom rspamd package. 

So my request is that `rules/rspamd.lua` be changed so that it either looks for `rspamd.local.lua` in `$LOCAL_CONFDIR` only, since in most cases `$LOCAL_CONFDIR = $CONFDIR`, or that it looks for both `$CONFDIR/rspamd.local.lua` and `$LOCAL_CONFDIR/rspamd.local.lua`

**Comment by vstakhov** [comment]
This is done now.

**Comment by griff** [comment]
@vstakhov I never thanked you for fixing this so: Thank you for the amazing work you do on this project.
