### ISSUE TITLE
Clickhouse arrays elements

### ISSUE THREAD

**Issue by hipotures** [rspamd/rspamd#2582]
### Classification (Please choose *one* option):
* [x ] Enhancement

### Reproducibility (Please choose *one* option):
* [X] Always

### Rspamd version: 1.8.0
For clickhouse database Urls.Tld and Urls.Url, arrays elements should be unique

### Description (Please provide a descriptive summary of the issue):
Database records:
Urls.Tld:                ['currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk','currys.co.uk']
Urls.Url:                ['t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk','t.e.currys.co.uk']

**Comment by vstakhov** [comment]
Should be fixed in 1.8.2
