### ISSUE TITLE
rspamd refuses connection from postfix

### ISSUE THREAD

**Issue by AlexCloudDev** [rspamd/rspamd#2583]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [ ] Enhancement
* [x] Question
### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.8.0
### Operation system, CPU:
docker container; debian stretch
### Description (Please provide a descriptive summary of the issue):
rspamd refuses connection to  postfix.
Both are in the same network.
The hostnames (postfix, rspamd) are known.

### Relevant logs (see details [here](https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd)):
postfix log:
`warning: connect to Milter service inet:rspamd:11332: Connection refused`

Nothing related in the rspamd log (log level "info").
### Expected results:
Postfix establishes a connection to rspamd.
### Actual results:
Postfix can't establish a connection to rspamd.
### Configuration (e.g. `rspamadm configdump module`):
rspamd worker-controller.inc:

password = "1234";
secure_ip = "postfix";

postfix main.cf:

smtpd_milters = inet:rspamd:11332
non_smtpd_milters = inet:rspamd:11332
milter_protocol = 6
milter_mail_macros =  i {mail_addr} {client_addr} {client_name} {auth_authen}
milter_default_action = accept

### Additional information:

Why is rspamd refusing the connection to postfix?

Thank you :)

**Comment by hildeb** [comment]
Try "telnet rspamd 11332" -- what's the output?


Am Do., 11. Okt. 2018 um 00:07 Uhr schrieb AlexCloudDev <
notifications@github.com>:

**Comment by drehNning** [comment]
Thank you for your help.
Output:

Trying 192.168.2.26...
telnet: Unable to connect to remote host: Connection refused

**Comment by AlexCloudDev** [comment]
My worker configs:

worker-normal.inc:
`bind_socket = "localhost:11333";`
`#count = 1`

worker-proxy.inc:
`bind_socket = "localhost:11332";`
`milter = yes;`
`timeout = 120s;`
`upstream "local" {`
`    default = yes;`
`    self_scan = yes;`
`}`

worker-controller.inc:
`password = "example";`
`#secure_ip = "postfix";`

I'm not using the web frontend, do i need the worker-controller.inc at all?

**Comment by moisseev** [comment]
> smtpd_milters = inet:rspamd:11332

> bind_socket = "localhost:11332";

`rspamd` and `localhost` resolve to different IP addresses, don't they?

> I'm not using the web frontend, do i need the worker-controller.inc at all?

You need the `controller` worker to learn Rspamd and manage statistics as well.

**Comment by AlexCloudDev** [comment]
> rspamd and localhost resolve to different IP addresses, don't they?

Yes, they do.

rspamd reolves to the ip address of the rspamd container. It is used in the postfix container's main.cf to specify the milter postfix should use.

localhost is the localhost inside the rspamd container, like 127.0.0.1.

**Comment by moisseev** [comment]
> If i understand it right, maybe i have to write
bind_socket = "ip_of_postfix_container:11332"
to make rspamd not refusing connections from outside?

To be precise it is not refusing connection, it is just not listening on the container IP.
No, it is not possible to bind it to IP of another container. To make it accessible from outside of the container, you need to bind it to the Rspamd container IP.

`bind_socket = "ip_of_rspamd_container:11332";`
The socket needs to be accessible from the Postfix container.

**Comment by moisseev** [comment]
Use `lsof` of `netstat` to check if proxy worker is listening on the expected socket. If it does it is probably Docker networking misconfiguration.

**Comment by AlexCloudDev** [comment]
Thx

`lsof -i` inside the rspamd container outputs:

`rspamd    1 root    7u  IPv4 39460878      0t0  TCP 6fcf527a7517:11333 (LISTEN)`
`rspamd    1 root    9u  IPv4 39458798      0t0  TCP 6fcf527a7517:11334 (LISTEN)`


> 6fcf527a7517:11334

is the rspamd's container ID.

About my docker network configuration i can say, that all other inter-container connections like 
postfix <--> mariadb
rspamd <--> redis
etc
are working well.
All are only communicating over their hostnames and ports.
