### ISSUE TITLE
Absurd DNS querying

### ISSUE THREAD

**Issue by azurit** [rspamd/rspamd#2585]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.8

### Operation system, CPU:
Debian 9

### Description (Please provide a descriptive summary of the issue):
My log is filled with these:

Oct 11 18:38:56 server00 rspamd[7586]: <7b5655>; lua; emails.lua:55: Error querying DNS(ht6e4d678mrgu7kc36diqheqhnt1xj9e): server fail
Oct 11 18:38:56 server00 rspamd[7586]: <381583>; lua; emails.lua:55: Error querying DNS(nnywm6iagb9pptn4q7y3j9os7k3xkynd): server fail
Oct 11 18:39:01 server00 rspamd[7586]: <2e3c86>; lua; emails.lua:55: Error querying DNS(ajnaugzwm5xuwg4f77ai478r96mgbgxz): server fail
Oct 11 18:39:01 server00 rspamd[7586]: <46012e>; lua; emails.lua:55: Error querying DNS(ajnaugzwm5xuwg4f77ai478r96mgbgxz): server fail
Oct 11 18:39:01 server00 rspamd[7586]: <9bc475>; lua; emails.lua:55: Error querying DNS(ajnaugzwm5xuwg4f77ai478r96mgbgxz): server fail
Oct 11 18:39:01 server00 rspamd[7586]: <5c6e02>; lua; emails.lua:55: Error querying DNS(ajnaugzwm5xuwg4f77ai478r96mgbgxz): server fail
Oct 11 18:39:06 server00 rspamd[7586]: <0b7ccb>; lua; emails.lua:55: Error querying DNS(8heuuuktb7wcicjdst7jbpnaq8p78mb1): server fail
Oct 11 18:39:18 server00 rspamd[7586]: <2a91c0>; lua; emails.lua:55: Error querying DNS(wdfd78kk4ggyw43qt1fd5k5dpsd888q5): server fail
Oct 11 18:39:54 server00 rspamd[7586]: <47a06d>; lua; emails.lua:55: Error querying DNS(ckbg8fx1ajhjueuunwjxymsxm3omsgmn): server fail
Oct 11 18:40:42 server00 rspamd[7586]: <13f9c4>; lua; emails.lua:55: Error querying DNS(nrbh18dbz5qd1zfjcxn34z94m4apz8oq): server fail
Oct 11 18:41:00 server00 rspamd[7586]: <8897c3>; lua; emails.lua:55: Error querying DNS(1haqepw3pju5ekeafywiqe7s9hs63o6n): server fail
Oct 11 18:41:38 server00 rspamd[7586]: <b27427>; lua; emails.lua:55: Error querying DNS(awdmkqrar79zuxtnssf33mwecxu6b9cq): server fail
Oct 11 18:41:39 server00 rspamd[7586]: <3717f7>; lua; emails.lua:55: Error querying DNS(yr91rmhatcpk78uzi7hf8i7hd6jqd546): server fail
Oct 11 18:42:12 server00 rspamd[7586]: <a42ad4>; lua; emails.lua:55: Error querying DNS(7oezamww1zshexggfog17iwsqf5csumr): server fail
Oct 11 18:42:34 server00 rspamd[7586]: <c8e376>; lua; emails.lua:55: Error querying DNS(hcagy7kjb8q11ck5w7kxk1fbjf6fi8rd): server fail
Oct 11 18:42:35 server00 rspamd[7586]: <65510b>; lua; emails.lua:55: Error querying DNS(hcagy7kjb8q11ck5w7kxk1fbjf6fi8rd): server fail
Oct 11 18:42:37 server00 rspamd[7586]: <75b71f>; lua; emails.lua:55: Error querying DNS(wmpu9u3feokhmkkhw54q7j4drjnyoq4d): server fail
Oct 11 18:42:37 server00 rspamd[7586]: <65510b>; lua; emails.lua:55: Error querying DNS(7zih79dt5fipfr3pf5t7oqh6fatba7iz): server fail
Oct 11 18:42:54 server00 rspamd[7586]: <4adc2f>; lua; emails.lua:55: Error querying DNS(mub6puhg4pjj3uzfmzbtc917y8t71pzw): server fail

**Comment by bjoe2k4** [comment]
I think you might have missed the DNSSEC root key rollover.

https://www.icann.org/dns-resolvers-checking-current-trust-anchors

**Comment by heraklit256** [comment]
What is the output of these commands:
```
dig soa dnssec-failed.org
dig soa debian.org
```

**Comment by azurit** [comment]
# dig soa dnssec-failed.org

; <<>> DiG 9.10.3-P4-Debian <<>> soa dnssec-failed.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35450
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;dnssec-failed.org.             IN      SOA

;; ANSWER SECTION:
dnssec-failed.org.      86400   IN      SOA     dns101.comcast.org. dnsadmin.comcast.net. 2010101934 900 180 604800 7200

;; Query time: 245 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Oct 17 21:30:59 CEST 2018
;; MSG SIZE  rcvd: 117

**Comment by azurit** [comment]
# dig soa debian.org

; <<>> DiG 9.10.3-P4-Debian <<>> soa debian.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62559
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;debian.org.                    IN      SOA

;; ANSWER SECTION:
debian.org.             3600    IN      SOA     denis.debian.org. hostmaster.debian.org. 2018101644 1800 600 1814400 600

;; Query time: 43 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Oct 17 21:31:18 CEST 2018
;; MSG SIZE  rcvd: 92

**Comment by azurit** [comment]
> I think you might have missed the DNSSEC root key rollover.
> 
> https://www.icann.org/dns-resolvers-checking-current-trust-anchors

Everything seems to be ok on my side, but, just to be sure, i restarted my resolver. Didn't help.

**Comment by moisseev** [comment]
No, it is not ok. The first test should return `SERVFAIL`.

**Comment by azurit** [comment]
According to web site you posted, it is ok:

# rec_control get-tas
Configured Trust Anchors:
.
                19036 8 2 49aa...
                20326 8 2 e06d...

**Comment by heraklit256** [comment]
@azurit: Thanks for the replies.

In case DNSSEC validation is desired, moisseev is right (`dnssec-failed.org` should be unreachabe by browser, too). The second response should also contain the `ad` flag, indicating authenticated data which were validated by your resolver.

Which resolver are you using? Do other applications (package management, mailserver) cause DNS trouble?

**Comment by azurit** [comment]
@heraklit256 pdns-recursor, 4.0.4-1+deb9u3+b1. I didn't noticed any other trouble. Do you have an example of a domain which should fail to resolve if i have something wrong?

**Comment by azurit** [comment]
I just upgraded to 1.8.1 and error messages changed a little:

Oct 17 21:54:58 server00 rspamd[1425]: <6e3f34>; lua; emails.lua:55: Error querying DNS(1ccfymecz97x133s9i6kpykinomag176.email.rspamd.com): server fail
Oct 17 21:55:13 server00 rspamd[1425]: <98d969>; lua; emails.lua:55: Error querying DNS(krafnu9rrkhecrboqkbs7iuoidqjxs7k.email.rspamd.com): server fail
Oct 17 21:55:37 server00 rspamd[1425]: <8446ea>; lua; emails.lua:55: Error querying DNS(yg3eshrr6t1chadnkimohyrso1antfdz.email.rspamd.com): server fail
Oct 17 21:57:03 server00 rspamd[1425]: <e4e72a>; lua; emails.lua:55: Error querying DNS(hrwwxrkggsyejqbtix19cucebn1apxfd.email.rspamd.com): server fail

**Comment by azurit** [comment]
Ok, so DNSSEC is disable in PowerDNS recursor by default, see:
https://doc.powerdns.com/md/recursor/dnssec/

process-no-validate: The default mode. In this mode the Recursor acts as a "security aware, non-validating" nameserver, meaning it will set the DO-bit on outgoing queries and will provide DNSSEC related RRsets (NSEC, RRSIG) to clients that ask for them (by means of a DO-bit in the query), except for zones provided through the auth-zones setting. It will not do any validation in this mode, not even when requested by the client.

**Comment by azurit** [comment]
So this is why i was able to resolve dnssec-failed.org and i'm missing AD flag. But, does is explain that weird DNS queries?

**Comment by azurit** [comment]
Just to be sure, i did what is here:
https://www.icann.org/dns-resolvers-updating-latest-trust-anchor

It didn't help.

**Comment by azurit** [comment]
So i set dnssec=validate:

# dig soa dnssec-failed.org

; <<>> DiG 9.10.3-P4-Debian <<>> soa dnssec-failed.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 12818
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dnssec-failed.org.             IN      SOA

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Oct 17 22:32:40 CEST 2018
;; MSG SIZE  rcvd: 35


# dig soa debian.org

; <<>> DiG 9.10.3-P4-Debian <<>> soa debian.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7540
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;debian.org.                    IN      SOA

;; ANSWER SECTION:
debian.org.             3600    IN      SOA     denis.debian.org. hostmaster.debian.org. 2018101647 1800 600 1814400 600

;; Query time: 280 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Oct 17 22:33:02 CEST 2018
;; MSG SIZE  rcvd: 92




didn't help :(

**Comment by azurit** [comment]
Why was this closed? I'm still having this issue.

**Comment by vstakhov** [comment]
Unrelated to Rspamd.

**Comment by azurit** [comment]
How is this unrelated to rspamd?

Nov 24 09:00:17 server00 rspamd[32287]: <1059d2>; lua; emails.lua:55: Error querying DNS(1kh1pszcdbcebdxmr3pr5n1n5qwg3dmf.email.rspamd.com): server fail

rspamd is querying subdomain '1kh1pszcdbcebdxmr3pr5n1n5qwg3dmf.email' on domain 'rspamd.com'.

**Comment by azurit** [comment]
It IS producing NXDOMAIN:

```
# cat /etc/resolv.conf
search .
nameserver 127.0.0.1

# dig @127.0.0.1 1kh1pszcdbcebdxmr3pr5n1n5qwg3dmf.email.rspamd.com

; <<>> DiG 9.10.3-P4-Debian <<>> @127.0.0.1 1kh1pszcdbcebdxmr3pr5n1n5qwg3dmf.email.rspamd.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 10738
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;1kh1pszcdbcebdxmr3pr5n1n5qwg3dmf.email.rspamd.com. IN A

;; AUTHORITY SECTION:
email.rspamd.com.       234     IN      SOA     ns1.asn.rspamd.com. support.rspamd.com. 1537706748 600 300 86400 300

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Nov 24 21:29:43 CET 2018
;; MSG SIZE  rcvd: 130
```

**Comment by vstakhov** [comment]
If it produces NXDOMAIN on manual lookups, then please fix your resolver. It is NOT an Rspamd issue. I'd suggest to install something like unbound and forget about this issue.

**Comment by azurit** [comment]
My resolver is ok:

```
# host 1kh1pszcdbcebdxmr3pr5n1n5qwg3dmf.email.rspamd.com
Host 1kh1pszcdbcebdxmr3pr5n1n5qwg3dmf.email.rspamd.com not found: 3(NXDOMAIN)
```

I'm running standard Debian Stretch and pdns-recursor, again, from standard Debian Stretch package.

**Comment by azurit** [comment]
I'm having the same problem also in other parts of rspamd, for example:

```
Nov 26 11:16:25 server00 rspamd[14437]: <3e5d8f>; lua; rbl.lua:153: error looking up 92.6.107.40.bip.virusfree.cz: server fail
```

**Comment by sschindel** [comment]
We also have the same issue over here. Is that some kind of ratelimiting or is it a misconfiguration on the DNS side (or client side?)

**Comment by vstakhov** [comment]
In fact, I don't quite understand why does it enable dnssec bit: it should be disabled by default.
