### ISSUE TITLE
phishtank enabled

### ISSUE THREAD

**Issue by ecoutinho** [rspamd/rspamd#2608]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):
On modules.d/phishing.conf on master branch it reads:

`# Disabled by default`
`phishtank_enabled = true;`

Shouldn't it be `phishtank_enabled = false;`?

**Comment by ecoutinho** [comment]
But if it is enabled on stock configuration, without specifying a `phishtank_map`, will it work?

**Comment by moisseev** [comment]
It queries phishtank.rspamd.com via DNS.

**Comment by ecoutinho** [comment]
OK, thanks. I didn't know that was a possibility. The Phishing module documentation lacks that information!

**Comment by ecoutinho** [comment]
Looking at phishing.lua, it seems `phishtank_map` is not even used any longer. The documentation needs to be updated.

**Comment by vstakhov** [comment]
https://help.github.com/articles/creating-a-pull-request/
