### ISSUE TITLE
ratelimit "new format" not working as described in the documentation

### ISSUE THREAD

**Issue by PHPGangsta** [rspamd/rspamd#2620]
### Classification (Please choose *one* option):

* [x] Ordinary bug

### Reproducibility (Please choose *one* option):

* [X] Always

### Rspamd version:
1.7.9 and 1.8.1

### Operation system, CPU:
Ubuntu

### Description (Please provide a descriptive summary of the issue):

The documentation says:
https://rspamd.com/doc/modules/ratelimit.html

> From version 1.5 it is also possible to define limits in a simplified form: bounce_to = "2 / 5m";
> The line above defines a bucket with a size of 2 and a leak rate of 2 message in 5 minutes (so 2 messages will be allowed per 5 minute period).

I set "15000 / 1d" in my custom_ratelimit.lua, but that results in nearly no leaked mails. It should leak 15000 mails in 1 day (compare to the sentence from the documentation), but it seams to only leak 1 mail in 1 day.

If I set "15000 / 1m", 1 Mail is leaked every minute (in the logs I can see (15000/0.016667) ).

So either the documentation is wrong, or the code is wrong. I would like to use the syntax from the documentation, because if I want to allow someone to send 15000 mails per day, it's easier to write
"15000 / 1d"
instead of
"15000 / 5.76s"

I'm not the only one who has this problem, see Mailing list:
[Rspamd-Users] Custom ratelimit: leak value

### Expected results:

"15000 / 1d" should leak 15000 mails per day

### Actual results:
"15000 / 1d" leaks only 1 mail per day

**Comment by vstakhov** [comment]
This format is a mistake in `leaky bucket` model. It's way better to specify it explicitly:

```
burst = 15000;
rate = 0.1; # One message each second
```

No fix will be made.

**Comment by herrwagner** [comment]
Hi @vstakhov , 

may be there is an issue with this new syntax:
```
info_symbol = "RATELIMIT";
rates {
  ip_limit = {
    selector = 'ip';
    bucket = {
      burst = 1000;
      rate = 0.1;
    }
  }
}
```

Configtest:
```
:/etc/rspamd/local.d# rspamadm configtest
bad limit: burst
bad limit: rate
```

**Comment by herrwagner** [comment]
> ```
> burst = 15000;
> rate = 0.1; # One message each second
> ```

I think ```rate = 0.1; # One message each second``` this is not correct.

If i understand the [module documentation](https://rspamd.com/doc/modules/ratelimit.html) right:
> burst is a capacity of a bucket and leak is a rate in messages per second. Both these attributes are floating point values.

and the example:
>     rate = 0.01666666666666666666; # leak 1 message per minute
 
it must be:

    rate = 1; # One message each second
