### ISSUE TITLE
Learning doesn't want working when message moved.

### ISSUE THREAD

**Issue by MrSorcus** [rspamd/rspamd#2625]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.8.1

### Operation system, CPU:
Archlinux, Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz

### Description (Please provide a descriptive summary of the issue):
Learning doesn't work if moving message between Spam and any other folder.

### Relevant logs (see details [here](https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd)):
dovecot logs
```
Debug: Loading modules from directory: /usr/lib/dovecot/modules
Debug: Module loaded: /usr/lib/dovecot/modules/lib95_imap_sieve_plugin.so
Debug: Effective uid=76, gid=76, home=/home/vmail/mailboxes/example.com/mail
Debug: Namespace inbox: type=private, prefix=, sep=, inbox=yes, hidden=no, list=yes, subscriptions=yes location=mdbox:/home/vmail/mailboxes/example.com/mail
Debug: fs: root=/home/vmail/mailboxes/example.com/mail, index=, indexpvt=, control=, inbox=, alt=
Debug: Mailbox INBOX: Mailbox opened because: SELECT
Debug: Mailbox Junk: Mailbox opened because: UID COPY
Debug: Namespace : Using permissions from /home/vmail/mailboxes/example.com/mail: mode=0700 gid=default
Debug: imapsieve: mailbox Junk: COPY event
Debug: sieve: Pigeonhole version 0.5.3 (f018bbab) initializing
Debug: sieve: include: sieve_global is not set; it is currently not possible to include `:global' scripts.
Debug: sieve: Sieve imapsieve plugin for Pigeonhole version 0.5.3 (f018bbab) loaded
Debug: sieve: Sieve Extprograms plugin for Pigeonhole version 0.5.3 (f018bbab) loaded
Debug: imapsieve: Static mailbox rule [1]: mailbox=`Junk' from=`*' causes=(COPY) => before=`file:/home/vmail/sieve/global/learn-spam.sieve' after=(none)
Debug: imapsieve: Static mailbox rule [2]: mailbox=`*' from=`Junk' causes=(COPY) => before=`file:/home/vmail/sieve/global/learn-ham.sieve' after=(none)
Debug: imapsieve: Matched static mailbox rule [1]
Debug: sieve: file storage: Using Sieve script path: /home/vmail/sieve/global/learn-spam.sieve
Debug: sieve: file script: Opened script `learn-spam' from `/home/vmail/sieve/global/learn-spam.sieve'
Debug: sieve: Opening script 1 of 1 from `/home/vmail/sieve/global/learn-spam.sieve'
Debug: sieve: Loading script /home/vmail/sieve/global/learn-spam.sieve
Debug: sieve: Script binary /home/vmail/sieve/global/learn-spam.svbin successfully loaded
Debug: sieve: binary save: not saving binary /home/vmail/sieve/global/learn-spam.svbin, because it is already stored
Debug: sieve: Executing script from `/home/vmail/sieve/global/learn-spam.svbin'
Debug: sieve: action pipe: running program: rspamc
Debug: Mailbox Junk: UID 4: Opened mail because: mail stream
Debug: waiting for program `/usr/bin/rspamc' to finish after 0 msecs
sieve: pipe action: piped message to program `rspamc'
sieve: left message in mailbox 'Junk'
Debug: imapsieve: mailbox INBOX: FLAG event (changed flags: \Deleted)
Debug: Mailbox INBOX: Mailbox opened because: STATUS
```
Rspamd logs are empty.

### Expected results:
Counter must be increment after every moving of message.

### Actual results:
There is no any info about learning, when message moved.

### Additional information:
postfix.conf
```
smtpd_milters = inet:localhost:11332
milter_default_action = accept
milter_protocol = 6
```

dovecot.conf
```
protocols = imap lmtp
mail_location = mdbox:/home/vmail/mailboxes/%d/%n

namespace inbox {
	type = private
	inbox = yes
	first_valid_uid = 76
	mail_attachment_dir = /home/vmail/mailboxes/%d/%n/attachments
	mail_attachment_hash = %{sha256}
}

namespace inbox {
	mailbox Drafts {
		auto = subscribe
		special_use = \Drafts
	}
	mailbox Spam {
		auto = subscribe
		special_use = \Junk
	}
	mailbox Trash {
		auto = subscribe
		special_use = \Trash
	}
	mailbox Sent {
		auto = subscribe
		special_use = \Sent
	}
	mailbox Archive {
		auto = subscribe
		special_use = \Archive
	}
}

protocols = $protocols sieve

protocol lmtp {
	mail_plugins = $mail_plugins sieve
}

protocol imap {
	mail_plugins = $mail_plugins imap_sieve
}

plugin {
	sieve = file:/home/vmail/sieve/%d/%n/scripts;active=/home/vmail/sieve/%d/%n/active.sieve
	sieve_before = /home/vmail/sieve/global/spam.sieve
	sieve_trace_debug = yes
	sieve_plugins = sieve_imapsieve sieve_extprograms

	# From elsewhere to Spam folder
	imapsieve_mailbox1_name = Junk
	imapsieve_mailbox1_causes = COPY
	imapsieve_mailbox1_before = file:/home/vmail/sieve/global/learn-spam.sieve

	# From Spam folder to elsewhere
	imapsieve_mailbox2_name = *
	imapsieve_mailbox2_from = Junk
	imapsieve_mailbox2_causes = COPY
	imapsieve_mailbox2_before = file:/home/vmail/sieve/global/learn-ham.sieve

	sieve_pipe_bin_dir = /usr/bin
	sieve_global_extensions = +vnd.dovecot.pipe imapsieve
}
```

learn-spam.sieve
```
require ["vnd.dovecot.pipe", "copy", "imapsieve"];
pipe :copy "rspamc" ["learn_spam"];
```

learn-ham.sieve
```require ["vnd.dovecot.pipe", "copy", "imapsieve"];
pipe :copy "rspamc" ["learn_ham"];
```

**Comment by c-rosenberg** [comment]
Have a look to the rspamd logs (controller entries). 

`2018-11-08 17:48:39 #2446(controller) <d1c30e>; csession; rspamd_message_parse: loaded message; id: <f2ff01d256ac$0e01ac40$3bfd90bc@eldinvk>; queue-id: <undef>; size: 485863; checksum: <69f7be644ab5e813ad3f48ddc3514a59>

2018-11-08 17:48:39 #2446(controller) <d1c30e>; csession; rspamd_mime_text_part_utf8_convert: converted from windows-1251 to UTF-8 inlen: 91, outlen: 91

2018-11-08 17:48:39 #2446(controller) <d1c30e>; csession; rspamd_mime_text_part_utf8_convert: converted from windows-1251 to UTF-8 inlen: 639, outlen: 639
2018-11-08 17:48:39 #2446(controller) <d1c30e>; csession; rspamd_mime_part_detect_language: detected part language: de

2018-11-08 17:48:39 #2446(controller) <d1c30e>; csession; rspamd_controller_learn_fin_task: <10.0.4.10> learned message as spam: f2ff01d256ac$0e01ac40$3bfd90bc@eldinvk
`

Mails learned before will not be added again.

**Comment by MrSorcus** [comment]
But if message is trash for me and i want mark it as `spam` how can i rescan them?

**Comment by c-rosenberg** [comment]
Bayes is not a blacklist, bayes should detext text contexts (also then to not learned mails)
If you want a blacklist maybe use other rspamd mechanism and a bash script to pipe from sieve. Or have a look to fuzzy.

**Comment by MrSorcus** [comment]
Ok, look at https://rspamd.com/doc/quickstart.html
What does mean `Dovecot with Sieve plugin to sort mail and learn by moving messages to Junk folder`?
Must it be learned when i moving messages or only when they coming from other servers to me?

**Comment by MrSorcus** [comment]
Now i get `connection refused`
```
[root@mx ~]# rspamc learn_spam < test.eml 
Results for file: stdin (0.000 seconds)
IO write error: Connection refused
```

**Comment by MrSorcus** [comment]
With `-h localhost:11332` i get
```
[root@mx0 ~]# rspamc learn_spam -h localhost:11332 < test.eml 
Results for file: stdin (0.000 seconds)
IO read error: unexpected EOF
```
Logs
```
2018-11-09 15:15:01 #9214(rspamd_proxy) <859be6>; proxy; proxy_accept_socket: accepted milter connection from 127.0.0.1 port 44014
2018-11-09 15:15:01 #9214(rspamd_proxy) <859be6>; proxy; proxy_milter_error_handler: abnormally closing milter connection from: 127.0.0.1, error: Command length is too big: 1347375955
```

**Comment by c-rosenberg** [comment]
likely ipv6 problem with localhost.
The proxy is the wrong service, try 127.0.0.1:11334 or just 127.0.0.1

**Comment by MrSorcus** [comment]
Yeah, now works. That's my fault.
But why doesn't work with ipv6?

**Comment by c-rosenberg** [comment]
maybe you have bind_socket = "127.0.0.1:11334"; in worker-controller.inc and localhost lookup is 

# host localhost
localhost has address 127.0.0.1
localhost has IPv6 address ::1

ipv6 is preferred then, but the the controller is not listening there.

**Comment by MrSorcus** [comment]
Oh, i must to go reread rspamd docs.
Thanks you so much. I think that issue can be closed.
