### ISSUE TITLE
Incoming mails that got forwarded by sieve rules locally (lmtp) get X-Spam: Yes conflicting with X-Spam-Status: No

### ISSUE THREAD

**Issue by pikachuprof** [rspamd/rspamd#2626]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [x] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.8.1

### Operation system, CPU:
OS: Debian 9.5 stretch
CPU: QEMU Virtual CPU version 2.5+ @ 2.2GHz

### Description (Please provide a descriptive summary of the issue):
Incoming mails that got forwarded by sieve rules locally (lmtp) (especially mails by paypal...) get a negative score:

X-Spam-Status: No, score=-10.72
X-Spamd-Result: default: False [-10.72 / 15.00];

but get still marked as spam and get moved away into spam folder:

X-Spam: Yes

### Expected results:

Mail should not be marked as Spam

**Comment by vstakhov** [comment]
This issue lacks relevant log lines.

**Comment by pikachuprof** [comment]
That's because the logfiles /var/log/rspamd/*.log are empty
