### ISSUE TITLE
rspamd didn't detect MIME_ENCRYPTED_ARCHIVE right

### ISSUE THREAD

**Issue by nacho26** [rspamd/rspamd#2629]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.8.1
### Operation system, CPU:
Debian 9 2 Core
### Description (Please provide a descriptive summary of the issue):
An rar or 7z Archive that has also an encrypted filelist is detected as MIME_ENCRYPTED_ARCHIVE. If the filelist is unencrypted and only the content is encrypted then rspamd didn't recognise it as MIME_ENCRYPTED_ARCHIVE. 
### Expected results:
recognise a 7z or rar as MIME_ENCRYPTED_ARCHIVE even if the filelist is unencrypted
### Actual results:
a 7z or rar archiv is recognised as normal Archive

**Comment by vstakhov** [comment]
I need samples to work on this issue.

**Comment by nacho26** [comment]
the twai_32.zip countains four files. 

twain_32_verschluesselt.rar -> full encrypted archive, detected as encrypted ok
twain_32_verschluesselt.7z -> full encrypted archive, detected as encrypted ok
twain_32.rar -> only content encrypted archive not the filelist, detected as normal rar, not enc. rar
twain_32.7z -> only content encrypted archive not the filelist, detected as normal rar, not enc. 7z


[twain_32.zip](https://github.com/rspamd/rspamd/files/2584700/twain_32.zip)
