### ISSUE TITLE
rspamc errors with dovecot antispam plugin

### ISSUE THREAD

**Issue by xnyhps** [rspamd/rspamd#2637]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

1.8.2.

### Operation system, CPU:

Debian 8, x86.

### Description (Please provide a descriptive summary of the issue):

I'm using rspamd with the Dovecot antispam plugin as described [here](https://kaworu.ch/blog/2014/03/25/dovecot-antispam-with-rspamd/). My dovecot config:

```
plugin {
  antispam_debug_target = syslog
  antispam_verbose_debug = 1

  antispam_backend = pipe
  antispam_trash = Deleted Messages
  antispam_spam = Spam
  antispam_pipe_program_spam_arg = learn_spam
  antispam_pipe_program_notspam_arg = learn_ham
  antispam_pipe_program = /usr/bin/rspamc
...
```

After updating rspam from 1.8.1 to 1.8.2, moving messages from my inbox to spam now often results in an error. Examining the messages, it appears that rspamc now returns an error status code for many instances where it did not before. Dovecot antispam interprets this as a fatal error, therefore refuses to move the message. This includes "errors" such as "... has been already learned as spam, ignore it" and "... is skipped for bayes classifier: already in class spam; probability 100.00%". Especially the second one occurs quite often when moving potential spam into the spam folder.

### Relevant logs (see details [here](https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd)):

syslog:
```
Nov 20 18:22:20 localhost imap: antispam: mailbox_is_unsure(Spam): 0
Nov 20 18:22:20 localhost imap: antispam: mailbox_is_trash(Possible spam): 0
Nov 20 18:22:20 localhost imap: antispam: mailbox_is_trash(Spam): 0
Nov 20 18:22:20 localhost imap: antispam: mail copy: from trash: 0, to trash: 0
Nov 20 18:22:20 localhost imap: antispam: mailbox_is_spam(Possible spam): 0
Nov 20 18:22:20 localhost imap: antispam: mailbox_is_spam(Spam): 1
Nov 20 18:22:20 localhost imap: antispam: mailbox_is_unsure(Possible spam): 0
Nov 20 18:22:20 localhost imap: antispam: mail copy: src spam: 0, dst spam: 1, src unsure: 0
Nov 20 18:22:20 localhost imap: antispam: running mailtrain backend program /usr/bin/rspamc
Nov 20 18:22:20 localhost imap: antispam: running mailtrain backend program /usr/bin/rspamc
Nov 20 18:22:20 localhost imap: antispam: running mailtrain backend program parameter 1 learn_spam
Nov 20 18:22:20 localhost imap: antispam: run program failed with exit code 1
```

rspamd.log:
```
2018-11-20 18:22:20 #8933(controller) <5e0965>; csession; rspamd_controller_check_password: allow unauthorized connection from a trusted IP 127.0.0.1
2018-11-20 18:22:20 #8933(controller) <5e0965>; csession; rspamd_message_parse: loaded message; id: <817854805.2784524.1538485151421@mail.yahoo.com>; queue-id: <undef>; size: 63106; checksum: <2af71c3c196ca00166bf092ef111e642>
2018-11-20 18:22:20 #8933(controller) <5e0965>; csession; rspamd_mime_part_detect_language: detected part language: en
2018-11-20 18:22:20 #8933(controller) <5e0965>; csession; rspamd_task_process: learn error: <817854805.2784524.1538485151421@mail.yahoo.com> is skipped for bayes classifier: already in class spam; probability 100.00%
2018-11-20 18:22:20 #8933(controller) <5e0965>; csession; rspamd_controller_learn_fin_task: cannot learn <817854805.2784524.1538485151421@mail.yahoo.com>: <817854805.2784524.1538485151421@mail.yahoo.com> is skipped for bayes classifier: already in class spam; probability 100.00%
```

### Expected results:
Moving a message to the Spam folder works.

### Actual results:
Moving a message to the Spam folder doesn't work.

### Additional information:

This is probably related to the fix of #2627.

**Comment by manuelgrabowski** [comment]
I have the same issue.

**Comment by stephdl** [comment]
same for me I have the error in logs

```
Nov 26 12:34:31 prometheus rspamd[6887]: <790a25>; csession; rspamd_task_process: learn error: <038D18A2.4A1A97DF@hyper.net.id> is skipped for bayes classifier: already in class spam; probability 100.00%
Nov 26 12:34:31 prometheus postfix/pipe[13367]: 0ACB5193D7E32: to=<stephane@domain.fr+learn_spam@spamtrain.nh>, relay=spamtrain, delay=0.46, delays=0.32/0.01/0/0.13, dsn=5.3.0, status=bounced (Command died with status 1: "/usr/bin/rspamc". Command output: Results for file: stdin (0.002 seconds) HTTP error: 410, <038D18A2.4A1A97DF@hyper.net.id> is skipped for bayes classifier: already in class spam; probability 100.00%  )
```


Something has changed with the version 1.8.2

**Comment by stephdl** [comment]
I would like to resume here what it occurs after an exchange with @vstakhov  on telegram

Now rspamc gives back an operation status on failure or success, this of course is intended to be right in the unix philosophy.

The concern here is to understand if the `already learned` must be understood as an error or a warn. IMHO, it is just a warn, rspamc is not broken and workable.

If the core is not patched to accept a different behavior on spam found as `already learned` as spam this is other way to use rspamc

- Use a wrapper to change the return code
- Use `rspamc learn_spam || true` -> no error code will happen ever

The best fix could be to change the 4xx error in learning to a 2xx code or another acceptable value

**Comment by DavidePrincipi** [comment]
If the upstream developer does't revert to the old behavior,  the wrapper is our only possible solution.

I guess `rspamc learn_spam || :` can't work from Postfix master.cf because it's a Bash command. Thus a wrapper script is required.

**Comment by stephdl** [comment]
Really thank you :)

**Comment by vstakhov** [comment]
I have released stable packages of 1.8.2 with this fix.

**Comment by stephdl** [comment]
Good job,  for me the fix close the bug, now on already in class spam, the value of return is not an error

```
Nov 27 21:21:10 prometheus rspamd[10359]: <3155cf>; csession; rspamd_mime_part_detect_language: detected part language: en
Nov 27 21:21:10 prometheus rspamd[10359]: <3155cf>; csession; rspamd_task_process: learn error: <DCB5CA6B.741EE033@reteivo.com> is skipped for bayes classifier: already in class spam; probability 100.00%
Nov 27 21:21:10 prometheus postfix/pipe[10741]: AEA4B193D7E28: to=<stephane@domain.fr+learn_spam@spamtrain.nh>, relay=spamtrain, delay=0.45, delays=0.43/0.01/0/0.01, dsn=2.0.0, status=sent (delivered via spamtrain service)
Nov 27 21:21:10 prometheus postfix/qmgr[30138]: AEA4B193D7E28: removed
```

**Comment by manuelgrabowski** [comment]
Can confirm, this update fixes the problem. Thanks for the quick reaction! 👍

**Comment by stephdl** [comment]
@vstakhov I can see many error in history now with 

`learn error: has been already learned as spam, ignore it`

I downgraded to 1.8.1 to check if these errors were reported in logs

**Comment by stephdl** [comment]
Hi @xnyhps 

Please this issue could be closed now, not granted to do it myself
