### ISSUE TITLE
per recipient disabled greylisting is not working

### ISSUE THREAD

**Issue by rseffner** [rspamd/rspamd#2643]
### Classification (Please choose *one* option):
* [x] Ordinary bug

### Reproducibility (Please choose *one* option):
* [x] Always

### Rspamd version:
1.8.1

### Operation system
debian 8.11 amd64

### Description (Please provide a descriptive summary of the issue):
I set up the following, getting TEST_SYMBOL into mail headers but it not stops greylisting:

ns1:~# rspamadm configdump settings
*** Section settings ***
no_greylist {
    symbols [
        "TEST_SYMBOL",
    ]
    id = "no_greylist";
    apply {
        actions {
            greylist = null;
        }
        TEST_SYMBOL = 0.100000;
    }
    priority = high;
    rcpt = "@seffner.de";
    rcpt = "@seffner-schlesier.de";
}
*** End of section settings ***

### Relevant logs (see details [here](https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd)):
From UI history:

...
TEST_SYMBOL (0.1)
GREYLIST (0) [greylisted,Thu, 22 Nov 2018 18:21:19 GMT,new record]
...

### Expected results:
No greylisting for specified recipient domains.

### Actual results:
As shown in logs, a greylist header entry.
Also at a telnet session, a smtp 45x temp fail.

### Configuration:
As shown in description part.

### Additional information:
I asked this twice at mailing list without an answer. "greylist = null;' as an possible action I got from documentation.

**Comment by rseffner** [comment]
same in 1.8.2

**Comment by rseffner** [comment]
same in 1.8.3

**Comment by rseffner** [comment]
I'll give it a try.
But what about "greylist = null; # Disable greylisting (from 1.8.1)" in https://rspamd.com/doc/configuration/settings.html?

**Comment by rseffner** [comment]
Now I set up the following:

`ns1:~# rspamadm configdump settings
*** Section settings ***
no_greylist {
    id = "no_greylist";
    apply {
        TEST_SYMBOL = 0.100000;
    }
    symbols [
        "TEST_SYMBOL",
    ]
    rcpt = "ronny@seffner.de";
    rcpt = "@seffner-schlesier.de";
    priority = 9999;
    symbols_diabled [
        "GREYLIST_CHECK",
        "GREYLIST_SAVE",
    ]
}

*** End of section settings ***
`
But mails to e.g. ronny@seffner.de were still greylistetd. What I'm doing wrong?

**Comment by vstakhov** [comment]
Those should be in apply block.
