### ISSUE TITLE
BASE64 Encoding in FROM is not decoded

### ISSUE THREAD

**Issue by derhelge** [rspamd/rspamd#2645]
### Classification (Please choose *one* option):
* [X] Ordinary bug

### Reproducibility (Please choose *one* option):
* [X] Always

### Rspamd version:
1.8.2
### Operation system, CPU:
CentOS7.5, vCPU
### Description (Please provide a descriptive summary of the issue):

Right now i see a lot of spam where the from field is partly BASE64 encoded:
`From: =?UTF-8?B?TXVzdGVyLCBNYXggPG1heC5tdXN0ZXJAZXhhbXBsZS5jb20+?= <max.muster@example.com>`

The decoded BASE64 string is an email address (including angle brackets, in this case: `Muster, Max <max.muster@example.com>` ). Unfortunately rspamd does not recognize the doubled FROM.

In 352a465639b64e024e54e25b76d59e4e68b798b5 this issue was already adressed but reverted in a4255c642865592ed07c79113d78c86d1650d27c due to unknown reasons.

**Comment by vstakhov** [comment]
In fact, I have added unicode validation for that pieces of the decoded data. Hence, I think that a4255c6 could be reverted back.

**Comment by vstakhov** [comment]
Done in 772964f83b82f6d597e22c8b4d08220ab7df3f43
