### ISSUE TITLE
bayes autolearn ham works unexpectedly

### ISSUE THREAD

**Issue by toto4ds** [rspamd/rspamd#2647]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.8.2
### Operation system, CPU:
linux, i386
### Description (Please provide a descriptive summary of the issue):
/etc/rspamd/local.d/statistic.conf
autolearn = [-5, 15];
ham learns not lower, but higher
#1131(rspamd_proxy) <d2953b>; proxy; rspamd_stat_check_autolearn: <CAB4kfxhinX6ZaAq1-H+Gb26ZD0vWSRLmRP77_Yqzsr5bz9NiKg@mail.gmail.com>: autolearn ham for classifier 'bayes' as message's score is negative: -4.44
spam works fine
### Expected results:
autolearn ham less -5
### Actual results:
autolearn ham between [0,-5]

**Comment by tjharman** [comment]
`/etc/rspamd/local.d/statistic.conf
`
That's not where you'd put an autolearn command.  Putting it there means it's outside the "classifier "bayes" {" section.

You should put it in local.d/classifier-bayes.conf, which is within that section.

Also you can check what actual config is being applied by rspamdadm configdump, as suggested above.

**Comment by toto4ds** [comment]
classifier {
    bayes {
        backend = "redis";
        min_tokens = 11;
        min_learns = 200;
        statfile {
            spam = false;
            symbol = "BAYES_HAM";
        }
        statfile {
            spam = true;
            symbol = "BAYES_SPAM";
        }
        autolearn = true;
        autolearn [
            -5,
            15,
        ]
        tokenizer {
            name = "osb";
        }
        servers = "localhost:6378";
        per_user = false;
    }
}

**Comment by tjharman** [comment]
Right, you have autolearn = true; there
That will cause the bug you have.

Re-read the docs on what to set autolearn to :)

(hint, one or the other, not both)

**Comment by tjharman** [comment]
> There are 3 possibilities to specify autolearning:
> 
> autolearn = true: autolearning is performing as spam if a message has reject action and as ham if a message has negative score
> autolearn = [-5, 5]: autolearn as ham if score is less -5 and as spam if score is more than 5
> autolearn = "return function(task) ... end": use the following Lua function to detect if autolearn is needed (function should return ‘ham’ if learn as ham is needed and string ‘spam’ if learn as spam is needed, if no learn is needed then a function can return anything including nil)

**Comment by toto4ds** [comment]
Oh, my mistake I am sorry = /
