### ISSUE TITLE
Ransomware - asks payment for video

### ISSUE THREAD

**Issue by robertboyl** [rspamd/rspamd#2649]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

Guys,

If you can pls try to create rules for this type of ransomware/hoax, where spammer informs he recorded a video of user and asks for payment, appreciate it. Scores very little.

See attachment.
[example.txt](https://github.com/rspamd/rspamd/files/2615504/example.txt)

Thanks!

**Comment by robertboyl** [comment]
1 more example.
[example2.txt](https://github.com/rspamd/rspamd/files/2615591/example2.txt)

**Comment by andryyy** [comment]
Are they always (almost) the same? You can try a local fuzzy storage then.

**Comment by robertboyl** [comment]
Hello! Thank you.

They are similar, but the wording changes. Ive been trying to collect samples and add words to our Spamassassin.

Also, when we move to spam it teaches rspamd, I believe it helps with fuzzy... So lets see.

When you say fuzzy storage, I believe this happens when we move false negatives to spam box.Is there another way?

But might be nice specific rules, if possible...

Perhaps other users can also send samples here.

Thanks!

**Comment by robertboyl** [comment]
1 more
[example3.txt](https://github.com/rspamd/rspamd/files/2615809/example3.txt)

**Comment by robertboyl** [comment]
1 more, this time in spanish.
[example4.txt](https://github.com/rspamd/rspamd/files/2615839/example4.txt)

**Comment by c-rosenberg** [comment]
Example 1 seems to be the same issue as discussed at spamassassin: [http://spamassassin.1065346.n5.nabble.com/9D-character-used-in-words-to-avoid-detection-td153717.html#a153736](http://spamassassin.1065346.n5.nabble.com/9D-character-used-in-words-to-avoid-detection-td153717.html#a153736)

The other examples got reject score while scanning with rspamc. Example4 is also listed in rspamd.com fuzzy.

**Comment by vstakhov** [comment]
I think I'll be able to workaround this easily. This character is transferred to ZERO WIDTH NON-JOINER in UTF8.
