### ISSUE TITLE
Bayes statistic returns false/no values

### ISSUE THREAD

**Issue by gamuse** [rspamd/rspamd#2650]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.8.1

### Operation system, CPU:
Ubuntu Linux

### Actual results:
Full score of ham or spam for some mails or no score. Sometimes, learned spam gets ham-score and for ham, too.

### Expected results:
Spam-/Ham-score in every mail with gradations.

### Configuration (e.g. `rspamadm configdump module`):
<pre><code>bayes {
    backend = "redis";
    min_tokens = 11;
    min_learns = 150;
    new_schema = true;
    statfile {
        spam = false;
        symbol = "BAYES_HAM";
    }
    statfile {
        spam = true;
        symbol = "BAYES_SPAM";
    }
    tokenizer {
        name = "osb";
    }
    learn_condition = &lt;&lt;EOD
return function(task, is_spam, is_unlearn)
  local prob = task:get_mempool():get_variable('bayes_prob', 'double')

  if prob then
    local in_class = false
    local cl
    if is_spam then
      cl = 'spam'
      in_class = prob >= 0.95
    else
      cl = 'ham'
      in_class = prob <= 0.05
    end

    if in_class then
      return false,string.format('already in class %s; probability %.2f%%',
        cl, math.abs((prob - 0.5) * 200.0))
    end
  end
  return true
end
EOD;
    per_user = true;
}</code></pre>

**Comment by vstakhov** [comment]
There cannot be score nor symbol when there is not enough confidence about this message, e.g. if no tokens have been seen previously or there are not enough of tokens that have been previously learned. Not an issue.
