### ISSUE TITLE
rspamc puts headers in middle of header

### ISSUE THREAD

**Issue by estiloinfo** [rspamd/rspamd#2652]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [] Always
* [X] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):
When receive mail with previous classify by "spamassassin" header contain this info

Subject: VACACIONES
Date: Wed, 28 Nov 2018 16:30:34 -0300
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="----=_NextPart_000_0091_01D48737.AF9F7100"
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 6.00.2900.5843
Disposition-Notification-To: "Rosario Impresos" <administracion@rimpresos.com.ar>
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2900.5579
X-Antivirus: avast! (VPS 181127-0, 27/11/2018), Outbound message
X-Antivirus-Status: Clean
X-Spam-Status: No, score=0.3
X-Spam-Score: 3
X-Spam-Bar: /
X-Ham-Report: Spam detection software, running on the system "server46.tudns7.info",
 has NOT identified this incoming email as spam.  The original
 message has been attached to this so you can view it or label
 similar future email.  If you have any questions, see
 root\@localhost for details.
 
 Content preview:  LES INFORMANOS A NUESTROS CLIENTES Y AMIGOS QUE LA FIRMA ROSARIO
    IMPRESOS CIERRA POR VACACIONES A PARTIR DEL JUEVES 27/12/2018 HASTA EL 12/01/2019
    INCLUSIVE. ANTICIPE SU PEDIDO. VOLVEMOS A ENVIAR ESTE [...] 
 
 Content analysis details:   (0.3 points, 5.0 required)
 
  pts rule name              description
 ---- ---------------------- --------------------------------------------------
 -1.9 BAYES_00               BODY: Bayes spam probability is 0 to 1%
                             [score: 0.0000]
 -0.0 RCVD_IN_DNSWL_NONE     RBL: Sender listed at http://www.dnswl.org/,
                             no trust
                             [190.226.41.10 listed in list.dnswl.org]
  0.0 HTML_MESSAGE           BODY: HTML included in message
  1.0 KAM_HTMLNOISE          Spam containing useless HTML padding
  0.0 UPPERCASE_75_100       message body is 75-100% uppercase
  0.2 KAM_MANYTO             Email has more than one To Header or more than 25
                             recipients
  1.0 KAM_LAZY_DOMAIN_SECURITY Sending domain does not have any
                             anti-forgery methods
X-Spam-Flag: NO

------=_NextPart_000_0091_01D48737.AF9F7100
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

Then process mail with "rspamc --user account --mime EMAIL_FILE". The modify header is

Subject: VACACIONES
Date: Wed, 28 Nov 2018 16:30:34 -0300
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="----=_NextPart_000_0091_01D48737.AF9F7100"
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 6.00.2900.5843
Disposition-Notification-To: "Rosario Impresos" <administracion@rimpresos.com.ar>
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2900.5579
X-Antivirus: avast! (VPS 181127-0, 27/11/2018), Outbound message
X-Antivirus-Status: Clean
X-Spam-Status: No, score=0.3
X-Spam-Score: 3
X-Spam-Bar: /
X-Ham-Report: Spam detection software, running on the system "server46.tudns7.info",
 has NOT identified this incoming email as spam.  The original
 message has been attached to this so you can view it or label
 similar future email.  If you have any questions, see
 root\@localhost for details.
 X-Spam-Scanner: rspamc 1.8.1
X-Spam-Scan-Time: 0.983
X-Spam: yes
X-Spam-Action: add header
X-Spam-Score: 11.25 / 15.00
X-Spam-Level: ************
X-Spam-Symbols: ARC_NA,
	HAS_REPLYTO,
	FROM_HAS_DN,
	TO_DN_SOME,
	FREEMAIL_ENVRCPT,
	REPLYTO_DN_EQ_FROM_DN,
	TAGGED_RCPT,
	PREVIOUSLY_DELIVERED,
	REPLYTO_ADDR_EQ_FROM,
	MIME_GOOD,
	HAS_X_PRIO_THREE,
	SUBJ_ALL_CAPS,
	RCPT_COUNT_TWELVE,
	FREEMAIL_TO,
	RCVD_NO_TLS_LAST,
	FROM_EQ_ENVFROM,
	MID_RHS_NOT_FQDN,
	BROKEN_HEADERS,
	RCVD_COUNT_SEVEN

 Content preview:  LES INFORMANOS A NUESTROS CLIENTES Y AMIGOS QUE LA FIRMA ROSARIO
    IMPRESOS CIERRA POR VACACIONES A PARTIR DEL JUEVES 27/12/2018 HASTA EL 12/01/2019
    INCLUSIVE. ANTICIPE SU PEDIDO. VOLVEMOS A ENVIAR ESTE [...] 
 
 Content analysis details:   (0.3 points, 5.0 required)
 
  pts rule name              description
 ---- ---------------------- --------------------------------------------------
 -1.9 BAYES_00               BODY: Bayes spam probability is 0 to 1%
                             [score: 0.0000]
 -0.0 RCVD_IN_DNSWL_NONE     RBL: Sender listed at http://www.dnswl.org/,
                             no trust
                             [190.226.41.10 listed in list.dnswl.org]
  0.0 HTML_MESSAGE           BODY: HTML included in message
  1.0 KAM_HTMLNOISE          Spam containing useless HTML padding
  0.0 UPPERCASE_75_100       message body is 75-100% uppercase
  0.2 KAM_MANYTO             Email has more than one To Header or more than 25
                             recipients
  1.0 KAM_LAZY_DOMAIN_SECURITY Sending domain does not have any
                             anti-forgery methods
X-Spam-Flag: NO

------=_NextPart_000_0091_01D48737.AF9F7100
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

The header added by rspamc is in de middle of info added by spamassassin

### Configuration (e.g. `rspamadm configdump module`):
rspamadm configdump actions
*** Section actions ***
rewrite_subject = 14;
add_header = 6;
greylist = 4;
reject = 15;
*** End of section actions ***

**Comment by estiloinfo** [comment]
I probe in version 1.8.4 same error

**Comment by vstakhov** [comment]
`rspamc --mime` support is somewhere at the very bottom of my TODO list. Please use some sane integration model where possible.

**Comment by estiloinfo** [comment]
Ok, I test same email msg via milter protocol, and same result. Header added in the middle of  spamassasing header.  If you want i can attach email file after send to rspamd

**Comment by vstakhov** [comment]
Then your spamassassin header is broken: simple. In fact, in milter mode, it is MTA who inserts/alters headers. If your MTA designates this header as broken and Rspamd designates this header as broken then it is broken.

**Comment by estiloinfo** [comment]
you right!! Sorry and thanks. 
I recompile version 1.8.4 and rspamc works fine when add header.
