### ISSUE TITLE
clickhouse database

### ISSUE THREAD

**Issue by hipotures** [rspamd/rspamd#2655]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [x] Enhancement

Please add possibility to choose protocol type http/https, login, password and database name for Clickhouse database. It should look like this:
https://login:password@clickhouse.server:port/?database=test?query=....

Now if I add login and password I've got error:
"cannot parse clickhouse address"

**Comment by vstakhov** [comment]
You can specify user and password by setting them in `clickhouse.conf` separately (`user` and `password` parameters accordingly).
