### ISSUE TITLE
'has been already learned as spam, ignore it' fill my history tab

### ISSUE THREAD

**Issue by stephdl** [rspamd/rspamd#2658]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
rspamd 1.8.2-2
### Operation system, CPU:
centos7
### Description (Please provide a descriptive summary of the issue):

From time to time rspamd complains that the spam is already in the class spam in its logs

for example : 

```
Nov 30 01:26:09 prometheus rspamd[2893]: <52f247>; proxy; rspamd_task_process: learn error: <3797AE0A.A8DB9BFE@3008.es> has been already learned as sp
am, ignore it
```
This does not affect the work of rspamd except that the error fills the history tab in the rspamd UI, and other errors could not be displayed. @moisseev do you think we could filter this kind of lines and not display them ?

### Expected results:

I expect that this line of logs is understood as a warn and not an error

### Actual results:
Actually each time this line appears, an error is displayed in the tab history

**Comment by stephdl** [comment]
![screenshot_2018-11-30 prometheus 980 rspamd - rspamd web interface 1](https://user-images.githubusercontent.com/3164851/49280124-9c03ed00-f489-11e8-9c1e-7929209acabb.png)

**Comment by moisseev** [comment]
In my opinion, it is not an error, actually. @vstakhov Can we just change its severity to `notice`?

**Comment by stephdl** [comment]
yes, a `notice` should be good

**Comment by stephdl** [comment]
Hi @vstakhov 

thank for the 1.8.3 version today, do you think we could change the severity to something not an error, the history tab is full of learn error

**Comment by stephdl** [comment]
I figured that the `learn error` comes after a virus detection found by clamav

```
Dec  9 04:15:38 prometheus rspamd[25030]: <8fd7a1>; lua; antivirus.lua:105: clamav: virus found: "Sanesecurity.Scam.12538.UNOFFICIAL"
Dec  9 04:15:38 prometheus rspamd[25030]: <8fd7a1>; proxy; rspamd_add_passthrough_result: <8EE2A1D8.933C75AB@chello.pl>: set pre-result to reject (no score): 'clamav: virus found: "Sanesecurity.Scam.12538.UNOFFICIAL"' from antivirus(1)
Dec  9 04:15:38 prometheus rspamd[25030]: <8fd7a1>; surbl; process_dns_results: <8EE2A1D8.933C75AB@chello.pl> domain [helgahanna.su] is in surbl sbl.spamhaus.org(200007f)
Dec  9 04:15:38 prometheus rspamd[25030]: <8fd7a1>; proxy; rspamd_check_group_score: maximum group score 12.50 for group surbl has been reached, ignoring symbol URIBL_SBL with weight 6.50
Dec  9 04:15:38 prometheus rspamd[25030]: <8fd7a1>; proxy; rspamd_stat_check_autolearn: <8EE2A1D8.933C75AB@chello.pl>: autolearn spam for classifier 'bayes' as message's action is reject, score: 43.26
Dec  9 04:15:38 prometheus rspamd[25030]: <8fd7a1>; proxy; rspamd_task_process: learn error: <8EE2A1D8.933C75AB@chello.pl> has been already learned as spam, ignore it
```


this is the full [gist](https://gist.github.com/74417907b11026e3cf51eff619b77a02)

**Comment by stephdl** [comment]
`set pre-result to reject (no score)`

will try to set a score in /etc/rspamd/scores.d/nethserver_group.conf

```
symbols = {
    symbol "CLAM_VIRUS" {
        weight = 200.0;
        description = "Clamav Antivirus found";
    }
}
```
