### ISSUE TITLE
DCC result is not logged anymore

### ISSUE THREAD

**Issue by anothatuber** [rspamd/rspamd#2659]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version: 1.8.2

Since commit 37e36c1cdc313152df847b4b8e83bb2188db8c7d src/plugins/lua/dcc.lua doesn't log the dcc result on the same loglevel as the request as it was moved from rspamd_logger to lua_util.
rspamd.com/doc/modules/dcc.md on the other hand still lists both log lines.

I for my part would like to see the result in the logs (even more than the request). The following change does the trick.
```
- lua_util.debugm(N, task, 'DCC result=%1 disposition=%2 header="%3"',
+ rspamd_logger.warnx(task, 'DCC result=%1 disposition=%2 header="%3"',
```
If this isn't wanted, please correct the documentation accordingly.

**Comment by vstakhov** [comment]
You can enable dcc module debug in `logging.inc` by adding it to the `debug_modules`.

**Comment by anothatuber** [comment]
But is this output really seen as debug output? I'd say that's even more interesting than
`lua; dcc.lua:170: sending to /var/lib/dcc/dccifd:nil`
