### ISSUE TITLE
Sentinel - read/write servers

### ISSUE THREAD

**Issue by hipotures** [rspamd/rspamd#2663]
### Classification (Please choose *one* option):
* [X] Ordinary bug

### Reproducibility (Please choose *one* option):
* [X] Always

### Rspamd version:
1.8.3
### Description (Please provide a descriptive summary of the issue):
Read and write server list are the same.

### Additional information:
lua_redis.lua, line 147:
    local write_servers_str = table.concat(read_servers_tbl, ',')
should be:
    local write_servers_str = table.concat(write_servers_tbl, ',')

**Comment by vstakhov** [comment]
Good catch!
