### ISSUE TITLE
some mails are not scanned (dns timeout)

### ISSUE THREAD

**Issue by stuzfuz** [rspamd/rspamd#2666]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [X] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [X] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
Rspamd daemon version 1.8.2

### Operation system, CPU:
Debian, Docker

### Description (Please provide a descriptive summary of the issue):
I am using Mailcow with rspamd since about a year and I'm super exited with the performance of rspamd.
Sometimes it happens that some mails are not scanned and got a score with 0.00.
Example attached:
![47601595-7770ad00-d9d3-11e8-8d1d-576829619cb4](https://user-images.githubusercontent.com/5834441/49494492-1eacf380-f860-11e8-861d-d41073690812.jpg)

Already asked the Mailcow guys to help me with that issue:
https://github.com/mailcow/mailcow-dockerized/issues/1957

### Relevant logs (see details [here](https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd)):
As the corresponding logs to the above picture already aged out I've grabbed new log lines:
^[[36mrspamd-mailcow_1 |^[[0m 2018-12-04 03:28:57 #11(normal) ; lua; lua_redis.lua:224: use default Redis settings for keep_spam
^[[36mrspamd-mailcow_1 |^[[0m 2018-12-04 03:28:57 #11(normal) ; lua; settings.lua:358: check for settings
^[[36mrspamd-mailcow_1 |^[[0m 2018-12-04 03:28:57 #11(normal) ; lua; settings.lua:385: XXXXXXXXXXXXX@qq.shibuichic.com apply settings according to rule score_XXXXXXXXXXXXXXXX
^[[36mrspamd-mailcow_1 |^[[0m 2018-12-04 03:29:02 #10(controller) ; map; rspamd_map_cache_cb: cached data is now expired (gen mismatch 72401 != 72402) for http://nginx:8081/forwardinghosts.php
^[[36mrspamd-mailcow_1 |^[[0m 2018-12-04 03:29:09 #10(controller) <533dwi>; map; http_map_finish: data is not modified for server updates.rspamd.com, next check at Tue, 04 Dec 2018 02:29:39 GMT
^[[36mrspamd-mailcow_1 |^[[0m 2018-12-04 03:29:09 #11(normal) ; task; rspamd_task_timeout: processing of task timed out, forced processing
^[[36mrspamd-mailcow_1 |^[[0m 2018-12-04 03:29:09 #11(normal) ; lua; asn.lua:69: error querying dns (129.145.227.165.asn.rspamd.com): query timed out

### Expected results:
Should scan every incomming mail

### Actual results:
Scans most of the incomming mails, but sometimes they got through without being scanned

### Configuration (e.g. `rspamadm configdump module`):
Default mailcow config

**Comment by tjharman** [comment]
Change your DNS timeout.
Read options.inc and see this setting:

dns {
    timeout = 1s;
    sockets = 16;
    retransmits = 5;
}

Put whatever timeout you want in.

This isn't a bug.

**Comment by stuzfuz** [comment]
Is there a best practice available for these settings?

**Comment by GMTA** [comment]
> This isn't a bug.

How isn't it a bug that NO scan takes place whatsoever if a DNS request times out?

**Comment by tjharman** [comment]
@stuzfuz You can specify multiple DNS servers to spread the load, or set them up in a master slave config.  The FAQ has more info: https://rspamd.com/doc/faq.html - As for "best practise" I don't know I'm sorry.

@GMTA The rspamd FAQ says clearly that rspamd will be "totally broken" if DNS resolution doesn't work.  I agree, you could argue that rspamd should try to defer messages it can't process, but what if it's in front of a massive mailserver, but there's a DNS outage.  Is it better to just let the mail pass, or to reject all mail because the DNS is out?  I can imagine that if it rejected/deferred mail there'd be a different group of people not happy with that default.

It says pretty clearly in the FAQ if your DNS is broken then rspamd is broken, so this doesn't seem a bug rather a call to fix the DNS infrastructure.

**Comment by GMTA** [comment]
@tjharman You are absolutely right about that FAQ entry. I find it odd that rspamd defaults to "let everything pass" in that case - there are a multitude of reasons why DNS stops working, rate limiting being just one of them. But that's a discussion for another ticket :-)

**Comment by vstakhov** [comment]
There is now option to emit soft reject when task times out.
