### ISSUE TITLE
Sentinel - choose only good read servers

### ISSUE THREAD

**Issue by hipotures** [rspamd/rspamd#2667]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.8.3

### Description (Please provide a descriptive summary of the issue):
Don't read from faulty server, you need read 'master-link-status' from SENTINEL SLAVES master-name:
if slave['master-link-status'] == 'ok' then we have good connection master-slave :)

**Comment by hipotures** [comment]
Redis version 4.0.10

**Comment by vstakhov** [comment]
Added, thanks for testing that :)
