### ISSUE TITLE
Assert checkpoint->cur_item == NULL faild in rspamd_symcache_check_symbol

### ISSUE THREAD

**Issue by zhang15535135608** [rspamd/rspamd#2669]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):
Start an async task in  normal filter plugin, if task timeout happend, will case rspamd abort. The probleme happends event time.

first: I created a type='filter' plugin
next:  I am set task timeout is 8s, set async http request timeout is 30s.
next: I use nc -l -p 11335 (do nothing), and send  mail.
result: if task timeout callback before http request timeout callback, rspamd assert faild in rspamd_symcache_check_symbol

### Relevant logs (see details [here](https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd)):

Program received signal SIGABRT, Aborted.
0x00007f6421bcd107 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007f6421bcd107 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f6421bce4e8 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f6425a33477 in g_assertion_message () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f6425a33994 in g_assertion_message_expr () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x000000000053c0a6 in rspamd_symcache_check_symbol (task=0x27cb0e0, cache=0x17fe5d0, item=0x22ded38, 
    checkpoint=0x27d51a0) at /data/rspamd/src/libserver/rspamd_symcache.c:1449
#5  0x000000000053d24b in rspamd_symcache_process_symbols (task=0x27cb0e0, cache=0x17fe5d0, stage=1024)
    at /data/rspamd/src/libserver/rspamd_symcache.c:1881
#6  0x00000000005417b0 in rspamd_task_process (task=0x27cb0e0, stages=131071) at /data/rspamd/src/libserver/task.c:796
#7  0x0000000000541b55 in rspamd_task_process (task=0x27cb0e0, stages=131071) at /data/rspamd/src/libserver/task.c:888
#8  0x0000000000541b55 in rspamd_task_process (task=0x27cb0e0, stages=131071) at /data/rspamd/src/libserver/task.c:888
#9  0x0000000000541b55 in rspamd_task_process (task=0x27cb0e0, stages=131071) at /data/rspamd/src/libserver/task.c:888
#10 0x0000000000541b55 in rspamd_task_process (task=0x27cb0e0, stages=131071) at /data/rspamd/src/libserver/task.c:888
#11 0x0000000000447127 in rspamd_task_timeout (fd=-1, what=1, ud=0x27cb0e0) at /data/rspamd/src/worker.c:148
#12 0x00007f6425554254 in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#13 0x00000000004484f8 in start_worker (worker=0x27b2370) at /data/rspamd/src/worker.c:688
#14 0x000000000054be95 in rspamd_fork_worker (rspamd_main=0x17fb0d0, cf=0x1899f10, index=0, ev_base=0x2923ad0)
    at /data/rspamd/src/libserver/worker_util.c:688
---Type <return> to continue, or q <return> to quit---q

(gdb) f 4
#4  0x000000000053c0a6 in rspamd_symcache_check_symbol (task=0x27cb0e0, cache=0x17fe5d0, item=0x22ded38, 
    checkpoint=0x27d51a0) at /data/rspamd/src/libserver/rspamd_symcache.c:1449
1449			g_assert (checkpoint->cur_item == NULL);
(gdb) l
1444	#else
1445			t1 = rspamd_get_ticks (FALSE);
1446	#endif
1447			dyn_item->start_msec = (t1 - task->time_real) * 1e3;
1448			dyn_item->async_events = 0;
1449			g_assert (checkpoint->cur_item == NULL);
1450			checkpoint->cur_item = item;
1451			checkpoint->items_inflight ++;
1452			/* Callback now must finalize itself */
1453			item->specific.normal.func (task, item, item->specific.normal.user_data);
(gdb) p checkpoint->cur_item 
$1 = (struct rspamd_symcache_item *) 0x1842628
(gdb) p *checkpoint->cur_item 
$2 = {st = 0x7f6426149920, last_count = 0, cd = 0x1842698, symbol = 0x18426b0 "LUA_SQUEEZE", type = 10244, 
  specific = {normal = {func = 0x4cfd83 <lua_metric_symbol_callback>, user_data = 0x7f6420e850d0, condition_cb = -1}, 
    virtual = {parent = 5045635}}, enabled = 1, is_filter = 1, is_virtual = 0, priority = 1, order = 2147483650, 
  id = 24, frequency_peaks = 0, deps = 0x183c320, rdeps = 0x183c340}
(gdb) 

### Additional information:

-- test demo: test_filter.lua

local rspamd_logger = require "rspamd_logger"
local ucl = require "ucl"
local rspamd_regexp = require "rspamd_regexp"

local rspamd_http = require "rspamd_http"

local function http_callback(err, code, body, header)
	if(err == nil) then
		err = ""
	end
	if(code == nil) then
		code = ""
	end
	if(body == nil) then
		body = ""
	end
	if(header == nil) then
		header = ""
	end

	rspamd_logger.errx(err .. code .. body .. header)
end

local function test_cb(task)
    rspamd_logger.errx("test plugin")

    rspamd_http.request({
        task=task,
        url="http://127.0.0.1:1235",
        body="",
        callback=http_callback,
        timeout = 30,
        mime_type='application/json',
    })

end

local function configure_test_module()
	rspamd_config:register_symbol({
		name = "test_filter",
		priority = 10,
		type = "filter",
		callback = test_cb,
	})
end

configure_test_module()

-- we set task timeout is 8s, use nc listen 1235 but do nothing  (http request timeout is 30s)

**Comment by vstakhov** [comment]
I believe it was fixed in 1.8.3

**Comment by zhang15535135608** [comment]
Thanks, can you provide a issue number?

**Comment by vstakhov** [comment]
Assume to be fixed.
