### ISSUE TITLE
Well-formed JSON compatibility within UCL include statement

### ISSUE THREAD

**Issue by msaladna** [rspamd/rspamd#2674]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [X] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.8.3

### Operation system, CPU:
CentOS 7.5 x86-64

### Description (Please provide a descriptive summary of the issue):
According to documentation, UCL is compatible with JSON. Moreover, per the [example](https://rspamd.com/doc/configuration/ucl.html#general-syntax-sugar), 

> General syntax sugar
Braces are not necessary to enclose a top object: it is automatically treated as an object:
`"key": "value"`
is equal to:
`{"key": "value"}`
There is no requirement of quotes for strings and keys, moreover, : may be replaced = or even be skipped for objects:
`key = value;`

Therefore based upon documentation the following should work in `/etc/rspamd/local.d/actions.conf` as it is functionally equivalent to "add_header = 99;"

```
{
   "add_header": 99
}
```

This does not. But if I replace UCL in `/etc/rspamd/actions.conf` with JSON it's OK.
```
{
actions: { add_header: 99}
}
```

Alternatively I dropped the actions: { ... } in local.d thinking that would work, but it elicited an error as well mentioned below.

### Compile errors (if any):
N/A

### Relevant logs (see details [here](https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd)):
N/A

### Expected results:
```
# rspamadm configdump | grep add_header
        add_header = 99;
```

### Actual results:
When treating local.d/actions.conf as top-level JSON:
*(Sample #1)*
```
failed to load config: ucl parser error: /etc/rspamd/actions.conf:30 object closed with } is not opened with { at line 2
```

When encapsulating local.d/actions.conf in actions var:
*(Sample #2)*
```
# rspamadm configdump | grep add_header
nested section: actions { actions { ... } }, it is likely a configuration error
    add_header = 6;
        add_header = 99;
```

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
N/A

### Configuration (e.g. `rspamadm configdump module`):
**Sample /etc/rspamd/actions.conf**
```
actions {
    add_header = 6; # Add header when reaching this score
    .include(try=true; priority=1; duplicate=merge) "$LOCAL_CONFDIR/local.d/actions.conf"
    .include(try=true; priority=10) "$LOCAL_CONFDIR/override.d/actions.conf"
}
```
**Sample /etc/rspamd/local.d/actions.conf**
```
{ 
  "add_header": 2   
}
```

**Second sample /etc/rspamd/local.d/actions.conf**
```
{ 
  "actions": {
    "add_header": 2   
  }
}
```
### Additional information:
Adapting include() to accept JSON or maybe add a format=json parameter to include directives will allow JSON tools such as Ansible to work with rspamd.

**Comment by msaladna** [comment]
Experimenting with it more, if I create a local configuration without {} it works, e.g.
`/etc/rspamd/local.d/actions.conf`
```
add_header: 99,
greylist: 199,
something: {
   else: 299
}
```

Updated title. Accepting "{" and "}" in the file would make it easier to parse with other utilities.

**Comment by vstakhov** [comment]
This isn't likely possible to fix. At least, there is no simple fix. Includes are very special as they leave parser stack untouched. Literally, your `}` closes the parent object. I don't have any intentions to fix this particular thing.

**Comment by dminuoso** [comment]
@vstakhov Can you explain why exactly that causes the problem?

Naively I'd assume that parsing an isolated file should be unproblematic as long as it's valid JSON. I mean if it was malformed, sure I can see how this could propagate errors out. But really, how can the closing `}` not be associated with the starting `{` in the same file?

**Comment by vstakhov** [comment]
You might treat `include` statement as copy that file and paste its content here instead of the `include` statement. If you think about it in this way it would be crystal clear why

```
foo = bar;
```

will work as expected within a file included, whilst

```
{
foo = bar;
}
```

will create a nested object.

**Comment by dminuoso** [comment]
Thanks, that makes perfect sense. So this happens because the macro is spliced in the middle of an object.

Then I wonder, can we splice a macro on the value side (or perhaps even as a list element)?  Just wondering because at that point we could splice in a full JSON object.

```
{
  foo = .include "path";
} 
```

That attempt itself seems to cnsider `.include "path"` to be a string, rather than splicing in the file at path.
```

The documentation subtly implies this is not possible.
