### ISSUE TITLE
Error using rspamd_lru_hash in spf.c plugin

### ISSUE THREAD

**Issue by zhang15535135608** [rspamd/rspamd#2675]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):

The spf records deadline use dns ttl in rspamd_lru_hash. this deadline means at some point after the current time. however, in rspamd_lru_hash, this deadline means not lookup it during this period. 

other, the dns ttl in seconds, but rspamd_lru_hash use min to second comparison? 

eg: 
I cache a spf record in 10:00:00, dns ttl is 1s. I except to expire after 10:00:05.
If there is no query lru in time 10:00:00-10:01:00, the record will expire aftre 10:01:00. ( use min to second comparison? )
other, If i am querying lru in time 10:00:00-10:01:00,  the record will expire after 10:02:00. querying lru in time 10:01:00-10:02:00, the record will expire after 10:03:00. (the record always revalidation, not update).

the codes:
rspamd_lru_hash_lookup (rspamd_lru_hash_t *hash, gconstpointer key, time_t now)
{
    rspamd_lru_element_t *res;
    res = g_hash_table_lookup (hash->tbl, key);
    if (res != NULL) {
        **now = TIME_TO_TS(now);  // second to minute ??**
        if (res->ttl != 0) {
            **if (now - res->last > res->ttl) { // the minute compare second?**
                rspamd_lru_hash_remove_node (hash, res);
                return NULL;
            }
        }
        **res->last = MAX (res->last, now); // revalidate, not update**
        rspamd_lru_hash_update_counter (res);
        rspamd_lru_hash_maybe_evict (hash, res);
        return res->data;
    }
    return NULL;
}

**Comment by zhang15535135608** [comment]
sorry, I except to expire after 10:00:01.

**Comment by zhang15535135608** [comment]
I want to know the lru ttl meaning.

1. This cache object expires after ttl seconds
2. Not accessed during this period, the cache object expires.

**Comment by vstakhov** [comment]
All times are in minutes in LFU cache. `last` field is used to implement decay of infrequently used records (http://antirez.com/news/109). Probably, there should be a separate field to match TTL indeed. I will check it.
