### ISSUE TITLE
Statistics / Bayes module not checking email

### ISSUE THREAD

**Issue by athanp** [rspamd/rspamd#2676]
Hi,,

I have almost 130 learnt spam and ham in redis and the following **local.d/classifier-bayes.conf** but rspamd 1.8.3 is not adding the bayes header in each email thus I assume the statistics module still doesn't check them.

```
cache {
    backend = "redis";
}

backend = "redis";
min_tokens = 11;
min_learns = 10;
autolearn = true;
new_schema = true;
languages_enabled = false;
per_language = false;
per_user = false;
expire = -1;

statfile {
    symbol = "BAYES_HAM";
    spam = false;
}
statfile {
    symbol = "BAYES_SPAM";
    spam = true;
}
```
BTW all other rspam modules put their headers in email.

Did I miss something?

PS: Rspamd  1.83 self scanning milter + Postfix/ FreeBSD 12/

**Comment by athanp** [comment]
> I'm guessing that rspamd will not include bayes symbols until the ham and spam class or more than 200.

Do you have **min_learns = xx** where xx < 200? If so it means that rspamd ignores this setting and always defaults to 200, an obvious bug.

In my own setup I've learnt rspamd 1100 spam and 130 ham messages and min_learns = 10 but still no BAYES symbol appear in header.

**Comment by Rayzilt** [comment]
My **rspamadm configdump** tells me that **min_learns** is configured at **200**, this is default indeed and I did not configure that. I configured bayes to use redis (rsapmadm configwizard) and nothing more. Was surprised that the bayes symbol was missing and went searching for a answer.

No idea if this is correct configured now.
