### ISSUE TITLE
Redis client doesn't follow redirect from redis cluster

### ISSUE THREAD

**Issue by xjodoin** [rspamd/rspamd#2677]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.8.3
### Description (Please provide a descriptive summary of the issue):

replies.lua:102: redis_set_cb received error: MOVED 8435 192.168.60.235:7000

**Comment by vstakhov** [comment]
Redis cluster is not supported and there are no plans to add this support to Rspamd.
