### ISSUE TITLE
whitelist: customized scores not applied

### ISSUE THREAD

**Issue by uvelokk** [rspamd/rspamd#2679]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Rspamd version:
1.8.3

### Operation system, CPU:
Debian 9 amd64

### Description (Please provide a descriptive summary of the issue):
Whitelist module customized scores from /etc/rspamd/local.d/whitelist.conf not applied during analysis. For example:
```
blah@blah:~# rspamadm configdump whitelist
*** Section whitelist ***
rules {
    WHITELIST_DMARC {
        inverse_symbol = "BLACKLIST_DMARC";
        score = -15;
        domains = "/etc/rspamd/white_dmarc.map";
        valid_dmarc = true;
    }
    WHITELIST_SPF_DKIM {
        valid_spf = true;
        inverse_symbol = "BLACKLIST_SPF_DKIM";
        domains = "/etc/rspamd/white_spf_dkim.map";
        valid_dkim = true;
        score = -10;
    }
 ```

From log file:
...WHITELIST_DMARC(-7.00) ...
...WHITELIST_SPF_DKIM(-3.00) ...

**Comment by vstakhov** [comment]
You need to define those scores in symbols as that's the place where they are redefined with higher priority.
