### ISSUE TITLE
Cannot log into web gui, domain/auth not found

### ISSUE THREAD

**Issue by armartar** [rspamd/rspamd#2683]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
Rspamd daemon version 1.8.3

### Operation system, CPU:
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"

### Description (Please provide a descriptive summary of the issue):
Installed rspam as a part of this tutorial https://thomas-leister.de/en/mailserver-debian-stretch/. When I try to access web gui I am correctly prompted with a password but given same "jquery-3.3.1.min.js:2 GET https://mydomain.com/auth 404 (Not Found)" every time I enter correct password. I rechecked password by generating another one using rspamadm pw and pasting it into worker-controller.inc as password parameter. After that I reinstalled rspam using https://rspamd.com/downloads.html but I still fail to log into web gui. On every unsuccessful login there is an undefined and request failed popup.

### Compile errors (if any):
jquery-3.3.1.min.js:2 GET https://mydomain.com/auth 404 (Not Found) in console.

### Relevant logs (see details [here](https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd)):
/

### Expected results:
I should be able to log into web gui.

### Actual results:
Unsuccessful logins with undefined and request failed popup.

### Configuration (e.g. `rspamadm configdump module`):
[config.txt](https://github.com/rspamd/rspamd/files/2683076/config.txt)

**Comment by tjharman** [comment]
You don't show us how you're trying to access the WebGUI.
Do you have it in front of a proxy?
Are you accessing it via a SSH Tunnel?

You have only bound the interface to localhost, so how are you accessing localhost from your webbrowser?  Is the web browser running on the same host the rspamd is running on (doubtful)?

`worker {
    controller {
        password = "$2$4xz31e3ogrekr596uaw4hzbeyeq6fgks$nc3ok6cc9ua6f9jwiptnk7kopzspksf9yrcycqtmgozxuzh81d8y";
        secure_ip = "127.0.0.1";
        secure_ip = "::1";
        enable_password = "$2$neq189it378nnr9ryfupjaf5ij7f6puu$4scu1c5er3xp8818mk6okfu6jscx961ko8usbzsg6781i1bkj4jy";
        static_dir = "/usr/share/rspamd/www/";
        count = 1;
        bind_socket = "localhost:11334";
    }
}
`

**Comment by armartar** [comment]
I am trying to access it via WebGUI from a computer in a same local network, no proxy, direct access to VM. Web browser is actually running on the same host as rspamd. So the rspamd, whole mail config and a web server for GUI are running on same virtual machine (VM) which is accessed via local domain / IP. I can reach WebGUI, problem is that the password does not work. See the printscreen below. 
![spam](https://user-images.githubusercontent.com/22413559/50336286-187c6f80-050e-11e9-8870-76e66c97b025.PNG)

**Comment by vstakhov** [comment]
Not Rspamd issue, closing.
