### ISSUE TITLE
WebUI uploading SPAM javascript error

### ISSUE THREAD

**Issue by xrayn** [rspamd/rspamd#2684]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [X] WebUI/Usability
* [ ] Serious bug
* [x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.8.3
### Operation system, CPU:
Linux
### Description:

Uploading data for learning spam seems to work, but the expected alert message is not generated. Instead the following error occurs.

upload.js:55 Uncaught TypeError: Cannot read property 'success' of undefined
    at Object.success (upload.js:55)
    at Object.complete (rspamd.js:226)
    at u (jquery-3.3.1.min.js:2)
    at Object.fireWith (jquery-3.3.1.min.js:2)
    at k (jquery-3.3.1.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery-3.3.1.min.js:2)

Expected behavior would be triggering the alert function. However, it seems, the return object is not defined/returned correctly.

                    if (json[0].data.success) {
                        rspamd.alertMessage("alert-success", "Data successfully uploaded");
                    }

https://github.com/rspamd/rspamd/blob/master/interface/js/app/upload.js#L53

**Comment by chmoelders** [comment]
Same here.

PR https://github.com/rspamd/rspamd/pull/2685 should close this issue.
