### ISSUE TITLE
different BAYES_SPAM for the same message using one redis-server

### ISSUE THREAD

**Issue by ameagle** [rspamd/rspamd#2687]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
Rspamd daemon version 1.8.0
### Operation system, CPU:
FreeBsd 10.3 on two the same servers
### Description (Please provide a descriptive summary of the issue):
Different Symbol: BAYES_SPAM for the same message, using the same redis server
### Expected results:
Symbol: BAYES_SPAM (4.80)[99.99%] for both servers
### Configuration (e.g. `rspamadm configdump module`):
I have the same configuration on both servers with one redis-server(carp_db).
But I get different BAYES_SPAM for the same message. Other symbols are the same.

root@msk02:/usr/local/etc/rspamd# rspamadm configdump classifier
*** Section classifier ***
bayes {
    backend = "redis";
    min_tokens = 11;
    languages_enabled = true;
    autolearn [
        -4,
        7,
    ]
    cache {
        type = "redis";
    }
    learn_condition = <<EOD
return function(task, is_spam, is_unlearn)
  local prob = task:get_mempool():get_variable('bayes_prob', 'double')

  if prob then
    local in_class = false
    local cl
    if is_spam then
      cl = 'spam'
      in_class = prob >= 0.95
    else
      cl = 'ham'
      in_class = prob <= 0.05
    end

    if in_class then
      return false,string.format('already in class %s; probability %.2f%%',
        cl, math.abs((prob - 0.5) * 200.0))
    end
  end

  return true
end
EOD;
    new_schema = true;
    statfile {
        spam = false;
        symbol = "BAYES_HAM";
    }
    statfile {
        spam = true;
        symbol = "BAYES_SPAM";
    }
    min_learns = 200;
    tokenizer {
        name = "osb";
    }
    name = "common";
    servers = "carp_db:6379";
}

*** End of section classifier ***

root@msk01:~/spam_test# rspamadm configdump classifier
*** Section classifier ***
bayes {
    backend = "redis";
    min_tokens = 11;
    languages_enabled = true;
    autolearn [
        -4,
        7,
    ]
    cache {
        type = "redis";
    }
    learn_condition = <<EOD
return function(task, is_spam, is_unlearn)
  local prob = task:get_mempool():get_variable('bayes_prob', 'double')

  if prob then
    local in_class = false
    local cl
    if is_spam then
      cl = 'spam'
      in_class = prob >= 0.95
    else
      cl = 'ham'
      in_class = prob <= 0.05
    end

    if in_class then
      return false,string.format('already in class %s; probability %.2f%%',
        cl, math.abs((prob - 0.5) * 200.0))
    end
  end

  return true
end
EOD;
    new_schema = true;
    statfile {
        spam = false;
        symbol = "BAYES_HAM";
    }
    statfile {
        spam = true;
        symbol = "BAYES_SPAM";
    }
    min_learns = 200;
    tokenizer {
        name = "osb";
    }
    name = "common";
    servers = "carp_db:6379";
}

*** End of section classifier ***

root@msk02:~/spam_test# rspamc -p 0545138691
Score: 3.37 / 8.00
Symbol: BAYES_SPAM (0.67)[78.17%]
....

root@msk01:~/spam_test# rspamc -p 0545138691
Score: 9.50 / 8.00
Symbol: BAYES_SPAM (4.80)[99.99%]
....

### Additional information:

**Comment by vstakhov** [comment]
No feedback, closing.
