### ISSUE TITLE
rspamc learn fails for already learned messages

### ISSUE THREAD

**Issue by stbuehler** [rspamd/rspamd#2691]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

`1.8.3-1~stretch`

### Operation system, CPU:

Debian stretch, amd64

### Description (Please provide a descriptive summary of the issue):

rspamc learn fails (with exit code 1) for already learned messages (`RSPAMD_TASK_FLAG_ALREADY_LEARNED`):

    # rspamc learn_spam
    [...]
    Results for file: stdin (0.004 seconds)
    HTTP error: 404, <...> has been already learned as spam, ignore it
    # echo $?
    1

### Expected results:

The exit code should be 0; learning didn't change the database because it didn't have to, not because something was wrong.

**Comment by c-rosenberg** [comment]
https://github.com/rspamd/rspamd/commit/d8c8fd5641a138cdf6e7dd6ee8dae39c4815cbae#diff-02786adb24b9071288d5a4f3456bdb64 fixed this.


```
# apt-cache policy rspamd                                                                                                                                                                     
rspamd:
  Installed: 1.8.3-1~stretch

# rspamc learn_spam file
Results for file: file (0.044 seconds)
error = "<...> has been already learned as spam, ignore it";
filename = "file";
scan_time = 0.044001;

# echo $?
0
```
And the same when using curl.

**Comment by sbergman27** [comment]
This is a significant issue for users of, say, Dovecot Antispam.  I had to write a wrapper script to check for a return code of 1 and return a 0 in that case.  Otherwise, users are unable to move previously seen emails in or out of "Junk", or out of the "unsure" folder. rspamc really needs to return a 0 in the case of previously seen emails.
