### ISSUE TITLE
Please support IPv6 on fuzzy{1,2}.rspamd.com

### ISSUE THREAD

**Issue by Natureshadow** [rspamd/rspamd#2695]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [X] Enhancement

### Description (Please provide a descriptive summary of the issue):

We are running rspamd on an IPv6-only host (like all our internal systems that do not need to be reached by users over the internet). This works well, except the fuzzy checks against the rspamd-provided hosts fail because neither of the servers is reachable via IPv6.

Please enable IPv6 on the fuzzy servers so rspamd instances that have no IPv4 connectivity to the internet can use them.

**Comment by Natureshadow** [comment]
>I'm sorry but IPv6 will not be supported as it proved to cause issues
>with many IPv4 only setups that are prevailing in the Internet so far.

Huh?

Can you please elaborate on that a bit?

**Comment by Natureshadow** [comment]
Maybe you misunderstood the request: I am asking to add an IPv6 address for fuzzy1.rspamd.com and fuzzy2.rspamd.com, so that these services are reachable via IPv6 as well. I do not see how this would in any way interfere with IPv4. The only thing that will look different for IPv4 clients is the presence of an AAAA record, which it will ignore.

**Comment by Natureshadow** [comment]
I do not understand what is wrong with just adding IPv6 to existing hosts, but a dedicated hostname would at least solve the issue.

**Comment by vstakhov** [comment]
Rspamd does not select another address when retransmitting request. So for people with no IPv6 connectivity (like me, for example) it will cause random fuzzy failures. I have fixed some pieces of logic in the master as there were also couple of bugs when there was live v4 and dead v6 addresses. However, the initial issue is not resolved and I don't see any sane and simple enough way to do it safely for UDP.

Furthermore, I've just realised that a VM where fuzzy storage lives there is even no IPv6 address. I'm not inclined to add one as it requires some efforts and I have neither time nor desire to do that.

**Comment by Natureshadow** [comment]
> Rspamd does not select another address when retransmitting request. So for people with no IPv6 connectivity (like me, for example) it will cause random fuzzy failures.

No, this is plain nonsense. On hosts with no IPv6, rspamd would simply not try IPv6 in the first place. It would not even query the DNS for AAAA records.

It is rather astonishing that we rely on security-relevant software written by someone who is incapable of understanding even the most basic questions of how network software works :o. Maybe we should fix that instead.

**Comment by vstakhov** [comment]
I praise your competence in the networking - of course you are free to fork off.
