### ISSUE TITLE
Please extend the antivirus module for ESET Mail Security Linux / FreeBSD

### ISSUE THREAD

**Issue by hhjanhh** [rspamd/rspamd#2697]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [X] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [X] Not applicable

### Description (Please provide a descriptive summary of the issue):
I'ld like to see ESET antivirus support.
Please extend the antivirus module for ESET Mail Security Linux / FreeBSD

Please  
https://www.eset.com/business/server-antivirus/mail-security-linux/
www.eset.com

Thanks
hhjanhh

**Comment by grufocom** [comment]
You can tell postfix to use the content_filter method to integrate ESET:
https://help.eset.com/ems_linux/4/en-US/setting_esets_postfix.html
What would be better on integrating it into rspamd?

**Comment by hhjanhh** [comment]
The main difference is that Milter happens pre-queue, i.e. before Postfix accepts the mail. Content filtering happens post-queue.
The downside to the post-queue approach is that Postfix cannot reject the mail in real-time.

**Comment by grufocom** [comment]
That's true but for antivirus scanning it's ok to get involved after the mail was accepted by rspamd - I think. Better than no antivirus...

**Comment by hhjanhh** [comment]
Eset has a antispam component, too

**Comment by c-rosenberg** [comment]
As far as I can see none of the protocols for eset mail security are sufficient for rspamd (don't know exactly for cgp and gwia):

https://help.eset.com/ems_linux/4/en-US/architecture_overview.html

Would icap (gateway security) be an option?
