### ISSUE TITLE
milter_headers: export add_header score

### ISSUE THREAD

**Issue by stbuehler** [rspamd/rspamd#2699]
### Classification

* [x] Enhancement

### Reproducibility

* [X] Always

### Rspamd version:

`1.8.3-1~stretch`

### Description (Please provide a descriptive summary of the issue):

milter_headers should export the "add_header" score (in e.g. `"x-spamd-result:"`); the maximum score is often the reject score, and is not helpful in establishing a "relative" spam rating like "80% spam" (for something like https://wiki2.dovecot.org/Pigeonhole/Sieve/Extensions/SpamtestVirustest).

As far as I can tell lua doesn't have access to this information yet; there is only a wrapper for `rspamd_task_get_required_score`, which is a rather useless information ("rspamd might stop searching for more if it reaches this score" and "highest score for any action").

Maybe an option (disabled by default for compat?) could be added to export all 3 scores: `[actual / add_header / max]`.

**Comment by c-rosenberg** [comment]
Maybe as Workaround:

```
custom {
    rspamd_sieve = <<EOD
-- X-Rspamd-Sieve: -6.14 / 11.00 / 15.00
return function(task, common_meta)
  local actions_settings = task:lookup_settings('actions')
  local actions_config = rspamd_config:get_key('actions')
  local metric_score = task:get_metric_score('default')

  local add_header = '-'

  if actions_settings.add_header ~=nil then 
    add_header = actions_settings.add_header
  elseif actions_config.add_header ~=nil then 
    add_header = actions_config.add_header
  end

  -- parameters are task and metadata from previous functions
  return nil, -- no error
    {['X-Rspamd-Sieve'] = string.format('%.2f', metric_score[1]) .. ' / '
      .. string.format('%.2f', add_header) .. ' / ' .. string.format('%.2f', metric_score[2])},
    {['X-Rspamd-Sieve'] = 1}, -- remove foreign X-Foo headers
    {} -- metadata to return to other functions
  end
EOD;
}
```

The required score (and current score) is in task:get_metric_score('default'). But if you set reject = null; the function will return the "nearest" required score (rewrite_subject, add_header).

**Comment by stbuehler** [comment]
Interesting idea, thx!
