### ISSUE TITLE
Debian-based package missing dependencies

### ISSUE THREAD

**Issue by brenard** [rspamd/rspamd#2700]
### Classification :

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility :

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

1.8.3

### Description (Please provide a descriptive summary of the issue):
 This following packages should be declared as _Build-Depends_ in _debian/control_ file :
- libunwind-dev
- libfann-dev

**Comment by vstakhov** [comment]
Rspamd doesn't need libfann for anything. Here is the script that builds Rspamd packages for Debian: https://github.com/rspamd/rspamd-build-scripts/blob/master/rspamd_build.sh#L532
