### ISSUE TITLE
DMARC sending report: pls add option for STARTTLS to support TLS-only server

### ISSUE THREAD

**Issue by TDannhauer** [rspamd/rspamd#2701]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [X] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.8.3

### Operation system, CPU:
debian buster, xen virtualized

### Description (Please provide a descriptive summary of the issue):

To send DMARC reports one has to provide SMTP configuration. However, it is not possible to configure whether the connection should be encrypted or not (STARTTLS)

As a consequence dmarc reports cannot be send from systems which provide SMTP auth only in encrypted connections (after STARTTLS).

### Compile errors (if any):
- 

### Relevant logs (see details [here](https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd)):

#26255(controller) <>; lua; dmarc.lua:920: got bad smtp response: 530 5.7.0 Must issue a STARTTLS command first

### Expected results:

It should be possible to configure whether SMTP connection should be establisehd encrypted or unencrypted.

### Actual results:

It is not possible to configure whether SMTP connection should be establisehd encrypted or unencrypted.

**Comment by vstakhov** [comment]
Lua TCP client used in Rspamd does not support SSL. Adding SSL is not extremely hard, however, adding starttls is almost impossible. Nevertheless, it is again a trivial problem resolved by a local MTA relay. It will not be added to Rspamd.

**Comment by TDannhauer** [comment]
Thanks, for the explanation and your erffort.

A local MTA is indeed a possible solution - but an ugly one. In times of NSA & Co, it should not be neccessary to setup a relay MTA to enable encryption.

From operational perspective every running softwareis also a possible source of malfunction. Setting up an MTA should have besser reasons than adding encryption.

For sure it is not a short term solution, but maybe Lua TCP client is not the right one if enabling encryption is a show stopper..  

Just my two cents.
