### ISSUE TITLE
Enhance rspamc to learn from compresed mails

### ISSUE THREAD

**Issue by TDannhauer** [rspamd/rspamd#2702]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.8.3

### Operation system, CPU:

debian buster, XEN virtualized

### Description (Please provide a descriptive summary of the issue):
currently, rspamc can learn ham and spam only from uncompressed mails.
However, with dovecot installations using maildir, mails are often stored compressed.

To avoid lengthly workarounds, it would be great if spamc can handle compressed mails as well.

### Compile errors (if any):
-
### Expected results:
-
### Actual results:
-

**Comment by vstakhov** [comment]
Why cannot you use `gzip` pipe? I'd refrain from adding complexity to a C program where a trivial shell wrapper could be used.

**Comment by TDannhauer** [comment]
Yes, this is a valid argument.
However, easy to use tools which support out of the box common scenaria are very welcome by every administrators. Piping gzip is possible, but there are nicer solutions. Thanks anyway.
