### ISSUE TITLE
Reasonable default settings for ARC

### ISSUE THREAD

**Issue by prehor** [rspamd/rspamd#2703]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
```
Rspamd daemon version 1.8.3
```

### Description (Please provide a descriptive summary of the issue):
The `ARC` module inherits its default settings from the `DKIM Signing` module, but they usually has to be overwritten because the `DKIM Signing` module's default settings are reasonable for signing outgoing e-mails while the `ARC` module should sign incoming e-mails. More reasonable default settings for `ARC` module are:
```bash
# Sign only external incoming e-mails
auth_only = false;
sign_local = false;
sign_inbound = true;

# Use envelope recipient's domain for signing
use_domain = "recipient";

# Ignore header/from/user mismatches
allow_hdrfrom_mismatch = true;
allow_hdrfrom_multiple = true;
allow_username_mismatch = true;
```

If pull request #2657 is merged, the server domain (`hostname -d`) could be used as the default value for `use_domain`.

**Comment by prehor** [comment]
Hi @vstakhov,

I know that the ARC should only sign the forwarded emails, but I do not think the existing ARC module configuration options in rspamd allow it.

In a simple set-up with all-in-one postfix and rspamd milter, rspamd is called before envelope recipients expansion, so rspamd is not able to find out whether the email will be delivered locally or forwarded, or even both at once. In this case, however, it is able to recognize that it is an external incoming email to be delivered to a local domain and to create an ARC signature. The ARC signature will not only have forwarded emails, but also emails delivered to local mailboxes, allowing users to forward email sent to their mailbox on their own. The above default values for the ARC module are suitable for this (I think often used) rspamd deployment.

In a more complex setup with incomming and outgoing postfix and rspamd milter in incomming postfix for creating Authentication-Result: header and rspamd milter in the outgoing postfix for creating ARC signatures from Authentication-Result: header, the ARC module is unable to find the ARC selector domain because the original recipient of forwarded emails is not in the authenticated user name, the envelope sender, the header sender, or the envelope recipient and may not even be in (now not applicable) header recipient. This would only be possible if ARC module will be able to configure static ARC selector domain (see #2657) for non originating emails. The above default values for the ARC module helps in this case too.

**Comment by vstakhov** [comment]
Ok, I will think more about it, thanks!

**Comment by tjharman** [comment]
Sorry to drag up an old, closed issue.
But "sign_inbound = true;" isn't a supported option for arc.

```
-!- rspamd/plugins » grep inbound arc.lua
-!- rspamd/plugins »                      
```

**Comment by tjharman** [comment]
Thanks @prehor for your settings above.
With this I am now able to correctly sign messages I am forwarding on.
Without these settings, this wasn't happening.

**Comment by klausenbusk** [comment]
> Ok, I will think more about it, thanks!

Would a PR be accepted?
