### ISSUE TITLE
Spamtrap doesnt trap a address over the mapfile

### ISSUE THREAD

**Issue by centertivevier** [rspamd/rspamd#2721]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [X] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Configuration (e.g. `rspamadm configdump module`):

Under:

/etc/rspamd/local.d/spamtrap.conf

action = "reject";
score = 14.0;
learn_fuzzy = true;
learn_spam = true;
map = file://$LOCAL_CONFDIR/maps.d/spamtrap.map;

and create the mapfile with:

/^example@test\.eu$/

### Additional information:

The mail to this spamtrapadresses send are going the to the inbox of the user, but not rejected from rspamd and learning to the filter. I have not an idea what ist wrong. On the log files is not problem listed with this configuration.

**Comment by centertivevier** [comment]
I have set it to example@test.eu but is not used. On documentation of the spamtrap module you see it this:

An example of a map file is:

/^test@example\.test$/
/^.*@catchalldomain.test$/

**Comment by remkolodder** [comment]
Ugh, you are right. Sorry for overlooking that.

So what I have is this;

/^user@domain\.tld$/
/^.*@sub\.domain\.tld$/

And that works fine..

**Comment by centertivevier** [comment]
Hi,

ok i get a new mail to this spamtrap address, but is doenst use it. Rspamd learn not the mal as a spam :-( or reject it.

**Comment by centertivevier** [comment]
Hi,

i have solved the problem with redis. With the mapfile had not a chance to create the spamtrapadress. I have disable the mapfile and write the spamtrapaddress to the redisserver. Now, the server are learning from this spamtrapaddress.
