### ISSUE TITLE
Please allow symlinks in controller static_dir

### ISSUE THREAD

**Issue by niol** [rspamd/rspamd#2726]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

1.8.1

### Operation system, CPU:

Debian GNU/Linux amd64

### Description (Please provide a descriptive summary of the issue):

Distribution usually package dependencies in other packages or directories, even for js libraries. js is usually symlinked from `/usr/share/javascript` where is system wide js file is installed.
However, rspamd controller checks the served files are in static_dir:

```c
    /* We also need to ensure that file is inside the defined dir */
    rspamd_strlcpy (filebuf, realbuf, sizeof (filebuf));
    dir = dirname (filebuf);

    if (dir == NULL ||
        !rspamd_http_router_is_subdir (entry->rt->default_fs_path,
        dir)) {
        return FALSE;
    }
```

### Expected results:

Symlinked files are served from `/usr/share/javascript`

### Actual results:

Symlinked files are not served from other directories.

### Additional information:

I can provide a patch for this but I need to know which solution is preferred:
- new `static_allow_symlinks` boolean option
- allow symlinks by default, not a security problem for a distribution installed rspamd as the directory holding static content is not writable by the user running rspamd
- new `static_allow_directories` list option to list authorized directories
- other?

Thanks for this software.

**Comment by vstakhov** [comment]
Hello, I think the second option is reasonable enough. Symlinks are disabled mostly because of some historical API, I see no harm in enabling them for Rspamd WebUI, as static dir is indeed unavailable for writing for Rspamd's user.
