### ISSUE TITLE
Percentage of email = image

### ISSUE THREAD

**Issue by robertboyl** [rspamd/rspamd#2738]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Ordinary bug
* [x ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

We really need a test that considers if most of the email contains embedded image (%) like spamassassin has.

heres an example of a false negative, the email has just an image.

And also bayes scored negatively, I guess its looking at the CSS...

See https://pastebin.com/WST0CH0Z

**Comment by vstakhov** [comment]
It is VML in fact. Nobody but crappy M$ clients would parse this shit.

**Comment by robertboyl** [comment]
example of a phishing email, 100% image. by luck, a DNSBL caught it. https://pastebin.com/CSmcHNgj

**Comment by vstakhov** [comment]
In the last sample, there is a rule called `HTML_SHORT_LINK_IMG_1` that actually is intended to catch this sort of behaviour. It's score is quite low as it could not get image's dimensions for an external image.

**Comment by robertboyl** [comment]
see how its important, this is a major scam, asking to pay with bitcon, account hacked, etc. it had very low score...

https://pastebin.com/9NsMkamd
