### ISSUE TITLE
Add extended reporting headers

### ISSUE THREAD

**Issue by wildstray** [rspamd/rspamd#274]
Spamassassin can add, in addition to a flag (X-Spam-Flag: [YES|NO]), some extended headers specifying what flags have been triggered and the scoring (X-Spam-Status), a verbose extended report (X-Spam-Report).

X-Spam-Status: Yes, score=5.2 required=5.0 tests=BAYES_50,DATE_IN_PAST_06_12,
    HTML_MESSAGE,UNPARSEABLE_RELAY,URIBL_DBL_ABUSE_REDIR,URIBL_WS_SURBL
    shortcircuit=no autolearn=no version=3.3.2
X-Spam-Report: 
    \*  0.0 URIBL_DBL_ABUSE_REDIR Contains an abused redirector URL listed in
    \*      the DBL blocklist
    \*      [URIs: bit.ly]
    \*  1.6 URIBL_WS_SURBL Contains an URL listed in the WS SURBL blocklist
    \*      [URIs: alphamethods.net]
    \*  1.5 DATE_IN_PAST_06_12 Date: is 6 to 12 hours before Received: date
    \*  0.0 HTML_MESSAGE BODY: HTML included in message
    \*  2.0 BAYES_50 BODY: Bayes spam probability is 40 to 60%
    \*      [score: 0.4584]
    \*  0.0 UNPARSEABLE_RELAY Informational: message has unparseable relay lines
X-Spam-Level: *****

As a drop in replacement it would be really useful to add this feature (for debugging purposes as well as mail tagging for fine grained filtering).
##

**Comment by fatalbanana** [comment]
How are you integrating with rspamd? In Exim this is available as $spam_report - not sure about rmilter but I'd guess it has a similar facility.

**Comment by wildstray** [comment]
Postfix as MTA, and rspamd+rmilter to replace spamassassin+spamass-milter. In this manner I gained 8~10 times in efficency... but loosing extended spam reporting (and per-user bayes storage) :(

**Comment by fatalbanana** [comment]
Try adding `extended_spam_headers = true` to rmilter's `spamd {}` config section.

**Comment by wildstray** [comment]
Thank you very much! There is no a self descriptive header such as X-Spam-Report, but X-Spamd-Result may fits my requirements :+1: 
I leave the issue open for a future (low priority) X-Spamd-Report, ok?

**Comment by fatalbanana** [comment]
Probably this issue would be better logged against rmilter. :) Please be explicit about which details you're not see'ing/would like to.

**Comment by fatalbanana** [comment]
... If you were hoping to see symbol descriptions I'm afraid the protocol doesn't provide this (in which case your issue would be in the right place). :)

**Comment by vstakhov** [comment]
Actually, you can see the full content of rspamd reply by specifying `--ucl` or `--json` to `rspamc` command.

**Comment by vstakhov** [comment]
Or take a look at https://rspamd.com/doc/architecture/protocol.html
