### ISSUE TITLE
Filter emails for rspamd's DMARC reports

### ISSUE THREAD

**Issue by analogic** [rspamd/rspamd#2745]
I've started using native DMARC reports, but there is one problem. 

Imagine you get everyday single email from multiple domains which end up with score 20+. They have proper NS records for everything DMARC included but it has no connectable mx. Then when rspamd generate reports outbound queue get filled with hunderds or tousands of email reports every day waiting to be delivered.

I don't want to destroy DMARC reports purpose for proper domains but there should be a way how to filter either reports itself or emails counted to reports.

**Comment by michelsup** [comment]
Sorry to reopen such an old issue but I think the problem got so worse recently that this issue should be resolved.
As more spammers use DMARC to try to circumvent antispam engines, we end up with hundreds of emails doing a loop.
- Spammer send an email rejected with a very high score
- Next day rspamd send a report. "Best" case is that the mail is queued for days, worst is that the mail is sent
- The next day the spammer send a report he has well received the report we sent him.
- The report is treated as spam and next day we still send a report we received a report.
- Rince and repeat indefinitely. 

This problem arise with all the reports. I send a report to a domain and the next day I receive another report. I guess in a few years most of the emails will be reports sent back and forth to thousands of domains nobody cares about anymore.

I guess a solution would be to check if it's a report we received, and discard it as "to be reported" to sender. And obviously remove any reports sent to spammy domains.

**Comment by vstakhov** [comment]
The whole dmarc reporting part should be rewritten completely :(

**Comment by PHPGangsta** [comment]
@michelsup You describe a loop of "DMARC Report mails"... If you send DMARC reports, you should send them from a subdomain, for which DMARC-Reporting is disabled. Then you break this loop very easily. You should also tell the other domain holder who sends back the reports that he should also send from a subdomain with disabled DMARC reporting. Only one has to do this to break the loop. And it's best if you both do this :-)

That's how you solve this problem. Don't try to "detect dmarc reports" or try to detect the loop in rspamd... The solution is: Don't request DMARC-Reports for the Reports you are sending, that's a lot better.

**Comment by michelsup** [comment]
@PHPGangsta This is a very good advice you gave me. Many thanks.
