### ISSUE TITLE
Please include Let's Encrypt CA import in documentation.

### ISSUE THREAD

**Issue by darkshram** [rspamd/rspamd#2747]
I had migrated several mail servers to rspamd with delightful success. But had some issues with CentOS 6/RHEL 6 servers that were **solved** by manually importing the Let's Encrypt CA cert. The ca-certificates package of those OS (_apparently_) does not include it, and rspamd servers use Let's Encrypt. So, issue #1855 surfaces. For CentOS/RHEL 6:

1. Install/update the ca-certificates package:
    yum -y install ca-certificates
2. Enable the dynamic CA configuration feature:
    update-ca-trust force-enable
3. Add Let's Encrypt CA cert as a new file to /etc/pki/ca-trust/source/anchors/:
    cp foo.crt /etc/pki/ca-trust/source/anchors/
4. update-ca-trust extract

For other OS:
[https://manuals.gfi.com/en/kerio/connect/content/server-configuration/ssl-certificates/adding-trusted-root-certificates-to-the-server-1605.html](
https://manuals.gfi.com/en/kerio/connect/content/server-configuration/ssl-certificates/adding-trusted-root-certificates-to-the-server-1605.html)

**Comment by vstakhov** [comment]
CentOS 6 is outdated, I do not recommend to use it with Rspamd. There are lots of known issues and new ones could appear in future. I don't have any plans to support CentOS 6 specific hacks any longer.
