### ISSUE TITLE
Radix map get_key problem

### ISSUE THREAD

**Issue by mguesdon** [rspamd/rspamd#2752]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [X] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.8.2

### Operation system, CPU:
CentOS 3.10.0-862.14.4.el7.x86_64

### Description (Please provide a descriptive summary of the issue):
I've written this:
local radix_tree = rspamd_config:add_map{
  type = 'radix', 
  url = 'file:///tmp/ips', 
  description = 'a sample ip map'
}
      logger.infox("get 1.2.3.4=%s",radix_tree:get_key('1.2.3.4'))
      logger.infox("get 2.3.4.5=%s",radix_tree:get_key('2.3.4.5'))
      logger.infox("get 2.3.4.5/32=%s",radix_tree:get_key('2.3.4.5/32'))

/tmp/ips contains:
1.2.3.4
2.3.4.0/24

It always return false. I probably miss something very simple but it's hours that I can not find where can be the problem 

### Relevant logs (see details [here](https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd)):

I've checked with strace: file is well readen and its seems to find the 2 radiw entries:
open("/tmp/ips", O_RDONLY|O_CLOEXEC)    = 4
lseek(4, 0, SEEK_SET)                   = 0
read(4, "1.2.3.4\n2.3.4.0/24\n", 19)    = 19
writev(3, [{"2019-02-12 18:57:17 #1510(main) ", 32}, {"<kut4id>; map; read_map_file_chu"..., 37}, {"/tmp/ips: read map chunk, 19 byt"..., 34}, {"\n", 1}], 4) = 104
read(4, "", 8)                          = 0
close(4)                                = 0
writev(3, [{"2019-02-12 18:57:17 #1510(main) ", 32}, {"<kut4id>; map; rspamd_radix_fin:"..., 33}, {"read radix trie of 2 elements: e"..., 77}, {"\n", 1}], 4) = 143

### Expected results:

get 1.2.3.4=true
get 2.3.4.5=true
get 2.3.4.5/32=false

### Actual results:

#1510(main) <kut4id>; map; rspamd_map_add: added map /tmp/ips
#1510(main) lua; a.lua:355: get 1.2.3.4=false
#1510(main) lua; a.lua:356: get 2.3.4.5=false
#1510(main) lua_map_get_key: invalid ip address: 2.3.4.5/32
  (=> this means at least it call radix search code)
#1510(main) lua; a.lua:357: get 2.3.4.5/32=false

**Comment by vstakhov** [comment]
Of course, you cannot read content of the maps just after their definition. Maps are loaded after Rspamd is started, so you can use them in rules only. Even `on_load` scripts might not be able to read maps data (but periodics should be able to do that if called late enough).
