### ISSUE TITLE
RBL module with emails option and hash not working as expected.

### ISSUE THREAD

**Issue by aalmenar** [rspamd/rspamd#2753]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):

Configuring an RBL for hash of emails dont work as expected:

Adding an RBL in rbl.conf like this:

RBL_HASHED {
   rbl = "ebl.msbl.org";
   from = false;
   emails = true;
   helo = false;
   exclude_users = false;
   exclude_private_ips = false;
   exclude_local = false;
   ignore_whitelists = true;
   hash = "sha1";

   returncodes = {
     RBL_HASHED = "127.0.0.2";
   }
 }

Does not do the lookup on the from address as is stated in the docs. It works for the helo if helo = true;, but for the email it does not.

### Expected results:

Do a query to ebl.msbl.org like {Hash sha-1 of from address}.ebl.msbl.org

### Actual results:

The lookup it's not made.

### Configuration (e.g. `rspamadm configdump module`):

 *** Section rbl ***
default_exclude_users = true;
default_received = false;
default_unknown = true;
default_from = true;
rbls {
    RBL_HASHED {
        ignore_whitelists = true;
        emails = true;
        helo = false;
        exclude_users = false;
        returncodes {
            RBL_HASHED = "127.0.0.2";
        }
        hash = "sha1";
        exclude_local = false;
        rbl = "ebl.msbl.org";
        exclude_private_ips = false;
        from = false;
    }
}

*** End of section rbl ***

**Comment by vstakhov** [comment]
Emails type does not include `from` email. It includes emails in the message's body and a email in `reply-to` header if it exists.

**Comment by aalmenar** [comment]
So, there is no way to use a hash RBL to check the from ?

**Comment by vstakhov** [comment]
No, there is no way except multimap+selectors. You need to define a custom selector for that.

**Comment by aalmenar** [comment]
Care to point me in the docs please ;) ?

**Comment by vstakhov** [comment]
https://rspamd.com/doc/configuration/selectors.html
