### ISSUE TITLE
Custom Subject rewrite

### ISSUE THREAD

**Issue by gotjoshua** [rspamd/rspamd#2755]
### Classification (Please choose *one* option):
* [x] WebUI/Usability

### Reproducibility (Please choose *one* option):
* [X] Always

### Rspamd version:
1.8.3

### Operation system, CPU:
using [hardware/mailserver docker container](https://github.com/hardware/mailserver/)
 - also [cross posted this issue](https://github.com/hardware/mailserver/issues/357) there as i am not sure where it _really_ belongs

### Description (Please provide a descriptive summary of the issue):

I am trying to follow the instructions at the bottom of the [Rspamd Metrics Docs](https://rspamd.com/doc/configuration/metrics.html).

And I added the following configuration to:
/var/mail/rspamd/rspamd_dynamic (via the rspamd web ui):

```[
    {
        "metric": "default",
        "subject": "[* SPAM>9 *] %s",
        "actions": [
            {
                "name": "rewrite subject",
                "value": 9.0,
                "subject": "[* SPAM>9 *] %s"
            },
```

The subject rewrite is happening, but not using the custom format.

Any advice?

### Expected results:
subject rewrite uses settings from  /var/mail/rspamd/rspamd_dynamic 
### Actual results:
rewrite functions, but does not use the custom format

**Comment by vstakhov** [comment]
This file, `rspamd_dynamic`, does not support custom subject settings. Use normal Rspamd configuration for that purposes.
