### ISSUE TITLE
Clickhouse module ignores settings.database

### ISSUE THREAD

**Issue by mgehlmann** [rspamd/rspamd#2759]
### Classification (Please choose *one* option):

* [X] Ordinary bug

### Reproducibility (Please choose *one* option):

* [X] Always

### Rspamd version:
1.8.3

### Description (Please provide a descriptive summary of the issue):
The clickhouse module ignores the database setting.

### Expected results:
The clickhouse module should use the database with the name that is defined in the local.d/clickhouse.conf by "database = ".
### Actual results:
The module always uses the "default" database instead. 

### Additional information:
The bug is caused by lua_clickhouse.lua, and can be fixed (tested) by replacing the lines:
**local database = params.database or 'default'**
with
**local database = settings.database or 'default'**
in 5 places.

**Comment by vstakhov** [comment]
Good catch, thanks!
