### ISSUE TITLE
rspamd can not find installed luajit

### ISSUE THREAD

**Issue by alexminder** [rspamd/rspamd#2760]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Unintended behaviour (bug)
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
mail-filter/rspamd-1.8.3

### Operation system (the exact version), CPU (including architecture and processor family):
Gentoo Base System release 2.6 x86_64 with musl libc

### Description (Please provide a descriptive summary of the issue):
rspamd failed to build with luajit support

### Compile errors (if any):  
```
CMake Error at CMakeLists.txt:1284 (MESSAGE):
  Cannot enable torch without luajit
```
### Expected results:
Success build rspamd with luajit installed.

### Actual results:
rspamd luajit test broken

### Configuration (e.g. `rspamadm configdump module`):
n/a

### Additional information:
LIBC: sys-libs/musl-1.1.21
LUAJIT: dev-lang/luajit-2.0.5-r1
```
# pkg-config --libs luajit
-lluajit-5.1
# pkg-config --modversion luajit
2.0.5

# qlist dev-lang/luajit
/usr/share/doc/luajit-2.0.5-r1/html/status.html
/usr/share/doc/luajit-2.0.5-r1/html/running.html
/usr/share/doc/luajit-2.0.5-r1/html/luajit.html
/usr/share/doc/luajit-2.0.5-r1/html/install.html
/usr/share/doc/luajit-2.0.5-r1/html/faq.html
/usr/share/doc/luajit-2.0.5-r1/html/extensions.html
/usr/share/doc/luajit-2.0.5-r1/html/ext_jit.html
/usr/share/doc/luajit-2.0.5-r1/html/ext_ffi_tutorial.html
/usr/share/doc/luajit-2.0.5-r1/html/ext_ffi_semantics.html
/usr/share/doc/luajit-2.0.5-r1/html/ext_ffi_api.html
/usr/share/doc/luajit-2.0.5-r1/html/ext_ffi.html
/usr/share/doc/luajit-2.0.5-r1/html/ext_c_api.html
/usr/share/doc/luajit-2.0.5-r1/html/contact.html
/usr/share/doc/luajit-2.0.5-r1/html/changes.html
/usr/share/doc/luajit-2.0.5-r1/html/bluequad.css
/usr/share/doc/luajit-2.0.5-r1/html/bluequad-print.css
/usr/share/doc/luajit-2.0.5-r1/html/img/contact.png
/usr/share/doc/luajit-2.0.5-r1/README.bz2
/usr/share/luajit-2.0.5/jit/vmdef.lua
/usr/share/luajit-2.0.5/jit/bcsave.lua
/usr/share/luajit-2.0.5/jit/dis_mipsel.lua
/usr/share/luajit-2.0.5/jit/dis_mips.lua
/usr/share/luajit-2.0.5/jit/dis_ppc.lua
/usr/share/luajit-2.0.5/jit/dis_arm.lua
/usr/share/luajit-2.0.5/jit/dis_x64.lua
/usr/share/luajit-2.0.5/jit/dis_x86.lua
/usr/share/luajit-2.0.5/jit/dump.lua
/usr/share/luajit-2.0.5/jit/v.lua
/usr/share/luajit-2.0.5/jit/bc.lua
/usr/share/man/man1/luajit.1.bz2
/usr/include/luajit-2.0/luajit.h
/usr/include/luajit-2.0/lua.hpp
/usr/include/luajit-2.0/luaconf.h
/usr/include/luajit-2.0/lauxlib.h
/usr/include/luajit-2.0/lualib.h
/usr/include/luajit-2.0/lua.h
/usr/lib/libluajit-5.1.so.2.0.5
/usr/lib/pkgconfig/luajit.pc
/usr/bin/luajit-2.0.5
/usr/bin/luajit
```

**Comment by vstakhov** [comment]
Unfortunately, your distro is not officially supported by Rspamd. I can clearly see many non-standard names there. It all could be resolved by adding specific CMake variables. However, I have neither time nor desire to support any possible Linux distro. So I would recommend to ask that question in the Gentoo community to find maybe better support there. I can accept patches to the upstream if needed.
