### ISSUE TITLE
support defining which languages are OK for incoming messages

### ISSUE THREAD

**Issue by mvdan** [rspamd/rspamd#2763]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Unintended behaviour (bug)
* [X] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

1.8.3

### Operation system (the exact version), CPU (including architecture and processor family):

```
$ uname -a
Linux shark 4.19.12-arch1-1-ARCH #1 SMP PREEMPT Fri Dec 21 13:56:54 UTC 2018 x86_64 GNU/Linux
$ cat /proc/cpuinfo | grep 'model name'
model name      : Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz
```

### Description (Please provide a descriptive summary of the issue):

I'd like to be able to tell Rspamd which languages I can read and understand, so that all other languages are more likely to get classified as spam. I was already doing this with SpamAssassin (https://spamassassin.apache.org/full/3.2.x/doc/Mail_SpamAssassin_Plugin_TextCat.html), and it's the only setting I haven't been able to port over to Rspamd.

In particular, I get a *ton* of Chinese spam. Sometimes in the thousands per day. I can't even read Chinese, and not ever in my life have I had a non-spam email in Chinese, so I'd like to add a big penalty to any email which is mostly (e.g. >50%) in that language. In fact, I can only read four languages, and I also get some spam in German and Korean, so it would be good to block all the other languages I don't read as well.

I realise I could train Rspamd with a large corpus of spam emails in Chinese, but that seems overly complex. Rspamd should be able to throw away emails in that language in a much simpler way.

### Expected results:

At most a few Chinese emails making their way into my Spam folder, just like when I used SpamAssassin.

### Actual results:

Between 20 and 30 Chinese emails in my Spam folder, some of them even making it to my Inbox.

### Additional information:

I found #1530, and I presume I could write a custom rule in Lua with `text_part:get_language()` (https://rspamd.com/doc/lua/rspamd_mimepart.html#mb8f0b). If it's decided that a built-in module or rule for this common use-case isn't wanted, I think we should add an entry to the FAQ with some example Lua code on how to penalize emails depending on the main detected language.

**Comment by vstakhov** [comment]
I have added `languages` selector, so for your case it is enough to add something like

```
lang_map {
  type = 'selector';
  selector = 'languages';
  map = ... # Path to file
  regexp = true; # If needed
}
```

**Comment by mvdan** [comment]
Thanks for the quick reply! I'm trying to go through the docs but it's not clear to me how I could use this to write a short custom rule, for example which would add a 2.0 score to any emails whose main language is neither english nor spanish.

Could we add such a short Lua snippet to the FAQ page? As far as I know the setting in SpamAssassin was quite common, so I'm sure it would be useful to others to be able to copy-paste an example.

**Comment by mvdan** [comment]
I also tried to hack together a custom rule in `rspamd.local.lua` before this fix, but I clearly failed as it's not doing anything at all :)

```
local ok_langs = {
        ['en'] = true,
        ['ca'] = true,
        ['es'] = true,
        ['fr'] = true,
}

rspamd_config.LANG_FILTER = {
        callback = function(task)
                local any_ok = false
                local parts = task:get_text_parts()
                for i, p in ipairs(parts) do
                        local ln = p:get_language()
                        local dash = s:find('-')
                        if dash > 1 then
                                -- from zh-cn to zh
                                ln = ln:sub(1, dash-1)
                        end
                        rspamd_logger.infox("lang for %1 is %2", i, ln)
                        if ok_langs[ln] then
                                any_ok = true
                        end
                end
                if any_ok then
                        return 0.1 // to debug
                end
                return 1.0
        end,
        score = 2.0,
        description = 'no ok languages',
}
```

**Comment by vstakhov** [comment]
Your rule looks valid if `rspamd_logger` is defined somewhere...

**Comment by mvdan** [comment]
Yes, I failed at copy-pasting :) I haven't debugged it further.

But in any case, if you added a patch to simplify this, I still think a short example in the FAQ would be great.

**Comment by vstakhov** [comment]
```lua
local rspamd_logger = require 'rspamd_logger'

local ok_langs = {
        ['en'] = true,
        ['ca'] = true,
        ['es'] = true,
        ['fr'] = true,
}

rspamd_config.LANG_FILTER = {
        callback = function(task)
                local any_ok = false
                local parts = task:get_text_parts()
                for i, p in ipairs(parts) do
                        local ln = p:get_language() or ''
                        local dash = ln:find('-')
                        if dash then
                                -- from zh-cn to zh
                                ln = ln:sub(1, dash-1)
                        end
                        rspamd_logger.infox("lang for %1 is %2", i, ln)
                        if ok_langs[ln] then
                                any_ok = true
                        end
                end
                if any_ok then
                        return 0.1
                end
                return 1.0
        end,
        score = 2.0,
        description = 'no ok languages',
}
```

**Comment by mvdan** [comment]
Ah, I had a bug in my Lua code, you're right! I was keeping an eye on the logs, but I couldn't see that there. Looking back, I still can't see any errors or messages about it, sadly.

Would you accept a patch to add a shorter version of this sample rule to the FAQ?

**Comment by vstakhov** [comment]
It means that your logging setup is incorrect most likely as I clearly could see what was wrong from the logs. I doubt this rule is worth FAQ placement I'm afraid. There should be some cookbook like document for rules like this one. I will think more about it.

**Comment by mvdan** [comment]
Yup, it was in the logs, I just missed as the error was buried among dozens of other `(normal)` lines.

Fair enough about the FAQ. I agree that there should be more documentation on writing custom rules, in particular a variety of simple examples. Your project is getting new users rapidly - congratulations! - but that also means that many will get stuck with the docs if they don't contain enough examples.
