### ISSUE TITLE
Seemingly no way to configure SUBJ_ALL_CAPS's weight

### ISSUE THREAD

**Issue by mvdan** [rspamd/rspamd#2764]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [X] Unintended behaviour (bug)
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

1.8.3

### Operation system (the exact version), CPU (including architecture and processor family):

```
$ uname -a
Linux shark 4.19.12-arch1-1-ARCH #1 SMP PREEMPT Fri Dec 21 13:56:54 UTC 2018 x86_64 GNU/Linux
$ cat /proc/cpuinfo | grep 'model name'
model name      : Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz
```

### Description (Please provide a descriptive summary of the issue):

I'd like to increase the weight of `SUBJ_ALL_CAPS`. I can't seem to find a way to do it, as the original Lua rule doesn't seem to use a symbol whose weight I can tweak.

This issue is quite similar to #548, which was closed, but I still see no way to increase the weight/scores of that builtin rule. I've tried hacks like `rspamd_config.SUBJ_ALL_CAPS.score = 5.0` in my `rspamd.local.lua`, but of course that doesn't work.

https://rspamd.com/doc/faq.html#how-to-change-score-for-some-symbol does cover this subject, but it seems to rely on symbols.

### Expected results:

Some way to tweak the strength of built-in rules.

### Actual results:

No apparent way, or at least none that I could get working.

**Comment by vstakhov** [comment]
I don't understand what is unclear in the faq... Yes, you cannot use your Lua snippet - it is just broken.

**Comment by mvdan** [comment]
The FAQ points me to adjust a symbol, but as best as I can tell, SUBJ_ALL_CAPS isn't a symbol I can tweak. Or perhaps it is, and I just can't see it? A `grep -r SUBJ_ALL_CAPS` in `/etc/rspamd/` gave zero matches.

**Comment by vstakhov** [comment]
It has default configuration obtained from Lua. However, you can define it's score as described in `groups.conf`.

**Comment by mvdan** [comment]
Thanks, that worked. I only got a bit confused as I thought the symbol needed to have been declared in `/etc/rspamd` explicitly.
