### ISSUE TITLE
Wrong results of task:get_urls based

### ISSUE THREAD

**Issue by jendis** [rspamd/rspamd#2767]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Unintended behaviour (bug)
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.8.3
### Description (Please provide a descriptive summary of the issue):

1. The set of urls in processed email returned by _task:get_urls()_ and _get_text()_ contains improperly classified url of http type.
Example:
If an email contains a text like _ ... something.cz ..._, the returned value is _http://xxx.something.cz_.
1. When an attempt of restricting the _task:get_urls()_ results by passing the parameter e.g. _{'http','https'}_ is done, the returned url type set is not restricted at all and contains e.g. _ftp_ or _mailto_ type if present in an email.
### Expected results:
1. Url-like text having domain format but not containing the prefix:
- _http://_
- _https://_ 
won't be classified as a _http_ url type. Only the url-like text starting with one of those prefix will be classified as a _http_.
2. Url types returned by _task:get_urls()_ are restricted according to the parameter specifying the types if this parameter passed.

### Actual results:
See description.

**Comment by vstakhov** [comment]
I cannot reproduce (2). When I get urls as `task:get_urls({'http','https'})` it correctly ignores mailto and ftp links. I've tested it against the master branch as this feature is absent in 1.8.3.

The first thing is an intended behaviour as that's how email clients usually work - they can find urls that are not prefixed with protocol in plain text parts (like `example.com`).

**Comment by jendis** [comment]
(1) is tricky and causes a false positive e.g. in case of bounces, where domain names of MTAs are a part of email body.

I can confirm that problem described in (2) is solved in master now.
Unfortunately these new changes cause that all urls are ignored in case of a plaintext email.

**Comment by vstakhov** [comment]
What do you mean by "urls are ignored in case of a plaintext email"?

**Comment by jendis** [comment]
I'm sorry for not being specific enough. I mean url in text/plain MIME content type, see example:

> MIME-Version: 1.0
> Content-Type: text/plain; charset=utf-8
> Content-Transfer-Encoding: 7bit
> Content-Language: en-US
> 
> my.example.com
