### ISSUE TITLE
Question/poroposition: Analyse/combine symbols

### ISSUE THREAD

**Issue by aTanW** [rspamd/rspamd#2768]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Unintended behaviour (bug)
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [x] Not applicable

### Rspamd version:
1.8.3

### Operation system (the exact version), CPU (including architecture and processor family):
4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Description (Please provide a descriptive summary of the issue):
I propose to add symbols check ability for synthesize new symbol(s) or change weights (scores) of existing ones.

Example:
I got lot of spam, that gets score near my low mark level. Detection adds, among others, following symbols: HAS_REPLYTO(0.00) FORGED_SENDER(0.30) FROM_NEQ_ENVFROM(0.00) GREYLIST(0.00) MX_INVALID(0.50) RCVD_COUNT_ZERO(0.00)

As for me, it will be one more level of "smartness" :) for rspamd to check all that present, and add someting like SYNT_FORGER(3.0). Or somehow raise weight(s) of already present symbols.

Like:

    analyze = {
      SYNT_FORGER = {
        symbol = "SYNT_FORGER";
        score = 3.0;
    # or 
    #   weight = 2.0;
        and {
          exist = [ "HAS_REPLYTO", "FORGED_SENDER", "FROM_NEQ_ENVFROM", "MX_INVALID", "RCVD_COUNT_ZERO" ];
          compare = [ "IP_SCORE >= 1.0", "BAYES_SPAM > 3.0", "NEURAL_SPAM_SHORT > 0.5" ];
        }
      }
    }

**Comment by vstakhov** [comment]
```
local.d/composites.conf 
SYNT_FORGER {
  expression = "IP_SCORE >= 1.0 & HAS_REPLYTO & FORGED_SENDER & FROM_NEQ_ENVFROM & BAYES_SPAM > 3.0";
  policy = "leave";
  score = 3.0;
}
```

**Comment by aTanW** [comment]
I'm very sorry! :-) I don't read docus up to end. Thank you!
