### ISSUE TITLE
Enabling rspamd_update fails configtest check

### ISSUE THREAD

**Issue by fd0** [rspamd/rspamd#2769]
First: Thank you very much for your work on rspamd!

### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Unintended behaviour (bug)
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

Rspamd daemon version 1.8.3

### Operation system (the exact version), CPU (including architecture and processor family):

Debian stable (9.8), Intel i7-6700 (amd64)

### Description (Please provide a descriptive summary of the issue):

Enabling the `rspamd_update` module makes `rspamadm configtest` print an error, which is also printed in the global log. The module is still enabled, though.

The `rspamd_update` module is disabled by default in `/etc/rspamd/modules.d/rspamd_update.conf`:

```
[...]
rspamd_update {
  [...]
  enabled = false; # Disable this module by default

  .include(try=true,priority=5) "${DBDIR}/dynamic/rspamd_update.conf"
  .include(try=true,priority=1,duplicate=merge) "$LOCAL_CONFDIR/local.d/rspamd_update.conf"
  .include(try=true,priority=10) "$LOCAL_CONFDIR/override.d/rspamd_update.conf"
}
```

The `configtest` command is happy with the configuration:

```
# rspamadm configtest 
syntax OK
```

Enabling it in `/etc/rspamd/local.d/rspamd_update.conf` works:

```
enabled = true;
```

### Compile errors (if any):

None, I used the provided package for Debian.

### Relevant logs (see details [here](https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd)):

```
# rspamadm configtest 
map has invalid type for value: boolean
cannot load updates from true
syntax OK
```

```
2019-02-26 12:56:50 #3644(main) <z5gidb>; lua; rspamd_update.lua:135: cannot load updates from true
2019-02-26 12:56:50 #3644(main) <z5gidb>; cfg; rspamd_init_lua_filters: init lua module rspamd_update
```

### Expected results:

No errors in the log, and no errors printed by `rspamadm configtest`.

### Actual results:

```
# rspamadm configtest 
map has invalid type for value: boolean
cannot load updates from true
syntax OK
```

The log file also contains this error when `rspamd` is restarted, but the module is enabled:

```
2019-02-26 12:56:50 #3644(main) <z5gidb>; lua; rspamd_update.lua:135: cannot load updates from true
2019-02-26 12:56:50 #3644(main) <z5gidb>; cfg; rspamd_init_lua_filters: init lua module rspamd_update
```

### Configuration (e.g. `rspamadm configdump module`):

```
# rspamadm configdump rspamd_update
map has invalid type for value: boolean
cannot load updates from true
*** Section rspamd_update ***
enabled = true;
key = "qxuogdh5eghytji1utkkte1dn3n81c3y5twe61uzoddzwqzuxxyb";
rules = "sign+https://updates.rspamd.com/rspamd-1.8.ucl";

*** End of section rspamd_update ***
```

**Comment by vstakhov** [comment]
I would not recommend to use this module anyway.

**Comment by fd0** [comment]
Thanks for the fix! I thought it would be a nice idea to have the rules update automatically, why do you recommend not using the module?
