### ISSUE TITLE
Strange behavior when resolving 'localhost' for socket binding

### ISSUE THREAD

**Issue by pridetechdesignllc** [rspamd/rspamd#2773]
### Classification (Please choose *one* option):

* [X] Unintended behaviour (bug)

### Reproducibility (Please choose *one* option):

* [X] Rarely

### Rspamd version:
1.8.1 and 1.8.3

### Operation system (the exact version), CPU (including architecture and processor family):
Debian 9.7

### Description (Please provide a descriptive summary of the issue):
Using the quick start guide from rspamd.com: https://rspamd.com/doc/quickstart.html -> https://thomas-leister.de/en/mailserver-debian-stretch/,
Replicating the deployment using Ansible, I've run into a rare problem that has affected only a couple of servers out of around a dozen.

The rspamd debug log indicates that it is trying to bind sockets on foreign IPs in the 74.0.0.0 IP range. The IPs seem to be the same each time, but different for each problem server. The IPs are owned by Google.

Changing the bind_socket addresses in the configuration from 'localhost' to '127.0.0.1' fixes the issue, but doesn't resolve the problem which is, why is rspamd resolving the incorrect IP for localhost? All other DNS resolution for localhost on these systems works properly (resolves to 127.0.0.1). /etc/hosts is configured properly. The strange foreign IPs do not occur anywhere else on the server.

I know this is possibly not a bug, but It does seem to be something unique to how rspamd is resolving localhost, and I'm hoping that if nothing else, someone could shed some light on the source of the issue.

**Comment by vstakhov** [comment]
Not Rspamd issue.

**Comment by pridetechdesignllc** [comment]
This only effects rspamd so how is it not an rspamd issue?
