### ISSUE TITLE
Confusing bayes info message

### ISSUE THREAD

**Issue by jendis** [rspamd/rspamd#2774]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Unintended behaviour (bug)
* [X] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.8.3
### Description (Please provide a descriptive summary of the issue):
The log message:
> 2019-03-01 10:59:41 #102873(controller) <7d3097>; bayes; bayes_classify: no tokens found in bayes database (61 total tokens, 25 text tokens), ignore stats

is confusing. Firstly it can lead to conclusion that really **no tokens** are found in DB but after reading the numbers in brackets the user is confused totally because it is not evident what is the meaning of this numbers. 
### Expected results:
Suggestion is:

> ...no tokens extracted from an email (61 total tokens, 25 text tokens) found in bayes database, ignore stats

**Comment by vstakhov** [comment]
I'm sorry but I'm not inclined to change this message as such a change might be confusing for people who knows what does it mean. I'd prefer not to make incompatibilities without a good reason.

**Comment by JoeKun** [comment]
I couldn't agree more with @jendis here. I'm trying to test some configuration changes on my instance of `rspamd`, and this super confusing log message threw me off for a while, and caused me to waste several hours.

In my humble opinion, log messages are not only meant for the original developer of the software to understand; it's equally important to make sure the meaning of log messages is also clear and not misleading to administrators deploying the software.

@vstakhov If you were willing to change your mind about this, I would be more than happy to create a pull request with this small change.
