### ISSUE TITLE
rspamd_proxy process terminated hardly

### ISSUE THREAD

**Issue by satanTime** [rspamd/rspamd#2777]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Unintended behaviour (bug)
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [x] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
Rspamd daemon version 1.8.3

### Operation system (the exact version), CPU (including architecture and processor family):
Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux, 1CPU Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz

### Description (Please provide a descriptive summary of the issue):
Can't find way to set stop grace period to kill child processes.
Currently once I got some email and manually learned it as HAM in UI I try to stop rspamd.
As result some of processes are terminated correctly (soft exit), but rspam_proxy is terminated hardly.
```
Mar  3 11:54:45 office rspamd[139]: <3c1bd7>; main; wait_for_workers: terminate worker rspamd_proxy(157) with SIGKILL
Mar  3 11:54:45 office rspamd[139]: <3c1bd7>; main; wait_for_workers: rspamd_proxy process 157 terminated hardly
Mar  3 11:54:45 office rspamd[139]: <3c1bd7>; main; main: terminating...
```
I don't see any other errors and was thinking to extend timeout, but wasn't able to find how to do that. Could you help with that?

### Compile errors (if any):
nothing

### Relevant logs (see details [here](https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd)):
Mar  3 11:54:45 office rspamd[139]: <3c1bd7>; main; wait_for_workers: terminate worker rspamd_proxy(157) with SIGKILL
Mar  3 11:54:45 office rspamd[139]: <3c1bd7>; main; wait_for_workers: rspamd_proxy process 157 terminated hardly
Mar  3 11:54:45 office rspamd[139]: <3c1bd7>; main; main: terminating...

### Expected results:
rspamd_proxy is terminated softly.

### Actual results:
rspamd_proxy is terminated hardly.

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
nothing

### Configuration (e.g. `rspamadm configdump module`):
configdump worker-proxy
Section worker-proxy NOT FOUND

### Additional information:
nothing special

**Comment by vstakhov** [comment]
Don't terminate processes when doing something long. This grace time will not likely be changed/configurable as I don't see any sane usage of that.

**Comment by satanTime** [comment]
It's terminated by main process of rspamd, I sent TERM signal to main process and was waiting for graceful termination, but got in logs messages about attempts to terminate rspamd_proxy and then this kill signal.
I'll try to create stable steps to reproduce it.

**Comment by vstakhov** [comment]
The question is what that workers are doing at that point?

**Comment by satanTime** [comment]
Yeah, good question, I'll investigate and drop message here with results.
