### ISSUE TITLE
When new release is planned?

### ISSUE THREAD

**Issue by rpv-tomsk** [rspamd/rspamd#2780]
Hi,

Three months have passed since the last release.
Maybe it's a time to make a new one?

Thanks for your Product and service!

**Comment by rpv-tomsk** [comment]
?

**Comment by vstakhov** [comment]
Please use GitHub issue tracker for issues only not for general questions. Non-issues questions will likely be closed without any feedback as I can hardly manage backlog of ~300 entries to allow general questions to be here.
