### ISSUE TITLE
[Question] IP Score tunning

### ISSUE THREAD

**Issue by LeDistordu** [rspamd/rspamd#2781]
Hi, For a year now I have received 3000 spam /month from a Chinese source.

IP_SCORE (1.80) [ipnet: 122.4.0.0/14(4.95), asn: 4134 (3.96), country: CN (0.10)];
IP_SCORE(1.80)[ipnet: 171.8.0.0/15(4.94), asn: 4134(3.96), country: CN(0.10)];
IP_SCORE(1.80)[ipnet: 122.224.0.0/12(4.95), asn: 4134(3.96), country: CN(0.10)];
IP_SCORE(1.80)[ipnet: 222.184.0.0/13(4.96), asn: 4134(3.96), country: CN(0.10)];

I would like to improve the results of IP_SCORE, what are the levers for IP Score to be harder ? Just global IP_Score weight ? (2 to 4 for exemple ?)

**Comment by vstakhov** [comment]
Yes, just change it's static score or use country based multimap rule. Please also refrain from using the issue tracker for general questions, use mailing lists instead.
