### ISSUE TITLE
CentOS 7 - experimental RPM 1.9.0-47.git00af0f521- requirement libjemalloc.so.2 failed

### ISSUE THREAD

**Issue by fm81** [rspamd/rspamd#2783]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [X] Unintended behaviour (bug)
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version: 
rspamd-1.9.0-47.git00af0f521 (from https://rspamd.com/rpm/centos-7/x86_64/rspamd-1.9.0-47.git00af0f521.x86_64.rpm)

### Operation system (the exact version), CPU (including architecture and processor family):
CentOS Linux release 7.6.1810 (Core) 

### Description (Please provide a descriptive summary of the issue):
Installation not possible, requirement libjemalloc.so.2 failed

### Relevant logs (see details [here](https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd)):
yum install https://rspamd.com/rpm/centos-7/x86_64/rspamd-1.9.0-47.git00af0f521.x86_64.rpm
Loaded plugins: fastestmirror
rspamd-1.9.0-47.git00af0f521.x86_64.rpm                                                                                                                                | 6.2 MB  00:00:00     
Examining /var/tmp/yum-root-olBW1D/rspamd-1.9.0-47.git00af0f521.x86_64.rpm: rspamd-1.9.0-47.git00af0f521.x86_64
Marking /var/tmp/yum-root-olBW1D/rspamd-1.9.0-47.git00af0f521.x86_64.rpm as an update to rspamd-1.8.4-34.git462ab60be.x86_64
Resolving Dependencies
--> Running transaction check
---> Package rspamd.x86_64 0:1.8.4-34.git462ab60be will be updated
---> Package rspamd.x86_64 0:1.9.0-47.git00af0f521 will be an update
--> Processing Dependency: libjemalloc.so.2()(64bit) for package: rspamd-1.9.0-47.git00af0f521.x86_64
Loading mirror speeds from cached hostfile
 * base: mirror.alpha-labs.net
 * epel: mirror.netsite.dk
 * extras: mirror.alpha-labs.net
 * updates: ftp.hosteurope.de
--> Finished Dependency Resolution
--> Finding unneeded leftover dependencies
Found and removing 0 unneeded dependencies
Error: Package: rspamd-1.9.0-47.git00af0f521.x86_64 (/rspamd-1.9.0-47.git00af0f521.x86_64)
           Requires: libjemalloc.so.2()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

### Expected results:
RPM will be updated without errors
### Actual results:
RPM will not be installed because unmet requirements

### Additional information:
Last working experimental RPM is rspamd-1.8.4-34.git462ab60be

yum provides "*libjemalloc.so.2*"
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.alpha-labs.net
 * epel: mirror.netsite.dk
 * extras: mirror.alpha-labs.net
 * updates: ftp.hosteurope.de
No matches found

**Comment by vstakhov** [comment]
Fixed now.
