### ISSUE TITLE
Question: Integrate with Thunderbird client (as mail database)

### ISSUE THREAD

**Issue by lixaotec** [rspamd/rspamd#2786]
Dear fellows,

Is there anyway to use my Thunderbird client as the 'mail database', with some feature, to integrate with a rspamd instance? So that I can have a mail spam check whenever a new message arrives and perhaps applying to my big mail database?

Or else would be possible to tell rspamd to poll an IMAP server to apply spam filtering directly?

Thanks

**Comment by tjharman** [comment]
It should be possible to write an addon for Thunderbird that talks to rspamd.

I don't think anyone's done it though.

**Comment by lixaotec** [comment]
Dear @tjharman , would you or someone give me starting points?

I´m just new to rspamd. How would that be accomplished?

Can you give me the steps or where to search.

Thanks.

**Comment by lixaotec** [comment]
I mean, all related to Thunderbird I´ll look anywhere else, i´m just wondering how could I interact with rspamd,

By rest api? or by telling rspamd to pool an imap server (imap is my preference). Just dont know where to start..

thanks again
