### ISSUE TITLE
Ubuntu 14.04.6 LTS not updated to version 1.9.x

### ISSUE THREAD

**Issue by achch** [rspamd/rspamd#2792]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Unintended behaviour (bug)
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Operation system (the exact version), CPU (including architecture and processor family):
Ubuntu 14.04.6 LTS
### Description (Please provide a descriptive summary of the issue):
All current updates are installed on the OS.

root@post-kes:~# apt-get --no-install-recommends install rspamd
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 rspamd : Depends: libstdc++6 (>= 4.9) but 4.8.4-2ubuntu1~14.04.4 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by vstakhov** [comment]
I'm going to drop trusty support soon. It's EOL is on April which comes in the next three weeks hopefully. Since I compile Rspamd on trusty using a newer compiler than it is provided by the system there are some broken deps unfortunately. Please upgrade your system to a more recent one.
