### ISSUE TITLE
"rspamadm control reload" does not reload the dkim key for signing outgoing mails

### ISSUE THREAD

**Issue by TheTesla** [rspamd/rspamd#2804]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Unintended behaviour (bug)
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.8.3

### Operation system (the exact version), CPU (including architecture and processor family):
Debian GNU/Linux 9.6 (stretch), Kernel 4.9.0-8-amd64

### Description (Please provide a descriptive summary of the issue):
_rspamadm control reload_ does not reload the dkim key for signing outgoing mails

### Expected results:
_rspamadm control reload_ does load new config and dkim key for signing outgoing mails

### Actual results:
old config and keys are used

**Comment by vstakhov** [comment]
This command is not intended to reload dkim keys. It was historically intended to reload fuzzy storage. So far, it does nothing. DKIM keys should be reloaded automatically on change (when their `mtime` changes). Furthermore, 1.8.3 is outdated now and no longer supported.
