### ISSUE TITLE
Elasticsearch does not work after update to 1.9.0

### ISSUE THREAD

**Issue by jensoliver** [rspamd/rspamd#2808]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Unintended behaviour (bug)
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.9.0-3

### Operation system (the exact version), CPU (including architecture and processor family):
Ubuntu 16.04.6 LTS

### Description (Please provide a descriptive summary of the issue):
rspamd is not able to send data to elasticsearch

Index was newly created (automated)

### Relevant logs (see details [here](https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd)):
_Mar 19 16:31:59 mtacluster-vm2 rspamd[4454]: <ecneyo>; cfg; rspamd_init_lua_filters: init lua module elastic
Mar 19 16:33:39 mtacluster-vm2 rspamd[4486]: <773faf>; lua; elastic.lua:221: cannot send 14 rows to ES 4 times, stop trying_

### Expected results:
Data send to elastic

### Actual results:
No data was sent

### Configuration (e.g. `rspamadm configdump module`):
*** Section elastic ***
server = "192.168.100.1:9200";
limit = 10;
import_kibana = false;
debug = false;
timeout = 5;
index_pattern = "rspamd-%Y.%m.%d";

*** End of section elastic ***

**Comment by vstakhov** [comment]
Please enable debug for this module in `debug_modules` in `logging` section.

**Comment by jensoliver** [comment]
Mar 19 19:41:46 mtacluster-vm1 rspamd[24052]: <ezpy9s>; cfg; rspamd_init_lua_filters: init lua module elastic
Mar 19 19:41:47 mtacluster-vm1 rspamd[24083]: <>; elastic; elastic.lua:255: ingest-geoip plugin has been found
Mar 19 19:41:47 mtacluster-vm1 rspamd[24082]: <>; elastic; elastic.lua:255: ingest-geoip plugin has been found
Mar 19 19:41:47 mtacluster-vm1 rspamd[24081]: <>; elastic; elastic.lua:255: ingest-geoip plugin has been found
Mar 19 19:41:47 mtacluster-vm1 rspamd[24084]: <>; elastic; elastic.lua:255: ingest-geoip plugin has been found
Mar 19 19:41:47 mtacluster-vm1 rspamd[24082]: <>; elastic; elastic.lua:321: pushed kibana template: {"took":14,"errors":false,"items":[{"index":{"_index":".kibana","_type":"doc","_id":"index-pattern:eb48a1c0-23a2-11e8-b222-e710267d9b66","_version":2,"result":"updated","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":370,"_primary_term":22,"status":200}},{"index":{"_index":".kibana","_type":"doc","_id":"dashboard:6c6a2ed0-8660-11e7-85ae-fbc80f1b7844","_version":6,"result":"updated","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":371,"_primary_term":22,"status":200}},{"index":{"_index":".kibana","_type":"doc","_id":"visualization:927debf0-8649-11e7-967f-798bfd7ac13a","_version":3,"result":"updated","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":372,"_primary_term":22,"status":200}},{"index":{"_index":".kibana","_type":"doc","_id":"visualization:6413f870-80f6-11e7-91e6-0986b0b459e7","_version":4,"result":"updated","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":373,"_primary_term":22,"status":200}},{"index":{"_index":".kibana","_type":"doc","_id":"visualization:92a92c00-80f6-11e7-91e6-0986b0b459e7","_version":3,"result":"updated","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":374,"_primary_term":22,"status":200}},{"index":{"_index":".kibana","_type":"doc","_id":"visualization:2be7b6f0-8649-11e7-967f-798bfd7ac13a","_version":3,"result":"updated","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":375,"_primary_term":22,"status":200}},{"index":{"_index":".kibana","_type":"doc","_id":"visualization:1f7d9210-80f7-11e7-91e6-0986b0b459e7","_version":3,"result":"updated","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":376,"_primary_term":22,"status":200}},{"index":{"_index":".kibana","_type":"doc","_id":"visualization:efa3f7a0-80f6-11e7-91e6-0986b0b459e7","_version":3,"result":"updated","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":377,"_primary_term":22,"status":200}}]}
Mar 19 19:47:38 mtacluster-vm1 rspamd[24084]: <6639ac>; elastic; elastic.lua:212: send elastic search rows: 14
Mar 19 19:47:38 mtacluster-vm1 rspamd[24084]: <6639ac>; lua; elastic.lua:221: cannot send 14 rows to ES 4 times, stop trying
