### ISSUE TITLE
atomic config and dkim key reload

### ISSUE THREAD

**Issue by TheTesla** [rspamd/rspamd#2809]
As learned in issue #2804 the dkim key is reloaded automatically when it is changed. This may result in unwanted behavior. During key rollover the new key may be send with old selector.

I don't know what the graceful config reload instruction is. My issue #2716 bescribes systemctl reload rspamd does not realy work. Like issue #2804 rspamadm control reload does also not reload the config. Is there a way for uninterrupted config reload?

If so we need a best practice for key rollover. The dkim key must not be reloaded by changing the dkim key file. The only way for the user is to specify the selector as part of the dkim key filename. During config reload the new filename is used.

My recommendation is to have a consistent behavior for all reloads. rspamadm control reload should reload the config and dkim key as one atomic operation. systemctl reload rspamd should call rspamadm control reload. 

If someone wants to have immediate key reload, so we should add a config option: LoadKeyOnChange = True

**Comment by c-rosenberg** [comment]
For a successful rollover you have to take DNS TTL into account. So you cannot really just change the key in this scenario but always have to add a new key with another selector. Therefore you can manually define multiple DKIM keys in the config and let Rspamd validate the DNS pub key or even double sign for a while.

**Comment by TheTesla** [comment]
Yes, that is the way I do it: I publish the new key in DNS. One day later I sign with the new key with the new selector. The receiver can validate old and new mails, because I have both DNS entries. The correct selector is written in the dkim signature. Double signing is not needed.

Having multiple keys in the config is not needed. For validation no key file is needed, the public key is in the DNS zone. For signing there is always exactly one key need. That key can be changed together with the selector, but the old key must remain some time in the DNS to give the receiving mailserver time to validate email newly received.

**Comment by vstakhov** [comment]
I don't understand your issue at all.

> This may result in unwanted behavior. During key rollover the new key may be send with old selector.

No! Name your key in format `newselector.domain.key`, change selector in the config, reload config. All new workers will sign using new private key, all remaining workers will use an old private key `oldselector.domain.key` which is absolutely ok. I don't see any races here and if you have some races then fix your architecture as described above. 

Closing this issue: not related to Rspamd.
