### ISSUE TITLE
Transparent compression support for learn_ham/learn_spam

### ISSUE THREAD

**Issue by msaladna** [rspamd/rspamd#2814]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Unintended behaviour (bug)
* [X] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.9.0
### Operation system (the exact version), CPU (including architecture and processor family):
CentOS 7.5

### Description (Please provide a descriptive summary of the issue):
Dovecot supports [transparent compression](https://wiki.dovecot.org/Plugins/Zlib) via LMTP in a variety of formats. These messages must first be decompressed prior to learning via rspamc client. Adding rspamc support to infer and decompress these messages on-the-fly would improve compatibility and take guesswork out of teaching mail in bulk from command-line.

### Compile errors (if any):
n/a

### Relevant logs (see details [here](https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd)):

For example, sample message:
```
# zcat test.gz
To: msaladna@apisnetworks.com
From: Matt Saladna <matt@apisnetworks.com>
Subject: Tessst
Message-ID: <eed96d35-1650-db9a-d432-64a6be8a8121@apisnetworks.com>
Date: Fri, 22 Mar 2019 14:03:27 -0500
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101
 Thunderbird/60.6.0
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="------------7D7782938851ACA5D286BE2C"
Content-Language: en-US

This is a multi-part message in MIME format.
--------------7D7782938851ACA5D286BE2C
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 7bit

test


--------------7D7782938851ACA5D286BE2C
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

<html>
  <head>

    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  </head>
  <body text="#000000" bgcolor="#FFFFFF">
    <p><font face="Verdana">test</font><br>
    </p>
  </body>
</html>

--------------7D7782938851ACA5D286BE2C--
```

### Expected results:
After accessing mail in Dovecot, seen flag added:

```
# zcat test.gz\:2\,S | rspamc learn_ham
Results for file: stdin (0.003 seconds)
error = "<eed96d35-1650-db9a-d432-64a6be8a8121@apisnetworks.com> has been already learned as ham, ignore it";
filename = "stdin";
scan_time = 0.003000;
```
### Actual results:
```
# rspamc learn_ham < test.gz\:2\,S 
Results for file: stdin (0.003 seconds)
error = "<undef> contains less tokens than required for bayes classifier: 1 < 11";
filename = "stdin";
scan_time = 0.003000;
```

### Additional information:
Using an imapsieve to feed rspamc works fine. Compression [detection routines](https://github.com/dovecot/core/blob/81b5b188c478ec36bea8bda8fcad1e5f32ac612b/src/lib-compression/compression.c#L29:L80) in Dovecot.

**Comment by vstakhov** [comment]
No it doesn't make any sense to me: adding such a function to a C program is hard. Since you already use `rspamc` in some script please consider a more sane alternatives. I won't like to make a swiss army knife from a simple client utility - it already has too many options from my opinion.
