### ISSUE TITLE
js error in pie update

### ISSUE THREAD

**Issue by fabianfrz** [rspamd/rspamd#2819]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Unintended behaviour (bug)
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

1.8.1

### Operation system (the exact version), CPU (including architecture and processor family):

Arch Linux x86-64 (virtual)

### Description (Please provide a descriptive summary of the issue):

JS has a problem because some data is missing

### Expected results:

no error

### Actual results:

![Screenshot_20190325_213759](https://user-images.githubusercontent.com/3713914/54952884-4dea8c00-4f47-11e9-9f0a-ee799a2b6c8d.png)

**Comment by vstakhov** [comment]
I don't think that version 1.8.1 is supported so far.

**Comment by fabianfrz** [comment]
give me some minutes - I am building the current one now - thanks for the hint.

**Comment by fabianfrz** [comment]
looks good on 1.9.0 - sorry for the delay, had some problems with AUR.
