### ISSUE TITLE
DMARC reports: .gz base64 attachment line length

### ISSUE THREAD

**Issue by PHPGangsta** [rspamd/rspamd#2820]
### Classification (Please choose *one* option):

* [x] Unintended behaviour (bug)

### Reproducibility (Please choose *one* option):

* [X] Always

### Rspamd version:
1.8.3

### Operation system (the exact version), CPU (including architecture and processor family):
Ubuntu 18.04

### Description (Please provide a descriptive summary of the issue):

DMARC reports have a base64 .zg attachment mime part. Each line of that part is 80 Bytes long. Spamassassin, when receiving such a report, marks it as Spam. 2 high scoring tests:

BASE64_LENGTH_78_79=2.667
BASE64_LENGTH_79_INF=1.502

If I count correctly, 78 visible characters + CRLF = 80 bytes.
Only 78 Bytes are allowed: 76 + CRLF.

"As such, MIME enforces a limit on line length of base 64-encoded data to 76 characters."
RFC2822 + RFC4648

I see other clients inserting line breaks after 73 characters, + \r\n gives 75 bytes, well below the limit.

**Comment by vstakhov** [comment]
The fix will be trivial but it seems that adding such a score is a mistake from SA side: I've never ever seen spam with that violation but I've seen many ham messages that violate this limit.

**Comment by vstakhov** [comment]
Also the whole DMARC reporting code is a subject for complete refactoring/rewrite as currently it is very ugly...

**Comment by PHPGangsta** [comment]
Thanks for quickly fixing it!

I don't judge SA for making RFC-Checks. rspamd also checks for strange things, like "MV_CASE" for example. I have rarely seen a Spam-Mail caught by this, but lots of ham hit by this 😄 

Thanks again.

**Comment by vstakhov** [comment]
MV_CASE score is 0.5 and not 4 in total...
