### ISSUE TITLE
Greylisting instead of rejection since 1.9

### ISSUE THREAD

**Issue by membero** [rspamd/rspamd#2821]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [X] Unintended behaviour (bug)
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:

1.9.0

### Operation system (the exact version), CPU (including architecture and processor family):

Debian 10

### Description (Please provide a descriptive summary of the issue):

After an upgrade from 1.8.3 to 1.9.0 messages will be greylisted even if they have a score higher than in action reject defined. This only happens when action reject is equal or less as action rewrite_subject or action add_header.

/etc/rspamd/local.d/actions.conf:
```
reject = 8;
add_header = 8;
rewrite_subject = 8;
greylist = 2;
```

If add_header and rewrite_subject are smaller than reject, everything is fine.

If I set add_header and rewrite_subject to null (https://rspamd.com/doc/faq.html#how-can-i-disable-some-rspamd-action), the problem is also solved.

I use a plugin which loads settings from redis. My goal is to allow users to reject emails without rewriting subject. So only emails which are lower than reject action will be delivered to the mailboxes. When I disable the module and set actions.conf like shown above, the results are the same.

With 1.8.3 task:set_settings with the following data was ok:

```
{[actions] = {[rewrite_subject] = 8, [greylist] = 2, [add_header] = 8, [reject] = 8}}
```

But with 1.9.0 it is not. I tried to set

```
{[actions] = {[rewrite_subject] = , [greylist] = 2, [add_header] = , [reject] = 8}}
```

But this also resulted in soft  rejects from Greylisting Module.

When reject action is greater than add_header/rewrite_subject I do not have a problem:

```
{[actions] = {[rewrite_subject] = 8, [greylist] = 2, [add_header] = 8, [reject] = 25}}
```

Perhaps my way to "disable" rewrite_subject/add_header action is not the best one. If so, I will be happy to get some input how to the recommended way is.

### Relevant logs (see details [here](https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd)):

```
Mar 27 15:37:20 mx01a rspamd[17205]: <a41a7e>; task; accept_socket: accepted connection from 127.0.0.1 port 35454, task ptr: 0000560D3DB95830
Mar 27 15:37:20 mx01a rspamd[17205]: <a41a7e>; task; rspamd_message_parse: loaded message; id: <fjghecfvowoftfhbjiplcbfbeyvsy@yy.duykhanhproduct.icu>; queue-id: <6E52240389>; size: 3388; checksum: <f2df1181e1e26db6c752dc41e96a0217>
Mar 27 15:37:20 mx01a rspamd[17205]: <a41a7e>; task; rspamd_mime_part_detect_language: detected part language: de
Mar 27 15:37:20 mx01a rspamd[17205]: <a41a7e>; task; rspamd_mime_part_detect_language: detected part language: de
Mar 27 15:37:20 mx01a rspamd[17205]: <a41a7e>; surbl; process_dns_results: <fjghecfvowoftfhbjiplcbfbeyvsy@yy.duykhanhproduct.icu> domain [duykhanhproduct.icu] is in surbl zen.spamhaus.org(900007f)
Mar 27 15:37:20 mx01a rspamd[17205]: <a41a7e>; surbl; process_dns_results: <fjghecfvowoftfhbjiplcbfbeyvsy@yy.duykhanhproduct.icu> domain [duykhanhproduct.icu] is in surbl zen.spamhaus.org(200007f)
Mar 27 15:37:20 mx01a rspamd[17205]: <a41a7e>; lua; once_received.lua:68: SMTP resolver failed to resolve: 89.233.149.185.in-addr.arpa is canister.cartzaa.com
Mar 27 15:37:20 mx01a rspamd[17205]: <a41a7e>; surbl; process_dns_results: <fjghecfvowoftfhbjiplcbfbeyvsy@yy.duykhanhproduct.icu> domain [duykhanhproduct.icu.multi.surbl.org] is in surbl multi.surbl.org(40)
Mar 27 15:37:20 mx01a rspamd[17205]: <a41a7e>; surbl; process_dns_results: <fjghecfvowoftfhbjiplcbfbeyvsy@yy.duykhanhproduct.icu> domain [duykhanhproduct.icu.multi.uribl.com] is in surbl multi.uribl.com(2)
Mar 27 15:37:20 mx01a rspamd[17205]: <a41a7e>; surbl; process_dns_results: <fjghecfvowoftfhbjiplcbfbeyvsy@yy.duykhanhproduct.icu> domain [duykhanhproduct.icu.dbl.spamhaus.org] is in surbl dbl.spamhaus.org(201007f)
Mar 27 15:37:20 mx01a rspamd[17205]: <a41a7e>; task; rspamd_symcache_process_symbols: <fjghecfvowoftfhbjiplcbfbeyvsy@yy.duykhanhproduct.icu> has already scored more than 118.49, so do not plan more checks
Mar 27 15:37:20 mx01a rspamd[17205]: <a41a7e>; task; bayes_classify: skip classification as ham class has not enough learns: 0, 200 required
Mar 27 15:37:20 mx01a rspamd[17205]: <a41a7e>; lua; greylist.lua:381: greylisted until "Wed, 27 Mar 2019 15:37:30 GMT", new record
Mar 27 15:37:20 mx01a rspamd[17205]: <a41a7e>; task; rspamd_add_passthrough_result: <fjghecfvowoftfhbjiplcbfbeyvsy@yy.duykhanhproduct.icu>: set pre-result to soft reject (no score): 'Your message was greylisted. Please wait ten seconds.' from greylist(1)
Mar 27 15:37:20 mx01a rspamd[17205]: <a41a7e>; task; rspamd_task_write_log: id: <fjghecfvowoftfhbjiplcbfbeyvsy@yy.duykhanhproduct.icu>, qid: <6E52240389>, ip: 185.149.233.89, from: <janaztccjengeier@duykhanhproduct.icu>, (default: F (soft reject): [126.57/12.00] [XXX,DBL_SPAM(12.50){duykhanhproduct.icu.dbl.spamhaus.org;},RBL_BARRACUDA(12.50){89.233.149.185.b.barracudacentral.org;},URIBL_BLACK(7.50){duykhanhproduct.icu.multi.uribl.com;},URIBL_SBL(6.50){duykhanhproduct.icu;},ABUSE_SURBL(5.50){duykhanhproduct.icu.multi.surbl.org;},URIBL_DROP(5.00){duykhanhproduct.icu;},IP_SCORE(3.78){ip: (9.91), ipnet: 185.149.232.0/22(4.95), asn: 174(3.96), country: US(0.05);},HFILTER_HOSTNAME_UNKNOWN(2.50){},KEEN_DNS_BADTLD(2.50){},HTML_SHORT_LINK_IMG_1(2.00){},KAM_ICU_BAD_TLD(2.00){__KAM_ICUTLD_FROM;},RBL_SPAMHAUS_CSS(2.00){89.233.149.185.zen.spamhaus.org : 127.0.0.3;},FROM_EXCESS_QP(1.20){},URI_COUNT_ODD(1.00){5;},BAD_REP_POLICIES(0.10){},MIME_GOOD(-0.10){multipart/alternative;text/plain;},ONCE_RECEIVED(0.10){},HAS_LIST_UNSUB(-0.01){},ARC_NA(0.00){},ASN(0.00){asn:174, ipnet:185.149.232.0/22, country:US;},DKIM_TRACE(0.00){duykhanhproduct.icu:-;},DMARC_POLICY_ALLOW(0.00){duykhanhproduct.icu;none;},DMARC_POLICY_ALLOW_WITH_FAILURES(0.00){},FROM_EQ_ENVFROM(0.00){},FROM_HAS_DN(0.00){},GREYLIST(0.00){greylisted;Wed, 27 Mar 2019 15:37:30 GMT;new record;},MIME_TRACE(0.00){0:+;1:+;2:~;},RCPT_COUNT_ONE(0.00){1;},RCVD_COUNT_ZERO(0.00){0;},R_DKIM_REJECT(0.00){duykhanhproduct.icu:s=dkim;},R_SPF_ALLOW(0.00){+ip4:185.149.233.0/24;},TO_DN_NONE(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){}]), len: 3388, time: 171.686ms real, 33.240ms virtual, dns req: 49, digest: <f2df1181e1e26db6c752dc41e96a0217>, rcpts: <XXX>, mime_rcpts: <XXX>, forced: soft reject "Your message was greylisted. Please wait ten seconds."; score=nan (set by grey
Mar 27 15:37:20 mx01a rspamd[17205]: <a41a7e>; task; rspamd_protocol_http_reply: regexp statistics: 2637 pcre regexps scanned, 6 regexps matched, 1454 regexps total, 383 regexps cached, 525k bytes scanned using pcre, 525k bytes scanned total
```

### Expected results:

Same behavior as 1.8.3.

### Actual results:

Messages get soft reject or even rewritten (when greylisting is successful) instead of reject.

### Configuration (e.g. `rspamadm configdump module`):

actions {
    add_header = 8;
    reject = 8;
    rewrite_subject = 8;
    subject = "*****SPAM***** %s";
    greylist = 2;
}
greylist {
    ipv6_mask = 64;
    whitelist_domains_url [
        "/etc/rspamd/local.d/greylist-whitelist-domains.inc",
    ]
    expire = 2592000;
    ipv4_mask = 19;
    message = "Your message was greylisted. Please wait ten seconds.";
    max_data_len = 10000;
    action = "soft reject";
    key_prefix = "rg";
    timeout = 10;
}

**Comment by vstakhov** [comment]
No, same thresholds have **NEVER** been expected to be valid. It is not Rspamd issue, just don't do it.

**Comment by membero** [comment]
Hello vstakhov,

OK, I can change that. I have tried the following:

Output from task:get_settings(): {[actions] = {[rewrite_subject] = 8.000001, [greylist] = 2, [add_header] = 8, [reject] = 8.000010}}

The problem still exists:

```
Mar 28 15:17:13 mx01a rspamd[15328]: <eb05db>; task; accept_socket: accepted connection from 127.0.0.1 port 40260, task ptr: 000055704F07EDF0
Mar 28 15:17:13 mx01a rspamd[15328]: <eb05db>; task; rspamd_message_parse: loaded message; id: <undef>; queue-id: <D664741321>; size: 3347; checksum: <c2d7882db0fc95d9de359799146bf856>
Mar 28 15:17:13 mx01a rspamd[15328]: <eb05db>; lua; keen_userconfig.lua:108: DEBUG used settings: {[actions] = {[rewrite_subject] = 8.000001, [greylist] = 2, [add_header] = 8, [reject] = 8.000010}}
Mar 28 15:17:13 mx01a rspamd[15328]: <eb05db>; task; rspamd_mime_text_part_utf8_convert: converted from windows-1251 to UTF-8 inlen: 2792, outlen: 2795 (2792 UTF16 chars)
Mar 28 15:17:13 mx01a rspamd[15328]: <eb05db>; task; rspamd_symcache_process_symbols: <undef> has already scored more than 10.50, so do not plan more checks
Mar 28 15:17:13 mx01a rspamd[15328]: <eb05db>; lua; once_received.lua:68: SMTP resolver failed to resolve: 36.240.177.94.in-addr.arpa is host36-240-177-94.static.arubacloud.fr
Mar 28 15:17:13 mx01a rspamd[15328]: <eb05db>; lua; greylist.lua:355: greylisting pass (body) until Sat, 27 Apr 2019 15:17:13 GMT
Mar 28 15:17:13 mx01a rspamd[15328]: <eb05db>; task; bayes_classify: skip classification as ham class has not enough learns: 0, 200 required
Mar 28 15:17:13 mx01a rspamd[15328]: <eb05db>; task; rspamd_task_write_log: id: <undef>, qid: <D664741321>, ip: 94.177.240.36, from: <hankins@james.com>, (default: T (rewrite subject): [72.28/8.00] [RBL_BARRACUDA(12.50){36.240.177.94.b.barracudacentral.org;},RBL_NIXSPAM(12.50){36.240.177.94.ix.dnsbl.manitu.net;},RBL_BLOCKLISTDE(6.50){36.240.177.94.bl.blocklist.de;},RBL_SPAMCOP(4.50){36.240.177.94.bl.spamcop.net;},RBL_VIRUSFREE_BOTNET(4.00){36.240.177.94.bip.virusfree.cz : 127.0.0.2;},IP_SCORE(3.78){ip: (9.91), ipnet: 94.177.240.0/22(4.95), asn: 199653(3.96), country: FR(0.09);},R_BAD_CTE_7BIT(3.50){7bit;},VIOLATED_DIRECT_SPF(3.50){},FORGED_MUA_OUTLOOK(3.00){},RCVD_HELO_USER(3.00){},RECEIVED_SPAMHAUS_XBL(3.00){36.104.114.103.zen.spamhaus.org : 127.0.0.4;},HFILTER_HOSTNAME_UNKNOWN(2.50){},MISSING_MID(2.50){},MISSING_TO(2.00){},RBL_SENDERSCORE(2.00){36.240.177.94.bl.score.senderscore.com;},FROM_NEEDS_ENCODING(1.00){},R_NO_SPACE_IN_FROM(1.00){},SUBJECT_NEEDS_ENCODING(1.00){},KAM_LOTTO1(0.50){__KAM_LOTTO2;__KAM_LOTTO3;__KAM_LOTTO5;},MIME_GOOD(-0.10){text/plain;},RCVD_NO_TLS_LAST(0.10){},ARC_NA(0.00){},ASN(0.00){asn:199653, ipnet:94.177.240.0/22, country:FR;},DMARC_NA(0.00){james.com;},FROM_EQ_ENVFROM(0.00){},FROM_HAS_DN(0.00){},GREYLIST(0.00){pass;body;},HAS_REPLYTO(0.00){salamancajesus@gmx.es;},HAS_X_PRIO_THREE(0.00){3;},MIME_TRACE(0.00){0:+;},RCVD_COUNT_TWO(0.00){2;},RCVD_VIA_SMTP_AUTH(0.00){},REPLYTO_DOM_NEQ_FROM_DOM(0.00){},R_DKIM_NA(0.00){},R_SPF_SOFTFAIL(0.00){~all;}]), len: 3347, time: 41.076ms real, 26.603ms virtual, dns req: 50, digest: <c2d7882db0fc95d9de359799146bf856>, rcpts: <xxx>
Mar 28 15:17:13 mx01a rspamd[15328]: <eb05db>; task; rspamd_protocol_http_reply: regexp statistics: 0 pcre regexps scanned, 13 regexps matched, 1454 regexps total, 1578 regexps cached, 0B bytes scanned using pcre, 8.21k bytes scanned total
```

This message was accepted with rewrite_subject instead of rejected. In 1.8.3 the same message was rejected (with the same lua plugin code).

Perhaps I did not get point but at the moment I am stumbed.

**Comment by mvdan** [comment]
I encountered the very same issue when upgrading to 1.9. I think `rspamadm configtest` should error if this kind of invalid config is found.

**Comment by membero** [comment]
Hello all,

I have tested this a little bit more and I could solve my problem.

To clearify: I have a LUA Plugin which uses task:set_settings to allow a per user configuration. My Plugins sets for example:

{[actions] = {[rewrite_subject] = 8, [greylist] = 2, [add_header] = 8, [reject] = 8}}

My local.d/actions.conf looked like:

reject = 25;
add_header = 12;
rewrite_subject = 12;
greylist = 2;

I could solve the problem with changing actions.conf to the minimal value I set with task:set_settings:

reject = 25;
add_header = 8;
rewrite_subject = 8;
greylist = 2;

With this setting, messages are being rejected correctly and the action is not "overwritten" by greylisting module.

**Comment by mvdan** [comment]
I personally think this issue should be reopened. Even if this is intended behavior, rspamd should at least consider the bad config as a start-up error.

**Comment by vstakhov** [comment]
I'm sorry but I cannot include protection from all stupid actions a user can do with Rspamd.

**Comment by mvdan** [comment]
True. But this is something that used to work and is now suddenly broken in a silent way. It's easy and reasonable to either undo the regression, or make rspamd error/warn in that case.

**Comment by vstakhov** [comment]
It's way more simple not to do stupid things I suppose.

**Comment by mvdan** [comment]
It's also much simpler for rspamd to not have hidden regressions and unspecified behavior :) From the user's point of view, it's the configuration file that's confusing.

**Comment by vstakhov** [comment]
The problem is that with the custom actions these sanity checks now look quite hard to be implemented...

**Comment by membero** [comment]
Hi,

I have corrected all thresholds and now everything is fine again. 

My plugin now sets:

{actions = {reject=8,greylist=null,"rewrite subject"=null}}

or 

{actions = {reject=12,greylist=2,"rewrite subject"=8}}

It will never set the same thresholds.

One important note is that task:set_settings does not recognize rewrite_subject with the underscore as an action. Only when "rewrite subject" is used, I see 

task; lua_task_set_settings: adjusted action rewrite subject: 8.00 -> 10.00

with debug logging enabled. I needed some time to find that out.
