### ISSUE TITLE
Comments with {{ inside bring ucl produce errors

### ISSUE THREAD

**Issue by croessner** [rspamd/rspamd#2824]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [X] Unintended behaviour (bug)
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
master

If you have a comment like this:

```
local.d/some_module.conf:

# {{{
...
# }}}
```

Rspamd will fail to start.

Same to Lua comments (for example settings_redis Lua function).

```
-- {{{
...
-- }}}
```

will prevent Rspamd from starting. These comments are used by Vim editor to do code folding. Without these comments, things become ugly to view.

**Comment by vstakhov** [comment]
As I've said in the IRC channel, it will NOT be changed.

The benefits from Jinja templates are much higher than benefits from allowing any sort of crap in the comments, you  can also use {% raw %} as suggested by @c-rosenberg.

**Comment by croessner** [comment]
If you want to, you could give me a hint in IRC (priv), what you are doing with Jinja here. I am interesed in this topic. I claos could play around with it and report bugs (if any) back to you. Thanks

**Comment by vstakhov** [comment]
https://rspamd.com/doc/configuration/index.html#jinja-templating 

Ideally, I should indeed fix lupa parser to avoid templates in at least line comments in both Lua and UCL styles (e.g. in those lines that start with `#` or `--`)

**Comment by vstakhov** [comment]
Actually, that would be too hard. Another thing I've thought about was to change liquid tags for variables to match both ucl and lua:

`{{ foo }}` -> `{{| foo |}}`

Or something else - suggestions are welcome.

**Comment by vstakhov** [comment]
`{= =}` - what about it?

**Comment by vstakhov** [comment]
Can we close it?

**Comment by croessner** [comment]
I fear, I can not really answer anything related.

For the original question, I had to remove all code folding tags. Too sad, but I can understand your arguments.

**Comment by vstakhov** [comment]
Folding tags should be fine with `{=` `=}`
