### ISSUE TITLE
Is it possible to use multimap with "quarantine" action?

### ISSUE THREAD

**Issue by iq180** [rspamd/rspamd#2841]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Unintended behaviour (bug)
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.9.0
### Operation system (the exact version), CPU (including architecture and processor family):
5.0.7-gentoo
### Description (Please provide a descriptive summary of the issue):
I want to move messages containing disabled attachments to the quarantine, but this doesn't work and I see such records in the log:

`2019-04-07 16:18:43 #6514(rspamd_proxy) <f25f9b>; proxy; lua_metric_symbol_callback: call to (FILENAME_EXT_BLACKLISTED) failed (2): /usr/share/rspamd/plugins/multimap.lua:571: unknown action quarantine; trace: [1]:{[C]:-1 - set_pre_result [C]}; [2]:{/usr/share/rspamd/plugins/multimap.lua:571 - callback [Lua]}; [3]:{/usr/share/rspamd/plugins/multimap.lua:459 - match_element [Lua]}; [4]:{/usr/share/rspamd/plugins/multimap.lua:585 - match_rule [Lua]}; [5]:{/usr/share/rspamd/plugins/multimap.lua:625 - match_filename [Lua]}; [6]:{/usr/share/rspamd/plugins/multimap.lua:818 - process_func [Lua]}; [7]:{/usr/share/rspamd/plugins/multimap.lua:888 - multimap_callback [Lua]}; [8]:{/usr/share/rspamd/plugins/multimap.lua:896 - <unknown> [Lua]};`

Strange but when I change the action to "reject" it works.

**Comment by vstakhov** [comment]
Yes, you'd need to define quarantine action first however. Again, please refrain from using GitHub issue tracker for generic questions. Closing issue.

**Comment by iq180** [comment]
According to the FAQ <https://rspamd.com/doc/faq.html#what-are-rspamd-actions>  this action is implemented:

 

From version 1.9, there are also some more actions:

*	quarantine: push a message to quarantine (must be supported by MTA)
*	discard: silently discard a message
