### ISSUE TITLE
[Help] Meaning of BAD_REP_POLICIES

### ISSUE THREAD

**Issue by resec** [rspamd/rspamd#2842]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [x] WebUI/Usability
* [ ] Unintended behaviour (bug)
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [X] Not applicable

### Rspamd version:
master

### Description (Please provide a descriptive summary of the issue):

I am trying to understand the meaning of Symbol BAD_REP_POLICIES and I found in https://github.com/rspamd/rspamd/blob/545e090c81ce22bbb7edb6d3621c348bd994449c/conf/composites.conf#L127
The expression of the composite Symbol is very different from others.

May I have your help to understand the meaning of this expression? And actually I cannot find any doc that is explaining the . But do refer me to the correct doc if I missed any. Thanks!

**Comment by moisseev** [comment]
[Composites with symbol groups](https://rspamd.com/doc/configuration/composites.html#composites-with-symbol-groups)

**Comment by resec** [comment]
@moisseev thanks! seems it is the one doc I am looking for : ) closing this now.
