### ISSUE TITLE
ebl.msbl.org DNS issues

### ISSUE THREAD

**Issue by locojohn** [rspamd/rspamd#2846]
4/11/2019, 12:44:57 PM | rspamd_proxy | 18845 | lua | 1d690e | Error querying DNS(b4cf0001d67a18d546d33f59d545face7c2c45b6.ebl.msbl.org): server fail
-- | -- | -- | -- | -- | --
4/11/2019, 12:44:55 PM | rspamd_proxy | 18845 | lua | 1d690e | Error querying DNS(77b9e9488090a5dd49695834a5470ce29dedfda6.ebl.msbl.org): server fail
4/11/2019, 12:44:55 PM | rspamd_proxy | 18845 | lua | 1d690e | Error querying DNS(bb92f63c51828e03154a1b66fa87136e30e83cfd.ebl.msbl.org): server fail
4/11/2019, 12:35:26 PM | rspamd_proxy | 18845 | lua | 9a51a1 | Error querying DNS(1f44909114fcd2a5c492be2d053b389f900184bb.ebl.msbl.org): server fail
4/11/2019, 12:35:26 PM | rspamd_proxy | 18845 | lua | 9a51a1 | Error querying DNS(bdd9eb45f938591c7dbebe700381aebceb2e329a.ebl.msbl.org): server fail
4/11/2019, 12:06:03 PM | rspamd_proxy | 18845 | lua | 8af43d | Error querying DNS(6b1418a9f9f2c009112b2518f2f22b19dff05094.ebl.msbl.org): server fail
4/11/2019, 12:06:03 PM | rspamd_proxy | 18845 | lua | 8af43d | Error querying DNS(77b9e9488090a5dd49695834a5470ce29dedfda6.ebl.msbl.org): server fail
4/11/2019, 10:38:07 AM | rspamd_proxy | 18845 | lua | 4af6eb | Error querying DNS(5665c7f09217effd18f8b4fa723c02d7cf651dac.ebl.msbl.org): server fail

Rspamd version 1.9.1
Ubuntu 18.04

**Comment by vstakhov** [comment]
Is it Rspamd issue?

**Comment by locojohn** [comment]
I don't know.  If not, what is it?
