### ISSUE TITLE
[Feature] Add a local.d plugins directory

### ISSUE THREAD

**Issue by sriccio** [rspamd/rspamd#2848]
Hello,

While I was writing a Cyren gateway plugin for rspamd (https://github.com/sriccio/rspamd-plugins), I've noticed that it the only way to add a plugin is to put it in `$PLUGINSDIR` which is most of the time set to `/usr/share/rspamd/plugins/`

It think it would be nice to also have a `local.d/plugins` or something like this that is also scanned at startup, so we can add "local" plugins without needing to add it to the official plugin dir.

For exemple this is good for when you use rspamd in a docker container and mount `/etc/rspamd/local.d` to docker host dir so you can easily customize the setup.

Actually we must mount the file itself for each module for example:
`path_to_the/lua_life.lua:/usr/share/rspamd/plugins/lua_file.lua`

**Comment by vstakhov** [comment]
I'll add that as `plugins.d`

**Comment by sriccio** [comment]
Excellent. Thank you very much!

**Comment by vstakhov** [comment]
Btw, I suppose that your plugin should be added as a part of `external_services` module.

**Comment by sriccio** [comment]
Hi, sorry for the late reply. Do you mean to officially add it to external_services ?
