### ISSUE TITLE
[BUG] Lua module returns to wrong code after coroutines yield when using blocking calls?

### ISSUE THREAD

**Issue by rm-minus-rf** [rspamd/rspamd#2853]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
I encountered a strange problem while writing a lua module, which saves the parts of the mail to disk (to unpack archives recursively...):
The actual code is executed inside a xpcall. The files are written to a temp dir which is removed by a a cleanup call after the xpcall wrapped callback was successful.
Because of the recursive nature of the module i decided to use blocking redis/http calls.
And that is where it get's strange.
Under load the module sometimes throws "no such file" errors, because the temp dir was already deleted by the cleanup routine, which seems to get called way to early.
BUT ... this only happens if i have blocking calls in my module.
Could this be a coroutines problem? It kinda seems like the cleanup routine is called right after the yield from the blocking call. (not always though...)

I managed to reproduce the problem in a spike consisting of a lua module (coro_test.lua) and a python testscript quickshot (spike-rnd-spamc-feed.py).
You can find both files attached.
[spike.zip](https://github.com/rspamd/rspamd/files/3084731/spike.zip)

                       
I really hope that you can reproduce the error with this setup on your systems...                    
                                                   
### Steps to Reproduce                             
1. [prepare rspamd]                                    
- Use coro_test.lua as module (should reproduce in a vanilla install of rspamd)
- create /tmp/rspamd/coro (writable for _rspamd user)
- (optional) Enable debug logging for coro_test module.         
2. [trigger error with python script]                               
Use spike-rnd-spamc-feed.py                        
  - change to params to match your environment                                                       
  - uncomment either the "self.rspamc_feed()" to check random mails with rspamc or "self.send_msg()" to send the random mails via smtp.
     (both ways produce the error for me, although rspamc tends to be the quicker way...
      'trd_ct = 2 / trd_mail_ct = 1' are suitable to trigger the error via rspamc, while
      'trd_ct = 8 / trd_mail_ct = 20' was needed to trigger it via smtp on our systems.)
  - uncomment either the redis or http blocking calls
     (both ways produce the errors, as long as they are blocking)
  - comment both blocking calls out to prove that the error does not occour

**Expected behavior**
Normal execution (correct order) of plugin

### Versions
Reproduced/Experienced with:
- Rspamd daemon version 1.9.2 @ Red Hat Enterprise Linux Server release 7.6 (Maipo)
- Rspamd daemon version 1.9.1 @ Red Hat Enterprise Linux Server release 7.6 (Maipo)
- Rspamd daemon version 1.9.1 @ Debian 9.8 (Stretch)
- Rspamd daemon version 1.9.0 @ Red Hat Enterprise Linux Server release 7.6 (Maipo)
- Rspamd daemon version 1.8.3 @ Red Hat Enterprise Linux Server release 7.6 (Maipo)

### Additional Information
Removing the xpcall does not solve the issue.

**Comment by duncrow** [comment]
I was able to reproduce the error. Debian 10 (Buster) with rspamd 1.9.2-1~stretch.

**Comment by rm-minus-rf** [comment]
Some debugging sessions later, it turns out, it might be a problem with using (global) variables.
When lua returns after a blocking call, there is a chance that a global variable I have set before the blocking call has the values from another task.

By habit (performance in mind) I assign attributes that should not change for a run (like task:get_queue_id()) to a variable.
So when the callback for the plugin is first called I extract the queue_id (to the variable task_id in the attached spike) and create a temporary directory based on that value.
Then I start iterating over task:get_parts(). For each part I check the cache via a blocking redis call. 
And every time this blocking call returns, there is a chance that the value of the task_id variable has changed and no longer fits to the queueid the task object represents for this run!
This explains why the temporary directory gets deleted to early:
 - task A creates temp dir A.
 - task B creates temp dir B.
 - task A makes blocking call.
 - task B makes blocking call.
 - task B returns from blocking call (task_id suddenly is 'A') and deletes temp dir A
 - task A crashes while trying to write to temp dir A

By not using variables to save the task_id (and everything based on it) or re-reading it from the task object on every return point from a blocking call I can avoid the problem.

Is this expected behavior?
Did I just miss something and that's perfectly normal for lua (or coroutines)?
If so, then maybe there should be a warning on the "Coroutines and async calls" page?
