### ISSUE TITLE
[Feature] Please develop LDAP support (i.e. for DKIM)

### ISSUE THREAD

**Issue by croessner** [rspamd/rspamd#2856]
## Summary

Some larger companies have parts of their infrastructure stored in LDAP. Currently it needs transformation scripts to extract data from LDAP and put it in some way to Redis. For example OpenDKIM is currently one big problem. DKIM keys are stored in LDAP. If you do DKIM key management and do a regular key rollover, it currently is a pain to convert this to Reids. So native LDAP support for this would really be helpful.

Unfortunately I am not a very good Lua developer, as I have done too few coding in this language yet. So I fear I am not able to do this task.

Maybe someone could spend some time and implment a LDAP Lua lib for Rspamd that could be used for DKIM (and maybe other modules as well).

## Motivation

- Eliminate the use of OpenDKIM
- Using OpenLDAP as store for DKIM keys (see also here for the rollover-tool: https://github.com/croessner/opendkim-manage)
- Attach Rspamd directly to OpenLDAP

## Describe alternatives you've considered

Bad scripting to convert data from one database to another

## Additional context

- none

**Comment by vstakhov** [comment]
No, that's not the point I'm afraid. As tomorrow somebody would ask for something like "let's store DKIM keys in PostgreSQL or MySQL". I have studied the options and it seems that the most sane one is to use [Hashicorp Vault](https://www.vaultproject.io/). Rspamd can easily access it via REST API and it can easily extract data, such as DER encoded keys, rotation information, selectors, multiple algorithms and so on and so forth.

Vault also supports multiple storage engines including LDAP (via AD backend). I think I will go with this approach instead of endless duplication of irrelevant protocols and technologies.

**Comment by croessner** [comment]
I have installed vault and consul and walked through the entire "Get started" guide. It seems, vault might be okay for SQL, AWS, ... but not for LDAP, as it does not have a LDAP storage backend. You only can authenticate against LDAP, which is not what I asked for.

If LDAP is really not an option, then a simple HTTP-request-response interface would help. This way, Rspamd could send a HTTP request for a domain and a selector, and such a service could response with the key. It is not a big deal to write such a HTTP service as a connector between Rspamd and LDAP. So that would help a lot.

Is this an option for you?

Required options:

- http_dkim_key_map - i.e. http://127.0.0.1/get_dkim_key
- POST or GET variables dkim_domain, dkim_selector

Could use HEAD to minimize queries.

**Comment by vstakhov** [comment]
Hum? https://shapeshed.com/hashicorp-vault-ldap/

**Comment by croessner** [comment]
It is about auth: vault auth-enable ldap

**Comment by croessner** [comment]
I do not see any backend ldap in the docs

**Comment by vstakhov** [comment]
Then you can track https://github.com/hashicorp/vault/issues/1087

I personally think that storing of keys in LDAP is quite stupid. I'm going to provide tooling to do rollover and keys management using Vault as it seems to be much more secure and has a decent architecture.

**Comment by croessner** [comment]
Even I have a different opinion concerning LDAP and security... That depends on what you have configured and how you use the service...

Anyways: Would it still be possible to provide the HTTP interface, so people have at least a chance to write their own database connector?

It is not against Vault. It is another option you would give us.

**Comment by c-rosenberg** [comment]
What about writing a custom plugin that checks for keys in redis and greps them via http when missing? btw is there really a need to have one key per domain?

**Comment by croessner** [comment]
I know setups with about 5000 domains. All using LDAP for DKIM key material. Redis doubles data storage. Nearly all mail components support LDAP. And now I look for a way to get Rspamd connected to such environments. And yet Vault is not ready for this.

**Comment by vstakhov** [comment]
You can implement some basic REST tool that supports a limited subset of the vault API (kv version 1 related).

**Comment by romale** [comment]
+1 for this request.
For example, Zimbra mail server stores dkim data in ldap and it can create issues, when need migration from Zimbra spamassassin to rspamd.

zimbra opendkim config example:
```
LDAPBindUser            uid=zmpostfix,cn=appaccts,cn=zimbra
LDAPBindPassword        MYPASSW
LDAPUseTLS              0
LDAPTimeout             30
LDAPKeepaliveIdle       240
LDAPKeepaliveProbes     10
LDAPKeepaliveInterval   30
SigningTable            ldaps://email.domain.ru:636/?DKIMSelector?sub?(DKIMIdentity=$d)
KeyTable                ldaps://email.domain.ru:636/?DKIMDomain,DKIMSelector,DKIMKey,?sub?(DKIMSelector=$d)
Canonicalization        relaxed/relaxed
ReportAddress           admin@domain.ru
SignHeaders             message-id,date,from,mime-version,to
```
