### ISSUE TITLE
Web UI authentication [$100]

### ISSUE THREAD

**Issue by msimerson** [rspamd/rspamd#286]
First off, my compliments to whomever created that spiffy Web UI, it's quite great. 

What would make it even greater would be permitting users to access it. For that to work, there'd need to be user/pass logins, and then filtering of the which entries they could see. In the simplest case, a logged in user could see only messages for which they were the envelope sender or envelope recipient. If their username is postmaster@example.com, they should see messages in which example.com appears as a sender or recipient.

If I were adding such a feature, I'd use the MTA or an IMAP server for the authentication source.
##

**Comment by vstakhov** [comment]
The problem here is that this check should be done within rspamd which would be complicated from my point of view. Even implementing asynchronous TLS is a pain as it is not really supported by libevent.

**Comment by vstakhov** [comment]
I'd not close this issue because I personally consider this functionality as a great idea for corporate clients. The only point I disagree with is the direct querying of the IMAP/SMTP service. That could be done by either some static list in json/pbkdf2 or by some intermediate service that would ask SMTP/IMAP in blocking matter (high load is not expected at this place).

**Comment by vstakhov** [comment]
So what type of authentication sound the most reasonable so far? Do we still need IMAP/SMTP authentication or we can store all user/password pairs somewhere in the rspamd configuration?

**Comment by msimerson** [comment]
The IMAP and SMTP servers already have access to a wide variety of auth providers (RDBMS, redis, vpopmail, LDAP, UNIX login, etc.). Why duplicate all that effort?

 The solution that requires the least work to write and maintain, and that will "just work" in the widest variety of environments is one that  uses IMAP or SMTP for user validation and authentication.

**Comment by vstakhov** [comment]
I see the only possibility to create a sort of perl script, for example, that would login to IMAP/SMTP when queried by HTTP by rspamd. Writing of non-blocking IMAP/SMTP client is not an easy task, I'm afraid.

**Comment by vstakhov** [comment]
Well, I'm starting to work on this issue. My initial idea is to have a special controller session which applies certain restrictions on using of webui. This involves the full description of what is allowed for this specific user and how. For example, some user can query Rspamd for its own domain but not about other domains. Authorisation itself could be done using cookies + some external http service to check authorisation. I'll start with imap + perl anyevent plugin I suppose. 

Moreover, the controller should support plugins from Lua to implement custom commands using Lua API.

**Comment by xpunkt** [comment]
make a controller that understand sasl auth like postfix do with dovecot-sasl socket, imho if just rspamd could use this as a auth it would make life more easy

still wish i had rmilter working with sasl auth here :(

**Comment by msimerson** [comment]
@xpunkt makes a good point. The reason I wanted POP3/IMAP auth was *because* dovecot already had SASL plugins, making it easier to tie into other mechanisms.
