### ISSUE TITLE
[BUG] System Crashes and reloads

### ISSUE THREAD

**Issue by khaverblad** [rspamd/rspamd#2866]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Seems that the installation, which has been up for less than 24h, seems to crash ones a while and noticed this due to the update in rspamd admin interface is reset once a while. Recommendation from TG was to enable debug logging and see if that reveals something more which it does. Seems to be some missing files, but still open an issue, based on that the admin gui doesn't provide any warnings, so not sure what exactly fails the running installation.

### Steps to Reproduce

Just keep it running.

**Expected behavior**
n/a

### Versions
Version: 1.9.2
Hardware: Intel NUC i3 x64 8gb RAM and 120GB M.2 SSD drive

### Additional Information
Adding debug log from system which includes everything from when it was installed <24h log and around 2-3h debug log.
[rspamd.zip](https://github.com/rspamd/rspamd/files/3100329/rspamd.zip)

**Comment by vstakhov** [comment]
It should be fixed now in the master branch.
