### ISSUE TITLE
[BUG] Can't detect exe files in 7z archive

### ISSUE THREAD

**Issue by skfwork** [rspamd/rspamd#2867]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

### Description

mime_types can't detect windows executables (.exe) in 7z archives. Same exe file in zip archive correctly detected by mime_types.

### Steps to Reproduce

1. Configure local.d/mime_types.conf: 
```
bad_archive_extensions = {
exe = 5,
}
```
2. Configure local.d/force_actions.conf: 
```
rules {

  REJECT_MESSAGE_BAD_EXTENSION {
      action = "reject";
      expression = "MIME_BAD_EXTENSION";
      message = "Rejected due to bad file extension in attachment.";

  }
}
```

3. Send e-mail with attached 7z archive, put any exe file in archive, notepad.exe for example.

**Expected behavior**
Messages should not be sent.

### Versions

Rspamd daemon version 1.9.2
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.8 (stretch)
Release:	9.8
Codename:	stretch

### Additional Information

Warning message from logs, probably related:

`error  in squeezed rule MIME_TYPES_CALLBACK:  /usr/share/rspamd/plugins/mime_types.lua:1093: attempt to compare  boolean with string`

**Comment by moisseev** [comment]
You should place `force actions` module configuration in `local.d/force_actions.conf` instead of `local.d/force_actions`.
The warning is not related to the issue.

**Comment by skfwork** [comment]
> You should place `force actions` module configuration in `local.d/force_actions.conf` instead of `local.d/force_actions`.
> The warning is not related to the issue.

Fixed typo in original post.

**Comment by moisseev** [comment]
Does it work as expected now?

**Comment by skfwork** [comment]
Nope, config file already was named force_actions.conf. Issue not resolved.

**Comment by moisseev** [comment]
I canot reproduce your issue.
```
# rspamc 7z.eml | egrep -v '(:?\([-0]|-ID)'
[Metric: default]
Action: reject
Spam: true
Score: 8.00 / 14.00
Symbol: MIME_BAD_ATTACHMENT (1.60)[7z]
Symbol: MIME_BAD_EXTENSION (10.00)[exe]
Message - smtp_message: Rejected due to bad file extension in attachment.
```

**Comment by skfwork** [comment]
I was able to reproduce this issue on clean installation, fresh VM.
I'm attaching configdump and couple of sample files.


```
# file certutil.*
certutil.7z:  7-zip archive data, version 0.4
certutil.exe: PE32 executable (console) Intel 80386, for MS Windows
certutil.zip: Zip archive data, at least v?[0x314] to extract
```

```
# rspamc *.eml
Results for file: zipexe.eml (0.119 seconds)
[Metric: default]
Action: reject
Spam: true
Score: 12.60 / 15.00
Symbol: ARC_NA (0.00)
Symbol: DMARC_NA (0.00)[example.com]
Symbol: FORCE_ACTION_REJECT_MESSAGE_BAD_EXTENSION (0.00)[reject]
Symbol: FROM_NO_DN (0.00)
Symbol: HAS_ATTACHMENT (0.00)
Symbol: HFILTER_HOSTNAME_UNKNOWN (2.50)
Symbol: MIME_BAD_EXTENSION (10.00)[exe]
Symbol: MIME_GOOD (-0.10)[multipart/mixed]
Symbol: MIME_HTML_ONLY (0.20)
Symbol: MIME_TRACE (0.00)[0:+, 1:~, 2:-, 2:~]
Symbol: RCPT_COUNT_ONE (0.00)[1]
Symbol: RCVD_COUNT_ZERO (0.00)[0]
Symbol: R_DKIM_NA (0.00)
Symbol: TO_DN_NONE (0.00)
Symbol: TO_EQ_FROM (0.00)
Message-ID: 05ec1f1d-9944-f7b6-e3c6-8ca9d5146ffe@example.com
Message - smtp_message: Rejected due to bad file extension in attachment.
```

```
Results for file: 7zexe.eml (0.119 seconds)
[Metric: default]
Action: no action
Spam: false
Score: 2.70 / 15.00
Symbol: ARC_NA (0.00)
Symbol: DMARC_NA (0.00)[example.com]
Symbol: FROM_NO_DN (0.00)
Symbol: HAS_ATTACHMENT (0.00)
Symbol: HFILTER_HOSTNAME_UNKNOWN (2.50)
Symbol: MIME_GOOD (-0.10)[multipart/mixed]
Symbol: MIME_HTML_ONLY (0.20)
Symbol: MIME_TRACE (0.00)[0:+, 1:~, 2:~]
Symbol: MIME_UNKNOWN (0.10)[application/x-7z-compressed]
Symbol: RCPT_COUNT_ONE (0.00)[1]
Symbol: RCVD_COUNT_ZERO (0.00)[0]
Symbol: R_DKIM_NA (0.00)
Symbol: TO_DN_NONE (0.00)
Symbol: TO_EQ_FROM (0.00)
Message-ID: c2ae0a9f-508a-2c96-7413-3e027475e4b2@example.com
```

[sample_files.zip](https://github.com/rspamd/rspamd/files/3107096/sample_files.zip)

**Comment by moisseev** [comment]
I've scanned your samples. Rspamd detected exe files in both archives.

**Comment by skfwork** [comment]
How can we proceed from here?

**Comment by moisseev** [comment]
Yes, maybe the problem is the official Debian package. Try to install Rspamd from Rspamd APT repository. https://rspamd.com/downloads.html

**Comment by skfwork** [comment]
Package was installed from rspamd repo:

```
# apt-cache policy rspamd
rspamd:
  Installed: 1.9.2-1~stretch
  Candidate: 1.9.2-1~stretch
  Version table:
 *** 1.9.2-1~stretch 500
        500 http://rspamd.com/apt-stable stretch/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by moisseev** [comment]
I've reproduced the issue on Debian 9.8.

@vstakhov 
On Debian `get_files_full` returns an empty list for `7zip` archives.
https://github.com/rspamd/rspamd/blob/master/src/plugins/lua/mime_types.lua#L1052
