### ISSUE TITLE
[Feature] Make action forced by dmarc module (or any module) clear in WebUI

### ISSUE THREAD

**Issue by tjharman** [rspamd/rspamd#2868]
## Summary

Make it clear in the WebUI why a message was rejected when rejected by a module.

## Motivation

If you enable the the following dmarc configuration to reject emails based on dmarc policy failure (in local.d/dmarc.conf) 
```
	actions = {
		quarantine = "add_header";
		reject = "reject";
	}
```
then when an email is rejected due to the dmarc module, it's not clear at all in the WebUI WHY the mail was rejected.  For example I just had an email get REJECT with a score of only 9.67.
DMARC_POLICY_REJECT (2) fired as I expected, but it's only adding 2 to the score.
It would be nice if there was a REJECTED_DUE_TO_DMARC_POLICY tag or similar, even if it had no score.  That way it's obvious without having to dig into the logs why a message got REJECT with a score lower than threshold.

## Describe alternatives you've considered

It could of course be argued that if you enable this feature, you're responsible for understanding under what circumstances it fired :)

## Update
Actually this should apply to more than just DMARC.  It would be nice if somehow the output you get in the logs from:

```rspamd_add_passthrough_result: <undef>: set pre-result to reject (no score): 'Action set by DMARC' from dmarc(1)```

was exposed in the WebUI.   So that it's possible to see if a module does set a passthrough result, which module that was and why it set the result it set.

**Comment by lhorace** [comment]
It would be nice if are you willing to submit a PR?

**Comment by tjharman** [comment]
@lhorace If I was able to code at all, I would have submitted a PR along with my FR.
I fully understand rspamd is an open source project and I in no way expect this to be implemented, it is more offered as a feature for consideration.
One day when I learn something other than ircII (see my LiCe github repo) I will contribute more than rspamd documentation updates.  Today, however is not that day :)

**Comment by lhorace** [comment]
I don't know the language but right now it's just one guy. He's willing to code to fix things is remarkable. I think before we ask for features, how about the documentation ?

**Comment by tjharman** [comment]
Where I've seen things in the documentation I feel I can fix, [I have](https://github.com/rspamd/rspamd.com/commits?author=tjharman&since=2018-11-30&until=2018-12-31).

**Comment by lhorace** [comment]
Nice, thanks

**Comment by lhorace** [comment]
That helps me too, I appreciate your work!
