### ISSUE TITLE
[QUESTION] MX Whitelist

### ISSUE THREAD

**Issue by celevra** [rspamd/rspamd#2869]
Hi,

i've tried to understand the documentation but don't get it.
I'm get mails from an external domain that is trying to send mails for a spf protected Domain and gets rejected.
i want to whitelist not a single mail server from that domain but the whole domain like
if the mail is from a stmp from *.microsoft.com then don't do any checks
is this possible?

regards

Celevra

**Comment by vstakhov** [comment]
Not a bug, closing as inappropriate for issue tracker.
