### ISSUE TITLE
[BUG] ARC Signing even if no DNS record for the key in the domain

### ISSUE THREAD

**Issue by mguesdon** [rspamd/rspamd#2876]
**Describe the bug**

When enabling ARC signing , there's no check if the signing key record exists in DNS. So we can't just configure a unique key and add arc signature only if the key exists in DNS.
DKIM do this check and sign only if key record exists in DNS.

### Steps to Reproduce

cat /etc/rspamd/local.d/arc.conf
auth_only = false;
allow_username_mismatch = true;
sign_inbound =true;
use_domain_sign_inbound = "recipient";
path = "/etc/my-arc-2019.key";
selector = "arc-2019";

**Expected behavior**

ARC signing only if the key record exist in recipient domain DNS

### Versions

Rspamd daemon version 1.8.3 (but I see no change in later commits on this point)
CentOS7

**Comment by vstakhov** [comment]
`check_pubkey` should be supported by arc module from the version 1.9.3 (already in the master).
