### ISSUE TITLE
Store history in sqlite3

### ISSUE THREAD

**Issue by windware** [rspamd/rspamd#2877]
## Summary

Is it possible to store history in sqlite3 instead of in redis?

## Motivation

I'm using sqlite3 as the data backend and do not have redis installed but I cannot seem to do so for histories and the web UI is throwing an error when trying to view the 'History' tab and the error log says that it can't connect to redis.

> lua; history_redis.lua:218: got error Connection refused when getting history: no value

## Describe alternatives you've considered

I'd like to store the history data in a sqlite3 database and have configuration to change the history data backend.

**Comment by moisseev** [comment]
Rspamd uses sqlite3 out-of-the-box. Probably you have enabled Redis (`servers` option) in `history_redis {}` or `redis {}` section.

**Comment by vstakhov** [comment]
No, Rspamd does not use Sqlite3 for history and there are no plans to add this functionality.

**Comment by windware** [comment]
OK. Thanks for clarification.
