### ISSUE TITLE
[BUG] rspamd build issues on macOS

### ISSUE THREAD

**Issue by essandess** [rspamd/rspamd#2881]
I am having difficulty building `rspamd` on macOS. The MacPorts link on the rspamd [page](https://rspamd.com/downloads.html) points to a `Portfile` that is years out of date and no longer works. I would like to write a new `Portfile` that uses the latest rspamd version.

It's close, but there are linking issues. I'm asking for some help to resolve these. I hope it can be done with `./configure` options specification. If not, we'll need some help on the right way to modify rspamd's cmake file.

I am seeing an issue where the necessary libraries do not appear, and the rspamd binary fails. More context appears in the commit discussions linked below, but quickly, this is what I see:

`Portfile` configure options (passed to `./configure`):
```
configure.args-append \
    -DNO_SHARED=OFF \
    -DRSPAMD_USER=${rspamd_user} \
    -DRSPAMD_GROUP=${rspamd_group} \
    -DCMAKE_INSTALL_PREFIX=${prefix} \
    -DCONFDIR=${prefix}/etc/${name} \
    -DMANDIR=${prefix}/share/man \
    -DRUNDIR=${prefix}/var/run/${name} \
    -DDBDIR=${prefix}/var/lib/${name} \
    -DLOGDIR=${prefix}/var/log/${name} \
    -DLIBDIR=${prefix}/lib \
    -DBUILD_PORT=ON \
    -DENABLE_LUAJIT=ON \
    -DINSTALL_EXAMPLES=ON \
    -DENABLE_FANN=ON \
    -DENABLE_PCRE2=ON \
    -DENABLE_GD=ON
```

Result:
```
sudo port uninstall rspamd ; sudo port clean --all rspamd ; sudo port -v install rspamd 1> ~/Downloads/rspamd_build.log 2>&1

sudo /opt/local/bin/rspamd -u _rspamd -g _rspamd -c /opt/local/etc/rspamd/rspamd.conf
dyld: Library not loaded: /opt/local/lib/libstemmer.dylib
  Referenced from: /opt/local/bin/rspamd
  Reason: image not found
Abort trap: 6

fgrep -i stemmer ~/Downloads/rspamd_build.log | head -1
[  1%] Generating libstemmer/modules.h

otool -L `which rspamd` | grep -i stemmer
	/opt/local/lib/libstemmer.dylib (compatibility version 0.0.0, current version 0.0.0)

ls -l /opt/local/lib/libstemmer.dylib
ls: /opt/local/lib/libstemmer.dylib: No such file or directory
```

If I set `-DNO_SHARED=ON`, then there are issues with the blake crypto library:
```
# after wiping and rebuilding
sudo /opt/local/bin/rspamd -u _rspamd -g _rspamd -c /opt/local/etc/rspamd/rspamd.conf
dyld: Symbol not found: _blake2b_blocks_x86
  Referenced from: /opt/local/lib/librspamd-server.dylib
  Expected in: flat namespace
 in /opt/local/lib/librspamd-server.dylib
Abort trap: 6
```

Any help would be greatly appreciated. It would be great to get a working rspamd on macOS.

PR references and discussions:
* https://github.com/macports/macports-ports/commit/857c47b3beba97eb7e9934c5bff6e8982bf44307
* https://github.com/macports/macports-ports/commit/bc694d91a1ada1cd36c092488629d8d634db89c2
* https://github.com/rspamd/rspamd/issues/2880
* https://github.com/rspamd/rspamd/issues/2879

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Comment by vstakhov** [comment]
I build Rspamd on osx as it is my main development platform. I use homebrew and the following command to build Rspamd:

```
~/rspamd.build $ cmake ../rspamd -DICU_ROOT_DIR=/usr/local/opt/icu4c/ -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DENABLE_LIBUNWIND=OFF -DENABLE_LUAJIT=ON -DENABLE_TORCH=ON -DENABLE_HYPERSCAN=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DHYPERSCAN_ROOT_DIR=/usr/local/hyperscan -DENABLE_UTILS=OFF
```

I had some issues with openssl and libicu bundled in osx itself. That's why homebrew provided ones are being used.

To tell the truth, I'm not extremely interested in OSX support as I can barely imagine any practical use of Rspamd in OSX aside of the development process.

**Comment by essandess** [comment]
Lol thanks!

Personally, I'm going to run a [mail server](https://github.com/essandess/macOS-Open-Source-Server) from a macOS box, built using rspamd. Now that Server.app is defunct, I expect you'll see a spike in interest in running rspamd on macOS from people like me who want a modern mail server. I can see from the parts that I do have working that a postfix+dovecot+rspamd+solr mail server will be a **much** better mail server than the old one Apple configured in Server.app.

It looks like it should be pretty easy to get running and maintain if you develop on macOS and are already using brew 🍺. BTW, no one over at brew has an `rspamd` recipe for macOS either, https://github.com/Homebrew/linuxbrew-core/search?q=rspamd&unscoped_q=rspamd

I'll start by trying the build based on a git clone using your command above.

**Comment by essandess** [comment]
Okay, here's what I've got. It looks like a simple process of making sure all the libraries get installed in the right place, and maybe a call to `name_tool` to point to the right dynamic libraries.

First, I'm able to build `rspamd` on macOS, and configure it with MacPorts installs. I changed your cmake command a little to point to what I believe are the correct locations for a MacPorts install. For Brew, this would be mostly replacing `/opt` with `/usr`.

```
git clone https://github.com/rspamd/rspamd.git
cd rspamd
cmake . -DICU_ROOT_DIR=/opt/local/lib/icu -DOPENSSL_ROOT_DIR=/opt/local/lib/openssl-1.0 -DENABLE_LIBUNWIND=OFF -DENABLE_LUAJIT=ON -DENABLE_TORCH=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_UTILS=OFF -DRSPAMD_USER=_rspamd -DRSPAMD_GROUP=_rspamd -DCMAKE_INSTALL_PREFIX=/opt/local -DCONFDIR=/opt/local/etc/rspamd -DMANDIR=/opt/local/share/man -DRUNDIR=/opt/local/var/run/rspamd -DDBDIR=/opt/local/var/lib/rspamd -DLOGDIR=/opt/local/var/log/rspamd -DLIBDIR=/opt/local/lib 1> ~/Downloads/rspamd_cmake.log 2>&1
make 1> ~/Downloads/rspamd_make.log 2>&1
```

All builds find. Now I just want to call the `rspamd` binary, using my own `local.d` settings. So I do this:
```
# copy the default rspamd configs to a location where local.d already lives
sudo rsync -a ./conf/ /opt/local/etc/rspamd
sudo ./src/rspamd -u _rspamd -g _rspamd -c /opt/local/etc/rspamd/rspamd.conf

2019-05-02 13:21:16 #48663(main) cfg; rspamd_config_read: failed to load config: ucl parser error: call for external handler failed
```

All the file permissions look good, so I'm note sure why this failed.

Also, for the libraries, a look into the binary for relative paths shows two, which should be easy to address on the install:
```
otool -L ./src/rspamd-1.9.3  | grep @
	@rpath/librspamd-server.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/librspamd-actrie.dylib (compatibility version 0.0.0, current version 0.0.0)
```

If you can help me get a running `rspamd` from git source, I can figure out how to configure the install on MacPorts.

**Comment by essandess** [comment]
By the way, I'm still not sure where the missing symbol `_blake2b_blocks_x86` referenced above lives in the build structure. A search through the binary and dynamic libraries doesn't show anything.

```
otool -L ./src/rspamd-1.9.3  | grep -i blake
find . -type f -name '*.dylib' -exec otool -L {} ';' | grep -i blake
```

**Comment by essandess** [comment]
Also, simplifying everything to the build directory alone causes the same issue:
```
./src/rspamd -c ./conf/rspamd.conf 
2019-05-02 13:42:36 #48825(main) cfg; rspamd_config_read: failed to load config: ucl parser error: call for external handler failed
```

**Comment by essandess** [comment]
Okay I got it! Well, at least a working example of how to create and install `rspamd` on macOS, if not yet a `Portfile`.

These steps create a fully functional `rspamd` on macOS, without library error, and without any children segmentation faults in history:
```
# deprecate macports binaries and compilers etc.
export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/opt/local/bin:/opt/local/sbin
git clone https://github.com/rspamd/rspamd.git
mkdir rspamd.build
cd rspamd.build

# cmake *without* MacPorts's -DCMAKE_OSX_ARCHITECTURES="x86_64" and -DCMAKE_OSX_SYSROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk"
cmake ../rspamd -G "CodeBlocks - Unix Makefiles" -DENABLE_LIBUNWIND=ON -DENABLE_LUAJIT=ON -DENABLE_TORCH=ON -DENABLE_SNOWBALL=ON -DENABLE_FANN=ON -DENABLE_PCRE2=ON -DENABLE_GD=ON -DNO_SHARED=ON -DINSTALL_EXAMPLES=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DRSPAMD_USER=_rspamd -DCMAKE_INSTALL_PREFIX=/opt/local -DCONFDIR=/opt/local/etc/rspamd -DMANDIR=/opt/local/share/man -DRUNDIR=/opt/local/var/run/rspamd -DDBDIR=/opt/local/var/lib/rspamd -DLOGDIR=/opt/local/var/log/rspamd -DLIBDIR=/opt/local/lib -DNO_SHARED=ON -DENABLE_SNOWBALL=ON -DCMAKE_OSX_DEPLOYMENT_TARGET="10.14" 1> ~/Downloads/rspamd_cmake.log 2>&1

# simple make
make SHELL='sh -x' -w -j 6 1> ~/Downloads/rspamd_make.log 2>&1
make install
sudo /opt/local/bin/rspamd -u _rspamd -g _rspamd -c /opt/local/etc/rspamd/rspamd.conf 
/opt/local/bin/rspamc -h 127.0.0.1:11334 -P foobar learn_spam < ~/Downloads/Test.eml
```

The MacPorts-added option `-DCMAKE_OSX_ARCHITECTURES="x86_64"` causes the `Symbol not found: _blake2b_blocks_x86` error. The MacPorts-added option `-DCMAKE_OSX_SYSROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk"` causes the `IO read error: unexpected EO” error` when piping to `rspamc`.
