### ISSUE TITLE
[BUG] rspamd macOS build with -DCMAKE_OSX_ARCHITECTURES="x86_64" fails

### ISSUE THREAD

**Issue by essandess** [rspamd/rspamd#2883]
Building `rspamd` with `-DCMAKE_OSX_ARCHITECTURES="x86_64"` causes causes the `Symbol not found: _blake2b_blocks_x86` error when the resulting binary is run.

This is the default setting for the MacPorts `PortGroup cmake`, and although there's a straightforward workaround of rewriting this flag, it's arguably an issue with Rspamd's cmake configuration because setting the flag prevents compilation of the ASM object `src/CMakeFiles/rspamd-server.dir/libcryptobox/blake2/x86-64.S.o` (ironically!). See https://github.com/macports/macports-ports/commit/857c47b3beba97eb7e9934c5bff6e8982bf44307

Example build:

```
# deprecate macports binaries and compilers etc.
export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/opt/local/bin:/opt/local/sbin
git clone https://github.com/rspamd/rspamd.git
mkdir rspamd.build
cd rspamd.build

cmake ../rspamd -G "CodeBlocks - Unix Makefiles" -DENABLE_LIBUNWIND=ON -DENABLE_LUAJIT=ON -DENABLE_TORCH=ON -DENABLE_SNOWBALL=ON -DENABLE_FANN=ON -DENABLE_PCRE2=ON -DENABLE_GD=ON -DNO_SHARED=ON -DINSTALL_EXAMPLES=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DRSPAMD_USER=_rspamd -DCMAKE_INSTALL_PREFIX=/opt/local -DCONFDIR=/opt/local/etc/rspamd -DMANDIR=/opt/local/share/man -DRUNDIR=/opt/local/var/run/rspamd -DDBDIR=/opt/local/var/lib/rspamd -DLOGDIR=/opt/local/var/log/rspamd -DLIBDIR=/opt/local/lib -DNO_SHARED=ON -DENABLE_SNOWBALL=ON -DCMAKE_OSX_DEPLOYMENT_TARGET="10.14" -DCMAKE_OSX_ARCHITECTURES="x86_64" 1> ~/Downloads/rspamd_cmake.log 2>&1

# simple make
make SHELL='sh -x' -w -j 6 1> ~/Downloads/rspamd_make.log 2>&1
make install
sudo /opt/local/bin/rspamd -u _rspamd -g _rspamd -c /opt/local/etc/rspamd/rspamd.conf 
/opt/local/bin/rspamc -h 127.0.0.1:11334 -P foobar learn_spam < ~/Downloads/Test.eml
```

Result:
```
sudo /opt/local/bin/rspamd -u _rspamd -g _rspamd -c /opt/local/etc/rspamd/rspamd.conf
dyld: Symbol not found: _blake2b_blocks_x86
  Referenced from: /opt/local/lib/librspamd-server.dylib
  Expected in: flat namespace
 in /opt/local/lib/librspamd-server.dylib
Abort trap: 6
```

PR references and discussions:
* https://github.com/macports/macports-ports/commit/857c47b3beba97eb7e9934c5bff6e8982bf44307
* https://github.com/macports/macports-ports/commit/bc694d91a1ada1cd36c092488629d8d634db89c2
* https://github.com/rspamd/rspamd/issues/2880
* https://github.com/rspamd/rspamd/issues/2879

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Comment by vstakhov** [comment]
- Doctor, it hurts when I do this thing.
- Don't do this thing.

Won't fix as it's likely linked to assembly, linker, osx and cmake retardness all together. I've experienced something like that in the past and all I remember it was lot's of butt's pain.

Roughly speaking, you *SHOULD NOT* use `-DCMAKE_OSX_ARCHITECTURES="x86_64"` on osx to build rspamd.

**Comment by essandess** [comment]
Thank you, doctor. I won't do that thing. At least it's documented when someone else inevitably does…
