### ISSUE TITLE
Header Name: X-Spamd-Result or X-Rspamd-Result ?

### ISSUE THREAD

**Issue by resec** [rspamd/rspamd#2888]
Hi, I found the name of detail scan header name is X-Spamd-Result, is it on purpose or a typo ?

**Comment by tjharman** [comment]
You know, I'd never noticed this.
Good question!

**Comment by tjharman** [comment]
I spent a bit more time looking at this.
The [milter-headers module](https://rspamd.com/doc/modules/milter_headers.html )clearly lists X-Spamd-Result a number of times, so while I don't know the history of while, it's obviously not a typo.
