### ISSUE TITLE
[BUG] multimap - regex are not work as expected

### ISSUE THREAD

**Issue by sleeplessnight2** [rspamd/rspamd#2894]
**Describe the bug**

### Steps to Reproduce

1. [First Step]
Create a content filter via Multimap.conf
2. [Second Step]
At the Content Filter .map use regex
3. 
Using special Character like "Ä Ü Ö" will detect some Words that never written in the table.. The Flag /u (regex fur unicode) are complete ignored and if i used unicode instead of the character ( **\u00fc** instead ü) the modul seems stop working because it's detecting nothing until the unicode is used.

**Expected behavior**
that regex are regex and operates as expected. It's seems, that the Modul using a own regex interpreter and not the standard like regexr.com works.

### Versions

1.9.2

**Comment by vstakhov** [comment]
It might be related to https://github.com/intel/hyperscan/issues/133
`\u` constructs are from C++/Java and not for regular expressions. `\x` escape should work however.
