### ISSUE TITLE
[BUG] error in squeezed rule ARC_SIGNED

### ISSUE THREAD

**Issue by leofeyer** [rspamd/rspamd#2898]
**Describe the bug**

After updating to version 1.9.3, the following error message appears repeatedly in the log file:

`May 14 09:13:21 m1 rspamd[15081]: <bd93bb>; lua; lua_squeeze_rules.lua:59: error in squeezed rule ARC_SIGNED: /usr/share/rspamd/lualib/lua_auth_results.lua:147: attempt to index field 'dkim_symbols' (a nil value)`

Related change: 2b0bc647ac4be8ccfe455c072f3b3867aceece5b

### Versions

Rspamd daemon version 1.9.3. Ubuntu 16.04.6.

**Comment by uvelokk** [comment]
In my server's logs the same type of bug appeared after upgrade from 1.9.1 to 1.9.2:

`#1861(normal) <51ae86>; lua; lua_squeeze_rules.lua:59: error in squeezed rule MIME_TYPES_CALLBACK: /usr/share/rspamd/plugins/mime_types.lua:1093: attempt to compare string with boolean`

**Comment by leofeyer** [comment]
@uvelokk This issue has already been fixed (see f24be0299381702d7fa5ad4695f1c5debfad78a9). Please don't hijack existing tickets to report unrelated bugs.

**Comment by uvelokk** [comment]
Had bugless code in my mind, not hijacking. Sorry.

**Comment by vstakhov** [comment]
It should be fixed in `1.9.3-2` packages (and in the master branch of course).

**Comment by leofeyer** [comment]
@uvelokk No hard feelings. 😉
