### ISSUE TITLE
[BUG] want_spam = yes --> dkim signing disabled

### ISSUE THREAD

**Issue by bjoe2k4** [rspamd/rspamd#2903]
### Prerequisites
dkim_signing is disabled when want_spam = yes. Deducing from the name, this parameter should only control if messages get rejected by rspamd or not, but from my POV they should be signed regardlessly.

### Steps to Reproduce

1. Assign an email address with want_spam = yes
2. Setup DKIM signing from that domain
3. send an authenticated email
4. Email is not DKIM signed

**Expected behavior**
Email is DKIM-signed 

### Versions
Arch x64
$ rspamd --version
Rspamd daemon version 1.9.3

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by vstakhov** [comment]
This option is preserved for backwards compatibility only. Please use enabled/disabled options.
