### ISSUE TITLE
[BUG] DKIM signing broken since 1.9.3, local sign_headers not accepted

### ISSUE THREAD

**Issue by crankedguy** [rspamd/rspamd#2905]
**Describe the bug**
Since 1.9.3 the DKIM signing is broken which broke all my mailing list compatibility. As you might know your default sign_headers is simply unusable for most mailing lists.
This was no problem with doing an sign_headers entry in local.d/dkim_signing.conf like this :
sign_headers = 'from:subject:date:message-id:\
to:cc:resent-to:resent-cc:resent-from:resent-date:resent-message-id:\
in-reply-to:references:list-id:list-owner:list-unsubscribe:\
list-subscribe:list-post:list-help:list-archive';

This worked perfectly until 1.9.3 because now this is not included anymore. Even not after a restart of rspamd.
I am getting 100s of failed DMARC reports now because my signing looks like this, which exactly reproduces your new default signing introduced with 1.9.3, headers are oversigned etc. etc. which breaks essential functionality of mailing lists
h=from:from:reply-to:subject:subject:date:date:message-id:message-id:
	 to:to:cc:mime-version:mime-version:content-type:content-type:
	 content-transfer-encoding:content-transfer-encoding:
	 in-reply-to:in-reply-to:references:references;

Please reply us with a solution so our local signing policy with sign_headers is accepted again

Thanks!

**Comment by vstakhov** [comment]
There were no changes in this logic to my best knowledge and `sign_headers` should override the default ones. I will check that but in the meantime please fix your mailing list software as it is apparently broken.

**Comment by vstakhov** [comment]
I have checked `sign_headers` option in `local.d/dkim_signing.conf` and it worked fine, so it is not even Rspamd bug. Closing issue.

**Comment by crankedguy** [comment]
Fixing MY mailing list software is somehow impossible. You are still oversigning reply-to unconditionally which is known to break mailman, before you oversigned unconditionally sender which is known to break majordomo. This is nothing to be discussed with me I am afraid but with the developers of the most used mailing list software. Sorry if you misunderstood that one.

**Comment by crankedguy** [comment]
Wow, great one! It worked before 1.9.3 and now is not working anymore so it is not even an rspamd bug...

**Comment by vstakhov** [comment]
Reply-to MUST be oversigned as it opens security breach if it is not. Please think about it. I don't care about broken software even if it is used by millions of ~flies~ users. I see shitty behaviour and say: it is shit. 

As I've said I have just checked `sign_headers` and can tell you it works for me. If it doesn't work for you then you do something wrong.

**Comment by crankedguy** [comment]
It seems that you were offended somehow which was not my intention. So please try to forget the mailing list discussion for this issue, it is not relevant at all.
What is relevant for me is that I have exactly this in dkim_signing.conf :
sign_headers = 'from:subject:date:message-id:
to:cc:resent-to:resent-cc:resent-from:resent-date:resent-message-id:
in-reply-to:references:list-id:list-owner:list-unsubscribe:
list-subscribe:list-post:list-help:list-archive';

and this worked until 1.9.3, but now all my headers in my messages are signed exactly accordingly to the default sign_headers since 1.9.3, so the local sign_headers it seems is not accepted anymore. I don't know what I can do about it to narrow it down why it is not read anymore from my local.d

And thats why I was asking you for help.

**Comment by vstakhov** [comment]
Do you see that setting when running `rspamadm configdump dkim_signing`?

**Comment by vstakhov** [comment]
Also, ARC signing will not use this setting apparently.

**Comment by crankedguy** [comment]
Now I don't know what that was now. My local.d/dkim_signing.conf had a change date from April. I made the sign_headers a one-liner now without line breaks and '\' and restarted/rebooted the server.

configdump shows the correct one now and also with debug logging it seems it is correct, the
rspamd_milter_send_action: change/insert header command pos = 1- "DKIM-Signature" shows the correct one. So it seems to be right.

Yes, ARC signing would have to be done with sign_headers in local.d/arc.conf, right?

Once again, this : "As you might know your default sign_headers is simply unusable for most mailing lists." was not meant as an offence at all. It is just a matter of fact up until 2019 but it was not meant to say rspamd is doing something wrong which mailing lists are doing right. Also the DKIM RFCs are not written a 100% clear on these issues. But in fact it had no relevance for my technical issue at all, so sorry for my maybe unclear wording.

Thanks

**Comment by vstakhov** [comment]
Yes, I understand. The sane mailing lists should either change from and add its own DKIM signature (that's what Rspamd mailing lists are doing) or rely on `List-*` headers and `Reply to List` ability of MUA. The first one is more widespread and the second is somehow not v. reliable.

Not oversigning of `Reply-To` header is dangerous as it is possible to organize some rogue relay without being noticed by manipulating with this header. That's why it is strictly oversigned.
