### ISSUE TITLE
[BUG] Getting false positives in SURBL module

### ISSUE THREAD

**Issue by arvindcool** [rspamd/rspamd#2907]
## Description
    * Since Rspamd by default appends "www" in front of URLs before querying SURBL we are getting some mismatches due to it.

### Steps to replicate
    * Consider my URL is "cnregistry.org.cn", While DNSBL lookup it queries as "www.cnregistry.org.cn.rbl.xxxx.com" which returns as false for URIBL_BLACK.
    * But in Spamassassin, it queries as "cnregistry.org.cn.rbl.xxxx.com" it returns true for URIBL_BLACK.
    * Here even though "cnregistry.org.cn" is listed under URIBL_BLACK I'm not able to identify it using RSPAMD.
### Rspamd log

> 2019-05-20 09:53:42 #14637(controller) <411f23>; surbl; surbl_tree_url_callback: check url http://www.cnregistry.org.cn/ in rbl.xxxxx.com
2019-05-20 09:53:42 #14637(controller) <411f23>; csession; format_surbl_request: request: www.cnregistry.org.cn.rbl.xxxxx.com, dots: 3, level: 10, orig: www.cnregistry.org.cn
2019-05-20 09:53:42 #14637(controller) <411f23>; surbl; make_surbl_requests: send surbl dns request www.cnregistry.org.cn.rbl.xxxxx.com
2019-05-20 09:53:42 #14637(controller) <411f23>; surbl; surbl_dns_callback: <5ce1eea397bd_1d48sfaac4524cc.sidekiq-email-9@automation.xxxxx.com> domain [www.cnregistry.org.cn.rbl.xxxxx.com] is not in surbl rbl.xxxxx.com

### Spamassassin log

> May 20 09:47:59.657 [10094] dbg: uridnsbl: complete_dnsbl_lookup URIBL_BLACK DNSBL:cnregistry.org.cn:rbl.xxxx.com
May 20 09:47:59.657 [10094] dbg: uridnsbl: cnregistry.org.cn . rbl.xxxx.com -> 127.0.0.2, URIBL_BLACK, subtest:2
May 20 09:47:59.658 [10094] dbg: uridnsbl: cnregistry.org.cn . rbl.xxxx.com -> 127.0.0.2, URIBL_BLACK, 7f000002 & 00000002 match
May 20 09:47:59.658 [10094] dbg: uridnsbl: domain "cnregistry.org.cn" listed (URIBL_BLACK): 127.0.0.2

### My Surbl file 

> surbl {
    whitelist = [
        "https://maps.rspamd.com/rspamd/surbl-whitelist.inc.zst",
        "${DBDIR}/surbl-whitelist.inc.local",
        "fallback+file://${CONFDIR}/surbl-whitelist.inc"
    ];
    redirector_hosts_map = "/usr/local/etc/rspamd/redirectors.inc";
    exceptions = [
        "https://maps.rspamd.com/rspamd/2tld.inc.zst",
        "${DBDIR}/2tld.inc.local",
        "fallback+file://${CONFDIR}/2tld.inc"
    ];

    rules {
        "URIBL_MULTI" {
            suffix = "rbl.xxxx.com";
            bits {
                URIBL_BLOCKED = 1;
                URIBL_BLACK = 2;
                URIBL_GREY = 4;
                URIBL_RED = 8;
                URIBL_GOLD = 16;
                URIBL_CUSTOM = 32;
            }
        }
        "DBL" {
            suffix = "xxxxx.dbl.dq.spamhaus.net";
            no_ip = true;
            check_dkim = true;

            ips = {
                # spam domain
               URIBL_DBL_SPAM = "127.0.1.2";
                # phish domain
                URIBL_DBL_PHISH = "127.0.1.4";
                # malware domain
                URIBL_DBL_MALWARE = "127.0.1.5";
                # botnet C&C domain
                URIBL_DBL_BOTNET = "127.0.1.6";
                # abused legit spam
                URIBL_DBL_ABUSE = "127.0.1.102";
                # abused spammed redirector domain
                URIBL_DBL_ABUSE_REDIR = "127.0.1.103";
                # abused legit phish
                URIBL_DBL_ABUSE_PHISH = "127.0.1.104";
                # abused legit malware
                URIBL_DBL_ABUSE_MALWARE = "127.0.1.105";
                # abused legit botnet C&C
                URIBL_DBL_ABUSE_BOTNET = "127.0.1.106";
                # error - IP queries prohibited!
                URIBL_DBL_PROHIBIT = "127.0.1.255";
            }
        }
    }
}

**Comment by vstakhov** [comment]
Your assumptions are wrong. Rspamd doesn't append anything like `www` to urls checked. Your problem is that you are likely modifying stock config files and don't read Rspamd logs afterwards.

**Comment by arvindcool** [comment]
Sorry I misunderstood that appending part, My problem is Rspamd just queries the full URL ie.. if the URL in the message is "www.cnregistry.org.cn", it looks up as "www.cnregistry.org.cn.rbl.xxxx.com", But I am getting URIBL_BLACK result only for the query "cnregistry.org.cn.rbl.xxxx.com". 
The correct approach must be RSPAMD should trim the "www" part before looking up RBL.

**Comment by arvindcool** [comment]
If the message

> Web: =

www.cnregistry.org.cn
 =
I am not getting proper result. Where as if i change the message in eml to

> Web: =

cnregistry.org.cn
 =

I am getting URIBL_BLACK in Rspamd result now

**Comment by vstakhov** [comment]
The answer is: don't modify stock configs.

**Comment by arvindcool** [comment]
I don't think it's a config issue. "www." should be trimmed before sending it to URIBL from RSPAMD for correct results.

**Comment by vstakhov** [comment]
I don't care of what do you think: I **know** it is a config error caused by a wrong 2tld file.

**Comment by vstakhov** [comment]
To be clear, check that `rspamadm configdump options.url_tld` points to an existing file. In Linux, it should be `/usr/share/rspamd/effective_tld_names.dat` and **not** something in plugins directory. Also check https://rspamd.com/doc/migration.html#migration-to-rspamd-190

**Comment by arvindcool** [comment]
OK, I will revert my Rspamd build and check again. Thanks.

**Comment by arvindcool** [comment]
The issue has been fixed now, I have been using PLUGINSDIR in options file to defile tld_names.Now after pointing it to correct path its working fine. Thanks for your help. Much appreciated!!
