### ISSUE TITLE
[BUG] WP_COMPROMISED rule is not triggered

### ISSUE THREAD

**Issue by milenevtimov** [rspamd/rspamd#2908]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
WP_COMPROMISED rule is not triggered, when body of email contains relevant url.
Regex of the rule does not seems to match urls containing /wp-includes/.

### Steps to Reproduce

1. Scan email containing url with /wp-includes/

**Expected behavior**
Detect urls containing /wp-includes/

### Versions
1.9.3
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by vstakhov** [comment]
This issue is useless without email samples to reproduce it.

**Comment by milenevtimov** [comment]
Sorry, here is a sample:

[sample.txt](https://github.com/rspamd/rspamd/files/3198542/sample.txt)

**Comment by vstakhov** [comment]
But this regexp indeed don't matches, you can check it by yourself: https://regex101.com/r/VPt8av/1

**Comment by milenevtimov** [comment]
Yes, i've already tested it, but I was thinking that this rule is intended to catch urls like that in the sample.
If that's not the case, sorry for the false report.
