### ISSUE TITLE
[BUG] Authenticated user and sign_networks

### ISSUE THREAD

**Issue by boboivancich** [rspamd/rspamd#2909]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

As a consequence of commit 530e595772bf0a1aa9d8be715da6ab4987d4ecae we're having an issue with our authenticated users not being any more eligible for signing, because their IP addresses are not included in sign_networks map.

### Steps to Reproduce

1) Enable logging in logging.inc
```
debug_modules = ["dkim_signing"];
```
2) Configure sign_networks in dkim_signing.conf
```
sign_networks = ["127.0.0.1/32"];
```
3) Configure domain signature
```
signing_table = ["*.mydomain.com mydomain.com"];
key_table = ["mydomain.com %:default:/etc/rspamd/dkim_keys/%.default.key"];
```
4) Send email as authenticated user "myuser@mydomain.com" whose IP is *not* in included in sign_networks.

**Expected behavior**

The mail gets signed.

The log includes:
```
...(rspamd_proxy)...; dkim_signing; lua_dkim_tools.lua:222: signing_table: found entry for myuser@mydomain.com: mydomain.com
...(rspamd_proxy)...; dkim_signing; lua_dkim_tools.lua:276: perform dkim signing for mydomain.com, selector=default, domain=mydomain.com, key file=/etc/rspamd/dkim_keys/mydomain.com.default.key
...(rspamd_proxy)...; dkim_signing; dkim_signing.lua:112: using key "/etc/rspamd/dkim_keys/mydomain.com.default.key", use selector "default" for domain "mydomain.com"
```

**Actual behaviour**

The mail doesn't get signed.

The log includes:
```
...(rspamd_proxy)...; dkim_signing; lua_dkim_tools.lua:145: user is authenticated
...(rspamd_proxy)...; dkim_signing; lua_dkim_tools.lua:209: signing_table: sign networks specified but IP is not from that network, skip signing
```

### Versions

Rspamd daemon version 1.9.3

OS="Ubuntu 18.04.2 LTS"

### Additional Information

The following patch resolves the issue:
```
--- lua_dkim_tools.lua	2019-05-21 09:05:47.110846069 +1200
+++ lua_dkim_tools.lua.new	2019-05-20 15:46:23.777470133 +1200
@@ -205,7 +205,7 @@
 
   if settings.signing_table and (settings.key_table or settings.use_vault) then
     -- OpenDKIM style
-    if settings.sign_networks and not is_sign_networks then
+    if settings.sign_networks and not is_sign_networks and not auser then
       lua_util.debugm(N, task,
           'signing_table: sign networks specified but IP is not from that network, skip signing')
       return false,{}
```

**Comment by vstakhov** [comment]
Yes, you are right thanks for noticing that.

**Comment by vstakhov** [comment]
Could you please test my version of the fix?

**Comment by boboivancich** [comment]
It works like a charm!

Thank you very much Vsevolod.
