### ISSUE TITLE
[BUG] History reset doesn't clear the most recent entry

### ISSUE THREAD

**Issue by foutrelis** [rspamd/rspamd#2910]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

This is a followup from https://github.com/rspamd/rspamd/issues/2346#issuecomment-406791511 — clicking `Reset` on the History page always leaves behind the latest entry. Perhaps it's an off-by-one in the [handler code](https://github.com/rspamd/rspamd/blob/6943c3c3a4/src/controller.c#L1700)?

### Steps to Reproduce

1. Visit the History page in the controller and check that it's not empty
2. Click `Reset`
3. Notice that one entry is still showing after the reset

**Expected behavior**

I would expect that the history list would be completely empty.

### Versions

I'm using Rspamd as part of mailcow and it's at version `1.9.3-2~bionic`.

**Comment by moisseev** [comment]
The problem still remains for redis history.
