### ISSUE TITLE
[BUG]  Domain in the email address inside message is not considered for URIBL

### ISSUE THREAD

**Issue by rspamd-internal** [rspamd/rspamd#2913]
**RSPAMD VERSION: 1.9.3**
**Problem:**
                 When there is a email address in a message, the domain in the email should be considered as a URL and checked against the URIBL blacklists.
                  It is a valid case since the user can reply his confidential data to the email which has a blacklisted domain and cause a security breach.

 **Steps to reproduce:**
                 Consider this message "Email: sample@generalbrand.world" is in the body of the email.I have ensured "generalbrand.world" is present in the URIBL_BLACK using SPAMASSASSIN. But rspamd does not check this against the URIBL blacklist.

**Spamassassin Log:**
> May 30 11:40:14.392 [32724] dbg: uridnsbl: complete_dnsbl_lookup URIBL_BLACK DNSBL:generalbrand.world:rbl.xxxx.com
May 30 11:40:14.392 [32724] dbg: uridnsbl: generalbrand.world . rbl.xxxx.com -> 127.0.0.2, URIBL_BLACK, subtest:2
May 30 11:40:14.392 [32724] dbg: uridnsbl: generalbrand.world . rbl.xxxx.com -> 127.0.0.2, URIBL_BLACK, 7f000002 & 00000002 match
May 30 11:40:14.392 [32724] dbg: uridnsbl: domain "generalbrand.world" listed (URIBL_BLACK): 127.0.0.2

**Comment by heraklit256** [comment]
Well, I think this _is_ fixed with the commits mentioned above. :-)

**Comment by rspamd-internal** [comment]
Thanks for the update. I am closing the issue now.
