### ISSUE TITLE
[BUG] ARC signing and 'rewrite subject'

### ISSUE THREAD

**Issue by mguesdon** [rspamd/rspamd#2914]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:

When doing:
      task:set_metric_subject("[ADDEDTAG] %s")
      task:set_pre_result('rewrite subject')
in a module, ARC signing still use original subject.

### Steps to Reproduce

Set just 3 symbols to apply in settings:
    symbols_enabled = ["ARC_CALLBACK","ARC_SIGNED","ALTER_MAIL"];

ALTER_MAIL is a symbol for a callback which just do:
      task:set_metric_subject("[ADDEDTAG] %s")
      task:set_pre_result('rewrite subject')
between ARC check and ARC signing

Send a mail for test with "MySubject" as subject

ARC signing should use rewritten subject: "[ADDEDTAG] MySubject" but it use original subject "MySubject".
In the delivered mail the subject is good: "Subject: [ADDEDTAG] MySubject"

Logs:
2019-05-30 20:18:57 #24736(rspamd_proxy) <079b93>; proxy; rspamd_add_passthrough
_result: <5cf01e8f.5jezt0Ab1/PvG6jm%mgfrom@xxxx>: set pre-result to 'rewrite subject' (no score): 'unknown reason' from Unknown lua(1)
....
2019-05-30 20:18:57 #24736(rspamd_proxy) <079b93>; arc; lua_dkim_tools.lua:354:
use domain(header) for signature: xxxx
...
2019-05-30 20:18:57 #24736(rspamd_proxy) <079b93>; dkim; rspamd_dkim_canonize_header_relaxed: update signature with header: subject:MySubject

### Versions

1.9.3 on CentOS 7

**Comment by vstakhov** [comment]
Why do you sign spam?

**Comment by mguesdon** [comment]
Good question :-)
In fact it's for adding some visible information to the recipient people.

**Comment by mguesdon** [comment]
I really think we should allow good ARC signing with modified subject...

**Comment by mguesdon** [comment]
ARC signing is pretty useless if it can't rightly sign modified email... :)
