### ISSUE TITLE
[BUG] rspamc learn_spam is unusably slow - several seconds per message

### ISSUE THREAD

**Issue by shlomif** [rspamd/rspamd#2918]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

[BUG] rspamc -v learn_spam is unusably slow - several seconds per message . When I run it on a folder with thousands of messages, it does not finish. sa-learn is fast enough. `iotop` shows me that rspamd is writing many megabytes per second to disk at that time.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**

### Versions

`Rspamd daemon version 1.9.4` on mageia linux v7 x86-64 on:

```


My primary machine is a desktop machine with a:

    An Intel Core i3 CPU (x86-64).
    8 GB of RAM.
    Intel Corporation Sandy Bridge Integrated Graphics Controller (rev 09)
    A 2 TB hard-disk.
    A 21″ Wide LCD Screen by LG.
    Intel Corporation Cougar Point High Definition Audio Controller.
    Intel Corporation 82579V Gigabit Network Connection.


```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by vstakhov** [comment]
Are you using sqlite3 backend for statistics? If yes, don't do it.

**Comment by shlomif** [comment]
@vstakhov : thanks for the hint. I used it because it was the default. After changing to redis per https://rspamd.com/doc/configuration/statistic.html it seems much faster.

**Comment by vstakhov** [comment]
It was default just for compatibility. I plan to deprecate it completely and move default to Redis in the next release.
