### ISSUE TITLE
[Feature] Use Rspamd to scan normal webform message

### ISSUE THREAD

**Issue by yellow1912** [rspamd/rspamd#2919]
I wonder if Rspamd can be used as a normal spam detection service that can take any kind of message and return a spam score, the message can be passed with additional information such as Sender IP and whatever additional information that can be helpful to detect spams?

Something like this:

http://www.devnetwork.net/viewtopic.php?f=14&t=93582

**Comment by moisseev** [comment]
It is exactly what `rspamc` does.
