### ISSUE TITLE
[BUG] Ubuntu Trusty package broken

### ISSUE THREAD

**Issue by rekcuFniarB** [rspamd/rspamd#2923]
Ubuntu Trusty package has unmet dependency. Current version of rspamd available in the repo is 1.9,4, it depends on libstdc++6 >= 4.9, but version of libstdc++6 available in trusty repos is 4.8.4

I had to manually download [deb package of rspamd version 1.8.3](https://rspamd.com/apt-stable/pool/main/r/rspamd/rspamd_1.8.3-1~trusty_amd64.deb) (this is last version which is built against libstdc++6 v4.8) and install with dpkg.

**Comment by vstakhov** [comment]
Ubuntu trusty is no longer supported (even by Ubuntu).

**Comment by vstakhov** [comment]
You can workaround that I suppose: 

```
# cat /etc/apt/sources.list.d/llvm.list
deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main
deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main

# Also add the following for the appropriate libstdc++
deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main
```

Then you'd be able to install Rspamd.

**Comment by rekcuFniarB** [comment]
Thanks, but I already solved my problem just installing older package manually. I don't thik that installing newer libstdc++ libraries is a good idea, it may break other installed packages.

The better solution would be just freeze rspamd version at 1.8.3 in Trusty repos.

**Comment by vstakhov** [comment]
I don't think that new libstdc++ would clash with anything else in system due to semver.
