### ISSUE TITLE
[BUG] SVG graphs not displayed.

### ISSUE THREAD

**Issue by gorn** [rspamd/rspamd#2925]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Web backend returns html pages with embeded SVG, which does not display in Firefox (and other broxsers).

Maybe it is connected to the fact, that web backend returns html pages with wrong `Content-Type: text/html ` pages are in HTML5 so it should be `Content-Type: application/xhtml+xml`. According to  SVG tests explained here http://philarcher.org/diary/svgtest/ it could mean that standards-complaint browsers will not displlay SVG graphs. 

### Steps to Reproduce

on server with rspamd run `wget -S -O - localhost:11334 > /dev/null`

**Expected behavior**
Content-Type: should be application/xhtml+xml

### Versions

Rspamd daemon version 1.8.1
Debian versions 9.9
Linux version 4.9.0-8-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #1 SMP Debian 4.9.144-3.1 (2019-02-19)

**Comment by moisseev** [comment]
The article you are referring to is actually about SVG in **X**HTML. I believe the correct content type for HTML5 is `text/html`.
It is likely setup related, e.g. misconfigured reverse proxy or something.

**Comment by gorn** [comment]
I doubt that the reverse proxy is wrongly setup - everything on pages works except the svg part.

**Comment by nd1012** [comment]
The same here. I setup rspamd on a new Debian 10 server, using the stable apt version from rspamd.com about one week ago. A few days ago rspamd was updated - since then no graphs are visible. I tried to override the content type using the nginx configuration, but it didn't help. I also get a 403 error in the browser debugger when a JS wants to use data from https://antispam3.softengine.de/rspamd/stat or https://antispam3.softengine.de/rspamd/auth (request succeed, but using the response was forbidden in Edge). Then I see more JS errors:

```
Object doesn't support property or method 'arc'
d3pie.min.js (8,19901)

Object doesn't support property or method 'scaleTime'
d3evolution.min.js (4,777)

Object doesn't support property or method 'arc'
d3pie.min.js (8,19901)
```
For me the frontend works, too, except the SVG images are not displayed.

**Comment by nd1012** [comment]
The problem has been solved for me with the update to version 1.9.4-1~buster :) Thanks a lot!

**Comment by vstakhov** [comment]
Never ever use packages for Rspamd provided by your Linux distributive: they are terribly outdated, not supported (at least not supported by me!) and are usually built not in the same matter that I recommend (especially in terms of performace). Use the packages provided by Rspamd project itself.

**Comment by gorn** [comment]
I understand your reasoning and motivation behind this and thans for your great work.

I would love to install all packages we use on servers from upstream, however it is not realistically possible. I use debian distribution, because it enables me to maintain servers in managable way.

I understand that you see prepackaged versions as PITA, but you may very well see debian as a good advertisement for your package. Peoplecan test it easily and if they have need and resources, they will come to you directly.

**Comment by gorn** [comment]
Just for the record - version  1.9.4 works for me as well.
