### ISSUE TITLE
[BUG] Modules execution order

### ISSUE THREAD

**Issue by mguesdon** [rspamd/rspamd#2930]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:

**Describe the bug**

When adding some symbols dependencies, we get "cyclic dependencies: maximum check level 20 exceed when checking dependencies for..."

### Steps to Reproduce

register a symbol with dependencies wich should be executed early:
	 local id = rspamd_config:register_symbol({
						     name = 'OXYMIUM_SENDER_ALLOW',
						     type = 'callback',
						     callback = sender_allowed_cb,
						     priority = -10,
						     no_squeeze = true, --mandatory for sync redis
						     flags = 'prefilter,coro,fine,ignore_passthrough'     --mandatory for DNS requests
						  })       
	 --before these ones
	      rspamd_config:register_dependency('DMARC_CALLBACK','OXYMIUM_SENDER_ALLOW')
	 rspamd_config:register_dependency('DKIM_SIGN','OXYMIUM_SENDER_ALLOW')

	 -- force even if set_pre_result
	 rspamd_config:add_symbol_flags('DKIM_SIGN',{'ignore_passthrough'})
	 rspamd_config:add_symbol_flags('DKIM_SIGNED',{'ignore_passthrough'})
	 rspamd_config:add_symbol_flags('DMARC_CALLBACK',{'ignore_passthrough'})

and a second with should be executed very later (after dmarc stuff,..)
	 local id = rspamd_config:register_symbol({
						     name = 'OXYMIUM_FINALIZE',
						     type = 'callback',
						     callback = finalize_cb,
						     priority = -10,
						     flags = 'coro,fine,ignore_passthrough', --always execute
						     no_squeeze = true --mandatory for sync redis
						  })       
	 --after this one
	 rspamd_config:register_dependency('OXYMIUM_FINALIZE','DMARC_CALLBACK')
	 --before this one
	 rspamd_config:register_dependency('ARC_SIGNED','OXYMIUM_FINALIZE')

### Expected behavior

OXYMIUM_FINALIZE should be evaluated after DMARC stuff and before ARC signing.
Here is it evaluated before dmarc stuff is finished.
(see logs).

If I remove "rspamd_config:register_dependency('ARC_SIGNED','OXYMIUM_FINALIZE')" it works well.

### Versions

rspamd 1.9.4, centos 7.

### Additional Information

[pb.log](https://github.com/rspamd/rspamd/files/3303079/pb.log)

**Comment by vstakhov** [comment]
Could you please enable debugging for `symcache` module and check the logging output?

**Comment by mguesdon** [comment]
I've enabled them with debug_modules = ["symcache"... See pb.log

**Comment by vstakhov** [comment]
You cannot add dependencies between filter classes (e.g. filter and prefilter). In 2.0 I have removed lua_squeeze, so this picture might be slightly different. You are likely introducing cyclic dependencies that are detected on init phase (so logs for messages checking are almost useless).

**Comment by mguesdon** [comment]
OK, thank you !

I've:
- removed dependencies
- moved prefilter flag to type for the first module
- configured second module as postfilter
and it works !
ARC signing is done before my second module which is still a problem but anyway I have to disable ARC for the moment because of #2920 and #2914.
