### ISSUE TITLE
[BUG] Lua REDIS error ?

### ISSUE THREAD

**Issue by aTanW** [rspamd/rspamd#2932]
### Steps to Reproduce

Just bootup on busy system

### Versions

1.9.0

### Additional Information

Never seen before.

Before that (from log) scripts are successfully (without any messages) loaded to redis.

Just found in log:

2019-06-20 01:01:40 #71(controller) rspamd_lua_execute_lua_subprocess: call to subprocess failed: /usr/share/rspamd/lualib/nn/Container.lua:67: 
In 1 module of nn.Sequential:
/usr/share/rspamd/lualib/nn/NaN.lua:50: NaN found in gradOutput of module :
nn.NaN(1) @ nn.Identity
stack traceback:
        [C]: in function 'error'
        /usr/share/rspamd/lualib/nn/NaN.lua:50: in function </usr/share/rspamd/lualib/nn/NaN.lua:46>
        [C]: in function 'xpcall'
        /usr/share/rspamd/lualib/nn/Container.lua:63: in function 'rethrowErrors'
        /usr/share/rspamd/lualib/nn/Sequential.lua:58: in function 'updateGradInput'
        /usr/share/rspamd/lualib/nn/StochasticGradient.lua:37: in function 'train'
        /usr/share/rspamd/plugins/neural.lua:676: in function </usr/share/rspamd/plugins/neural.lua:661>
        [C]: in function 'spawn_process'
        /usr/share/rspamd/plugins/neural.lua:685: in function 'callback'
        /usr/share/rspamd/lualib/lua_redis.lua:921: in function </usr/share/rspamd/lualib/lua_redis.lua:915>

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.; trace: [1]:{[C]:-1 - error [C]}; [2]:{/usr/share/rspamd/lualib/nn/Container.lua:67 - rethrowErrors [Lua]}; [3]:{/usr/share/rspamd/lualib/nn/Sequential.lua:58 - updateGradInput [Lua]}; [4]:{/usr/share/rspamd/lualib/nn/StochasticGradient.lua:37 - train [Lua]}; [5]:{/usr/share/rspamd/plugins/neural.lua:676 - <unknown> [Lua]}; [6]:{[C]:-1 - spawn_process [C]}; [7]:{/usr/share/rspamd/plugins/neural.lua:685 - callback [Lua]}; [8]:{/usr/share/rspamd/lualib/lua_redis.lua:921 - <unknown> [Lua]};

**Comment by vstakhov** [comment]
Unsupported Rspamd version.
