### ISSUE TITLE
[BUG] BROKEN_HEADERS due to MIME preamble

### ISSUE THREAD

**Issue by rseichter** [rspamd/rspamd#2933]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
I recently noticed messages being flagged with the BROKEN_HEADERS symbol and used `rspamadm mime modify` to figure out what Rspamd dislikes about them. The resulting differences boil down to this:
```
$ rspamadm mime modify original.eml > rspamadm-output.eml
$ diff original.eml rspamadm-output.eml
80,81d79
< This is a multi-part message in MIME format
<
```
This "MIME preamble" has been common for years, so why does Rspamd consider this broken? Why is the default score for BROKEN_HEADERS a +10, which seems excessively high to me? As a minor issue, the name BROKEN_HEADERS is somewhat misleading, given that Rspamd is processing the message body at this time.

### Steps to Reproduce

I can provide sample messages, but since they need to be obfuscated first, I hope the description above is sufficient. Let me know if you do need samples.

**Expected behavior**
Rspamd should not flag messages with a MIME preamble with BROKEN_HEADERS.

### Versions

Rspamd 1.9.0 on GNU/Linux.

**Comment by vstakhov** [comment]
1. You are using unsupported version: please bear in mind that I usually immediately close all issues about unsupported versions without any further feedback.

2. Your issue is not related to mime preamble of course. `mime modify` does not preserve it indeed but this is unrelated to `BROKEN_HEADERS`. Please see more details here: https://github.com/rspamd/rspamd/issues/2836 especially my last comment.

**Comment by rseichter** [comment]
@vstakhov While I know it is not your doing, but 1.9.0 is the release flagged as "stable" for Gentoo Linux. I can update if you have lately made changes in the relevant area. Released in March and already unsupported, seems a bit odd.

I had read #2836 but don't see how this applies here? Other than stripping the preamble, rspamadm does not make any changes, so how is is problem unrelated? Like I said, I can provide sample messages, although it would take some preparation. Among them are messages generated by Thunderbird, in no way related to mailing lists, and Rspamd is the only scanner complaining.

**Comment by vstakhov** [comment]
Then please seek advice from your Gentoo maintainer, I'm done here.

**Comment by rseichter** [comment]
@vstakhov I have reserved time to build Rspamd from source tomorrow.

Generally speaking, you seriously need to work on your attitude. Past issue comments and mailing list postings of yours have been bad enough, but "I'm done here" is reaching new heights of arrogance. Rspamd is far from perfect, so dealing with the shortcomings is part of the package.

**Comment by vstakhov** [comment]
Generally speaking, who are you to teach me? 

If you don't like Rspamd then just don't use it: it's pretty simple, isn't it?

**Comment by vstakhov** [comment]
Regarding your issue, as I've said above, there is no issue with mime preamble - at least to my best knowledge. 

If you really want to talk about the issue and not about my behaviour or about Rspamd perfectness, then please provide a case where BROKEN_HEADERS is issued **with** mime preamble and, **at the same time**, missing when this preamble is removed.

**Comment by rseichter** [comment]
I am somebody who has worked in this business for over 30 years, who is an influencer for all his customers (which include banks, insurances, and a federal ministry) as far as software selection goes, and who knows that politeness costs nothing. Rspamd comes free of charge, which I appreciate, and I don't expect you to solve my problems for me, but I _do_ expect common courtesy in communication related to open source endeavours, on GitHub or elsewhere.

I'll let you know when I have run more tests. It might take a bit to get the samples

**Comment by vstakhov** [comment]
Well, I had a hard day today and I'm sorry if my tone was too rough or impolite. 

However, I **really** don't have enough resources to support all previous versions of Rspamd as I have to manage the whole project alone. Hence, I imply, and it is clearly stated in the issue template, that you should check if there is a fix for your issue in the master branch.

It is also suggested to create a small test, I don't need any irrelevant content from your message: just a simple case where this issue reproduced. In your case you can remove all parts content (leaving merely mime structure) and all irrelevant headers excluding Content-Type. Please keep all newlines as is though:

```
Content-Type: multipart/alternative; boundary=XXXX

Mime-Preamble
--XXXX
Content-Type: text/plain


--XXXX
Content-Type: text/html


--XXXX--
```

Something like this one...

**Comment by rseichter** [comment]
> Well, I had a hard day today and I'm sorry if my tone was too rough or impolite.

Accepted. We've all experienced these days, and the short fuse they result in. I'm actually very tired myself now, so I will look into the test you suggested tomorrow, when the newly built Rspamd is ready.

**Comment by andryyy** [comment]
> Am 20.06.2019 um 21:10 schrieb Ralph Seichter <notifications@github.com>:
> 
> I am somebody who has worked in this business for over 30 years, who is an influencer for all his customers (which include banks, insurances, and a federal ministry)
> 
Why?

**Comment by rseichter** [comment]
One customer has since declined permission to use affected messages anywhere outside his organisation, citing privacy concerns. The second has still not replied to my request.

**Comment by rseichter** [comment]
Still no news regarding the second customer. I'll close this issue for now and continue trying to cut through the red tape to obtain samples, but I don't know how long that might take.
