### ISSUE TITLE
[BUG] rspamd_config:add_condition not working for symbol CLAM_VIRUS

### ISSUE THREAD

**Issue by csazku** [rspamd/rspamd#2936]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Condition added for the symbol `CLAM_VIRUS` get ignored.

### Steps to Reproduce

1. In `/etc/rspamd/rspamd.local.lua` added the line `rspamd_config:add_condition("CLAM_VIRUS", function(task) return false end)`
2. Sent an email containing virus to a test email account
3. `CLAM_VIRUS` still shows up in the results

**Expected behavior**
`CLAM_VIRUS` is not added to the spam tests

### Versions

Rspamd daemon version 1.9.4

### Additional Information

Tried adding the same condition to the `ASN` symbol, that works fine.
Also tried adding a condition to a custom symbol defined in a map, it gets ignored as well.

**Comment by vstakhov** [comment]
There was some issue about adding conditions to virtual symbols. Settings should work better at lower cost and will work with virtual symbols from Rspamd 2.0.

**Comment by csazku** [comment]
My goal is to disable the `CLAM_VIRUS` symbol if the recipient domain is found in a map (just like the example in the documentation), can this be done somehow?
