### ISSUE TITLE
[Feature] Email has mostly absolute image

### ISSUE THREAD

**Issue by robertboyl** [rspamd/rspamd#2952]
Hi guys

This major phishing passed by undetected. Cant Rspamd have some test to score emails that have mostly an image? This email like 90%+ is an absolute image...

See https://pastebin.com/2GUgjxEj

Thanks.

**Comment by vstakhov** [comment]
Of course, it can. Do you offer yourself as a volunteer to write this sort of detection or do you look for a free work force?

**Comment by robertboyl** [comment]
Hello, Vsevolod

When I asked if it can, if its already possible somehow. Of course Im aware if not, software can be improved for that.

Sorry, unfortunately I don't have the knowledge to help program it. It's just a suggestion that can benefit everyone IMHO, if by any chance anyone can help. I will try to check with colleagues that are programmers, if they can help possibly.

Here's 1 more example, a phishing that caused false negative. Mostly absolute image.

https://pastebin.com/5cUZqKpz

Thank you.
