### ISSUE TITLE
[BUG] Debian/aarch64 Build - Lua not found, lua support is required

### ISSUE THREAD

**Issue by TCB13** [rspamd/rspamd#2953]
Hello,

I'm trying to compile rspamd for aarch64 (RK3399) by following the instructions available at https://rspamd.com/downloads.html. Unfortunately it doesn't seem to work:

```
root@mx10:/mnt/SU1/rspam/rspamd.build# cmake ../rspamd                                                                                                                           -- Hyperscan support is possible only for x86_64 architecture
-- Configuring for Linux
-- Check for luajit 5.1
-- Fallback from luajit to plain lua
-- Check for lua 5.1
CMake Error at CMakeLists.txt:616 (MESSAGE):
  Lua not found, lua support is required
```
Now, as you can see lua is installed:
```
root@mx10:/mnt/SU1/rspam/rspamd.build# lua -v                                                                                                                                    Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
```
Is this related to my architecture or am I missing something?

```
Distributor ID: Debian
Description:    Debian GNU/Linux 9.9 (stretch)
Release:        9.9
Codename:       stretch
```

Thank you.

**Comment by lhorace** [comment]
Hello there,

You likely just need the dev version of lua. I don't have Debian readily handy here but I suspect it would be `liblua-dev`.

Good luck.

**Comment by TCB13** [comment]
@lhorace thank you for the tip. Here is the complete list of packages I had to install to make it work: ` apt install ragel libevent-dev lua5.1 liblua5.1-dev cmake sqlite3 libmagic-dev libsqlite3-dev  libicu-dev`.

**Comment by vstakhov** [comment]
Learn your system's command: `apt-get build-dep`

**Comment by TCB13** [comment]
Eventually I decided to get `luajit` also by adding testing to my `sources.list`:
````
deb http://ftp.fr.debian.org/debian/ testing main contrib non-free
````
And then:
````
apt install ragel libevent-dev lua5.1 liblua5.1-dev cmake sqlite3 libmagic-dev libsqlite3-dev libicu-dev luajit libluajit-5.1
````
