### ISSUE TITLE
[BUG] rebuilding rspamd-1.9.4 for for centos7

### ISSUE THREAD

**Issue by mguesdon** [rspamd/rspamd#2963]
### Prerequisites

**Describe the bug**

centos/rspamd.spec seems out of date.
Is it possible to publish rspamd.spec used to generate rspamd-1.9.4 ?
May be it can also help to put src rpm on https://rspamd.com/rpm-stable/

**Comment by mguesdon** [comment]
Seems still out-of-date:  "Version:        1.1.0"

**Comment by stephdl** [comment]
we use a spec file to build rspamd for ARM, maybe it could help 

https://github.com/NethServer/rspamd-spec
