### ISSUE TITLE
[BUG] (some) mlmmj mailing lists not recognized

### ISSUE THREAD

**Issue by wrosenauer** [rspamd/rspamd#2964]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Mailing list (generic) is not identified correctly for mlmmj lists.
(I found an old issue where it should have been integrated into the LUA script.)

It works for mailman lists though.

Here are snippets from the relevant list headers which should make it possible to identify that it's a list post:

Precedence: bulk
Mailing-List: contact opensuse-factory+help@opensuse.org; run by mlmmj
X-Mailinglist: opensuse-factory
List-Post: <mailto:opensuse-factory@opensuse.org>
List-Help: <mailto:opensuse-factory+help@opensuse.org>
List-Subscribe:  <mailto:opensuse-factory+subscribe@opensuse.org>
List-Unsubscribe:  <mailto:opensuse-factory+unsubscribe@opensuse.org>
List-Owner: <mailto:opensuse-factory+owner@opensuse.org>
List-Archive: <http://lists.opensuse.org/opensuse-factory/>

List-Id is indeed missing from this setup apparently.

### Steps to Reproduce

1. receive mail from a mlmmj mailing list
2. observe the symbols

**Expected behavior**
The MAILLIST (generic I guess) should appear in the received/scanned mail.

### Versions

ds9:~ # rspamd --version
Rspamd daemon version 1.9.4
on openSUSE Leap 15.1 (x86_64, KVM)

**Comment by vstakhov** [comment]
It seems that `List-ID` is a requested header :( I will think about it as it seems to be not right. I would appreciate if you can point me to some archives with relevant messages so I could study them and improve this plugin.
