### ISSUE TITLE
[BUG] Sorting of errors by date in WebUI 

### ISSUE THREAD

**Issue by dimejo** [rspamd/rspamd#2965]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
The errors displayed on the history site of rspamd's WebUI are not properly sorted by date if there are errors from more than 1 month.
![Screenshot_2019-07-08_rspamd](https://user-images.githubusercontent.com/25005220/60811679-18814b80-a190-11e9-85f4-f67d83571a4c.png)

### Steps to Reproduce
No steps required.

### Versions
CentOS Linux release 7.6.1810 (Core)
3.10.0-957.21.3.el7.x86_64 GNU/Linux
Rspamd daemon version 1.9.4

**Comment by moisseev** [comment]
@dimejo Would you please test the fix?

**Comment by dimejo** [comment]
Unfortunately those 2 entries from June are gone now. Is there an easy way to add entries besides messing with date/time?

**Comment by moisseev** [comment]
I have no idea how to do that or if it is possible. Let's hope the fix is correct.

**Comment by dimejo** [comment]
I've setup a reminder to check the fix at the start of August and will report back if this is definitely fixed.

**Comment by z-jun** [comment]
Above fix is'n complete. Here is missing part:

```
mail ~ # diff /usr/share/rspamd/www/js/app/history.js /usr/share/rspamd/www/js/app/history.js.orig
411c411
<                     {sorted:true, direction:"DESC", name:"ts", title:"Time", style:{"font-size":"11px", "width":300, "maxWidth":300}, sortValue: function (val) { return Number(val.options.sortValue);}},
---
>                     {sorted:true, direction:"DESC", name:"ts", title:"Time", style:{"font-size":"11px", "width":300, "maxWidth":300}},

```

Patch tested on version 2.7.
