### ISSUE TITLE
[Feature] Rewrite subject without triggering is_spam

### ISSUE THREAD

**Issue by derryaire** [rspamd/rspamd#2972]
## Summary

It would be useful to prepend an [Unscanned] to a subject without the action "rewrite subject" when getting encrypted mails which cannot be scanned to inform the user.

## Motivation

Our users get a lot accounting reports in encrypted zip files and a seperate password sent out on paper (this is Germany after all). So I allowed those mails in settings.conf for a specific sender and ip range.

## Describe alternatives you've considered

I tried an lua script to rewrite my subject but the only thing I got is set_metric_subject() together with set_pre_result('rewrite subject')  which triggers "rewrite subject" obviously and is filtered into Junk automatically by "X-Spam-Status = Yes".

## Additional context

Is there a function I could use besides set_pre_result('rewrite subject') without triggering is_spam?

**Comment by vstakhov** [comment]
I suppose that could be done with this method: https://rspamd.com/doc/lua/rspamd_task.html#m1bbbc
