### ISSUE TITLE
[BUG] Ratelimit whitelisted_user exception not working

### ISSUE THREAD

**Issue by friizer** [rspamd/rspamd#2982]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Ratelimit whitelised_user is not working
Created file /etc/rspamd/local.d/ratelimit.conf
    rates {
      user = {
        selector = 'user.lower';
        bucket =       [
      {
        burst = 50;
        rate = "10 / 1hour";
      },
      {
        burst = 3;
        rate = "1 / 1min";
      }]

      }
    }
whitelisted_user = { "info@domain.com" = "info@domain.com" }
// also tried this
//whitelisted_user = "info@domain.com"

### Steps to Reproduce

1. debug_modules = ["ratelimit"]
2. sent 4 mails with auth in 1 minute
3. in log found 
2019-07-16 10:17:23 #17528(normal) <067849>; lua; ratelimit.lua:610: ratelimit "user(info@domain.com)" exceeded, (3 / 0.016666666666666666): 3.6100173616667 (1.1605:1.3451 dyn); redis key: RLshdhfaapprxnomza

**Expected behavior**
"skip ratelimit for whitelisted user" found in log, and user auth is not ratelimited

### Versions

Rspamd daemon version 1.9.4 
Ubuntu 16 KVM

**Comment by vstakhov** [comment]
Whitelisted user must be array, please read the docs about UCL syntax.

**Comment by friizer** [comment]
OK thanks 

whitelisted_user = [
  "info@domain.,com",
  "info@otherdomain.com"
]

sytnax working

**Comment by ladisone** [comment]
I have the same problem, but "whitelisted_user" as array no accept whitlisting this user in array.

My configuration local.d/ratelimit.conf is:

```
rates {
    user = {
      selector = 'user.lower';
      symbol = "USERS_RATELIMIT";
      whitelisted_user  = [
        "authuser1@domain.tld"
      ];
      bucket = {
        burst = 3;
        rate  = "2 / 1min";
      }
    }
}
```

It is really good syntax for this setting?

**Comment by ladisone** [comment]
Aha sorry, right syntax is:

```
rates {
  user = {
    selector = 'user.lower';
    symbol = "USERS_RATELIMIT";
    bucket = {
      burst = 3;
      rate  = "2 / 1min";
    }
  }
}
whitelisted_user  = [
  "authuser1@domain.tld"
];
```
Thist syntax working.

Thank you.
