### ISSUE TITLE
[Feature] do not score FORGED_RECIPIENTS if X-Sieve-Redirected-From is set

### ISSUE THREAD

**Issue by toto4ds** [rspamd/rspamd#2987]
If you use sieve from dovecot to resend mail, for example:
`
if true
{
    redirect "user2@host";
}
`
Rspamd set score FORGED_RECIPIENTS(2.00)[user1@host,user2@host]
Maybe disable it for sieve only?

**Comment by vstakhov** [comment]
You can add a composite rule for that.

**Comment by martbock** [comment]
@vstakhov I'm sorry if the question is stupid – but how exactly would I go about that? 
I would assume that the header `X-Sieve-Redirected-From` needs to be matched and turned into a symbol.
Could you explain what I'd have to do to create a composite rule for this use case?
Thank you so much!
