### ISSUE TITLE
DKIM/SPF, unexpected cache state logged

### ISSUE THREAD

**Issue by jendis** [rspamd/rspamd#2991]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Value set to spf_cache_size or dkim_cache_size doesn't correspond to log message 

>  stored record for <domain> (0x7a6c7ec9029211a4) in LRU cache for <num_of_secs> seconds, <curr_value>/<cache_size> elements in the cache

### Steps to Reproduce

1. Set in local.d/spf.conf _spf_cache_size = 0;_
Then caching is done anyway and the number after the _slash_ is always 32, see

> 2019-07-22 16:05:34 #4164(controller) <e086c9>; csession; spf_plugin_callback: stored record for something.cz (0x2119af2f966a5c31) in LRU cache for 107 seconds, 498/32 elements in the cache

2. Set in local.d/spf.conf _spf_cache_size = 64;_
Then caching is done even if that number exceeded
> 2019-07-22 16:26:16 #4164(controller) <d847be>; csession; spf_plugin_callback: stored record for something2.cz (0xdeba9331963bbcd8) in LRU cache for 86398 seconds, 575/64 elements in the cache

3. Set in local.d/spf.conf _spf_cache_size = 2000;_
Observed expected behaviour.

Generally speaking, the same was observed for a dkim cache configuration and all the spf_plugin_callback, spf_check_list and the dkim_module_key_handler callbacks and so for controller and normal workers.

**Expected behavior**
The caching will be disabled when _spf_cache_size_ or _dkim_cache_size_ set to zero.
The cached elements won't exceed the _spf_cache_size_ or _dkim_cache_size_ value.

### Versions

rspamd-1.9.4.

**Comment by vstakhov** [comment]
It should be fixed now. Please bear in mind, that the minimum cache size is 32. 0 should disable caching but anything `[1..32]` will be just 32.
