### ISSUE TITLE
DKIM/SPF, unshared cache between workers

### ISSUE THREAD

**Issue by jendis** [rspamd/rspamd#2992]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
LRU cache for DKIM/SPF handlers between normal and controller worker is unshared.
It can be seen from the log, e.g.:

> 2019-07-22 16:49:06 #4164(controller) <ee18fa>; csession; dkim_module_key_handler: stored DKIM key for domain1.com in LRU cache for 542 seconds, 3683/4000 elements in the cache
2019-07-22 16:49:06 #4188(normal) <588384>; task; dkim_module_key_handler: stored DKIM key for domain2.com in LRU cache for 241 seconds, 1340/4000 elements in the cache

> 2019-07-22 16:49:06 #4188(normal) <918f37>; task; spf_check_list: use cached record for d1.com (0x4ab10e3bf020e01f) in LRU cache for 177 seconds, 86/64 elements in the cache
2019-07-22 16:49:06 #4164(controller) <576b13>; csession; spf_check_list: use cached record for d2.com (0x9875f605af8b68e) in LRU cache for 231 seconds, 645/64 elements in the cache

### Steps to Reproduce

No special steps necessary.

**Expected behavior**
The cache will be shared between workers, so the user will see in log incremental increase of cached elements after every updated no matter which type of process does this task.

### Versions

rspamd-1.9.4

**Comment by vstakhov** [comment]
It won't be added, sorry. No way.
