### ISSUE TITLE
SPF LRU cache not increments

### ISSUE THREAD

**Issue by jendis** [rspamd/rspamd#2993]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
The SPF module callback _spf_plugin_callback_ logs action "stored record ... in LRU cache for xxx seconds, <cur_num>/<max_num> elements in the cache" where the <cur_num> is not always incremented regarding to the previously logged value, even when <cur_num> is less then <max_num>. Observation done for one specific worker and its instance.

### Steps to Reproduce
Just let the SPF module running and observe the logs:

> 2019-07-23 20:20:06 #11636(controller) <c2b115>; csession; spf_plugin_callback: stored record for zonerama.com (0xb93243acb3979991) in LRU cache for 506 seconds, 2702/4000 elements in the cache
> 2019-07-23 20:20:11 #11636(controller) <3f58fb>; csession; spf_plugin_callback: stored record for sexualny-kontakt.com (0x11478e5521099fff) in LRU cache for 54 seconds, 2702/4000 elements in the cache
> 2019-07-23 20:20:14 #11636(controller) <262b81>; csession; spf_plugin_callback: stored record for captaincandy.cz (0xd795a2230ac140ce) in LRU cache for 299 seconds, 2703/4000 elements in the cache
> 2019-07-23 20:20:14 #11636(controller) <c38551>; csession; spf_plugin_callback: stored record for asfinag.at (0x7ad6ff08f84a47c2) in LRU cache for 168 seconds, 2704/4000 elements in the cache
> 2019-07-23 20:20:21 #11636(controller) <52aac5>; csession; spf_plugin_callback: stored record for lekarna.cz (0xea168030795626ba) in LRU cache for 156 seconds, 2704/4000 elements in the cache
> 2019-07-23 20:20:23 #11636(controller) <72a168>; csession; spf_plugin_callback: stored record for sportisimo.cz (0xc3b6ed07a4fffadc) in LRU cache for 69 seconds, 2704/4000 elements in the cache
> 2019-07-23 20:20:23 #11636(controller) <ebf23f>; csession; spf_plugin_callback: stored record for t-mobile.cz (0xbf4d78e9c5db4511) in LRU cache for 4 seconds, 2704/4000 elements in the cache
> 2019-07-23 20:20:27 #11636(controller) <095034>; csession; spf_plugin_callback: stored record for modnisatnik.cz (0x1acf096529a2413d) in LRU cache for 84 seconds, 2705/4000 elements in the cache
> 2019-07-23 20:20:29 #11636(controller) <f0d1e3>; csession; spf_plugin_callback: stored record for amsbus.cz (0xa95ba4e2ce56b8b4) in LRU cache for 1790 seconds, 2705/4000 elements in the cache
> 2019-07-23 20:20:30 #11636(controller) <f47282>; csession; spf_plugin_callback: stored record for zoznam.sk (0x75f65a304c98a2d) in LRU cache for 299 seconds, 2705/4000 elements in the cache
> 2019-07-23 20:20:30 #11636(controller) <eeb43c>; csession; spf_plugin_callback: stored record for infusionmail.com (0x1e0e080089533c6) in LRU cache for 96 seconds, 2705/4000 elements in the cache

**Expected behavior**
For at least a given worker and its instance, the cache will be incremented with every new stored element, so the user will never see (in the log) the same number of cached elements with every new stored record.

### Versions
rspamd-1.9.4

**Comment by vstakhov** [comment]
No, it is LRU cache and elements are aso evicted on insertion.
