### ISSUE TITLE
[BUG] [low priority] Apparently wrong "too few text tokens" message

### ISSUE THREAD

**Issue by vadz** [rspamd/rspamd#2995]
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

### Steps to Reproduce

1. Receive the spam message partially reproduced below.
2. Try to relearn it as spam.
3. Get the following messages in the logs:

```
csession; rspamd_message_parse: loaded message; id: <9b50db1ff949d2f21c01724ceb519ce8@milimetricindustrial.com>; queue-id: <undef>; size: 796209; checksum: <927582cd756270155e61135e1a141b03>
csession; rspamd_mime_part_detect_language: detected part language: pt
bayes; bayes_classify: ignore bayes probability since we have found too few text tokens: 0 (of 100 checked), at least 1 is required
csession; rspamd_controller_learn_fin_task: <127.0.0.1> learned message as spam: 9b50db1ff949d2f21c01724ceb519ce8@milimetricindustrial.com
```

**Expected behavior**

The messages above look strange because there are some text tokens in the message, which is partially reproduced below. Is this error due to misdetecting the language (it looks like Lithuanian to me, but in any case it's definitely not Portuguese)?

Message excerpt:
```
Date: Wed, 31 Jul 2019 11:52:12 +0100
From: sales <sales@milimetricindustrial.com>
To: undisclosed-recipients:;
Subject: Fw: swift confirmation
Message-ID: <9b50db1ff949d2f21c01724ceb519ce8@milimetricindustrial.com>
X-Sender: sales@milimetricindustrial.com
User-Agent: Roundcube Webmail/1.3.8
X-PPP-Message-ID: <20190731105212.8778.1636@server.imaicom.com>
X-PPP-Vhost: milimetricindustrial.com

--=_e24ca5d6209aafa8fb3f49326b7335f9
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=UTF-8;
 format=flowed

Labas rytas pone,

Cia pridedamas musu mokejimo irodymas. PraÅ¡ome praneÅ¡ti apie galima 
pristatymo data ir butinas priemones.

Linkejimai.



UAB "Ginmitia"

Minsko pl.101; SkaidiÅ¡kiu km. Vilniaus raj.

Tel. +37064385458

sales@milimetricindustrial.com

www.milimetricindustrial.com
--=_e24ca5d6209aafa8fb3f49326b7335f9
Content-Transfer-Encoding: base64
Content-Type: application/octet-stream;
 name="swift copy.daa"
Content-Disposition: attachment;
 filename="swift copy.daa";
 size=579836

... a lot of binary junk snipped ...
```

### Versions

rspamd 1.9.4, Debian Buster.

**Comment by vstakhov** [comment]
This log message means that no statistical tokens were **found** in the bayes database. It means not just extracted tokens but some matched with the previously learnt stuff. 

Language detection for short texts is really quite a hard task. 

This text definitely looks like a Lithuanian and I have added some changes to the detection code. However, lack of content-type for multipart message is definitely a bad thing :( Also, Lithuanian is still somehow close to Portuguese and other EU languages. Probably, there should be some stop words for lt as well...

**Comment by vadz** [comment]
Thanks for the answer! I think changing the warning message to say "known text tokens" would make it slightly more clear.

As for language auto-detection, it's definitely a difficult problem. This is probably out of scope of this bug, but I wonder why does rspamd actually try to do this, does it really matter in which language the spam is written as long as we know that it's spam? DSPAM, which I used before, didn't do any language detection at all, yet it was very effective at Bayesian spam detection (it had many other problems and rspamd is better than it in almost all the areas, but maybe not in this particular one).
