### ISSUE TITLE
[Build] Use CMAKE_<LANG>_FLAGS_<CONFIG> to set optimization/debug CFLAGS

### ISSUE THREAD

**Issue by citrin** [rspamd/rspamd#2996]
## Summary

Recommended way of setting debug and optimization CFLAGS in Cmake is:
1. Always call cmake with CMAKE_BUILD_TYPE, e. g. `cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..` (for building packaged this is usually added by packaging system by default).

2. In CMakeLists.txt change optimization/debug CFLAGS  only using `CMAKE_<LANG>_FLAGS_<CONFIG>` if it is needed, e. g. `CMAKE_C_FLAGS_DEBUG` and `CMAKE_CXX_FLAGS_DEBUG` for `CMAKE_BUILD_TYPE=Debug` e. t. c.
But I found default values provided by Cmake reasonable and think we should not change `CMAKE_<LANG>_FLAGS_<CONFIG>`.

## Motivation

Currently it is difficult to build Rspamd with desired CFLAGS (Rspamd CMakeLists.txt adds flags I don't need). Also currently I see many redundant CFLAGS in a command line `-g -O2 -O2 -g -pipe -Wall - ... -O2 -g -DNDEBUG   -msse2 -W -Wall`. Changing only some of them may not change the result.

## Additional context

https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/Useful-Variables#compilers-and-tools
https://gitlab.kitware.com/cmake/community/wikis/FAQ#how-can-i-change-the-default-build-mode-and-see-it-reflected-in-the-gui

Changing  CMAKE_C_FLAGS/CMAKE_CXX_FLAGS directly is considered an anti-pattern in modern Cmake and in almost all cases should be avoided.

**Comment by citrin** [comment]
Also while we a here I suggest to remove stuff like
```
IF(ENABLE_FULL_DEBUG MATCHES "OFF")
if ("${CMAKE_C_COMPILER_ID}" STREQUAL "Clang" OR "${CMAKE_C_COMPILER_ID}" STREQUAL "GNU")
    SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O3")
endif ()
ENDIF()
```

`-O3` increases resulting binary size (aggressive loop unroll + inline), but performance results are mixed - in some benchmarks  `-O3` slower than `-O2`, in some faster. Compilation with -O3 is slower. Unless we have benchmarks which shows that there is statistically significant difference between O2 and O3 for rspamd and O3 is faster, I suggest to drop this.

**Comment by vstakhov** [comment]
It was done for a reason. However, this reasoning might be not relevant now with the compilers set used so far. I agree with the proposed change, however, it seems like a low priority task with negligible outcome for me.
