### ISSUE TITLE
[Feature] Reject extensions from mime type or inside archive

### ISSUE THREAD

**Issue by stephdl** [rspamd/rspamd#2998]
## Summary

We would like to reject emails with specific attachment based on their mime types or when they are inside an archive, We would like for this a specific smtp rejection message.

## Motivation

The file extension could be renamed by the spammer or the attacker, some extensions that we do not want are hidden inside an archive, rspamd should be able to reject files from their mime content or when they are bundled inside an archive.

## Describe alternatives you've considered

- We use the multimap module to reject the extension with  a map file, it works but we two cons
    - we cannot check  files inside  an archive
    - if the extension is renamed then we cannot reject it

- We have implemented the mime_types module and created a locale.d/mime_types.conf to make a 20 score for the list of extension we would like to reject, it works but the smtp message is for spam rejection, rather to a smtp attachment rejection message

## Additional context

I made a PR to attempt to solve my issue: https://github.com/rspamd/rspamd/pull/2997

**Comment by heraklit256** [comment]
I really appreciate this feature, thank you very much!

**Comment by vstakhov** [comment]
Multimap checks extensions in the archives. However, content-type and libmagic checks are obviously not performed for archived files (neither by multimap, nor by mime_types modules) as it implies decompression support which is not likely be added to Rspamd.

**Comment by stephdl** [comment]
@vstakhov just tested it, in my configuration multimap did not succeed to reject a exe extension inside a zip archive, but mime_types see it and add a the `MIME_BAD_EXTENSION` symbol

https://gist.github.com/d97bb8cab6ad2275e26a4b4ac480b717

this is my multimap configuration


 ```
#reject email when the file extension is found
    FORBIDDEN_FILE_EXTENSION {
    type = "filename";
    filter = "extension";
    map = [
    "${CONFDIR}/forbidden_file_extension.map",
    ];
    action = "reject";
    symbol = "FORBIDDEN_FILE_EXTENSION";
    description = "List of forbidden file extensions";
}
```

what is wrong ?

**Comment by vstakhov** [comment]
Have you tested it with the master branch?

**Comment by vstakhov** [comment]
The code is identical, so I cannot see why there could be any difference I'm afraid.

**Comment by stephdl** [comment]
@vstakhov I tested with rspamd 1.9.4, on centos7, do you want I open a new issue to track this ?

**Comment by Stefan1904** [comment]
I have the same problem with Rspamd 1.9.4. Extensions in archives will not be rejected. So i don't know how to reject for example exe files in zip archives.

**Comment by stephdl** [comment]
@vstakhov I will open a specific issue to track this, @Stefan1904 seems to get the same issue than me

**Comment by stephdl** [comment]
solved by https://github.com/rspamd/rspamd/commit/99cdd89e0c466bef05ee42ab98d046e7f642f591

now multimap is able to looks inside archive after a extension, find the mime type of a file, but the limitation is that mime check are not done inside archive
