### ISSUE TITLE
[BUG] (clamav) lua_redis_push_data: call to callback failed: attempt to index a nil value

### ISSUE THREAD

**Issue by int-avoss** [rspamd/rspamd#3007]
**Describe the bug**
When an email arrives, log reports "lua_redis_push_data: call to callback failed: attempt to index a nil value" while passing content to antivirus/clamav.

### Steps to Reproduce

1. update rspamd to commit "456880ef0ab91d3cea8d83d1be9a670a8968ec67"
2. receive an email

**Expected behavior**
email should be checked like "clamav.lua:132: clamav: message or mime_part is clean"

### Versions

`Rspamd daemon version 2.0`

`Linux XXXXX 4.19.66-gentoo #1 SMP PREEMPT Mon Aug 12 09:23:26 CEST 2019 x86_64 Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz GenuineIntel GNU/Linux`

### Additional Information

normal log:
`rspamd[510]: <41d27a>; lua; clamav.lua:132: clamav: message or mime_part is clean`

failure log:
`rspamd[26402]: <>; ; lua_redis_push_data: call to callback failed: attempt to index a nil value; trace: [1]:{[C]:-1 - request [C]}; [2]:{/usr/share/rspamd/lualib/lua_scanners/clamav.lua:167 - fn [Lua]}; [3]:{/usr/share/rspamd/lualib/lua_scanners/common.lua:153 - callback [Lua]}; [4]:{/usr/share/rspamd/lualib/lua_redis.lua:869 - <unknown> [Lua]};`

**Comment by int-avoss** [comment]
It seems to be a local issue on gentoo.

the provided init-script uses the function:

```
checkconfig() {
        ${command} -c "${RSPAMD_CONFIGFILE}" -u ${RSPAMD_USER} -g ${RSPAMD_GROUP} -t 1>/dev/null \
                || return 1
}
```
prior to "start"/"stop".

with the latest git-commit the option:

`-t, --config-test       Do config test and exit`

is not available in rspamd anymore, so the function fails.

as result of the "broken" init-script there was a running rspamd which shows the mentioned behaviour above. after killing this process and a clean start (without "checkconfig") the erros from clamav.lua are gone.

**Comment by vstakhov** [comment]
Hum, not sure how that could be related.
