### ISSUE TITLE
[BUG] metadata_exporter - error in tcp callback

### ISSUE THREAD

**Issue by sateng** [rspamd/rspamd#3011]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

Rejected or as spam recognized mails do not get reported to the configured e-mail address. The attempt to deliver these notifications is visible in the rspamd logfile but rspamd is unable to get a connection to the local mailserver.
Postfix listens on all interfaces but does not log a connection attempt.
This bug has also been reproduced on an alternate system with older CentOS and less restricted postfix configuration but the result is the same.
The version of rspamd is the same on both test-systems.

### Steps to Reproduce

1. [First Step]
Configure metadata_exporter.conf to report is_spam or is_reject to an e-mail address

2. [Second Step]
Send an email which will be rejected or recognized as spam. 
RSPAMD will select message for processing

**Expected behavior**
The processed mail should be notified to the admin as spam or rejected.

### Versions

You can get this information from copy and pasting the output of `rspamd --version` from the command line. Also, please include the **OS** and what version and architecture including the generation of CPU model (e.g. Haswell) where applicable,  of the OS you're running.

Rspamd daemon version 1.9.4
Cent OS 7 3.10.0-042stab139.1

### Additional Information

Snippet from Logging:

[...]
2019-08-22 10:19:23 #13286(rspamd_proxy) <f95ffa>; metadata_exporter; metadata_exporter.lua:696: Message selected for processing
[...]
2019-08-22 10:19:23 #13286(rspamd_proxy) <f95ffa>; lua; metadata_exporter.lua:299: got error in tcp callback: IO read error while trying to read data: Verbindungsaufbau abgelehnt

[metadata_exporter.txt](https://github.com/rspamd/rspamd/files/3529331/metadata_exporter.txt)

When the above message appears, there is no log entry in postfix maillog that localhost attempts to connect

**Comment by vstakhov** [comment]
Not a bug in Rspamd: `connection refused` is your networking issue.
