### ISSUE TITLE
[BUG] fail to load map from rspamd .com

### ISSUE THREAD

**Issue by Neurozone** [rspamd/rspamd#3017]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
got this error in rspamd.log:

map; http_map_finish: cannot load map https://updates.rspamd.com/rspamd-1.9.ucl from updates.rspamd.com: HTTP error 404

tried to put this url in the browser, 404

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

i'm not sure, it's an install from the rpm

**Expected behavior**

Maybe update working ?

### Versions

v1.9
You can get this information from copy and pasting the output of `rspamd --version` from the command line. Also, please include the **OS** and what version and architecture including the generation of CPU model (e.g. Haswell) where applicable,  of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by vstakhov** [comment]
This module is default disabled in 1.9.4. Don't enable it.
