### ISSUE TITLE
[BUG] Image Urls inside Html content are not considered for SURBL checks

### ISSUE THREAD

**Issue by rspamd-internal** [rspamd/rspamd#3020]
### Problem
Urls that are present inside HTML contents more specifically inside <img src=""> tag are not considered for SURBL checks.

### Additional Information
I can see RSPAMD detecting image URL in logs

> 2019-08-28 10:54:23 #29964(controller) <a96cc4>; surbl; surbl_tree_redirector_callback: check url redirection http://dqa3.mycheapcase.com/00.jpg
2019-08-28 10:54:23 #29964(controller) <a96cc4>; surbl; surbl_test_redirector: checked image url http://dqa3.mycheapcase.com/00.jpg for redirectors

But it does not consider it for SURBL checks like URIBL and others. And the Url is not listed in the result also.

> Symbol: __VIA_ML (0.00)[__ML1]
Message-ID: xxx@tkd.mycheapcase.com
Urls: ["faym4.mycheapcase.com","mycheapcase.com"]
Message - spf: (SPF): spf allow

**Comment by vstakhov** [comment]
`check_images = true`
