### ISSUE TITLE
[BUG] 1.9.4 log 'stop resolving on reaching 64 requests'

### ISSUE THREAD

**Issue by tomascharvat** [rspamd/rspamd#3026]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Rspamd log message

2019-08-31 12:20:35 #8997(controller) <2aa1a1>; csession; make_dns_request_task_common: <ZZ@aa.com> stop resolving on reaching 64 requests

log frequency is variable, under high load it can be several per second

local unbound did handle 20k+/s under stress test

What seems to be bug to me, is that value 64 seems to be reffering to 64 sockets, however rspamadm configdump show 96. Even when I change it to 32, error message doesnt change.
If I understood documentation and error log correctly, then rspamd ignore this option.
### Steps to Reproduce

1. [First Step]
set:
dns {
    sockets = 96;
}
2. [Second Step]
stress rspamd and see log file

**Expected behavior**
I did expect to see set value in error log.

### Versions
1.9.4
on System uname: Linux-4.19.69-gentoo-x86_64-AMD_EPYC_7601_32-Core_Processor-with-gentoo-2.6

**Comment by vstakhov** [comment]
```
$ rspamadm confighelp -k dns_max
Showing help for keyword dns_max:
Configuration element: .options.dns_max_requests
	Description: Legacy option for DNS maximum requests per task count
	Type: int32
	Required: false
```

Default is 64. Some request can bypass this limit (e.g. rDNS or DKIM requests)

**Comment by tomascharvat** [comment]
It would be lovely to see Default value in presented output.

As for ".options.dns_max_requests" I figured out, that proper place where to put this is:
file: local.d/options.inc
root section of the file, not dns {}
As "." in the name are probably delimiters for config tree, while "_" are part of the config name.

Not it work as expected, thanks for clarification. Please consider Default value print in confighelp output.
