### ISSUE TITLE
[BUG] spamtrap doesn't parse regex when configuring map from WebUI

### ISSUE THREAD

**Issue by Manawyrm** [rspamd/rspamd#3031]
### Prerequisites

* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
When using the spamtrap plugin, and configuring a map from the webUI with
` map = "${DBDIR}/spamtrap.inc.map"; ` 
no regexp are used/parsed.
`/^.*@mydomain\.de$/` doesn't match, 
`mydomain.de` does match. 

When using the spamtrap with a local file: 
` map = "/etc/rspamd/local.d/spamtrap.map"; `
regexp like to one above work like expected. 

### Steps to Reproduce

1. Configure the spamtrap module like here https://rspamd.com/doc/modules/spamtrap.html
2. Use ` map = "${DBDIR}/spamtrap.inc.map"; `
3. Configure a regex via the webinterface lists
4. Send a test email to the address in the regexp

You'll find
`spamtrap; spamtrap.lua:133: skip spamtrap for testaccount@mydomain.de`
in your log, as the plugin isn't detecting the mail address. 

**Expected behavior**
The mail is detected by the plugin. 

### Versions
Debian 9, rspamd 1.9.4 (from official repo)

**Comment by moisseev** [comment]
Does it work if you add a newline character after the regexp?

**Comment by Manawyrm** [comment]
@moisseev Yes! Wow, good call :) 
That isn't expected behaviour, right?

**Comment by Manawyrm** [comment]
We've tested this with rspamd 2.1 and can still reproduce the behaviour.
Is this expected or could it be fixed?

**Comment by vstakhov** [comment]
Expected.
