### ISSUE TITLE
[Feature] rspamd lua api: add ability to get values from maps by case-insestive keys

### ISSUE THREAD

**Issue by tierpod** [rspamd/rspamd#3036]
## Summary

There is map:get_key(in) method in rspamd lua api, but it's case-sensitive. In some cases it would be nice to get value from map by case-insensitive key, or check if key exists in map in case-insensitive way.

## Motivation

For example, I have map file (type = set, plain strings with no values). This map file contains list of keywords (in lowercase):

```
keyword1
угроза
```

I write lua module that loads this map file and checks words in Subject header against these keywords. Simple way:

```lua
exists = mymap:get_key("keyword1")
-- returns true

exists = mymap:get_key("KeyWord1")
-- returns false
```

That is a problem: get_key works in case-sensitive way, so *exists* is false when keyword is not lowercased. So it would be useful to have alternative function that works in case-insensitive way.

## Describe alternatives you've considered

I researched some existent rspamd api methods and can suggest another ways:

1) lua has string:lower() function, but it doesn't work with utf8 strings. Solution: add rspamd lua method that works with utf8 strings:

```lua
rspamd_util.str_lower("Угроза")
-- returns "угроза"
mymap:get_key(rspamd_util.str_lower("УГРОЗА"))
-- returns true
```

2) Add iteration support for rspamd maps (like tables) and use `util.strequal_caseless(str1, str2)`

```lua
for _, keyword in ipairs(mymap) do
  if util.strequal_caseless("УГРОЗА", keyword) then
    -- ...
  end
end
```

**Comment by ianhlavats** [comment]
I have a similar problem but in my case I am trying to read the values from the map file and check if they exist in the message body. Rspamd supports iterating the words in the message body and checking if they exist in the map, but is there a way to do the opposite, that is, read the value from the map file and check if they exist in the message?

**Comment by vstakhov** [comment]
The first problem is resolved, the second comment is clearly XY problem. Closing.

**Comment by ianhlavats** [comment]
My apologies, will raise a separate ticket.

**Comment by ianhlavats** [comment]
My apologies @vstakhov . Can you please advise me on how to get support for my question? It is neither a bug report or a feature request. I could not find an answer in the documentation.
