### ISSUE TITLE
Too many slow rules reported for DKIM_CHECK and R_SPF_FAIL

### ISSUE THREAD

**Issue by jendis** [rspamd/rspamd#3052]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Rspamd logs following lines too many times in case of DKIM_CHECK and R_SPF_FAIL symbols per each 30 minutes
>2019-09-23 21:45:25 #6366(controller) <995c15>; csession; rspamd_symcache_finalize_item: slow rule: R_SPF_FAIL(36): 997.12 ms
>2019-09-23 21:49:04 #6366(controller) <5939fd>; csession; rspamd_symcache_finalize_item: slow rule: DKIM_CHECK(35): 1000.00 ms

number of lines in average over the 30 minutes intervals in case of rules:
- DKIM_CHECK: 920
- R_SPF_FAIL: 719
Average number of waiting time is ~600ms.

### Steps to Reproduce

No special steps to reproduce, default config for DKIM and SPF is used.

**Expected behavior**
If the reason is waiting for a DNS response, this should be mentioned in logs, for example:
>2019-09-23 21:45:25 #6366(controller) <995c15>; csession; rspamd_symcache_finalize_item: slow rule: R_SPF_FAIL(36): 997.12 ms (800 ms spent by waiting for a DNS response)

### Versions

1.9.4
on System uname: Linux-4.19.69-gentoo-x86_64-AMD_EPYC_7601_32-Core_Processor-with-gentoo-2.6

**Comment by vstakhov** [comment]
This cannot be done, closing.
