### ISSUE TITLE
[Feature] cache metadata_exporter exports, if remote end is down

### ISSUE THREAD

**Issue by nafetsreuab** [rspamd/rspamd#3056]
## Summary

cache metadata_exporter exports via HTTP POST, if remote end (receiver) is down.

## Motivation

Metadata is key for logging/auditing. Sometimes, remote end is down and can not accept metadata from post requests (HTTP POST) sent by rspamd. Currently, there might be gaps in the logs/data. This is bad.

## Describe alternatives you've considered

Having 100% availability at receiver end is nearly impossible. A caching in between would be great to not lost any data.

## Additional context

Thank you for considering.

**Comment by vstakhov** [comment]
This will not likely be implemented.

**Comment by nafetsreuab** [comment]
Too bad :/ Would be nice, if you could keep it up and maybe re-validate if others will find it helpful as well :) Thank you.

**Comment by nafetsreuab** [comment]
Please consider this. Exporting is great but loosing data during write/push is bad :/
