### ISSUE TITLE
[Feature] Percentage of image

### ISSUE THREAD

**Issue by robertboyl** [rspamd/rspamd#3062]
Hi, everyone

If someone can pls consider a test, such as Spamassassin's, to score if there is more percentage of image then text in a message.

Examples of false negatives..

1) just an example of why "80% or so of image in body" test would help.
it has a few images and very little text.

See example1.txt

2) See example2.txt

Thanks!!
[example1.txt](https://github.com/rspamd/rspamd/files/3675877/example1.txt)
[example2.txt](https://github.com/rspamd/rspamd/files/3675878/example2.txt)

**Comment by vstakhov** [comment]
The first email has `HTML_SHORT_LINK_IMG_1` and the second has `R_EMPTY_IMAGE` symbols. Isn't that enough?

**Comment by robertboyl** [comment]
Thanks for reply.

I see... Well, the thing is false negatives still occur with these spams that have mostly an image.. I thought maybe we could increase scores a bit or find other ways.

If it's Ok for you, I can send a few more examples as they occur, so you can see what you suggest...

I think SA had different scores according to the ratio text x image.

Thanks!

**Comment by robertboyl** [comment]
Heres 1 more example, false negative. A spam that has mostly image.

Any ideas?

Thanks!
[example3.txt](https://github.com/rspamd/rspamd/files/3699252/example3.txt)

**Comment by robertboyl** [comment]
one more example of a major spam not detected with mostly image.
[example.txt](https://github.com/rspamd/rspamd/files/3712481/example.txt)

**Comment by robertboyl** [comment]
[example-14-10-19.txt](https://github.com/rspamd/rspamd/files/3725273/example-14-10-19.txt)

**Comment by robertboyl** [comment]
[example-15-10-19.txt](https://github.com/rspamd/rspamd/files/3730386/example-15-10-19.txt)

**Comment by robertboyl** [comment]
[image spam.txt](https://github.com/rspamd/rspamd/files/3798850/image.spam.txt)

**Comment by robertboyl** [comment]
major phishing false negative. check out the % of image...
[phishing.txt](https://github.com/rspamd/rspamd/files/3841710/phishing.txt)

**Comment by robertboyl** [comment]
1 more, major phishing, very low score. 1 single image in body...

shouldnt r_empty_image be higher?

can I do something like if theres a single image AND it comes from gmail, outlook.com, etc. then give it a higher score? These systems have to be penalized, this happens all the time from their servers, unfair.
[phishing.txt](https://github.com/rspamd/rspamd/files/4030579/phishing.txt)

**Comment by robertboyl** [comment]
1 more, major phishing, asking for money, etc... scored very low... :(
[phishing.txt](https://github.com/rspamd/rspamd/files/4123366/phishing.txt)
