### ISSUE TITLE
[BUG] email adress containing a dot in the username part are not recognized in multimap

### ISSUE THREAD

**Issue by urmel1960** [rspamd/rspamd#3066]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
I created the following symbol in /etc/rspamd/local.d/multimap.conf:

```
sender_from_whitelist_addr {
            type = "from";
            filter = "email:addr";
            map = "file:///etc/rspamd/maps.d/whitelist_from_addr.map";
            symbol = "SENDER_FROM_WHITELIST_ADDR";
            action = "accept"; # Prefilter mode
}
```

The map-file /etc/rspamd/maps.d/whitelist_from_addr.map contains the following entry:
```
# whitelisted addresses
john.doe@gmail.com
```
Sending a mail from john.doe@gmail.com through rspamd. This email is listed in the history table of the web gui. In column "[Envelope From] From" the senders adress is listed as "johndoe@gmail.com" instead of "john.doe@gmail.com". The dot in the username part is not recognized and therefore the mail is not handled properly by the rule from multimap.conf

Using adress-entries without a dot in the username are processed properly and the symbol is added correctly and is shown in history on web gui.

### Steps to Reproduce

See above

**Expected behavior**
email-adresses containing a dot within the username part should be recognised properly in the described scenario .

### Versions

You can get this information from copy and pasting the output of `rspamd --version` from the command line. Also, please include the **OS** and what version and architecture including the generation of CPU model (e.g. Haswell) where applicable,  of the OS you're running.

Rspamd daemon version 1.9.4 

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by moisseev** [comment]
It is intentional. Rspamd normalizes gmail addresses so they would match in any [variation](https://support.google.com/mail/answer/7436150?hl=en)


https://support.google.com/mail/answer/7436150?hl=en
