### ISSUE TITLE
[BUG] Upgrade:  1.9.4_2 -> 1.9.4_3 (overwritten configuration)

### ISSUE THREAD

**Issue by IPTRACE** [rspamd/rspamd#3069]
### Prerequisites

OS: FreeBSD 12.0-RELEASE-p10
Application: rspamd
Version (before upgrade): 1.9.4_2
Version (after upgrade): 1.9.4_3
Upgrade by packages; pkg upgrade rspamd

**Describe the bug**
After upgrade the file modules.d/milter_headers.conf has been overwriten to default, so I lost all my changes.

P.S. I've not already checked others.
P.S.2. Checked, I've lost my all changes in all files inside the directory modules.d ....

**Expected behavior**
It should be not changed anyway. Or if I missed somewhere the sentence in all configuration files
"# You can modify '$LOCAL_CONFDIR/rspamd.conf.local' to add parameters defined on the top level"
means you MUST because you will lose your changes.

**Comment by vstakhov** [comment]
It should and it will be changed. You've been warned many times. A comment now is the following:

```
# Please don't modify this file as your changes might be overwritten with
# the next update.
```
