### ISSUE TITLE
 [BUG] Upgrade: 1.9.4_2 -> 1.9.4_3 (cannot read ed25519 private key)

### ISSUE THREAD

**Issue by IPTRACE** [rspamd/rspamd#3070]
After upgrade the same key readable in 1.9.4_2 cannot be read by version 1.9.4_3 . The same issue like in the bug description at https://github.com/rspamd/rspamd/issues/2974 .

lua_rsa_privkey_load_file: cannot open private key from file: /var/rspamd/my.key, error:0909006C:PEM routines:get_name:no start line

I've generated the new one and the same issue occured.

**Comment by kbabioch** [comment]
Isn't this a regression? Is it really a good idea to close this issue with wontfix?

**Comment by shithubsucks** [comment]
I am still having this issue on FreeBSD with rspamd 3.11.1
