### ISSUE TITLE
[Feature] DMARC sending report: add option for STARTTLS to support TLS

### ISSUE THREAD

**Issue by IPTRACE** [rspamd/rspamd#3077]
## Summary

This is the same as https://github.com/rspamd/rspamd/issues/2701 .

## Motivation

Increase security and functionality.

## Additional context
Are there any chance to add support STARTTLS for MTA to send DMARC reports?

**Comment by vstakhov** [comment]
I'm still not convinced that there are any benefits in adding this feature. I have explained my position in the issue you've referenced.

**Comment by IPTRACE** [comment]
It should desirable to encrypt traffic between rspamd (DMARC) and MTA in case where both applications are split between two different systems.

**Comment by vstakhov** [comment]
Set a local MTA that would forward emails from Rspamd to another MTA, what's the problem?

**Comment by IPTRACE** [comment]
The problem is with such logic that it complicates mail system which is already complicated a lot.

**Comment by vstakhov** [comment]
Ok, so you are suggesting me to complicate already complicated Rspamd? No way. If you don't want a local MTA then just use stunnel (or anything similar).
