### ISSUE TITLE
[Feature] Rewrite Subject + Add Header

### ISSUE THREAD

**Issue by LeDistordu** [rspamd/rspamd#3078]
## Summary

We need rewrite subject (user visibility) and Add header (Mail Server trigger). I tried a lot of things but I have not succeeded, if i apply action to rewrite the subject, the header does not apply.

## Motivation

In some cases mail servers do not know how to do action on the header and sometimes the opposite.

**Comment by croessner** [comment]
This can be done in user settings. But rewriting subject sets also the X-Spam header, even if the mail is ham. So be careful when using this feature.

Adding headers works also in user settings. I use this a lot. Look for user settings in the documentation.

Example:

```
settings {
    ROLEACCOUNT {
        id = "roleaccount";
        priority = low;
        rcpt = "postmaster";
        rcpt = "abuse";
        apply {
            add_headers {
                X-Rspamd-Policy = "Policy set to POLICY_ROLEACCOUNT";
            }
            ... other things ...
        }
    }
}
```

Maybe the rspamd-users mailinglist is a better place for help ;-)

**Comment by LeDistordu** [comment]
I try this settings :

`/etc/rspamd/local.d/settings.conf`
```test01 {
        id = "test01";
        priority = high;
        rcpt = "domain1.com";
        rcpt = "domain2.com";
        request_header = {
                "spam" = "yes";
        }
        apply {
                actions {
                        "subject" = SPAM %s;
                }
        }
}```

it does not work :/

**Comment by Yotouille** [comment]
Hi there,

I've been trying to modify the mail subject using users_settings, but I think there is something I do not understand. Maybe someone could point me in the right direction..?

This is matched and it works (ARC_NA is rewrited with new score):
```
test01 {
        id = "test01";
        priority = high;
        rcpt = "test@domain.tld";
        apply {
            ARC_NA = 1.0;
        }
}
```

This is matched but do not work (Subject is not changed):
```
test02 {
        id = "test02";
        priority = high;
        rcpt = "test@domain.tld";
        apply {
            subject = "TEST %s";
        }
}
```

Is there something special needed to apply the new subjet ? I'm very lost here...

Thanks !

**Comment by stephdl** [comment]
I have it workable

```
[root@prometheus ~]# cat /etc/rspamd/local.d/milter_headers.conf 
#
# This file will be overwritten by the next rpm update
# use /etc/rspamd/override.d/file.conf' - to override the defaults
#

#add extended headers (see score and symbols in header)
extended_spam_headers = true;

# Add score headers for authenticated users or local IP 
skip_authenticated = false;
skip_local = false;

# Add the known spam header of spamassassin
# "X-Spam" header of rspamd is not removed
use = ["spam-header"];
routines {
   spam-header {
     header = "X-Spam-Flag";
     value = "Yes";
   }
}
```
```
[root@prometheus ~]# cat /etc/rspamd/local.d/actions.conf 
# ================= DO NOT MODIFY THIS FILE =================
# 
# Manual changes will be lost when this file is regenerated.
#
# Please read the developer's guide, which is available
# at NethServer official site: https://www.nethserver.org
#
# 
#
# 10base
#

#see https://rspamd.com/doc/configuration/metrics.html
#override spam thresholds


reject = 19.9;
add_header = 8;
greylist = 4;
rewrite_subject = 8.01;
subject = "***SPAM*** %s";
```

**Comment by jneuhauser** [comment]
Is there really no simple working solution to apply the action `add_header` also if `rewrite_subject` is triggered with a lower score?

**Comment by stephdl** [comment]
in our previous spammassin configuration (before 2018) it was set like this, now nethserver 8 is quite out, so we use again rspamd based on container @williamdes

**Comment by williamdes** [comment]
> in our previous spammassin configuration (before 2018) it was set like this, now nethserver 8 is quite out, so we use again rspamd based on container @williamdes

D'accord, c'était plutot que je trouvais bizzare de ne pas voir la valeur en majuscule alors que les autres exemples et configs sur le net ont `YES` en majuscule ;)
La config proposée dans le commentaire marche t'elle ?

Bon en tout cas j'ai pas réussi de mon coté avec docker mailserver et rspamd

**Comment by stephdl** [comment]
test then nethserver8, a full podman solution based on postfix, dovecot, rspamd but with many others modules full container based. We have a cluster solution, you can have many nodes

we are going to beta 2

**Comment by mvasi90** [comment]
> But rewriting subject sets also the X-Spam header, even if the mail is ham

@croessner, I don't see the X-Spam header after rewritting the subject from force_actions.

How to mark the mail as spam but change also change the subject?

**Comment by jimRoper** [comment]
> > But rewriting subject sets also the X-Spam header, even if the mail is ham
> 
> @croessner, I don't see the X-Spam header after rewritting the subject from force_actions.
> 
> How to mark the mail as spam but change also change the subject?

I am also seeing this behavior.  Clients are recieving mail with a rewritten subject in their inboxes.  I reviewed the headers of the emails in question and found that spam headers were added to the emal but the Xspam: Yes flag is missing, which is what sieve is looking for to move the mail to Junk. 

Attached is the header of a rewrite header email:

Content-Type: multipart/alternative; boundary="_=_swift_1708531179_94ae2a551576daf9211a7a6083fb224a_=_"
Mime-Version: 1.0
X-Rspamd-Action: rewrite subject
X-Spamd-Result: default: False [22.17 / 150.00]; FUZZY_DENIED(9.11)[1:3669e43944:0.75:txt]; VIOLATED_DIRECT_SPF(3.50)[]; HFILTER_HOSTNAME_UNKNOWN(2.50)[]; PHISHING(2.00)[[peoplevine.com](http://peoplevine.com/)->[stockconglomerate.com](http://stockconglomerate.com/)]; RDNS_NONE(1.00)[]; PHISH_EMOTION(1.00)[]; HFILTER_HELO_IP_A(1.00)[[r238.domain.com](http://r238.domain.com/)]; URI_COUNT_ODD(1.00)[7]; R_PARTS_DIFFER(0.98)[98.8%]; BAD_REP_POLICIES(0.10)[]; ONCE_RECEIVED(0.10)[]; MIME_GOOD(-0.10)[multipart/alternative,text/plain]; HAS_LIST_UNSUB(-0.01)[]; TO_MATCH_ENVRCPT_ALL(0.00)[]; RCPT_COUNT_ONE(0.00)[1]; DMARC_NA(0.00)[[stockconglomerate.com](http://stockconglomerate.com/)]; FORGED_SENDER_VERP_SRS(0.00)[]; FROM_HAS_DN(0.00)[]; R_DKIM_ALLOW(0.00)[[stockconglomerate.com](http://stockconglomerate.com/):s=hws]; HAS_REPLYTO(0.00)[[info@stockconglomerate.com](mailto:info@stockconglomerate.com)]; FROM_NEQ_ENVFROM(0.00)[[info@stockconglomerate.com](mailto:info@stockconglomerate.com),[info-admin=xxxxx.com@stockconglomerate.com](mailto:info-admin=xxxxx.com@stockconglomerate.com)]; R_SPF_SOFTFAIL(0.00)[~all]; DKIM_TRACE(0.00)[[stockconglomerate.com](http://stockconglomerate.com/):+]; TO_DN_NONE(0.00)[]; REPLYTO_ADDR_EQ_FROM(0.00)[]; ARC_NA(0.00)[]; SUBJECT_ENDS_EXCLAIM(0.00)[]; MIME_TRACE(0.00)[0:+,1:+,2:~]; RCVD_COUNT_ZERO(0.00)[0]; MID_RHS_MATCH_FROM(0.00)[]; ASN(0.00)[asn:8560, ipnet:74.208.0.0/16, country:DE]; GREYLIST(0.00)[pass,body]
X-Rspamd-Queue-Id: 395FB402D2
Dkim-Signature: v=1; a=rsa-sha256; bh=YFoIqhpPmajo4w3NxoGAZWU1mxxxxxA8QY7U46Uu5pQ=; d=[stockconglomerate.com](http://stockconglomerate.com/); h=Message-ID: Date: Subject: From: Reply-To: To: MIME-Version: Content-Type: List-Unsubscribe; [i=@stockconglomerate.com](mailto:i=@stockconglomerate.com); s=hws; t=1708531179; b=T8ZpCzD+PYN7kIt/QzPFFjoGogKb7sgSG8OQvFu3JTwVAYccY1BVTcwYWIxMWUAz+aQOgZaoj kWF6o48b5WAMUAjSuP5VQ6NH3NFn3CTPO3a20snk9d5xe/fV9mpLS7ZwioKrro5/6iFCc+V3K Ndlqb3smtF+WIR4g0MAHjhyUPT/gIXY7iEui/t8ie7PqsEVgWZ/09AgOp8nDFfAaCDt0HIllK 0aW/EAvmDpzLJ80P2hLnYOiEgMt1AZMIip2quBu5QQtVe+QhiREPoyIdYkSZOyr/n7awPKF21 y0tyFBotcFabPL6YPEhq2LZ9hw5umpNGR7HY5X/WQR6HQpWplA==
Return-Path: <[info-admin=xxxxx.com@stockconglomerate.com](mailto:info-admin=xxxxx.com@stockconglomerate.com)>
X-Var: 199310797-382437-2062-16-13-3-2-13
X-Logid: 199310797
Received: from [mail01.xxxxx.com](http://mail01.xxxxx.com/) by [mail01.xxxxx.com](http://mail01.xxxxx.com/) with LMTP id ms5GIvgk1mUzkgIAD4+bWw (envelope-from <[info-admin=xxxxx.com@stockconglomerate.com](mailto:info-admin=xxxxx.com@stockconglomerate.com)>); Wed, 21 Feb 2024 10:29:44 -0600
Received: from [r238.domain.com](http://r238.domain.com/) (unknown [xxx.xxx.xxx.xxx]) by [mail01.xxxxx.com](http://mail01.xxxxx.com/) (Postfix) with ESMTPS id 395FB402D2 for <[admin@xxxxx.com](mailto:admin@xxxxx.com)>; Wed, 21 Feb 2024 10:29:44 -0600 (CST)
<[2-wZrYOhgPTI5I-RDnNzn8Njlca@stockconglomerate.com](mailto:2-wZrYOhgPTI5I-RDnNzn8Njlca@stockconglomerate.com)>
List-Unsubscribe: <http://fps.stockconglomerate.com/campaign/unsub-email/MjA2Mg%3D%3D/MzgyNDM3/Mw%3D%3D__MTk5MzEwNzk3__MTY%3D>
X-Rspamd-Server: [mail01.xxxxx.com](http://mail01.xxxxx.com/)

**Comment by xiego** [comment]
To my knowledge, this hasn't been solved yet. There are countless workarounds, none of which work. It should really be an option in the configuration to keep the header.

**Comment by szotsaki** [comment]
Started a thread on the users mailing list: https://lists.rspamd.com/pipermail/users/2025-June/003742.html.

**Comment by bmatthewshea** [comment]
Seeing same problem here. Posting because I noticed this was closed due to being 'stale' ?

I had to add this in sieve global-

```
if header :contains "subject" "*** SPAM ***" {
  fileinto "Spam";
}
```

**Comment by aurelf** [comment]
Arrived at the same limitation, I couldn't get add header and rewrite subject simultaneously. That sounds like something simple to address ? 

Can someone reopen the bug? 

The issue is definitely not solved, and I don't see why it should be a wontfix.

**Comment by jaylogue** [comment]
I'm running into the same problem.  IMO, both of these actions -- signaling the user (via subject: ***SPAM***...) and signaling downstream mail handling (via X-Spam: Yes) -- are minimum ante functionality for any spam handling system.  I definitely think this needs to be reopened.

**Comment by stephengaito** [comment]
There is a rather good reason that this issue is marked `wontfix`.... there is an existing solution using `milter_headers`... alas it took me some time to wander around both the documentation and RSpamd code to understand what this solution should be.

**So** for anyone who still wants this "feature" you are welcome to adjust the following code for your needs and place it, along with any other `milter_headers` configuration you might need, in your `local.d/milter_headers.conf`:

```
# We add our own custom rewrite subject header routine by making slight
# modifications to the example custom routine in the milter_headers.conf
# documentation.
#
# see:
#  https://docs.rspamd.com/modules/milter_headers/
#  https://docs.rspamd.com/modules/milter_headers/#custom-routines

use = ["custom_rewrite_subject"];

custom {
  custom_rewrite_subject = <<EOD
  return function(task, common_meta)
    -- parameters are task and metadata from previous functions

    if task:has_symbol('CLAM_VIRUS') then
      return nil, -- no error
      {
       ['Subject'] = '*** Virus *** '..task:get_header('subject'),
      }, -- add header: Subject
      {
       ['Subject'] = 0
      }, -- remove foreign Subject headers
      {} -- metadata to return to other functions
    end

    local theAction = task:get_metric_action('default')
    if theAction:find("header") then
      return nil, -- no error
      {
       ['Subject'] = '*** Spam *** '..task:get_header('subject'),
      }, -- add header: Subject
      {
       ['Subject'] = 0
      }, -- remove foreign Subject headers
      {} -- metadata to return to other functions
    end

    return nil, -- no error
    { }, -- add header: X-Foo: Bar
    { }, -- remove foreign X-Foo headers
    {} -- metadata to return to other functions
  end
EOD;
}

# To understand the Lua interface, see:
#  get_subject: https://docs.rspamd.com/lua/rspamd_task/#m908c3
#  get_header:  https://docs.rspamd.com/lua/rspamd_task/#m9ce3b
#  has_header:  https://docs.rspamd.com/lua/rspamd_task/#mb152f
#  get_metric_result: https://docs.rspamd.com/lua/rspamd_task/#mc326f
#  get_metric_score:  https://docs.rspamd.com/lua/rspamd_task/#m5519f
#  get_metric_threshold: https://docs.rspamd.com/lua/rspamd_task/#m40b9d
#  get_metric_action: https://docs.rspamd.com/lua/rspamd_task/#m9b471
#  has_symbol:  https://docs.rspamd.com/lua/rspamd_task/#m824ce
#  get_symbol:  https://docs.rspamd.com/lua/rspamd_task/#mb89bf
#  get_symbol_regexp: https://docs.rspamd.com/lua/rspamd_task/#m7db46
#  get_symbols: https://docs.rspamd.com/lua/rspamd_task/#m6717b
#
#  https://docs.rspamd.com/lua/rspamd_logger

# To understand when the milter_headers are called and how the actions are
# determined, see:
#  https://docs.rspamd.com/getting-started/understanding-rspamd#stage-by-stage-breakdown
#  https://docs.rspamd.com/getting-started/understanding-rspamd#score-calculation-and-action-selection
#

```

This **assumes** that you have configured the actions as suggested by the RSpamd documentation, and in particular you use the `add header` action for any score you consider to be Spam.  This "standard" configuration, will *add the header* and the above `custom_rewrite_subject` routine will rewrite the subject.

These modifications to the RSpamd example code are placed in the **Public Domain**.  However, there is **NO WARRANTY** THAT IT WILL WORK FOR YOU.  **You MUST Test it in your non-production systems BEFORE use**
