### ISSUE TITLE
[BUG] history is not shown in web gui after upgrade to 2.0 - message scan gives error

### ISSUE THREAD

**Issue by urmel1960** [rspamd/rspamd#3080]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Updated from working 1.9.4 to 2.0. rspamd is up and  running but history is not show in webgui. Scan of a message in web gui gives an error "cannot scan data" .Log files shows that the message was scanned,.

### Versions
rspamd 2.0
Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-65-generic x86_64)

**Comment by HansVanEijsden** [comment]
I had the same problem. It sounds silly but... I had to clear my browser cache. After clearing my browser cache, all was fine.

**Comment by Krawi** [comment]
Clearing browser cache didn't help for me, but disable and reenable uBlock Origin and NoScript worked for me (Firefox addons). Chrome with only NoScript addon had no problems.

**Comment by urmel1960** [comment]
Hi guys - yes that worked. cleaning cache and all is fine. Thanks a lot
