### ISSUE TITLE
[BUG] rspamc: Resource temporarily unavailable

### ISSUE THREAD

**Issue by tleuxner** [rspamd/rspamd#3082]
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

rspamc called from a shell script hits a resource limit with rspamd 2.0, more precisely the OpenBLAS library. This started after updating rspamd while Dovecot and the scripts remained the same.

```
Oct 13 17:12:05 edi dovecot: imap: Error: OpenBLAS blas_thread_init: pthread_create failed for thread 7 of 16: Resource temporarily unavailable
Oct 13 17:12:05 edi dovecot: imap: Error: OpenBLAS blas_thread_init: RLIMIT_NPROC 128027 current, 128027 max
Oct 13 17:12:05 edi dovecot: imap(tlx@leuxner.net)[17854]: <ICuQLMyUWuwFkqnf>: Error: program exec:/var/vmail/conf.d/rspamd/rspamc-learn-ham.sh (17855): write(program stdin) failed: Broken pipe
Oct 13 17:12:05 edi dovecot: imap(tlx@leuxner.net)[17854]: <ICuQLMyUWuwFkqnf>: Error: program exec:/var/vmail/conf.d/rspamd/rspamc-learn-ham.sh (17855): Terminated abnormally with signal 2
```

### Steps to Reproduce

cat /var/vmail/conf.d/rspamd/rspamc-learn-ham.sh
`exec /usr/bin/rspamc learn_ham
`

### Versions
rspamd         2.0-1~buster

**Comment by tleuxner** [comment]
Adding this to the script seems to fix the issue after some quick googling:

`export OMP_NUM_THREADS=1`

**Comment by vixns** [comment]
I have a similar/related issue using rspamc ... learn_spam on debian/buster

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f8c18dba973 in pthread_mutex_trylock () from /lib/x86_64-linux-gnu/libpthread.so.0
[Current thread is 1 (Thread 0x7f8bfc1f5700 (LWP 17616))]
(gdb) bt
#0  0x00007f8c18dba973 in pthread_mutex_trylock () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f8c196eebae in je_tcache_arena_associate () from /usr/lib/rspamd/librspamd-server.so
#2  0x00007f8c196f0356 in je_tsd_tcache_data_init () from /usr/lib/rspamd/librspamd-server.so
#3  0x00007f8c196f04e8 in je_tsd_tcache_enabled_data_init () from /usr/lib/rspamd/librspamd-server.so
#4  0x00007f8c196f1417 in je_tsd_fetch_slow () from /usr/lib/rspamd/librspamd-server.so
#5  0x00007f8c1967af02 in malloc () from /usr/lib/rspamd/librspamd-server.so
#6  0x00007f8c1419796e in ?? () from /usr/lib/x86_64-linux-gnu/libopenblas.so.0
#7  0x00007f8c14197df8 in blas_memory_alloc () from /usr/lib/x86_64-linux-gnu/libopenblas.so.0
#8  0x00007f8c141985cb in ?? () from /usr/lib/x86_64-linux-gnu/libopenblas.so.0
#9  0x00007f8c18db7fa3 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#10 0x00007f8c18bb94cf in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

`export OMP_NUM_THREADS=1` workaround it

**Comment by vstakhov** [comment]
It seems that now it is not set by kann. I've observed the same crap with Torch and added a workaround some time ago. Probably, I need to add one for kann-openblas tandem as well.

**Comment by vstakhov** [comment]
That should be fixed (and configurable!) now.

**Comment by vstakhov** [comment]
Also, with bundled jemalloc, you can set this value to `1` only as I build it with threads disabled. Just in case.

**Comment by Koopman** [comment]
I am still seeing this error on v 2.1 (updated yesterday)

**Comment by chkpnt** [comment]
I'm also experiencing this issue with 3.10.2.

> That should be fixed (and configurable!) now.

@vstakhov How to change the configuration? I can't find any blas setting in my configdump.
