### ISSUE TITLE
[BUG] cannot exec invalidate script in redis

### ISSUE THREAD

**Issue by RvdE** [rspamd/rspamd#3085]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
After upgrading to rspamd 2.0 my error log shows the following message every minute:
_cannot exec invalidate script in redis: ERR Error running script (call to f_a43800941e2820ed8d764d50dfd9c142beddde68): @enable_strict_lua:15: user_script:6: Script attempted to access nonexistent global variable 'cjson'_

### Steps to Reproduce

1. Upgrade to 2.0
2. Start rspamd
3. View error log

**Expected behavior**
No error shown in log

### Versions
Rspamd daemon version 2.0
OS: FreeBSD 12.0-RELEASE-p10 and 12.1-RC1.
CPU: Core i7 860

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by vstakhov** [comment]
Your Redis server version is unsupported.

**Comment by vstakhov** [comment]
Well, at least it looks like this. Cjson is obviously documented in https://redis.io/commands/eval

**Comment by RvdE** [comment]
I've found the issue. On FreeBSD both databases/redis and databases/redis-devel require ENABLE_CJSON_GLOBAL set to make cjson available globally. On OpenBSD they remove the #ifdef/#endif lines to always enable that code. I will create PR's for both so FreeBSD will become compatible with rspamd 2.0
