### ISSUE TITLE
[BUG] metrics warning if log level is set in local.d/logging.inc

### ISSUE THREAD

**Issue by leofeyer** [rspamd/rspamd#3089]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

I have noticed that if I specify the log level in the `local.d/logging.inc` file, there will be multiple of the following log entries:

```
proxy; insert_metric_result: detected NaN score for symbol NEURAL_HAM, replace it with zero
```

The log entries do not occur if the `level` directive is not used in the `local.d/logging.inc` file. 🤔 

### Steps to Reproduce

1. Create or edit the file `/etc/rspamd/local.d/logging.inc`, add `level = "notice";` and restart rspamd.
2. Observe the log and watch out for the warning above.
3. Remove the `level = "notice";` entry again and restart rspamd.

### Versions

Ubuntu 16.04
Intel Xenon Skylake
Rspamd 2.0

**Comment by vstakhov** [comment]
Yes, that's how log levels work. You don't see messages with less than specified log level... Not a bug. NAN score is likely a bug however...

**Comment by leofeyer** [comment]
You misunderstood. It does not matter which level I actually set.

The log entry is there as soon as I add `level = "<any level>"` to the `local.d/logging.inc` file. And as soon as I remove the `level =` line again, the message is no longer logged.

Even if I set the log level to `warning`, which is supposed to log only errors and warnings, this particular line is added multiple times.

```
# local.d/logging.inc
type = "syslog";
facility = "mail";
level = "warning";
```

As soon as I remove the line, the message is no longer logged.

```
# local.d/logging.inc
type = "syslog";
facility = "mail";
```

This cannot be "how log levels work", can it?

**Comment by whataboutpereira** [comment]
> ```
> # local.d/logging.inc
> type = "syslog";
> facility = "mail";
> ```
> 
> This cannot be "how log levels work", can it?

The default log level is info, which is two levels less verbose than warning.

**Comment by vstakhov** [comment]
The default is indeed `info` but it is two levels **more** verbose than warning.

**Comment by whataboutpereira** [comment]
> 
> 
> The default is indeed `info` but it is two levels **more** verbose than warning.

*sigh* Indeed. There goes my last bit of credibility.

**Comment by leofeyer** [comment]
FYI, the "detected NaN score for symbol NEURAL_HAM" message went away after I had deleted the existing Redis databases. Maybe some old entries were causing the problem?

@vstakhov Please feel free to close this issue if you do not want to follow up on it. And keep up the good work – Rspamd 2 is great!
