### ISSUE TITLE
[BUG] mx_check module doc states greylist_invalid = false, but it's true

### ISSUE THREAD

**Issue by aletheia7** [rspamd/rspamd#3092]
The [MX Check module](https://www.rspamd.com/doc/modules/mx_check.html) states a ```greylist_invalid = false;``` default. However, ```greylist_invalid = true;``` is the default in [mx_check.lua](https://github.com/rspamd/rspamd/blob/master/src/plugins/lua/mx_check.lua#L37)

### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Expected behavior**

Either update the documentation or change the default in mx_check.lua.

### Versions

1.9.4
Debian Testing/Buster

**Comment by moisseev** [comment]
I've updated the documentation (rspamd/rspamd.com@a28fbc9a5f27bbeeda58db8470e94e2e554d0227).
