### ISSUE TITLE
[BUG] pid not being written in $RUNDIR/rspamd.pid

### ISSUE THREAD

**Issue by geekteq** [rspamd/rspamd#3096]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
I'm trying to setup monit to monitor rspamd for me so it would restart in case of any issues (going away) but for some reason, although configured in config.inc (both in regular and local.d) it doesn't actually seems to create a pid-file that I can monitor. 

### Steps to Reproduce

1. Checked default config.inc for "pid_file" (as per documentation) but was mentioned as "pidfile" instead with $RUNDIR/rspamd.pid so I put both pidfile and pid_file in local.d/config.inc - also verified in /etc/init.d/rspamd where it should be putting it /run/rspamd/rspamd.pid
2. Restarted rspamd 
3. Checked for a pid-file in $RUNDIR - nope - nothing there.. not in /var/run/rspamd either

**Expected behavior**
I expect rspamd to put a pidfile in the run-directory

### Versions
Rspamd daemon version 2.1-git.52d43acb2
Debian Stretch - Linux alpha 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux

**Comment by vstakhov** [comment]
I'm not keen to debug systemd or your system's configuration, sorry. Closing.
