### ISSUE TITLE
[BUG] Razor not working

### ISSUE THREAD

**Issue by jirireischig** [rspamd/rspamd#3098]
### Prerequisites

**Describe the bug**
External scanner razor is not working.
Errors in log:
lua; external_services.lua:124: unknown external scanner type: razor
lua; external_services.lua:194: cannot add rule: "razor"

### Steps to Reproduce

1. configure razor by example config in https://rspamd.com/doc/modules/external_services.html#razor-specific-details

**Expected behavior**
Razor test is working with example config in rspamd's documentation.

### Versions

2.0
Centos 7.7

**Comment by HansVanEijsden** [comment]
@jirireischig yes, can confirm: exactly the same error here, after applying https://github.com/rspamd/rspamd/pull/3101 manually. Debian Stretch, 64 bit.

**Comment by jirireischig** [comment]
Razor plugin working good with the patch.
Thank you very much.
