### ISSUE TITLE
[Feature] Task timeout logging improvement.

### ISSUE THREAD

**Issue by whataboutpereira** [rspamd/rspamd#3100]
Currently when the global timeout is reached, the following is logged:

`2019-10-17 19:04:23 #8210(normal) <671ac7>; task; rspamd_task_timeout: processing of task time out: 20.0 second spent; forced processing`

Would it be possible to mention the actual task/module in that log entry? It would make looking for the actual culprit much easier.

Thanks!

**Comment by vstakhov** [comment]
It is not possible as this is triggered by libev timer that is irrelevant to other modules. However, it is possible to print async events pending in it's session (such as `lua_dns` or `lua_tcp`). That won't be bound to symbols however, though the former seems doable in fact...

**Comment by whataboutpereira** [comment]
Naughty bot.
