### ISSUE TITLE
[BUG]rspamd 2.0-1~stretch crashes on startup

### ISSUE THREAD

**Issue by dmallor** [rspamd/rspamd#3102]
After upgrading rspam on Debian stable stretch 2.0.1 (from 1.9.4) is crashing at startup.  This issue looks exactly like the one that was reported for sid so surprised this made it to stable.  manually reverting back to 1.9.4 got it back up and running. 

Other issue
https://github.com/rspamd/rspamd/issues/3079

messages on startup 
   11.669849] rspamd[755]: segfault at 0 ip 00007f4f237390d9 sp 00007fffd8a70ee0 error 4 in librspamd-server.so[7f4f23615000+a78000]
   14.186466] rspamd[1399]: segfault at 0 ip 00007f7c271ed0d9 sp 00007fffd6e6b2b0 error 4 in librspamd-server.so[7f7c270c9000+a78000]
   15.402089] rspamd[1694]: segfault at 0 ip 00007fc69798d0d9 sp 00007fffc8db26e0 error 4 in librspamd-server.so[7fc697869000+a78000]
   16.206587] rspamd[1778]: segfault at 0 ip 00007f19bbbed0d9 sp 00007fff072ec6c0 error 4 in librspamd-server.so[7f19bbac9000+a78000]
   16.817094] rspamd[1797]: segfault at 0 ip 00007ffb823540d9 sp 00007ffc7d6d7b80 error 4 in librspamd-server.so[7ffb82230000+a78000]
   17.683050] rspamd[1865]: segfault at 0 ip 00007f1af571e0d9 sp 00007ffc44545ec0 error 4 in librspamd-server.so[7f1af55fa000+a78000]
   18.456332] rspamd[1918]: segfault at 0 ip 00007f1aea6330d9 sp 00007ffce1d98eb0 error 4 in librspamd-server.so[7f1aea50f000+a78000]
   19.311146] rspamd[1974]: segfault at 0 ip 00007f3cd90d80d9 sp 00007ffc29a54ba0 error 4 in librspamd-server.so[7f3cd8fb4000+a78000]
   20.173850] rspamd[2004]: segfault at 0 ip 00007f189b64d0d9 sp 00007ffd1d973190 error 4 in librspamd-server.so[7f189b529000+a78000]
   20.898903] rspamd[2063]: segfault at 0 ip 00007f4134f7d0d9 sp 00007ffe0c8b8740 error 4 in librspamd-server.so[7f4134e59000+a78000]

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**

### Versions

You can get this information from copy and pasting the output of `rspamd --version` from the command line. Also, please include the **OS** and what version and architecture including the generation of CPU model (e.g. Haswell) where applicable,  of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by vstakhov** [comment]
WTF is 2.0.1?

**Comment by vstakhov** [comment]
The package that is currently in stretch repo should not be affected by #3079

**Comment by dmallor** [comment]
Very strange as this package was just pushed Friday the 11th for an update and afterwards will not start with seg faults.  I went back to the previous version rspamd_1.9.4-3~stretch and it it back up and running. 

Package Details:

apt-listchanges: Reading changelogs...
apt-listchanges: Changelogs
---------------------------

--- Changes for rspamd ---
rspamd (2.0-1~stretch) stretch; urgency=low

  * New release.

**Comment by dmallor** [comment]
Looks like the update came from rspam stretch source not Debian.  

rspamd.list 
deb http://rspamd.com/apt-stable/ stretch main

**Comment by amotl** [comment]
Dear Vsevolod,

first things first: Thanks for your amazing work on `rspamd`!

We can confirm the same segfault issue after receiving the same package `rspamd_2.0-1~stretch_amd64.deb` from `deb http://rspamd.com/apt-stable/ stretch main` right now. We reverted back to `rspamd_1.9.4-2~stretch_amd64.deb` in order fix things.

Thanks already for looking into this.

With kind regards,
Andreas.

**Comment by m0hzn** [comment]
We confirm this segfault with 2.0-1 AND 2.1-1 but from https://rspamd.com/apt-stable/ xenial, we had to revert to 1.9.4.

Thanks that you are looking into this and keep up the amazing work, rspamd has helped us alot this year.

**Comment by PG248** [comment]
I can confirm the issue with 2.1-1 from repository deb http://rspamd.com/apt-stable/ stretch main on Debian stretch. Had to revert to 1.9.4.

**Comment by vstakhov** [comment]
Unrelated to the original issue, closing.
