### ISSUE TITLE
[BUG] Statfile: length: 0

### ISSUE THREAD

**Issue by locojohn** [rspamd/rspamd#3105]
Hi,

I am running rspamd v2.0 and I am not sure if it's a bug or is this normal behaviour.  

After running "rspamc stat", it always shows Statfile length being 0.

```
# rspamc stat
Results for command: stat (0.024 seconds)
Messages scanned: 34516
Messages with action reject: 9718, 28.15%
Messages with action soft reject: 0, 0.00%
Messages with action rewrite subject: 306, 0.88%
Messages with action add header: 928, 2.68%
Messages with action greylist: 1581, 4.58%
Messages with action no action: 21983, 63.68%
Messages treated as spam: 10952, 31.73%
Messages treated as ham: 23564, 68.26%
Messages learned: 286
Connections count: 0
Control connections count: 3
Pools allocated: 82
Pools freed: 50
Bytes allocated: 20.71MiB
Memory chunks allocated: 83
Shared chunks allocated: 16
Chunks freed: 0
Oversized chunks: 4
Fuzzy hashes in storage "FUZZY_LOCAL": 5
Fuzzy hashes in storage "rspamd.com": 789273246
Fuzzy hashes stored: 789273251
Statfile: BAYES_SPAM type: redis; length: 0; free blocks: 0; total blocks: 0; free: 0.00%; learned: 19; users: 2; languages: 0
Statfile: BAYES_HAM type: redis; length: 0; free blocks: 0; total blocks: 0; free: 0.00%; learned: 22; users: 1; languages: 0
Total learns: 41
```

I can see that messages are being learned as SPAM and HAM, but how come Statfile length is 0?  There are no errors in Rspamd log file.  Maybe this isn't a bug and I misunderstand something?

**Comment by locojohn** [comment]
I am using redis as backend and stock statistic.conf.

**Comment by HansVanEijsden** [comment]
I can confirm, although Bayes also works fine here.

```
# /usr/bin/rspamc -h /var/run/rspamd/rspamd.sock stat
Results for command: stat (0.011 seconds)
Messages scanned: 519517
Messages with action reject: 292900, 56.37%
Messages with action soft reject: 0, 0.00%
Messages with action rewrite subject: 0, 0.00%
Messages with action add header: 28890, 5.56%
Messages with action greylist: 42985, 8.27%
Messages with action no action: 154742, 29.78%
Messages treated as spam: 321790, 61.94%
Messages treated as ham: 197727, 38.05%
Messages learned: 16254
Connections count: 0
Control connections count: 829
Pools allocated: 10097
Pools freed: 10070
Bytes allocated: 21.65MiB
Memory chunks allocated: 84
Shared chunks allocated: 18
Chunks freed: 0
Oversized chunks: 744
Fuzzy hashes in storage "rspamd.com": 789512666
Fuzzy hashes stored: 789512666
Statfile: BAYES_SPAM type: redis; length: 0; free blocks: 0; total blocks: 0; free: 0.00%; learned: 12657; users: 13; languages: 0
Statfile: BAYES_HAM type: redis; length: 0; free blocks: 0; total blocks: 0; free: 0.00%; learned: 4653; users: 35; languages: 0
Total learns: 17310
```

**Comment by locojohn** [comment]
So is this not an issue?

**Comment by Viste** [comment]
confirm
`[Infrastructure] some-user@some-host /etc # rspamc stat
Results for command: stat (0.038 seconds)
Messages scanned: 3494
Messages with action reject: 11, 0.31%
Messages with action soft reject: 0, 0.00%
Messages with action rewrite subject: 0, 0.00%
Messages with action add header: 753, 21.55%
Messages with action greylist: 4, 0.11%
Messages with action no action: 2726, 78.01%
Messages treated as spam: 764, 21.86%
Messages treated as ham: 2730, 78.13%
Messages learned: 137
Connections count: 0
Control connections count: 72
Pools allocated: 157
Pools freed: 120
Bytes allocated: 27.12MiB
Memory chunks allocated: 217
Shared chunks allocated: 18
Chunks freed: 0
Oversized chunks: 13
Fuzzy hashes in storage "sph_fuzzy": 4294967109
Fuzzy hashes in storage "rspamd.com": 1803522832
Fuzzy hashes stored: 6098489941
Statfile: BAYES_SPAM type: redis; length: 0; free blocks: 0; total blocks: 0; free: 0.00%; learned: 41; users: 4; languages: 0
Statfile: BAYES_HAM type: redis; length: 0; free blocks: 0; total blocks: 0; free: 0.00%; learned: 62; users: 2; languages: 0
Total learns: 103
`
