### ISSUE TITLE
[BUG] DCC used by external services not insert symobls

### ISSUE THREAD

**Issue by jirireischig** [rspamd/rspamd#3106]
**Describe the bug**
Dcc don't insert symbol DCC_REJECT  when it's configured as external services.

### Steps to Reproduce
Configure Dcc in external_services.conf by example conf: https://rspamd.com/doc/modules/external_services.html#dcc-specific-details

**Expected behavior**
Symbol DCC_REJECT is inserted same as it's inserted when Dcc is configured by Dcc module:
 https://rspamd.com/doc/modules/dcc.html

### Versions

Centos 7.7
Rspamd 2.0

### Additional Information

local.d/external_services.conf
`dcc {
        servers = "/etc/dcc/dccifd";
        timeout = 15s;
}
`
local.d/dcc.conf
`
socket = "/etc/dcc/dccifd";
timeout = 30s;
`

example log Dcc as external services:

Oct 21 11:04:02  rspamd[10776]: <926a25>; dcc; dcc.lua:183: DCC result=R disposition=R header="X-DCC--Metrics: ecn3.ecn.cz 1480; bulk Body=many Fuz1=many Fuz2=many\0a\0a"
Oct 21 11:04:02  rspamd[10776]: <926a25>; lua; common.lua:108: dcc: result - hashfound: "bulk Body=many Fuz1=many Fuz2=many  - score: 4"
Oct 21 11:04:02  rspamd[10776]: <926a25>; dcc; common.lua:275: dcc: saved cached result for rs_dcc_0bebef81a0369b5aea62ebc7260b4305: bulk Body=many Fuz1=many Fuz2=many  - score 4 - ttl 7200
Oct 21 11:04:03  rspamd[10776]: <926a25>; proxy; rspamd_task_write_log: id: <75871.8951878.1571648628052@epocket.pk>, ... DCC(0.00){bulk Body=many Fuz1=many Fuz2=many ;},...
Oct 21 11:04:03  rspamd[10776]: <926a25>; proxy; rspamd_protocol_http_reply: regexp statistics: 0 pcre regexps scanned, 3 regexps matched, 184 regexps total, 107 regexps cached, 0B scanned using pcre, 2.33KiB scanned total

**Comment by jirireischig** [comment]
I add  score to configuration local.d/external_services.conf:
```
dcc {
        servers = "/etc/dcc/dccifd";
        timeout = 15s;
        score = 2
}
```

It help's to insert symbol like
`DCC(2.00)[bulk Body=1 Fuz1=1 Fuz2=many ];`

default_score=1 is not used without defined score in local config.

But symbol DCC_REJECT is not inserted by Dcc as external services.

**Comment by whataboutpereira** [comment]
I suspect you need the same:

symbol_fail = 'DCC_FAIL';
symbol = 'DCC_REJECT';
symbol_bulk = 'DCC_BULK';

In external services dcc config.

**Comment by jirireischig** [comment]
If I add `symbol = 'DCC_REJECT';` to config symbol DCC is change to DCC_REJECT.

I don't known if it is OK.
Why defaults from rspamd/lualib/lua_scanners/dcc.lua file is not used?
