### ISSUE TITLE
[Feature] Virustotal support

### ISSUE THREAD

**Issue by vstakhov** [rspamd/rspamd#3109]
## Summary

Cool to support

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

## Describe alternatives you've considered

A clear and concise description of the alternative solutions you've considered. Be sure to explain why Rspamd's existing customizability isn't suitable for this feature.

## Additional context

Add any other context about the feature request here.

**Comment by vstakhov** [comment]
Done.

**Comment by yoshimo** [comment]
This is only supporting the private unlimited access , not the public version with ratelimiting for testing right?

**Comment by klausenbusk** [comment]
> This is only supporting the private unlimited access , not the public version with ratelimiting for testing right?

The code only use the [/file/report](https://developers.virustotal.com/reference#url-report) endpoint which is part of the public api.

**Comment by pete1019** [comment]
Could you please implement private api as well since this is not limited to 4 uploads a minute.
Or is rspamd able to limit to 4 uploads a minute and queue more?
Thanks!

**Comment by pete1019** [comment]
Since the public API is limited to 4 uploads a minute, is rspamd able to limit to 4 uploads a minute and queue more the second Minute and so on?
Thanks!

**Comment by jneuhauser** [comment]
First, very cool module!

@pete1019 
As you see here: 
https://github.com/rspamd/rspamd/blob/9c2d72c6eba3fc05fd7459e388ea7c92eb87095f/lualib/lua_scanners/virustotal.lua#L113-L117
Only "virustotal request rate limit exceeded" is added to your log and your mail gets a defined fail symbol with 1.0 score added!

I'm no expert, but i think the failed symbol get's only added if it's defined in your config like:
**antivirus.conf**
```
virustotal {
  apikey = "...":
  symbol_fail = "VIRUSTOTAL_FAIL";
}
```
Then rspamd will add the header "VIRUSTOTAL_FAIL: rate limit exceeded".

Correct me if this assumption is wrong as I'm no rspamd expert.

**Comment by pete1019** [comment]
@jneuhauser thank you for your input but does this answer my question from 2019 in any way?
"Since the public API is limited to 4 uploads a minute, is rspamd able to limit to 4 uploads a minute and queue more the second minute and so on?"

**Comment by jneuhauser** [comment]
Nothing changed, only some bugfixes...
But if i think about your feature request and mine to do real file scans, there are a lot edge cases that one has to handle and the current state of this module is simple and good.

**Comment by pete1019** [comment]
@jneuhauser when this is done "task:insert_result(rule.symbol_fail, 1.0, 'rate limit exceeded')" does that mean rspamd will scan that file later again?

**Comment by jneuhauser** [comment]
No, only the above mentioned fail symbol get added...
You can assign a score to this symbol, but this make not much sense.
