### ISSUE TITLE
[BUG] redis/sentinel: READONLY You can't write against a read only slave.

### ISSUE THREAD

**Issue by int-avoss** [rspamd/rspamd#3113]
**Describe the bug**
rspamd tries to write against a readonly-redis in several modules. 
sentinel doesn't resolv the current master correctly and delivers a readonly-redis.

### Steps to Reproduce

1. receiving an email

**Expected behavior**

rspamd selects the current writeable redis-server via sentinel-protocol.

### Versions

`Rspamd daemon version 2.1 (commit 0d916d0c7a636fcd72d80f73193d8543a1e6dcd3)`

### Additional Information

the correct redis-master is deliverd via "redis-cli sentinel get-master-addr-by-name XXXXX".

the following messages can be found in log:

`Oct 23 08:52:33 XXXXX rspamd[7908]: <185f9f>; lua; neural.lua:299: cannot store ANN profile for default:default at rn_default_default_sjqtqjqc_0 : READONLY You can't write against a read only slave.
`

`Oct 23 08:52:33 XXXXX rspamd[7908]: <185f9f>; lua; history_redis.lua:96: got error READONLY You can't write against a read only slave. when writing history row: no value
`

`Oct 23 08:58:32 XXXXX rspamd[7905]: <402688>; lua; common.lua:272: failed to save virus cache for OK -> "rs_cl_979f7b0745a024e02007d3b03eaada14": READONLY You can't write against a read only slave.
`

`Oct 23 10:49:21 XXXXX rspamd[7196]: <ff3926>; lua; greylist.lua:356: got error READONLY You can't write against a read only slave. when setting greylisting record on server xxx.xxx.xxx.xxx
`

**Comment by vstakhov** [comment]
This issue lacks information badly while all telepaths are on vacation so far.

**Comment by int-avoss** [comment]
rspamd uses the following redis-config in /etc/rspamd/local.d/redis.conf:

```
servers = "172.16.127.101:6379,172.16.127.102:6379,172.16.127.103:6379";
sentinels = "172.16.127.101:26379,172.16.127.102:26379,172.16.127.103:26379";
sentinel_watch_time = 30sec;
```
the redis-cluster is working/Online, all sentinels and redis-nodes are up and connectable for rspamd.

A redis-cli-query (to all three sentinels) via "sentinel get-master-addr-by-name" gives 

1) "172.16.127.101"
2) "6379"

as writeable node.

Manual tests are giving expected results:

```
# redis-cli -h 172.16.127.101 -p 6379  SET mykey "Hello"
OK
```

```
# redis-cli -h 172.16.127.102 -p 6379  SET mykey "Hello"
(error) READONLY You can't write against a read only slave.
```

```
# redis-cli -h 172.16.127.103 -p 6379  SET mykey "Hello"
(error) READONLY You can't write against a read only slave.
```

rspamd seems to not use this information about the writeable node correctly because we receive several errors like "READONLY You can't write against a read only slave" from rspamd.

What additional information is needed ?

**Comment by int-avoss** [comment]
It may be related to the confiuration:

`sentinel_masters_pattern = "^redis-ha-mx.*$";`

if i disable "sentinel_masters_pattern" to let rspamd select all available masters, the messages about the RO-slave are gone so far, may the hyphens cause the trouble ?

**Comment by vstakhov** [comment]
```
LuaJIT 2.0.5> s = 'redis-ha-mx-1'
LuaJIT 2.0.5> s:match('^redis-ha-mx.*$')
nil
LuaJIT 2.0.5> s:match('^redis%-ha%-mx.*$')
redis-ha-mx-1
LuaJIT 2.0.5>
```

Not a bug.
