### ISSUE TITLE
[BUG] Multiple classifiers on redis working incorrectly

### ISSUE THREAD

**Issue by resec** [rspamd/rspamd#3129]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
When there are multiple bayes classifiers, if `min_learns` for them are set differently and not all them are fulfilled. Then all the classifiers are not working.

### Steps to Reproduce

Setup two classifiers in `local.d/statistic.conf`:
```
classifier "bayes" {
    name = "bayes_one"
    tokenizer {
        name = "osb";
    }
    backend = "redis";
    new_schema = true;
    store_tokens = false;
    signatures = false;
    min_learns = 1;

    statfile {
        symbol = "BAYES_HAM_ONE";
        spam = false;
    }
    statfile {
        symbol = "BAYES_SPAM_ONE";
        spam = true;
    }
}
classifier "bayes" {
    name = "bayes_two"
    tokenizer {
        name = "osb";
    }
    backend = "redis";
    new_schema = true;
    store_tokens = false;
    signatures = false;
    min_learns = 5000;

    statfile {
        symbol = "BAYES_HAM_TWO";
        spam = false;
    }
    statfile {
        symbol = "BAYES_SPAM_TWO";
        spam = true;
    }
}
```

Start the rspamd and learn some messages for both spam and ham:
```
rspamc learn_ham -c bayes_one /etc/rspamd/scores.d
rspamc learn_spam -c bayes_one /etc/rspamd/modules.d

rspamc learn_ham -c bayes_two /etc/rspamd/scores.d
rspamc learn_spam -c bayes_two /etc/rspamd/modules.d
```

Start any file:
```
rspamc /etc/rspamd/common.conf
```

And you will see no bayes symbols are output.

**Expected behavior**
When one classifier's `min_learns` is fulfilled, it starts working right away.

### Versions

Rspamd daemon version 2.1

### Additional Information

It is because that in 
https://github.com/rspamd/rspamd/blob/7a7791926e0ad43ce69d3ba9cc5c73dc8fa9d3a2/src/libstat/stat_process.c#L427-L431

Any error in pulling the tokens from redis for one statfile, all classifiers are stopped.

**Comment by resec** [comment]
https://github.com/resec/rspamd/commit/65f99530f454f1dce95ddc0e9dd04a43758274bc fixed part of issue, at least when one classifier's `min_learns` is met, it starts working right away.

However, I found more to fix:

- When running `rspamc learn_xxx`, the `can_learn` is based on the results of all classifiers, but it should be based on each classifier only right? 
- `rspamc learn_xxx` returns an error if any statfile's `min_learns` is not met, but the learning (for the specific statfile) is actually succussed.

**Comment by resec** [comment]
https://github.com/resec/rspamd/commit/606c653671216b6575e4966e4c84a2f8da2fe43f fixed the below issue:

- `rspamc learn_xxx` returns an error if any statfile's `min_learns` is not met, but the learning (for the specific statfile) is actually succussed.

Now it only outputs a warning about skipping obtaining bayes tokens instead of raising an error.
```
rspamd_redis_connected: skip obtaining bayes tokens for BAYES_HAM_TWO of classifier bayes_two: not enough learns 1; 5000 required
rspamd_redis_connected: skip obtaining bayes tokens for BAYES_SPAM_TWO of classifier bayes_two: not enough learns 2; 5000 required
```

**Comment by resec** [comment]
https://github.com/resec/rspamd/commit/14495547dea7e4a0c14cf1507ba7def74b58a4ce fixed the below issue:
- When running `rspamc learn_xxx`, the `can_learn` or not is based on the results of all classifiers.
- Multiple classifier's token value in redis is mixed together without prefix properly defined

So the idea is just prepending classifier's name (if defined) into both `redis_cache` and `redis_backend` object key, then multiple classifiers can work together harmoniously inside one redis.

**Comment by resec** [comment]
@vstakhov, at this point, I am not sure if this is a fix or maybe a feature implementation already, but with these patch, rspamd can support the case like having multiple classifiers working together.

**e.g. one for phishing, another one for bulk message, and last one for per user spam.**

So I would like to create a PR for merging and could you take a little bit time to review?

And below some of things I think may need further work:

- `rspamc stat` is not reporting the classifier of statfile, which could be enhanced
-  `learnspam` and `learnham` api should report result for each classifier.

**Comment by vstakhov** [comment]
Yes, please open a PR. I clearly see some issues with your proposed patches but I cannot review those without a PR.
