### ISSUE TITLE
WEBUI, configuration: local > Save map error: Cannot open map: Permission denied

### ISSUE THREAD

**Issue by alfredo-ardito** [rspamd/rspamd#3131]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
After updating rspamd to version 2.1 I cannot edit the configuration files anymore in webui. I'm getting this error:
local > Save map error: Cannot open map: Permission denied
The 2 files are /etc/rspamd/local.d/sender_whitelist.map and /etc/rspamd/local.d/recipient_whitelist.map with the owner set to _rspamd

I have the following configuration in /etc/rspamd/local.d/multimap.conf:

RECIPIENT_WHITELIST {
      type = "rcpt";
      prefilter = true;
      map = "${LOCAL_CONFDIR}/local.d/recipient_whitelist.map";
      action = "accept";
  }

SENDER_WHITELIST {
      type = "from";
      prefilter = true;
      map = "${LOCAL_CONFDIR}/local.d/sender_whitelist.map";
      action = "accept";
  }

In webui, under configuration, it displays the read and write label on both files:
/etc/rspamd/local.d/sender_whitelist.map
/etc/rspamd/local.d/recipient_whitelist.map

With Rspamd daemon version 2.0 never got any error when editing both files in WebUI>configuration

### Versions
Rspamd daemon version 2.1

**Comment by andryyy** [comment]
What's the output of 'ls -la /etc/rspamd/local.d'?

**Comment by alfredo-ardito** [comment]
ls -la /etc/rspamd/local.d
```
drwxr-xr-x 3 root    root      249 Nov  1 23:20 .
drwxr-xr-x 7 root    root     4096 Oct 31 08:40 ..
-rw-r--r-- 1 root    root     1586 Nov  1 22:31 dkim_domains.map
-rw-r--r-- 1 root    root      624 Nov  1 22:32 dkim_selectors.map
-rw-r--r-- 1 root    root       56 Sep 30 20:59 history_redis.conf
-rw-r--r-- 1 root    root     1546 Oct 12 09:27 milter_headers.conf
-rw-r--r-- 1 root    root      597 Nov  1 22:16 multimap.conf
-rw-r--r-- 1 _rspamd _rspamd    18 Oct  3 07:54 recipient_whitelist.map
-rw-r--r-- 1 root    root       23 Sep 30 20:58 redis.conf
-rw-r--r-- 1 _rspamd _rspamd   153 Nov  1 23:20 sender_whitelist.map
drwxr-xr-x 2 root    root    12288 Nov  1 22:33 users
-rw-r--r-- 1 root    root      242 Sep 30 21:08 worker-controller.inc

```

**Comment by andryyy** [comment]
Can you try `chmod _rspamd:_rspamd /etc/rspamd/local.d` ?

**Comment by alfredo-ardito** [comment]
I've tried `chown _rspamd:_rspamd /etc/rspamd/local.d`
and it works now. I wanted to try that before but I thought it could cause security issues. 
Solved, Thx

**Comment by alfredo-ardito** [comment]
I've tried `chown _rspamd:_rspamd /etc/rspamd/local.d`
and it works now. I wanted to try that before but I thought it could cause security issues. 
Solved, Thx

**Comment by bundyrob** [comment]
I am receiving this error on a new installation.
 configuration in /etc/rspamd/local.d/multimap.conf
    WHITELIST_SENDER_DOMAIN {
      type = "from";
      filter = "email:domain:tld";
      map = "/etc/rspamd/local.d/whitelist.sender.domain.map";
      score = -100.0 # large

/etc/rspamd/local.d# ls -la
total 88
drwxr-xr-x 3 root root 4096 Jun 19 22:28 .
drwxr-xr-x 7 root root 4096 Jun 17 23:21 ..
-rw-r--r-- 1 root root 1411 Jun 17 21:48 antivirus.conf
-rw-r--r-- 1 root root  262 Jun 17 21:48 antivirus_group.conf
-rw-r--r-- 1 root root   64 Jun 17 21:48 classifier-bayes.conf
-rw-r--r-- 1 root root   71 Jun 17 21:52 dkim_domains.map
-rw-r--r-- 1 root root   29 Jun 17 21:52 dkim_selectors.map
-rw-r--r-- 1 root root  129 Jun 17 21:48 dkim_signing.conf
-rw-r--r-- 1 root root   27 Jun 17 21:48 greylist.conf
-rw-r--r-- 1 root root  205 Jun 17 21:48 groups.conf
-rw-r--r-- 1 root root   56 Jun 17 21:43 history_redis.conf
-rw-r--r-- 1 root root  116 Jun 17 21:48 milter_headers.conf
-rw-r--r-- 1 root root  171 Jun 19 19:09 multimap.conf
-rw-r--r-- 1 root root  210 Jun 17 21:48 mx_check.conf
-rw-r--r-- 1 root root  608 Jun 17 21:48 neural.conf
-rw-r--r-- 1 root root  452 Jun 17 21:48 neural_group.conf
-rw-r--r-- 1 root root   78 Jun 17 21:48 options.inc
-rw-r--r-- 1 root root   22 Jun 17 21:48 redis.conf
drwxr-xr-x 2 root root 4096 Jun 21 09:51 users
-rw-r--r-- 1 root root  847 Jun 17 21:48 users.conf
-rw-rw-rw- 1 root root  526 Jun 19 22:27 whitelist.sender.domain.map
-rw-r--r-- 1 root root  242 Jun 17 21:54 worker-controller.inc
 number to confirm this is working. planning on reducing this once sure
 }
 Config is whitelist.sender.domain.map
domain_1
domain_2
domain_3 #2837 

used chmod a-+w to get whitelist.sender.domain.map to display read write.

when save is used after change/no change to whitelist.sender.domain.map 
I get the error " local > Save map error: Cannot open map: Permission denied "

**Comment by moisseev** [comment]
> used chmod a-+w to get whitelist.sender.domain.map to display read write.

To modify this file rspamd also needs write permission to the directory. I would rather move this map into the `/var/lib/rspamd/`.

BTW, `2.1` is a bit outdated. Please consider using packages from Rspamd official [repository](https://rspamd.com/downloads.html) .

>  Debian standard repos notes
Please DO NOT use those packages.
Please DO NOT use those packages!!
Please DO NOT use those packages!!!
Rspamd is also available in some versions of Debian and Ubuntu. Please DO NOT use those packages, as they are not supported in any way. Any issues or feature requests related to the packages from Debian provided distros will be closed with no feedback (or even rage feedback). Just don’t do it, you are warned!

**Comment by bundyrob** [comment]
Thank you.
Moved to /var/lib/rspamd chown to _rspamd:_rspamd and restarted 
works great
