### ISSUE TITLE
[BUG] Segmentation fault due do config reload

### ISSUE THREAD

**Issue by ralphM78** [rspamd/rspamd#3133]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
"systemctl reload rspamd" causes segmentation fault and old neural data are gone.

### Steps to Reproduce

systemctl reload rspamd

**Expected behavior**

reloading config without segmentation fault and using learned neural data.

### Versions

Ubuntu 16.04.6 LTS
rspamd 2.1-1~xenial

### Additional Information

rspamd log : 

#31341(main) rspamd_crash_sig_handler: caught fatal signal 11(Segmentation fault), pid: 31341, trace: 
#31341(main) rspamd_print_crash: 0: 000000000048FD1F: nallocm()+0x12b3f
#31341(main) rspamd_print_crash: 1: 0000000000477A5D: free()+0x31d
#31341(main) rspamd_print_crash: 2: 00007F8E143DA39F: corei7_hs_free_database()+0x1f
#31341(main) rspamd_print_crash: 3: 00007F8E14044639: rspamd_multipattern_destroy()+0x79
#31341(main) rspamd_print_crash: 4: 00007F8E14092A81: rspamd_url_init()+0x41
#31341(main) rspamd_print_crash: 5: 00007F8E14047592: rspamd_config_post_load()+0x322
#31341(main) rspamd_print_crash: 6: 000000000042276D: _init()+0x10485
#31341(main) rspamd_print_crash: 7: 00007F8E12ED3F71: ev_invoke_pending()+0x71
#31341(main) rspamd_print_crash: 8: 00007F8E12ED4C4C: ev_run()+0xcbc
#31341(main) rspamd_print_crash: 9: 0000000000422156: _init()+0xfe6e
#31341(main) rspamd_print_crash: 10: 00007F8E14BFB830: __libc_start_main()+0xf0
#31341(main) rspamd_print_crash: 11: 00000000004142D9: _init()+0x1ff1
#31341(main) rspamd_print_crash: 12: 0000000000000000: <unknown>

[stack_trace.log](https://github.com/rspamd/rspamd/files/3800298/stack_trace.log)

**Comment by vstakhov** [comment]
Uh-oh, I have no ideas I'm afraid. Hardware info is likely useful in this case.

**Comment by ralphM78** [comment]
It's a vm on kvm. hwinfo output from guest, host or both ?

**Comment by arty-name** [comment]
I have almost the same issue with `avx2_hs_free_database` instead of `corei7_hs_free_database`: 

```
2019-11-13 15:37:48 #12390(main) rspamd_crash_sig_handler: caught fatal signal 11(Segmentation fault), pid: 12390, trace: 
2019-11-13 15:37:48 #12390(main) rspamd_print_crash: 0: 000000000048B26F: nallocm()+0x12a4f
2019-11-13 15:37:48 #12390(main) rspamd_print_crash: 1: 0000000000472F05: free()+0x275
2019-11-13 15:37:48 #12390(main) rspamd_print_crash: 2: 00007F5771A99FA2: avx2_hs_free_database()+0x12
2019-11-13 15:37:48 #12390(main) rspamd_print_crash: 3: 00007F57716138E9: rspamd_multipattern_destroy()+0x79
2019-11-13 15:37:48 #12390(main) rspamd_print_crash: 4: 00007F5771661D21: rspamd_url_init()+0x41
2019-11-13 15:37:48 #12390(main) rspamd_print_crash: 5: 00007F5771616832: rspamd_config_post_load()+0x322
2019-11-13 15:37:48 #12390(main) rspamd_print_crash: 6: 000000000041DD9D: _init()+0x104b5
2019-11-13 15:37:48 #12390(main) rspamd_print_crash: 7: 00007F57703EAEE1: ev_invoke_pending()+0x71
2019-11-13 15:37:48 #12390(main) rspamd_print_crash: 8: 00007F57703EBBBC: ev_run()+0xcbc
2019-11-13 15:37:48 #12390(main) rspamd_print_crash: 9: 000000000041D786: _init()+0xfe9e
2019-11-13 15:37:48 #12390(main) rspamd_print_crash: 10: 00007F5772277B97: __libc_start_main()+0xe7
2019-11-13 15:37:48 #12390(main) rspamd_print_crash: 11: 000000000040F91A: _init()+0x2032

**Comment by nafetsreuab** [comment]
> It's a vm on kvm. hwinfo output from guest, host or both ?

We're seeing very strange problems like that on other applications since several days and latest qemu-update on proxmox/linux-kvm.

Could solve it by setting cpu type to host instead of kvm64. some cpu-flags are not passed through correctly (-cpu kvm64 was bad in our case).

**Comment by ralphM78** [comment]
No difference between host-passthrough or host-model. Same behavior.

**Comment by vstakhov** [comment]
I'm sorry but I'm not keen to debug your VM issues.

**Comment by ralphM78** [comment]
With 2.2-1~xenial this disappeared at my setup.

**Comment by vstakhov** [comment]
Btw, it might still be useful to try out ASAN packages just to ensure that the issue is not just hidden now...

**Comment by ralphM78** [comment]
@vstakhov indeed with ASAN packages there is no core dump but ASAN logs.
[rspamd-asan.1632.log](https://github.com/rspamd/rspamd/files/3893732/rspamd-asan.1632.log)
[rspamd-asan.1631.log](https://github.com/rspamd/rspamd/files/3893733/rspamd-asan.1631.log)
[rspamd-asan.1628.log](https://github.com/rspamd/rspamd/files/3893734/rspamd-asan.1628.log)
[rspamd-asan.1627.log](https://github.com/rspamd/rspamd/files/3893735/rspamd-asan.1627.log)
[rspamd-asan.1625.log](https://github.com/rspamd/rspamd/files/3893736/rspamd-asan.1625.log)
[rspamd-asan.1624.log](https://github.com/rspamd/rspamd/files/3893737/rspamd-asan.1624.log)
[rspamd-asan.1623.log](https://github.com/rspamd/rspamd/files/3893738/rspamd-asan.1623.log)
[rspamd-asan.1622.log](https://github.com/rspamd/rspamd/files/3893739/rspamd-asan.1622.log)
[rspamd-asan.1621.log](https://github.com/rspamd/rspamd/files/3893740/rspamd-asan.1621.log)
