### ISSUE TITLE
[BUG] multimap module does not recognize DMARC_POLICY_ALLOW

### ISSUE THREAD

**Issue by aletheia7** [rspamd/rspamd#3135]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
The multimap module does not recognize DMARC_POLICY_ALLOW symbol even though it is defined.

### Test
1. Add the following to multimap.conf 
```
B_TEST_DMARC {
    require_symbols = "DMARC_POLICY_ALLOW";
    score = -2.22;
}
```
2. Send yourself a test email from an outside email account. I use gmail. When the email arrives, I get DMARC_POLICY_ALLOW and R_DKIM_ALLOW, however, the B_TEST_DMARC symbol is not added. If I swap DMARC_POLICY_ALLOW for R_DKIM_ALLOW, B_TEST_DMARC is added.

The rspamd log message for gmail contains:

  ... DMARC_POLICY_ALLOW(0.00){gmail.com;none;}
R_DKIM_ALLOW(0.00){gmail.com:s=20161025;},R_SPF_ALLOW(0.00){+ip4:209.85.128.0/17;}, ...

**Expected behavior**
The DMARC_POLICY_ALLOW symbol should be recognized and  B_TEST_DMARC should be added with a -2.22 score.

### Versions

1.9.4

**Comment by vstakhov** [comment]
1. Your version is not supported, so it is pointless to open issues about it.
2. It is not an issue but XY problem. You need composites, not multimap.

**Comment by aletheia7** [comment]
I tested and see that composites will work. Thank you.
