### ISSUE TITLE
Different incoming and outgoing policy

### ISSUE THREAD

**Issue by waclaw66** [rspamd/rspamd#3143]
## Summary

I have switched from amavis-new to rspamd and there is one of features which I'm missing here.
It is a possibility to set different policy for incoming and outgoing zone.
When an email is received and it is a spam, I would like to set a rule to discard messages without notifying the sender. On the other hand, when a spam is sent from an authorized user, it's elegible to reject and inform a user immediately that something is wrong.

## Motivation

To improve the security of smtp server against spammers.

## Describe alternatives you've considered

An alternative could be to set discard on reject in any case, and also set autoreply about spam and undelivered message to authorized user only.

**Comment by croessner** [comment]
https://rspamd.com/doc/configuration/settings.html

That is what you want

**Comment by vstakhov** [comment]
You are breaking SMTP protocol guarantees but Rspamd allows `discard` action from 2.0. RTFM how to use it. Not a feature request, inappropriate for issue tracker.
