### ISSUE TITLE
[BUG] cannot create tree of regexp when processing

### ISSUE THREAD

**Issue by urmel1960** [rspamd/rspamd#3145]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Using multimap module with regex enabled maps. The following error occurs when trying to blacklist *.rocks tld:
` cannot create tree of regexp when processing '\\N\\.rocks': '\\N' at index 0 not supported.`

The error is reported by all workers (controller,rspamd-proxy, fuzzy, normal).

There are several similar entries like the one above in the map and they do work - although the first entry causes the error message.

According the documentation the regex should be hyperscan compatible. Hyperscan follows the regular expression syntax of the PCRE library.  The regex `\N\.rocks` causing the error is 
PCRE compliant:

Match any single character that is NOT a line break character (line feed) «\N»
Match the character “.” literally «\.»
Match the character string “rocks” literally (case sensitive) «rocks»

### Versions

Rspamd daemon version 2.1
Linux 4.15.0-66-generic #75-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

**Comment by vstakhov** [comment]
Why do you create this report in Rspamd project? Apparently, it is unrelated to Rspamd but is caused by hyperscan. Multimap uses `multipattern` library code that, in turn, uses hyperscan all the time. So you MUST NOT use any Hyperscan incompatible REs in this module. If you do then blame yourself (or ask Hyperscan developers to support your syntax construction). There is nothing Rspamd can do here.

**Comment by urmel1960** [comment]
People nowadays are always under pressure - I understand but there is no need to be rude - nobody wanted to blame you or anybody including myself . As I mentioned the RE I used is hyperscan compatible and I checked it before. 

A simple hint that this issue is something to go with to hyperscan would have been enough. If it would have been "apparently" that it is not rspamd related, I would have not recorded it here.

**Comment by vstakhov** [comment]
I'm sorry if that was rude, I'm just not very good in politeness and verbosity all the time. It wasn't intended anyway.

**Comment by vstakhov** [comment]
The main difference is that there is `re_cache` library that is responsible for task related regular expressions (e.g. `regexp` or `spamassassin` modules) and `multipattern` library. The first one has fallback to PCRE if Hyperscan fails, the second one is intended to be fast and modern, hence, it supports merely Hyperscan (or give full switch to PCRE if Hyperscan is not available). The proper thing is not to use any Hyperscan incompatible REs (or ask the devs to make them compatible).

**Comment by urmel1960** [comment]
> 
> 
> I'm sorry if that was rude, I'm just not very good in politeness and verbosity all the time. It wasn't intended anyway.

Accepted - Thanks - not everyone would be able to admit that.
Thank you for your answer and on this occasion especially for the great tool rspamd.

I will go to hyperscan to ask for help with the RE ...

**Comment by urmel1960** [comment]
just for completeness - here is the answer from the hyperscan guys:

> \N is currently not supported by Hyperscan.
> \N is not frequently used and matches anything except newline which is identical to .. The only difference is that \N ignores /s modifier. You may consider to replace it with . if possible.
> We will think about adding the support in next release.
>
