### ISSUE TITLE
[Feature] Need some options to match rules with multiple hits 

### ISSUE THREAD

**Issue by rspamd-internal** [rspamd/rspamd#3146]
## Description
Need a option to get messages matching a pattern multiple times just like the "multiple" option in spamassassin.

## Problem overview
Consider i need to match some payment phising rule, where subject contains multiple "payment" word. 
I want to match subjects like "Netflix payment payment" but it should not hit subjects like this "Netflix payment".
In spamassassin i can achieve this using below rule,

```
header      __CUSTOM_NETFLIX_SUB    Subject =~ /payment/i
tflags      __CUSTOM_NETFLIX_SUB      multiple maxhits=10
meta        CUSTOM_NETFLIX_SUB    (_CUSTOM_NETFLIX_SUB > 1)
score     CUSTOM_NETFLIX_SUB       10
```

There are many usecases like this that i cannot perform using rspamd.

## Additional context
Spamassassin plugin in rspamd does not work for these type of rules.
Is there any option to achieve this using the current rspamd version? Is it possible to create a option for this in future. TIA.

**Comment by vstakhov** [comment]
That's not a feature request in fact. Rspamd supports expressions like `A + B + ... > CONST`, and it doesn't need any `multiple` and `maxhits` crap - this is actually handled in final symbol itself as `nshots` option. However, expressions like `A > CONST` does not work. This needs to be fixed...

**Comment by rspamd-internal** [comment]
Cool, Is there any tasks in pipeline for doing such operations? I think it can be useful for many such cases.

**Comment by vstakhov** [comment]
Well, it seems that `A > CONST` should also work fine.

**Comment by vstakhov** [comment]
```
LuaJIT 2.0.5> function process_func(a) return atoms[a] end
LuaJIT 2.0.5> x = e.create('A > 10', {parse_func, process_func}, p)
LuaJIT 2.0.5> x:process()
0
LuaJIT 2.0.5> atoms = {}
LuaJIT 2.0.5> atoms['A'] = 11
LuaJIT 2.0.5> x:process()
1
LuaJIT 2.0.5> atoms['A'] = 10
LuaJIT 2.0.5> x:process()
0
```

**Comment by vstakhov** [comment]
Not an issue as it is already implemented and works, closing.
