### ISSUE TITLE
[Feature] SPF: allow check against other address than from_addr

### ISSUE THREAD

**Issue by zwetschgenbaeumle** [rspamd/rspamd#3152]
## Summary

I would like to do the spf check not against from_addr but an upstream "from_addr" one.

## Motivation

Most of our mails arrive indirectly via an upstream mail-relay (which we do not control). I would like to search for the "real" from_addr in the received-headers and then check against that one.

My suggestion would be:

* add an option from_ip_callback where you could register a lua function cb(task) which returns an ip address.

*  this cb is called from spf_symbol_callback() and stores the address in a task->spf_from_addr . If there is no such callback or the calback returns nil then set task->spf_from_addr =  task->from_addr.

* in spf_check_element use task->spf_from_addr instead of ask->from_addr

Maybe I misread the code this proposal is nonsense.

I then could set a lua_callback which would search the original from_addr in the received headers in the case the email arrived via the mail-relay and return that, or task:get_from_ip() in all other cases.

## Describe alternatives you've considered

I considered manipulating the tasks from_addr with task:set_from_ip() before spf_symbol_callback() is called and then setting it back afterwards. But I'm not sure if this could be done in a way that this does not influence other checks.

**Comment by vstakhov** [comment]
Yes, this feature is highly demanded and I have plans to add it at some point.

**Comment by zwetschgenbaeumle** [comment]
A, thanks.

I have written a small implementation of this feature which works for me:

https://github.com/zwetschgenbaeumle/rspamd.git
in branch stwm1. (commit 8ca8743e34055299d8158d621fcfc3b8668f2f78).

Running it since some days and seems to work fine. I use a mempool variable to pass the address.

In rspamd.local.lua I then have a symbol:

    rspamd_config.STWM_get_sfp_from_addr = {
        type = 'callback',
        callback = function(task)
        .....
        local mp = task:get_mempool()
        mp:set_variable('spf_from_addr', fromip);
        end,
    }
    rspamd_config:register_dependency('SPF_CHECK', 'STWM_get_sfp_from_addr');

**Comment by vstakhov** [comment]
My idea is slightly different. I want to kill the existing C plugin and write a Lua one with new bells and whistles :)

**Comment by dnavarrojr** [comment]
+1
I keep getting false positives despite putting the FROM address from the header in the whitelist.

**Comment by zwetschgenbaeumle** [comment]
seems to be implemented.
