### ISSUE TITLE
[User question] How to create symbol for specific authenticated user?

### ISSUE THREAD

**Issue by rpv-tomsk** [rspamd/rspamd#3155]
Hi,

How to create symbol for specific authenticated user?

We have ERP system which actively send "forged sender" mails.
`From` and `To` can be arbitrary, the only one common email attribute is authorized user value.
 
I want to disable FORGED_SENDER and several other symbols using `composites`, but I need a symbol to use as base.  I did not find how to do this using the multimap module, which is usually used for similar tasks.

Hope for your help.
Thanks for your product!

**Comment by rpv-tomsk** [comment]
Added #3158 with implementation.

**Comment by vstakhov** [comment]
I really like this sort of issues, thank you!
