### ISSUE TITLE
Rspamd: IPv6 IO write error - duplicated mails after Upgrade 1.9.4 to 2.1

### ISSUE THREAD

**Issue by serial-bug** [rspamd/rspamd#3167]
Hi there,

After Upgrade from 1.9.4 to 2.1 i see many IO write errors in rspamd.log.
I already opened an detailed issue on the opnsense repo:

https://github.com/opnsense/plugins/issues/1591

Thank you.

**Comment by vstakhov** [comment]
If your `localhost` resolves to ipv6 address then it is your issue not Rspamd's one.

**Comment by serial-bug** [comment]
localhost resolves to IPv4.

**Comment by vstakhov** [comment]
```
2019-11-23 21:05:00 #21813(rspamd_proxy) <377a74>; proxy; proxy_backend_master_error_handler: abnormally closing connection from backend: ::1, error: IO write error: Broken pipe, retries left: 5
```

Then how it comes that it tries to connect `::1`?

**Comment by serial-bug** [comment]
Exactly this is the problem.
With 1.9.4, rspamd never did this, and everything worked just fine.

**Comment by vstakhov** [comment]
Again, this is possible merely if your localhost resolves to `::1` in addition to `127.0.0.1`.

**Comment by serial-bug** [comment]
I know what you want to say, but i dont undestand why ipv6 is the problem ?
If i check the logs, rspamd communicates very well over ipv6.

(rspamd_proxy) <wuoxg5>; lua; lua_redis.lua:1173: uploaded redis script to [::1]:6379 with id 4, sha: b19d519e912f8c4d4a1f9fd972696ca72c72f366
019-11-23 16:05:31 #37032(normal) <wuoxg5>; lua; lua_redis.lua:1173: uploaded redis script to [::1]:6379 with id 2, sha: a43800941e2820ed8d764d50dfd9c142beddde68
2019-11-23 16:05:31 #31636(normal) <wuoxg5>; lua; lua_redis.lua:1173: uploaded redis script to [::1]:6379 with id 6, sha: da3a534c5a16cf973cfab2ba50c1fb8461a87093
2019-11-23 16:05:31 #31636(normal) <wuoxg5>; lua; lua_redis.lua:1173: uploaded redis script to [::1]:6379 with id 5, sha: 3356099ff58c7e8893283c259278305d0d813a84

The question is, why is rspamd failing with an IO error and in other cases the communication works without problems over ipv6.

**Comment by vstakhov** [comment]
Does the normal worker listen on IPv6 address?

**Comment by serial-bug** [comment]
Good morning...

If you could tell me how to check this, i will check.

Thank you.

**Comment by andryyy** [comment]
https://rspamd.com/doc/workers/

"grep" for `bind_socket` in /etc/rspamd

**Comment by serial-bug** [comment]
You mean, what is configured ?

cat /usr/local/etc/rspamd/rspamd.conf | grep bind
    bind_socket = "localhost:11333";
    bind_socket = "localhost:11334";
    bind_socket = "localhost:11332";
    bind_socket = "localhost:11335";

**Comment by serial-bug** [comment]
cat /usr/local/etc/rspamd/rspamd.conf | grep bind
    bind_socket = "localhost:11333";
    bind_socket = "localhost:11334";
    bind_socket = "localhost:11332";
    bind_socket = "localhost:11335";

**Comment by andryyy** [comment]
If you don't need IPv6, use 127.0.0.1 or make sure localhost does not resolve to ::1 (not a good idea imo).

**Comment by serial-bug** [comment]
Ok, that could be a workaround, but not a solution.
Thank you.

Just for my understanding:

You think that the problem is that localhost sometimes resolves to its ipv6 address.
Ok, this behavior could be a problem of opnsense it self.

But, what i dont understand is, why is this a problem for rspamd ?
In the logs you can see, that rspamd can handle ipv6 well, so why is it failing on rspamd_proxy with ipv6 ?
