### ISSUE TITLE
consolidate redis prefixes

### ISSUE THREAD

**Issue by waclaw66** [rspamd/rspamd#3169]
## Summary

There is inconsistency among prefixes of redis keys. Some of them are configurable, some are harcoded. Prefix stucture also do not follow best praxis of redis key structure - names divided by colon. As I discovered, there are currently following cases:
- main redis prefix (not working for all keys)
- neural prefix prefixing the main prefix
- harcoded anti-virus prefixes
- any other?

## Motivation

I would like to have all rspamd keys under one tree structure. It's synoptic and well maintainable. Thus it should be configurable to set the main prefix for all redis keys and the module subkey. That is currently impossible.

Proposal examples:
rspamd:history:domain_zst
rspamd:neural:default_...
rspamd:virus:clamav
etc...

Thanks for considering this.

**Comment by vstakhov** [comment]
There is an interface at `lua_redis.register_prefix` to do it. It is just not adopted to all Rspamd modules. Your proposal will 
1. increase the length of the Redis keys (meaning more memory and network traffic consumption in some cases)
2. break all compatibility (the most important bit!)
3. will not simplify anything in fact as the exact keys won't be known after all

So I'm more inclined to extent these prefixes framework and adding more tools to make it working than to renaming the existing keys (I agree that currently they are just messy).

**Comment by waclaw66** [comment]
> So I'm more inclined to extent these prefixes framework and adding more tools to make it working than to renaming the existing keys (I agree that currently they are just messy).

Understood, I would appreciate this.
