### ISSUE TITLE
[BUG] rspamd floods syslog when redis is offline

### ISSUE THREAD

**Issue by dphi** [rspamd/rspamd#3170]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
When redis does not accept new connections, rspamd start issuing logs like

<>; ; rspamd_redis_pool_new_connection: cannot connect to redis 127.0.0.1 (port 6379): Die angeforderte Adresse kann nicht zugewiesen
<>; ; rspamd_lua_redis_prepare_connection: cannot connect to redis (OS error): Die angeforderte Adresse kann nicht zugewiesen werden

and then some additional lines based on the task that currently tries to connect to redis, eg, dmarc.lua:1056 . 

**Expected behavior**
I'd expect that rspamd notices the issue with redis, limits the numer of re-tries, and related log messages, and maybe gives an option to send a notification.

### Versions

Rspamd daemon version 2.2
Debian GNU/Linux 10 (buster)

**Comment by vstakhov** [comment]
I'm sorry but it is not Rspamd task to monitor external services. There is monitoring for RBLs but it exists just because you likely do not control those external black lists. In case of Redis, monitoring is your task, not Rspamd's one.
