### ISSUE TITLE
[Feature] DMARC reject != Spam message rejected

### ISSUE THREAD

**Issue by uvelokk** [rspamd/rspamd#3174]
### Synopsis
It would be nice if the message to an e-mail sender in the case of a DMARC rejection would describe what really happened (something like "Rejected by DMARC policy"). At the moment the rejection message in such situations is "Spam message rejected".

### Effective configuration
```
dmarc {
    actions {
        reject = "reject";
    }
}
```

**Comment by lxp** [comment]
I solved the issue via a custom rule for the force_actions module:
```
force_actions {
    rules {
        REJECT_DMARC_POLICY_REJECT {
            action = "reject";
            expression = "DMARC_POLICY_REJECT";
            message = "Email rejected per DMARC policy";
        }
    }
}
```

This rejects the affected messages with
```
554 5.7.1 Email rejected per DMARC policy
```
instead of

```
554 5.7.1 Spam message rejected
```
