### ISSUE TITLE
[Feature] Make SPF checks work behind relay

### ISSUE THREAD

**Issue by gollum53** [rspamd/rspamd#3176]
## Summary

Make SPF checks  (and DMARC policy) work correctly behind relay

## Motivation

When rspamd is run on a server where all mail is passed to it via upstrem relay server, SPF checks always fail for obvious reason. So does subsequent DMARC checks. If rspamd could obey standard Received-SPF header added by upstream relay server, that would solve the issue.

## Describe alternatives you've considered

I have considered removing the last Received: header by MTA but that did not help. I have not come across anything in rspamd configuration that would help in this situation.

**Comment by vstakhov** [comment]
There is now `external_relay` option in the SPF module.

**Comment by vstakhov** [comment]
Using of Received-Spf should also be trivial to add.

**Comment by gollum53** [comment]
Could you please provide the details on using the external_relay feature? Thanx

**Comment by andryyy** [comment]
```
# overrides existing spf.conf files
echo 'external_relay = "1.2.3.4";' > /etc/rspamd/local.d/spf.conf
```

**Comment by gollum53** [comment]
not getting any error with this config, but still getting:
spf=softfail (a.b.c.d: e.f.g.h is neither permitted nor denied ...
where a.b.c.d is rspamd server and e.f.g.h is the relay.
 I am using stable version 2.2 Is that OK?

**Comment by andryyy** [comment]
It is probably not yet in a release. :)

**Comment by gollum53** [comment]
ok then. thanks :)
