### ISSUE TITLE
[BUG] BLACKLIST_DMARC wrongly added

### ISSUE THREAD

**Issue by gollum53** [rspamd/rspamd#3178]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
My rspamd server is behind a relay, so SPF checks will always fail. However, DKIM checks are valid. When I get mail from paypal.com, it (wrongly) gets BLACKLIST_DMARC score:

Authentication-Results: xxx..muni.cz;
	dkim=pass header.d=mail.paypal.com header.s=pp-epsilon1 header.b=kVgcUBcx
X-Rspamd-Queue-Id: B663F3002AB
X-Spamd-Result: default: False [7.36 / 15.00];
	 HAS_REPLYTO(0.00)[noreply-HP2v40000016eccfd208aaa0acbf4bbcf76f8234@mail.paypal.com];
	 REDIRECTOR_FALSE(0.00)[paypal.cz->paypal-communication.com];
	 ZERO_FONT(1.00)[87];
	 BLACKLIST_DMARC(6.00)[paypal.com:D:-];
	 TO_DN_NONE(0.00)[];
	 RCVD_DKIM_ARC_DNSWL_MED(-0.50)[];
	 DKIM_TRACE(0.00)[mail.paypal.com:+];
	 RCVD_IN_DNSWL_MED(-0.20)[147.251.4.46:from];
	 FREEMAIL_TO(0.00)[email.cz];
	 FORGED_SENDER(0.30)[paypal@mail.paypal.com,SRS0=mEEv=ZZ=mail.paypal.com=bounce@seznam.cz];
	 RCVD_IN_DNSWL_LOW(-0.10)[77.75.78.89:received];
	 RCVD_TLS_LAST(0.00)[];
	 FREEMAIL_ENVFROM(0.00)[seznam.cz];
	 FORGED_RECIPIENTS(2.00)[smid@email.cz,ibaadmin@ibamail2019.muni.cz];
	 MID_RHS_MATCH_FROM(0.00)[];
	 FROM_NEQ_ENVFROM(0.00)[paypal@mail.paypal.com,SRS0=mEEv=ZZ=mail.paypal.com=bounce@seznam.cz];
	 ASN(0.00)[asn:2852, ipnet:147.251.0.0/16, country:CZ];
	 ARC_NA(0.00)[];
	 R_PARTS_DIFFER(0.17)[58.4%];
	 R_DKIM_ALLOW(-0.20)[mail.paypal.com:s=pp-epsilon1];
	 FROM_HAS_DN(0.00)[];
	 DWL_DNSWL_MED(-2.00)[paypal.com:dkim];
	 MIME_GOOD(-0.10)[multipart/alternative,text/plain];
	 MIME_TRACE(0.00)[0:+,1:+,2:~];
	 REPLYTO_DOM_EQ_FROM_DOM(0.00)[];
	 HAS_LIST_UNSUB(-0.01)[];
	 RCPT_COUNT_ONE(0.00)[1];
	 MANY_INVISIBLE_PARTS(1.00)[10];
	 RCVD_IN_DNSWL_NONE(0.00)[142.54.244.108:received];
	 RCVD_COUNT_SEVEN(0.00)[9];
	 GREYLIST(0.00)[pass,body]
X-Spam-Flag: Yes

FORGED_RECIPIENTS(2.00) is expected as the mail is forwarded.

### Steps to Reproduce

1. Put rspamd behind a relay server
2. Make paypal send you a mail :)

**Expected behavior**
When DKIM check is valid, DMARC should also be valid by definition. BLACKLIST_DMARC(6.00)[paypal.com:D:-]; shoud not be added.

### Versions
Rspamd daemon version 2.2
OS: Ubuntu 18.04 LTS
Linux mail2019 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Additional Information
No special config for DMARC module has been added.

**Comment by vstakhov** [comment]
It looks like it is related to subdomains in DMARC. Do you have any full email you can share with me for tests, probably privately?

**Comment by gollum53** [comment]
Thanx, I have sent it to you in private email.

**Comment by vstakhov** [comment]
Hum, I cannot reproduce it I'm afraid. I have found my own email from paypal and tried to forge it's source IP address. Here is what I've got:

```
Results for file: /Users/vstakhov/Downloads/paypal_real.eml (2.420 seconds)
[Metric: default]
Action: no action
Spam: false
Score: -0.20 / 6.00
Symbol: DKIM_TRACE (0.00)[mail.paypal.com:+]
Symbol: DMARC_POLICY_ALLOW (0.00)[paypal.com, reject]
Symbol: DMARC_POLICY_ALLOW_WITH_FAILURES (-0.50)
Symbol: FROM_NEQ_ENVFROM (0.00)[paypal@mail.paypal.com, bounce@mail.paypal.com]
Symbol: R_DKIM_ALLOW (-0.20)[mail.paypal.com:s=pp-epsilon1]
Symbol: R_SPF_FAIL (1.00)[-all]
Symbol: VIOLATED_DIRECT_SPF (1.00)
Symbol: WHITELIST_DMARC (-7.00)[paypal.com:D:+]
Message-ID: HP2v40000016c76599d97c51953f4bbc786c8089@mail.paypal.com
Urls: ["epl.paypal-communication.com","t.myvisualiq.net","epidm.edgesuite.net"]
```

I don't see any DMARC symbols in your reply and that's suspicious.

**Comment by gollum53** [comment]
Thanx, yes that is suspicious. I have enabled DKIM logging and will wait if I can reproduce this.

**Comment by pdf** [comment]
I have the same issue with Paypal emails and rspamd v3.4.

Emails verify with opendkim-testmsg, but rspamd consistently adds the BLACKLIST_DMARC symbol:

```
__BODY_URI_ONLY (0) [__BODY_TEXT_LINE,__HAS_ANY_URI]
__FM_MY_PRICE (0) [__FB_S_PRICE]
__KHOP_NO_FULL_NAME (0)
__NOT_SPOOFED (0) [__DKIM_EXISTS]
__URI_ONLY_MSGID_MALF (0) [__BODY_URI_ONLY,__MSGID_NOFQDN2]
ARC_NA (0)
ASN (0) [asn:17012, ipnet:173.0.80.0/21, country:US]
BLACKLIST_DMARC (6) [paypal.com.au:D:-]
DKIM_TRACE (0) [paypal.com.au:+]
FROM_DN_EQ_ADDR (1)
FROM_EQ_ENVFROM (0)
GREYLIST (0) [pass,body]
MID_RHS_NOT_FQDN (0.5)
MIME_HTML_ONLY (0.1)
MIME_TRACE (0) [0:~]
NO_RECEIVED (-0.001)
POSSIBLE_PAYPAL_PHISH_02 (0) [__FROM_NAME_PAYPALCOM]
R_DKIM_ALLOW (-0.2) [paypal.com.au:s=pp-dkim1]
R_SPF_ALLOW (-0.2) [+ip4:173.0.84.224/27]
RCPT_COUNT_ONE (0) [1]
RCVD_COUNT_ZERO (0) [0]
RWL_MAILSPIKE_GOOD (-0.1) [173.0.84.228:from]
TO_DN_ALL (0)
TO_MATCH_ENVRCPT_ALL (0)
```

**Comment by pdf** [comment]
Also happens for amazon.com
