### ISSUE TITLE
replies.lua fails on all outgoing mail

### ISSUE THREAD

**Issue by FlyveHest** [rspamd/rspamd#3183]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Every time I send an outgoing mail, I get the following error in the rspamd log

`lua; replies.lua:131: redis_set_cb received error: ERR value is not an integer or out of range`

replies modules is stock configured, I run a global redis backend database.

### Steps to Reproduce

1. Send outgoing e-mail through scanner

**Expected behavior**
That the replies module logged message id, or, at least not gave an error.

### Versions

Rspamd daemon version 2.2
PostFix v3.3.0

### Additional Information

From postfix log (i'm not sure if this is the msgid rspamd uses though)
message-id=<414caf39ba9cf649bbfceacdfed492ba@domain.tld>

Debugging the module gives the following

#67(rspamd_proxy) <a9302b>; replies; replies.lua:137: sender is authenticated
#67(rspamd_proxy) <a9302b>; replies; replies.lua:150: storing message-id for replies check
#67(rspamd_proxy) <a9302b>; lua; replies.lua:131: redis_set_cb received error: ERR value is not an integer or out of range

So it seems like the problem is in the redis_make_request call in line 156 of replies.lua?

**Comment by vstakhov** [comment]
It seems your `expire` option is not set properly.

**Comment by vstakhov** [comment]
Or you are using your own build and not the packages I provide.

**Comment by vstakhov** [comment]
The second option might happen as it reminds me about vanilla Lua issue:

```
> lua5.3
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
> print(tostring(100500.0))
100500.0
```

vs

```
> rspamadm lua
LuaJIT 2.0.5> print(tostring(100500.0))
100500
```

The plain Lua version would fail apparently.

**Comment by vstakhov** [comment]
I've tried to add a workaround.

**Comment by FlyveHest** [comment]
I am using the packages from http://rspamd.com/apt-stable/ and I have not touched the replies config at all, so its running stock.

Rspamd is running in a debian:buster Docker image from https://hub.docker.com/_/debian

**Comment by vstakhov** [comment]
Can you run `rspamadm configdump expire` to clarify?

**Comment by FlyveHest** [comment]
Can do

`root@230541d2560c:/# rspamadm configdump replies
*** Section replies ***
symbol = "REPLY";
message = "Message is reply to one we originated";
expire = "259200:";
key_prefix = "rr";

*** End of section replies ***
`

Expire seems to be a string here. 

This is whats in my local.d/replies.conf (upped the expiry a bit)

`expire = 259200:`

And now I see, its not a ; but a : at the end of the line.

Changing that made the expire data in the configdump into an integer, i'm so sorry for that stupid mistake on my part.
