### ISSUE TITLE
[BUG] virustotal action = add_header will still be applied even if mail scores over 15

### ISSUE THREAD

**Issue by tjharman** [rspamd/rspamd#3184]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
A message comes in and has a virus attached.  My antivirus.conf just has virustotal enabled with my apikey and action = add_header;

The mail scored way in excess of 15 and should have been rejected, but the add_header action is applied instead and the mail was accepted with only a header added.

### Steps to Reproduce

1. Set action = add_header in your antivirus.conf virustotal section.
2. Receive
 an email that triggers a lot of rules and scores a large (over your reject score) number.
3. Observe that the email is accepted by rspamd and has a X-Spam=Yes header added.

**Expected behavior**
The mail, exceeding the threshold of 15, should have been rejected.

### Versions

-!- rspamd/local.d » rspamd --version
Rspamd daemon version 2.2
Debian 10.2
Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

```
1193:2019-12-10 08:51:21 #9479(normal) <9211f6>; lua; common.lua:107: virustotal: result - virusfound: "ec3962ba103e85f4a30947ddb170ddb0:6/57 - score: 0.75"
1194:2019-12-10 08:51:21 #9479(normal) <9211f6>; task; rspamd_add_passthrough_result: <542B7E97.F98C2AF2@gmail.com>: set pre-result to 'add header' (no score): 'virustotal: spam message found: "ec3962ba103e85f4a30947ddb170ddb0:6/57"' from virustotal(1)
1197:2019-12-10 08:51:22 #9479(normal) <9211f6>; task; rspamd_task_write_log: id: <542B7E97.F98C2AF2@gmail.com>, qid: <9374920590>, ip: 23.228.73.188, from: <watkinsmelanie58shyy@gmail.com>, (default: T (add header): [50.34/15.00] [DBL_SPAM(6.50){myinstabuzz.co:url;},MIME_BAD_ATTACHMENT(4.00){html;},RBL_NIXSPAM(4.00){23.228.73.188:from;},RBL_ABUSIX(3.00){23.228.73.188:from;},RBL_BARRACUDA(3.00){23.228.73.188:from;},RSPAMD_URIBL(3.00){myinstabuzz.co:url;},SURBL_ABUSIX(3.00){myinstabuzz.co:url;},FORGED_MUA_THUNDERBIRD_MSGID_UNKNOWN(2.50){},HFILTER_HOSTNAME_UNKNOWN(2.50){},DCC_REJECT(2.00){bulk Body=1 Fuz1=20 Fuz2=many ;},RBL_LASHBACK(2.00){23.228.73.188:from;},RBL_MAILSPIKE_WORST(2.00){23.228.73.188:from;},RBL_PSBL(2.00){23.228.73.188:from;},RBL_SENDERSCORE(2.00){23.228.73.188:from;},RBL_SPAMCOP(2.00){23.228.73.188:from;},RBL_TRUNCATE(2.00){23.228.73.188:from;},RBL_UCEPROTECT1(2.00){23.228.73.188:from;},RBL_VIRUSFREE_BOTNET(2.00){23.228.73.188:from;},RBL_SEM(1.00){23.228.73.188:from;},RWL_HOSTKARMA_QUIT_USED(-0.25){23.228.73.188:from;},DMARC_POLICY_SOFTFAIL(0.10){gmail.com : No valid SPF, No valid DKIM;none;},MIME_GOOD(-0.10){multipart/mixed;text/plain;},ONCE_RECEIVED(0.10){},MX_GOOD(-0.01){cached: alt3.gmail-smtp-in.l.google.com;},ARC_NA(0.00){},ARC_SIGNED(0.00){i=1;},ASN(0.00){asn:46573, ipnet:23.228.73.0/24, country:US;},FREEMAIL_ENVFROM(0.00){gmail.com;},FREEMAIL_FROM(0.00){gmail.com;},FROM_EQ_ENVFROM(0.00){},FROM_HAS_DN(0.00){},HAS_ATTACHMENT(0.00){},MID_RHS_MATCH_FROM(0.00){},MIME_TRACE(0.00){0:+;1:+;2:~;},RCPT_COUNT_ONE(0.00){1;},RCVD_COUNT_ZERO(0.00){0;},R_DKIM_NA(0.00){},R_SPF_SOFTFAIL(0.00){~all;},SPAMHAUS_FROM(0.00){23.228.73.188:from:127.0.0.2;23.228.73.188:from:127.0.0.4;},TO_DN_NONE(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){},URIBL_BLACK(0.00){myinstabuzz.co:url;},VIRUSTOTAL(0.00){ec3962ba103e85f4a30947ddb170ddb0:6/57;},ZRD(0.00){23.228.73.188:from:127.0.2.255;}]), len: 1410, time: 1815.645ms, dns req: 43, digest: <5144c4a04872aafbc638e5f78a423271>, rcpts: <tim@muppetz.com>, mime_rcpts: <tim@muppetz.com>, forced: add header "virustotal: spam message found: "ec3962ba103e85f4a30947ddb170ddb0:6/57""; score=nan (set by virustotal)
```

**Comment by vstakhov** [comment]
Forced actions are special. But this change should implement the desired behaviour.

**Comment by tjharman** [comment]
Thank you.
Would a worthwhile feature request be to remove "action" and replace it with "force_action" and "minimum_action"?

That way the user can decide if they want the action to be the thing least enforced, or the thing that's enforced no matter what?

Anyway, thank you for the commit above.
