### ISSUE TITLE
[BUG] Neural module doesn't work properly

### ISSUE THREAD

**Issue by mans39** [rspamd/rspamd#3185]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**

### Versions

You can get this information from copy and pasting the output of `rspamd --version` from the command line. Also, please include the **OS** and what version and architecture including the generation of CPU model (e.g. Haswell) where applicable,  of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

Hello,

I have an issue with the neural module.

Here is my neural.conf : 

enabled = true;

servers = "master-slave:127.0.0.1:6379";

train {
  max_train = 1k; # Number ham/spam samples needed to start train
  max_usages = 20; # Number of learn iterations while ANN data is valid
  learning_rate = 0.01; # Rate of learning
  max_iterations = 25; # Maximum iterations of learning (better preciseness but also lower speed of learning)
  spam_score = 9; # Score to learn spam
  ham_score = -5; # Score to learn ham
}
ann_expire = 30d; # For how long ANN should be preserved in Redis

And the neural_group.conf file : 

symbols = {
  "NEURAL_SPAM" {
    weight = 3.0; # sample weight
    description = "Neural network spam";
  }
  "NEURAL_HAM" {
    weight = -3.0; # sample weight
    description = "Neural network ham";
  }
}

Neural module is correctly loaded but never match with ham/spam. 

I can see this line in my log file : 

Dec 10 17:19:47 mx1 rspamd[49735]: <f7a546>; lua; neural.lua:473: cannot learn ham ANN default:default: sampled out with probability 0.5 (151 vectors stored)
Dec 10 17:21:22 mx1 rspamd[49734]: <968774>; lua; neural.lua:473: cannot learn ham ANN default:default: sampled out with probability 0.5 (157 vectors stored)
Dec 10 17:21:29 mx1 rspamd[49735]: <dd5e3e>; lua; neural.lua:473: cannot learn ham ANN default:default: sampled out with probability 0.5 (157 vectors stored)
Dec 10 17:21:47 mx1 rspamd[49734]: <fa0180>; lua; neural.lua:473: cannot learn ham ANN default:default: sampled out with probability 0.49367088607595 (157 vectors stored)
Dec 10 17:22:28 mx1 rspamd[49734]: <9dabcc>; lua; neural.lua:473: cannot learn ham ANN default:default: sampled out with probability 0.49685534591195 (158 vectors stored)
Dec 10 17:22:44 mx1 rspamd[49737]: <2a7590>; lua; neural.lua:473: cannot learn ham ANN default:default: sampled out with probability 0.48427672955975 (158 vectors stored)
Dec 10 17:23:03 mx1 rspamd[49737]: <a71b86>; lua; neural.lua:473: cannot learn ham ANN default:default: sampled out with probability 0.48427672955975 (158 vectors stored)
Dec 10 17:23:39 mx1 rspamd[49734]: <eec102>; lua; neural.lua:473: cannot learn ham ANN default:default: sampled out with probability 0.4875 (159 vectors stored)
Dec 10 17:23:57 mx1 rspamd[49734]: <4e8349>; lua; neural.lua:473: cannot learn ham ANN default:default: sampled out with probability 0.475 (159 vectors stored)
Dec 10 17:24:52 mx1 rspamd[49734]: <8efcfa>; lua; neural.lua:473: cannot learn ham ANN default:default: sampled out with probability 0.46951219512195 (163 vectors stored)
Dec 10 17:24:54 mx1 rspamd[49736]: <d6a155>; lua; neural.lua:473: cannot learn ham ANN default:default: sampled out with probability 0.46341463414634 (163 vectors stored)
Dec 10 17:25:02 mx1 rspamd[49734]: <c05785>; lua; neural.lua:473: cannot learn ham ANN default:default: sampled out with probability 0.46666666666667 (164 vectors stored)
Dec 10 17:25:09 mx1 rspamd[49734]: <001f47>; lua; neural.lua:473: cannot learn ham ANN default:default: sampled out with probability 0.46987951807229 (165 vectors stored)
Dec 10 17:25:28 mx1 rspamd[49737]: <f0075d>; lua; neural.lua:473: cannot learn ham ANN default:default: sampled out with probability 0.46987951807229 (165 vectors stored)
Dec 10 17:25:36 mx1 rspamd[49735]: <1f3c96>; lua; neural.lua:473: cannot learn ham ANN default:default: sampled out with probability 0.46987951807229 (165 vectors stored)
Dec 10 17:27:14 mx1 rspamd[49735]: <63518d>; lua; neural.lua:473: cannot learn ham ANN default:default: sampled out with probability 0.46107784431138 (166 vectors stored)
Dec 10 17:27:37 mx1 root: root 10.39.10.92 [24679]: tail -f /var/log/syslog | grep -i "neural" [130]
Dec 10 17:27:53 mx1 rspamd[49735]: <1b1282>; lua; neural.lua:473: cannot learn ham ANN default:default: sampled out with probability 0.45833333333333 (167 ve

I can understand that HAM doesn't match because the probability is not reach, but I can't see anything about SPAM.

Does my configuration is incorrect or I missing something ?

Regards,

**Comment by vstakhov** [comment]
Please don't use issue tracker for questions. Closing.
