### ISSUE TITLE
[Feature] rspamc installation package

### ISSUE THREAD

**Issue by koehn** [rspamd/rspamd#3189]
## Summary

There should be an `rspamc` installation package for integrating with non-local MTA/MDA installations. 

## Motivation

Under containerized environments like Kubernetes, the design goal is to isolate applications like MTAs (e.g., Postfix), MDAs (e.g., Dovecot), and spam filters (e.g., Rspamd) into separate containers. This makes scalability, process isolation, recovery, etc. much simpler, as it's built into the Kubernetes environment. 

To achieve this scalability with Rspamd, one must have the `rspamc` client available on MTAs for miltering and MDAs for allowing users to mark mail as spam/ham by moving messages in/out of the Junk folder. 

In order to get the `rspamc` program, one must currently install the full `rspamd` package, which results in a lot of unnecessary code and files being included in MDA/MTA containers. It would be better if one could install the `rspamc` client via package managers as its own package. 

## Describe alternatives you've considered

I'm still new to Rspamd, but as far as I know installing the entire `rspamd` package is the only alternative; as I said it brings along a lot of unneeded code and files.

**Comment by vstakhov** [comment]
Rspamd uses HTTP/1.0 protocol for communications. Is it really that hard to find any suitable HTTP client in your environment? There is also an entry in FAQ about it: https://rspamd.com/doc/faq.html#can-i-check-a-message-with-rspamd-without-rspamc

**Comment by koehn** [comment]
I saw the FAQ and ran the test to see the output. Yes, I could certainly invoke `curl` and parse the JSON output myself with a tool like `jq`, but at that point I'm pretty much replicating the functionality of `rspamc`, which you've already written and support. 

Also, for whatever reason repeatedly running the exact command from the FAQ takes 1.5 seconds each time, while running `rspamc` takes 0.15 seconds. I don't know what `rspamc` is doing behind the scenes, but it seems much faster than `curl`. 

Put another way, is it really that hard to write another package to install the client you've already written, or should every user in my position replicate the same work?

**Comment by vstakhov** [comment]
Yes, it is hard enough and I have no time for that.

**Comment by koehn** [comment]
Yeah, I bet it would be hard to do with all that it includes. 

```
ldd /usr/bin/rspamc 
	linux-vdso.so.1 (0x00007ffcefbae000)
	librspamd-server.so => /usr/lib/rspamd/librspamd-server.so (0x00007fccd959f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fccd957b000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fccd945c000)
	librspamd-ev.so => /usr/lib/rspamd/librspamd-ev.so (0x00007fccd944d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fccd928c000)
	libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007fccd926f000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fccd91f9000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007fccd90d7000)
	libicui18n.so.63 => /usr/lib/x86_64-linux-gnu/libicui18n.so.63 (0x00007fccd8dfc000)
	libicuuc.so.63 => /usr/lib/x86_64-linux-gnu/libicuuc.so.63 (0x00007fccd8c2d000)
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007fccd8b9b000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007fccd88b2000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fccd8692000)
	libsodium.so.23 => /usr/lib/x86_64-linux-gnu/libsodium.so.23 (0x00007fccd863b000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fccd8631000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fccd862c000)
	librspamd-replxx.so => /usr/lib/rspamd/librspamd-replxx.so (0x00007fccd8602000)
	librspamd-actrie.so => /usr/lib/rspamd/librspamd-actrie.so (0x00007fccd85fe000)
	librspamd-kann.so => /usr/lib/rspamd/librspamd-kann.so (0x00007fccd85dd000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fccd8459000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fccd82d6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fccda331000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fccd82bc000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fccd8294000)
	libicudata.so.63 => /usr/lib/x86_64-linux-gnu/libicudata.so.63 (0x00007fccd68a2000)
```

**Comment by koehn** [comment]
Never mind; I can write a script and use `socat` to invoke `rspamc` on the rspamd pod. Sucks, but there it is. 

# 🤷🏼‍♂️

**Comment by koehn** [comment]
For anyone else who's interested, you can run `rspamc` (or any other command) remotely using the [simple scripts available here](https://gitlab.koehn.com/bkoehn/socat-remote).

**Comment by borekon** [comment]
> For anyone else who's interested, you can run `rspamc` (or any other command) remotely using the [simple scripts available here](https://gitlab.koehn.com/bkoehn/socat-remote).

Link is down and no repo in your github

> Rspamd uses HTTP/1.0 protocol for communications. Is it really that hard to find any suitable HTTP client in your environment? There is also an entry in FAQ about it: https://rspamd.com/doc/faq.html#can-i-check-a-message-with-rspamd-without-rspamc

The link provided no longer exists
