### ISSUE TITLE
[BUG] signed maps are no longer supported for HTTP

### ISSUE THREAD

**Issue by julian70400** [rspamd/rspamd#3190]
Hello,

Since RSPAMD 2.0 (and now with 2.2), got this error message : 

> signed maps are no longer supported for HTTP(s): sign+https://updates.rspamd.com/rspamd-2.ucl

I just find this : 

`grep -i -R -n updates.rspamd.com /etc/rspamd/*`

> /etc/rspamd/modules.d/rspamd_update.conf:19:  rules = "sign+https://updates.rspamd.com/rspamd-${BRANCH_VERSION}.ucl";

Got nothing specific in local.d, only original file : 

` cat /etc/rspamd/modules.d/rspamd_update.conf`

> [...]
> 
> rspamd_update {
>   rules = "sign+https://updates.rspamd.com/rspamd-${BRANCH_VERSION}.ucl";
>   key = "qxuogdh5eghytji1utkkte1dn3n81c3y5twe61uzoddzwqzuxxyb";
>   enabled = false; # Disable this module by default
> 
>   .include(try=true,priority=5) "${DBDIR}/dynamic/rspamd_update.conf"
>   .include(try=true,priority=1,duplicate=merge) "$LOCAL_CONFDIR/local.d/rspamd_update.conf"
>   .include(try=true,priority=10) "$LOCAL_CONFDIR/override.d/rspamd_update.conf"
> }

So, what's wrong ? Thanks.

**Comment by vstakhov** [comment]
rspamd_update is now disabled by default and signed maps are indeed removed. What is the question?

**Comment by julian70400** [comment]
I understand, but why showing a message in the log if everything is normal ? Also, as **enabled = false;** , why showing a warning about a feature which is deactivated and no more longer supported by tool ?
Maybe I am wrong, but it appaers to me as a false positive warning/info message.

**Comment by vstakhov** [comment]
It looks like it is enabled in your local config. Please run `rspamadm configdump rspamd_update` to acknowledge that.

**Comment by julian70400** [comment]
Damn you're right..

> rspamadm configdump rspamd_update
> signed maps are no longer supported for HTTP(s): sign+https://updates.rspamd.com/rspamd-2.ucl
> *** Section rspamd_update ***
> enabled = true;
> key = "qxuogdh5eghytji1utkkte1dn3n81c3y5twe61uzoddzwqzuxxyb";
> rules = "sign+https://updates.rspamd.com/rspamd-2.ucl";
> 
> *** End of section rspamd_update ***

I don't understand where is this enabled. It is set nowhere in my configuration
