### ISSUE TITLE
[BUG] The learns counter gets different values

### ISSUE THREAD

**Issue by stephdl** [rspamd/rspamd#3191]
**Describe the bug**

I noticed with the move to rspamd 2.2 from 1.9.4 that the learns counter has started from 0 in logs, I mean this in maillog

```
Dec 15 00:19:12 nethservice rspamd[15843]: <5fb59c>; proxy; rspamd_redis_connected: skip obtaining bayes tokens for BAYES_SPAM of classifier bayes: not enough learns 199; 200 required
Dec 15 00:54:32 nethservice rspamd[15843]: <bc0c60>; proxy; rspamd_redis_connected: skip obtaining bayes tokens for BAYES_HAM of classifier bayes: not enough learns 199; 200 required
```

but I can find several others sources for how many learned messages I have, other one 

```
[root@here ~]# rspamc stat
Results for command: stat (0.034 seconds)
Messages scanned: 1457081
Messages with action reject: 421653, 28.93%
Messages with action soft reject: 3528, 0.24%
Messages with action rewrite subject: 16, 0.00%
Messages with action add header: 40105, 2.75%
Messages with action greylist: 6790, 0.46%
Messages with action no action: 984989, 67.60%
Messages treated as spam: 465302, 31.93%
Messages treated as ham: 991779, 68.06%
Messages learned: 25210
Connections count: 0
Control connections count: 12
Pools allocated: 18691
Pools freed: 18658
Bytes allocated: 21.87MiB
Memory chunks allocated: 128
Shared chunks allocated: 17
Chunks freed: 0
Oversized chunks: 1547
Fuzzy hashes in storage "local": 0
Fuzzy hashes in storage "rspamd.com": 905848192
Fuzzy hashes stored: 905848192
Statfile: BAYES_SPAM type: redis; length: 0; free blocks: 0; total blocks: 0; free: 0.00%; learned: 3261; users: 39; languages: 0
Statfile: BAYES_HAM type: redis; length: 0; free blocks: 0; total blocks: 0; free: 0.00%; learned: 11001; users: 1251; languages: 0
Total learns: 14262
```
and also this, it comes from` /var/lib/rspamd/stats.ucl`, we query it to display a widget in the UI to inform how many learns you need before to get bayes

```
curl --connect-timeout 2 'http://localhost:11334/auth'

{
  "version": "2.2",
  "auth": "ok",
  "uptime": 248605,
  "clean": 985008,
  "probable": 40121,
  "greylist": 6790,
  "reject": 421653,
  "soft_reject": 3528,
  "scanned": 1457100,
  "learned": 25210,
  "read_only": false,
  "config_id": "token"
}
```

I want to say that once the minimal learn is done, the bayes works pretty well as expected, there is no bug on this side.

### Steps to Reproduce

1. install rspamd v 1.9.4 and go in production
2. when trained, install v2.2
3. the learn counter in maillog starts to learn from zero again

**Expected behavior**

I do not know if it is a bug, or a new feature, I can understand that maybe we need to start from zero due to the new bayes feature in v2, I mean about reputation for example, but what it puzzled me is that I can find different values for the learned counters.

For a new server installation, nobody will be aware, but for an upgrade, I figure that we could have some issues.

### Versions

OS : nethserver 7.7 (centos7.7)
rspamd version: 2.2

**Comment by vaygr** [comment]
I experienced the same when switching from 1.6.4 to 2.7.

Is there any fix for that?

cc @vstakhov
