### ISSUE TITLE
[BUG] Redis slowlog issue in statistics

### ISSUE THREAD

**Issue by rspamd-internal** [rspamd/rspamd#3192]
### Description
Getting slowlogs in redis due to Statistics module.

I have attached image i got in redislabs today, it shows slowlogs are happening when  **EVALSHA** command is executed by **RSPAMD** in redis.

Total learns: 21k
Can you help us in understanding why this latency is occurring as we are able to see considerable spike in RSPAMD processing time as well if we enable statistics module.

<img width="1197" alt="Screenshot 2019-12-17 at 3 30 29 PM" src="https://user-images.githubusercontent.com/46189845/70987147-52faf700-20e5-11ea-9448-8c2b693f954e.png">

**Comment by vstakhov** [comment]
It comes from bayes expiry I suppose. What are your settings for this module?

**Comment by rspamd-internal** [comment]
Here are our settings
    classifier "bayes" {
        tokenizer {
            name = "osb";
        }

        name = "GLOBAL";
        min_tokens = 5;
        min_learns = 200;
        backend = "redis";
        servers = xxxx ;
        password = xxxx;
        min_tokens = 5;
        min_learns = 200;
        new_schema = true;
        expire = 86400;

        statfile {
            symbol = "BAYES_SPAM";
            spam = true;
        }
        statfile {
            symbol = "BAYES_HAM";
            spam = false;
        }
        }

**Comment by vstakhov** [comment]
I need bayes_expiry, not bayes: `rspamadm configdump bayes_expiry`

**Comment by rspamd-internal** [comment]
Hi according to this page https://rspamd.com/doc/modules/bayes_expiry.html
I have configured expiration in classifier "bayes" section only

backend = "redis";   
servers = "xxxxx";
new_schema = true;   
expire = 86400;
lazy = true;
