### ISSUE TITLE
Comment in phishing.conf is inconsistent with reality

### ISSUE THREAD

**Issue by kbabioch** [rspamd/rspamd#3194]
**Describe the bug**

The comment in the phishing.conf file suggests that `phishtank` is disabled by default. This is not true, since it is enabled in the very line following this comment:

https://github.com/rspamd/rspamd/blob/7d1482a9ff1a0d57ae2c5331b9c72ff11e8ebf7a/conf/modules.d/phishing.conf#L21-L22

**Expected behavior**
Comment should represent the true and intended behavior.

**Comment by moisseev** [comment]
`Phishtank` is disabled by default in the module code but explicitly enabled in the stock configuration file. If one omit or comment out `phishtank_enabled = true;` in the configuration file then `phishtank` will be disabled.

Would you suggest how to rephrase the comment?

**Comment by kbabioch** [comment]
Well, typically people using rspamd don't know (and don't care) about the internals of the module, but only about the configuration of the software (i.e. anything in `/etc`).

My suggestion(s) are:

- Drop the comment altogether (as the name of the variable is self-expeditionary)
- Have a comment like (`Phishtank is disabled within the module by default, so let's enable it explicitly here`)

**Comment by moisseev** [comment]
#3241
