### ISSUE TITLE
Add module of  generic antivirus scan engine

### ISSUE THREAD

**Issue by mshabou** [rspamd/rspamd#3197]
## Summary

add an antivirus module for generic CLI (like amavis): execute a command (cli), depending of the return code we know if there is a virus or not 

## Motivation

add compatibility to other virus scanner (bitdefender, kaspersky linux,...)

**Comment by vstakhov** [comment]
It is unlikely to be implemented as it contradicts with the performance concerns in Rspamd.

**Comment by mshabou** [comment]
Hi,

with the majority of the new antivirus  (cf bitdefender and kaspersky) there is a daemon, the cli only send a request to the daemon to scan a file or a directory:

here how a scan of a file take:

root@Pxxxx:~# time /usr/bin/kesl-control --scan-file --action skip /root/virus2/
Scanned objects                     : 1
Total detected objects              : 1
Infected objects and other objects  : 1
Disinfected objects                 : 0
Moved to Storage                    : 0
Removed objects                     : 0
Not disinfected objects             : 1
Scan errors                         : 0
Password-protected objects          : 0
Skipped                             : 0

real	0m0,141s
user	0m0,000s
sys	0m0,017s


the cli command interract with a daemon:

root       951  0.0  0.0  10804  2044 ?        S    déc.24   4:20 /opt/kaspersky/kesl/libexec/wdserver --trace-level 0 --trace-file /var/log/kaspersky/kesl/kesl_wdserver.log --n-restart 5 --master-timeout 180 --reboot-timeout 0 --wdsock /var/run/wdserver.sock --max-used-mem 90% --max-used-swap 100% --term-signal 2 -p /var/run/wdserver.pid -d -e /opt/kaspersky/kesl/libexec/kesl

**Comment by vstakhov** [comment]
If there is a daemon then it is better to communicate with this daemon directly. Fork+exec is no way in Rspamd due to performance considerations (please read some Unix design handbooks if you do not understand why). 

For Kaspersky, there is a direct interface for example. On the other hand, there is no such an interface for BitDefender, as BitDefender company has ignored my inquiry to add it.

**Comment by mshabou** [comment]
hi, 
actualy i want to you Kaspersky  ENDPOINT SECURITY FOR, LINUX  with rspamd. there is a  an unix socket but think that the protocol est open never documentated

**Comment by vstakhov** [comment]
I'd suggest to use the supported Scan Engine: https://www.kaspersky.com/scan-engine
