### ISSUE TITLE
Rspamd Statistics Reset

### ISSUE THREAD

**Issue by rubenszolt** [rspamd/rspamd#3203]
Hi everybody, I use 2.2 version and I want to reset the Rspamd statistics and email , to start from from zero, but I not find a good and official solution. I appreciate I somebody It can help in this case.

**Comment by vstakhov** [comment]
Please do not use issue tracker for support requests or questions, closing issue.

**Comment by moisseev** [comment]
```sh
# rspamc --commands | grep reset
     stat_reset (control*)      show and reset rspamd statistics (useful for graphs)
```

**Comment by rubenszolt** [comment]
I think I was not clear, I want to reset statistics and mail training too. I know about rspamc stat_reset command. It reset the WEB GUI but not the mail training, I want to start everything from zero.

**Comment by ThiefMaster** [comment]
just deleting all data from the redis db is probably the easiest option
