### ISSUE TITLE
[BUG] favicon.ico does not display on Firefox bookmark toolbar, only in the Tab.

### ISSUE THREAD

**Issue by xekon** [rspamd/rspamd#3207]
**Describe the bug**
favicon.ico does not display on Firefox bookmark toolbar, only in the Tab.

### Steps to Reproduce

1. install latest firefox
2. open your rspamd web page
3. bookmark the page to your bookmark toolbar

**Expected behavior**
The icon is not visible on the bookmark toolbar, it should be.

### Versions

Latest Firefox, Ubuntu 18.04

### Additional Information

As you can see, it is properly visible on the Firefox Tab, but not on the bookmark. The bookmark just stays blank without an icon. Also you might be able to guess from the 3 visible bookmarks on my toolbar that I am not using labels, I actually delete the label using only the icon, this allows me more space for sites on my toolbar, so having a working icon for Rspamd would be great!

![image](https://user-images.githubusercontent.com/106644/72198142-d99dae00-33dd-11ea-9b37-26bab7f38aad.png)

**Comment by michelsup** [comment]
Now it's the opposite, in Firefox I get an icon in the bookmark but not on the tab (anymore?)
In Chrome I dot not get both.

**Comment by moisseev** [comment]
Paths to the icons were accidentally changed to absolute.
https://github.com/rspamd/rspamd/blob/f7abf7b8807f30f100a12f3688d21ae3cf77c9ed/interface/index.html#L10-L14
@michelsup Are you using proxy in front of rspamd?
Is removing leading slashes in the `href` attributes fix the issue?

**Comment by michelsup** [comment]
Yes I do use a proxy.
Yes it does for both issues for both browsers. Good call, thank you.
