### ISSUE TITLE
src/libutil/addr.c binds on random port

### ISSUE THREAD

**Issue by cgzones** [rspamd/rspamd#3221]
During startup of rspamd or rspamadm I noticed attempts to bind on a random port.

This is an issue when using e.g. SELinux cause binds on unreserved ports are suspicious and therefore forbidden.

```
type=PROCTITLE msg=audit(01/16/20 16:18:26.419:323) : proctitle=/usr/bin/rspamd -c /etc/rspamd/rspamd.conf -f 
type=SOCKADDR msg=audit(01/16/20 16:18:26.419:323) : saddr={ fam=inet6 laddr=::1 lport=18803 } 
type=SYSCALL msg=audit(01/16/20 16:18:26.419:323) : arch=x86_64 syscall=bind success=no exit=EACCES(Permission denied) a0=0x4 a1=0x7ffe666e7200 a2=0x1c a3=0x0 items=0 ppid=1 pid=146436 auid=unset uid=_rspamd gid=_rspamd euid=_rspamd suid=_rspamd fsuid=_rspamd egid=_rspamd sgid=_rspamd fsgid=_rspamd tty=(none) ses=unset comm=rspamd exe=/usr/bin/rspamd subj=system_u:system_r:rspamd_t:s0 key=(null) 
type=AVC msg=audit(01/16/20 16:18:26.419:323) : avc:  denied  { name_bind } for  pid=146436 comm=rspamd src=18803 scontext=system_u:system_r:rspamd_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=tcp_socket permissive=0
```

Seems like https://github.com/rspamd/rspamd/blob/7e0bf487c39571d8fd228a2802f544ac11faa481/src/libutil/addr.c#L158-L174 are causing this behavior.

Is this check necessary?
Please consider avoiding to bind on a random port.

**Comment by vstakhov** [comment]
Yes, because fucking dual-stack in OSes could be broken in zillions of ways. I've expressed my frustration about it many times already but I don't know if there is a better sollution to understand if we have working IPv6 configuration or not.

**Comment by Lekensteyn** [comment]
With https://github.com/rspamd/rspamd/commit/4fe834a29f6592cfd3a11a4c231b5c9ca13cb49d merged, can this issue be closed now?
