### ISSUE TITLE
[BUG] milter port does not support /ping

### ISSUE THREAD

**Issue by cgzones** [rspamd/rspamd#3222]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Milter port seems to not support /ping request.

### Steps to Reproduce

```
$ curl http://127.0.0.1:11333/ping
pong
$ curl http://127.0.0.1:11334/ping
pong
$ curl http://127.0.0.1:11332/ping
curl: (52) Empty reply from server
```

rspamd log:
```
2020-01-16 17:09:24 #148331(rspamd_proxy) <7c4b01>; proxy; proxy_milter_error_handler: abnormally closing milter connection from: 127.0.0.1:36622, error: Command length is too big: 1195725855
```

**Expected behavior**
Responding a pong.

### Versions

Rspamadm 2.2
Debian

**Comment by vstakhov** [comment]
The problem is that once socket is accepted in the milter mode then only milter stuff is supported. We could probably read some data from socket and auto-detect what we have. But this is a bit tricky...
