### ISSUE TITLE
[BUG] DMARC reporting still crashes rspamd process (please reopen #2499)

### ISSUE THREAD

**Issue by maznu** [rspamd/rspamd#3229]
Please see [latest comments](https://github.com/rspamd/rspamd/issues/2499#issuecomment-575203320) in #2499, which show that the issue is still happening on rspamd 2.2.

**Comment by vstakhov** [comment]
Have you found volounteers/contractors to solve this issue? As I've said this logic should be completely rewritten, it is almost every time broken so far.

**Comment by maznu** [comment]
> As I've said this logic should be completely rewritten, it is almost every time broken so far.

I have only seen [your comment from over a year ago](https://github.com/rspamd/rspamd/issues/2499#issuecomment-427754874) in #2499 that this is fixed in the master branch.

If there is a discussion about rewriting the DMARC reporting somewhere, please could you link me up. It is something we could consider tackling here.

**Comment by dragoangel** [comment]
@maznu I have DMARC module enabled, but do not see any issues with hanging of RspamD v2.2. As I understand it hanging in case of issues with DNS resolving? I use it in docker as part of mailcow-dockerized which has unbound DNS resolver, it used as upstream DNS resolver for RspamD. Maybe you need check your DNS configuration and use own local DNS resolver, or maybe I have not so many reports to generate as you have =). After I saw your report, I looked to Zabbix at time frame of last 7 days and not see any stripes of CPU or RAM usage at time my RspamD send reports.

**Comment by maznu** [comment]
@dragoangel: in #2499 other people were having the same problem as me, so we are not the only users who could benefit from a fix.

@vstakhov: is there a discussion about "should be completely rewritten"? We are happy to help.

**Comment by vstakhov** [comment]
What sort of help do you mean here?

**Comment by maznu** [comment]
> What sort of help do you mean here?

As per your earlier message…

> Have you found volounteers/contractors to solve this issue? As I've said this logic should be completely rewritten, it is almost every time broken so far.

…we would consider rewriting the DMARC module. This is why I asked what you meant by "as I've said this logic should be completely rewritten".  Where have you said that?  What else did you say, was a design discussed, what work has been done already?
