### ISSUE TITLE
[BUG] Conflicting/Wrong implementation and documentation of `auth_only` setting of DKIM module

### ISSUE THREAD

**Issue by alexdupre** [rspamd/rspamd#3230]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

Documentation, configuration wizard and the actual code don't seem to be aligned on the meaning of the DKIM signing `auth_only` configuration setting.

The wizard asks the following question (https://github.com/rspamd/rspamd/commit/4f14063dcffe203b68d1456c28b11d33acb6326d#diff-3c326618c4086f8a317b8d1272efde10R315):
`Do you want to sign mail from authenticated users only? [Y/n]`

The configuration file says (https://github.com/rspamd/rspamd/commit/7b94f845f7732c3c8b5a70d8b29a482a91a68f32#diff-10b1967277648d6c56c6a7f1a7b26e93R37):
`If false, messages from authenticated users are not selected for signing`

The original code seemed to sign all messages if `auth_only=false`, and only messages from authenticated users and from sign/local networks if `auth_only=true` (similarly to what asked in the wizard), but two years ago it was changed by https://github.com/rspamd/rspamd/commit/8f1967692ce69d3a0dd97f806a41fb024ec8216e in a way that seems more similar to what stated in the config, but honestly I don't get why someone would like to avoid signing messages from authenticated users, and the code logs 'ignoring unauthenticated mail' even if the user is authenticated.

**Comment by vstakhov** [comment]
I'm not quite sure what is not clear here to be honest. `only` means `only` or am I missing something?

**Comment by alexdupre** [comment]
I want to think that for some reason you didn't read the full bug description with the needed attention. Please give it another try. If you won't see what's wrong I'll try to be more explicative.

**Comment by vstakhov** [comment]
I prefer unified diff language - that's something I can read easily.

**Comment by alexdupre** [comment]
I could make a patch if there was an agreement on what that flag should mean, that's one of the main issues.

Don't you see anything wrong in the following phrase?
```
Do you want to sign mail from authenticated users only?
If no, messages from authenticated users are not selected for signing.
```

**Comment by vstakhov** [comment]
Hum, what I understand means that if `auth_only` is true then we sign **if** a message comes from authenticated users. Otherwise, we look into other criterias.

Pseudo-code:

```
need_sign = false
if auth_only then
    if authenticated then
       need_sign = check_other_signing_conditions()
    end
else
  need_sign = check_other_signing_conditions()
end
```

**Comment by alexdupre** [comment]
Well, then we have 2 problems:
1) in English that phrases have a different meaning
2) the code is not doing what you are saying

**Comment by vstakhov** [comment]
```
local function is_skip_sign()
    return not (settings.sign_networks and is_sign_networks) and
        not (settings.auth_only and is_authed) and
        not (settings.sign_local and is_local)
  end
```

That's how it looks like now. It has been changed by @Lekensteyn recently: https://github.com/rspamd/rspamd/commit/845b8c00dc03d2a98f5514eda15f0e8909cd96b7#diff-c52540acb46df221a751fee771adb06c

**Comment by alexdupre** [comment]
Nope, look a few lines above, I've linked the diff in my original description and this is the current version:

https://github.com/rspamd/rspamd/blob/master/lualib/lua_dkim_tools.lua#L159

**Comment by alexdupre** [comment]
```
-thumbsup
+facts
```

**Comment by fatalbanana** [comment]
`auth_only` should rightly be called something like `sign_authenticated` for consistency with `sign_local` and `sign_networks` but is so-named for legacy reasons. Adding an alias mightn't hurt.

Configwizard shouldn't say `only` as that's misleading.

`ignoring unauthenticated mail` might better read `ignoring uninteresting mail'`.

Beyond that I don't see problems.

**Comment by alexdupre** [comment]
Ok, your explanation is fine. *If* that's the meaning of the flag, then we just have to fix the wording in a few places, all messages are wrong but the code is doing that.
But please note that you put a thumb up on a presudo-code with a completely different logic :-)

**Comment by Lekensteyn** [comment]
With https://github.com/rspamd/rspamd.com/pull/440, can this issue be closed?

The documentation for the DKIM signing module (not the DKIM module!) can be found here:
https://rspamd.com/doc/modules/dkim_signing.html

In particular, pay attention to this condition:
> To be eligible for signing, a mail must be received from an authenticated user OR a reserved (local) IP address OR an address in the `sign_networks` map (if defined)

My recent change only clarified the intention of the code, it has no functional effect. See also the description in https://github.com/rspamd/rspamd/pull/3214 for the motivation behind said recent change.

**Comment by alexdupre** [comment]
Your change is a big step forward in clarifying the code documentation, it may be enough to close this issue.

For the sake of completeness, I still don't fully like the wording of the `sign_*` comments, because they make to think the conditions are exclusive (AND) and not inclusive (OR). They'd clearer if expressed with positive language, as in:

`# If true, messages from authenticated users are selected for signing`
