### ISSUE TITLE
[Feature] Add an apt-stable repository for Debian Testing/Bullseye

### ISSUE THREAD

**Issue by aletheia7** [rspamd/rspamd#3237]
Debian has just moved from Testing/Buster to Testing/Bullseye .

See https://www.debian.org/releases/testing/

Please add an apt-stable repository for bullseye here: https://rspamd.com/apt-stable/dists/

Thank you.

**Comment by tkorkunckaya** [comment]
apt repository for bullseye still not in the list...
Testing for Debian is Bullseye now, i think it should be in this list: https://rspamd.com/apt/dists/
Thanks.
