### ISSUE TITLE
x509 certificates for rspamd.com and maps.rspamd.com seems to have expired

### ISSUE THREAD

**Issue by cstrotm** [rspamd/rspamd#3244]
Hi,

(sorry for posting an infrastructure issue here)

it seems to be that the x509 certificates for the websites https://rspamd.com and https://maps.rspamd.com have expired tonight.

rspamd instances are throwing errors because the software cannot access the new maps files.

![Screenshot 2020-02-02 at 08 53 03](https://user-images.githubusercontent.com/141758/73605201-2ca8f200-4593-11ea-836b-e5409e209d16.png)

**Comment by vstakhov** [comment]
All done. My nginx is still experiencing troubles for some reasons though.
