### ISSUE TITLE
[BUG] R_SUSPICIOUS_URL marking logwatch version [7.4.3] as 7.4.0.3 suspicious url

### ISSUE THREAD

**Issue by wienfuchs** [rspamd/rspamd#3248]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Logwatch Version in mails are marked as R_SUSPICIOUS_URL counting 5.0 points per default

### Steps to Reproduce

1. Enable logwatch on any Ubuntu 18.04 system
2. receive any log of this on any rspamd 2.2-1~bionic enabled system
3. read (previousely enabled) headers or history, you'll find R_SUSPICIOUS_URL (5) on logwatch [7.4.0.3] version number

**Expected behavior**
Would not expect the lua to mark a Logwatch "7.4.3" version info as "7.4.0.3" SUSPICIOUS_URL match with heavy 5 points. This probably will hit also other version numbers in future.

### Versions

Rspamd daemon version 2.2 from Ubuntu 2.2-1~bionic package
on Ubuntu 18.04.4 LTS
also Logwatch 7.4.3, same system

### Additional Information

Example matching mailboy (excerpt):
--- snip ---
 ################### Logwatch 7.4.3 (12/07/16) #################### 
        Processing Initiated: Wed Feb  5 05:25:10 2020
        Date Range Processed: yesterday
--- snap ---

Workaround:
Declare own LUA to match logwatch head to re-whitelist:
  re = '/# Logwatch \d\.\d\.\d (\d\d\/\d\d\/\d\d) #/{sa_raw_body}',
  score = -5.0
Alternatively whitelist mail address.

Fix: To be discussed. Maybe include the workaround in the check to avoid this? But then maybe some other software will hit this and so on. Maybe exclude 3-block digital matches (commonly used for any software version) from R_SUSPICIOUS_URL in general?

**Comment by rpv-tomsk** [comment]
Can you please provide more details of mail content?
Just checked, I can't reproduce this issue on plaintext email with content
```
To: me@domain.com
From: "Pavel" <me@another.domain.net>
Subject:  Logwatch 7.4.3 report
Message-ID: <5b991533-00e4-b9ae-aec2-1bcc1d5ea704@another.domain.net>
Date: Thu, 6 Feb 2020 01:52:55 +0700
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:68.0) Gecko/20100101
 Thunderbird/68.3.1
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 8bit
Content-Language: ru


################### Logwatch 7.4.3 (12/07/16) ####################
Processing Initiated: Wed Feb 5 05:25:10 2020
Date Range Processed: yesterday

-- 
C СѓРІР°Р¶РµРЅРёРµРј, РџР°РІРµР».
```

**Comment by wienfuchs** [comment]
Attached is an anonymised mail source from today's morning including rspamd produced headers.
[example.com.txt](https://github.com/rspamd/rspamd/files/4163358/example.com.txt)

This example surprisingly does not trigger in webui, but as you can see, it triggered in when received by mail (same host). rspamd.log confirms this:

2020-02-06 05:26:00 #8346(normal) <dc20d4>; task; rspamd_task_write_log: id: <20200206042558.ED16B180DE5@host.example.com>, qid: <76A2C54147F>, ip: n.n.n.n, from: <root@host.example.com>, (default:
 F (no action): [-13.00/15.00] [WHITELIST_OWN_HOSTS(-15.00){host.example.com;},R_SUSPICIOUS_URL(5.00){7.4.0.3;},BAYES_HAM(-3.00){100.00%;},DMARC_POLICY_SOFTFAIL(0.10){example.com : No valid SPF, No valid DKI
M;none;},MIME_GOOD(-0.10){text/plain;},ARC_NA(0.00){},ASN(0.00){asn:30823, ipnet:n.n.n.0/24, country:DE;},FROM_EQ_ENVFROM(0.00){},FROM_NO_DN(0.00){},MID_RHS_MATCH_FROM(0.00){},MIME_TRACE(0.00){0:
+;},PRECEDENCE_BULK(0.00){},RCPT_COUNT_ONE(0.00){1;},RCVD_COUNT_ZERO(0.00){0;},R_DKIM_NA(0.00){},R_SPF_NA(0.00){},TO_DN_NONE(0.00){},TO_EQ_FROM(0.00){}]), len: 23564, time: 794.848ms, dns req: 72, dig
est: <8715cffdb67055a0b71e4d8dd7135bea>, rcpts: <host.example.com>, mime_rcpts: <root@host.example.com>

**Comment by rpv-tomsk** [comment]
I think you have to continue work to provide minimized content which triggers marking.

Maybe some of your properties (which are hidden - i.e IP, domain/host names) are somehow related to 7.4.0.3 which unexpectedly matches logwatch version ?

Another proposal it to do binary patching of logwatch binaries to change its reported version and recheck
.

**Comment by rpv-tomsk** [comment]
If you want, you can send me a PM with real mail source: pavel2000@ngs.ru

**Comment by wienfuchs** [comment]
Sent, thank you so much for your look into this weird manner

**Comment by rpv-tomsk** [comment]
Hmm, found nothing.

1) Got two emails from @wienfuchs, one is `Logwatch 7.4.2` report and has `R_SUSPICIOUS_URL(5.00)[7.4.0.2];` symbol, another is `Logwatch 7.4.3` report and has `R_SUSPICIOUS_URL(5.00)[7.4.0.3];` symbol. This confirms what symbol cause is logwatch version.
2) When passing both email content through webui no R_SUSPICIOUS_URL symbol added.
3) If I try to change `Logwatch 7.4.3` string to `Logwatch 7.4.0.3` and `Logwatch http://7.4.0.3` still no R_SUSPICIOUS_URL symbol added (checked via webui).
4) Sent plain part of email from one my mailbox to another - no symbol added.

I was able to get R_SUSPICIOUS_URL only when email has explicit url `http://7.4.2` (`R_SUSPICIOUS_URL(5.00){7.4.0.2;},HTTP_TO_IP(1.00){}`).

I have nothing more to check. 
Required somebody with more knowledge about Rspamd internals.

**Comment by rpv-tomsk** [comment]
>Maybe exclude 3-block digital matches (commonly used for any software version) from R_SUSPICIOUS_URL in general?

Another thinking is @wienfuchs configuration has some kind of local LUA (pre-)processing of email content which causes symbol triggered.

**Comment by wienfuchs** [comment]
Don't think this two rules triggers. It is definately a little weird. But it anyhow should not hav too much priority just seen, as local Logwatch should be whitelisted anyhow as they can trigger other symbols (which should be triggered) on some special contents. The R_SUSPICIOUS_URL anyhow is only (improperly) triggered on the Logwatch versions with me, nowhere else, so probably this is a personal issue and not a general one then.

local.d/rspamd.lua :

# local lua addition

local reconf = config['regexp']

reconf['BLACKLIST_LOCAL_SYMBOL'] = {
  re = '/Kontakt und Datenschutz. blacklist at blacklist..ru .einen Punkt entfernen und .at. bedeutet ../{sa_raw_body}',
  description = "Has blacklisted blacklist at blacklist text",
  score = 10.0,
  one_shot = true,
}

reconf['BLACKLIST_LIST_UNSUBSCRIBE'] = {
  re = 'List-Unsubscribe=/(domain1|domain2|...)/{raw_header}',
  description = "Has blacklisted unsubscription domain",
  score = 10.0,
  one_shot = true,
}

**Comment by vstakhov** [comment]
Please send those samples to me as well (v@rspamd.com).

**Comment by wienfuchs** [comment]
rechecked with actual release
Rspamd daemon version 2.3 from Ubuntu 2.3-1~bionic package

could reproduce same with Logwatch 7.4.0.2, sample exists, can send if wanted
