### ISSUE TITLE
[BUG] url_redirector module: rspamd_lua_check_udata_common: lua type error

### ISSUE THREAD

**Issue by uvelokk** [rspamd/rspamd#3249]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
URL redirector module logs an error during connection to redis service. One example:
```
#8401(normal) <d313ef>; url_redirector; url_redirector.lua:314: check url https://goo.gl/forms/snip
#8401(normal) <d313ef>; url_redirector; url_redirector.lua:230: select user agent Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0)
#8401(normal) <d313ef>; url_redirector; url_redirector.lua:196: found redirect from https://goo.gl/forms/snip to https://docs.google.com/snip, err code 302
#8401(normal) <d313ef>; url_redirector; url_redirector.lua:204: stop resolving redirects as https://docs.google.com/snip is not a redirector
#8401(normal) rspamd_lua_check_udata_common: lua type error: expected rspamd{text} at position -1, but userdata has table metatable; trace:  [1]:{/usr/share/rspamd/lualib/lua_redis.lua:946 - redis_make_request [Lua]}; [2]:{/usr/share/rspamd/plugins/url_redirector.lua:143 - cache_url [Lua]}; [3]:{/usr/share/rspamd/plugins/url_redirector.lua:206 - <unknown> [Lua]}; stack(5): [1: table] [2: table] [3: table] [4: number] [5: ud=rspamd{url}] 
#8401(normal) lua_http_finish_handler: callback call failed: /usr/share/rspamd/lualib/lua_redis.lua:946: bad argument #5 to 'make_request' ('text' expected)
```

### Steps to Reproduce

1. Activate URL redirecor module: add option 'redirector_hosts_map' to local.d/rbl.conf
2. Set url_redirect module logging level to debug

### Versions

Rspamd 2.2-1\~buster, 2.3-1\~buster, 2.5-156\~buster

### Additional Information

OS: Debian 10
```
:~# rspamadm configdump url_redirector redis rbl
*** Section url_redirector ***
user_agent = "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0)";
key_prefix = "rdr:";
max_size = 10000;
nested_limit = 1;
check_ssl = false;
redirector_hosts_map = "/etc/rspamd/redirectors.inc";
expire = 86400;
timeout = 10;

*** End of section url_redirector ***
*** Section redis ***
db = "0";
servers = "127.0.0.1";
write_servers = "127.0.0.1";

*** End of section redis ***
*** Section rbl ***
default_exclude_users = true;
redirector_hosts_map = "/etc/rspamd/redirectors.inc";
/---snip---/
```

**Comment by kr1pt0ph0b14** [comment]
I got the following error reporting in the log file, is that related to the 'bug' above, too?

# cat /var/log/rspamd/rspamd.log
2020-03-01 09:48:56 #97298(main) rspamd_lua_check_udata_common: lua type error: expected rspamd{text} at position 2, but userdata has userdata metatable; trace:  [1]:{/usr/local/share/rspamd/plugins/phishing.lua:438 - <unknown> [Lua]}; stack(2): [1: ud=(NULL)] [2: ud=userdata] 
# rspamd -v
Rspamd daemon version 2.4
# 

If not, any idea on solving it? Thanks a lot.

**Comment by dvglab** [comment]
> I got the following error reporting in the log file, is that related to the 'bug' above, too?

The same stuff at me, just upgraded from 2.2 to 2.4
```
#cat rspamd.log | grep error
2020-03-02 08:02:21 #2751(main) <9aj59o>; symcache; rspamd_symcache_load_items: cannot open file /var/db/rspamd/symbols.cache, error 2, No such file or directory
2020-03-02 08:02:21 #2751(main) rspamd_lua_check_udata_common: lua type error: expected rspamd{text} at position 2, but userdata has userdata metatable; trace:  [1]:{/usr/local/share/rspamd/plugins/phishing.lua:438 - <unknown> [Lua]}; stack(2): [1: ud=(NULL)] [2: ud=userdata]
# freebsd-version
12.1-RELEASE-p2
# rspamd -v
Rspamd daemon version 2.4
```

**Comment by julian70400** [comment]
Same here, from 2.3 to 2.4 :


> 02/03/2020 à 13:18:42 | normal | 18686 |   |   | lua type error: expected rspamd{text} at position 2, but userdata has userdata metatable; trace: [1]:{/usr/share/rspamd/plugins/phishing.lua:438 - [Lua]}; stack(2): [1: ud=(NULL)] [2: ud=userdata]
> -- | -- | -- | -- | -- | --
> 02/03/2020 à 13:18:30 | normal | 18685 |   |   | lua type error: expected rspamd{text} at position 2, but userdata has userdata metatable; trace: [1]:{/usr/share/rspamd/plugins/phishing.lua:438 - [Lua]}; stack(2): [1: ud=(NULL)] [2: ud=userdata]
> 02/03/2020 à 13:18:23 | controller | 18684 |   |   | lua type error: expected rspamd{text} at position 2, but userdata has userdata metatable; trace: [1]:{/usr/share/rspamd/plugins/phishing.lua:438 - [Lua]}; stack(2): [1: ud=(NULL)] [2: ud=userdata]
> 02/03/2020 à 11:17:12 | main | 9113 |   |   | lua type error: expected rspamd{text} at position 2, but userdata has userdata metatable; trace: [1]:{/usr/share/rspamd/plugins/phishing.lua:438 - [Lua]}; stack(2): [1: ud=(NULL)] [2: ud=userdata]

**Comment by heraklit256** [comment]
As far as I am concerned, rspamd 2.5 fixed this problem.

**Comment by jendis** [comment]
Version 2.5 still has this issue.

**Comment by uvelokk** [comment]
Thank you, @jendis & @vstakhov!
