### ISSUE TITLE
[BUG] Release 2.3 broke listening on IPv6

### ISSUE THREAD

**Issue by irworks** [rspamd/rspamd#3254]
We are running rspamd in an IPv6 only environment, that's the reason we ran into this issue. rspamd is running in a separate container, postfix and dovecot are running in others. Just to clarify our network structure and explain why v6 communication is key to our setup.

### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Since upgrading to 2.3 all rspamd services stopped listening on v6.

### Steps to Reproduce

1. Install rspamd in an v6 only environment.

**Expected behavior**
rspamd should listen on v6 and v4 if configured this way.

### Versions

`Rspamd daemon version 2.3`
Debian 10:
`Linux rspamd 4.15.18-21-pve #1 SMP PVE 4.15.18-48 (Fri, 20 Sep 2019 11:28:30 +0200) x86_64 GNU/Linux`

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

Config, which should support listening on v6 and v4.
```
root@rspamd ~ # cat /etc/rspamd/local.d/worker-controller.inc 
bind_socket = "*:11334";
```

Nothing is listening on v6. 
```root@rspamd ~ # netstat -tulpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          1662448916 193/sshd            
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      0          1662450103 375/master          
tcp        0      0 0.0.0.0:11332           0.0.0.0:*               LISTEN      107        1662449309 184/rspamd: main pr 
tcp        0      0 127.0.0.1:11333         0.0.0.0:*               LISTEN      107        1662449331 184/rspamd: main pr 
tcp        0      0 0.0.0.0:11334           0.0.0.0:*               LISTEN      107        1662449326 184/rspamd: main pr 
tcp6       0      0 :::22                   :::*                    LISTEN      0          1662448918 193/sshd            
tcp6       0      0 ::1:25                  :::*                    LISTEN      0          1662450104 375/master```

Thank you very in advance much for looking into this.

**Comment by vstakhov** [comment]
What is in your `/proc/net/if_inet6` file?

**Comment by irworks** [comment]
Thank you for the fast response, here is the output:

```
root@rspamd ~ # cat /proc/net/if_inet6
00000000000000000000000000000001 01 80 10 80       lo
fe8000000000000060d443fffe6b1786 be 40 20 80     eth0
2a0103d8101800020000000000001819 be 30 00 80     eth0
```

**Comment by vstakhov** [comment]
That's strange. Could you please do strace for the main process with the emphasis on `socket`, `bind` and `listen` syscalls?

**Comment by irworks** [comment]
Short update: When supplying a concrete IPv6 address instead of * it suddenly works:

```
root@rspamd ~ # cat /etc/rspamd/local.d/worker-controller.inc 
bind_socket = "[2a01:3d8:1018:2::1819]:11334";
```

**Comment by jendis** [comment]
We observe in release 2.3 the problem with v6 too.
To be more specific, when we set any worker e.g. _/etc/rspamd/local.d/worker-normal.inc_ 
> bind_socket = "localhost:11333";

then 
> admin@dev ~ $ dev telnet ::1 11333
> Trying ::1...
> telnet: Unable to connect to remote host: Connection refused

but when
> bind_socket = "[::1]:11333";

then 
> admin@dev ~ $ dev telnet ::1 11333
> Trying ::1...
> Connected to ::1.
> Escape character is '^]'

This causes after deployment of the 2.3 release unexpected crashes because our other services communicating with **rspamd** on _localhost_ use _::1_ by default.

**Comment by jendis** [comment]
There is even suspicious lines in the log when _bind_socket = "localhost:11333"_ for **normal** and _bind_socket = "localhost:11334"_ for **controller** worker set :
> (main) rspamd_inet_address_listen: bind 127.0.0.1:11333 failed: 98, 'Address already in use'
> (main) rspamd_inet_address_listen: bind 127.0.0.1:11333 failed: 98, 'Address already in use'

Checked and no other process on that socket binded and workers on that socket are listening.

**Comment by vstakhov** [comment]
Dual stack sucks. That's all I can say. Using localhost instead of ip or `*` is also a stupid idea (similarly to considering localhost both ::1 and 127.0.0.1 and not just an ipv4 address). And poor developers have to work with all this mess invented by uneducated or, sometimes, overeducated idiots.

**Comment by vstakhov** [comment]
BTW, OSX defines `localhost` as `127.0.0.1` ¯\_(ツ)_/¯.

**Comment by vstakhov** [comment]
Ok, `*:11334` listens on both ipv4 and ipv6 on osx.

**Comment by vstakhov** [comment]
Ok, it's all very very funny.

First, thing:

```
root@rspamd-test:~# cat /proc/net/if_inet6
fe80000000000000042ab5fffedefc88 02 40 20 80     ens3
2a0104f9002a1d9d042ab5fffedefc88 02 40 00 00     ens3
00000000000000000000000000000001 01 80 10 80       lo
root@rspamd-test:~# stat /proc/net/if_inet6
  File: /proc/net/if_inet6
  Size: 0               Blocks: 0          IO Block: 1024   regular empty file
Device: 4h/4d   Inode: 4026532150  Links: 1
Access: (0444/-r--r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-02-25 20:35:12.079873892 +0100
Modify: 2020-02-25 20:35:12.079873892 +0100
Change: 2020-02-25 20:35:12.079873892 +0100
 Birth: -
```

So the `stat(2)` reports zero size but this file actually is not empty!

Next, if I specify `AF_INET` and not `AF_UNSPEC` to `getaddrinfo` in Linux, it returns `127.0.0.1` twice! What a mess! glibc is seriously broken I suppose.

**Comment by irworks** [comment]
Out of curiosity: Why does rspamd implement DNS resolving on its own instead of using `gethostbyname()` syscalls or similar? By using the method rspamd ignores `/etc/nsswitch.conf` settings, which prevents hostname overrides.

**Comment by vstakhov** [comment]
Rspamd uses `getaddrinfo` for listening address resolution as this task is not performance critical. But even for that purposes, this call is a mess: read my message above. `gethostbyname` is apparently no way for anything that cares about performance nor for anything that is not intended to block anywhere (like Rspamd for both things).
