### ISSUE TITLE
[BUG] howto do whitelisting in the reputation module / possible bug in lua_maps_expressions

### ISSUE THREAD

**Issue by rm-minus-rf** [rspamd/rspamd#3256]
### Description ###
**Part A (Documentation how to use whitelist maps for the reputation module, seems to be missing)**

After reading https://www.rspamd.com/doc/migration.html#migration-to-rspamd-20 we tried to adapt our ip_score whitelisting maps to the reputation module.
Unfortunately there is no documented way to whitelist that we could find for the reputation module: https://www.rspamd.com/doc/modules/reputation.html.

Looking at the lua source it seems that you can define whitelists exactly like "combined maps" in the multimap module (both use lua_maps_expressions.lua): https://www.rspamd.com/doc/modules/multimap.html#combined-maps.
Here is our local.d/reputation.conf as reference for other users that want to whitelist and also as description how to reproduce Part B:
```
rules {
  ip_reputation =  {
    selector "ip" {
    }
    backend "redis" {
    }

    symbol = "IP_REPUTATION";

    whitelist = {
      rules {
        ip_whitelist = {
          type = "radix";
          map = "$LOCAL_CONFDIR/local.d/ip_score-whitelist-ips.inc";
          selector = "ip";
        }
      }
      expression = "ip_whitelist";
    }
  }

...

}
```

**Part B (radix map as whitelist for the ip selector in the repuation module seems to whitelist all ip adresses regardless of map content)** 
After we managed to have rspamd accept the whitelist definition, we hit another problem: Every remote ip was whitelisted.
Adding some debug messages we traced it to line 81 in lua_maps_expressions.lua:
```
--- /usr/share/rspamd/lualib/lua_maps_expressions.lua 2020-02-06 10:22:40.957807764 +0100
+++ /tmp/lua_maps_expressions.lua-orig  2020-02-06 10:22:40.073809929 +0100
@@ -78,7 +78,7 @@
 
   local res = elt.expr:process(process_atom)
 
-  if res > 0 then
+  if res then
     return res,matched
   end
```

Not sure what elt.expr:process has as possible return values.
But it seems that even if there is no match in the map the return value was still evaluated to true by lua afterwards.
Changing the condition to "> 0" seems to fix it for our case. Not sure if it might destroy combined symbols in multimap, though. (never used them).

### Versions
rspamd 2.2 (rpm) @ RHEL 7.7

**Comment by vstakhov** [comment]
Your proposed fix is correct, thank you! It should definitely be `> 0`.
