### ISSUE TITLE
[BUG] 2.3 does not build on FreeBSD when using LibreSSL

### ISSUE THREAD

**Issue by Nuadh** [rspamd/rspamd#3257]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
rspamd 2.3 fails to build on FreeBSD using poudriere with libressl

### Steps to Reproduce

1. set
DEFAULT_VERSIONS+= ssl=libressl
in relevant make.conf
2. run
poudriere bulk -j $jailname mail/rspamd
3. watch rspamd fail to be built. Relevant error messages from the log:
/wrkdirs/usr/ports/mail/rspamd/work/rspamd-2.3/src/libutil/util.c:2487:15: warning: implicit declaration of function 'FIPS_mode' is invalid in C99 [-Wimplicit-function-declaration]
                        int mode = FIPS_mode ();
/wrkdirs/usr/ports/mail/rspamd/work/rspamd-2.3/src/libutil/util.c:2492:9: warning: implicit declaration of function 'FIPS_mode_set' is invalid in C99 [-Wimplicit-function-declaration]
                                if (FIPS_mode_set (1) != 1) {
ld.lld: error: src/librspamd-server.so: undefined reference to FIPS_mode
ld.lld: error: src/librspamd-server.so: undefined reference to FIPS_mode_set
ld.lld: error: src/librspamd-server.so: undefined reference to FIPS_mode
ld.lld: error: src/librspamd-server.so: undefined reference to FIPS_mode_set

**Expected behavior**
For rspamd to be built.

### Versions
Rspamd:
rspamd-2.3

FreeBSD:
FreeBSD 12-1.RELEASE-p2

Compiler:
FreeBSD clang version 8.0.1 (tags/RELEASE_801/final 366581) (based on LLVM 8.0.1)
Target: x86_64-unknown-freebsd12.1
Thread model: posix

CPU:
Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz

### Additional Information
using libressl instead of openssl. LibreSSL does not support FIPS mode

Attached is the build log:
[rspamd-2.3.log](https://github.com/rspamd/rspamd/files/4170916/rspamd-2.3.log)

**Comment by vstakhov** [comment]
Just replied in bugzilla: https://github.com/rspamd/rspamd/commit/963657514d24c29604e0b873c17dcee0d3efd345 should fix it.

**Comment by Nuadh** [comment]
<3 (sorry for the lack of title on the bug report btw)

**Comment by Nuadh** [comment]
Patches works. Thanks.

**Comment by lanodan** [comment]
Can confirm that it also fixes it on gentoo with LibreSSL.
