### ISSUE TITLE
Total weight of X-Spamd-Result is not real

### ISSUE THREAD

**Issue by romale** [rspamd/rspamd#3262]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Marked as SPAM with strange summary of balls.
Real sum of balls from header is about -5.5, but X-Spamd-Result show 6.0

### Steps to Reproduce

I've email marked as SPAM, but sum of any balls from header is not valid.

X-Spamd-Result: default: False [**6.00** / 20.00];
	 HAS_REPLYTO(0.00)[reply-febc1c7577610c7a-108_HTML-1177957529-1014838-271283@email.microsoftonline.com];
	 R_DKIM_REJECT(0.00)[email.microsoftonline.com:s=200608];
	 R_SPF_ALLOW(-0.20)[+ip4:52.100.0.0/14];
	 DKIM_MIXED(0.00)[];
	 RCVD_DKIM_ARC_DNSWL_MED(-0.50)[];
	 RCVD_COUNT_THREE(0.00)[4];
	 TO_DN_ALL(0.00)[];
	 DKIM_TRACE(0.00)[mailbio.onmicrosoft.com:+,email.microsoftonline.com:-];
	 RCVD_IN_DNSWL_MED(-0.20)[10.1.1.4:from];
	 MX_GOOD(-0.01)[];
	 FORGED_SENDER(0.30)[Office365@email.microsoftonline.com,username@mail.bio.domain.ru];
	 MIME_TRACE(0.00)[0:+,1:+,2:~];
	 RCVD_TLS_LAST(0.00)[];
	 ARC_ALLOW(-1.00)[i=1];
	 ASN(0.00)[asn:2848, ipnet:10.1.0.0/18, country:RU];
	 FROM_NEQ_ENVFROM(0.00)[Office365@email.microsoftonline.com,username@mail.bio.domain.ru];
	 FORGED_RECIPIENTS(1.00)[username@mail.bio.domain.ru,username@gen.domain.su];
	 BAYES_HAM(-3.00)[100.00%];
	 R_DKIM_ALLOW(-0.20)[mailbio.onmicrosoft.com:s=selector2-mailbio-onmicrosoft-com];
	 FROM_HAS_DN(0.00)[];
	 DMARC_POLICY_QUARANTINE(1.50)[email.microsoftonline.com : SPF not aligned (relaxed), DKIM not aligned (relaxed),quarantine];
	 MIME_GOOD(-0.10)[multipart/alternative,text/plain];
	 REPLYTO_DOM_EQ_FROM_DOM(0.00)[];
	 RCPT_COUNT_ONE(0.00)[1];
	 MANY_INVISIBLE_PARTS(0.05)[1];
	 NEURAL_HAM(-3.11)[-1.037]

**Expected behavior**
X-Spamd-Result: default: False [**-5.5** / 20.00];

### Versions

Rspamd daemon version 2.3
CentOS Linux release 7.7.1908 (Core)

Cpu 8 cores

processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version (cpu64-rhel6)
stepping        : 3
microcode       : 0x1
cpu MHz         : 2593.748
cache size      : 4096 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 4
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm nopl eagerfpu pni cx16 hypervisor lahf_lm
bogomips        : 5187.49
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by vstakhov** [comment]
Not a bug, read the documentation (FAQ).
