### ISSUE TITLE
[Feature] List of subdomains to be checked in rbl

### ISSUE THREAD

**Issue by LonePhalcon** [rspamd/rspamd#3267]
## Summary
Apart from the effective tld names there needs to be a manual way to make RspamD check subdomains. It was in RspamD prior to 2.0 release (afair) in surbl module under the name of "exceptions".

## Example 
We have "earth" domain in effective tld names and we want to check scum.of.earth in rbl.

Currently it would go to etld, get "earth" domain, add one level and proceed to check of.earth in rbl, which is (for the purpose of this example) a hosting.

With the added list you could manually add "*.of.earth" to something akin to effective domains and scum.of.earth would be checked.

"of.earth" would effectively become whitelisted, but its subdomains would be checked.
## Motivation
Effective tld names list does not provide us with all the possible hosting services and similar resources, which are usually too slow to react to the complaints, that one of their clients is sending spam. And blocking the whole domain would cause more trouble than it's worth.

**Comment by vstakhov** [comment]
Here are the current test cases:


```lua
  -- First one is the input hostname, the second is the expected results
  cases = {
    {'example.com', 'example.com'},
    {'baz.example.com', 'baz.example.com'},
    {'3.baz.example.com', 'baz.example.com'},
    {'bar.example.com', 'example.com'},
    {'foo.example.com', 'foo.example.com'},
    {'3.foo.example.com', '3.foo.example.com'},
  }
  -- Just a domain means domain + 1 level
  -- *.domain means the full hostname if the last part matches
  -- !domain means exclusion
  -- !*.domain means the same in fact :)
  -- More rules can be added easily...
  local excl_rules1 = {
      'example.com',
      '*.foo.example.com',
      '!bar.example.com'
  }
```

Does it look sane?

**Comment by LonePhalcon** [comment]
Yes, looks nice.
