### ISSUE TITLE
[BUG] Webinterface History regression in 2.3: missing columns

### ISSUE THREAD

**Issue by CAPSLOCK2000** [rspamd/rspamd#3271]
**Missing information in Webinterface History**
After upgrading to 2.3 some columns are missing from the History page of the Webinterface.
Futhermor, when a log entry is expanded it contains far less extra information.

Version <= 2.2: 
columns:
ID | IP address | [Envelope From] From | [Envelope To] To/Cc/Bcc | Subject | Action | Score | Msg size | Scan time | Time | Authenticated user

log: entry
[Envelope To] To/Cc/Bcc
Symbols                ....  ...   ... (symbols)
Sort by:
Magnitude Value Name

Version >= 2.3:
columns:
ID | IP address | Action | Score | Message size | Scan time | Time | Authenticated user

log entry:
symbols ... ... (symbols) 

The missing columns (From, To, Subject) are rather important when looking for a specific mail. Most users are unable to provide a Message ID and rely on the "From", "To" and "Subject" to specify what mail they are talking about.

### Versions
Tested with your Debian packages for:
- Rspamd daemon version 2.3
- Rspamd daemon version 2.4-git.b3489b088
- Rspamd daemon version 2.4-git.3fbf6a943

Running on Debian Buster (amd64).

### Additional Information
There is nothing in the debug logs that seems related.
I've inspected the HTML and see no trace of the missing information.
We are also having some problems with connecting to Redis over IPv6, but I do not think it is related as the other columns are still there and contain valid information.

There is nothing in the changelog that indicates this was changed intentionally nor can I find a commit message that says so, so I assume this is a regression.
Looking back through commits I think it broke in https://github.com/rspamd/rspamd/commit/61e85c6e7ad7a59b5f29465480a4b0c178ab740d#diff-5770e36f7e56928fe4642c0129b4e8a2 as that was the last major change to history.js

**Comment by moisseev** [comment]
> columns:
ID | IP address | Action | Score | Message size | Scan time | Time | Authenticated user

Looks like **legacy** history.
Please check if the redis_history module is enabled.
You can get the list of enabled modules with `rspamadm configwizard`.

**Comment by CAPSLOCK2000** [comment]
Thanks, that is a useful hint.
The module is indeed disabled and configwizard shows that it is because Redis is not reachable.
I guess that (not being able to connect to) Redis is the root cause. I'll close this report for now.

I have to say that it is rather confusing that this old history module is still around and shows somewhat useful information.
