### ISSUE TITLE
[BUG] Error creating DMARC report

### ISSUE THREAD

**Issue by simon816** [rspamd/rspamd#3272]
Going to do away with the bug report template because it'll be a pain to reproduce this with all debug info.

I found this error in the rspamd log file:
```
(rspamd_proxy) lua_redis_push_data: call to callback failed:
/usr/share/rspamd/plugins/dmarc.lua:864: invalid argument;
trace:
[1]:{[C]:-1 - escape_xml [C]};
[2]:{/usr/share/rspamd/plugins/dmarc.lua:864 - xmlf [Lua]}; 
[3]:{/usr/share/rspamd/plugins/dmarc.lua:912 - send_report_via_email [Lua]};
[4]:{/usr/share/rspamd/plugins/dmarc.lua:990 - callback [Lua]};
[5]:{/usr/share/rspamd/lualib/lua_redis.lua:985 - <unknown> [Lua]};
```
(added line breaks for readability)

rspamd version 2.3.1.
OS: CentOS Linux release 7.7.1908 (Core)

Domain in question: `twitch.tv`

```
_dmarc.twitch.tv.	300	IN	TXT	"v=DMARC1; p=reject; adkim=s; aspf=s; fo=1; ri=3600; rua=mailto:twitch@rua.agari.com; ruf=mailto:twitch@ruf.agari.com"
```

From a quick glance at the code, it could be a type error:
https://github.com/rspamd/rspamd/blob/2.3/src/plugins/lua/dmarc.lua#L1173
I wonder if the default for `pct` should be a string not a number. Though, don't know lua so I could be wrong on that.

**Comment by simon816** [comment]
Just scanned through some older log files

Exactly the same traceback for these domains:
```
_dmarc.github.com.	3261	IN	TXT	"v=DMARC1; p=none; rua=mailto:dmarc@github.com"
```
```
_dmarc.google.com.	300	IN	TXT	"v=DMARC1; p=reject; rua=mailto:mailauth-reports@google.com"
```

Report sent successfully for:
```
_dmarc.amazon.com.	900	IN	TXT	"v=DMARC1; p=quarantine; pct=100; rua=mailto:dmarc-reports@bounces.amazon.com; ruf=mailto:dmarc-reports@bounces.amazon.com"
```

**Comment by vstakhov** [comment]
Yes, it looks like this a type issue. I will fix it soon.

**Comment by simon816** [comment]
Seems to be working fine on 2.4. Thanks.
