### ISSUE TITLE
[Feature] Allow blacklisting domains from DMARC reporting

### ISSUE THREAD

**Issue by kyrias** [rspamd/rspamd#3274]
# Summary

I want to be able to maintain a blacklist of domains that DMARC reports will not be sent for.

## Motivation

There are a lot of domains where the configured DMARC reporting address mailbox is either full, or completely nonextant.  This leads to me receiving multiple such bounced emails every day.

## Describe alternatives you've considered

I've tried contacting each of them, but their hostmaster addresses are also either bouncing or just never reply.

**Comment by vstakhov** [comment]
no_reporting_domains already exists in the module

**Comment by kyrias** [comment]
Oh, indeed, it's just missing from the documentation.  Thanks!
