### ISSUE TITLE
[BUG] Symbol MIME_ENCRYPTED_ARCHIVE for un-encrypted 7z archives

### ISSUE THREAD

**Issue by spacefreak86** [rspamd/rspamd#3275]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
The symbol MIME_ENCRYPTED_ARCHIVE is set on un-encrypted archives in some cases.
I have found out that it happens, when a 7z archive contains a ".pdf" file or just an empty directory. It does not happen when the archive only contains a ".txt" file.

### Steps to Reproduce

1. Create a 7z archive containg just an empty directory:
user@host ~ $ mkdir /tmp/xx
user@host ~ $ 7z a /tmp/test.7z /tmp/xx

2. Send the archive as attachment (e.g. with swaks):
user@host ~ $ swaks --from=FROM_ADDRESS --to=TO_ADDRESS --attach /tmp/test.7z --server MAILSERVER

**Expected behavior**
Symbol MIME_ENCRYPTED_ARCHIVE should not be set as the archive is not encrypted.

### Versions

Rspamd: 2.3
OS: Gentoo (x86_64)

### Additional Information

I am not sure if this is important or not, but the symbol MIME_BAD_ATTACHMENT is always set too when MIME_ENCRYPTED_ARCHIVE is falsely set.

**Comment by vstakhov** [comment]
7zip just sucks. That's it.

**Comment by spacefreak86** [comment]
Usually I would fix the issue by myself an do a PR. My problem is that the issue seems to be in the C part of Rspamd.
The company I am working for is just providing services, so I am not allowed to spend time to setup the needed environment to tackle this issue.

If I could help in any other way, just let me know.

**Comment by vstakhov** [comment]
The proper fix would require at least around a week of my time. I don't think it's worth that.

**Comment by spacefreak86** [comment]
Then I may check if I could get some time to fix it by myself.
For us, this bug is mission critical because we reject mails with encrypted attachments. We do that to guarantee that every part of every mail passes the virus scanners.

**Comment by LucaAruba** [comment]
Hi, 
i ve got the same problem.
I banned for example .wsf extensions.
If anyone send an email with a wsf file extension and pdf file on 7z archive, rspamd detect the archive as MIME_ENCRYPTED_ARCHIVE then don't list the files inside and email will be accepted instead blocked for invalid extension found. 

Can you please reopen the issue and solve the bug ?
