### ISSUE TITLE
[BUG] Reject message of force_actions plugin ignored

### ISSUE THREAD

**Issue by spacefreak86** [rspamd/rspamd#3276]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
After updating from Rspamd 2.1 to 2.3, the reject messages configured in force_actions plugin are visible in the log, but the MTA always returns the default message "Spam message rejected" to the client.

### Steps to Reproduce

1. Configure a rule in /etc/rspamd/local.d/force_actions.conf, for example:
  SPF_FAIL {
    action = "reject";
    expression = "R_SPF_FAIL";
    message = "Message rejected due to SPF failure";
  }

2. Send a message which violates above rule.

**Expected behavior**
The MTA should reject the message with the configured reject message.

### Versions

Rspamd: 2.3
OS: Gentoo

### Additional information

Here is the debug log of such a message.

Feb 26 09:43:41 HOSTNAME rspamd[25560]: <c8a636>; proxy; rspamd_task_write_log: id: <undef>, qid: <483D820BE72>, ip: XX.XX.XX.XX, from: <SENDER@SENDERDOMAIN>, (default: T (reject): [4.69/15.00] [MISSING_MID(2.50){},HFILTER_HELO_IP_A(1.00){mailserver.ccc.intra;},R_SPF_FAIL(1.00){-all;},HFILTER_HELO_NORES_A_OR_MX(0.30){mailserver.ccc.intra;},MIME_GOOD(-0.10){text/plain;},ARC_NA(0.00){},ASN(0.00){asn:20914, ipnet:XX.XX.XX.XX/XX, country:CH;},DMARC_NA(0.00){SENDERDOMAIN;},FORCE_ACTION_SPF_FAIL(0.00){reject;},FROM_EQ_ENVFROM(0.00){},FROM_NO_DN(0.00){},MIME_TRACE(0.00){0:+;},RCPT_COUNT_ONE(0.00){1;},RCVD_COUNT_ZERO(0.00){0;},R_DKIM_NA(0.00){},TO_DN_NONE(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){}]), len: 220, time: 6098.428ms, dns req: 24, digest: <b22921db38be6efca1815852b88c6d24>, rcpts: <RCPT@RCPTDOMAIN>, mime_rcpts: <RCPT@RCPTDOMAIN>, forced: reject "Message rejected due to SPF failure"; score=nan (set by force_actions)
Feb 26 09:43:41 chsfslx0250 rspamd[25560]: <c8a636>; milter; rspamd_milter_send_action: command y; value=554 5.7.1 Spam message rejected

**Comment by vstakhov** [comment]
That is already fixed in the master (and experimental packages)

**Comment by clangguth** [comment]
Just a question, as I was about to file pretty much the same bug, but for the antivirus module: Does that commit also fix the bug that the `message` setting in `antivirus.conf` isn't working? 

Funnily, for me the message= setting in antivirus doesn't work, but I found a (half-decent) workaround by using the force_actions plugin.

So in other words: force_actions `message` setting works here, but antivirus `message` setting doesn't. (Using version `2.4-1~bionic`) - is this the same bug and the same fix?
