### ISSUE TITLE
[BUG] upgrade to 2.4 results in huge memory spike - have to kill process

### ISSUE THREAD

**Issue by caffeinejolt** [rspamd/rspamd#3278]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Today I tried upgrading to https://rspamd.com/rpm-stable/centos-8/x86_64/rspamd-2.4-1.x86_64.rpm

Result in memory/cpu spike on starting process - rolled back to 2.3 and things work fine again.

The mail server it is used on had 1GB of RAM.  Starting rspamd 2.4 effectively brings the server to its knees (no longer handling mail... or doing anything - I am just barely able to type "systemctl stop rspamd") - so my ability to provide extended information is inhibited since in order to do so... I have to bring the server down.  

### Steps to Reproduce

1. yum upgrade from 2.3 to 2.4
2. type systemctl stop rspamd quickly before system becomes completely unresponsive

**Expected behavior**
That rspamd would fire up like it always has after a yum update

### Versions
2.3
2.4

### Additional Information

Its pretty much a stock rspamd setup with minimal config in local.d (not even running redis) - I just added razor support to try and catch a few more spams that keep getting through to me

**Comment by vstakhov** [comment]
Congratulations! I'm closing this 'useful' issue report now.

**Comment by vstakhov** [comment]
Please reopen if actual using the github issue template provided with all information required.

**Comment by caffeinejolt** [comment]
ok - filled in more details

**Comment by vstakhov** [comment]
You can try to enable swap and attach strace to the process starting I suppose.

**Comment by vstakhov** [comment]
I don't observe more than 50mb of rss per process in Rspamd.

**Comment by caffeinejolt** [comment]
I just tried installing in a centos 8 VM with nothing in local.d - same result - it brings the system down.  So it should be very repeatable....

**Comment by caffeinejolt** [comment]
Actually - I take the above back - the VM had too little memory allocated to run rspamd.... need to test this out more...

**Comment by caffeinejolt** [comment]
I think the problem here is with my mail server - it simply does not have enough memory.  Going from 2.3 to 2.4 seems to require WAY more memory:

2.3

Process 'rspamd'                                                        
  status                       OK                                       
  monitoring status            Monitored                                
  monitoring mode              active                                   
  on reboot                    start                                    
  pid                          29350                                    
  parent pid                   1                                        
  uid                          989                                      
  effective uid                989                                      
  gid                          985                                      
  uptime                       1h 9m                                    
  threads                      1                                        
  children                     4                                        
  cpu                          0.0%                                     
  cpu total                    0.0%                                     
  memory                       7.0% [57.4 MB]                           
  memory total                 34.2% [280.9 MB]                         
  security attribute           system_u:system_r:unconfined_service_t:s0
  disk read                    0 B/s [80 kB total]                      
  disk write                   0 B/s [5.5 MB total]                     
  data collected               Wed, 26 Feb 2020 11:51:33                

2.4

Process 'rspamd'
  status                       OK
  monitoring status            Monitored
  monitoring mode              active
  on reboot                    start
  pid                          28453
  parent pid                   1
  uid                          985
  effective uid                985
  gid                          983
  uptime                       7m
  threads                      1
  children                     4
  cpu                          0.0%
  cpu total                    0.0%
  memory                       17.6% [322.3 MB]
  memory total                 77.9% [1.4 GB]
  security attribute           system_u:system_r:unconfined_service_t:s0
  disk read                    0 B/s [836 kB total]
  disk write                   0 B/s [15.1 MB total]
  data collected               Wed, 26 Feb 2020 11:53:10

**Comment by caffeinejolt** [comment]
Had a chance to look at this again - so 2.4 only uses substantially more memory than 2.3 when initializing the files in /var/lib/rspamd.  After that is done - if you restart it - it still uses more memory than 2.3, but not enough to wipe out a 1GB RAM VM.

This probably only impacts a small percentage of rspamd users like me who use it on very small mail servers (i.e. my personal mail).  Hopefully this helps others who might run across this situation.

**Comment by vstakhov** [comment]
It happens as Rspamd has to recompile publicsuffix list in hyperscan. Unfortunately, this procedure cannot be postponed and it must be executed once on start. Then this database is serialised and saved on disk - so no more expensive calculations are needed. However, the first recompile is inevitable.
