### ISSUE TITLE
[BUG] File-based lua map is not loaded on startup

### ISSUE THREAD

**Issue by oxc** [rspamd/rspamd#3283]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch
* [ ] I have not tried ASAN builds because they are not available for xenial

**Describe the bug**

I have a map that is defined in a custom lua plugin:

```lua
local virtual_alias_map = rspamd_config:add_map{
  type = "hash",
  url = "file:///etc/rspamd/virtual_alias_maps",
  description = "Postfix virtual alias table",
}
```

However, this map gets never loaded, until I manually touch the file. The "init scheduled check" periodic is triggered and executed, but the map does not get any entries.
Upon re-reading from stat change, the entries get loaded correctly.

**Expected behavior**
I expect the map to be loaded on rspamd startup.

### Versions
Rspamd daemon version 2.4
Version: 2.4-2~xenial

Virtualization: qemu
Operating System: Ubuntu 16.04.6 LTS
Kernel: Linux 4.4.0-173-generic
Architecture: x86-64

### Additional information
Here is a log-excerpt with `debug_modules = ["map"]`. It covers a rspamd restart, and shows that the map is not loaded on startup.
When I touch the map file after a few minutes, the content gets loaded.
(I've waited much longer in earlier trials, but don't have the log outputs)

[rspamd.log](https://github.com/rspamd/rspamd/files/4278137/rspamd.log)

I have redacted some sensitive information, but not removed anything.

Note that the "read hash of 30 elements" only occurs after touching the map file, however its content has not changed.

**Comment by oxc** [comment]
This still happens on 2.5.0

**Comment by vstakhov** [comment]
You have added it from a wrong place. Maps must be added on the configuration stage - basically in the main body of lua scripts, not from callbacks/periodics/on_load functions. Also you should use lua_maps module as it provides convenience around maps handling. Not an Rspamd bug, closing.

**Comment by oxc** [comment]
Thanks. Requiring it from rspamd.local.lua helped. Sorry for the inconvenience.
