### ISSUE TITLE
WebUI cluster members - Cannot get server status

### ISSUE THREAD

**Issue by stfast** [rspamd/rspamd#3284]
Hi,

I'we set WebUI neighbours, but I get an error after logging

Request failed
server2 > Cannot get server status
Request failed

Please enlight me with a working configuration setup for WebUI cluster.

$ cat options.inc 
neighbours {
	server2 { host = "localhost:11334"; }
	server2 { host = "172.16.103.26:11334";}
}

Server 2 
$ telnet 172.16.103.26 11334
Trying 172.16.103.26...
Connected to 172.16.103.26.
Escape character is '^]'.

**Comment by moisseev** [comment]
1. Server names should be unique, e.g. `server1` and `server2`.
2. Host names need to be resolvable on web browser side. So `localhost` is not likely want you want.

**Comment by stfast** [comment]
OK. I got it working.

There must be the same neighbours{} configuration on both nodes, otherwise other node is offline.

Is it OK, that "Configuration ID" is the same for both nodes.

**Comment by moisseev** [comment]
> Is it OK, that "Configuration ID" is the same for both nodes.

Yes. That means configurations of the nodes are identical. "Configuration ID" is the hash of the configuration.
