### ISSUE TITLE
FROM_NEQ_DISPLAY_NAME false positive

### ISSUE THREAD

**Issue by jendis** [rspamd/rspamd#3285]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Rule FROM_NEQ_DISPLAY_NAME creates false positive since it improperly extracts domain from display name in _From_ header field and has relatively high score (4).

### Steps to Reproduce
Take whatever sample and replace the _From_ header filed by
`From: fooo@foo.fo- private <fooo@foo.fo>`

then shown in rspamc results:
`Symbol: FROM_NEQ_DISPLAY_NAME (4.00)[foo.fo, foo.fo- private]`

**Expected behavior**
Correct detection of domain in display name and lower score e.g. 1.

### Versions

You can get this information from copy and pasting the output of `rspamd --version` from the command line. Also, please include the **OS** and what version and architecture including the generation of CPU model (e.g. Haswell) where applicable,  of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by href** [comment]
We have the same issue. While the check in itself makes sense, it is easily fooled. For example, if someone sends an e-mail from `Backoffice @Company <backoffice@example.com>`.

Can this bug be reopened?

**Comment by lefterists** [comment]
I have the exact same issue and has been like this for years now. Can someone reopen this bug please?
