### ISSUE TITLE
[BUG] force actions plugin is not working

### ISSUE THREAD

**Issue by fkrauthan** [rspamd/rspamd#3299]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
The action defined in the force actions module is not getting applied (`add header` in my case) and instead the email gets rejected. This is very bad as in my specific case I want to receive all emails forwarded from a secondary email account in my primary mail account and worst case have them flagged as spam.

### Steps to Reproduce

1. Configure a custom symbol: In my case I have a Lua plugin that adds the symbol `GMX_FORWARD` in some cases
2. Configure a force action (see below for sample)
3. Have an email send to rspamd that usual would be rejected

**Expected behavior**
The force action should prevent an email rejection and instead changes the action to `add header` which in the past worked but with the latest `2.4` version update it stopped working.

**Sample Force Actions Config**

```
rules {
    GMX_FORWARD {
        action = "add header";
        expression = "GMX_FORWARD";

        require_action = ["reject", "discard"];
    }
}
```

### Versions

` rspamd --version` output: `Rspamd daemon version 2.4`

`lsb_release -a` output:

```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

### Additional Information

The force action seem to be getting executed correctly (as it adds the expected Symbol) but the enforced action is not triggered.

Sample of Force Action symbol added: `FORCE_ACTION_GMX_FORWARD (0) [add header]`

**Comment by andryyy** [comment]
Can confirm, but have not yet completed my test case. :(

**Comment by thmo** [comment]
Exakt the same issue here: According to the logs, the `force_action` rule is applied (`"add header"` instead of `["reject", "soft reject"]`), but the mail in question is rejected nevertheless, if the score is >15.

With rspam < 2.4, things worked as expected.

Updating to the experimental 2.5 version doesn't help.

**Comment by fkrauthan** [comment]
I can confirm that the work around with setting the action to `rewrite subject` works as advertised.

**Comment by thmo** [comment]
The 2.5 release has fixed this for me.
