### ISSUE TITLE
GTube test spam question

### ISSUE THREAD

**Issue by grharry** [rspamd/rspamd#3303]
I am trying to enable incoming of the test GTUBE spam string but rspamd always returns a reject to postfix and postfix to remote! 

How is it possible to enable it ? 

Rspamd version = 2.4
my overide.d/metrics.conf 
#override.d/metrics.conf            
actions {            
        reject =null;  
        add_header = 6;
        greylist = 4;
}
Thanks
Regards
Harry

--------------^ Click "Preview" for a nicer view!
We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks!

---

* Mailing list: https://lists.rspamd.com/mailman/listinfo (you can subscribe on that page or browse the archives)
* Telegram channel: http://t.me/rspamd
* Also have a look at the following page for more information on how to get support:
  https://rspamd.com/support.html

**Comment by vstakhov** [comment]
Gtube is always rejected, disregarding **anything**. Won't fix.

**Comment by grharry** [comment]
ok 
Благодарность
