### ISSUE TITLE
[BUG] IP reputation score is greather than its weight

### ISSUE THREAD

**Issue by heraklit256** [rspamd/rspamd#3304]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds [not possible on the productive system I observed this]
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
This issue is possibly related to https://github.com/rspamd/rspamd/issues/477: The `reputation` module is configured for IP reputation tracking [as shown in the module documentation](https://rspamd.com/doc/modules/reputation.html). In order to have meaningful scores, the weights of `IP_REPUTATION_HAM` and `IP_REPUTATION_SPAM` are defined in `local.d/groups.conf` with `1.0` each.

However, the reputation modules' score seems to exceed `1.0` in some messages (`abs(-1.11)` > `1.0`):
```
X-Spamd-Result: default: False [-4.32 / 11.00];
	 ARC_NA(0.00)[];
	 R_DKIM_ALLOW(-0.20)[x];
	 FROM_HAS_DN(0.00)[];
	 DWL_DNSWL_MED(-2.00)[x:dkim];
	 R_SPF_ALLOW(-0.20)[+ip6:x];
	 TO_MATCH_ENVRCPT_ALL(0.00)[];
	 MIME_GOOD(-0.10)[multipart/mixed,text/plain];
	 HAS_ATTACHMENT(0.00)[];
	 PREVIOUSLY_DELIVERED(0.00)[x];
	 RCVD_DKIM_ARC_DNSWL_MED(-0.50)[];
	 RCPT_COUNT_ONE(0.00)[1];
	 TO_DN_NONE(0.00)[];
	 IP_REPUTATION_HAM(-1.11)[asn: x(-0.31), country: DE(-0.00), ip: x(-0.79)];
	 DKIM_TRACE(0.00)[x:+];
	 DMARC_POLICY_ALLOW(-0.50)[x,none];
	 ARC_SIGNED(0.00)[i=1];
	 RCVD_IN_DNSWL_MED(-0.20)[x:from];
	 MID_RHS_NOT_FQDN(0.50)[];
	 MX_GOOD(-0.01)[];
	 FROM_EQ_ENVFROM(0.00)[];
	 MIME_TRACE(0.00)[0:+,1:+,2:~];
	 RCVD_TLS_LAST(0.00)[];
	 ASN(0.00)[asn:x, ipnet:2001:x::/48, country:DE];
	 TAGGED_FROM(0.00)[no-reply];
	 RCVD_COUNT_TWO(0.00)[2]
```

### Steps to Reproduce

Content of `local.d/reputation.conf` is as follows:
```
rules {
  ip_reputation = {
    selector "ip" {
    }
    backend "redis" {
      servers = "localhost";
    }    
    symbol = "IP_REPUTATION";
  }
}
```

Content of `local.d/groups.conf` is as follows (off-topic remark: `IP_REPUTATION_HAM` weight must not be negative, which was surprising to me):
```
group "reputation" {
    symbols = {
        "IP_REPUTATION" {
            weight = 0.0;
            description = "generic symbol for IP reputation module";
        }
        "IP_REPUTATION_SPAM" {
            weight = 1.0;
            description = "IP reputation module spam";
        }    
        "IP_REPUTATION_HAM" {
            weight = 1.0;
            description = "IP reputation module ham";
        }
    }
}
```
Depending on the collected data, this behaviour can be reproduced by processing a message from a sender with a very good or very bad reputation.

**Expected behavior**
I would expect the IP reputation module result to be lower than or equal to the defined weight.

### Versions

Output of `rspamd --version`:
```
Rspamd daemon version 2.4
```

Output of `cat /etc/os-release`:
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Additional Information

Thank you in advance for looking at this.

**Comment by heraklit256** [comment]
Quick footnote: This behaviour is still present using rspamd 2.5 on Debian Buster.

**Comment by heraklit256** [comment]
To my knowledge, this issue is still valid.

**Comment by tjharman** [comment]
Isn't it a multiplier?

So your score in your example (added together) is 1.10.  1 x 1.10 = 1.1

I suspect actually there's some rounding going on, thus why you see 1.11.

If you set your weight to 2, you'd see a weight of 2.22 for your posted message.

At least that's MY understanding of how it works?

**Comment by sleeplessnight2** [comment]
I can imagine, but there is no info about it.

But interesting that it can also totally freak out. I currently have URL Reputation assigned a weight of 2, but the last mail it was rated 7.8 (!!)

This forces me to turn off the module. There seems to be an upward limit missing here in general.

I hope either an explanation or a fix is given here.
