### ISSUE TITLE
[Feature] Support clamscan

### ISSUE THREAD

**Issue by plinss** [rspamd/rspamd#3305]
## Summary

Add support for using clamscan instead of clamd.

## Motivation

I have mail servers that process a very low volume of email and would like to reduce resource needs. Keeping a running clamd consumes up to 1GB of RAM. Being able to configure Rspamd to use clamscan would reduce the necessary RAM usage significantly.

I appreciate that clamscan uses the same amount of RAM and is significantly slower due to startup costs, but the RAM usage is intermittent and the mail volume is low enough that having clamscan cause swap usage is a better tradeoff in some circumstances.

## Describe alternatives you've considered

There doesn't appear to be a way to configure Rspamd to use clamscan at the moment.

An alternative would be to move clamd to another server, but the lack of TLS support for the connection to it means potentially exposing email which is unacceptable for me.

**Comment by vstakhov** [comment]
Again, despite there is a support of spawning processes I don't like this approach. So I'll mark this issue as 'wontfix' as apparently I will not going to implement that.
