### ISSUE TITLE
[Feature] Support TLS for clamav

### ISSUE THREAD

**Issue by plinss** [rspamd/rspamd#3306]
## Summary

Keeping a running clamd instance consumes a significant amount of RAM. Being able to shift clamd to a another server would allow using Rpsamd with clamd on servers with a small amount of RAM. However, the lack of TLS support for clamd means exposing email to potential eavesdropping.

An additional bonus feature would be supporting client-side certificates for the TLS connection allowing access control on the clamd server.
 
## Motivation

I have mail servers that I'd like to host on low RAM VMs, currently running clamd requires 1GB of RAM. Being able to shift clamd to a single server and share it would reduce RAM needs significantly.

## Describe alternatives you've considered

Alternatively switching to clamscan or connecting to clamd over an insecure connection.

## Additional context

See #3305

**Comment by vstakhov** [comment]
stunnel has this functionality, there is no reason to implement tls functionality in Rspamd. However, Rspamd `tcp` library has TLS support so it shouldn't be hard to add native support. It just looks useless to me.

**Comment by plinss** [comment]
Setting up a mail server already involves a large number of services, adding yet one more just makes the whole stack more fragile. If you already have the ability to make TLS connections then avoiding another external dependency would be useful and appreciated.

**Comment by plinss** [comment]
Friendly ping to keep stale-bot from closing the issue
