### ISSUE TITLE
[BUG] Web interface does not update / reset

### ISSUE THREAD

**Issue by vasyugan** [rspamd/rspamd#3312]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
 [...]
**Describe the bug**
Until a few days ago, the web interface worked fine for me. A couple of days ago, I noticed that it stopped adding new items to the history list. My first suspicion fell on the history module, but it seems to be innocent...

Even when I log off and log on or reload bypassing the browser cache, the situation remains unchanged. The only remedy is to either use a private browser window, later close it, open a new one etc or to remove the site from the browser history.

Tested with several different browsers across several different machines. It doesn't seem to be a browser specific issue.

### Steps to Reproduce

1. Log on to the rspamd web interface
2. Watch for the newest item
3. Wait some time, until new mails arrive
4. Note the newest item in the list
5. Fully reload the page, bypassing the browser cache
6. Note the latest item..
7. Click on "reset list"
8. Examine the list...

Result: In all cases, the list remains unchanged. It is neither reset nor updated.

**Expected behavior**
Page should update 

### Versions

Rspamd version 2.4

Ubuntu Bionic 
CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz

### Additional Information

Configuration changes I did in the last few days included enabling the neural and reputation plugins. 

I notice that /var/lib/rspamd/rspamd.history has been last modified on 15 March, it seems rspamd has switched to using redis since.

**Comment by moisseev** [comment]
I think you have two unrelated issues.
The first one is a bug in the controller: https://github.com/rspamd/rspamd/issues/2910

**Comment by vasyugan** [comment]
Just found out, it was my mistake. I by accident added "expires max" to one of the nginx config files. Sorry for bothering you needlessly...
