### ISSUE TITLE
[Feature] Displaying matching regex pattern in exported symbols (multimap)

### ISSUE THREAD

**Issue by sriccio** [rspamd/rspamd#3314]
## Summary

Hi,
It would be really nice (at least for us) to have an option, in multimap, like for example "showpattern = true" that exports the matching regex pattern that triggered a symbol.

Let's say I have this multimap configuration:

```
BAD_SUBJECT {
  symbols_set = ["BAD_SUBJECT"];
  type = "header";  
  header = "subject";
  prefilter = true;
  map = "${LOCAL_CONFDIR}/custom/bad_subjects.map";
  regexp = true;
  score = 100;
  description = "Subject contains known spam subject pattern";
  message = "Sorry, your mail has been rejected. Please contact SwissCenter support for more informations. [BLSUBJ]";
  action = "reject";
}
```

When something matches, the symbol output is:

```
BAD_SUBJECT (0) [Copy of: Hallo, ich wünsche dir einen schönen Tag.]
```

The pattern that matched in our .map file is:
```
/Hallo\, ich wünsche dir/ui
```

It would be very useful to see the symbol like:

```
BAD_SUBJECT (0) [/Hallo\, ich wünsche dir/ui]
```
or
```
BAD_SUBJECT (0) [Copy of: Hallo, ich wünsche dir einen schönen Tag. (/Hallo\, ich wünsche dir/ui)]
```
Well, to include somewhere the matching regex pattern.

## Motivation

When you start having a lot of regex pattern in the map file, especially some complicated ones. You can easily mess something and have false positives.
Having the information about which pattern matched greatly helps to quickly find which one is guilty.

## Describe alternatives you've considered

Not that much

## Additional context

Thanks a lot for your very good work on this project!

**Comment by silverasu** [comment]
As multimap type = "content" does not log anything at all, it is impossible to identify what rule matched from big map.
So we have similar request, for logging matched regex pattern from map.

**Comment by Flow86** [comment]
I'm interested in how to diplay this information too, is there a way to handle this? (I know its a stale issue, but perhaps there is a solution for this?)

**Comment by fatalbanana** [comment]
> I'm interested in how to diplay this information too, is there a way to handle this? (I know its a stale issue, but perhaps there is a solution for this?)

https://github.com/rspamd/rspamd/discussions/4631
