### ISSUE TITLE
[Feature] contrib/replxx/src/ConvertUTF.{h,cpp} are non-free

### ISSUE THREAD

**Issue by sbadia** [rspamd/rspamd#3317]
## Summary

This issue is more a "info" about non-free license in ConvertUTF.{h,cpp} contrib files.
Upstream issue live here https://github.com/AmokHuginnsson/replxx/issues/12 but isn't active.

## Motivation

Replxx includes non-free code from Unicode Inc (ConvertUTF.{cpp,h}), those license problem was detected by lintian tool, in https://bugs.debian.org/823100

taglib migrated away from ConvertUTF.{cpp,h} using https://github.com/nemtrif/utfcpp

## Additional context

* https://github.com/AmokHuginnsson/replxx/issues/12
* https://github.com/taglib/taglib/issues/793 (migration to UTF8-CPP library)
* https://bugs.debian.org/823100

**Comment by vstakhov** [comment]
Conversion to libicu looks the most appropriate solution here.

**Comment by sbadia** [comment]
Fixed by @vstakhov in commit https://github.com/rspamd/rspamd/commit/0a822b38c6c7177633c81d373946c7ba12639ec7

Thanks !!
