### ISSUE TITLE
[BUG] Elasticsearch exporter bulk operation fails

### ISSUE THREAD

**Issue by HRvojeIT** [rspamd/rspamd#3324]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Using rspamd 2.5 and elastic 7.6.2 with a fresh install the elastic.lua bulk insert fails with a "strange error":
java.lang.IllegalArgumentException: mapper [rspamd_meta.geoip.location] of different type, current_type [geo_point], merged_type [ObjectMapper].

### Steps to Reproduce

1. Install rspamd
2. Install elastic
3. Configure rspamd
4. See index and pipeline created in elastic but not documents in index
5. See elasticsearch log for the mapper error.

**Expected behavior**
I expected to see data into elastic.

### Versions

Debian buster
Rspamd 2.5
elastic 7.6.2

### Additional Information

After a lot of debug I found that the error reported is not correct or is a sub-problem of the fact that the elastic.lua in the bulk request is sending a deprecated parameter (_type). Maybe is it possibile to check is the elastic is version > 6 (using ingest_module param or adding one?) to change the bulk request? If I use this all is ok.
Maybe I can add a pull request?

Line 74:
from
        '", "_type" : "logs" ,"pipeline": "rspamd-geoip"} }')
to
        '","pipeline": "rspamd-geoip"} }')

Not sure but this can be modified even in the kibana part.

**Comment by sriccio** [comment]
Hi,
I had the same problem with our elasticsearch 7.6.1 stack and after some debugging it was caused by the `_type` parameter using in bulk send.

I was about to submit a PR but I wanted first to check that everything else is working
We also had trouble with the automatic import of the kibana template , that I finally added manually.

This is related to the followwing module settings:
`kibana_file = "${PLUGINSDIR}/elastic/kibana.json";`
`import_kibana = false`;

I wanted to try it again from scratch with our changes to the module, on another cluster, to avoid breaking the working one :)

**Comment by HRvojeIT** [comment]
Yeah, kibana has the same problem. I chandeg just two lines (removing the _type parameter) and it works like a charm. The problem is to support earlier versions of elastic (5/6) so my too simple change (or yours) has to be discussed!

**Comment by sriccio** [comment]
@HRvojeIT, yes I agree. It should at least support the previous major version, as I don't think people would upgrade their stack to "only" add rspamd data to their existing cluster.

However maybe it is possible to push the data to a logstash instance which would do some rewrites before flushing to ES.

**Comment by sriccio** [comment]
From what I understand here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#_schedule_for_removal_of_mapping_types

With the type removed it should be compatible at least from 6.x to 8.x. Do you understand the same ?

**Comment by HRvojeIT** [comment]
I understand:
- from 5.6 you can avoid its use
- from 6 you can use it but the index ca hane only one type
- from 7 is deprecated
- from 8 is removed
So I understand tha same.
But, if I'm the first person after one year of elastic 7 that has this problem (with you we are two!) I think that there are many configurations with old engines. Maybe we could add one configuration parameter to tell if the version is < 7 or not! And, I would appreciate to add some debug inforations (eg: print body of request if debug is enabled)!

**Comment by gauthierc** [comment]
I had the same problem that I fixed locally.
You have to replace the "logs" type by "_doc" in the elastic.lua file.
I'm going to propose a pull request. I didn't do it, because I don't know the side effects it can have on previous versions of elasticsearch.
