### ISSUE TITLE
[Feature] SMTP AUTH for DMARC reports

### ISSUE THREAD

**Issue by azurit** [rspamd/rspamd#3334]
## Summary

Allow setting SMTP AUTH login and password when sending DMARC reports.

## Motivation

In our (not uncommon, i believe) setup, every SMTP connection must be authenticated, even from localhost.

## Describe alternatives you've considered

Allowing unauthenticated connections from localhost. We had it like this before but we decided to change it for various reasons.

## Additional context

None.

**Comment by vstakhov** [comment]
I would suggest you to fix your setup instead. The main assumption is that local mta should be able to send mail without auth.

**Comment by Flow86** [comment]
`I would suggest you to fix your setup instead. The main assumption is that local mta should be able to send mail without auth.`
thats a wrong assumption: The rspamd instance sending the report must not be locally connected to your mta.
I also for example have mailserver + rspamd on different (docker) containers
