### ISSUE TITLE
[Feature] allow variables in force_action return messages

### ISSUE THREAD

**Issue by rm-minus-rf** [rspamd/rspamd#3335]
## Summary
Allow variables in the smtp return message in force_action rules.

## Motivation
We want to allow variables in the return messages to give the peer more and more precise information. Examples for such information can be: queue-id or the filenames of blocked attachments.
We had positive experience with including these kind of information in the smtp return messages:
1) the probability that the peer admin/user will understand the situation and no case at the service-desk is opened increases.
2) If a case is opened most of the time the smtp return message is preserved and the 1st level can handle it based on the included information.
3) in all levels the included queue-id (named support-id in our case) helps a lot tracking the mail in logs.

## Describe alternatives you've considered
No alternatives found.

## Additional context
Our idea was to allow 3 prefixes in the variables:
- 'selector::\<selector-expression\>' => fill with value extracted by a selector
 (selectors are powerful and allow for a lot of different information)
- 'symbol::\<symbol-name\>'   => fill with matching symbol option string(s)
 (we wrote a custom lua plugin to filter attachments which adds unwanted files as symbol option string)
- 'task::\<task-attribute\>'     => fill with matching task attribute (ONLY 'queue_id' and 'uid' ALLOWED!)
 (this prefix is needed for queue_id and uid which cannot be extracted by a selector) 

Let´s look at an example:
```
  DAAS_REJECT_MIME_BLACK {
    expression = "DAAS_MIMEDIVER_BLACKLISTED & !(DAAS_MIME_BLACK_OK)";
    action = "reject";
    honor_action = ["reject"];
    message = "(support-id: ${task::queue_id}) Your mail was rejected because it contains BANNED ATTACHMENTS: ${symbol::DAAS_MIMEDIVER_BLACKLISTED}. Please check https://www.example.com/${selector::languages.first}/allowed-attachments.html for further details!"
  }
```
Will expand to: `5.7.1 (support-id: 491cJ173kpzyT9) Your mail was rejected because it contains BANNED ATTACHMENTS: MExplorer.exe. Please check https://www.example.com/en/allowed-attachments.html for further details!`

Here is a patch that should allow the mentioned prefixes/variables:
```
--- /root/work/force_actions.lua.org	2020-04-09 10:53:01.639165761 +0200
+++ /usr/share/rspamd/plugins/force_actions.lua	2020-04-09 15:45:56.128199622 +0200
@@ -29,6 +29,7 @@
 local rspamd_cryptobox_hash = require "rspamd_cryptobox_hash"
 local rspamd_expression = require "rspamd_expression"
 local rspamd_logger = require "rspamd_logger"
+local lua_selectors = require "lua_selectors"
 
 local function gen_cb(expr, act, pool, message, subject, raction, honor, limit, least)
 
@@ -63,6 +64,66 @@
 
   return function(task)
 
+    local function fill_vars(repl, var_class, var_payload)
+      -- fill template vars prefixed with 
+      --  'selector::' => fill with value extracted by a selector
+      --  'symbol::'   => fill with matching symbol option string(s)
+      --  'task::'     => fill with matching task attribute
+      --                   (only queue_id and uid allowed)
+
+      if var_class == "selector" then
+        local selector = lua_selectors.create_selector_closure(rspamd_config, var_payload, '', true)
+        if not selector then 
+          rspamd_logger.errx(rspamd_config, 'could not create selector [%1]', var_payload)
+          return "((could not create selector))"
+        end
+        local extracted = selector(task)
+        if extracted then
+          -- replace non ascii chars
+          if type(extracted) == 'table' then
+            extracted = table.concat(extracted, ',')
+          end
+          extracted = string.gsub(extracted, '[\128-\255]', '?')
+        else
+          rspamd_logger.errx(rspamd_config, 'could not extract value with selector [%1]', var_payload)
+          extracted = '((error extracting value))'
+        end
+        return extracted
+      end
+
+      if var_class == "symbol" then
+        local symb_opts
+        local symb_strs = {}
+        if task:has_symbol(var_payload) then
+          local symb_tbl = task:get_symbol(var_payload)
+          for _,symb in ipairs(symb_tbl) do
+            local symb_opts = symb.options
+            if symb_opts then
+              -- replace non ascii chars
+              symb_strs[#symb_strs+1] = string.gsub(table.concat(symb_opts, ','), '[\128-\255]', '?')
+            end
+          end
+          symb_str = table.concat(symb_strs, ',')
+        else
+          symb_str = '((symbol not found))'
+        end
+        return symb_str
+      end
+
+      -- would it make sense to export task:get_queue_id and task:get_uid as selector data definition?
+      if var_class == "task" then
+        local attr_val = '((unknown task attribute))'
+        if var_payload == 'queue_id' then
+          attr_val = task:get_queue_id()
+        elseif var_payload == 'uid' then
+          attr_val = task:get_uid()
+        end
+        return attr_val
+      end
+
+    end 
+
+
     local cact = task:get_metric_action('default')
     if cact == act then
       return false
@@ -83,6 +144,8 @@
       if least then flags = "least" end
 
       if type(message) == 'string' then
+        -- fill vars in return message
+        message = string.gsub(message, '(${(.-)::(.-)})', fill_vars)
         task:set_pre_result(act, message, N, nil, nil, flags)
 
       else

```
I was unsure wether to post this patch here or as a pull request.
But because i do not feel 'mature' enough in the rspamd code especially with the selector stuff i decided to put it here. 

@leofeyer could be also interested in this because #2830 was similiar.
Maybe he would be willing to test the patch in his environment too?

**Comment by vstakhov** [comment]
Hello, I would suggest you to open PR. The idea looks good to me and I want to be able to do review or allow others to test the branch with this feature.

**Comment by rm-minus-rf** [comment]
Hello,

i just opened PR #3336. 
(First pull request for me. I hope i created as it should be...)

**Comment by rm-minus-rf** [comment]
Hello @vstakhov ,

sorry to bother you here again, but i have newer used github before and therefore this is my first pull request.

I tried to incorporate your suggested changes from the pull request and did another commit to my fork. The changes appear in the pull request. Is there anything else i have to do? Start another Review? Close something? 
Tried to do some RTFM on the github workflow regarding pull requests. Only thing i could find was: commit again to your fork.

**Comment by rm-minus-rf** [comment]
Just for documentation.
The merged version of the patch would change the example rule to:
```
  DAAS_REJECT_MIME_BLACK {
    expression = "DAAS_MIMEDIVER_BLACKLISTED & !(DAAS_MIME_BLACK_OK)";
    action = "reject";
    honor_action = ["reject"];
    message = "(support-id: ${queueid}) Your mail was rejected because it contains BANNED ATTACHMENTS: ${symbol('DAAS_MIMEDIVER_BLACKLISTED'):options.to_ascii}. Please check https://www.example.com/${languages.first}/allowed-attachments.html for further details!"
  }
```

**Comment by vstakhov** [comment]
I would really appreciate if you can update the module documentation! Thank you for your work.

**Comment by rm-minus-rf** [comment]
I have already forked rspamd.com and will do a companion pull request.
The selectors description page lists the version in which the transform/data extrection was introduced. 
Can i list "2.5+" for the additions?

**Comment by vstakhov** [comment]
I think that should be 2.6+.

**Comment by rm-minus-rf** [comment]
Pull request for rspamd.com (# 459) is created.
And yes, it should have been 2.6+.

I changed my example rule to only use a symbol that was already used in the documentation (MIME_BAD), to keep it consistent.
