### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wrosenauer** [rspamd/rspamd#3337]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Apparently DMARC reports are sent to the wrong reporting address in addition to the correct one.
I got feedback from wrong recipients and one logging sample looks like this:

```
Apr 15 10:09:32 saruman rspamd[24063]: 2020-04-15 10:09:32 #24071(controller) <>; lua; dmarc.lua:1001: sending report for de-news.adidas.com <{[dmarc_rua@emaildefense.proofpoint.com] = true, [e2a4c-8143@rua.dmarc.emailanalyst.com] = true, [e
bay@rua.agari.com] = true, [csvpzcx5@ag.dmarcian.eu] = true, [dmarc_agg@auth.returnpath.net] = true}> (<{}> bcc)

```
The DMARC record is:
`_dmarc.adidas.com.	300	IN	TXT	"v=DMARC1; p=none; sp=reject; rua=mailto:dmarc_rua@emaildefense.proofpoint.com; ruf=mailto:dmarc_ruf@emaildefense.proofpoint.com;fo=1"`

I cannot explain where rspamd gets the other three addresses from.

### Steps to Reproduce

1. enable DMARC reporting
2. receive mails from senders with DMARC policy

**Expected behavior**
Reports should be sent to the defined rua and ruf reporting addresses specififed within the DMARC DNS entry.

### Versions

Rspamd daemon version 2.5
running on openSUSE Leap 15.1

**Comment by vstakhov** [comment]
DNS records can be changed. What you see now is not what it was 300 seconds ago.

**Comment by wrosenauer** [comment]
That is true. The postmaster behind csvpzcx5@ag.dmarcian.eu contacted me that they never have been responsible for that reports for that domain though.

**Comment by wrosenauer** [comment]
Enabled debug logging now to catch it next time
