### ISSUE TITLE
[BUG] Building with moonjit fails

### ISSUE THREAD

**Issue by darix** [rspamd/rspamd#3338]
Fixing the cmake finder was kinda easy.

```moonjit-headers.patch 
Index: rspamd-2.5/cmake/FindLua.cmake
===================================================================
--- rspamd-2.5.orig/cmake/FindLua.cmake
+++ rspamd-2.5/cmake/FindLua.cmake
@@ -16,6 +16,7 @@ MACRO(FindLua)
                 "${RSPAMD_SEARCH_PATH}" "${LUA_ROOT}"
                 $ENV{LUA_DIR}
                 PATH_SUFFIXES "include/luajit-2.0"
+                "include/moonjit-2.2"
                 "include/luajit-2.1"
                 "include/luajit${LUA_VERSION_MAJOR}${LUA_VERSION_MINOR}"
                 "include/luajit${LUA_VERSION_MAJOR}.${LUA_VERSION_MINOR}"
```

moonjit would also support a pkgconfig based finder:

```
pkg-config --libs --cflags luajit 
-I/usr/include/moonjit-2.2 -lluajit-5.1 
```

but building still fails with:

```
In file included from /home/abuild/rpmbuild/BUILD/rspamd-2.5/contrib/lua-lpeg/lptree.c:9:
/home/abuild/rpmbuild/BUILD/rspamd-2.5/src/lua/lua_common.h:44:19: error: static declaration of 'lua_absindex' follows non-static declaration
   44 | static inline int lua_absindex (lua_State *L, int i) {
      |                   ^~~~~~~~~~~~
In file included from /home/abuild/rpmbuild/BUILD/rspamd-2.5/src/lua/lua_common.h:6,
                 from /home/abuild/rpmbuild/BUILD/rspamd-2.5/contrib/lua-lpeg/lptree.c:9:
/usr/include/moonjit-2.2/lua.h:363:13: note: previous declaration of 'lua_absindex' was here
  363 | LUA_API int lua_absindex (lua_State *L, int idx);
      |             ^~~~~~~~~~~~
make[2]: *** [contrib/lua-lpeg/CMakeFiles/rspamd-lpeg.dir/build.make:122: contrib/lua-lpeg/CMakeFiles/rspamd-lpeg.dir/lptree.c.o] Error 1
```

### Steps to Reproduce

building openSUSE Tumbleweed with moonjit instead of luajit. But I guess this can happen on other distros too because I was told more and more switch to moonjit.

### Versions

OS: openSUSE Tumbleweed
moonjit 2.2.0

**Comment by frispete** [comment]
Hi @darix, I was able to workaround this issue with a simple [patch](https://build.opensuse.org/package/view_file/home:frispete:mail/rspamd/rspamd-moonjit.patch?expand=1). Not sure, if this is good enough for a SR, since it relies on moonjit for the Leaps now, but it's definitely good enough for me.

Guys, in order to properly support moonjit, this declaration should be omitted, but I have no idea on how to check for LUAJIT_VERSION_NUM without importing luajit.h, but that would compromise plain LUA support, if I'm not mistaken...

**Comment by darix** [comment]
Does everything work with your patch? then IMHO sure just do the SR

**Comment by darix** [comment]
Any thought about this bug?

**Comment by frispete** [comment]
I don't understand, how a project can rely on a script language, if they cannot deal even with the simplest issues? Nobody with a little Lua-fu out there want/is able to deal with this issue?

**Comment by vstakhov** [comment]
I don't care about all forks of LuaJIT apart of the Mike Pall's one. You can consider this as an official position. Closing issue.
