### ISSUE TITLE
[Feature] Rspamd official packages & repo for Ubuntu 20.04 LTS   

### ISSUE THREAD

**Issue by tomassrnka** [rspamd/rspamd#3348]
## Summary

Please consider adding rspamd official packages & repo for Ubuntu 20.04 LTS  

## Motivation

I would love to use official rspamd packages on Ubuntu 20.04 LTS as Ubuntu 20.04 has been released stable on Apr 23. 

## Describe alternatives you've considered

I considered using official Ubuntu's packages, but rspamd doc is pretty clear :-) "Rspamd is also available in some versions of Debian and Ubuntu. Please DO NOT use those packages, as they are not supported in any way."

## Additional context

.

**Comment by Disassembler0** [comment]
For the impatient, this is how you can compile it on your own:

```bash
# Install build dependencies
apt-get install --no-install-recommends git devscripts build-essential cmake debhelper libcurl4-openssl-dev libglib2.0-dev libhyperscan-dev libicu-dev libjemalloc-dev libluajit-5.1-dev libmagic-dev libpcre2-dev libsodium-dev libsqlite3-dev libssl-dev libunwind-dev ragel zlib1g-dev

# Clone rspamd git repo
git clone https://github.com/vstakhov/rspamd.git

# Build deb packages
cd rspamd
debuild -i -us -uc -b

# Install rspamd (or transfer the package wherever you need)
dpkg -i ../rspamd_2.5_amd64.deb
```

Alternatively, you can use the released tarball instead of git master as the source. The rest of the process is the same. Note, however, that the compiled version is missing a few /etc/rspamd/*.inc files  (_2tld_, _dmarc_whitelist_, _maillist_, _mid_, _mime_types_, _redirectors_, _spf_dkim_whitelist_, _surbl-whitelist_) which are otherwise distributed in the upstream packages.

(I'm eagerly awaiting the official upstream package for _focal_ too.)

**Comment by wienfuchs** [comment]
> ```shell
> # Install build dependencies
> apt-get install --no-install-recommends git devscripts build-essential cmake debhelper libcurl4-openssl-dev libglib2.0-dev libhyperscan-dev libicu-dev libjemalloc-dev libluajit-5.1-dev libmagic-dev libpcre2-dev libsodium-dev libsqlite3-dev libssl-dev libunwind-dev ragel zlib1g-dev
> ```

one would also need devscripts for use of debuild ;)

**Comment by wienfuchs** [comment]
> You can get these on https://github.com/rspamd/maps/tree/master/rspamd.

can be automated using wget like this:
```
cd /etc/rspamd
for INC in 2tld.inc dmarc_whitelist.inc dmarc_whitelist_new.inc maillist.inc mid.inc mime_types.inc redirectors.inc spf_dkim_whitelist.inc surbl-whitelist.inc
do wget -O $INC https://github.com/rspamd/maps/blob/master/rspamd/$INC
done
```

**Comment by rmappleby** [comment]
Showing my ignorance here, but if I compile my own package as per the instructions from @Disassembler0 and @wienfuchs does that have any implications on switching to the official repository & focal package when it becomes available? I'm thinking not, but confirmation would be reassuring, thanks

**Comment by mconigliaro** [comment]
Looks like Focal packages have been available since July 15, 2020: https://rspamd.com/apt-stable/dists/focal/

**Comment by dmke** [comment]
> They seem broken though

Can't confirm, at least not when using the systemd unit:

```console
# apt show rspamd                                 
Package: rspamd
Version: 2.5-156~bionic
Status: install ok installed
...

# systemctl status rspamd.service 
● rspamd.service - rapid spam filtering system
     Loaded: loaded (/lib/systemd/system/rspamd.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2020-07-16 08:12:25 UTC; 6 days ago
```

**Comment by wienfuchs** [comment]
> They seem broken though:
> ```
> # /etc/init.d/rspamd restart
>  * Restarting rapid spam filtering system rspamd
> /etc/init.d/rspamd: line 39:  5571 Segmentation fault      $RSPAMADM configtest $DAEMON_ARGS > /dev/null
> ```

Having the same issue with the a/m packages, self-built packages are working fine though.

**Comment by gerdesj** [comment]
I've just followed the instructions here: https://rspamd.com/downloads.html on an Ubuntu 20.04.1 fully patched box and it installed fine and started the daemon.  This VM was installed from a "minimal" server 16.04 .iso many moons ago and has been upgraded from LTS to LTS.

However, running rspamadm configtest does generate a seg fault so time to dig out strace and co.  At first sight it looks like rspamd itself is running fine.
