### ISSUE TITLE
[BUG] SPOOF_REPLYTO causes false positives on messages emitted by ticket systems

### ISSUE THREAD

**Issue by heraklit256** [rspamd/rspamd#3350]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Some ticket systems preserve the original `From`-header, add themselves in a `Sender`-header and ensure replies go back to the ticket system rather than the original customer by taking advantage of `Reply-To`. Example:

```
From: John Doe <jdoe@example.com>
Sender: ACME Inc. ticket system <tickets@acme.com>
Reply-To: ACME Inc. ticket system <tickets@acme.com>
```

Since the right hand side of `Reply-To` contains a domain which differs from `From` RHS, the [`SPOOF_REPLYTO`](https://github.com/rspamd/rspamd/blob/25fbf9a11b80c3a7ac2ecffbbd6c35760393c7df/rules/misc.lua#L575-L617) symbol is applied to that message. While I understand and applaud the idea of that symbol, processing the `Sender`-header - if present - rather than the `From`-header seems to make sense to me in order not to cause false positives on indirect mail flows.

### Steps to Reproduce

1. Scan such a message by rspamd.

**Expected behavior**
`SPOOF_REPLYTO` should cause as little false positives as possible, especially as it's weight is rather large. :-)

### Versions
```
user@machine:~> rspamd --version
Rspamd daemon version 2.5
```

### Additional Information

Thanks for having a look at this.

**Comment by heraklit256** [comment]
Sorry for the late reply. IMHO, this bug is still valid.

**Comment by fpoulain** [comment]
It is looking like #1673.

**Comment by sthibaul** [comment]
We have the same issue, rspamd 2.7 here
