### ISSUE TITLE
[BUG] Cannot receive history: {"error": "NOAUTH Authentication required."}

### ISSUE THREAD

**Issue by the-djmaze** [rspamd/rspamd#3353]
**Describe the bug**
/etc/rspamd/local.d/history_redis.conf is not using the global set redis password

### Steps to Reproduce

1. /etc/rspamd/local.d/redis.conf
servers = "127.0.0.1";
password = "mypassword";
2. /etc/rspamd/local.d/history_redis.conf
servers = 127.0.0.1:6379; # Redis server to store history
key_prefix = "rs_history"; # Default key name
nrows = 2000; # Default rows limit
compress = true; # Use zstd compression when storing data in redis
subject_privacy = false; # subject privacy is off
3. http://127.0.0.1:11334/#history

**Expected behavior**
See result in the history area

### Versions
v2.5

### Additional Information
/etc/redis.conf
requirepass mypassword

**Comment by vstakhov** [comment]
Working as intended. If you define any redis parameter inside of the specific block (e.g. in a module config) then you need to define all parameters, including password.
