### ISSUE TITLE
[BUG] Segmentation fault in contrib/lua-lpeg/lpvm.c on ppc64el

### ISSUE THREAD

**Issue by bauruine** [rspamd/rspamd#3365]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

rspamd after commit 92ec3e389a7d4b4f6898fa347c35b9256bfcb792 crashes with a segfault on ppc64el. I've tested it with 4626766ee1cbe74b33f3194d8dda97880e8c5c2e (the commit before) which works.

```
Program received signal SIGSEGV, Segmentation fault.
lpeg_allocate_mem_low (sz=512) at ./contrib/lua-lpeg/lpvm.c:77
```

Full backtrace https://gist.github.com/bauruine/eef476eed82c150e6c9f6ecf796a3a88

### Steps to Reproduce

Build latest version according to https://rspamd.com/downloads.html on ppc64el
run rspamd

#### Expected behavior

rspamd should run.

### Versions

rspamd --version
Rspamd daemon version 2.6

ubuntu 20.04 focal ppc64le running on a POWER9 CPU

### Additional Information

I could provide a ppc64el LXD container if needed.

**Comment by markfqs** [comment]
Hi I'm experiencin the same issue in ARMv7 (32bits):

/ # gdb -q -nh /usr/sbin/rspamd  core
Reading symbols from /usr/sbin/rspamd...
Reading symbols from /usr/lib/debug//usr/sbin/rspamd.debug...
[New LWP 51]

warning: Can't read pathname for load map: No error information.
Core was generated by `/usr/sbin/rspamd -u rspamd -g rspamd -c /etc/rspamd/rspamd.conf -f'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x76e6b658 in lpeg_allocate_mem_low (sz=<optimized out>, sz@entry=4800) at /usr/include/fortify/string.h:53
53	/usr/include/fortify/string.h: No such file or directory.
(gdb) quit

Is possible ARM arch should be took in account on https://github.com/rspamd/rspamd/pull/3366/commits/c8f69801ec7ef53f3b4b2d8114934716f2cdf698 ?
