### ISSUE TITLE
[BUG] DKIM Module does not parse key file path correctly

### ISSUE THREAD

**Issue by dellarte** [rspamd/rspamd#3370]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Dkim signing module does not parse the key file path correctly.
It transforms the '/' charracter to '.' character and then fail with the error cannot load dkim key ...

### Steps to Reproduce

/etc/rspamd/local.d/dkim_signing :
```enabled = true;

try_fallback = false;
selector_map = "/var/lib/rspamd/dkim_selectors.map";
path_map = "/var/lib/rspamd/dkim_paths.map";

#path = "/var/lib/rspamd/dkim/$domain/$selector.key";
#selector = "mx-smtp";
```
/var/lib/rspamd/dkim_paths.map : 
```
[...]
mydomain.com /var/lib/rspamd/dkim/mydomain.com/mx-smtp.key
[...]
```
/var/lib/rspamd/dkim_selectors.map : 
```
[...]
mydomain.com mx-smtp
[...]
```
Generate this error : 
```
May 13 17:59:34 mx1 rspamd[115707]: <2db2dd>; task; dkim_module_load_key_format: cannot load dkim key /var/lib/rspamd/dkim/mydomain.com.mx-smtp.key: cannot stat key file: '/var/lib/rspamd/dkim/mydomain.com.mx-smtp.key'
```

As you can see, it is searching for 
mydomain.com **.** mx-smtp.key

instead of 

mydomain.com **/** mx-smtp.key

This problem is temporary resolved by restarting the rspamd service....

**Expected behavior**
Load dkim key correctly

### Versions

Linux mx1 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
Rspamd daemon version 2.5

**Comment by dellarte** [comment]
Hi, this bug is still present. Can you help me ?

**Comment by mans39** [comment]
Same behaviour here.

**Comment by levitte** [comment]
I suspect that if you uncomment this, things will be fine:

```
#path = "/var/lib/rspamd/dkim/$domain/$selector.key";
```

**Comment by dellarte** [comment]
Indeed, this do the job but i can't explain why uncommenting this resolve the issue since i have a map ........
