### ISSUE TITLE
How to force SPF check in local network 

### ISSUE THREAD

**Issue by user9-9** [rspamd/rspamd#3375]
Hello,

How can I force SPF (and DKIM) check for SMTP server in my local network ? 
I always have this message : 
lua, spf.lua:185 skip SPF checks for local network and authorized users

Thanks

**Comment by moisseev** [comment]
Probably you need to change [local_addrs](https://rspamd.com/doc/tutorials/scanning_outbound.html#scanning-outbound-with-rspamd) to enable all checks for that IP or use [settings](https://rspamd.com/doc/configuration/settings.html) if you need just SPF and DKIM.

**Comment by user9-9** [comment]
Working Thanks !
