### ISSUE TITLE
[BUG] multimap ignores require_symbols

### ISSUE THREAD

**Issue by aletheia7** [rspamd/rspamd#3377]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
multimap module ignores require_symbols. An email was matched by the following multimap rule. The email did not have a DKIM-Signature header:
```
B_DKIM_ENV_FROM_DOMAIN_WL {
        type = "from";
        map = "/etc/rspamd/local.d/b_dkim_env_from_domain_wl.map";
        header = "From";
        filter = "email:domain:tld";
        prefilter = true;
        action = "accept";
        require_symbols = "R_DKIM_ALLOW";
}
```

Perhaps the multimap module is executing before any R_DKIM_ALLOW is defined?

### Steps to Reproduce

1. Setup the above multimap rule.
2. Send an email with the domain listed in b_dkim_env_from_domain_wl.map. The email must not have a DKIM-Signature header.

**Expected behavior**
The rule should not apply when a DKIM-Signature header is absent.

### Versions

Rspamd daemon version 2.5 (from rspamd, not a Debian package)
amd64
Debian Testing.

**Comment by vstakhov** [comment]
> Perhaps the multimap module is executing before any R_DKIM_ALLOW is defined?

Of course it does - you have configured it as a prefilter. Not a bug, closing.

**Comment by aletheia7** [comment]
The Documentation clearly shows I can use require_symbols with prefilter. Nowhere does the Documentation say require_symbols and prefilter are mutually exclusive.

How would I construct a prefilter action of accept that requires a DKIM-Signature header and a successful lookup in a map?

**Comment by vstakhov** [comment]
You cannot, that's it.

**Comment by aletheia7** [comment]
Ok. Thank you.

Can I define a multimap rule with just a prefilter = accept and a require_symbols directive with all the symbols I want? Example:
```
IN_MY_MAP {
        type = "from";
        map = "/etc/rspamd/local.d/b_dkim_env_from_domain_wl.map";
        header = "From";
}
MY_ALLOWED {
        prefilter = true;
        action = "accept";
    require_symbols = "R_DKIM_ALLOW & IN_MY_MAP";
}
```

**Comment by andryyy** [comment]
You probably want `type = "header";`?
Type from does this: "matches envelope from (or header From if envelope from is absent)"

**Comment by vstakhov** [comment]
No, prefilters are always executed before filters. Dependencies work merely between symbols. Just use score or force_actions plugin. Passthrough actions are evil.
