### ISSUE TITLE
[BUG] rspamd fails on OSX High Sierra (macports)

### ISSUE THREAD

**Issue by phifogg** [rspamd/rspamd#3378]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
I have installed rspamd via macports on my OSX High Sierra system. On trying to launch rspamd I get the following error:

Illegal instruction: 4

This seems similar to this issue here https://github.com/rspamd/rspamd/issues/3035, but the lldb output is different (I have manually compiled hyperscan already).

### Steps to Reproduce

1. Install via macports
2. Start rspamd as: /opt/local/bin/rspamd  -u _rspamd -g _rspamd -f -c /opt/local/etc/rspamd/rspamd.conf

**Expected behavior**
Graceful startup of rspamd

### Versions
Rspamd daemon version 2.3
OSX High Sierra (10.13.6)
Mac Mini late 2012 (2.4 GHz Intel Core 2 Duo)

### Additional Information

Based on previous issues I manually compiled hyperscan and these binaries seem to work fine.
LLDB outoput of rspamd failing:
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x000000000024b7b9 librspamd-server.dylib`checkMode(unsigned int, hs_compile_error**) + 105
librspamd-server.dylib`checkMode:
->  0x24b7b9 <+105>: popcntl %eax, %eax
    0x24b7bd <+109>: cmpl   $0x1, %eax
    0x24b7c0 <+112>: jne    0x24b84e                  ; <+254>
    0x24b7c6 <+118>: movl   %edi, %ecx
Target 0: (rspamd) stopped.

Appreciate your help in getting rspamd working on my system.

**Comment by phifogg** [comment]
I have recompiled rspamd from source (macports) and now it starts up just fine. Must be some macport issue.

**Comment by phifogg** [comment]
My bad... i thought it is running but it is not. :/ The error is still here and the same as above.

**Comment by vstakhov** [comment]
Hyperscan will not work without ssse3 instructions set. TBH I have neither time nor desire to support museum style hardware. In theory, it should be possible to build naked Rspamd with no Hyperscan so you should be able to run in on legacy CPU.

**Comment by phifogg** [comment]
not the answer I was hoping for, but understandable. Thanks for responding.
