### ISSUE TITLE
greylist doesn't show any debug information

### ISSUE THREAD

**Issue by satanTime** [rspamd/rspamd#3381]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
I  have in `local.d/logging.inc`: `debug_modules = ["redis","greylist","greylisting"]`, but I don't see any log messages about `greylist`.

### Steps to Reproduce
1. configure `logging.inc` as
```
level = "info";
debug_modules = ["redis","greylist","greylisting"];
type = "syslog";
```

2. configure `mail/etc/rspamd/local.d/greylist.conf`
```
greylist_min_score = 0.1;
timeout = 15min;
key_prefix = "gl_";
max_data_len = 1k
report_time = 15min;
```
3. configure redis
```
servers = "/var/run/redis/redis.sock";
prefix="olovei";
db="0";
```

4. send an email that will get score higher than 0.1

5. check logs, there's no messages about greylist despite there was a single MGET in redis with `gl_` prefix.

**Expected behavior**
Logs should display information about greylist and how it works / doesn't work. In my case all email with any score aren't stopped by greylist.

### Versions

`rspamd --version`
Rspamd daemon version 2.5

**Comment by satanTime** [comment]
When I put in metrics 0 - it started to work, but still no logs.

```
actions {
    reject = 15;
    add_header = 8;
    greylist = 0;
}
```

**Comment by vstakhov** [comment]
Yes, `greylist` lacks debugging logging completely.

**Comment by satanTime** [comment]
Good :)
