### ISSUE TITLE
[BUG] FreeBSD stable/12 - signal SIGBUS error

### ISSUE THREAD

**Issue by ozkankirik** [rspamd/rspamd#3386]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
After updating FreeBSD from stable/12 (from source), both rspamd 2.5 and rspamd 2.4 stops with `SIGBUS` error. lldb backtrace is below. I saw that, llvm-project was update to version10.0.0 4 weeks ago (https://svnweb.freebsd.org/base/stable/12/contrib/llvm-project/libunwind/?view=log). 
Is it possible to fix this error ?

### Steps to Reproduce

1. svnlite checkout svn://svn.freebsd.org/base/stable/12
2. make buildworld ...
3. make kernel ...
4. make installworld
5. pkg install rspamd 
6. service rspamd onestart
throws sigbus error.

**Expected behavior**
Service should start without errors. Before updating FreeBSD stable/12, it was working.

### Versions
Problem tested with 2.5 and 2.4 versions. Both of them are affected.

### Additional Information
```
root@installer:/usr/ports/mail/rspamd/work/.build/src # lldb ./rspamd-2.5
(lldb) target create "./rspamd-2.5"
Current executable set to '/usr/ports/mail/rspamd/work/.build/src/rspamd-2.5' (x86_64).
(lldb) run -u rspamd -g rspamd
Process 4256 launching
Process 4256 launched: '/usr/ports/mail/rspamd/work/.build/src/rspamd-2.5' (x86_64)
Process 4256 stopped
* thread #1, name = 'rspamd-2.5', stop reason = signal SIGBUS: hardware error
    frame #0: 0x0000000801d5662f libgcc_s.so.1`_Unwind_RaiseException(exception_object=0x00000008002608c8) at UnwindLevel1.c:360:31
   357    // Mark that this is a non-forced unwind, so _Unwind_Resume()
   358    // can do the right thing.
   359    exception_object->private_1 = 0;
-> 360    exception_object->private_2 = 0;
   361
   362    // phase 1: the search phase
   363    _Unwind_Reason_Code phase1 = unwind_phase1(&uc, &cursor, exception_object);
(lldb) bt all
* thread #1, name = 'rspamd-2.5', stop reason = signal SIGBUS: hardware error
  * frame #0: 0x0000000801d5662f libgcc_s.so.1`_Unwind_RaiseException(exception_object=0x00000008002608c8) at UnwindLevel1.c:360:31
    frame #1: 0x00000008016676ac libluajit-5.1.so.2`___lldb_unnamed_symbol26$$libluajit-5.1.so.2 + 92
    frame #2: 0x00000008016af7e4 libluajit-5.1.so.2`___lldb_unnamed_symbol524$$libluajit-5.1.so.2 + 52
    frame #3: 0x00000008016943e1 libluajit-5.1.so.2`___lldb_unnamed_symbol415$$libluajit-5.1.so.2 + 10849
    frame #4: 0x00000008016b00db libluajit-5.1.so.2`___lldb_unnamed_symbol535$$libluajit-5.1.so.2 + 811
    frame #5: 0x0000000801663bd7 libluajit-5.1.so.2`___lldb_unnamed_symbol1$$libluajit-5.1.so.2 + 6983
    frame #6: 0x00000008016afd73 libluajit-5.1.so.2`___lldb_unnamed_symbol534$$libluajit-5.1.so.2 + 67
    frame #7: 0x000000080166f569 libluajit-5.1.so.2`___lldb_unnamed_symbol127$$libluajit-5.1.so.2 + 233
    frame #8: 0x0000000801665261 libluajit-5.1.so.2`___lldb_unnamed_symbol1$$libluajit-5.1.so.2 + 12753
    frame #9: 0x0000000801675529 libluajit-5.1.so.2`lua_pcall + 105
    frame #10: 0x00000008003d1443 librspamd-server.so`rspamd_rcl_jinja_handler + 179
    frame #11: 0x000000080056f16f librspamd-server.so`ucl_parser_add_chunk_full + 271
    frame #12: 0x000000080056c81a librspamd-server.so`ucl_include_file_single + 4234
    frame #13: 0x000000080056b70a librspamd-server.so`ucl_include_file + 426
    frame #14: 0x0000000800567215 librspamd-server.so`ucl_include_common + 1717
    frame #15: 0x0000000800570f08 librspamd-server.so`ucl_state_machine + 6776
    frame #16: 0x000000080056f34d librspamd-server.so`ucl_parser_add_chunk_full + 749
    frame #17: 0x000000080056c81a librspamd-server.so`ucl_include_file_single + 4234
    frame #18: 0x000000080056b5c2 librspamd-server.so`ucl_include_file + 98
    frame #19: 0x0000000800567215 librspamd-server.so`ucl_include_common + 1717
    frame #20: 0x0000000800570f08 librspamd-server.so`ucl_state_machine + 6776
    frame #21: 0x000000080056f34d librspamd-server.so`ucl_parser_add_chunk_full + 749
    frame #22: 0x000000080056c81a librspamd-server.so`ucl_include_file_single + 4234
    frame #23: 0x000000080056b5c2 librspamd-server.so`ucl_include_file + 98
    frame #24: 0x0000000800567215 librspamd-server.so`ucl_include_common + 1717
    frame #25: 0x0000000800570f08 librspamd-server.so`ucl_state_machine + 6776
    frame #26: 0x000000080056f34d librspamd-server.so`ucl_parser_add_chunk_full + 749
    frame #27: 0x00000008003d11b8 librspamd-server.so`rspamd_config_parse_ucl + 1256
    frame #28: 0x00000008003d165a librspamd-server.so`rspamd_config_read + 154
    frame #29: 0x000000000021cb3b rspamd-2.5`load_rspamd_config + 91
    frame #30: 0x000000000021c1c2 rspamd-2.5`main + 978
    frame #31: 0x0000000000212960 rspamd-2.5`_start(ap=<unavailable>, cleanup=<unavailable>) at crt1.c:76:7
(lldb)
```

**Comment by fsmeets** [comment]
I ran into the same problem. I build my packages in a 12.1-RELEASE poudriere jail, and run them in stable/12 jails/hosts. To test I setup a stable/12 poudriere jail and used the packages compiled from there, then rspamd works again. So it seems the merge of llvm 10 to stable/12 breaks binary compatibility / ABI / whatever the correct term is in this case.

**Comment by fsmeets** [comment]
The culprit is now actually the rspamd package, but the luajit package that needs to be complied on stable/12

**Comment by ozkankirik** [comment]
Thanky you, problem is gone after recompiling luajit.

**Comment by bsdlme** [comment]
For the records: This also happens on FreeBSD 12.2-RELEASE. Re-compiling luajit fixes the bus error.

**Comment by Crest** [comment]
FreeBSD packages are supposed to be forward compatible within the same major release so packages built on FreeBSD 12.1 should work on 12.2, but this compatibility has it limits for stuff like (JIT) compilers bypassing symbol versioning. The FreeBSD project doesn't have enough resources to maintain up to date precompiled package repos for each minor release and platform.
