### ISSUE TITLE
[BUG] rspamadm vault roll -r example.com does create new keys

### ISSUE THREAD

**Issue by croessner** [rspamd/rspamd#3391]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
If you have create DKIM keys in a vault/consul database and it comes to the first time, where you decide to rollover the keys, the expired keys will be removed but unfortunately the same command creates a new key. Therefor you always have two keys (or more if ed25519, too) per domain.

### Steps to Reproduce

1. rspamadm vault new ... somedomain

2. Wait a month, whatever time period for rollover

3. rspamadm vault roll somedomain
This time a new key is generated and the old keys gets an expire field

4. Wait some days and try to remove _only_ expired keys:

I show this on a existing domain Note the given '-r' flag!:

rspamadm vault roll -r alltagswahnsinn.de
removed expired key for alltagswahnsinn.de (selector rsa-20200512, expire "Fri 15 May 2020 11:10:35 AM CEST"
removed expired key for alltagswahnsinn.de (selector ed25519-20200512, expire "Fri 15 May 2020 11:10:35 AM CEST"
rolled key for: alltagswahnsinn.de, new selector: rsa-20200604
please place the corresponding public key as following:
rsa-20200604._domainkey IN TXT ( "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs8vLW/xfEScnOwafL9xc0Qg75E6Iz
j60BByIUCYs9HKtBk67GE2l1/+tyljrob0xwx04tvaXDWCi2IijNofQXvjP28KP5gpSWKKflSeO8aSdYRsj/qfh7qHi1R5Ajp+pQJ6AKtWtdwEdBJqqvrbW2cvqFW
2WnvOAEcmUooBpvo4LYMvpcLoBCatBaCZdbcuRr4"
        "hg3MGwq19gBuuDBB7F8mIBbTQTJM4T10w7JU10d7nsOZ8TMVVEsPv6wrj09QAWrmnJWTsFjCZ5lcEem5EuQeZs5yjyi9FN0eFphWVWXa5Q3UHTfYm8wH
Fie67TnF2frhUt9J4RLSsM1ZeG9PEDwwIDAQAB" )
rolled key for: alltagswahnsinn.de, new selector: ed25519-20200604
please place the corresponding public key as following:
ed25519-20200604._domainkey IN TXT ( "v=DKIM1; k=ed25519; p=RMH5W9JzBtZ2opnuj745Fck1hIwjaOYtWUllpHqobCw=" )
your old keys will be valid until Fri 05 Jun 2020 01:37:20 PM CEST

As you see, the old keys were removed but the '-r' flag also created new keys. That must not be the case. Else you never can remove expired keys. This flag really should only remove expired keys.

**Expected behavior**
Remove expired keys from a domain and leave the existing keys in place.

### Versions

This happens in Rspamd-2.5 and master-branch.

### Additional Information

none

**Comment by croessner** [comment]
Anything else required to understand/fix the issue?

**Comment by croessner** [comment]
[vault.lua.diff.zip](https://github.com/rspamd/rspamd/files/4947364/vault.lua.diff.zip)

Path against lualib/rspamadm/vault.lua

Can you please review it?

**Comment by vstakhov** [comment]
Could you please send it as a pull request?

**Comment by vstakhov** [comment]
Should be fixed by the proposed PR, thank you @croessner !
