### ISSUE TITLE
R_SUSPICIOUS_URL false detection

### ISSUE THREAD

**Issue by OleSta** [rspamd/rspamd#3399]
How do I prevent R_SUSPICIOUS_URL to trigger for www.clubmatas.dk?

Get this on legal emails:
R_SUSPICIOUS_URL (5) [www.clubmatas.dk]

**Comment by vstakhov** [comment]
It triggers not from the specific domains but from the ways of how these domains are used withing URLs. Hence, I cannot provide you any more details without the context.

**Comment by OleSta** [comment]
Ok.
I don't have this email so for now we cannot do any more.

**Comment by Sanookmakmak** [comment]
I have it with Google Alerts, but interestingly not with every alert.

`R_SUSPICIOUS_URL(5.00)[www.google.at];`

**Comment by neingeist** [comment]
I've had few false positives with rspamd, but the ones I have I could easily correct if I could configure that the score of e.g. `R_SUSPICIOUS_URL(5.00)[shop.maerkischekiste.de]`(*) should be 0. AFACIT I can only change the score of R_SUSPICIOUS_URL but not limited to this specific domain. (Another FP has a URIBL_BLACK for a specific domain, but that one I would need to investigate more thouroughly.)

A way to correct this specific score could be to write a post filter, if I'm not mistaken. Is this correct?

Technically it's not even a FP, those mails just get sorted into a "suspected spam" folder I have, for rspamd scores between 6.0 and 15.0.

(*) from a newsletter I subscribed to.

**Comment by neingeist** [comment]
(In my case, all the FPs also have valid DKIM and valid SPF, so the best way is probably to whitelist the senders (validated through DKIM/SPF) and not fumble with the scores. → https://rspamd.com/doc/modules/whitelist.html)
