### ISSUE TITLE
[BUG] worker-controller ignores password and bind_socket directives

### ISSUE THREAD

**Issue by rootwyrm** [rspamd/rspamd#3404]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
When `worker-controller.inc` is modified in any fashion outside of configwizard, rspamd refuses to acknowledge the binding or password configuration. This results in a completely broken and insecure installation because the WebUI now only binds to localhost AND has lost all password protection.

### Steps to Reproduce

1. Replace `local.d/worker-controller.inc` in whole or part using any method, using rspamadm pw to generate the password hash, and set a `bind_socket` value appropriately.
```
password = "$2$--replace with your hash--";
bind_socket = "*:11334";
```
2. Ensure the `local.d/worker-controller.inc` has correct permissions (root:wheel should also be fine as long as it's 0644 octal):
```
-rw-r--r--  1 rspamd  rspamd  195 Jun 10 19:22 local.d/worker-controller.inc
```
3. Restart rspamd
4. Rspamd will ONLY bind to localhost:11334 and the Web UI will have NO password protection.
```
# netstat -aln | grep 11334
tcp6       0      0 ::1.11334                                     *.*                                           LISTEN
tcp4       0      0 127.0.0.1.11334                               *.*                                           LISTEN
# curl http://localhost:11334
<!DOCTYPE html>
<html lang="en">
... full webpage follows ...
```

**Expected behavior**
Rspamd obviously should bind to all interfaces as configured and should never ignore the password setting. 

### Versions

```
# rspamd --version
Rspamd daemon version 2.5
# uname -a
FreeBSD redacted.host 12.1-RELEASE-p3 FreeBSD 12.1-RELEASE-p3 GENERIC  amd64
# pkg info rspamd
rspamd-2.5_2
Name           : rspamd
Version        : 2.5_2
Installed on   : Wed Jun 10 17:59:39 2020 EDT
Origin         : mail/rspamd
Architecture   : FreeBSD:12:amd64
Prefix         : /usr/local
Categories     : mail
Licenses       : APACHE20
Maintainer     : vsevolod@FreeBSD.org
WWW            : https://rspamd.com/
Comment        : Fast spam filtering system
Options        :
        BLAS           : on
        CGP            : off
        GPERF          : off
        HYPERSCAN      : on
        LUAJIT         : on
```

### Additional Information

Debug logs produced no additional information. Only indication of a problem is the following:
```
2020-06-14 13:17:49 #14168(controller) <nf8irq>; controller; rspamd_controller_password_sane: your normal password is not encrypted, we strongly recommend to replace it with the encrypted one
2020-06-14 13:17:49 #14168(controller) <nf8irq>; controller; rspamd_controller_password_sane: enable password is not set, so you should filter controller availability by using of firewall or `secure
_ip` option
```
This appears to indicate that the file is being read but is being handled entirely incorrectly for some unlogged reason. Turning on debug for the worker-controller module did not produce any additional information.

**Comment by vstakhov** [comment]
Your configuration is broken most likely.

```
> md5 /usr/local/etc/rspamd/worker-controller.inc
MD5 (/usr/local/etc/rspamd/worker-controller.inc) = 3330ad0f8b56f57ea4ebd0e2ac19312b
> md5 /usr/local/etc/rspamd/rspamd.conf
MD5 (/usr/local/etc/rspamd/rspamd.conf) = ce3fdfc607c83609290db939b6d0e0e5
```

What checksums do you have? Do you have any overrides:

```
    .include(try=true; priority=10) "$LOCAL_CONFDIR/override.d/worker-controller.inc"
```

Or even other legacy configs:

```
.include(try=true) "$LOCAL_CONFDIR/rspamd.conf.local"
.include(try=true,priority=10) "$LOCAL_CONFDIR/rspamd.conf.local.override"
.include(try=true,priority=10) "$LOCAL_CONFDIR/rspamd.conf.override"
```

**Comment by rootwyrm** [comment]
Sorry, got dragged into other things and didn't have time to get back to it. It absolutely is not a broken configuration and exhibits any time the `local.d/worker-controller.inc` file is replaced wholesale. 

```
# md5 /usr/local/etc/rspamd/worker-controller.inc
MD5 (/usr/local/etc/rspamd/worker-controller.inc) = 3330ad0f8b56f57ea4ebd0e2ac19312b
# md5 /usr/local/etc/rspamd/rspamd.conf
MD5 (/usr/local/etc/rspamd/rspamd.conf) = ce3fdfc607c83609290db939b6d0e0e5
```

I thought it was due to the passwd possibly being broken (that `rspamadm pw` doesn't accept piped input is a whole other thing) but it persists even when the password is removed from the configuration.

**Comment by rootwyrm** [comment]
@vstakhov where are things at on this? It is clearly a bug.

**Comment by andryyy** [comment]
Can't replicate it. Password and binding changes work fine. :/

**Comment by rootwyrm** [comment]
That, is very odd. What exactly did you test on? I have absolutely consistent reproduction on FreeBSD 12.1 systems, including completely fresh installations.

**Comment by andryyy** [comment]
Debian 10
