### ISSUE TITLE
[BUG] user _rspamd should that not be rspamd

### ISSUE THREAD

**Issue by f1-outsourcing** [rspamd/rspamd#3406]
AFAIK centos users daemons are never starting with _. No idea if this changed in rhel8.

```
[@spam2 rspamd]# grep rspam /etc/passwd
_rspamd:x:492:227:Rspamd user:/var/lib/rspamd:/bin/false
```

rspamd-2.0-14.gita5f75e4a3.x86_64
CentOS release 6.10 (Final)

**Comment by vstakhov** [comment]
I'm sorry but that won't be changed as it will break almost all the existing installations. `_` comes from the Debian conventions, I've not realised that they are different in any Linux distro. There is nothing harmful in having `_` prefix here but, on the contrary, changing that is definitely going to break systems. So it will not be changed.
