### ISSUE TITLE
[BUG] DMARC whitelist does not appear to work for local mail

### ISSUE THREAD

**Issue by plinss** [rspamd/rspamd#3407]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Local mail is getting marked as spam.

I have a number of mail servers and have added all their domains to /etc/rspamd/local.d/maps.d/dmarc_whitelist.inc.local

Mail sent from one of my servers that is listed in the dmarc_whitelist to another gets a very low score, e.g. WHITELIST_DMARC(-28.00) so it appears that the whitelist is working.

However mail sent from a local user to another local user does not get the whitelist score and is often classified as spam even though the local server is in the whitelist and the mail is dkim signed.

I'd be happy to learn there's a configuration setting I missed or a better way to whitelist local mail.

### Steps to Reproduce

Send mail from one local user to another

**Expected behavior**
DMARC whitelist should apply and affect overall score.

### Versions

Rspamd daemon version 2.5
Debian 10.4 on x86_64

**Comment by klausenbusk** [comment]
> However mail sent from a local user to another local user does not get the whitelist score and is often classified as spam even though the local server is in the whitelist and the mail is dkim signed.

DMARC checking is disabled for local and authenticated users:
https://github.com/rspamd/rspamd/blob/286cd0143ea834021147e36f307fe13f6e99be83/src/plugins/lua/dmarc.lua#L599-L602

You can't disable it, but you could use `dkim_whitelist.inc.local`. Another option is simply disabling the relevant checks for "authenticated users": https://rspamd.com/doc/configuration/settings.html#settings-structure
