### ISSUE TITLE
Can't match header with user settings ?

### ISSUE THREAD

**Issue by LeDistordu** [rspamd/rspamd#3408]
Hi, I searched everywhere, asked questions about IRC but I can't find the solution... I try to match header with user settings

I just want disable symbol if header "List-Unsubscribe" exist

I try 

```
newsletter {
    id = "newsletter";
    priority = high;
    header = ["List-Unsubscribe"];
    apply {
        symbols_disabled = ["BAYES_SPAM","R_SUSPICIOUS_IMAGES","HTML_SHORT_LINK_IMG_1","MISSING_TO"];
    }
}
```
I try lot of things (I'm going to be crazy) : 

    header = ["List-Unsubscribe"];
    request_header = ["List-Unsubscribe"];
    request_header = ["List-Unsubscribe" = ".*"];
    request_header = {"List-Unsubscribe" = ".*"};
    ....

**Comment by fatalbanana** [comment]
```
    header = {
      "List-Unsubscribe" = ".*"
    }
```

**Comment by LeDistordu** [comment]
Thank you it works !! :)
