### ISSUE TITLE
[BUG] Incorrect entries in the REDIS with rspamc for the FUZZY module

### ISSUE THREAD

**Issue by beschastnov** [rspamd/rspamd#3410]
Incorrect entries in the REDIS with rspamc for the FUZZY module.
There are both normal and garbage records in REDIS.
The configuration is almost standard, the only one for training by users is not BAYES, but FUZZY.
I do not observe errors in RSPAMD logs.

Sometimes the following errors occur in DOVECOT logs:
_Error: sieve: pipe action: failed to execute to program `sa-learn-spam.sh': refer to server log for more information.
Error: sieve: Execution of script /etc/dovecot/sieve/before/report-spam.sieve failed_
I suppose these errors may be related to garbage in REDIS

Additionally:
It is not possible to delete invalid keys from the REDIS database.
I guess REDIS stumbles on the characters in the command redis-cli and the program ends.

OS: Debian 9.12 (4.9.210-1 x86_64 GNU/Linux)
Rspamd daemon version 2.5

**REDIS output part, command; redis-cli --scan --pattern 'fuzzy*'**
fuzzy_5_511224598946480011
fuzzy_25_772816414989100313
fuzzy_21_68285457733436361
fuzzy_23_1093173447360358065
fuzzy_7_148972079867200762
fuzzy▒▒▒Ȓ9q▒▒▒vhN`▒q▒y*3ʝ▒2▒▒▒v▒"▒BT▒o▒j▒▒t▒▒▒-wO▒▒4▒+
fuzzy_5_103867494505175720
fuzzy+3I▒y!▒▒▒▒0H▒▒▒o▒▒▒%"#▒."▒▒V?▒▒▒w(ۗ4=▒7B▒Xǔ▒▒▒rg▒m
fuzzy▒ ڈ▒>Vxw▒▒
*▒gW▒@▒▒:(▒▒~▒▒▒▒▒d0sw▒뾈▒▒▒▒)▒▒▒▒U▒▒▒O
fuzzy_27_422309031281213159
5!▒▒Q▒▒▒▒~▒y▒A:▒▒
▒aq▒`K{▒h▒▒▒▒Q▒.▒w▒▒~▒e▒C▒Q▒▒
                             _▒$▒sL▒T▒'▒▒/0-▒[|
fuzzy▒▒
       ▒▒[▒▒&Q▒#▒'8%>འǡ▒)l▒N▒ߞ▒X▒▒{2▒7|c▒▒h▒▒▒▒▒s?
fuzzyVE▒q▒F▒$

# dovecot.conf
plugin {
  sieve_plugins = sieve_imapsieve sieve_extprograms
 
  imapsieve_mailbox1_name = "Нежелательная почта"
  imapsieve_mailbox1_causes = COPY
  imapsieve_mailbox1_before = file:/etc/dovecot/sieve/before/report-spam.sieve

  imapsieve_mailbox2_name = *
  imapsieve_mailbox2_from = "Нежелательная почта"
  imapsieve_mailbox2_causes = COPY
  imapsieve_mailbox2_before = file:/etc/dovecot/sieve/before/report-ham.sieve

  sieve_pipe_bin_dir = /etc/dovecot/sieve/before
  sieve_global_extensions = +vnd.dovecot.pipe

# sa-learn-ham.sh
#!/bin/sh
exec /usr/bin/rspamc -S LOCAL_FUZZY_WHITE -w 1 -h localhost:11334 -P "PASSWORD" fuzzy_add

# sa-learn-spam.sh
#!/bin/sh
exec /usr/bin/rspamc -S LOCAL_FUZZY_PROB -w 1 -h localhost:11334 -P "PASSWORD" fuzzy_add

# report-ham.sieve
require ["vnd.dovecot.pipe", "copy", "imapsieve", "environment", "variables"];
if environment :matches "imap.mailbox" "*" {
  set "mailbox" "${1}";
}
if string "${mailbox}" "Удаленные" {
  stop;
}
if string "${mailbox}" "Корзина" {
  stop;
}
if string "${mailbox}" "Trash" {
  stop;
}
if string "${mailbox}" "Deleted Messages" {
  stop;
}
if environment :matches "imap.user" "*" {
  set "username" "${1}";
}
pipe :copy "sa-learn-ham.sh" [ "${username}" ];

# report-spam.sieve
require ["vnd.dovecot.pipe", "copy", "imapsieve", "environment", "variables"];
if environment :matches "imap.user" "*" {
  set "username" "${1}";
}
pipe :copy "sa-learn-spam.sh" [ "${username}" ];

# fuzzy_check.conf
rule "local" {
    servers = "127.0.0.1:11335";
    symbol = "LOCAL_FUZZY_UNKNOWN";
    mime_types = ["*"];
    max_score = 20.0;
    read_only = no;
    skip_unknown = yes;
    algorithm = "mumhash";
    short_text_direct_hash = true;

    fuzzy_map = {
        LOCAL_FUZZY_DENIED {
            max_score = 20.0;
            flag = 11;
        }
        LOCAL_FUZZY_PROB {
            max_score = 10.0;
            flag = 12;
        }
        LOCAL_FUZZY_WHITE {
            max_score = 2.0;
            flag = 13;
        }
    }
}

# fuzzy_group.conf
symbols = {
    "LOCAL_FUZZY_UNKNOWN" {
        weight = 5.0;
        description = "Generic fuzzy hash match";
    }
    "LOCAL_FUZZY_DENIED" {
        weight = 12.0;
        description = "Denied fuzzy hash";
    }
    "LOCAL_FUZZY_PROB" {
        weight = 5.0;
        description = "Probable fuzzy hash";
    }
    "LOCAL_FUZZY_WHITE" {
        weight = -2.1;
        description = "Whitelisted fuzzy hash";
    }
}

# worker-fuzzy.inc
allow_update = ["127.0.0.1"];
bind_socket = "127.0.0.1:11335";
backend = "redis";
expire = 100d;
sync = 1min;

**Comment by vstakhov** [comment]
Redis keys are binay indeed. That was an intended decision. However, there might be a script to delete fuzzy entries. As usually, I leave that to volounteers. Per se, it is not a bug at all.

**Comment by beschastnov** [comment]
Thanks for the clarification. In order not to clutter up the main instance with such recordings, I connected the fuzzy module to a separate of the redis server.

**Comment by vstakhov** [comment]
Yes, another option is using of a separate DB in the same Redis instance - it is also supported.
