### ISSUE TITLE
Can't disable greylisting

### ISSUE THREAD

**Issue by gnilebein** [rspamd/rspamd#3412]
### Prerequisites

* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
I deactivated greylisting as described in the FAQ. However, greylisting remains active.

### Steps to Reproduce

1. Place "enabled = false;" in local.d/greylist.conf
2. Set a low greylisting score.
3. Restart RSPAMD
4. In history mails still get greylisted

**Expected behavior**
Mails should not get greylisted

### Versions

Rspamd daemon version 2.5 - Ubuntu 16.04.6 LTS

### Additional Information

Greylist part from configdump:

```
greylist {
    ipv6_mask = 64;
    whitelist_domains_url [
        "/etc/rspamd/local.d/greylist-whitelist-domains.inc",
        "/etc/rspamd/local.d/maps.d/greylist-whitelist-domains.inc",
    ]
    expire = 86400;
    enabled = false;
    ipv4_mask = 19;
    message = "Try again later";
    max_data_len = 10000;
    action = "soft reject";
    key_prefix = "rg";
    timeout = 300;
}
```

**Comment by GieltjE** [comment]
Add "greylist = null;" to "override.d/actions.conf" should solve it for now

**Comment by gnilebein** [comment]
But why there is an option to disable it? The official faq says this is the way to disable it.

**Comment by GieltjE** [comment]
That's probably a bug (cannot verifty, a dev should be able to quickly), just noting a possible (temp) solution.

**Comment by fatalbanana** [comment]
`greylist` action is not greylisting; rather it's functionally the same as `no action`.

**Comment by micoraweb** [comment]
So a 'simple setting' and it can't be switched off?! Why is it so difficult and there's still no clear answer as to how this unwanted functionality can be easily disabled?!

**Comment by fatalbanana** [comment]
> So a 'simple setting' and it can't be switched off?! Why is it so difficult and there's still no clear answer as to how this unwanted functionality can be easily disabled?!

Both `greylist` module and `greylist` action can be disabled, as detailed on this page among other places. 

The former won't work without configuration & the latter shouldn't really do anything.

**Comment by micoraweb** [comment]
Tried everything from this list and still can't switch off the greylisting completely. I just bought an online course, and the email confirming my purchase is labeled as "greylist"-ed. I don't need that. How can I completely switch off and/or control this greylisting functionality ? :)

**Comment by fatalbanana** [comment]
> Tried everything from this list and still can't switch off the greylisting completely. I just bought an online course, and the email confirming my purchase is labeled as "greylist"-ed. I don't need that. How can I completely switch off and/or control this greylisting functionality ? :)

`greylist` action is not greylisting; rather it's functionally the same as `no action`.

How to disable `greylist` action is described [here](https://github.com/rspamd/rspamd/issues/3412#issuecomment-649515985); how to disable the `greylist` module is described in the [original post](https://github.com/rspamd/rspamd/issues/3412#issue-644362175); greylist module does not work without configuration so there is nothing in need of being disabled out-the-box.

**Comment by micoraweb** [comment]
Thank you!

**Comment by TCB13** [comment]
> > Tried everything from this list and still can't switch off the greylisting completely. I just bought an online course, and the email confirming my purchase is labeled as "greylist"-ed. I don't need that. How can I completely switch off and/or control this greylisting functionality ? :)
> 
> `greylist` action is not greylisting; rather it's functionally the same as `no action`.
> 
> How to disable `greylist` action is described [here](https://github.com/rspamd/rspamd/issues/3412#issuecomment-649515985); how to disable the `greylist` module is described in the [original post](https://github.com/rspamd/rspamd/issues/3412#issue-644362175); greylist module does not work without configuration so there is nothing in need of being disabled out-the-box.

But if an email is marked as "greylist" doesn't that mean it won't be marked as "add header" for example? My goal is to be able to completely disable greylisting and make sure all emails above 5 are sent to the spam folder.

I've this:

```
cat /var/lib/rspamd/rspamd_dynamic
[
    {
        "metric": "default",
        "actions": [
            {
                "name": "rewrite subject",
                "value": nan
            },
            {
                "name": "add header",
                "value": 5.0
            },
            {
                "name": "reject",
                "value": 12.0
            },
            {
                "name": "greylist",
                "value": nan
            }
        ],
        "symbols": []
    }
]
```

```
 rspamadm configdump greylist
unknown worker attribute: servers; worker type: normal
*** Section greylist ***
whitelist_domains_url [
    "/etc/rspamd/local.d/greylist-whitelist-domains.inc",
    "/etc/rspamd/local.d/maps.d/greylist-whitelist-domains.inc",
]
expire = 86400.0;
timeout = 300.0;
key_prefix = "rg";
max_data_len = 10000;
message = "Try again later";
action = "no action";
ipv4_mask = 19;
ipv6_mask = 64;
enabled = false;

*** End of section greylist ***
```

However I still see some emails marked as "greylist" on the webUI that never reached the spam folder.

I now created a this: /etc/rspamd/local.d:
```
default {
    symbols_disabled = ["GREYLIST_CHECK", "GREYLIST_SAVE"];
}
```

But this is probably not correct because it says ` no actions in settings: default` in the logs.
