### ISSUE TITLE
[Feature] Support Microsoft Defender ATP for Linux

### ISSUE THREAD

**Issue by m3nu** [rspamd/rspamd#3416]
## Summary

Microsoft just [released](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-linux) their virus scanner for Linux. There is no ICAP interface or similar yet, but it's possible to disable all on-access scanning and just scan a single path (they call it passive mode). They also provide repos for all major distros for simple updates.

## Motivation

Have another free virus scanner option.

## Describe alternatives you've considered

Most people would already use ClamAV, so this would be an addition.

## Additional context

- [Introduction to MS Defender AV for Linux](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/microsoft-defender-atp-linux)
- [Install instructions](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually)
- [ CLI Configuration](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-resources#configure-from-the-command-line)

**Comment by vstakhov** [comment]
It doesn't have any interface to interact with from what I see in the documentation. That will not work with Rspamd.

**Comment by m3nu** [comment]
Right. That's what I found too. I'll report back here, when/if they add an interface.
