### ISSUE TITLE
Mailu Rspamd Missing column in history

### ISSUE THREAD

**Issue by pcuryllo** [rspamd/rspamd#3420]
Mailu - 1.7
Rspamd - 1.9.4

I have a problem with missing column in rspamd history.
I haven't looked into it for a long time, maybe there was an latest update.

Earlier following columns
![image](https://user-images.githubusercontent.com/1391933/86465616-5036bb00-bd32-11ea-8565-77ae30fdf2aa.png)

Currently missing columns: [Envelope From] From, [Envelope To] To/CC/Bcc

What can this be caused by, can it be restored in the configuration settings?

**Comment by moisseev** [comment]
You need to enable [redis history module](https://rspamd.com/doc/modules/history_redis.html).

Please do not ask support questions on Github issues.

**Comment by pcuryllo** [comment]
The module was on. The module update helped.
https://hub.docker.com/r/mailu/rspamd

Thank you for your help.
