### ISSUE TITLE
[BUG] FORWARDED rule is not working

### ISSUE THREAD

**Issue by SuperTux88** [rspamd/rspamd#3430]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
It looks like the [`FORWARDED`](https://github.com/rspamd/rspamd/blob/f94be8262d42e1f02d124682ac1a46b3c1c39805/rules/forwarding.lua#L110-L159) rule isn't working, because it checks for `for` in the Received header, but nothing is there, but there is a `for <foobar@example.com>` in the header.

I added a debug output to the rule to log the content of the `rcvd` variable for every loop, this is the output (I changed the mail address, the mail was sent from gmail to gmx which forwards to my server):

`{[by_hostname] = mx-ha.gmx.net, [proto] = esmtps, [from_ip] = 209.85.210.49, [real_ip] = 209.85.210.49, [raw] = from mail-ot1-f49.google.com ([209.85.210.49]) by mx-ha.gmx.net (mxgmx117 [212.227.17.5]) with ESMTPS (Nemesis) id 1Mul6x-1klWOh40KB-00ronN for <xxx@gmx.ch>; Fri, 10 Jul 2020 21:01:21 +0200, [flags] = {[authenticated] = false, [ssl] = true, [artificial] = false}, [from_hostname] = mail-ot1-f49.google.com, [timestamp] = 1594407681}`

As you can see, the `[raw]` contains the `for <xxx@gmx.ch>`, but there is no `[for]`.

If I understand it correctly, the `for` should be set [here](https://github.com/rspamd/rspamd/blob/f94be8262d42e1f02d124682ac1a46b3c1c39805/src/lua/lua_task.c#L3044) from `for_mbox`, but I don't find where `for_mbox` is set (but my C knowledge is very limited).

### Steps to Reproduce

1. Create a mail forward rule on another mail server to be forwarded to an address on my server
2. Send mail to this created forwarding mail address
3. Mail triggers `FORGED_SENDER` and `FORGED_RECIPIENTS`, but not `FORWARDED`.

**Expected behavior**
Mail should be marked as `FORWARDED` and `FORGED_SENDER_FORWARDING` and `FORGED_RECIPIENTS_FORWARDING` should prevent `FORGED_SENDER` and `FORGED_RECIPIENTS`.

### Versions

Rspamd daemon version 2.5 on debian buster from https://rspamd.com/downloads.html

**Comment by vstakhov** [comment]
It seems that `for` part is now not processed at all :( I will check, thanks for report!

**Comment by SuperTux88** [comment]
The bug still exists.

**Comment by SuperTux88** [comment]
OK, it looks like this was fixed in the new 2.6 release with commit https://github.com/rspamd/rspamd/commit/0e7eeb52add2e905fd935043b6a80519f283ef91, but since the issue wasn't updated I didn't know that it was already fixed but not released yet.
