### ISSUE TITLE
rspamd doesn't learn spam

### ISSUE THREAD

**Issue by comfuzio** [rspamd/rspamd#3440]
Hello!
I am running a Centos 7.8.2003 server with vestacp panel and rspamd 2.5.
I have installed rspamd following this guide https://forum.vestacp.com/viewtopic.php?f=12&t=18479
My problem is, I get every day lots of spam which consists of 10~15 different messages.
The spam mail comes from different domains but the messages are exactly the same! Identical!
I login to web UI to rspamd/#scan and copy the emails and paste them here, scan and then upload spam.
No errors, all goes well. 1 minute later, the exact same e-mail but from different sender, arrives in my inbox! 
Maybe 1 out of 100 spam mails I get goes to the actual spam folder and none of them change the headers.
Could something be wrong in the guide i've followed? 
I've also tried to make a list to reject emails based on content, for example none from the domains I host have any use for pills, so any email containing this term should be deleted and never ever arrive in an inbox, but yet it does!

**Comment by vstakhov** [comment]
Is it Rspamd issue? Apparently no! And this place is for bug reports/feature requests only, not for support questions.

**Comment by comfuzio** [comment]
And how do you know it is not an issue by rspamd?

**Comment by nh2** [comment]
> And how do you know it is not an issue by rspamd?

@comfuzio That cannot be known, but your issue description does not provide anything actionable, so it is not very useful for developers.

> Could something be wrong in the guide i've followed?

Of course it could be, but developers rarely have time to check every possible guide for mistakes, given how many different possible integrations exist.

You should:

* Report your to the author of the guide instead.
* Use the "General Questions and Community Support" or "Commercial Support" offerings from https://rspamd.com/support.html
* If you find that it's a misconfiguration that could be avoided by better documentation in Rspamd, open an issue about the concrete documentation that is unsatisfactory.
* If you believe there is a bug, make a minimal reproducer:, including all data Provide the spam messages you train with, and an easily reproducible setup where you feed them to Rspamd, and then show how it still classifies other messages you provide incorrectly.
