### ISSUE TITLE
Errors in GUI after Learning Rspamd with Spam-Mails 

### ISSUE THREAD

**Issue by maze-m** [rspamd/rspamd#3446]
Hi there! 

Hope. it's okay to ask here my question... I've setup rspamd and it works fine. But when I try to learn my rspamd-Setup with Spam-Mails I can see the following errors in the Web-GUI:

![grafik](https://user-images.githubusercontent.com/50629567/87931110-8346b180-ca89-11ea-98e5-8e3b5ff74313.png)

Does anyone have an idea what I can do regarding this?

---

* Mailing list: https://lists.rspamd.com/mailman/listinfo (you can subscribe on that page or browse the archives)
* Telegram channel: http://t.me/rspamd
* Also have a look at the following page for more information on how to get support:
  https://rspamd.com/support.html

**Comment by vstakhov** [comment]
No, it is not OK place to ask question, closing issue.
