### ISSUE TITLE
[Feature] Enable DKIM for certain domains only

### ISSUE THREAD

**Issue by micw** [rspamd/rspamd#3451]
## Summary

Allow to Enable DKIM signing for certain domains only

## Motivation

I'm adding DKIM for some domains. Currently all domains are signed but not all domains contains the key in DNS. That should not harm but "in the wild", some MTAs reject dkim signed mails with missing keys in DNS.

## Describe alternatives you've considered

I tried to set enabled=false globally and enabled=true for some domains in dkim_signing.conf but the later is ignored then.

I tried to set "path" to a non-existing file or empty globally and to someting else for some domains. That works as expected but logs warning message about missing key files on every single mail that is not signed.

**Comment by vstakhov** [comment]
Please read the documentation. You describe not an issue but a deep misunderstanding of how this module works. Closing an issue.
