### ISSUE TITLE
[BUG] Rspamd does not detect the postfix user has been authenticated?

### ISSUE THREAD

**Issue by flixman** [rspamd/rspamd#3452]
### Prerequisites

* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Rspamd is not detecting that a user is authenticated, and does not sign the mail accordingly (because the mail becomes not eligible). From a webmail on the same machine, the mail get successfully signed.

### Steps to Reproduce

1. Send a mail from a non local network (through submission)

**Expected behavior**
The mail gets successfully signed

### Versions
Rspamd version 2.5
Debian buster

### Additional Information
This is the postfix / rspamd log with debugging enabled: 

Jul 26 12:02:35 domain postfix/smtpd[3379]: connect from unknown[1.2.3.4]
Jul 26 12:02:35 domain postfix/smtpd[3379]: Anonymous TLS connection established from unknown[1.2.3.4]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (P-384) server-digest SHA384
Jul 26 12:02:39 domain postfix/smtpd[3379]: 046B480A: client=unknown[1.2.3.4], sasl_method=LOGIN, sasl_username=user@domain.org
Jul 26 12:02:39 domain postfix/cleanup[3011]: 046B480A: message-id=<1716798.cDEPJIj1py@laptop>
Jul 26 12:02:39 domain rspamd[25168]: <402ed9>; dkim_signing; lua_dkim_tools.lua:170: mail is ineligible for signing

This is the configuration in place, reported by rspamd:

dkim_signing {
    use_esld = true;
    allow_hdrfrom_mismatch = false;
    selector = "mail";
    symbol = "DKIM_SIGNED";
    sign_networks [
        "127.2.4.7",
    ]
    allow_envfrom_empty = true;
    try_fallback = true;
    sign_authenticated = true;
    path = "/mnt/websites/$domain/certs/dkim.key.pem";
    use_redis = false;
    allow_username_mismatch = false;
    sign_local = true;
    key_prefix = "DKIM_KEYS";
    use_domain = "header";
    allow_hdrfrom_multiple = false;
}

In my postfix configuration, I have the following:
in main.cf: smtpd_milters=local:/var/run/rspamd/worker-proxy.sock

in master.cf:
submission inet n       -       y       -       -       smtpd
  -o strict_rfc821_envelopes=no
  -o smtpd_client_restrictions=permit_mynetworks,reject_plaintext_session,permit_sasl_authenticated,reject

**Comment by vstakhov** [comment]
It is not an Rspamd issue, it is your configuration issue. GH issues are not for support questions -> closing issue.
