### ISSUE TITLE
[BUG] DMARC Module: additional_address_bcc isn't working

### ISSUE THREAD

**Issue by dragoangel** [rspamd/rspamd#3465]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
If add `additional_address_bcc` to `dmarc.conf` rspamd will send report only to original recipients and will skip sending mail to additional_address as BCC.

### Steps to Reproduce

1. enable & configure DMARC reporting module to send emails to `additional_address` and add `additional_address_bcc=true` to config. Note: even setting `additional_address_bcc=false` in my case was been lead to this bug.
2. wait ~24 hours and check `additional_address` inbox folder, it will not get copy of reports
3. check rspamd logs and there will no rcpt to `additional_address` also

**Expected behavior**
When `additional_address_bcc=true` set to true mail will delivered to `additional_address` as hidden copy. If `additional_address_bcc=false` mail will delivered to `additional_address` as usual `To: rcpt` as well.

### Versions

Rspamd 2.5 inside Docker container, as part of Mailcow Docker-Compose Project

**Comment by dragoangel** [comment]
This bug created for informational purpose.

**Comment by dragoangel** [comment]
Unstale

**Comment by palWorx** [comment]
And unstale again.
Same problem here but no docker installation. Installed rspamd-2.6-156.x86_64 from centos repo. Working like a charm - so far - but there are no dmarc-reports to the additional adress.
