### ISSUE TITLE
Howto: write a copy of received message to disk/storage

### ISSUE THREAD

**Issue by systemcrash** [rspamd/rspamd#3470]
Currently I have postfix BCC a copy of every message, which is written to a user folder somewhere, and discarded after x days. Allows me at a later stage to review spam that crept through.  

But if a message is rspamd rejected, it does not reach this stage. 

Can rspamd write a copy of *everything* to disk somewhere? How? 

This will allow me to tighten up on false negatives and fix false positives.

**Comment by mans39** [comment]
Hi,

I think you can do that with the metadata exporter module : https://rspamd.com/doc/modules/metadata_exporter.html

Regards,

**Comment by vurgun** [comment]
Ready to go example Lua example
"Maildir delivery based on Rspamd" part

[https://rspamd.com/doc/lua/examples.html](https://rspamd.com/doc/lua/examples.html)

**Comment by systemcrash** [comment]
"some assembly required" :)

I think this is closest to what I'm looking for - thank you. 

> Ready to go Lua example
> "Maildir delivery based on Rspamd" part
> 
> https://rspamd.com/doc/lua/examples.html

**Comment by vstakhov** [comment]
This is not an issue/feature request, closing.
