### ISSUE TITLE
[BUG] rspamadm configtest segfaults

### ISSUE THREAD

**Issue by knutov** [rspamd/rspamd#3475]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following: [...] 

**Describe the bug**

`/usr/bin/rspamadm configtest` can randomly run without errors or do segfault, with no changes of configs during the test.

### Steps to Reproduce

```
root@mx-wip:/etc/rspamd# /usr/bin/rspamadm configtest
syntax OK
root@mx-wip:/etc/rspamd# /usr/bin/rspamadm configtest
Segmentation fault (core dumped)
root@mx-wip:/etc/rspamd# /usr/bin/rspamadm configtest
Segmentation fault (core dumped)
root@mx-wip:/etc/rspamd# /usr/bin/rspamadm configtest
Segmentation fault (core dumped)
root@mx-wip:/etc/rspamd# /usr/bin/rspamadm configtest
syntax OK
```

**Expected behavior**

do not segfault

### Versions

Ubuntu 20.04 inside LXD container (with latest LXD from snap from  `latest/stable` branch).
Rspamd daemon version 2.5 from rspamd ubuntu deb repo.

### Additional Information

I can do `sysctl -w kernel.core_pattern=...` but it generates core for the all LXD node with private (I supposed) information.

Inside dmesg I see:

```
[Wed Aug 19 00:56:36 2020] rspamadm[23190]: segfault at 7ffd93cceff8 ip 00007fd5a1f870a7 sp 00007ffd93ccf000 error 6 in librspamd-server.so[7fd5a1ef7000+3ea000]
[Wed Aug 19 00:56:36 2020] Code: f1 80 fa 01 77 0d b8 01 00 00 00 5b c3 66 0f 1f 44 00 00 48 8b 15 09 5c 3a 00 0f b6 04 02 3c 01 74 29 3c 02 75 1d 48 8d 7b 08 <e8> c4 ff ff ff 85 c0 75 d3 48 63 43 04 48 8d 1c c3 eb ba 66 0f 1f
[Wed Aug 19 00:57:21 2020] rspamadm[25346]: segfault at 7ffc205f1ff8 ip 00007f1cfe94e0a7 sp 00007ffc205f2000 error 6 in librspamd-server.so[7f1cfe8be000+3ea000]
[Wed Aug 19 00:57:21 2020] Code: f1 80 fa 01 77 0d b8 01 00 00 00 5b c3 66 0f 1f 44 00 00 48 8b 15 09 5c 3a 00 0f b6 04 02 3c 01 74 29 3c 02 75 1d 48 8d 7b 08 <e8> c4 ff ff ff 85 c0 75 d3 48 63 43 04 48 8d 1c c3 eb ba 66 0f 1f
[Wed Aug 19 00:57:23 2020] rspamadm[25364]: segfault at 7ffe87a43ff8 ip 00007fb4333f80a7 sp 00007ffe87a44000 error 6 in librspamd-server.so[7fb433368000+3ea000]
[Wed Aug 19 00:57:23 2020] Code: f1 80 fa 01 77 0d b8 01 00 00 00 5b c3 66 0f 1f 44 00 00 48 8b 15 09 5c 3a 00 0f b6 04 02 3c 01 74 29 3c 02 75 1d 48 8d 7b 08 <e8> c4 ff ff ff 85 c0 75 d3 48 63 43 04 48 8d 1c c3 eb ba 66 0f 1f
[Wed Aug 19 00:57:25 2020] rspamadm[25602]: segfault at 7fff30edeff8 ip 00007fdd051680a7 sp 00007fff30edf000 error 6 in librspamd-server.so[7fdd050d8000+3ea000]
[Wed Aug 19 00:57:25 2020] Code: f1 80 fa 01 77 0d b8 01 00 00 00 5b c3 66 0f 1f 44 00 00 48 8b 15 09 5c 3a 00 0f b6 04 02 3c 01 74 29 3c 02 75 1d 48 8d 7b 08 <e8> c4 ff ff ff 85 c0 75 d3 48 63 43 04 48 8d 1c c3 eb ba 66 0f 1f
```

**Comment by mjeanrichard** [comment]
Same here. Thi also happens while `running rspamadm configtest` (it also works every now and then)
gdb output:
`#0  0x00007feb1a3370a7 in hascaptures () from /usr/lib/rspamd/librspamd-server.so`

**Comment by vstakhov** [comment]
CPU architecture?

**Comment by knutov** [comment]
@vstakhov intel 64bit

**Comment by mjeanrichard** [comment]
Intel, 64bi on Ubuntu 20.04.1 LTS.
I also installed the DBG Package. GDB output is now
``#0  0x00007feb1a3370a7 in hascaptures (tree=0x7feb15cbb18c) at ./contrib/lua-lpeg/lpcode.c:144``
It looks like there have been some changes recently to that file. There is an additional method `callrecursive`. Is there any chance that this is fixed on the current master?
I only have a production machine with Rspam running and don't want to compile Rspamd from source on there. Is there any plan to create a new Ubuntu Package from master? Or should I install it from experimental branch? Is there any way to tell what code is in the current experimental package?

**Comment by vstakhov** [comment]
It is fixed in the current master and in the experimental packages.

**Comment by mjeanrichard** [comment]
Cool, thanks. I'll try experimental now.

**Comment by hfaleiros** [comment]
same happens here on focal, when the fix will be available on apt-stable?

**Comment by mconigliaro** [comment]
FWIW, rspamd 2.6 is working for me on focal.

**Comment by nh2** [comment]
For me upgrading Rspamd 2.5 -> 2.6 also fixed segfaults at startup.
