### ISSUE TITLE
Video file gets flagged as mime type exe [BUG]

### ISSUE THREAD

**Issue by T9C5F** [rspamd/rspamd#3481]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Rspamd falsely detects an exe mime extension in an h264 mp4 video file. I stripped the video's bytes to narrow down the false positive. The extracted bytes are near the end of the original video file. Maybe a part of the sequence is already sufficient.

### Steps to Reproduce

1. Send a file as an attachment which contains these bytes: ```.9ó..\...;...Y!..6...^...4^..`...7†..f...f...9É..N¾..G...?‘..E?..Fö..b...PE..R¦..@}..e```
2. Video attachment gets flagged as MIME_BAD_EXTENSION Bad extension (40) [exe]

**Expected behavior**
It should not be flagged as an exe file as it's a normal video file.

### Versions
Rspamd daemon version 2.5
Inside an x86 docker debian:buster-slim

**Comment by vstakhov** [comment]
It should be fixed now, thanks for report.
