### ISSUE TITLE
What does it take to integrate Cloudmark or Cyren into rspamd checks

### ISSUE THREAD

**Issue by oleksandriegorov** [rspamd/rspamd#3482]
Hi, I wonder:
- what would it take to add support for Cloudmark and/or Cyren into rspamd. Would it be lua code as with Vade Secure?
- is there only http interface available for communication with spam filtering engine or header inspection (for milter integration would suffice too)?

**Comment by vstakhov** [comment]
That should be not difficult at all. In fact, when I've worked on external services I have written to many OEM systems, including Cloudmark and Cyrent. Unfortunately, the only companies that have replied were Vade and Kaspersky. I'd like to thank all people from the companies mentioned for collaboration - we now have quite sane support of their products. Cloudmark/Cyren has either not replied or dropped the communication suddenly. That's a pity but I'm not inclined to beg large companies to allow adding their products support in my (semi)hobby project - I just got nothing for that.
