### ISSUE TITLE
[Feature] Support Prometheus metrics

### ISSUE THREAD

**Issue by mrueg** [rspamd/rspamd#3484]
## Summary

Currently rspamd only supports graphite metrics, it would be great if there were support for https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format metrics as well
## Motivation
We use prometheus to monitor systems and would like to monitor rspamd as well.

## Describe alternatives you've considered

Setting up graphite and pull via prometheus from there is not viable as it requires additional services to maintain.

## Additional context

Some implementations how this could look like as a lua-plugin:
https://github.com/knyar/nginx-lua-prometheus/blob/master/prometheus.lua
https://github.com/tarantool/prometheus

**Comment by vstakhov** [comment]
Tarantool library looks almost ready to use. However, I have neither need nor desire to write such a plugin. But I leave space for volounteers here. 

The current metric_exporter plugin is poorly designed and needs to be rewritten. I even had some branch with this work but it has never been finished.

**Comment by fatalbanana** [comment]
One might query `/stat` on the controller directly I suppose- but the result is not suitable for direct consumption by Prometheus. One could write an `exporter` to deal with it and scrape that instead; it looks like others are using [https://github.com/shiroyagicorp/prometheus-json-exporter](json-exporter) with rspamd so far.

**Comment by dragoangel** [comment]
Yep, native support will be cool. For example HAproxy had csv export that was been converted to prometheus by dedicated exporter, but after some time HAproxy created buildin exported, and it quite popular as far I know

**Comment by mrueg** [comment]
For those interested in getting prometheus metrics now, @WilliButz has implemented a module using json-exporter for NixOS (https://github.com/NixOS/nixpkgs/pull/68496) and shared a rendered config with me: https://gist.github.com/WilliButz/2ed6cb59eb7e684ed79a5b4b09503ccc

**Comment by systemcrash** [comment]
Frustrating. Didn't realize /stat was available. Doesn't seem like a stretch to go from JSON to Prometheus metrics. 


> The current metric_exporter plugin is poorly designed and needs to be rewritten. I even had some branch with this work but it has never been finished.

Which branch, BTW?

Let us put it this way: once a prometheus exporter is implemented, this repo and project now have keywords [Prometheus and exporter](https://trends.google.com/trends/explore?date=today%205-y&q=prometheus%20monitoring). 

People like to monitor their key infrastructure. 😄

**Comment by systemcrash** [comment]
Also, here's [roughly how openwrt do it](https://github.com/openwrt/packages/tree/openwrt-19.07/utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors).

**Comment by dragoangel** [comment]
Here is link to rspamd-exporter https://hub.docker.com/r/badsmoke/rspamd-exporter which convert current stats in prometheus format
