### ISSUE TITLE
[BUG] mx_checks: MX_GOOD added although MX record is missing for domain

### ISSUE THREAD

**Issue by tokred** [rspamd/rspamd#3486]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Minor bug: If a sender domain has no MX record, the mx_check module adds the symbols MX_MISSING(3.50) **_and_** MX_GOOD(-0.01) which should be in fact mutually exclusive.

No module configuration except enabling:
```
$ cat local.d/mx_check.conf
enabled = true;
```

Example log entry:
```
2020-09-15 12:32:09 #79386(rspamd_proxy) <d86f40>; proxy; rspamd_task_write_log:
 id: <202009151031.08FAVw0e013540@xxx.com>, qid: <5F42330E4E>, ip: 91.207.x.x, f
rom: <xxx@xx.com>, (default: F (soft reject): [8.00/15.00] [MX_MISSING(3.50){},M
IME_HEADER_CTYPE_ONLY(2.00){},MISSING_MIME_VERSION(2.00){},R_MIXED_CHARSET(0.66)
{},BAYES_HAM(-0.25){73.30%;},MIME_HTML_ONLY(0.20){},DMARC_POLICY_SOFTFAIL(0.10){
ppops.net : No valid SPF, No valid DKIM;none;},MIME_GOOD(-0.10){multipart/relate
d;},RCVD_IN_DNSWL_LOW(-0.10){91.207.x.x:from;},MX_GOOD(-0.01){},ARC_NA(0.00){},A
SN(0.00){asn:xxxx, ipnet:91.207.x.x/23, country:GB;},FROM_EQ_ENVFROM(0.00){},FRO
M_NO_DN(0.00){},GREYLIST(0.00){greylisted;Tue, 15 Sep 2020 10:37:09 GMT;new reco
rd;},MIME_TRACE(0.00){0:+;1:~;2:~;},PREVIOUSLY_DELIVERED(0.00){aaa@aaa.com;},RCP
T_COUNT_ONE(0.00){1;},RCVD_COUNT_THREE(0.00){4;},RCVD_TLS_LAST(0.00){},R_DKIM_NA
(0.00){},R_SPF_NEUTRAL(0.00){?all;},TO_DN_NONE(0.00){},TO_MATCH_ENVRCPT_ALL(0.00
){}]), len: 29746, time: 3337.070ms, dns req: 39, digest: <891c3cd263437829d7536
c5305c80020>, rcpts: <aaa@aaa.com>, mime_rcpts: <aaa@aaa.com>, forced: soft reje
ct "Try again later"; score=nan (set by greylist)
```

### Steps to Reproduce

1. Send an email from a domain without MX record to rspamd.
2. Look in the rspamd.log entry for MX_ symbols

**Expected behavior**
As soon as MX_MISSING is being triggered, all other MX checks should probably be skipped to avoid other MX symbols are added.

### Versions

Rspamd daemon version 2.5
FreeBSD 11.3-RELEASE-p12

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by moisseev** [comment]
The symbols are not mutually exclusive. If the sender's domain  MX records are missing then mail can be delivered to A record.
In your case the sender's domain A record is likely pointing to a connectable SMTP server.

**Comment by tokred** [comment]
@moisseev: Huh, I did not consider this scenario. You are correct that the sender's domain has an A record.

Thanks, then I guess this can be closed. :)
