### ISSUE TITLE
[Feature] Mimetype check in attachment type mail (eml, msg)

### ISSUE THREAD

**Issue by lprat** [rspamd/rspamd#3487]
## Summary

Rspamd can score some extensions (https://rspamd.com/doc/modules/mime_types.html): exe, vbs, ...
This module can to check inside archive (https://rspamd.com/doc/modules/mime_types.html#archives-support).
it would be interesting to be able to check inside email format attachment: eml, msg; because you can attach eml file to mail, which contains a prohibited extension (by your policy). This attachment inside eml not detected by module "mime_types".

## Motivation
Avoid bypassing "mimetypes" module.

## Describe alternatives you've considered

For avoid this problem without this feature then use clamav yara sig.

**Comment by vstakhov** [comment]
I don't understand anything from the text above.

**Comment by lprat** [comment]
Sorry, I reedited my issue, I hope to be a little clearer.

**Comment by vstakhov** [comment]
Can you attach some samples please? As far as I know, .eml attachments should be parsed as mime documents.

**Comment by lprat** [comment]
----local.d/mime_types.conf-----
bad_extensions = {
  exe = 20
};
bad_archive_extensions = {
  pptx = 0.5,
  docx = 0.5,
  xlsx = 0.5,
  pdf = 1.0,
  jar = 3,
  js = 0.5,
  py = 0.5,
  jse = 8,
  vbs = 20,
  exe = 20
};
archive_extensions = {
  zip = 1,
  arj = 1,
  rar = 1,
  ace = 1,
  7z = 1,
  cab = 1
};

---------------SAMPLE-------------
Return-Path: <xxx@xxxx.fr>
Delivered-To: zzz@zzz.fr
Received: from host.zzz.fr ([127.0.0.1])
	by host.zzz.fr with LMTP
	id wHoIK+h/YF+uAAAAGkTlNg
	(envelope-from <xxx@xxxx.fr>)
	for <zzz@zzz.fr>; Tue, 15 Sep 2020 10:48:40 +0200
Received: from host.zzz.fr (xxx.xx [8.8.8.8])
	(using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
	 key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256)
	(No client certificate requested)
	by host.zzz.fr  (Postfix) with ESMTPS id 9B27A46824
	for <zzz@zzz.fr>; Tue, 15 Sep 2020 10:48:28 +0200 (CEST)
Received: from [127.0.0.1] (unknown [192.168.0.1])
	by host.zzz.fr (Postfix) with ESMTP id C6837230B95
	for <zzz@zzz.fr>; Tue, 15 Sep 2020 08:48:13 +0000 (UTC)
Content-Type: multipart/mixed; boundary="===============2114172985742389083=="
MIME-Version: 1.0
From: xxx@xxxx.fr
To: zzz@zzz.fr
Subject: SEND EXE
X-Last-TLS-Session-Version: TLSv1.3
Authentication-Results: zzz@zzz.fr;
	dkim=none;
	dmarc=none;
	spf=pass (zzz@zzz.fr: domain of xxx@xxxx.fr designates 8.8.8.8 as permitted sender) smtp.mailfrom=xxx@xxxx.fr

--===============2114172985742389083==
Content-Type: text/html; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

PCFET0NUWVBFIGh0bWw+PGh0bWwgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGh0bWwi
IGxhbmc9IiIgeG1sOmxhbmc9IiI+PGhlYWQ+PG1ldGEgY2hhcnNldD0idXRmLTgiIC8+Cjx0aXRs
ZT5UZXN0IGRlIHZ1bG7DqXJhYmlsaXTDqSBzdXIgbGEgY29uZmlndXJhdGlvbiBkZSBsYSBtZXNz
YWdlcmllPC90aXRsZT4KPC9oZWFkPgo8Ym9keT4KPGgxPlRlc3QgZGUgdnVsbmVyYWJpbGl0w6kg
SUQgbsKwOiA2NTwvaDE+CjxpbWcgc3JjPSJodHRwOi8vd3d3Mi5hc2xwc2FudGUuZnIvbWFpbC81
OS9saW9uZWxAdGVzdC5hc2xwc2FudGUuZnIvMTYwMDE1OTU3OS42NjMzOTQvNjUvaW1hZ2UucG5n
IiBzdHlsZT0ibWFyZ2luLXRvcDowcHg7Ij4KPGgyPkTDqXRhaWxzPC9oMj4KPHA+U2kgdm91cyBy
ZWNldmV6IGNlIGNvdXJyaWVsLCBjJ2VzdCBxdWUgdm91cyDDqnRlcyBwb3RlbnRpZWxsZW1lbnQg
dnVsbmVyYWJsZSDDoCBjZSB0ZXN0LjwvcD4KPHA+QWZpbiBkJ29idGVuaXIgbGVzIGluZm9ybWF0
aW9ucyBzdXIgY2UgdGVzdCwgYWluc2kgcXVlIGRlIHZhbGlkZXIgb3Ugbm9uIHNvbiByw6lzdWx0
YXQsIHZldWlsbGV6IHN1aXZyZSBjZSBsaWVuOiA8YSBocmVmPSJodHRwczovL3BtLmFzbHBzYW50
ZS5mci9tYWlsLzU5L2xpb25lbEB0ZXN0LmFzbHBzYW50ZS5mci8xNjAwMTU5NTc5LjY2MzM5NC82
NS9maWNoZV9oZWxwLmh0bWwiPmplIHbDqXJpZmllIGxhIHZhbGlkaXTDqSBkdSB0ZXN0LjwvYT48
L3A+CjxwPkxhIHZhbGlkYXRpb24gZHUgdGVzdCBwYXIgbGUgbGllbiBjaS1kZXNzdXMgcGVybWV0
IGxhIGfDqW7DqXJhdGlvbiBkdSByYXBwb3J0IGZpbmFsLjwvcD4KPGgyPkNvbnRhY3Q8L2gyPgo8
cD5DZSBjb3VycmllbCBlc3QgZ8OpbsOpcsOpIGF1dG9tYXRpcXVlbWVudCBwYXIgbCdvdXRpbCBk
ZSB0ZXN0cyBkZSB2dWxuw6lyYWJpbGl0w6lzIGRlIGxhIG1lc3NhZ2VyaWUgcmVhbGlzw6kgcGFy
IGxhIENlbGx1bGUgQUNTUyBkZSBsJ0FOUy48L3A+CjxwPlBvdXIgdG91cyBwcm9ibMOobWVzLCB2
b3VzIHBvdXZleiBjb250YWN0ZXIgY3liZXJ2ZWlsbGVAc2FudGUuZ291di5mciAuPC9wPgo8L2Jv
ZHk+PC9odG1sPgo=

--===============2114172985742389083==
Content-Type: application/octet-stream; Name="test.eml"
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="test.eml"

WC1Nb3ppbGxhLVN0YXR1czogMDAwMQ0KWC1Nb3ppbGxhLVN0YXR1czI6IDAwODAwMDAwDQpYLU1v
emlsbGEtS2V5czogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICANClRvOiB2aWN0aW1AdGVzdC5mcg0K
RnJvbTogb3RoZXJAdGVzdC5mcg0KU3ViamVjdDogZXhlDQpNZXNzYWdlLUlEOiA8OTUxZTU5Y2Mt
MjkzNS0zODNmLTI3YzAtZGVkOTI1MWRlODZmQHRlc3QuZnI+DQpEYXRlOiBUaHUsIDE2IEFwciAy
MDIwIDE0OjQwOjEyICswMjAwDQpYLU1vemlsbGEtRHJhZnQtSW5mbzogaW50ZXJuYWwvZHJhZnQ7
IHZjYXJkPTA7IHJlY2VpcHQ9MDsgRFNOPTA7IHV1ZW5jb2RlPTA7DQogYXR0YWNobWVudHJlbWlu
ZGVyPTA7IGRlbGl2ZXJ5Zm9ybWF0PTQNClVzZXItQWdlbnQ6IE1vemlsbGEvNS4wIChYMTE7IExp
bnV4IHg4Nl82NDsgcnY6NjAuMCkgR2Vja28vMjAxMDAxMDENCiBUaHVuZGVyYmlyZC82MC45LjAN
Ck1JTUUtVmVyc2lvbjogMS4wDQpDb250ZW50LVR5cGU6IG11bHRpcGFydC9taXhlZDsNCiBib3Vu
ZGFyeT0iLS0tLS0tLS0tLS0tRDhDMjU2NkJEOUJEMTI2MzZCNzY5QThGIg0KQ29udGVudC1MYW5n
dWFnZTogZW4tVVMNCg0KVGhpcyBpcyBhIG11bHRpLXBhcnQgbWVzc2FnZSBpbiBNSU1FIGZvcm1h
dC4NCi0tLS0tLS0tLS0tLS0tRDhDMjU2NkJEOUJEMTI2MzZCNzY5QThGDQpDb250ZW50LVR5cGU6
IHRleHQvaHRtbDsgY2hhcnNldD11dGYtOA0KQ29udGVudC1UcmFuc2Zlci1FbmNvZGluZzogN2Jp
dA0KDQo8aHRtbD4NCiAgPGhlYWQ+DQoNCiAgICA8bWV0YSBodHRwLWVxdWl2PSJjb250ZW50LXR5
cGUiIGNvbnRlbnQ9InRleHQvaHRtbDsgY2hhcnNldD1VVEYtOCI+DQogICAgPHRpdGxlPmV4ZTwv
dGl0bGU+DQogIDwvaGVhZD4NCiAgPGJvZHkgdGV4dD0iIzAwMDAwMCIgYmdjb2xvcj0iI0ZGRkZG
RiI+DQogICAgPHA+aGVsbG8hPGJyPg0KICAgIDwvcD4NCiAgPC9ib2R5Pg0KPC9odG1sPg0KDQot
LS0tLS0tLS0tLS0tLUQ4QzI1NjZCRDlCRDEyNjM2Qjc2OUE4Rg0KQ29udGVudC1UeXBlOiBhcHBs
aWNhdGlvbi94LW1zLWRvcy1leGVjdXRhYmxlOw0KIG5hbWU9ImhlbGxvLmV4ZSINCkNvbnRlbnQt
VHJhbnNmZXItRW5jb2Rpbmc6IGJhc2U2NA0KQ29udGVudC1EaXNwb3NpdGlvbjogYXR0YWNobWVu
dDsNCiBmaWxlbmFtZT0iaGVsbG8uZXhlIg0KDQpUVnFRQUFNQUFBQUVBQUFBLy84QUFMZ0FBQUFB
QUFBQVFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUENCkFBQUFBQUFBZ0FB
QUFBNGZ1ZzRBdEFuTkliZ0JUTTBoVkdocGN5QndjbTluY21GdElHTmhibTV2ZENCaVpTQnlkVzRn
YVc0Zw0KUkU5VElHMXZaR1V1RFEwS0pBQUFBQUFBQUFCUVJRQUFUQUVEQUI4eWwxNEFBQUFBQUFB
QUFPQUFBZ0VMQVFnQUFBUUFBQUFHDQpBQUFBQUFBQTNpTUFBQUFnQUFBQVFBQUFBQUJBQUFBZ0FB
QUFBZ0FBQkFBQUFBQUFBQUFFQUFBQUFBQUFBQUNBQUFBQUFnQUENCkFBQUFBQU1BUUlVQUFCQUFB
QkFBQUFBQUVBQUFFQUFBQUFBQUFCQUFBQUFBQUFBQUFBQUFBSkFqQUFCTEFBQUFBRUFBQUxBQw0K
QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUdBQUFBd0FBQUE4SXdBQUhBQUFBQUFBQUFBQUFBQUFB
QUFBQUFBQUFBQUFBQUFBDQpBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBSUFBQUNBQUFBQUFB
QUFBQUFBQUFDQ0FBQUVnQUFBQUFBQUFBQUFBQUFDNTANClpYaDBBQUFBNUFNQUFBQWdBQUFBQkFB
QUFBSUFBQUFBQUFBQUFBQUFBQUFBQUNBQUFHQXVjbk55WXdBQUFMQUNBQUFBUUFBQQ0KQUFRQUFB
QUdBQUFBQUFBQUFBQUFBQUFBQUFCQUFBQkFMbkpsYkc5akFBQU1BQUFBQUdBQUFBQUNBQUFBQ2dB
QUFBQUFBQUFBDQpBQUFBQUFBQVFBQUFRZ0FBQUFBQUFBQUFBQUFBQUFBQUFBREFJd0FBQUFBQUFF
Z0FBQUFDQUFVQWFDQUFBTlFDQUFBQkFBQUENCkFRQUFCZ0FBQUFBQUFBQUFBQUFBQUFBQUFBQUFB
QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQURZQQ0KY2dFQUFIQW9CQUFB
Q2dBcUhnSW9CUUFBQ2lvQUFFSlRTa0lCQUFFQUFBQUFBQXdBQUFCMk1pNHdMalV3TnpJM0FBQUFB
QVVBDQpiQUFBQVB3QUFBQWpmZ0FBYUFFQUFPd0FBQUFqVTNSeWFXNW5jd0FBQUFCVUFnQUFIQUFB
QUNOVlV3QndBZ0FBRUFBQUFDTkgNClZVbEVBQUFBZ0FJQUFGUUFBQUFqUW14dllnQUFBQUFBQUFB
Q0FBQUJSeFFBQUFrQUFBQUErZ0V6QUJZQUFBRUFBQUFHQUFBQQ0KQWdBQUFBSUFBQUFGQUFBQUF3
QUFBQUVBQUFBQkFBQUFBQUFLQUFFQUFBQUFBQVlBTkFBdEFBWUFXUUJHQUFzQWJRQUFBQVlBDQpu
QUI4QUFZQXZBQjhBQVlBMmdBdEFBQUFBQUFCQUFBQUFBQUJBQUVBQVFBUUFCa0FBQUFGQUFFQUFR
QlFJQUFBQUFDV0FEc0ENCkNnQUJBRjRnQUFBQUFJWVlRQUFPQUFFQUVRQkFBQklBSVFCQUFCZ0FL
UUJBQUE0QU1RRGlBQjBBQ1FCQUFBNEFMZ0FMQUNJQQ0KTGdBVEFDc0FMZ0FiQURRQUJJQUFBQUFB
QUFBQUFBQUFBQUFBQUFBQUdRQUFBQUlBQUFBQUFBQUFBQUFBQUFFQUpBQUFBQUFBDQpBQUFBQUFB
OFRXOWtkV3hsUGdCb1pXeHNiM2R2Y214a0xtVjRaUUJvWld4c2IzZHZjbXhrQUcxelkyOXliR2xp
QUZONWMzUmwNCmJRQlBZbXBsWTNRQVRXRnBiZ0F1WTNSdmNnQlRlWE4wWlcwdVJHbGhaMjV2YzNS
cFkzTUFSR1ZpZFdkbllXSnNaVUYwZEhKcA0KWW5WMFpRQkVaV0oxWjJkcGJtZE5iMlJsY3dCVGVY
TjBaVzB1VW5WdWRHbHRaUzVEYjIxd2FXeGxjbE5sY25acFkyVnpBRU52DQpiWEJwYkdGMGFXOXVV
bVZzWVhoaGRHbHZibk5CZEhSeWFXSjFkR1VBVW5WdWRHbHRaVU52YlhCaGRHbGlhV3hwZEhsQmRI
UnkNCmFXSjFkR1VBUTI5dWMyOXNaUUJYY21sMFpVeHBibVVBQUJkb0FHVUFiQUJzQUc4QUlBQjNB
RzhBY2dCc0FHUUFBQUFBQUI0TQ0KUlZsT2JWVkduc2xUSGFYYWptRUFDTGQ2WEZZWk5PQ0pBd0FB
QVFNZ0FBRUZJQUVCRVEwRUlBRUJDQVFBQVFFT0NBRUFCd0VBDQpBQUFBQ0FFQUNBQUFBQUFBSGdF
QUFRQlVBaFpYY21Gd1RtOXVSWGhqWlhCMGFXOXVWR2h5YjNkekFRQUFBQUFBSHpLWFhnQUENCkFB
QUNBQUFBTndBQUFGZ2pBQUJZQlFBQVVsTkVVKzBpVzVqS2IxOUNxV3BBbnVCRHpTc0JBQUFBWXpw
Y1ZYTmxjbk5jU1VWVg0KYzJWeVhHaGxiR3h2ZDI5eWJHUXVjR1JpQUFDNEl3QUFBQUFBQUFBQUFB
RE9Jd0FBQUNBQUFBQUFBQUFBQUFBQUFBQUFBQUFBDQpBQUFBQUFBQXdDTUFBQUFBQUFBQUFGOURi
M0pGZUdWTllXbHVBRzF6WTI5eVpXVXVaR3hzQUFBQUFBRC9KUUFnUUFBQUFBQUENCkFBQUFBQUFB
QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUJBQkFBQUFBWUFBQ0FB
QUFBQUFBQQ0KQUFBQUFBQUFBQUFCQUFFQUFBQXdBQUNBQUFBQUFBQUFBQUFBQUFBQUFBQUJBQUFB
QUFCSUFBQUFXRUFBQUZRQ0FBQUFBQUFBDQpBQUFBQUZRQ05BQUFBRllBVXdCZkFGWUFSUUJTQUZN
QVNRQlBBRTRBWHdCSkFFNEFSZ0JQQUFBQUFBQzlCTy8rQUFBQkFBQUENCkFBQUFBQUFBQUFBQUFB
QUFBQUEvQUFBQUFBQUFBQVFBQUFBQkFBQUFBQUFBQUFBQUFBQUFBQUFBUkFBQUFBRUFWZ0JoQUhJ
QQ0KUmdCcEFHd0FaUUJKQUc0QVpnQnZBQUFBQUFBa0FBUUFBQUJVQUhJQVlRQnVBSE1BYkFCaEFI
UUFhUUJ2QUc0QUFBQUFBQUFBDQpzQVMwQVFBQUFRQlRBSFFBY2dCcEFHNEFad0JHQUdrQWJBQmxB
RWtBYmdCbUFHOEFBQUNRQVFBQUFRQXdBREFBTUFBd0FEQUENCk5BQmlBREFBQUFBc0FBSUFBUUJH
QUdrQWJBQmxBRVFBWlFCekFHTUFjZ0JwQUhBQWRBQnBBRzhBYmdBQUFBQUFJQUFBQURBQQ0KQ0FB
QkFFWUFhUUJzQUdVQVZnQmxBSElBY3dCcEFHOEFiZ0FBQUFBQU1BQXVBREFBTGdBd0FDNEFNQUFB
QUVBQUR3QUJBRWtBDQpiZ0IwQUdVQWNnQnVBR0VBYkFCT0FHRUFiUUJsQUFBQWFBQmxBR3dBYkFC
dkFIY0Fid0J5QUd3QVpBQXVBR1VBZUFCbEFBQUENCkFBQW9BQUlBQVFCTUFHVUFad0JoQUd3QVF3
QnZBSEFBZVFCeUFHa0Fad0JvQUhRQUFBQWdBQUFBU0FBUEFBRUFUd0J5QUdrQQ0KWndCcEFHNEFZ
UUJzQUVZQWFRQnNBR1VBYmdCaEFHMEFaUUFBQUdnQVpRQnNBR3dBYndCM0FHOEFjZ0JzQUdRQUxn
QmxBSGdBDQpaUUFBQUFBQU5BQUlBQUVBVUFCeUFHOEFaQUIxQUdNQWRBQldBR1VBY2dCekFHa0Fi
d0J1QUFBQU1BQXVBREFBTGdBd0FDNEENCk1BQUFBRGdBQ0FBQkFFRUFjd0J6QUdVQWJRQmlBR3dB
ZVFBZ0FGWUFaUUJ5QUhNQWFRQnZBRzRBQUFBd0FDNEFNQUF1QURBQQ0KTGdBd0FBQUFBQUFBQUFB
QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB
DQpBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB
QUFBQUFBQUFBQUFBQUFBQUENCkFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB
QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQ0KQUFBQUFBQUFBQUFBQUFBQUFBQUFB
QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBDQpBQUFB
QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB
QUFBQUFBQUFBQUENCkFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB
QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQ0KQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB
QUFBQWdBQUFNQUFBQTRETUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBDQpBQUFBQUFBQUFB
QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB
QUFBQUENCkFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB
QUFBQUFBQUFBQUFBQUFBQUFBQUFBQQ0KQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB
QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBDQpBQUFBQUFBQUFBQUFBQUFB
QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEN
CkFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB
QUFBQUFBQUFBQUFBQUFBQQ0KQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB
QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBDQpBQUFBQUFBQUFBQUFBQUFBQUFBQUFB
QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUENCkFBQUFB
QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB
QUFBQUFBQUFBQQ0KQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFB
QUFBQUFBQUFBQUFBQUFBQUFBQQ0KLS0tLS0tLS0tLS0tLS1EOEMyNTY2QkQ5QkQxMjYzNkI3NjlB
OEYtLQ0K

--===============2114172985742389083==--
---------------END SAMPLE-------------

If you try to scan in rspamd (web UI), you dont lookup:
"MIME_BAD_ATTACHMENT (20) [exe]" because exe inside eml; mimetypes module dont parse eml or msg file.

**Comment by vstakhov** [comment]
`Content-Type: application/octet-stream` - it should be `message/rfc822` for .eml attachments. Mime types should already penalize such a situation (e.g. .eml attachment with a rubbish content-type). `message/rfc822` should be parsed properly.

**Comment by lprat** [comment]
Thank you for your reply! I tried and got a good result with 'message / rfc822'.
When you said: "Mime types should already penalize such a situation", can you explain to me the symbol that should be the trigger for that?
Thank.

**Comment by moisseev** [comment]
> When you said: "Mime types should already penalize such a situation", can you explain to me the symbol that should be the trigger for that?

`MIME_BAD_ATTACHMENT (1.6) [eml]`

**Comment by lprat** [comment]
Ok for "MIME_BAD_ATTACHMENT" but the default score is "4" * eml mimetype score (if I understood the principle correctly), in our case result is 1.6; but MIME_BAD_EXTENSION (exe == score 20) dont triggered (on "application/octet-stream")...

Compared to an exe's score, it is very low. If I increase the score of "MIME_BAD_ATTACHMENT", I'm afraid I will have a lot of false positives.

Rspamd recognizes eml, is it possible to force rspamd to act as "message/rfc822"? 
Thanks!

**Comment by vstakhov** [comment]
No, it is not possible.

**Comment by vstakhov** [comment]
But you can create a composite on this symbol + eml option with higher score.

**Comment by lprat** [comment]
The problem with composite on eml and BAD_ATTACHMENT is false positive, because eml can have a bad mime (ex: python script, ...) and the content is not dangerous. I still prefer to use Yara's rules.

I have tried with Outlook MSG attachment, and it looks like rspamd cannot parse (i tried with mimetype: "application/vnd.ms-outlook" => https://github.com/rspamd/rspamd/blob/d6f2dc67078d48e2623d5920e202c888300bd685/lualib/lua_magic/types.lua#L187)

For EML, i thinking 2 ways:
----
First way:
 - In test of bad_attachment (https://github.com/rspamd/rspamd/blob/a493c2ca1174571947d8e4c68f25e78d5422c80d/src/plugins/lua/mime_types.lua#L364) , set "ct" (mimetype rspamd reference for extension) in "state of file" for remplace wrong mimetype (octet-stream) (https://github.com/rspamd/rspamd/blob/a493c2ca1174571947d8e4c68f25e78d5422c80d/src/plugins/lua/mime_types.lua#L548)

I don't know if the change of mimetype at this time will allow the eml type to be parsed correctly (or if it's too late).

--- 
Second Way:
  - In set mimetype (https://github.com/rspamd/rspamd/blob/388dd3f53f65474c73cdeea675ce9569692da371/src/lua/lua_mimepart.c#L1295) for part, verify mimetype rspamd reference and change if not correct. I don't know if possible to keep "BAD_ATTACHMENT" symbol...

---
if the order allows it, the first solution is better I think...
What do you think?
Thank

**Comment by vstakhov** [comment]
There is nothing that you can do with yara and cannot do with Rspamd regular expressions with postfilters (see https://github.com/rspamd/rspamd/blob/master/rules/bitcoin.lua#L184 for example).

**Comment by lprat** [comment]
Sorry, when I say "yara" I mean yara with clamav! 

Because clamav extracts each embedded element (eml-> eml-> zip-> exe -> ...) and scans each extracted (embedded) file with each rules / signatures. 
In our case, clamav found exe inside eml and have a simple sig yara on PE header.

If you want to do like that with regex rspamd, it's just not possible, as you will have to extract EML, parse EML to extract the base64 file and identify "header PE"...

Good solution maybe "way1", I will try to modify the code to see. But second problem on "application/vnd.ms-outlook" => ".msg", I don't know!

**Comment by vstakhov** [comment]
> Good solution maybe "way1", I will try to modify the code to see. But second problem on "application/vnd.ms-outlook" => ".msg", I don't know!

It will be too late, so this 'way1' cannot work properly.

**Comment by lprat** [comment]
> It will be too late, so this 'way1' cannot work properly.

Ok thank for your help.I will think again!

**Comment by c-rosenberg** [comment]
Just as start you should be able to use https://rspamd.com/doc/lua/rspamd_mimepart.html#m8fa7a to get recursively the children mime_parts of attachments and maybe match them against a map. I think we also use used rspamd_task.load_from_string to get full access of an attached eml somehow.

Looking into attached mail structures is maybe a good addition to lua_content?

**Comment by vstakhov** [comment]
The main problem is to detect .eml/.msg signature. Probably add heuristic for .eml files with bogus Content-Type? @citrin do you have any thoughts on it - we have discussed it some time ago.

**Comment by lprat** [comment]
@c-rosenberg this is a possibility but if we can already use the include function when the content type of the message is "message / rfc822", it is better.

The problem maybe in function "lua_mimepart_is_message" https://github.com/rspamd/rspamd/blob/388dd3f53f65474c73cdeea675ce9569692da371/src/lua/lua_mimepart.c#L1742,  return is based on content-type?

**Comment by vstakhov** [comment]
It is not about lua_mimepart at all. It is about message detection by mime parser which sits deep in the core of Rspamd.
