### ISSUE TITLE
[BUG] rspamadm configwizard crashes

### ISSUE THREAD

**Issue by SWW13** [rspamd/rspamd#3489]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Running `rspamadm configwizard` on a fresh installation crashes.

```
Do you wish to continue?[Y/n]: 
Setup WebUI and controller worker:
Controller password is not set, do you want to set one?[Y/n]: n
Redis servers are not set:
The following modules will be enabled if you add Redis servers:
	* greylist
	* url_redirector
	* replies
	* neural
	* ratelimit
	* history_redis
Do you wish to set Redis servers?[Y/n]: n
Do you want to setup dkim signing feature?[y/N]: n

#0(main) lua_thread_str_error_cb: call to rspamadm lua script failed (2):
/usr/share/rspamd/lualib/lua_redis.lua:407: attempt to index local 'options' (a nil value); trace:
[1]:{/usr/share/rspamd/lualib/lua_redis.lua:491 - try_load_redis_servers [Lua]};
[2]:{/usr/share/rspamd/lualib/rspamadm//configwizard.lua:455 - check_redis_classifier [Lua]};
[3]:{/usr/share/rspamd/lualib/rspamadm//configwizard.lua:652 - setup_statistic [Lua]};
[4]:{/usr/share/rspamd/lualib/rspamadm//configwizard.lua:786 - <unknown> [Lua]};
```

### Steps to Reproduce
1. Install rspamd
1. Run `rspamadm configwizard`
3. Crash

**Expected behavior**
No crash.

### Versions
```
$ rspamadm configwizard
Rspamd daemon version 2.5
$ uname -a
Linux $HOST 5.8.8-arch1-1 #1 SMP PREEMPT Wed, 09 Sep 2020 18:59:45 +0000 x86_64 GNU/Linux
```

### Additional Information
Previously reported by someone else without any responses: https://github.com/rspamd/rspamd/issues/3181

**Comment by vstakhov** [comment]
Well, I've never ever tested Rspamd without Redis as in this case it's functionality is cut by like 90%. I also see no reasons to run Rspamd, and of course `configwizard`, without Redis. `configwizard` is also not aware of redis-less configurations...

**Comment by SWW13** [comment]
Seems reasonable, but then setting a Redis server should be mandatory or `configwizard` should print an error when Redis isn't configured.

Running `rspamadm configwizard` is the first thing mention in the quickstart guide after the installation. The question _"Do you wish to set Redis servers?[Y/n]:"_ implied for me that Redis is optional (only a handful of modules are said to be disabled) and a stack trace is not really meaningful.
