### ISSUE TITLE
Why is Exim not recommended for Rspamd?

### ISSUE THREAD

**Issue by ygoe** [rspamd/rspamd#3497]
The [quick start documentation](https://rspamd.com/doc/quickstart.html#preparation-steps) says:

> Exim MTA has a very limited support of Rspamd so it is not recommended to run Exim in conjunction with Rspamd.

Why is this? I couldn't find any issue with this anywhere. In fact the [integration provided](https://rspamd.com/doc/integration.html#integration-with-exim-mta) looks pretty solid to me. I'm in the process of replacing SpamAssassin with Rspamd for a new server (Ubuntu 20.04). And I'm not willing to replace Exim as well. I once tried to look at Postfix but found that it wasn't any better or easier than Exim so I stayed with Exim. It does all I need and has all the system integration I need.

So I'm interested in what won't work if I use Rspamd with Exim. Could you please make that clearer in the documentation? It sounds a bit vague like this and not very trustworthy.

**Comment by vstakhov** [comment]
Is it Rspamd issue? This is issue tracker, so unless it is not an bug report I close it.

**Comment by ygoe** [comment]
Is the documentation not part of the project? Sorry, I don't have Telegram or IRC.

**Comment by fatalbanana** [comment]
The mailing list is also an option.

Documentation is mostly at [rspamd.com repo](https://github.com/rspamd/rspamd.com).

The specific limitations of Exim's native Rspamd support so far (vs Postfix) is the inability to:

- Add/remove headers from Rspamd
- DKIM sign messages
- Use Rspamd's SMTP message
- Set MTA tag
- Maybe other stuff I'm not thinking of

Most of which will require support for HTTP+JSON, which is problematic for Exim (so unlikely this changes soon or at all).

For my purposes it works well enough.

**Comment by ygoe** [comment]
Mailing lists are the worst option of all, from an occasional user's perspective. Way too complicated to manage and inefficient to use.

Feel free to move this issue to the appropriate repository.

Thanks for the short explanation. That looks like it's not a real restriction and the documentation exaggerated things a bit.
