### ISSUE TITLE
[BUG] UI status page error

### ISSUE THREAD

**Issue by vixns** [rspamd/rspamd#3498]
**Describe the bug**

The UI status page fails to load data.

js console error :  

`Uncaught TypeError: can't access property "no action", data.actions is undefined         [...]              stats.js:276:37`

### Versions

2.6

**Comment by moisseev** [comment]
Would you find the response (or responses if you have multiple hosts in the cluster) on `GET` request(s) to `/stat` path  in the browser console and post it here?

**Comment by vixns** [comment]
`{"error":"Unauthorized"}`

Did I miss a configuration change when updating to version 2.6 ?

**Comment by HansVanEijsden** [comment]
I also had js errors and module errors after upgrading from 2.5 to 2.6 (Safari 14.0 (15610.1.28.1.9, 15610)).
Clearing the Safari browser cache helped in my case: no more errors and everything runs smoothly.

**Comment by urmel1960** [comment]
Had issues with firefox 81 after upgrade - clearing saved browser data and closing browser completly after cache clearing solved the issues.
All running fine in UI

**Comment by vstakhov** [comment]
That's another candidate to add to the upgrading notes.

**Comment by vixns** [comment]
It seems the UI try to fetch /stat without any headers before asking for the password, this call returns a 403 error, as expected.
After the password is entered, the /stat calls are well formated and returns this content

From a node: 
```json
{"version":"2.6","config_id":"REDACTED","uptime":19755,"read_only":false,"scanned":2782,"learned":153,"actions":{"reject":313,"soft reject":0,"rewrite subject":0,"add header":647,"greylist":372,"no action":1450},"spam_count":960,"ham_count":1822,"connections":5286,"control_connections":1812,"pools_allocated":7143,"pools_freed":7116,"bytes_allocated":31188552,"chunks_allocated":219,"shared_chunks_allocated":17,"chunks_freed":0,"chunks_oversized":1167,"fragmented":0,"total_learns":190204,"statfiles":[{"revision":128562,"used":0,"total":0,"size":0,"symbol":"BAYES_SPAM","type":"redis","languages":0,"users":121},{"revision":61642,"used":0,"total":0,"size":0,"symbol":"BAYES_HAM","type":"redis","languages":0,"users":381}],"fuzzy_hashes":{"rspamd.com":1403013953}}
```
from a proxy :
```json
{"version":"2.6","config_id":"REDACTED","uptime":19596,"read_only":false,"scanned":0,"learned":0,"spam_count":0,"ham_count":0,"connections":0,"control_connections":2263,"pools_allocated":98569,"pools_freed":98533,"bytes_allocated":28423904,"chunks_allocated":227,"shared_chunks_allocated":16,"chunks_freed":0,"chunks_oversized":1,"fragmented":0,"total_learns":0,"statfiles":[{"revision":0,"used":0,"total":0,"size":0,"symbol":"BAYES_SPAM","type":"redis","languages":0,"users":0},{"revision":0,"used":0,"total":0,"size":0,"symbol":"BAYES_HAM","type":"redis","languages":0,"users":0}],"fuzzy_hashes":{"rspamd.com":1403008934}}
```

The `actions` key is missing in the proxy response, this may be the js error's cause.

**Comment by moisseev** [comment]
@vixns Looks like the responses are from different nodes and the proxied response is actually from Rspamd 2.5 or later.

What is the "js error's cause"?

**Comment by vixns** [comment]
@moisseev The proxy host runs rspamd version 2.6

modify `stats.js` line 276  as follow fix this issue.
```
if (data.actions != undefined) neighbours_sum.actions[action] += data.actions[action];
```

**Comment by moisseev** [comment]
@vixns Sure, it does. But I'd like to know the reason why the `data.actions` is undefined.
The proxied and direct responses are too different. I am quite sure they are from different nodes.

**Comment by moisseev** [comment]
I've found the problem. Controller doesn't return the `actions` object until at least one message is scanned. I'll fix it in WebUI.
