### ISSUE TITLE
[enhancement] whois lookup support

### ISSUE THREAD

**Issue by AdUser** [rspamd/rspamd#350]
It would be nice to add a module to lookup whois base for sender domain. This will allow detect recently created domains and add some points to final score.
##

**Comment by fatalbanana** [comment]
Should be technically possible to implement a whois client with the [lua tcp module](https://rspamd.com/doc/lua/tcp.html) but I fear this would be prohibitively expensive (and that operators of the whois servers would not appreciate it).

Rspamd [currently has some limited support for this](https://github.com/vstakhov/rspamd/blob/rspamd-0.9/conf/modules.conf#L103) in the form of [spameatingmonkey.com's FRESH15 list](http://spameatingmonkey.com/lists.html#SEM-FRESH15).

Conceptually, as an antispam mechanism I am not fond of this - since it is a potential inconvenience to good senders while it's trivial for spammers to stockpile domains.

**Comment by msimerson** [comment]
In general, @fatalbanana is spot on, but I’ve conducted mass Whois queries against billions of domains for quite a few years (its part of a registry abuse reporting service). The solution to avoiding blacklisting is simple: be a good netizen and throttle your requests to each Whois server. 

The value of Whois data is associating domains with owners and/or registrars. Owner and registrar associations can be used for reputation engines that can predict “everything from owner A is spam” and “77% of domains from registrar B is spam.” Owners and registrar relationships are far fewer and much easier to track than domains. :-)

**Comment by klausenbusk** [comment]
Most of the false negative I experience seems to be from new domains. Today alone I received spam which wasn't detected from the following domains:
```
goidea.info: Creation Date: 2019-09-02T07:32:49Z (104.248.74.237)
gotgo.info: Creation Date: 2019-09-02T07:32:56Z (157.245.33.27)
shopsale.info: Creation Date: 2019-09-02T07:32:50Z (165.227.219.1)
riannehoeve.com: Creation Date: 2007-09-25T21:43:02Z (45.65.124.250)
openinvestment.info: Creation Date: 2019-09-02T07:33:38Z (165.22.82.163)
```
(The spam from *.info domains is probably the same spammer)

The IPs is already on some smaller blacklists (which rspamd doesn't use by default), so I assume they will end up on some bigger blacklists shortly. In this case I think a "domain age"-module could have been useful (if age <= 14 days reject), but as @fatalbanana says it is very easily to circumvent.

**Comment by tcutts** [comment]
If I were to implement this, I'd make the check twofold; firstly, newly registered domains should have a small score, if anything at all.  But checking who the registrar is, and in particular whether the registrant has been hidden behind a particular proxy should be a higher score.  Currently, for example, I'm getting a huge amount of spam through a large number of domains.   At the moment I'm blocking most of them with multimap based on the received header, which looks for the pattern that fortunately there is for the servers they're using behind the bazillions of domain names.  But one single thing ties them all together, they're all registered with NameCheap, and hidden behind namecheap's WhoisGuard proxy, which would be a very effective test, I suspect.

**Comment by klausenbusk** [comment]
I think it will be easier to use [RDAP](https://www.icann.org/rdap), but it is only supported by some registry.

**Comment by tcutts** [comment]
Certainly a standardised protocol like that would make it a great deal easier, yes.  Whois clearly isn't really designed for machine access.

**Comment by klausenbusk** [comment]
> I think it will be easier to use [RDAP](https://www.icann.org/rdap), but it is only supported by some registries.

So there are currently [1526](https://data.iana.org/TLD/tlds-alpha-by-domain.txt) TLDs and [1195](http://data.iana.org/rdap/dns.json) of them supports RDAP. All gTLD are [required](https://www.icann.org/en/system/files/files/legal-notice-implementation-rdap-service-27feb19-en.pdf) to support RDAP.

List of TLDs which dosn't support RDAP (all/most ccTLD I think, 331 total)
```
# comm -3 <(curl -s https://data.iana.org/TLD/tlds-alpha-by-domain.txt | tr '[:upper:]' '[:lower:]' | grep -v '^#' | sort) <(curl -s http://data.iana.org/rdap/dns.json | jq .services[][0][] -r | sort)
abudhabi
ac
ad
ae
aero
af
ag
ai
aigo
al
alstom
am
anquan
ao
aq
arab
arpa
as
at
au
aw
ax
az
ba
bb
bd
be
bf
bg
bh
bi
bj
bm
bn
bo
bond
bs
bt
bv
bw
by
bz
ca
cd
cf
cg
ch
ci
ck
cl
cm
cn
co
cu
cv
cw
cx
cy
de
dj
dk
dm
do
dubai
dz
ec
edu
ee
eg
er
es
et
eu
fi
firmdale
fj
fk
fm
fr
ga
gb
gdn
ge
gf
gg
gh
gi
gl
gm
gn
gov
gp
gq
gr
gs
gt
gu
gw
gy
hk
hm
hn
hr
ht
hu
id
ie
ifm
il
im
in
int
io
iq
ir
is
it
je
jm
jo
jp
ke
kg
kh
ki
km
kn
kp
kr
kw
kz
la
lb
lc
li
lk
lr
ls
lt
lu
lv
ly
ma
mc
md
me
mg
mh
mil
mk
ml
mm
mn
mo
mp
mq
mr
ms
mt
mtn
mu
mv
mw
mx
my
mz
na
nc
ne
nf
ng
ni
nl
no
nowruz
np
nr
nu
nz
om
pa
pars
pe
pf
pg
ph
pk
pl
pm
pn
pr
ps
pt
py
qa
re
ren
ro
rs
ru
rw
sa
sb
sc
sd
se
sg
sh
shia
shouji
si
sj
sk
sl
sm
sn
so
sr
ss
st
su
sv
sx
sy
sz
tc
tci
td
tf
tg
th
tj
tk
tl
tm
tn
to
tr
tt
tw
ua
ug
uk
us
uy
uz
va
vc
ve
vi
vn
vu
wf
win
ws
xihuan
xn--1qqw23a
xn--2scrj9c
xn--3ds443g
xn--3e0b707e
xn--3hcrj9c
xn--45br5cyl
xn--45brj9c
xn--54b7fta0cc
xn--55qx5d
xn--80ao21a
xn--90a3ac
xn--90ae
xn--90ais
xn--clchc0ea0b2g2a9gcd
xn--d1alf
xn--e1a4c
xn--fiq228c5hs
xn--fiqs8s
xn--fiqz9s
xn--fpcrj9c3d
xn--fzc2c9e2c
xn--gecrj9c
xn--h2breg3eve
xn--h2brj9c
xn--h2brj9c8c
xn--io0a7i
xn--j1amh
xn--j6w193g
xn--kprw13d
xn--kpry57d
xn--l1acc
xn--lgbbat1ad8j
xn--mgb9awbf
xn--mgba3a4f16a
xn--mgbah1a3hjkrd
xn--mgbai9azgqp6j
xn--mgbayh7gpa
xn--mgbbh1a
xn--mgbbh1a71e
xn--mgbc0a9azcg
xn--mgbca7dzdo
xn--mgberp4a5d4ar
xn--mgbgu82a
xn--mgbpl2fh
xn--mgbt3dhd
xn--mgbtx2b
xn--mgbx4cd0ab
xn--mgbaam7a8h
xn--mix891f
xn--ngbrx
xn--node
xn--o3cw4h
xn--ogbpf8fl
xn--p1acf
xn--p1ai
xn--pgbs0dh
xn--qxa6a
xn--qxam
xn--rvc1e0am3e
xn--s9brj9c
xn--vuq861b
xn--wgbh1c
xn--wgbl6a
xn--xhq521b
xn--xkc2al3hye2a
xn--xkc2dl3a5ee0h
xn--y9a3aq
xn--yfro4i67o
xn--ygbi2ammx
ye
yt
yun
za
zm
zw
```
