### ISSUE TITLE
unknown symbol SENDER_REP_HAM

### ISSUE THREAD

**Issue by tleuxner** [rspamd/rspamd#3500]
**Error Message**

`Oct  1 09:23:00 edi rspamd[9801]: <456200>; proxy; lua_task_insert_result_common: symbol insertion issue: unknown symbol SENDER_REP_HAM; trace: [1]:{/usr/share/rspamd/plugins/reputation.lua:80 - add_symbol_score [Lua]}; [2]:{/usr/share/rspamd/plugins/reputation.lua:424 - ipstats_check [Lua]}; [3]:{/usr/share/rspamd/plugins/reputation.lua:453 - continuation_cb [Lua]}; [4]:{/usr/share/rspamd/plugins/reputation.lua:915 - callback [Lua]}; [5]:{/usr/share/rspamd/lualib/lua_redis.lua:1296 - callback [Lua]}; [6]:{/usr/share/rspamd/lualib/lua_redis.lua:917 - <unknown> [Lua]};`

**Release**
2.6-156~buster

**Notes**
No custom configuration for reputation module present.

**Comment by HansVanEijsden** [comment]
You're not the only one, same problem here on all servers.
So, I decided to take a look at the website changes: perhaps there was a new config setting or something.
And indeed, it is: https://github.com/rspamd/rspamd.com/commit/ff43d0071fb3245324f19601a6952ea3f7edaf68
Long story short: you also need to define the scores in local.d/groups.conf now. See: https://rspamd.com/doc/modules/reputation.html

**Comment by vstakhov** [comment]
This should probably come to the upgrading notes.

**Comment by tleuxner** [comment]
I have added these to local.d/groups.conf based on the example Hans referenced:
```
        "SENDER_REP_HAM" {
            weight = 1.0;
        }

        "SENDER_REP_SPAM" {
            weight = 2.0;
        }
```
I noticed all the other symbols in the example use REPUTATION, these two are the only ones using REP. For cleanness, shouldn't the reputation symbols be referenced via an _include_ from the main groups.conf like the other symbols?

**Comment by vstakhov** [comment]
I have added that to the upgrading notes, thanks.

**Comment by kroerig** [comment]
when running 'conftest' I get:
`symbol 'SENDER_REP_SPAM' has its score defined but there is no corresponding rule registered
symbol 'SENDER_REP_HAM' has its score defined but there is no corresponding rule registered
`
What's missing?
