### ISSUE TITLE
[BUG] dkim_singining will fail for path_map where the path is valid base64

### ISSUE THREAD

**Issue by dtugend** [rspamd/rspamd#3512]
Probably somewhere the key_fromat needs to be set properly instead, since this code won't safe it from being unset if it's valid base64:
https://github.com/rspamd/rspamd/blob/53daa246944b73d015d8e8eea5646a5f9c7a81be/src/plugins/dkim_check.c#L641

I personaly worked around it by inserting a redundant `/.` at the front for the absolute paths, that will work since `.` is not valid base64 unlike `/`.

**Comment by vstakhov** [comment]
Well, if you name your keys using base64 characters with no `.` or `/` in the name then I can only assume that you are trying to do something very strange. I doubt there is anything to fix here: just don't do it in this way.

**Comment by dtugend** [comment]
As I indicated above `/` is a base64 character, I am not doing anything weird here imho, see https://en.wikipedia.org/wiki/Base64#Base64_table

**Comment by vstakhov** [comment]
I usually use extensions for files (so `.` character is essential).

**Comment by dtugend** [comment]
Thank you for your replies.
I understand that rpsamd is open source and free and people are wellcome to try to contribute patches.
I'd try to argue that file name extensions is not inherently a Linux concept and they are just merely cosmetic, but then you would rightfully point out that many config scripts sort of relay on it (for example .conf files in .d folders).
I will try to make time to check if it's possible for me to try to contribute a patch for me (currently don't see that happening yet sadly though).

Until then people with same problem can just use the same workaround like me (prefixing with `/.` I guess :)

**Comment by vstakhov** [comment]
The only thing I can suggest is to check if the length of the input is divisable by 4. Or do full base64 decoding and checking of asn.1 signatures. The first option is trivial but might not be enough to fix the issue completely.

**Comment by vstakhov** [comment]
Actually, it was a hack as is. And there are `rawkey`/`key` parameters that are intended to distinguish these forms of keys. Unfortunately, there are other places in dkim signing code that distinguish base64/file, e.g. here: https://github.com/rspamd/rspamd/blob/master/lualib/lua_dkim_tools.lua#L280
So I really don't know how to fix them all without breaking compatibility.
