### ISSUE TITLE
[BUG] Spamtrap Module not learning bayes if action is set explicitly

### ISSUE THREAD

**Issue by TPWareHouseManager** [rspamd/rspamd#3516]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
If you activate spamtrap module in rspamd 2.6 on debian, bayes filter is not trained if you set action = "no action" explicitly
### Steps to Reproduce

1. Enable Spamtrap module with this configuration

learn_spam = true;
enabled = true;
action = "no action";
score = 1.0;
map = file://$LOCAL_CONFDIR/local.d/spamtrap.map

2. Configure map with regex
/^mail_address@domain\.tld/

3. Send Mail to mail_address@domain.tld and verify bayes learning in the WebUI

- You will see in History that SPAMTRAP symbol is added to the mail

- Bayes learns will not increase.

- you can see in the logs
2020-10-11 22:28:58 #14557(normal) <61ddee>; task; rspamd_task_process: learn error: Cannot learn statistics when passthrough result has been set; not classified

**Expected behavior**
Bayes learns are increasing by 1 for each spamtrapped mail

### Versions

Rspamd daemon version 2.6

Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

CPU
Intel Xeon Processor (Skylake, IBRS)

### Additional Information

If you comment the lines

#action = "no action"
#score = 1.0

The passthrough error is not logged, bayes learn works and you can see in the debug log of spamtrap 
default: F (no action)

The documentation clearly states bayes learns should work with action and score set explicitly:
https://rspamd.com/doc/modules/spamtrap.html

**Comment by vstakhov** [comment]
It is working as intended. Bayes learning and many other things that rely on full message analysis are disabled if you set passthrough result.

**Comment by TPWareHouseManager** [comment]
Thank you for the clarification. I might propose a change in the documentation. What is the purpose of spamtrap module with defined action setting passthrough result, if the message is not learned as spam?

**Comment by vstakhov** [comment]
I agree, that this passthrough stuff might be confusing. I have one idea to improve it, so I would probably implement it at some point.

**Comment by heraklit256** [comment]
Thanks, I just stumbled across this. :-)

**Comment by TPWareHouseManager** [comment]
I have noticed that there are messages with SPAMTRAP symbol being rejected. If I set action = "no action" in spamtrap module, bayes is not being learned. How can I prevent rejection in some other way? It feels like rejecting spamtrapped mails kind of beats the purpose of a spamtrap address. Am I missing something?
