### ISSUE TITLE
[Feature] User setting require symbols

### ISSUE THREAD

**Issue by GieltjE** [rspamd/rspamd#3517]
## Summary
According to https://rspamd.com/doc/configuration/settings.html there is no way to require/deny a set of symbols, it only allows  for modifying the score or adding them.

## Motivation
This would be highly usefull for somewhat more reliable whitelisting, e.g. require R_DKIM_ALLOW/DKIM_SIGNED or deny when R_DKIM_REJECT is specified in conjunction with a required from address.

## Describe alternatives you've considered
Couldn't think of any.

## Additional context
Am I right in thinking that adding multiple "from" lines will allow any of the supplied from addresses?

**Comment by vstakhov** [comment]
There are composite rules for that purposes.

**Comment by GieltjE** [comment]
Am I correct that you are refering to: https://rspamd.com/doc/tutorials/writing_rules.html ?

If so adding the mentioned options to the "basic" settings would allow configuration via http with a lot more flexibility.

**Comment by fatalbanana** [comment]
https://rspamd.com/doc/configuration/composites.html

Settings is probably not an ideal way to handle whitelisting in the general case, maybe whitelist module is interesting: https://rspamd.com/doc/modules/whitelist.html ; or multimap: https://rspamd.com/doc/modules/multimap.html ; see also force actions module: https://rspamd.com/doc/modules/force_actions.html

**Comment by GieltjE** [comment]
Indeed multimap + composites does the trick:

local.d/multimap.conf:
```
WHITELISTED_REQUESTED {
  description = "Local whitelists";
  type = "combined";
  rules {
    addr {
      map = "/etc/rspamd/local.d/multimap-users.list";
      selector = "from:addr";
    }
    domain {
      map = "/etc/rspamd/local.d/multimap-domains.list";
      selector = "from:domain";
    }
  }
  expression = "addr || domain"
  require_symbols = "R_SPF_ALLOW & R_DKIM_ALLOW"
}
```
local.d/composites.conf
```
WHITELIST_SPF_DKIM_REQUESTED {
  expression = "WHITELISTED_REQUESTED";
  score = -100;
}
```

This functions fine (adds the correct WHITELIST_SPF_DKIM_REQUESTED header with a score of -100), however this would not be translatable to a situation where there is a per recipient whitelist, or is it possible to use the rcpt address in the map filename?

currently we have a lot of emails that we keep learning but always trigger the spam filter no matter how many times they are learned (nearly all are legit but bulk mail without a correct layout).
Spamassassin used to have an auto white list plugin, e.g. if a user learned it a few times as ham it would be auto whitelisted, is such a module possible/in the works?

**Comment by fatalbanana** [comment]
> is it possible to use the rcpt address in the map filename?

No; the way to deal with it could be to generate sender/recipient pairs using selector and look those up in a common map. If users are not suitably batched by the MTA it could behave in unexpected ways (so you should somehow ensure that if you accept a message for > 1 recipient that those recipients share common policy; or scans should be done per-recipient after receipt of the message).

> currently we have a lot of emails that we keep learning but always trigger the spam filter no matter how many times they are learned (nearly all are legit but bulk mail without a correct layout).

It's best to deal with that directly (eg. drop scoring for problem symbols) - or perhaps whitelist/add negative scoring to those senders globally.

>  Spamassassin used to have an auto white list plugin, e.g. if a user learned it a few times as ham it would be auto whitelisted, is such a module possible/in the works?

It's possible. If you want to hook on learning you could abuse `learn_condition`.

> Finally would it make sense to add this as an example config somewhere?

I expect there are some floating around on the web. I'd like to see one with warnings about batching & suggestions about how to correctly implement that.
