### ISSUE TITLE
[BUG] Suspicious URL: maps.google.com

### ISSUE THREAD

**Issue by azurit** [rspamd/rspamd#3525]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

Some of e-mails are getting lots of points because they contain URL https://maps.google.com. Relevant part of the rspamd header:
R_SUSPICIOUS_URL(5.00)[maps.google.com];

### Versions

```
# rspamd --version
Rspamd daemon version 2.6
```

Debian Buster, 64bit.

**Comment by vstakhov** [comment]
This rule works not on domains but on a specific form of URLs. I need a full url (probably anonymized if relevant) with `<a href=...>content</a>` parts (both href and content).

**Comment by azurit** [comment]
I see two versions of it (i copied it directly from maildir file format so it's a little encoded, sorry).

text/plain:
```
<https://maps.google.com/?q=3DPribinova+25%C2%A0+%0D+811+09%C2%A0Bratislava=
+%0
D+Slovak+Republic&entry=3Dgmail&source=3Dg> Bratislava
```

text/html:
```
<a href=3D"https://maps.google.com/?q=3DPribinova+25%C2%A0+%0D+811+09%C2%=
A0Bratislava+%0D+Slovak+Republic&amp;entry=3Dgmail&amp;source=3Dg"><span st=
yle=3D'color:#0563C1'>Bratislava</span></a>
```

**Comment by vstakhov** [comment]
Yes, these url's have some bad characters: e.g. `\r`. That's why Rspamd marks it as suspicious.

**Comment by azurit** [comment]
Thank you.
