### ISSUE TITLE
[BUG] symbol insertion issue unknown symbol

### ISSUE THREAD

**Issue by aletheia7** [rspamd/rspamd#3527]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
The journal shows the following info message with correct syntax in settings.conf.
```    
...
Oct 21 16:48:12 mail rspamd[183616]: <8047d3>; lua; settings.lua:363: <4CGnHc1Dpjz1mbTf@example.com.com> apply static settings example (id = 1489247326); header:From matched; priority low
Oct 21 16:48:12 mail rspamd[183616]: <8047d3>; proxy; lua_task_insert_result_common: symbol insertion issue: unknown symbol REJECT_EXAMPLE; trace: [1]:{/usr/share/rspamd/plugins/settings.lua:383 - fun [Lua]}; [2]:{/usr/share/rspamd/lualib/fun.lua:34 - call_if_not_empty [Lua]}; [3]:{/usr/share/rspamd/lualib/fun.lua:192 - each [Lua]}; [4]:{/usr/share/rspamd/plugins/settings.lua:382 - <unknown> [Lua]};   
...
```
### Steps to Reproduce

1. Make a settings.conf entry:
```
example {
        header = {
                "From" = "/@example\.com/i";
        }
        apply {
                REJECT_EXAMPLE = 99;
        }
        symbols [
                "REJECT_EXAMPLE"
        ]
}
```
2. ```rspamadm configtest && systemctl reload rspamd```
3. Send an email that matches the settings rule.

**Expected behavior**
The log messages should not appear. The syntax is valid because ```rspamadm configtest``` is OK.

### Versions
Rspamd daemon version 2.6
Operating System: Debian GNU/Linux bullseye/sid
Kernel: Linux 5.7.0-3-amd64
Architecture: x86-64
apt: deb [arch=amd64] http://rspamd.com/apt-stable/ buster main

### Additional Information
Although the confusing info messages appear, the symbol REJECT_EXAMPLE still gets defined.

**Comment by vstakhov** [comment]
You are doing things in a wrong way. I'm not inclined to explain that in details in a bug tracker but it is apparently not an Rspamd issue.
