### ISSUE TITLE
[BUG] owner= ignored in bind_socket

### ISSUE THREAD

**Issue by GieltjE** [rspamd/rspamd#3528]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
The owner= is ignored, the socket is created with user and group _rspamd, worse if the socket is to be created in a directory that is owned by the owner= it just gives:
```
2020-10-22 11:57:20 #218891(main) <ef543c>; main; spawn_workers: cannot listen on normal socket /var/spool/postfix/private/rspamd mode=0666 owner=postfix: Permission denied
2020-10-22 11:57:20 #218891(main) <ef543c>; main; spawn_workers: cannot create listen socket for rspamd_proxy at /var/spool/postfix/private/rspamd mode=0666 owner=postfix
```

### Steps to Reproduce

1. Edit override.d/worker-proxy.inc: bind_socket = "/var/spool/postfix/private/rspamd mode=0666 owner=postfix";
2. Add _rspamd user to postfix group
3. Restart rspamd

**Expected behavior**
A socket should be made that is owned by postfix

### Versions

Rspamd daemon version 2.6, Debian testing

**Comment by vstakhov** [comment]
Do you run Rspamd `main` process as root?

**Comment by GieltjE** [comment]
No, using the rspamd.com debian packages.

**Comment by vstakhov** [comment]
How do you imagine then that Rspamd is able to set owner on an arbitrary file in your FS without root permissions?

**Comment by GieltjE** [comment]
Usualy a service is started as root and drops after.

**Comment by vstakhov** [comment]
Then start it as root, what is the problem?

**Comment by GieltjE** [comment]
That it's a common ability for apps to drop their own permissions after they're done with the parts that require root in order to make the appropriate sockets and maintain security.

**Comment by vstakhov** [comment]
There is such an ability in Rspamd from the very beginning of the project. Just run it from a root user specifying `-u _rspamd -g _rspamd` so main process will run as root and worker process would drop privs.

**Comment by GieltjE** [comment]
That's the default way in which I am running it, calling /etc/init.d/rspamd start as root with the unexpected results of the above socket problems.

**Comment by army1349** [comment]
> 
> 
> That's the default way in which I am running it, calling /etc/init.d/rspamd start as root with the unexpected results of the above socket problems.

Are you on FreeBSD?

**Comment by army1349** [comment]
This is also issue on FreeBSD caused by rc file using ${rspamd_user}, ${rspamd_group} and default start_cmd.

**Comment by GieltjE** [comment]
I'm on Debian.

**Comment by vstakhov** [comment]
Is it Rspamd issue that you run it not as root? I see no glue in this issue.

**Comment by vstakhov** [comment]
I think we need @moisseev opinion on that.

**Comment by moisseev** [comment]
@army1349 I am not following you. The rc script does not forces anything, but has its defaults. You can redefine `rspamd_user` and `rspamd_group` in `/etc/rc.conf` if you need.

**Comment by army1349** [comment]
@moisseev If you define `rspamd_user`, and not define `start_cmd`, default method will be used (see `run_rc_command` in `/etc/rc.subr`), which will use `su`, to run `command` with `command_args` as user defined in `rspamd_user`.

**Comment by moisseev** [comment]
I am still not following you. What is wrong with the default method?
```
# grep rspamd /etc/rc.conf
rspamd_enable="YES"
rspamd_user="root"
# service rspamd start
Starting rspamd.
# ps -waux | grep rspamd
root    95425    8,0  3,7 182640 115012  -  S    14:26         0:00,02 rspamd: controller process (*:11334) (rspamd-2.7)
root    95426    8,0  3,7 153964 114764  -  S    14:26         0:00,02 rspamd: hs_helper process (rspamd-2.7)
root    95422    7,0  3,7 153964 114764  -  Ss   14:26         0:00,03 rspamd: main process (rspamd-2.7)
root    95423    7,0  3,7 181860 114916  -  S    14:26         0:00,02 rspamd: fuzzy process (localhost:11335) (rspamd-2.7)
root    95424    7,0  3,7 181860 114916  -  S    14:26         0:00,02 rspamd: rspamd_proxy process (localhost:11332) (rspamd-2.7)
root    95428    0,0  0,1  11500   2620  1  S+   14:26         0:00,00 grep rspamd
```

**Comment by army1349** [comment]
This way you can't run main process as root and workers as different user.
Using `-u ${rspamdd_user}` has no effect, if you run `rspamd` binary as `rspamdd_user`.

**Comment by GieltjE** [comment]
That in the end running the main rspamd as root is unwanted, but it is required during startup to drop the socket.

**Comment by moisseev** [comment]
@army1349, @vstakhov What do you think about this change in the rc script?
```diff
--- rspamd.orig 2020-11-06 15:16:55.246332000 +0300
+++ rspamd      2020-11-06 15:35:24.604163000 +0300
@@ -26,8 +26,8 @@
 load_rc_config $name

 : ${rspamd_enable:="NO"}
-: ${rspamd_user="rspamd"}
-: ${rspamd_group="rspamd"}
+: ${rspamd_run_user="rspamd"}
+: ${rspamd_run_group="rspamd"}
 : ${rspamd_flags="-c /usr/local/etc/rspamd/rspamd.conf"}

 pidfile=${rspamd_pidfile:-"/var/run/rspamd/rspamd.pid"}
@@ -40,7 +40,7 @@
 reopenlog_cmd="reopenlog_cmd"

 required_files=/usr/local/etc/rspamd/rspamd.conf
-command_args="-u ${rspamd_user} -g ${rspamd_group}"
+command_args="-u ${rspamd_run_user} -g ${rspamd_run_group}"
 extra_commands="reload configtest reopenlog"
 stop_postcmd="rm -f $pidfile"
 sig_reload="HUP"
```

**Comment by army1349** [comment]
I like it. I would maybe call it `rspamd_worker_user`, but that is just matter of taste.

**Comment by vstakhov** [comment]
That makes sense indeed.

**Comment by vstakhov** [comment]
The problem might happen for users who have set a custom rspamd_user, so a corresponding pkg-message will likely be needed.

**Comment by army1349** [comment]
There would be no change of behavior for `rspamd_user`, but pkg-message could inform about new possibility to set worker user.

**Comment by fatalbanana** [comment]
@GieltjE this is how to start rspamd as root on Debian:
Create `/etc/systemd/system/rspamd.service.d/overlay.conf` with contents as below:
```
[Service]
ExecStart=
ExecStart=/usr/bin/rspamd -u _rspamd -g _rspamd -c /etc/rspamd/rspamd.conf -f
User=root
```
Do `systemctl daemon-reload ; systemctl restart rspamd`

**Comment by moisseev** [comment]
@vstakhov , @army1349  [Bug 250904](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=250904)

**Comment by GieltjE** [comment]
> 
> 
> @GieltjE this is how to start rspamd as root on Debian:
> Create `/etc/systemd/system/rspamd.service.d/overlay.conf` with contents as below:
> 
> ```
> [Service]
> ExecStart=
> ExecStart=/usr/bin/rspamd -u _rspamd -g _rspamd -c /etc/rspamd/rspamd.conf -f
> User=root
> ```
> 
> Do `systemctl daemon-reload ; systemctl restart rspamd`

Works like a charm 👍
