### ISSUE TITLE
[BUG] DKIM Signing always uses basedomain, subdomain is ignored

### ISSUE THREAD

**Issue by GieltjE** [rspamd/rspamd#3531]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
A DKIM signature contains the domain and the selector, when sending from a subdomain (e.g. info@test.domain.nl) instead of just the domain (e.g. info@domain.nl) the domain part of the header should contain the full subdomain.

Current: DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=domain.nl; s=_dkim; t=1603366680;
Should be: v=1; a=rsa-sha256; c=relaxed/relaxed; d=test.domain.nl; s=_dkim; t=1603366680;

### Steps to Reproduce

1. Set up DKIM signing
2. Set up a subdomain or send using PHP or similar
3. View the headers of the received mail or send it to gmail and have it bounced back

**Expected behavior**
The subdomain part is included in the domain part.

### Versions

Rspamd daemon version 2.6, Debian testing.

### Additional Information

All DKIM signing tools I worked with at least allow this, as this is often used for specialised marketing or billing providers.

**Comment by andryyy** [comment]
What about your config?

**Comment by vstakhov** [comment]
Please read https://rspamd.com/doc/modules/dkim_signing.html searching for `use_esld` string. Not an Rspamd issue.

**Comment by xdkaka** [comment]
why make root domain and subdomain differnt ......
When I add use_esld = false;   Mail retrun DKIM： | 'FAIL'
When I add use_esld = true;   Mail contain not DKIM and vefify fail too

**Comment by xdkaka** [comment]
why make root domain and subdomain differnt ......
When I add use_esld = false; Mail retrun DKIM： | 'FAIL'
When I add use_esld = true; Mail contain not DKIM and vefify fail too

**Comment by xdkaka** [comment]
> Please read https://rspamd.com/doc/modules/dkim_signing.html searching for `use_esld` string. Not an Rspamd issue.

why make root domain and subdomain differnt ......
When I add use_esld = false; Mail retrun DKIM： | 'FAIL'
When I add use_esld = true; Mail contain not DKIM and vefify fail too


"xxx.com.cn    or      xxx.co.jp" root domain or subdomain ?

**Comment by CompuRoot** [comment]
After setting

> use_esld = false;

DKIM signing correctly both primary domain as well subdomains, but you have to add appropriate DNS records for subdomain too as well add in configuration
```
domain {
 subdomain.example.com {
    path = "/var/lib/rspamd/dkim/some-selector.subdomain.example.com.dkim.key";
    selector = "some-selector";
  }
}
```
