### ISSUE TITLE
[BUG] bitcoin.lua - bad argument

### ISSUE THREAD

**Issue by jendis** [rspamd/rspamd#3533]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
When email containing bitcoin address is scanned:
`2020-10-27 20:53:27 #7500(controller) <330dbb>; csession; rspamd_re_cache_check_lua_condition: cannot call for re_cache_check_lua_condition for re \b[13LM][1-9A-Za-z]{25,34}\b: error when calling lua fun
ction from /var/tmp/portage/mail-filter/rspamd-2.6-r1/work/rspamd-2.6/src/libserver/re_cache.c:567: /usr/share/rspamd/rules/bitcoin.lua:190: bad argument #2 to 'str_trim' (string expected, got userdata);
 trace: [1]:{[C]:-1 - str_trim [C]}; [2]:{/usr/share/rspamd/rules/bitcoin.lua:190 - <unknown> [Lua]};`

### Steps to Reproduce
Create an empty file named _sample.eml_ and put string like bitcoin address e.g. _15rHFEZqt1dJb8eBwCxA4Fnd1K8uWYQCi8_.
Run `rspamc sample.eml`.
See logs, you'll find an error there.
Works for any email containing bitcoin address.

**Expected behavior**
No errors.

### Versions
Rspamd version 2.6.
Running on gentoo, installed by latest ebuild 2.6-r1.

**Comment by jendis** [comment]
Found another similar issue:
`2020-10-29 13:58:51 #40735(main) <rwzsya>; map; lua_map_fin: call to map fin function failed (2): /usr/share/rspamd/plugins/phishing.lua:438: bad argument #2 to 'rspamd_str_split_fun' (string expected, got userdata); trace: [1]:{[C]:-1 - rspamd_str_split_fun [C]}; [2]:{/usr/share/rspamd/plugins/phishing.lua:438 - <unknown> [Lua]};
`

**Comment by vstakhov** [comment]
It seems you are using system lpeg somehow.

**Comment by vstakhov** [comment]
Not an Rspamd issue most likely - there is definitely an issue with your build. System LPEG is not supported by Rspamd - you have to use bundled modified lpeg version for proper functioning.

**Comment by jendis** [comment]
Thanks, it seems that problem is in a gentoo package.
Closing this issue.

**Comment by vstakhov** [comment]
It seems that the packagers have tried to decouple some of the embedded dependencies from Rspamd to system ones. It is presumably my fault - I have updated https://github.com/rspamd/rspamd/blob/master/contrib/DEPENDENCY_INFO.md to denote which contrib libraries have been modified in Rspamd (so they should not be decoupled).
