### ISSUE TITLE
[BUG] symbol insertion issue

### ISSUE THREAD

**Issue by jendis** [rspamd/rspamd#3534]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
We observe following log lines`
2020-10-27 20:53:27 #7500(controller) <330dbb>; csession; lua_task_insert_result_common: symbol insertion issue: unknown symbol FORGED_SENDER; trace: [1]:{/usr/share/rspamd/plugins/forged_recipients.lua:
145 - <unknown> [Lua]};
`
`2020-10-27 20:53:27 #7500(controller) <330dbb>; csession; lua_task_insert_result_common: symbol insertion issue: unknown symbol ONCE_RECEIVED; trace: [1]:{/usr/share/rspamd/plugins/once_received.lua:144 
- <unknown> [Lua]};`

### Steps to Reproduce
Fresh installation of rspamd-2.6
No configuration in local.d/* regarding to the symbols _ONCE_RECEIVED_ or _FORGED_SENDER_.
configtest says:
> dev /home/jsmutny # rspamadm configtest
> 2020-10-28 10:38:12 #0(main) <>; lua; lua_cfg_transform.lua:242: conflicting names in surbl and rbl rules: SURBL_MULTI, prefer surbl rule!
> 2020-10-28 10:38:12 #0(main) <>; lua; lua_cfg_transform.lua:242: conflicting names in surbl and rbl rules: URIBL_MULTI, prefer surbl rule!
> 2020-10-28 10:38:12 #0(main) <>; lua; lua_cfg_transform.lua:242: conflicting names in surbl and rbl rules: RSPAMD_URIBL, prefer surbl rule!
> 2020-10-28 10:38:12 #0(main) <>; lua; lua_cfg_transform.lua:242: conflicting names in surbl and rbl rules: SEM_URIBL_FRESH15_UNKNOWN, prefer surbl rule!
> 2020-10-28 10:38:12 #0(main) <>; lua; lua_cfg_transform.lua:242: conflicting names in surbl and rbl rules: DBL, prefer surbl rule!
> 2020-10-28 10:38:12 #0(main) <x9err6>; cfg; rspamd_init_filters: requested unknown module spf
> 2020-10-28 10:38:12 #0(main) <x9err6>; cfg; rspamd_init_filters: requested unknown module surbl
> 2020-10-28 10:38:12 #0(main) <x9err6>; symcache; rspamd_symcache_validate: symbol 'BLACKLIST_DMARC' has its score defined but there is no corresponding rule registered
> 2020-10-28 10:38:12 #0(main) <x9err6>; symcache; rspamd_symcache_validate: symbol 'BLACKLIST_DKIM' has its score defined but there is no corresponding rule registered
> 2020-10-28 10:38:12 #0(main) <x9err6>; symcache; rspamd_symcache_validate: symbol 'BLACKLIST_SPF' has its score defined but there is no corresponding rule registered
> 2020-10-28 10:38:12 #0(main) <x9err6>; symcache; rspamd_symcache_validate: symbol 'ARC_ALLOW' has its score defined but there is no corresponding rule registered
> 2020-10-28 10:38:12 #0(main) <x9err6>; symcache; rspamd_symcache_validate: symbol 'ARC_INVALID' has its score defined but there is no corresponding rule registered
> 2020-10-28 10:38:12 #0(main) <x9err6>; symcache; rspamd_symcache_validate: symbol 'ARC_DNSFAIL' has its score defined but there is no corresponding rule registered
> 2020-10-28 10:38:12 #0(main) <x9err6>; symcache; rspamd_symcache_validate: symbol 'ARC_NA' has its score defined but there is no corresponding rule registered
> 2020-10-28 10:38:12 #0(main) <x9err6>; symcache; rspamd_symcache_validate: symbol 'ARC_REJECT' has its score defined but there is no corresponding rule registered
> 2020-10-28 10:38:12 #0(main) <x9err6>; symcache; rspamd_symcache_validate: symbol 'BLACKLIST_SPF_DKIM' has its score defined but there is no corresponding rule registered

but it shouldn't affect problematic symbols mentioned above.

**Expected behavior**
Rules with those symbols should work properly with no issues.

### Versions
rspamd-2.6

**Comment by ser** [comment]
this bug persists already 6 years
