### ISSUE TITLE
[Feature] Per user whitelist based on contact list

### ISSUE THREAD

**Issue by plinss** [rspamd/rspamd#3536]
## Summary

Have a module that can query a per-recipient contact list for whitelisting purposes.

## Motivation

Some email services allow whitelisting senders that are on a user's contact list. This is common enough that many services that allow sign ups recommend users add them to their contact list to prevent being treated as spam.

It would be nice to be able to integrate an external contact list, for example a CardDAV server or an LDAP directory that could be configured to generate whitelist scores.

Given the various possibilities of how contacts are stored and managed, this could be implemented as a per-recipient redis lookup and independent services can be built to sync contact lists to the redis server.

## Describe alternatives you've considered

I may be missing something, but existing whitelist functionality doesn't seem to be able to have per-recipient whitelists and are based on sender domains rather than specific sender addresses

**Comment by fatalbanana** [comment]
Most recently discussed [here](https://github.com/rspamd/rspamd/issues/3517). It's possible to use multimap or abuse settings for this purpose. The main problem is it will work in unexpected ways without suitable MTA configuration (if MTA will accept >1 recipient per message, are those recipients batched suitably?).
