### ISSUE TITLE
Mailchimp: Prevent SPOOFED_UNAUTH

### ISSUE THREAD

**Issue by ddeenniiss** [rspamd/rspamd#3541]
**Describe the bug**
Despite a dns configuration that seems to be correct, my mailing sent from mailchimp are rejected for @domain.tld addresses . 

The mailing is sent with

From: xxx@domain.tld
Reply-To: <us10-e309f52506-131f943aea@inbound.mailchimp.com>

 [75.79/15.00] [SPOOFED_UNAUTH(50.00){},POLICY_FAILURE(10.00){},NEURAL_SPAM_LONG(3.70){1.000;},FORGED_W_BAD_POLICY(3.00){},BAYES_SPAM(2. 50){100.00%;},BAD_REP_POLICIES(2.00){},DMARC_POLICY_SOFTFAIL(2.00){domain.tld: SPF not aligned (relaxed), DKIM not aligned (relaxed);none;

My dns config for domain.tld

SPF 
v=spf1 a mx a:domain.tld ip4:xx.xx.xx.xx  ip6:xx:xx:xx:xx::x include:servers.mcsv.net ?all 
 
 CNAME
k2._domainkey 	dkim2.mcsv.net.
k3._domainkey 	dkim3.mcsv.net.

DMARC
_dmarc v=DMARC1; p=none; rua=mailto:info@xxx.xx; pct=100; ruf=mailto:xxx.xx; fo=0:d:s; aspf=r; adkim=r; 

### Versions

Rspamd 2.6

### Additional Information

The mailing is sent correctly to all other addresses.

**Comment by andryyy** [comment]
Hi, that's not an Rspamd symbol but mailcow.
You need to setup your policies correctly and wait for them to propagate.

"The mail is sent correctly to all other addresses" is absolutley not helpful. The spoofed symbol is added when you send unauthenticated and with broken policies from another server with @yourdomain.tld to the mailcow server holding yourdomain.tld. Broken policies, no authentication => spoofed_unauth.

Please don't open an issue in the mailcow repository, we don't do support there, thanks.

**Comment by vstakhov** [comment]
Not an Rspamd issue.
