### ISSUE TITLE
[Feature] Higher-level access to TLS protocol information

### ISSUE THREAD

**Issue by windgmbh** [rspamd/rspamd#3549]
## Summary

At the moment Rspamd gathers Information on transport encryption by parsing the received headers (`/rules/misc.lua`). 

* RCVD_TLS_LAST
* RCVD_NO_TLS_LAST
* RCVD_TLS_ALL

Through milter macros/ http headers Rspamd does get more detailed information about transport encryption of the last hop, which are already definied in `/src/libserver/protocol_internal.h`:

* `TLS_CIPHER_HEADER`
* `TLS_VERSION_HEADER`
* `CERT_ISSUER_HEADER`

Currently the symbol RCVD_TLS_LAST[] is empty. By passing those milter macros/ http headers along, it would be possible to use this information like

RCVD_TLS_LAST[TLSv1.3,TLS_CHACHA20_POLY1305_SHA256]

Furthermore I did see that about ~40% of the processed mail do not contain any of the above mentioned symbols which makes them rather inconsistent for analysis/ further processing.

## Motivation

A higher level access to this information could be useful for many potential use cases:

* to reject messaged based on a encryption policy and provide the sender with a SMTP message why this has been done,
* the ability to warn end users about unencrypted messages/ weak TLS configuration by rewriting message subjects,
* as variables for statistical modules,
* for further processing in connected databases (p.e. `clickhouse.lua`) like `Tls.Version`, `Tls.Cipher` and `Tls.Issuer`,
* maybe those variables are useful in the statistical modules (I did not look into how they work yet),
* composing TLS Reports (RFC 8460),
* et cetera ...

## Describe alternatives you've considered

The proposed solution is probably easier than dealing with every possible header parsing shenanigans in `/rules/misc.lua`.
Of course the milter macros won't provide any useful information about previous hops. But the last hop is probably the most interesting one concerning spam classification, policy enforcement and data analysis.

## Additional context

In case there is approval of the basic idea, I may find the time to implement it.

**Comment by PHPGangsta** [comment]
I like the idea very much. Being able to write rules/scores based on the TLS version would be awesome. Instead of disabling TLS 1.0/1.1, I would prefer to reject with a nice error message, and maybe have a whitelist with hosts I allow the use of the old TLS versions. Having a score of 1 would be nice for "badly encrypted mails coming in via TLS 1.0"...

Info: "TLS Reports (RFC 8460)" have to be generated by sending mailservers (outbound postfix connections for example), rspamd cannot generate those reports.
