### ISSUE TITLE
[BUG] /rspamd/stats throws 403 when behind reverse proxy

### ISSUE THREAD

**Issue by ivdok** [rspamd/rspamd#3556]
### Describe the bug

When reverse-proxying rspamd with nginx, as shown [in the quickstart](https://rspamd.com/doc/quickstart.html), status & throughput at least don't show anything, and I have 403 error in network logs. Might be a duplicate of #2085, but issue didn't receive any attention for some reason.

### Steps to Reproduce

1. Quickguide.
2. https://mail.domain.tld/rspamd/, login
3. Stare at blank stats and 403 in logs

**Expected behavior**
Anything but 403, really

### Versions
Debian 10
rspamd 1.8.1
nginx version: nginx/1.14.2
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-Cjs4TR/nginx-1.14.2=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_xslt_module=dynamic --with-stream=dynamic --with-stream_ssl_module --with-stream_ssl_preread_module --with-mail=dynamic --with-mail_ssl_module --add-dynamic-module=/build/nginx-Cjs4TR/nginx-1.14.2/debian/modules/http-auth-pam --add-dynamic-module=/build/nginx-Cjs4TR/nginx-1.14.2/debian/modules/http-dav-ext --add-dynamic-module=/build/nginx-Cjs4TR/nginx-1.14.2/debian/modules/http-echo --add-dynamic-module=/build/nginx-Cjs4TR/nginx-1.14.2/debian/modules/http-upstream-fair --add-dynamic-module=/build/nginx-Cjs4TR/nginx-1.14.2/debian/modules/http-subs-filter

### Additional Information
nginx.conf:
```
server {
    listen 80;
    listen [::]:80;
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    ssl_certificate /etc/letsencrypt/live/mail.domain.tld/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mail.domain.tld/privkey.pem; # managed by Certbot

    server_name mail.domain.tld;
    index index.php;
    root /var/www/html;
    client_max_body_size 2048m;
    client_body_timeout 120s;

    if ($ssl_protocol = "") {
        return 301 https://$server_name$request_uri;
    }

    location / {
        try_files $uri $uri/ /index.php;
    }

    location ~ ^/(README|README.md|INSTALL|INSTALL.md|LICENSE|LICENSE.md|CHANGELOG|CHANGELOG.md|UPGRADING|UPGRADING.md)$ {
        deny all;
    }

    location ~ ^/(bin|SQL|config)/ {
        deny all;
    }

    location ~ /composer.(json|json-dist|lock) {
        deny all;
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass  unix:/var/run/php/php7.3-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
	fastcgi_param PATH_INFO $fastcgi_path_info;
    }



	location /rspamd/ {
		proxy_pass       http://localhost:11334/;
		proxy_set_header Host      $host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
    error_page 404 https://domain.tld;

    location ~ /.well-known/acme-challenge {
        allow all;
    }
}
```

**Comment by fatalbanana** [comment]
Please use the [contemporary version](https://rspamd.com/downloads.html) of Rspamd. Alternately try your luck logging bugs at [Debian](https://wiki.debian.org/BugReport).

**Comment by ivdok** [comment]
> Please use the [contemporary version](https://rspamd.com/downloads.html) of Rspamd. Alternately try your luck logging bugs at [Debian](https://wiki.debian.org/BugReport).

Here, let me [submit this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=976188) in your stead. I don't really care for your snide remarks, but I do want this to be fixed in the foreseeable future.
