### ISSUE TITLE
Filename on header

### ISSUE THREAD

**Issue by LucaAruba** [rspamd/rspamd#3557]
Hi,

is it possible to add attachment filename on header TAG ?

example:

**added headers by rspamd:**

ATTACH_SHA512(1.00)[5dc92d39e97c8faa035fe76b1a446e1cb0add56c30d2b0e7aa93c1864b7a44023698ab7c7a5880570145b802fd4dd1c741f785d162759187a6e2d8de8f2601d8];
MIME_ARCHIVE_IN_ARCHIVE(1.00)[zip];
OLETOOLS(1.00)[M-S-----,Hex Strings];
CONTENT_BLACKLISTED(1.00)[http://www.mafa.net];
EXT_BLACKLISTED(5.00)[pdf,docx];

**i would like to add scanned file name if is possible:**

ATTACH_SHA512(1.00)[5dc92d39e97c8faa035fe76b1a446e1cb0add56c30d2b0e7aa93c1864b7a44023698ab7c7a5880570145b802fd4dd1c741f785d162759187a6e2d8de8f2601d8,**FILE.test**];
MIME_ARCHIVE_IN_ARCHIVE(1.00)[**FILE.zip**];
OLETOOLS(1.00)[M-S-----,Hex Strings,**FILE.dot**];
EXT_BLACKLISTED(5.00)[FILE.PDF,**FILE.DOCX**];

 
multimap.conf
ATTACH_SHA512 {
        # match sha256sum hashes
        type = "selector";
        selector = "attachments(hex,sha512)";
        map = "http://127.0.0.1/hashes.txt";
        score = 1.0;
        action = "reject"
        message = "hash allegato non valida"
}
EXT_BLACKLISTED {
  type = "filename";
  filter = "extension";
  map = "http://127.0.0.1/bad.txt";
  score = 1.0
  action = "reject"
  message = "Estensione non valida"
}

**Comment by vstakhov** [comment]
@citrin do you think it is a good suggestion? I'm a bit worried about the Clickhouse part if we start storing all file names in various options.

**Comment by LucaAruba** [comment]
@vstakhov for the moment is going to be good for me if is it possibile for OLETOOLS. 
I checked in oletools.lua there is no reference to original filename.
Can you help me to know where can i should check ?

**Comment by LucaAruba** [comment]
I found a way for oletools. 
Thanks. 
it would be usefull anyway for almost every tag
