### ISSUE TITLE
[Feature] Check spamassassin rules and reload if updated

### ISSUE THREAD

**Issue by a16bitsysop** [rspamd/rspamd#3562]
## Summary

Currently rspamd does not check if the spamassassin rules have been updated on disk, so a SIGHUP signal to rspamd is required to load updated rules.

## Motivation

Spamassasin rules can be downloaded from the internet that are being updated as new spam emerges, rspamd already checks map files and other files to see if they need reloading.

Having to send rspamd a SIGHUP means the updater script has to run as root.

## Describe alternatives you've considered

Running the updater script as root and sending rspamd a SIGHUP signal, causing rspamd to reload the whole config.

**Comment by vstakhov** [comment]
That's not likely possible by many architectural reasons (sorry, but details are a bit hard to explain). Reload is a simple and non distruptive procedure so it should be used instead.

**Comment by a16bitsysop** [comment]
Ok, is there a way for a process running as rspamd user to initiate a reload?

**Comment by fatalbanana** [comment]
Yes
```
_rspamd@debvm:~$ export `systemctl -p MainPID show rspamd.service`
_rspamd@debvm:~$ kill -HUP $MainPID
```

**Comment by a16bitsysop** [comment]
Thanks for the suggestion, I am running alpine version (in a container) and it doesn't work:

```
$ whoami
rspamd

$ kill -HUP $(pgrep -o rspamd)
sh: can't kill pid 82: Operation not permitted
```

Maybe some things are owned by root that should be rspamd (user is rspamd not _rspamd in alpine)?

**Comment by fatalbanana** [comment]
If the main process is started as root you should be root to perform reload.

Alternatively you might not start rspamd as root - it looks like OpenRC could support it.

**Comment by a16bitsysop** [comment]
Thanks will try that, will have a look at the OpenRC initd script.  Not tried that yet, generally is it better to have a root main process or start as rspamd user?

**Comment by fatalbanana** [comment]
If started as a non-root user Rspamd won't be able to `chown` its UNIX sockets to a different user (#3528). Possibly similar issues might exist - some/all of which might be solved with use of `capabilities`. Packages for Linux provided by rspamd.com have started as non-root for some years & that seems to be working out fine for the majority of users.

**Comment by a16bitsysop** [comment]
Ok thanks, will change my container to start rspamd as rspamd user and have a look at the alpine OpenRC script
