### ISSUE TITLE
FUZZY_DENIED score can't be adjusted

### ISSUE THREAD

**Issue by jendis** [rspamd/rspamd#3565]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
FUZZY_DENIED symbol causes false positive and it's impossible to lower the score, only set to zero is possible.

### Steps to Reproduce
Having a sample of HAM as _fuzzy_ham.eml_ `rspamc fuzzy_ham.eml` gives result:
`Symbol: FUZZY_DENIED (9.24)[1:86db51001e:0.59:txt, 1:86db51001e:0.53:txt]`
Configuration of _"$LOCAL_CONFDIR/local.d/fuzzy_check.conf"_:
```
rule "rspamd.com" {
    fuzzy_map = {
        FUZZY_DENIED {
            max_score = <float>;
        }
    }
}
```
where changing value of the `max_score` has no impact except of value 0 which results in _FUZZY_DENIED_ score 0.

**Expected behavior**
Score of symbol _FUZZY_DENIED_ depends on `max_score`

### Versions
Gentoo OS
rspamd-2.6-r2

**Comment by fatalbanana** [comment]
This setting determines the maximum combined score in case of multiple matches. Score can be set in [groups.conf](https://rspamd.com/doc/faq.html#how-to-change-score-for-some-symbol).

**Comment by jendis** [comment]
What you say is not in compliance with the documentation https://rspamd.com/doc/modules/fuzzy_check.html, which is, not really clear too. After reading it twice, the `max_score` should behave like a trigger, but documentation uses a term _single_vote_weight_, which isn't described unfortunately anywhere, so produdes more questions than answers.
After reading third time, I finally understood that the `weight` parameter is exactly what I need - it really defines the maximum symbol's score in the scan result and can be configured in the `${CONFDIR}/local.d/fuzzy_group.conf` like

> symbols = {
>     "FUZZY_DENIED" {
>         weight = 5;
>     }
> }
