### ISSUE TITLE
Ham Mail Is Labeled Junk with Positive X-Spam Score

### ISSUE THREAD

**Issue by essandess** [rspamd/rspamd#3569]
I’m having a problem with some ham mail being sent to Junk.

Email explicitly marked as ham is still being classified with a `X-Spam: Yes` tag and moved into Junk.

When I load the raw messages into Scan/Learn, I get the correct message that they are already classified as ham:

```
<XXX@mg.mobilize.us> is skipped for bayes classifier: already in class ham; probability 100.00%
```

I’m using the default modules.d/spamassassin.conf without any ruleset, effectively disabling spamassassin.

To the best of my knowledge, rspamd and specifically `local.d/classifier-bayes.conf` are correctly configured.

Here’s what the headers of ham mail in Junk look like:

```
X-Rspamd-Queue-Id: 5024B1AFF75C0
X-Spamd-Result: default: False [7.27 / 15.00];
    HAS_REPLYTO(0.00)[XXX@YYY.mobilize.us];
    MX_INVALID(0.50)[];
    MV_CASE(0.50)[];
    SPF_FAIL_FORWARDING(0.00)[];
    R_SPF_SOFTFAIL(0.00)[~all];
    TO_DN_ALL(0.00)[];
    DKIM_TRACE(0.00)[mg.mobilize.us:+];
    DMARC_POLICY_ALLOW(0.00)[mobilize.us,none];
    DMARC_POLICY_ALLOW_WITH_FAILURES(0.00)[];
    FORGED_SENDER(0.00)[email.replies@mobilize.us];
    RCVD_IN_DNSWL_LOW(-0.10)[208.80.120.35:from];
    MIME_TRACE(0.00)[0:+,1:+,2:~];
    RCVD_TLS_LAST(0.00)[];
    PHISHING(0.66)[zoom->mobilize];
    ASN(0.00)[asn:16552, ipnet:208.80.120.0/24, country:US];
    ARC_ALLOW(0.00)[google.com:s=arc-20160816:i=1];
    FROM_NEQ_ENVFROM(0.00)[email.replies@mobilize.us];
    R_PARTS_DIFFER(0.72)[86.2%];
    RCVD_COUNT_FIVE(0.00)[6];
    R_DKIM_ALLOW(0.00)[mg.mobilize.us:s=pic];
    FROM_HAS_DN(0.00)[];
    RSPAMD_URIBL(4.50)[mobilize.us:url];
    BAYES_HAM(-3.00)[99.99%];
    HTML_SHORT_LINK_IMG_2(1.00)[];
    MIME_GOOD(-0.10)[multipart/alternative,text/plain];
    REPLYTO_DOM_NEQ_FROM_DOM(0.00)[];
    HAS_LIST_UNSUB(-0.01)[];
    RCPT_COUNT_ONE(0.00)[1];
    BAD_REP_POLICIES(0.10)[];
    FORGED_SENDER_FORWARDING(0.00)[];
    HFILTER_HOSTNAME_UNKNOWN(2.50)[];
    GREYLIST(0.00)[pass,meta]
X-Spam: Yes
```

**Comment by JQuags** [comment]
Could this be an existing x-spam flag ?

https://rspamd.com/doc/modules/milter_headers.html#remove_upstream_spam_flag-171

It should default to true to remove, perhaps it got set to false.
Can you provide the output of **rspamadm configdump**

**Comment by moisseev** [comment]
Pre-existing x-spam flag has nothing to with it. As well as Bayesian classifier: `BAYES_HAM(-3.00)[99.99%];`.
`X-Spam: Yes` flag was added because the message score of 7.72 is greater than `add_header` threshold (assuming it is default 6).
Everything works as expected.

**Comment by essandess** [comment]
@moisseev Thanks for the explanation. But how do I tell `rspamd` that this message isn't spam? It's "`already in class ham; probability 100.00%`".

Shouldn't message in class ham be classified as not spam?

**Comment by moisseev** [comment]
Actually, it is classified as ham by Bayesian classifier. It gives -3.00 to the message.
You need to decrease total score somehow: tune symbol scores, use some kind of whitelisting. etc. I would start with delisting mobilize.us from Rspamd URIBL at bl.rspamd.com.

**Comment by vstakhov** [comment]
Not an issue, closing as inappropriate.
