### ISSUE TITLE
[BUG]score calculation with grow_factor

### ISSUE THREAD

**Issue by mohammad-hachem** [rspamd/rspamd#3584]
Hi,
I have a multimap symbol having a type: content.
The purpose of this symbol is to check if specific words are found in an email and to increase the score everytime a match is found
My configuration parameters are the below:
score = 1.5
one_shot = false
grow_factor = 1.1

I am sending some tests email to test my configuration but i am always getting a score of 3.15 for this symbol regardless if my email contain one or multiple matches.
I enabled debug logging and below is a the log showing i am getting a score of 3.15 in an email on which a single match was found.
The symbol name is: CONTENT_KEYWORD_FILTER
The matched word in the below log is: prymatica

Dec 25 12:31:54 rspamd4 rspamd[111957]: <001163>; symcache; rspamd_symcache_check_symbol: execute CONTENT_KEYWORD_FILTER, 243
Dec 25 12:31:54 rspamd4 rspamd[111957]: <001163>; symcache; rspamd_symcache_item_async_inc_full: increase async events counter for CONTENT_KEYWORD_FILTER(243) = 0 + 1; subsystem lua symbol (/release/rspamd-2.5/src/lua/lua_config.c:1203)
Dec 25 12:31:54 rspamd4 rspamd[111957]: <001163>; multimap; multimap.lua:437: check value prymatica#015#012#015#012 for multimap CONTENT_KEYWORD_FILTER
Dec 25 12:31:54 rspamd4 rspamd[111957]: <001163>; metric; insert_metric_result: want to insert symbol CONTENT_KEYWORD_FILTER, initial weight 1.00
Dec 25 12:31:54 rspamd4 rspamd[111957]: <001163>; metric; insert_metric_result: metric multiplier for CONTENT_KEYWORD_FILTER is 1.50
Dec 25 12:31:54 rspamd4 rspamd[111957]: <001163>; metric; insert_metric_result: adjust grow factor to 1.10 for symbol CONTENT_KEYWORD_FILTER (1.50 final)
Dec 25 12:31:54 rspamd4 rspamd[111957]: <001163>; metric; insert_metric_result: final insertion for symbol CONTENT_KEYWORD_FILTER, score 1.50, factor: 1.5
Dec 25 12:31:54 rspamd4 rspamd[111957]: <001163>; multimap; multimap.lua:437: check value prymatica#015#012 for multimap CONTENT_KEYWORD_FILTER
Dec 25 12:31:54 rspamd4 rspamd[111957]: <001163>; metric; insert_metric_result: want to insert symbol CONTENT_KEYWORD_FILTER, initial weight 1.00
Dec 25 12:31:54 rspamd4 rspamd[111957]: <001163>; metric; insert_metric_result: metric multiplier for CONTENT_KEYWORD_FILTER is 1.50
Dec 25 12:31:54 rspamd4 rspamd[111957]: <001163>; metric; insert_metric_result: nshots: 100 for symbol CONTENT_KEYWORD_FILTER
Dec 25 12:31:54 rspamd4 rspamd[111957]: <001163>; metric; insert_metric_result: symbol CONTENT_KEYWORD_FILTER can be inserted multiple times: 1.50 weight
Dec 25 12:31:54 rspamd4 rspamd[111957]: <001163>; metric; insert_metric_result: adjust grow factor to 1.10 for symbol CONTENT_KEYWORD_FILTER (1.65 final)
Dec 25 12:31:54 rspamd4 rspamd[111957]: <001163>; metric; insert_metric_result: increase final score for multiple symbol CONTENT_KEYWORD_FILTER += 1.50 = 1.65
Dec 25 12:31:54 rspamd4 rspamd[111957]: <001163>; metric; insert_metric_result: final insertion for symbol CONTENT_KEYWORD_FILTER, score 3.15, factor: 1.5
Dec 25 12:31:54 rspamd4 rspamd[111957]: <001163>; symcache; rspamd_symcache_item_async_dec_full: decrease async events counter for CONTENT_KEYWORD_FILTER(243) = 1 - 1; subsystem lua symbol (/release/rspamd-2.5/src/lua/lua_config.c:1316)
Dec 25 12:31:54 rspamd4 rspamd[111957]: <001163>; symcache; rspamd_symcache_finalize_item: process finalize for item CONTENT_KEYWORD_FILTER(243)

**Comment by vstakhov** [comment]
Grow factor is not a per-symbol option.

**Comment by mohammad-hachem** [comment]
Yes i am aware that Grow factor is globally configured for all Rspamd.
I just mentioned it so you understand my case.

**Comment by fatalbanana** [comment]
You should use regex rules rather than multimap.

https://rspamd.com/doc/tutorials/writing_rules.html#regexp-rules
https://rspamd.com/doc/modules/regexp.html

**Comment by mohammad-hachem** [comment]
I am using regex in my map file to match specific words and phrases.
But since my target is to increase the symbol score after each match i though that using one_shot = false and grow_factor > 1 is the best way since these are builtin Rspamd features.
But as i mentioned in my initial message i can't understand how the final score is being calculated based on the number of matches.
As per Rspamd documentation  score = score + grow_factor*weight
But the tests that i have done does not fit with this formula.

**Comment by fatalbanana** [comment]
Regex maps do not support multiple matches (hence you should use rules).

**Comment by mohammad-hachem** [comment]
If i have the below symbol
CONTENT_KEYWORD_FILTER {
        type = "content";
        filter = "text";
        map = "${LOCAL_CONFDIR}/local.d/content_keyword_filter.map.inc";
        regexp = true;
        symbol = "CONTENT_KEYWORD_FILTER"
        score = 1.0;
        description = "Content filter custom rules";
}

and my Map content is similar to the below:
(?is)^(?=.*\bsex\b).*$
(?is)^(?=.*\bporn\b).*$
(?is)^(?=.*\bfuck\b).*$

So whats wrong if i rely on one_shot = false and grow_factor in this case?

**Comment by mohammad-hachem** [comment]
I checked the regex module and i didn't find anyway to create a symbol in which i have several words configured and with each match the score is increased by 1, unless i have to create a separate symbol for each word and this is not salable.
Any idea??

**Comment by mohammad-hachem** [comment]
In the same context of how Rspamd calculate the score, can someone explain to me why i  see in my logs the below for a symbol which have a score of 1 and one_shot = true  @fatalbanana @vstakhov 
Jan  4 11:11:53 rspamd4 rspamd[228759]: <f10ee7>; metric; insert_metric_result: symbol CONTENT_KEYWORD_FILTER can be inserted multiple times: 1.00 weight
Jan  4 11:11:53 rspamd4 rspamd[228759]: <f10ee7>; metric; insert_metric_result: adjust grow factor to 1.00 for symbol CONTENT_KEYWORD_FILTER (1.00 final)
Jan  4 11:11:53 rspamd4 rspamd[228759]: <f10ee7>; metric; insert_metric_result: increase final score for multiple symbol CONTENT_KEYWORD_FILTER += 1.00 = 1.00
Jan  4 11:11:53 rspamd4 rspamd[228759]: <f10ee7>; metric; insert_metric_result: final insertion for symbol CONTENT_KEYWORD_FILTER, score 2.00, factor: 1

**Comment by mohammad-hachem** [comment]
When i removed (filter = "text") from the symbol configuration i am always getting the proper score.
Any idea?? is this is a bug?
In the other hand i can't understand why you labeled this issue as invalid, it's obvious that i am raising a valid issue and i am showing all the logs that demonstrate that.
