### ISSUE TITLE
URL hidden in text

### ISSUE THREAD

**Issue by mohammad-hachem** [rspamd/rspamd#3590]
Hi,

Does Rspamd supports checking URL hidden in text for phishing, reputation and other criteria..
I found some modules such as "rspamd_url" but i can't figure out whether this is enabled by default and where can i configured it.

Thx

**Comment by nafetsreuab** [comment]
I dont know what you mean by "text" but if you're talking about mail body, then yes, thats the default with rspamd.
Have a look at https://rspamd.com/doc/modules/multimap.html#url-filters

Please note that this is a **bug**-tracker.

**Comment by mohammad-hachem** [comment]
Yes i figured it out after i did some tests.
Thx anyway
