### ISSUE TITLE
[BUG] APT Repository partially down

### ISSUE THREAD

**Issue by lfuelling** [rspamd/rspamd#3596]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
The APT Repository for RSPAMD (https://rspamd.com/apt-stable) seems to be partially down. 
At least every two tries, `apt update` is failing with an error like:
```
Err:11 https://rspamd.com/apt-stable buster Release
  404  Not Found [IP: 135.181.136.158 443]
Reading package lists... Done
E: The repository 'https://rspamd.com/apt-stable buster Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

### Steps to Reproduce

1. Add `https://rspamd.com/apt-stable buster` to APT repos
2. Run `apt update`
3. Repeat step 2 until the error appears

**Expected behavior**
The update should work.

### Versions

N/A

### Additional Information
The times this happens seems to be ~2-5 minutes.
I noticed the bug because I use a provisioning script that runs `apt update` multiple times over its runtime.
It currently always fails to complete successfully, but the exact step when it fails changes. 
I am also able to reproduce it by spamming `apt update` in the shell (see steps to reproduce).

**Comment by vstakhov** [comment]
That should be fixed now.

**Comment by lfuelling** [comment]
It does, thanks for fixing :)
