### ISSUE TITLE
[BUG] neural.lua - error after upgrade

### ISSUE THREAD

**Issue by zdzichu6969** [rspamd/rspamd#3602]
Hello, 

After upgrade rspamd form version 2.6 to 2.7 i see error in log:
![image](https://user-images.githubusercontent.com/13821532/104073555-4aa0bd00-520e-11eb-83f8-41a6080d1a25.png)

Message: 
`cannot run config post init script: /usr/share/rspamd/lualib/plugins/neural.lua:624: attempt to index field 'profile' (a nil value); trace: [1]:{/usr/share/rspamd/lualib/plugins/neural.lua:624 - process_settings_elt [Lua]}; [2]:{/usr/share/rspamd/lualib/plugins/neural.lua:708 - [Lua]};; priority = 0`

### Versions

» rspamd -v
**Rspamd daemon version 2.7**

`Linux XXX 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by vstakhov** [comment]
I think it should be fixed in the master branch.
