### ISSUE TITLE
[BUG] Web UI not working behind NGINX in subdirectory

### ISSUE THREAD

**Issue by buzz** [rspamd/rspamd#3604]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

The web interface is not working correctly. It seems the web UI is somehow constructing invalid URLs.

It loads the interface. After entering the password it shows `local > Cannot get server status` and `Request failed`

All resources load fine in the browser until I enter the password:

![](https://i.imgur.com/3lh3VcP.png)

rspamd logs:
```
rspamd_http_router_finish_handler: path: /index.htmlauth not found
rspamd_http_router_finish_handler: path: /index.htmlstat not found
```

### Steps to Reproduce

1. Install rspamd (Debian buster, using current version 2.7 from `https://rspamd.com/apt-stable/`).
2. Add postfix milter configuration to interface with rspamd (as described in the docs).

3. Setup the web UI as in the docs (behind nginx as a reverse proxy under a sub-directory).

**Expected behavior**

Expecting the web UI to work.

### Versions

`Rspamd daemon version 2.7`

```
$ cat /etc/debian_version 
10.7
```

### Additional Information

NGINX and rspamd are running on two different hosts. Everything else is working as expected.

The web UI works just fine if I forward port 11334 using SSH.

**Comment by urmel1960** [comment]
Can you please provide content of your nginx.conf file?

**Comment by buzz** [comment]
> Can you please provide content of your nginx.conf file?

```nginx
# /etc/nginx/nginx.conf
include /etc/nginx/modules-enabled/*.conf;

user nobody;
worker_processes  1;

error_log /var/log/nginx/error.log;
pid /var/run/nginx.pid;

events {
  worker_connections  1024;
  # multi_accept on;
}

http {
  include /etc/nginx/mime.types;

  access_log /var/log/nginx/access.log;

  sendfile on;
  #tcp_nopush  on;

  #keepalive_timeout 0;
  keepalive_timeout 65;
  tcp_nodelay on;

  gzip on;
  gzip_disable "MSIE [1-6]\.(?!.*SV1)";

  index index.php index.html index.htm;

  # disable server name in error pages
  server_tokens off;

  include /etc/nginx/conf.d/*.conf;
  include /etc/nginx/sites-enabled/*;
```

```nginx
# /etc/nginx/sites-enabled/mysite.conf
server {
  listen 443 ssl http2;
  server_name XXX;
  access_log /var/log/nginx/XXX.access.log;
  root /var/www/XXX;

  ssl_certificate /etc/letsencrypt/live/XXX/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/XXX/privkey.pem;
  include ssl_stuff;

  include robots-disallow.conf;

  # allow index
  location ~ ^/$ {}
  location ~ ^/index.html$ {}

  location ~ /.git {
    return 404;
  }

  # Support for favicon. Return a 204 (No Content) if the favicon
  # doesn't exist.
  location = /favicon.ico {
    try_files /favicon.ico =204;
  }
  # Any other attempt to access PHP files returns a 404.
  location ~* ^.+\.php$ {
    return 404;
  }

  # Return a 404 for all text files.
  location ~* ^/(?:README|LICENSE[^.]*|LEGALNOTICE)(?:\.txt)*$ {
    return 404;
  }

  # znc webadmin
  location /znc {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://znc:65431;
  }

  # rspamd web interface
  location /rspamd {
    proxy_pass http://rspamd:11334/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # anything else -> auth
  location / {
    auth_basic "Restricted";
    auth_basic_user_file htpasswd_XXX;
  }
```

**Comment by urmel1960** [comment]
I assume that your problem is in the section 

```
# rspamd web interface
  location /rspamd {
   proxy_pass http://rspamd:11334/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

```
Are you sure that this server can resolve "rspamd" with the right ip address of the server you are running rspamd on? 

I would anyway have separate conf-files for each virtual host/nginx sites. 

Here is the working nginx.conf I use:

```
worker_processes  2;
user www-data www-data;

pid        /var/run/nginx.pid;

events {
        worker_connections 8192;
        use epoll;
}

http {
    include       mime.types;
    default_type  text/plain;

    sendfile  on;
    tcp_nopush   on;
    tcp_nodelay on;

    gzip  on;

    server {

        listen *:8443 ssl;
        add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-XSS-Protection "1; mode=block";

#       include ssl.conf;
        ssl_certificate /etc/letsencrypt/live/xxx.xxx.xxx/fullchain.pem;
        ssl_trusted_certificate /etc/letsencrypt/live/xxx.xxx.xxx/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/xxx.xxx.xxx/privkey.pem;

        server_name xxx.xxx.xxx;
        location / {
            root /usr/share/rspamd/www/;
            try_files $uri @proxy;
        }
        location @proxy {
                proxy_pass  http://127.0.0.1:11334;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
        }
#       ssl on;
        ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
        ssl_ciphers "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA256:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EDH+aRSA+AESGCM:EDH+aRSA+SHA256:EDH+aRSA:EECDH:!aNULL:!eNULL:!MEDIUM:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4:!SEED";
        ssl_prefer_server_ciphers on;
        ssl_session_cache builtin;
        ssl_session_timeout 1m;
        ssl_stapling on;
        ssl_stapling_verify on;
        server_tokens off;
        # Do not forget to generate custom dhparam using
        # openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
				# ssl_dhparam /etc/nginx/dhparam.pem;
        ssl_ecdh_curve prime256v1;
    }
}
```
You will need to replace the 127.0.0.1 in the proxy section with the appropriate IP-address of the server where rspamd is running on and you must have opened all necessary ports on firewalls in between. Depending on the number of different public ip adresses you may have, you can run the gui on the normal ssl-port and on a specific ip address. 

```

**Comment by buzz** [comment]
> I assume that your problem is in the section
> 
> ```
> # rspamd web interface
>   location /rspamd {
>    proxy_pass http://rspamd:11334/;
>     proxy_set_header Host $host;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>   }
> ```

I assume it to be correct. What do you think is wrong with it? It comes from the rspamd documentation and I've been using similar directives for a long time without any problems.

> Are you sure that this server can resolve "rspamd" with the right ip address of the server you are running rspamd on?

Yes.

**Interestingly, the issue just disappeared.**

The web UI now works perfectly just by reloading it after ~12h uptime. I'm not sure what caused the issue but I'd consider this issue closed as I'm unable to reproduce it atm.
