### ISSUE TITLE
[BUG] R_SUSPICIOUS_URL from fileserver link type

### ISSUE THREAD

**Issue by Jorier** [rspamd/rspamd#3605]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
It look like rspamd mark as "suspicious" link with "№" symbol.

### Steps to Reproduce

1. Insert link to message with symbol "№" in path to file.
2. Send mail.

If mail contain link like this:
\\FILESERVER\Projects\Проекты\ПС №4\тех.паспорт.xlsx
<file://FILESERVER/Projects/Проекты/ПС%20№4/тех.паспорт.xlsx>
or
link=3D"#0563C1" vlink=3D"#954F72" style=3D'word-wrap:break-word'><div =
class=3DWordSection1><p class=3DMsoNormal><a =
href=3D"file://192.168.28.10/Projects/=CF=F0=EE=E5=EA=F2=FB/=CF&#8470;-2=
20.vsd">\\192.168.28.10\Projects\=CF=F0=EE=E5=EA=F2=FB\=CF=B9-220.vsd</a=

rspamd mark this mail with "X-Spam: Yes" flag.

(default: T (add header): [6.00/15.00] [R_SUSPICIOUS_URL(5.00){192.168.28.10;}

### Versions

pkg info | grep rspamd
rspamd-2.6_2                   Fast spam filtering system### Additional Information

**Comment by vstakhov** [comment]
I cannot reproduce it.

**Comment by Jorier** [comment]
Maybe there a combination of some things.

[1.host.ru.log](https://github.com/rspamd/rspamd/files/5809991/1.host.ru.log)
[2.host.ru.log](https://github.com/rspamd/rspamd/files/5809992/2.host.ru.log)

user@host:/4check # rspamc 1.host.ru.log | grep R_SUSPICIOUS_URL
Symbol: R_SUSPICIOUS_URL (5.00)[192.168.28.10]
user@host:/4check # rspamc 2.host.ru.log | grep R_SUSPICIOUS_URL
user@host:/4check #
