### ISSUE TITLE
[BUG] MULTIPLE_FROM rule does not check if "Sender" header exist

### ISSUE THREAD

**Issue by mars90226** [rspamd/rspamd#3606]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
MULTIPLE_FROM rule only detect if mail has multiple from addresses, but [RFC5322 3.6.2](https://tools.ietf.org/html/rfc5322#section-3.6.2) allows mail to have multiple from addresses if it also has a "Sender" header.

I'm not sure if this is intended behavior to only check for multiple from addresses and not check sender header.
But it's blocking some legit mails. So I create this issue.

### Steps to Reproduce

1. Craft a mail with multiple from addresses and a sender address.
2. Scan the mail with Rspamd.
3. The mail hits MULTIPLE_FROM rule.

**Expected behavior**
The mail should not hit MULTIPLE_FROM rule.

### Versions
Rspamd daemon version 2.7
Ubuntu 18.04 x86_64

**Comment by vstakhov** [comment]
Rspamd is a spam filter not an RFC compliance checker. RFC defines tonns of stupid things that are used merely by spammers or brain damaged people. Do you know any legit usage of multiple from header counting that it's mandatory for DKIM signing and for DMARC checks?

**Comment by mars90226** [comment]
I agree with you about that Rspamd is a spam filter and may block legit RFC-compliant mails. So I create this issue to ask if it's intended. As for multiple from header with DKIM signing and DMARC checks, I think it's possible for multiple from header with the same domain. But overall, I think you're right. I'll close this issue. Thanks.
