### ISSUE TITLE
[BUG] neural.lua redis data not reused post upgrade from 2.6 (same behavior in 2.7)

### ISSUE THREAD

**Issue by rikmos** [rspamd/rspamd#3609]
VER 2.6 and 2.7

To reproduce:

Run multiple combustible rspamd pods in kubernetes cluster 
New redis cluster created to store neural data (clean from 2.6 rspamd+)

Description:

Im running Docker Rspamd on spot instances with HPA in AWS, in version 2.4(rspamd)
when a spot was removed, the new pods continue using existing data from redis.

I've upgraded to version 2.6 then 2.7 

Now when a pod is restarted , the neural data in redis is NOT reused and the pods
begin to learn again until enough data is gained to start applying NEURAL_SPAM tags

Is this intended action? 
Can it be disabled?

**Comment by vstakhov** [comment]
It's not intentional but I don't know how to debug it...

**Comment by rikmos** [comment]
Let me know what you need, I can run debug logs on the modules

**Comment by rikmos** [comment]
Config settings:

inbound-rspamd/conf/local.d/neural.conf 
enabled = true;
backend = "redis";
write_servers = "neural-server-master.name:6379";
read_servers = "neural-server-slave.name:6379";

**Comment by rikmos** [comment]
021-01-15 20:56:50 #7116(normal) <6f9cec>; task; lua_metric_symbol_callback: call to (NEURAL_LEARN) failed (2): /usr/share/rspamd/lualib/lua_redis.lua:934: attempt to index field 'write_servers' (a nil value); trace: [1]:{/usr/share/rspamd/lualib/lua_redis.lua:934 - redis_make_request [Lua]}; [2]:{/usr/share/rspamd/plugins/neural.lua:74 - new_ann_profile [Lua]}; [3]:{/usr/share/rspamd/plugins/neural.lua:253 - ann_push_task_result [Lua]}; [4]:{/usr/share/rspamd/plugins/neural.lua:812 - <unknown> [Lua]};
​

**Comment by rikmos** [comment]
We have reverted to 2.5 and training was short and retained on restart ..

**Comment by rikmos** [comment]
This is the difference we see in out logs, it appears every time a pod is restarted, it breaks the ANN in redis for ALL other clients connected to that redis server
 
2021-01-16 01:49:55 #2647(controller) <bkp3sy>; lua; neural.lua:1187: invalidated ANN for default:default; redis key: rn_default_default_7kwphm47_75; version=75

**Comment by kaechele** [comment]
Is this maybe related to https://rspamd.com/doc/migration.html#migration-to-rspamd-26 ?
> `Neural networks` plugin training data will also be lost as the internal structure of the NN has been reworked in an incompatible way. Further training should continue as usually.

It seems that with that you will be unable to re-use training data from versions < 2.6 with 2.6 and later.

When you say
> it appears every time a pod is restarted, it breaks the ANN in redis for ALL other clients connected to that redis server

are you testing this with all clients using the same redis server being 2.6 and newer or are you mixing versions 2.6 and newer with older versions? That may explain your newer clients invalidating learning data for the older clients which still use the old format.

**Comment by rikmos** [comment]
Negative, a new redis cluster (for neural data) was spun up with no data in it for the initial launch of 2.6 and a second redis cluster was spun up for the launch of 2.7On Jan. 19, 2021 4:26 p.m., Felix Kaechele <notifications@github.com> wrote:
Is this maybe related to https://rspamd.com/doc/migration.html#migration-to-rspamd-26 ?

Neural networks plugin training data will also be lost as the internal structure of the NN has been reworked in an incompatible way. Further training should continue as usually.

It seems that with that you will be unable to re-use training data from versions < 2.6 with 2.6 and later.
When you say

it appears every time a pod is restarted, it breaks the ANN in redis for ALL other clients connected to that redis server

are you testing this with all clients using the same redis server being 2.6 and newer or are you mixing versions 2.6 and newer with older versions? That may explain your newer clients invalidating learning data for the older clients which still use the old format.

**Comment by gadall** [comment]
I'm seeing this behavior with a new installation of rspamd 2.7. Single server, local redis instance. Upon every restart, training starts again and existing ANNs are invalidated.

**Comment by vstakhov** [comment]
Fix has been already in the master branch for a long time: https://github.com/rspamd/rspamd/commit/21249013d490c8591451dd2a4b48d365bc3c7779

**Comment by gadall** [comment]
@vstakhov Thanks,
I've just applied that patch locally and I see the same behavior:

```
2021-03-01 00:37:42 #17787(main) <>; lua; lua_cfg_transform.lua:510: enable `options.check_all_filters` for neural network
2021-03-01 00:37:42 #17787(main) <f4wu1a>; lua; init.lua:58: controller plugin neural; register webui path learn
2021-03-01 00:37:42 #17787(main) <f4wu1a>; lua; neural.lua:876: register ann rule default
2021-03-01 00:37:42 #17787(main) <f4wu1a>; cfg; rspamd_init_lua_filters: init lua module neural from /usr/share/rspamd/plugins/neural.lua; digest: 4461fcc25c
2021-03-01 00:39:17 #17794(normal) <fc3fd3>; lua; neural.lua:69: created new ANN profile for default:default, data stored at prefix rn_default_default_wwxq6cfw_0
2021-03-01 00:39:43 #17789(controller) <f4wu1a>; lua; neural.lua:765: invalidated ANN for default:default; redis key: rn_default_default_hincfejx_0; version=0
2021-03-01 00:40:10 #17791(normal) <2d5fde>; lua; neural.lua:69: created new ANN profile for default:default, data stored at prefix rn_default_default_wwxq6cfw_0
2021-03-01 00:40:10 #17791(normal) <2d5fde>; lua; neural.lua:311: skip ham sample to keep spam/ham balance; probability 0.6666666666666667; 1 spam and 2 ham vectors stored
2021-03-01 00:40:34 #17794(normal) <fe97c9>; lua; neural.lua:311: skip ham sample to keep spam/ham balance; probability 0.6666666666666667; 1 spam and 2 ham vectors stored
2021-03-01 00:44:50 #17791(normal) <fdba97>; lua; neural.lua:311: skip ham sample to keep spam/ham balance; probability 0.4; 3 spam and 4 ham vectors stored
```

**Comment by vstakhov** [comment]
Yes - one time, but not subsequent. Well, at least I hope so.

**Comment by gadall** [comment]
OK, confirmed. Thank you!

**Comment by lhorace** [comment]
I'm sorry to have to ask this, is there a estimated release date for the 2.8? AFAIK, according to your release history, there are no point releases to fix breaking bugs. In some circumstances, it's difficult to get maintainers to cherry pick fixes?

**Comment by lhorace** [comment]
I following this project, that's why I don't update my rspamd, the risk is real

**Comment by rikmos** [comment]
If a 2nd server is added will it invalidate the ANN?

**Comment by rikmos** [comment]
I'm not sure if the issue is sorted for multiple , rspamd servers and a single redis store , can someone confirm if the bug is fixed?
