### ISSUE TITLE
[BUG] SPF validation with external relay is very misleading

### ISSUE THREAD

**Issue by markv9401** [rspamd/rspamd#3614]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
When using an external relay, SPF reports pass and that the sender's domain designates the ip (my relay host) as permitted sender. This is obviously very misleading and wrong. This is not a solution but a hack/workaround that generates false "security"

### Steps to Reproduce

1. Enable SPF module
2. Set up an external relay
3. See SPF results

**Expected behavior**
SPF should (as described it would) check the next headers and see if the next sender smtp matches with the header it generated and report this check's results instead of "lying" that my external relay is designated as a sender in the SPF records. 

### Versions

Latest stable

**Comment by vstakhov** [comment]
Are you talking about authentication results?

**Comment by markv9401** [comment]
Yes, for example:

spf=pass (mymailserver.org: domain of mygmail@gmail.com designates my.relay.server.ip as permitted sender) smtp.mailfrom=mygmail@gmail.com

**Comment by jnorell** [comment]
Also note ARC-Authentication-Results has this same problem (though fixing one might well fix the both?).

**Comment by jnorell** [comment]
Silly stalebot, this should stay open until fixed...

**Comment by vstakhov** [comment]
I believe it should be resolved by `external_relay` plugin. @fatalbanana to confirm.

**Comment by markus-96** [comment]
have the same issue. I put the ip of the relay in /etc/rspamd/local.d/external_relay.map like this:

`xxx.xxx.xxx.xxx/27`

where xxx.xxx.xxx.xxx is an ip of the relay

and in /etc/rspamd/local.d/spf.conf the following:

`external_relay = "/etc/rspamd/local.d/external_relay.map";`

still produces the following:

```
Authentication-Results: [...]
	spf=none (localhost: domain of mail@domain.tld has no SPF policy when checking xxx.xxx.xxx.xxx)
```

**Comment by markv9401** [comment]
So for anyone intersted I found the extremely counter-intuitive and confusing, albeit readily implemented solution:
https://rspamd.com/doc/modules/external_relay.html

You're going to want to use a .map file consisting of:

your.external.relay.domain.com direct

The fact that this should be a key-value pair map and the value should be exactly "direct" is essential and is nowhere documented. I reverse-engineered it via debug logging and reading the source.. It works as expected after this. Omit the, yet again, extremely confusingly identically named external_relay option from spf.conf. That does nothing but bypasses spf, pretty much. Will be opening a ticket to request to clean this up.....

**Comment by markv9401** [comment]
Anyone any time soon still countering this ticket, please refer to: https://github.com/rspamd/rspamd/issues/4080

Thanks everyone
