### ISSUE TITLE
What does this mean? OLEFY (OLETOOLS?)

### ISSUE THREAD

**Issue by G2G2G2G** [rspamd/rspamd#3615]
I looked through several different websites and links, but I cannot actually see what this error was caused by
(sender was GMAIL)
![1](https://user-images.githubusercontent.com/50514477/105550406-fa723200-5cc6-11eb-880d-567988714498.jpg)

It added +20 which made the server reject the email entirely, otherwise it would have been well within the clear. 

I use mailcow.email everything has worked for a few years, but this came up randomly with someone from gmail sending me an email. From what I can tell it's something to do specifically with rspamd and I think this: https://github.com/HeinleinSupport/olefy 

Am I right that it just means the microsoft doc or whatever was sent has some bad macro thing in it or something?

Thanks

**Comment by vstakhov** [comment]
Please ask this question for olefy maintainers.

**Comment by andryyy** [comment]
It is blocked, yes. Every doc with macro is blocked.
