### ISSUE TITLE
[BUG] dkim_signing : Signature check of Mails signed by rspamd fails. First header line always falsely "ignored"?

### ISSUE THREAD

**Issue by 346L3** [rspamd/rspamd#3617]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
I've gotten reports of failed DKIM verification of mails that were sent over my mailserver and signed by rspamd.
If I disable dkim_signing and put a second milter (openDKIM) behind rspamd, everything's apparently fine, so I think I traced the issue (BUG or error on my part?) to rspamd...
After long sessions of trial and error it seems that the only way to get a valid signature every time is, to modify the default headers that are being signed and remove "oversign" for some, because rspamd seems to think some headers are empty.

If I understand correctly, oversign should sign a header that's contained a single time (e.g. "cc:") twice. If it's not in the mail, an empty value for "cc:" should be signed once to prevent malicious third parties to add this header after signing.
I noticed that despite this, when set to oversigned "to" or "subject" only appear once (!) in the "h=" line, even if it clearly DOES exist. If I do conditional oversign for them, they ares missing from the signature and signature check on the remote end starts to pass.

I've gotten this behaviour sporadically for subject or to, but one of them is always treated as missing by rspamd and thus every signature oversigning them is broken.
It seems that it's dependent on the position of this header field in the mail that was being sent:
If "to" is the first header field (as in most cases), rspamd treats it as empty, signs it as empty once (in case of oversign) and produces a broken signature.
If "subject" is the first header, the same happens to that.
Obviously, these headers are present, even in the resulting mail. Interestingly, rspamd inserts it DKIM signature "below" the header line it treats as missing...

So, as far as I can tell, it seem that rspamd dkim_signing has trouble getting the first header line in the signing module, determines it to be missing and - in case of oversigning - signs an empty value once for existing headers (instead of signing the real value twice), thus breaking the DKIM signature.
The only dirty "workaround" in my case was, to remove strict oversigning for headers that "might" come first, which are some of the most important headers...

The HowTo on reporting bugs mentions, full mails are required to debug DKIM issues. Is there a "safe" place to drop some examples off?
Also, if more configuration examples are needed, please let me know.

### Steps to Reproduce

1. Send mail with "to" and "subject" both oversigned, in my case from Thunderbird (shouldn't matter)
2. Check signature and header field order on receiving side
3. Signature wrong in every instance as existing fields are being treated as empty/missing, supposedly "missing/empty" header field above generated DKIM header.

**Expected behavior**
Received mail passing DKIM signature checks.

### Versions

RSpamd 2.7 from the official repository together with
Postfix 2.10.1 running on
CentOS Linux release 7.9.2009 (Core) (x86_64)

Also reproducible on rspamd-2.6-156

### Additional Information
Enabling debug for dkim_signing yielded no valuable information as far as I could tell. Also the most verbose logging to syslog didn't give me any clues...
(x)subject:(x)to

local.d/dkim_signing.conf is mostly on default values:

path = "/var/lib/rspamd/dkim/$selector.key";
selector = "ashtaroth";
### Enable DKIM signing for alias sender addresses
allow_username_mismatch = true;

----------
To workaround the issue, I set "sign_headers = " to the default string mentioned in the documentation, replacing
(o) with (x) on the problematic fields: (x)subject:(x)to

**Comment by vstakhov** [comment]
All I can tell is that Rspamd is used by thousands of users for DKIM signing and everything just works fine. So it is likely that there is something unusual with your email.
You can zip the examples and send it to my personal email so I can check them.

**Comment by 346L3** [comment]
I sent one two-way exchange as an example.
Thanks.

**Comment by vstakhov** [comment]
I have totally missed this issue, will try to look at the samples soon.

**Comment by 346L3** [comment]
I'd appreciate it, thanks!
If I can provide anything more than these examples, please let me know.

**Comment by vstakhov** [comment]
Well, usually the first header is a `Received` header that's why DKIM signature is inserted after `To` in your case. I'm investigating the rest. There might be something 'unusual' about the first header...

**Comment by vstakhov** [comment]
It was hard, but I was unable to reproduce your issue. Rspamd works as expected.

Here is my config for this:

```
# dkim_signing.conf
allow_hdrfrom_mismatch_sign_networks = true;
allow_username_mismatch = true;
auth_only = true;
allow_hdrfrom_mismatch = true;
sign_networks [
    "127.0.0.0/8",
]

signing_table = [
  "*@allgaeulab.de allgaeulab.de",
];

key_table = [
  "allgaeulab.de %:eddsa:EKlVH5JwhHxns4XgZiE58cYRUaKnswKc9Ti/JXeNF1yeGXz4hRw3VeNCrysfHMDWbOobbF41rKtfgC+YGQ8Jlg==",
];
```

I have generated this key using `rspamadm dkim_keygen -d allgaeulab.de -s dkim -t ed25519`
Then, to simulate check I have added the following stuff:

```
# local.d/options.inc
dns {
  fake_records = [
        {
          name = "eddsa._domainkey.allgaeulab.de";
          type = "txt";
          replies = ["v=DKIM1; k=ed25519; p=nhl8+IUcN1XjQq8rHxzA1mzqG2xeNayrX4AvmBkPCZY="];
        }
   ];
} 
```

Then I have simulated signing:

```
> rspamc -p ~/Downloads/Testmails/Testmail_sent.eml -i 127.0.0.1 -u test@allgaeulab.de
```

And got the following DKIM signature:

```
DKIM-Signature: v=1; a=ed25519-sha256; c=relaxed/relaxed; d=allgaeulab.de;
	s=eddsa; t=1613400763;
	h=from:from:reply-to:subject:subject:date:date:message-id:message-id:
	 to:to:cc:mime-version:mime-version:content-type:content-type:
	 content-transfer-encoding:content-transfer-encoding;
	bh=viAC1RePjCVbUsHTX4QXJFSOXQ4Lr/toK75An1IBiPA=;
	b=B01/0eOQ+Xf1Gd752IuCKN8EAQqX5tLuGg/B39aV7kEGiBPdCoEOAqq0Ef0yVAgDNW80xv
	o1CIiB0gRHcGiQAg==
```

I have copied and pasted it into the message you've sent to me and tried to check it with `rspamc -p ~/Downloads/Testmails_signed.eml`

And I finally got `Symbol: R_DKIM_ALLOW (-0.20)[allgaeulab.de:s=eddsa]`. So I assume there is something broken in your setup, not in Rspamd.

**Comment by vstakhov** [comment]
I've also tried to place `Dkim-Signature` into many places of the message and got `R_DKIM_ALLOW` in all the cases. It makes me confident that there are no issues in Rspamd.

**Comment by 346L3** [comment]
Thanks for your configuration example and steps to test. I'll try to reproduce my issue with your methology and make out the difference... Honestly, it's weird, my rspamd-configuration and milter-settings in postfix aren't special in any way - at least as far as I can tell.

**Comment by 346L3** [comment]
Please leave open for a bit longer.
I can still observe this issue from time to time with my workaround in place and reproduce always when using the default signing config (oversign/sign fields), but I was under a lot of time constraints since february.
I'll use the methodology described above over the course of next week to work out the difference between my setup and the "barebone"-test that worked.

Thanks for the patience.
