### ISSUE TITLE
[Feature] Documentation cyrus-imapd learn spam / ham

### ISSUE THREAD

**Issue by thefiredragon** [rspamd/rspamd#3629]
Dear all,

I searched a while and we're using over years sogo with cyrus-imapd and amavis.
We like to switch to rspamd. 
The reason why I wrtire here is, theres no documentations about if learning spam / ham is supported also for cyrus-imapd.

Or if there are some workarounds? 
Dovecot and Cyrus use different directory schemes and I noticed thats theres also a manually learn command. 
So would it work to create an own script?

For dovecot I found sieve scripts which interactive flag a mail if a mail will be moved from spam or a mail will be marked and moved to spam in special directories where rspamd can learn.

best Regards

**Comment by vstakhov** [comment]
It is not an issue for Rspamd. If it is an issue for the documentation, then please use the rspamd.com repo (but I doubt that it will be noticed by anybody). If you are looking for help, then please use GH discussions or mailing lists.
