### ISSUE TITLE
[BUG] razor support should be improved

### ISSUE THREAD

**Issue by jranma** [rspamd/rspamd#3630]
Hi, 

I'm using rspamd version 2.7 and trying to use razor as an external service. 
I enabled it using razorfy perl daemon (downloaded at: https://github.com/HeinleinSupport/razorfy)
```
razor {
  # default razor settings
  servers = "127.0.0.1:11342"
}

```
rspamd razor support is working but is still very minimal. The use of this plugin leads to confusion on different aspects: 

1. In case of "ham" mail, the razor score is not integrated to the score headers. On the other hand, in case of spam, a line seems to be added: "RAZOR (0) [spam]".

2. In case of spam, the message is automatically rejected. Razor is not patr of the score calculation like other modules, but works in the "accept/reject" mode. On the other hand, in the web interface, the rejected message appears in green, with a "no action" label. The score is indeed lower than the trigger threshold of my "rewrite_header". 

I'm well aware that the support is minimal, so it's less a bug report than a request for improvement. Nevertheless, in this state, the razor external service doesn't seem to be able to be used correctly.

**Comment by c-rosenberg** [comment]
> rspamd razor support is working but is still very minimal. The use of this plugin leads to confusion on different aspects:
> 
> In case of "ham" mail, the razor score is not integrated to the score headers. On the other hand, in case of spam, a line seems to be added: "RAZOR (0) [spam]".

Yes, adding a ham symbol is a good idea. If you know any more razor scoring details to improve the plugin, you're welcome :)

> In case of spam, the message is automatically rejected. Razor is not patr of the score calculation like other modules, but works in the "accept/reject" mode. On the other hand, in the web interface, the rejected message appears in green, with a "no action" label. The score is indeed lower than the trigger threshold of my "rewrite_header".

The razor plugin will not trigger a reject, when its not configured to do so.
Please have a detailed look to the logs and maybe post your complete config and logs.

**Comment by jranma** [comment]
Thanks @c-rosenberg 
you're right, mail rejection problem was on my side and was not related to razor (spam example mail contained UTF8 characters in the subject, which dovecot doesnt like...)

I added this to my metrics-conf and I think it's working fine !

```
symbol "RAZOR" {
    weight = 5.0;
    description = "Detected as spam by Vipul's Razor";
}
```

Now I feel a bit confused because of razorsocket. 
HeinleinSupport wrote two wrapers (https://github.com/HeinleinSupport/razorfy): 
- razorsocket
- razorfy (which has been updated after razorsocket)

I installed razorsocket, as it's supposed to work with razor2, but it looks like the first one is working as well... Which one would you recommend ? thanks for your support !

**Comment by c-rosenberg** [comment]
https://github.com/HeinleinSupport/razorfy

This is the only supported wrapper and this one is linked in the docs.

https://rspamd.com/doc/modules/external_services.html#razor-specific-details

**Comment by jranma** [comment]
thks !
