### ISSUE TITLE
[BUG] url.c: TLD part is not detected on obfuscated url

### ISSUE THREAD

**Issue by AlphaDE** [rspamd/rspamd#3637]
### Prerequisites

[X] Put an X between the brackets on this line if you have done all of the following:

**Describe the bug**

rspamd is processing a message with phished and obfuscated url. 

`<a href=3D"https://woola.shop/csv/"><span style=3D"color: rgb(51=
, 153, 255);"><font face=3D"Times New Roman" size=3D"3">https://ku=D5=B8=
d=D0=B5.=D1=81=D6=85mdi=D0=B3=D0=B5=D1=81t.d=D0=B5/lp/wt/l=D6=85=D6=81=
i=D5=B8?=D0=B5x=D0=B5=D1=81uti=D6=85=D5=B8=3D=D0=B51s1</font></span></=
a>`

Instead of recognizing the url, debug log shows

csession; rspamd_html_url_is_phished: extract of url 'https://kuոdе.сօmdiгесt.dе/lp/wt/lօցiո?еxесutiօո=е1s1' failed: TLD part is not detected

which stops the further processing of that url and prevents the detection of the phishing attempt.

The log message shows the decoded url with all necessary information.

### Steps to Reproduce

1. Receive / scan (from web interface) malicious message
2. Phishing is not recognized

**Expected behavior**

Phishing attempt should be recognized and processing in phishing module should happen. Url should get properly decoded.

### Versions

Rspamd daemon version 2.7
Ubuntu 18.04.5 LTS

**Comment by vstakhov** [comment]
I see some invalid unicode there. Can you post the full message somehow? Or at least the relevant and unmodified content.

**Comment by vstakhov** [comment]
Also `.de` is also in unicode, so this url cannot be displayed correctly. There is a problem: Rspamd cannot just treat every piece of shit that looks like a url as a url. Unicode standard makes it even more shitty as far as you see. What we can think about is that if we see something that looks like `https://` inside `<a> ... </a>` but cannot be parsed as url it can be a bad phishing attempt. However, I still see some ways to cheat this detection, e.g. by obfuscating `https://` but, again, I can think about how to use confusable characters detection to figure out that attempts.

**Comment by AlphaDE** [comment]
@vstakhov 

Here we go the whole message, just removed third party personal information.

I fully agree that we will never be able to cover everything and some human judgement on the reeceivers end is required.

But your approach to score an obfuscated https: inside <a> tags would be a good way. 

In this specific case, Thunderbird displays (in text only mode)

`https://kuոdе.сօmdiгесt.dе/lp/wt/lօցiո?еxесutiօո=е1s1`

though the url really points to https://woola.shop/csv/

`Return-Path: <vqflclkn@riedel-roensahl.de>
Delivered-To: *******@*******
Received: from mout.kundenserver.de (mout.kundenserver.de [212.227.126.130])
	(using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits))
	(No client certificate requested)
	by  ******* (Postfix) with ESMTPS id 0BDC51804D75
	for <*******@*******>; Mon,  8 Feb 2021 06:22:46 +0100 (CET)
Received: from VMFD1371B ([217.160.46.182]) by mrelayeu.kundenserver.de
 (mreue009 [213.165.67.97]) with ESMTPSA (Nemesis) id 1MC2sH-1l3n0J1gtx-00CVOo
 for <*******@*******>; Mon, 08 Feb 2021 06:22:42 +0100
From: "=?utf-8?B?Q8yyb21kaXJlY3Q=?=" <vqflclkn@riedel-roensahl.de>
Subject: Aktualisieren photoTAN App : 49497135 2/8/2021
To: "*******" <*******@*******>
Content-Type: multipart/alternative; boundary="HOFauIaAvEvcRRxnaYdAO3I=_rVf89qJ8f"
MIME-Version: 1.0
Date: Mon, 8 Feb 2021 05:22:42 +0000
Message-ID: <1Mo6zD-1lgi3l23a7-00pfxo@mrelayeu.kundenserver.de>
X-Provags-ID: V03:K1:f4pOYnxw/thS/+S1c7b0YbrJhrwBy68aAnU9WoaKymW7fVgZWcq
 z2Or6gtKAWyCbE8Eh0bt56QzOUdW+6peSFeWEQsA3ENv2n8xAlkRdNdIPso9xsv8mXY1VlX
 guC2uNJEmgZawwXrYJ8gKYglfG1wJ0l6qwQw/vfgBtT5Cd5d+IWi8TpfKmKK1toRyoPowDJ
 WZLkEzZC/Q4ns2CV9rVWw==
X-Spam-Flag: NO
X-UI-Out-Filterresults: notjunk:1;V03:K0:N3aKJ+W0n6Y=:VmAykm47Titv1LrPdutQIH
 WslaXN+iRYtrVONVCglTMjayiApNGeM8kGGMCWkqf+CpyBb06MMwZf759+VTrxAnvMbBfX5sa
 DLs08f4mb3olJvN4u/432WeWVVC5ngKZCS6Ngmuy9WeGAHd1y9iSld+xoitF3tVXNqdEMJS56
 PBlYAFQCH4OIdH+CkWj/47kIT688ZGTIs8fXRxBkShbTC+sqH5ectO3axcLD9Q0zRlrom5jXD
 Z0jaeL3+OnT2ak3iwA+g5Z8rX1MQwC38baRqp8Yea0L9CpW1NhxcIB44EH7hr88pweb3IXhZM
 geQug297ZFy6SHy8M24uGVI+linPsYaRkD1U6z5VzX3/6ujWT/6s+6/4COrFF76AIVrURZiij
 vWhk2FOQlMhN7YmAz7Mk/S7LXID2nifdWPLHFoIIURT7Ea2XDZv8STZsSFlj7IWepn7xbCoKr
 Vg71MvC8BUCQuBQ6EyyHWdL/mO0Dh+9KLuaDze2Ad07jvJetAZWGlSbgLHC7wFh+j73gNxdW2
 R0Cm+B8BxyWEcoOMFTSNzsXGPdXe1uP6sGMw3HgUYCS
Authentication-Results: frodo.akxnet.de;
	dkim=none;
	spf=none (*******: domain of vqflclkn@riedel-roensahl.de has no SPF policy when checking 212.227.126.130) smtp.mailfrom=vqflclkn@riedel-roensahl.de;
	dmarc=none
X-Spam-Level: ***
X-Spamd-Bar: +++

This is a multi-part message in MIME format

--HOFauIaAvEvcRRxnaYdAO3I=_rVf89qJ8f
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline




S=D0=B5h=D0=B3 =D6=81=D0=B5eh=D0=B3t=D0=B5=D0=B3 Ku=D5=B8d=D0=B5,

Fwd: ph=D6=85t=D6=85TA=D5=B8 ID : 4338644678
M=D0=B5ssa=D6=81=D0=B5 ID: J54R5

=D1=96=D5=B8 Ih=D0=B3=D0=B5=D0=B3 =CE=A1=CE=BF=D1=95t=D0=92=CE=BF=D1=85=
 f=C3=BC=D0=B3 d=D0=B0=D1=95 =CE=9A=CE=BF=D5=B8t=D0=BE b=D0=B0=D5=B8k=D0=
=B0u=D1=95t=D0=B3=D1=96=D0=B0 w=D0=B0=D0=B3t=D0=B5t e=D1=96=D5=B8=D0=B5=
 =CE=9Da=D1=81h=D0=B3=D1=96=D1=81ht =D0=B0uf =D0=85=D1=96=D0=B5.

W=D0=B5=D5=B8=D5=B8 Si=D0=B5 die =D5=B8a=D1=81h=D0=B3i=D1=81ht l=D0=B5=
s=D0=B5=D5=B8 m=C3=B6=D1=81hte=D5=B8, =D0=B3uf=D0=B5=D5=B8 Si=D0=B5 di=
es=D0=B5 bitt=D0=B5 auf u=D5=B8s=D0=B5=D0=B3=D0=B5=D0=B3 W=D0=B5bsit=D0=
=B5 =C3=BCb=D0=B5=D0=B3 Ih=D0=B3=D0=B5

https://ku=D5=B8d=D0=B5.=D1=81=D6=85mdi=D0=B3=D0=B5=D1=81t.d=D0=B5/lp/=
wt/l=D6=85=D6=81i=D5=B8?=D0=B5x=D0=B5=D1=81uti=D6=85=D5=B8=3D=D0=B51s1=


Wi=D0=B3 e=D5=B8ts=D1=81huldi=D6=81=D0=B5=D5=B8 u=D5=B8s di=D0=B5 U=D5=
=B8a=D5=B8=D5=B8=D0=B5hmli=D1=81hk=D0=B5it=D0=B5=D5=B8.

Mit f=D0=B3=D0=B5u=D5=B8dli=D1=81h=D0=B5=D5=B8 =D6=81=D0=B3=C3=BC=C3=9F=
=D0=B5=D5=B8

=D1=81=D6=85mdi=D0=B3=D0=B5=D1=81t ba=D5=B8k AG

Di=D0=B5s ist =D0=B5i=D5=B8=D0=B5 aut=D6=85matis=D1=81h =D0=B5=D0=B3st=
=D0=B5llt=D0=B5 =D0=B5-Mail. Bitt=D0=B5 a=D5=B8tw=D6=85=D0=B3t=D0=B5=D5=
=B8 Si=D0=B5 =D5=B8i=D1=81ht di=D0=B3=D0=B5kt da=D0=B3auf.

=20

C=D6=85mdi=D0=B3=D0=B5=D1=81t ba=D5=B8k AG
Pas=D1=81alk=D0=B5h=D0=B3=D0=B5 15, 37677 Quickborn
(AG Pi=D5=B8=D5=B8=D0=B5b=D0=B5=D0=B3=D6=81 H=D0=B3B 9634)
www.=D1=81=D6=85mdi=D0=B3=D0=B5=D1=81t.d=D0=B5


--HOFauIaAvEvcRRxnaYdAO3I=_rVf89qJ8f
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

<html><head>
	<title></title>
=09
</head>
<body>
<table width=3D"100%" align=3D"center" style=3D"font-family: Verdana; =
font-size: 12px; border-collapse: collapse; border-spacing: 0px; backg=
round-color: rgb(255, 255, 255);" border=3D"0" cellspacing=3D"0" cellp=
adding=3D"0">
	<tbody>
		<tr>
			<td style=3D"color: rgb(26, 26, 26); line-height: 24px; letter-spac=
ing: 0px; padding-left: 20px; font-family: Arial, sans-serif; font-siz=
e: 16px;" colspan=3D"2">
			<p><font color=3D"#000000" face=3D"Times New Roman" size=3D"3"><img=
 alt=3D"E-Mail-Unterlagen_Header.png (600=C3=9757)" src=3D"https://www=
=2Ecomdirect.de/cms/img/0022_safe/E-Mail-Unterlagen_Header.png"></font=
></p>

			<p><font color=3D"#000000" face=3D"Times New Roman" size=3D"3">S=D0=
=B5h=D0=B3 =D6=81=D0=B5eh=D0=B3t=D0=B5=D0=B3 Ku=D5=B8d=D0=B5,</font></=
p>

			<p><font color=3D"#000000" face=3D"Times New Roman" size=3D"3"><spa=
n style=3D"background-color: rgb(255, 255, 255);">Fwd: ph=D6=85t=D6=85=
TA=D5=B8 ID : 3778650138</span><br style=3D"background-color: rgb(255,=
 255, 255);">
			<span style=3D"background-color: rgb(255, 255, 255);">M=D0=B5ssa=D6=
=81=D0=B5 ID: 80QNB</span></font></p>

			<p><font color=3D"#000000" face=3D"Times New Roman" size=3D"3">=D1=96=
=D5=B8 Ih=D0=B3=D0=B5=D0=B3 =CE=A1=CE=BF=D1=95t=D0=92=CE=BF=D1=85 f=C3=
=BC=D0=B3 d=D0=B0=D1=95 =CE=9A=CE=BF=D5=B8t=D0=BE b=D0=B0=D5=B8k=D0=B0=
u=D1=95t=D0=B3=D1=96=D0=B0 w=D0=B0=D0=B3t=D0=B5t e=D1=96=D5=B8=D0=B5 =CE=
=9Da=D1=81h=D0=B3=D1=96=D1=81ht =D0=B0uf =D0=85=D1=96=D0=B5.<br>
			<br>
			W=D0=B5=D5=B8=D5=B8 Si=D0=B5 die =D5=B8a=D1=81h=D0=B3i=D1=81ht l=D0=
=B5s=D0=B5=D5=B8 m=C3=B6=D1=81hte=D5=B8, =D0=B3uf=D0=B5=D5=B8 Si=D0=B5=
 dies=D0=B5 bitt=D0=B5 auf u=D5=B8s=D0=B5=D0=B3=D0=B5=D0=B3 W=D0=B5bsi=
t=D0=B5 =C3=BCb=D0=B5=D0=B3 Ih=D0=B3=D0=B5</font></p>

			<p><a href=3D"https://woola.shop/csv/"><span style=3D"color: rgb(51=
, 153, 255);"><font face=3D"Times New Roman" size=3D"3">https://ku=D5=B8=
d=D0=B5.=D1=81=D6=85mdi=D0=B3=D0=B5=D1=81t.d=D0=B5/lp/wt/l=D6=85=D6=81=
i=D5=B8?=D0=B5x=D0=B5=D1=81uti=D6=85=D5=B8=3D=D0=B51s1</font></span></=
a></p>

			<p><font color=3D"#000000" face=3D"Times New Roman" size=3D"3">Wi=D0=
=B3 e=D5=B8ts=D1=81huldi=D6=81=D0=B5=D5=B8 u=D5=B8s di=D0=B5 U=D5=B8a=D5=
=B8=D5=B8=D0=B5hmli=D1=81hk=D0=B5it=D0=B5=D5=B8.</font></p>

			<p><font color=3D"#000000" face=3D"Times New Roman" size=3D"3">Mit =
f=D0=B3=D0=B5u=D5=B8dli=D1=81h=D0=B5=D5=B8 =D6=81=D0=B3=C3=BC=C3=9F=D0=
=B5=D5=B8</font></p>

			<p><font color=3D"#000000" face=3D"Times New Roman" size=3D"3">=D1=81=
=D6=85mdi=D0=B3=D0=B5=D1=81t ba=D5=B8k AG</font><br>
			<img width=3D"546" height=3D"66" style=3D"width: 294px; height: 41p=
x;" alt=3D"29e644b403452c75b98e0f32e50cb208_10200.png (548=C3=9766)" s=
rc=3D"http://img.srv2.de/assets/bm/imh/2/9/e/6/29e644b403452c75b98e0f3=
2e50cb208_10200.png"><br>
			<font color=3D"#000000" face=3D"Times New Roman" size=3D"3">Di=D0=B5=
s ist =D0=B5i=D5=B8=D0=B5 aut=D6=85matis=D1=81h =D0=B5=D0=B3st=D0=B5ll=
t=D0=B5 =D0=B5-Mail. Bitt=D0=B5 a=D5=B8tw=D6=85=D0=B3t=D0=B5=D5=B8 Si=D0=
=B5 =D5=B8i=D1=81ht di=D0=B3=D0=B5kt da=D0=B3auf.</font></p>

			<p>&nbsp;</p>
			</td>
		</tr>
		<tr>
			<td style=3D"color: rgb(26, 26, 26); line-height: 24px; letter-spac=
ing: 0px; padding-left: 20px; font-family: Arial, sans-serif; font-siz=
e: 16px;" colspan=3D"2"><font color=3D"#000000" face=3D"Times New Roma=
n" size=3D"3">C=D6=85mdi=D0=B3=D0=B5=D1=81t ba=D5=B8k AG<br>
			Pas=D1=81alk=D0=B5h=D0=B3=D0=B5 15, 57036 Quickborn<br>
			(AG Pi=D5=B8=D5=B8=D0=B5b=D0=B5=D0=B3=D6=81 H=D0=B3B 9176)<br>
			www.=D1=81=D6=85mdi=D0=B3=D0=B5=D1=81t.d=D0=B5</font></td>
		</tr>
		<tr>
			<td style=3D"color: rgb(26, 26, 26); line-height: 24px; letter-spac=
ing: 0px; padding-left: 20px; font-family: Arial, sans-serif; font-siz=
e: 16px;" colspan=3D"2">
			<p><font color=3D"#000000" face=3D"Times New Roman" size=3D"3"><img=
 alt=3D"E-Mail-Unterlagen_Footer_2.png (600=C3=97100)" src=3D"https://=
www.comdirect.de/cms/img/0022_safe/E-Mail-Unterlagen_Footer_2.png"></f=
ont></p>
			</td>
		</tr>
	</tbody>
</table>


</body></html>


--HOFauIaAvEvcRRxnaYdAO3I=_rVf89qJ8f--

`

**Comment by vstakhov** [comment]
Sorry, github has broken formatting again. Please pack an eml into a zip file and attach to the ticket. Thanks.

**Comment by vstakhov** [comment]
Nvm, reproduced

**Comment by AlphaDE** [comment]
@vstakhov I saw it... and could hopefully fix the broken format...

**Comment by vstakhov** [comment]
Ok, I have added such a fix but I doubt it covers everything, so let's assume it as a starting point.

**Comment by AlphaDE** [comment]
great, thx.
