### ISSUE TITLE
[BUG] zen.spamhaus.org should not be used with 'received' checks

### ISSUE THREAD

**Issue by e477** [rspamd/rspamd#3641]
The default configuration uses the `zen.spamhaus.org` RBL for `received` checks. This can lead to false positives e.g. affecting legitimate e-mails sent from a dial-up with via a smarthost with SMTP-authentication. Spamhaus says:

> Do not use ZEN in filters that do any ‘deep parsing’ of Received headers, or for anything other than checking IP addresses that hand off to your mailservers.

**Comment by vstakhov** [comment]
No, it uses zen for XBL/SBL checks only. That's why it is safe to use that for Received headers (PBL is not).

**Comment by e477** [comment]
Stupid me... upon closer inspection the (legitimate) sender turned out to sit on a XBLed shared IP and I also discovered the `weight = 0` for RECEIVED_SPAMHAUS_PBL. Thanks for the clarification and sorry for the false alert.
