### ISSUE TITLE
[BUG] webUI stats and throughput unavailable

### ISSUE THREAD

**Issue by kuldaoo** [rspamd/rspamd#3643]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
WebUI stats and throughput are unavailable. A blank page appears. Browser console shows following errors:

jquery-3.3.1.min.js:1 Uncaught Error: Syntax error, unrecognized expression: #
    at Function.Sizzle.error (jquery-3.3.1.min.js:1)
    at Sizzle.tokenize (jquery-3.3.1.min.js:1)
    at Sizzle.select (jquery-3.3.1.min.js:2)
    at Function.Sizzle [as find] (jquery-3.3.1.min.js:1)
    at jQuery.fn.init.find (jquery-3.3.1.min.js:2)
    at Tab.show (bootstrap.min.js:2)
    at HTMLAnchorElement.<anonymous> (bootstrap.min.js:2)
    at Function.each (jquery-3.3.1.min.js:1)
    at jQuery.fn.init.each (jquery-3.3.1.min.js:1)
    at jQuery.fn.init.Plugin [as tab] (bootstrap.min.js:2)

d3pie.min.js:9 Uncaught TypeError: d3.arc is not a function
    at Object.create (d3pie.min.js:9)
    at d3pie.min.js:9
    at d3pie.min.js:9

### Steps to Reproduce

1. [open webUI]
2. [login]
3. [click on Stats or on Throughput]

**Expected behavior**
Display stats and throughput information

### Versions
Rspamd daemon version 1.8.1
Debian GNU/Linux 10
4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux (VPS)

### Additional Information

Tried on Chrome 88/Firefox 85

**Comment by vstakhov** [comment]
1.8.1 is not supported, please fix your time machine.

**Comment by kuldaoo** [comment]
@vstakhov  Sure :) thank you very much. Fixed. 🤦
