### ISSUE TITLE
[BUG] Can't install rspamd on Debian Bullseye

### ISSUE THREAD

**Issue by shoujii** [rspamd/rspamd#3650]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
I am using the lastest -> clean <- and updated testversion of Debian Bullseye and I'm trying to install rspamd.

### Steps to Reproduce

1. apt-get install rspamd
2. Saying yes to the SSE3 Extension Popup
3. 
cp: der Aufruf von stat für '/usr/share/javascript/jquery/jquery.min.js' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
dpkg: Fehler beim Bearbeiten des Paketes rspamd (--configure):
 »installiertes rspamd-Skript des Paketes post-installation«-Unterprozess gab den Fehlerwert 1 zurück

Translation: He can't find "/usr/share/javascript/jquery/jquery.min.js"
And the sub process returns error 1

---------------------------

Saying no to the SSE3 extension results in:
Aborting installation because of missing SSSE3 extension.
dpkg: Fehler beim Bearbeiten des Archivs /tmp/apt-dpkg-install-DdfRih/00-libhyperscan5_5.4.0-2_amd64.deb (--unpack):
 »neues libhyperscan5-Skript des Paketes pre-installation«-Unterprozess gab den Fehlerwert 1 zurück

....

Fehler traten auf beim Bearbeiten von: (Error while editing)
 /tmp/apt-dpkg-install-DdfRih/00-libhyperscan5_5.4.0-2_amd64.deb

### Versions

# rspamd --version
rspamd: error while loading shared libraries: libhs.so.5: cannot open shared object file: No such file or directory

### Additional Information

Running a VM on a Proxmox Server

**Comment by vstakhov** [comment]
Do you use Rspamd provided packages or debian ones?

**Comment by shoujii** [comment]
Debian ones

**Comment by vstakhov** [comment]
Please open this issue on the debian bugtracker then. I do not recommend to use debian packages and have never supported them.

**Comment by enderandrew** [comment]
FWIW, I just ran into the same thing and I will be opening a bug with Debian but you're not offering the option to install your packages because you don't offer a package for Bullseye.

I tried adding your repo, but you don't have a Bullseye package.
