### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AlphaDE** [rspamd/rspamd#3651]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

It is not possible to set "whitelisted_rcpts" in the ratelimit module to an empty string or to a string with just one value.

Without that empty string, already one matching CC recipient disables ratelimiting for the whole message.

### Steps to Reproduce

Set "whitelisted_rcpts" in local.d/ratelimit.conf to ""

Ratelimit does not work anymore.

**Expected behavior**

Ratelimit should work and whitelisting should be disabled.

### Additional Information

In line 524 of /usr/share/rspamd/plugins/ratelimit.lua, settings.whitelisted_rcpts is used without checking whether it is nil or contains just one entry.

 task; lua_metric_symbol_callback: call to (RATELIMITED) failed (2): /usr/share/rspamd/plugins/ratelimit.lua:552: attempt to index field 'whitelisted_rcpts' (a nil value); trace: [1]:{/usr/share/rspamd/plugins/ratelimit.lua:552 - fun [Lua]}; [2]:{/usr/share/rspamd/lualib/fun.lua:34 - call_if_not_empty [Lua]}; [3]:{/usr/share/rspamd/lualib/fun.lua:672 - any [Lua]}; [4]:{/usr/share/rspamd/plugins/ratelimit.lua:552 - <unknown> [Lua]};

**Comment by vstakhov** [comment]
Set `enabled=false` to disable any module. `whitelisted_rcpts` is simply not designed for that (not sure why did you think it was 'expected').

**Comment by AlphaDE** [comment]
The expected behaviour is that the ratelimit module works with whitelisted_rcpts being an empty string or having a single entry.

The idea is not to disable the module, from a programming perspective, no or only one entry in whitelisted_rcpts should be properly handled by the code. The condition of no or only one entry is just not catched.

**Comment by vstakhov** [comment]
Well, I think emitting error on crap values is a proper behaviour. Please read the documentation about Rspamd maps as this parameter actually defines a map.
