### ISSUE TITLE
[BUG] Unable to build against lua 5.4

### ISSUE THREAD

**Issue by ggardet** [rspamd/rspamd#3656]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
I am unable to build against lua 5.4. Cmake only checks against lua 5.3, 5.2 and 5.1.

### Steps to Reproduce
1. try to build against lua 5.4
2. lua is not found

**Expected behavior**
lua 5.4 should be supported.

### Versions
2.7

### Additional Information
None

**Comment by ggardet** [comment]
Likely better to use: https://cmake.org/cmake/help/latest/module/FindLua.html

**Comment by vstakhov** [comment]
No, I cannot use that as Rspamd mainly uses LuaJIT not plain Lua (and I do not recommend to use plain Lua as well, despite it is more or less supported).

**Comment by ggardet** [comment]
This patch detects Lua 5.4 properly, but I get a build failure later:
```
[  162s] /home/abuild/rpmbuild/BUILD/rspamd-2.7/src/lua/lua_thread_pool.c: In function 'lua_do_resume_full':
[  162s] /home/abuild/rpmbuild/BUILD/rspamd-2.7/src/lua/lua_thread_pool.c:242:9: error: too few arguments to function 'lua_resume'
[  162s]   242 |  return lua_resume (L, NULL, narg);
[  162s]       |         ^~~~~~~~~~
[  162s] In file included from /home/abuild/rpmbuild/BUILD/rspamd-2.7/src/lua/lua_common.h:6,
[  162s]                  from /home/abuild/rpmbuild/BUILD/rspamd-2.7/src/lua/lua_thread_pool.c:20:
[  162s] /usr/include/lua5.4/lua.h:300:15: note: declared here
[  162s]   300 | LUA_API int  (lua_resume)     (lua_State *L, lua_State *from, int narg,
[  162s]       |               ^~~~~~~~~~
[  162s] /home/abuild/rpmbuild/BUILD/rspamd-2.7/src/lua/lua_thread_pool.c:244:1: error: control reaches end of non-void function [-Werror=return-type]
[  162s]   244 | }
[  162s]       | ^
[  162s] cc1: some warnings being treated as errors
[  163s] make[2]: *** [src/CMakeFiles/rspamd-server.dir/build.make:1521: src/CMakeFiles/rspamd-server.dir/lua/lua_thread_pool.c.o] Error 1
```

**Comment by vstakhov** [comment]
Pushed, please check.

**Comment by ggardet** [comment]
> Pushed, please check.

I now have the following errors:
```
[  545s] /home/abuild/rpmbuild/BUILD/rspamd-2.7/src/lua/lua_thread_pool.c: In function 'lua_do_resume_full':
[  545s] /home/abuild/rpmbuild/BUILD/rspamd-2.7/src/lua/lua_thread_pool.c:243:24: error: 'from' undeclared (first use in this function)
[  545s]   243 |  return lua_resume (L, from, nargs, NULL);
[  545s]       |                        ^~~~
[  545s] /home/abuild/rpmbuild/BUILD/rspamd-2.7/src/lua/lua_thread_pool.c:243:24: note: each undeclared identifier is reported only once for each function it appears in
[  545s] /home/abuild/rpmbuild/BUILD/rspamd-2.7/src/lua/lua_thread_pool.c:243:30: error: 'nargs' undeclared (first use in this function); did you mean 'narg'?
[  545s]   243 |  return lua_resume (L, from, nargs, NULL);
[  545s]       |                              ^~~~~
[  545s]       |                              narg
[  545s] /home/abuild/rpmbuild/BUILD/rspamd-2.7/src/lua/lua_thread_pool.c:248:1: error: control reaches end of non-void function [-Werror=return-type]
[  545s]   248 | }
[  545s]       | ^
[  545s] cc1: some warnings being treated as errors
[  545s] make[2]: *** [src/CMakeFiles/rspamd-server.dir/build.make:1521: src/CMakeFiles/rspamd-server.dir/lua/lua_thread_pool.c.o] Error 1
```

This is `nargs` vs `narg` + the missing return.

**Comment by vstakhov** [comment]
Yes, there is no missing return as far as I see but there is clearly a misprint. I have fixed it. TBH, I have no Lua 5.4 to test and I mostly test everything with LuaJIT only, so I'd not be surprised if there are some other bugs/incompatibilities with the plain Lua.

**Comment by ggardet** [comment]
Now the build succeeded! Thanks! :)
