### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by phifogg** [rspamd/rspamd#3659]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
WebUi does not load properly, I get messages as 
'Module loading error: timeout, module: fontawesome'
'Module loading error: timeout, module: fontawesome_solid'
'Module loading error: timeout, module: app/rspamd'

I am not sure when this started to happen, but it was working some time ago. One of the latest updates seems to have changed it.

I am using Rspamd daemon version 2.7 - installed on debian buster using apt.

### Steps to Reproduce

open WebUI on localhost:11334

**Expected behavior**
Regular WebUI :D

### Versions
Rspamd daemon version 2.7
Debian Buster
Intel(R) Core(TM) i5-4260U CPU

You can get this information from copy and pasting the output of `rspamd --version` from the command line. Also, please include the **OS** and what version and architecture including the generation of CPU model (e.g. Haswell) where applicable,  of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by vstakhov** [comment]
Do you use packages from Debian or from rspamd.com?

**Comment by phifogg** [comment]
Standard debian packages.

**Comment by vstakhov** [comment]
Please open an issue to the Debian bug tracker then. I do not support and do not recommend to use Debian packages.
