### ISSUE TITLE
[BUG] PHISHING symbol did not fire on a phished HTML link

### ISSUE THREAD

**Issue by WRMSRwasTaken** [rspamd/rspamd#3664]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
I received an email with the following decoded HTML inside it;
```
<a href="http://studiosandri.it/as207781.net">http://portail.ate.info/paiement/rev.php?id=AYhJUKzEThJ8569</a>
```
According to https://rspamd.com/doc/modules/phishing.html, this should fire the `PHISHING` symbol (`portail.ate.info -> studiosandri.it`)

Also the plain text part of the mail contains the phished link which is way more obvious:
```
http://portail.ate.info/paiement/rev.php?id=AYhJUKzEThJ8569
<http://studiosandri.it/as207781.net>
```

### Steps to Reproduce

1. Receive the mail or scan my attached mail
2. See the symbol not firing, the only symbols firing with plus weight by the time the mail arrived were:
```
MX_INVALID (2) [greylisted]
R_MIXED_CHARSET (1.875) [subject]
BAYES_SPAM (1.539639) [86.09%]
BAD_REP_POLICIES (0.1)
```

**Expected behavior**
The `PHISHING` symbol should fire: `portail.ate.info -> studiosandri.it`

### Versions
Rspamd daemon version 2.7
Arch Linux, Kernel `5.10.17-hardened1-1-hardened` x86_64 on AMD Ryzen 2700x

### Additional Information
I've attached the received mail for troubleshooting help, renamed from `.eml` to `.txt`.
[Votre domaine as207781.net a été expiré.txt](https://github.com/rspamd/rspamd/files/6071134/Votre.domaine.as207781.net.a.ete.expire.txt)

**Comment by vstakhov** [comment]
It works to me:

`Symbol: PHISHING (1.02)[ate.info->studiosandri.it]`

text/plain links are apparently not checked as there is no possibility to detect them (despite it might be 'obvious' to you it is impossible).

**Comment by WRMSRwasTaken** [comment]
Something doesn't seem right, on a brand new Arch Linux install (everything default), the only commands I did were:

```
pacman -S rspamd
systemctl start rspamd
rspamc Votre.domaine.as207781.net.a.ete.expire.txt
```
it yields the following for me:

```
Results for file: Votre.domaine.as207781.net.a.ete.expire.txt (1.030 seconds)
[Metric: default]
Action: add header
Spam: true
Score: 7.16 / 15.00
Symbol: ARC_NA (0.00)
Symbol: DATE_IN_PAST (1.00)[72]
Symbol: DKIM_TRACE (0.00)[erasmbook.es:+]
Symbol: DMARC_POLICY_ALLOW (-0.50)[erasmbook.es, quarantine]
Symbol: FROM_EQ_ENVFROM (0.00)
Symbol: FROM_HAS_DN (0.00)
Symbol: HAS_LIST_UNSUB (-0.01)
Symbol: HAS_REPLYTO (0.00)[contact@erasmbook.es]
Symbol: MID_RHS_MATCH_FROM (0.00)
Symbol: MIME_GOOD (-0.10)[multipart/alternative, text/plain]
Symbol: MIME_TRACE (0.00)[0:+, 1:+, 2:~]
Symbol: PRECEDENCE_BULK (0.00)
Symbol: RCPT_COUNT_ONE (0.00)[1]
Symbol: RCVD_COUNT_TWO (0.00)[2]
Symbol: RCVD_NO_TLS_LAST (0.10)
Symbol: REPLYTO_EQ_FROM (0.00)
Symbol: R_DKIM_ALLOW (-0.20)[erasmbook.es:s=mail1]
Symbol: R_MIXED_CHARSET (1.87)[subject]
Symbol: SPAM_FLAG (5.00)
Symbol: TO_DN_ALL (0.00)
Message-ID: NDIYODI3.MJA0NDGZMQ.154932703021734202108104666109@erasmbook.es
Urls: ["portail.ate.info","studiosandri.it"]
Emails: []
```

The `PHISHING` symbol did not fire...

Also setting `debug_modules = ["phishing"];` in `local.d/logging.inc` only yields the following:
```
2021-03-05 17:55:04 #445243(controller) <df8af2>; phishing; phishing.lua:156: try to resolve {portail.ate.info, paiement/rev.php} -> xtq7yomfa6q796h8qjj655xfgtqojj6g.phishtank.rspamd.com
2021-03-05 17:55:04 #445243(controller) <df8af2>; phishing; phishing.lua:172: try to resolve {portail.ate.info, paiement/rev.php, id=AYhJUKzEThJ8569} -> qmntxyo13f7epxi86kuobreex6czah1o.phishtank.rspamd.com
2021-03-05 17:55:04 #445243(controller) <df8af2>; phishing; phishing.lua:156: try to resolve {studiosandri.it, as207781.net} -> g7q5r4prshh1qcxg6eaceeittapc7no3.phishtank.rspamd.com
```

Version is `rspamd 2.7-1`.

I am going to compile latest master to see if the Problem persists there...

**Comment by WRMSRwasTaken** [comment]
Spawning an Ubuntu 20.04 LXC container, installing rspamd from the PPA provided on the rspamd.com website and running the scan inside the container also does not yield the symbol:

```
root@test:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
root@test:~# rspamd -v
Rspamd daemon version 2.7
root@test:~# rspamc Votre\ domaine\ as207781.net\ a\ été\ expiré..eml
Results for file: Votre domaine as207781.net a été expiré..eml (0.293 seconds)
[Metric: default]
Action: add header
Spam: true
Score: 7.16 / 15.00
Symbol: ARC_NA (0.00)
Symbol: DATE_IN_PAST (1.00)[98]
Symbol: DKIM_TRACE (0.00)[erasmbook.es:+]
Symbol: DMARC_POLICY_ALLOW (-0.50)[erasmbook.es, quarantine]
Symbol: FROM_EQ_ENVFROM (0.00)
Symbol: FROM_HAS_DN (0.00)
Symbol: HAS_LIST_UNSUB (-0.01)
Symbol: HAS_REPLYTO (0.00)[contact@erasmbook.es]
Symbol: MID_RHS_MATCH_FROM (0.00)
Symbol: MIME_GOOD (-0.10)[multipart/alternative, text/plain]
Symbol: MIME_TRACE (0.00)[0:+, 1:+, 2:~]
Symbol: PRECEDENCE_BULK (0.00)
Symbol: RCPT_COUNT_ONE (0.00)[1]
Symbol: RCVD_COUNT_TWO (0.00)[2]
Symbol: RCVD_NO_TLS_LAST (0.10)
Symbol: REPLYTO_EQ_FROM (0.00)
Symbol: R_DKIM_ALLOW (-0.20)[erasmbook.es:s=mail1]
Symbol: R_MIXED_CHARSET (1.87)[subject]
Symbol: SPAM_FLAG (5.00)
Symbol: TO_DN_ALL (0.00)
Message-ID: NDIYODI3.MJA0NDGZMQ.154932703021734202108104666109@erasmbook.es
Urls: ["portail.ate.info","studiosandri.it"]
Emails: []
```

It's not that the `PHISHING` rule generally doesn't fire, it fired for example for an email received from Fabebook: `PHISHING (0.789501) [youtu.be->facebook.com]`, it just does not fire for the email above.

**Comment by vstakhov** [comment]
I have found an issue.

**Comment by vstakhov** [comment]
The fix wasn't trivial, so please test :\

**Comment by WRMSRwasTaken** [comment]
```
# rspamc Votre\ domaine\ as207781.net\ a\ été\ expiré..eml | grep -i phish
Symbol: PHISHING (1.02)[ate.info->studiosandri.it]
```

This fixed it, thank you 👍
