### ISSUE TITLE
[BUG] Difference between "greylisted" and "soft reject" is unclear in web UI

### ISSUE THREAD

**Issue by mconigliaro** [rspamd/rspamd#3665]
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
The status page of the web UI shows a number of greylisted emails in the pie chart, but the history page shows zero emails with the "greylist" action. It looks like greylisted emails are showing up under the "soft reject" action. 

### Steps to Reproduce
1. Log into web UI
1. Compare the number of emails categorized as "Greylisted" on the "Status" page with the number of emails with the "greylist" action on the "History" page.

**Expected behavior**
It's unclear what the difference is between "greylist" and "soft reject." In fact, I believe greylisting is a form of soft reject. In any case, greylisted emails should appear on the "History" page when you select the "greylisted" action.

### Versions

    $ rspamd --version
    Rspamd daemon version 1.9.4

    $ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 20.04.2 LTS
    Release:	20.04
    Codename:	focal

**Comment by mconigliaro** [comment]
I just realized the rspamd package repo doesn't have ARM64 packages, so I must have gotten some older version from an Ubuntu package repo when I rebuilt my server a couple days ago. I believe this problem still exists on newer rspamd versions though.

**Comment by moisseev** [comment]
Duplicate of #3654
