### ISSUE TITLE
Log: incorrect timestamp for 'accepted connection from ...'

### ISSUE THREAD

**Issue by gadall** [rspamd/rspamd#3666]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Perhaps a rather minor issue.

When accepting a request, rspamd starts logging when the request was already submitted, but not when the connection is established. Thus, the wording "accepted connection from ...", with the wrong timestamp, is somewhat misleading, in cases where there the time difference is big.

I came about this issue while experimenting with setting lower timeouts on exim's side, thinking that since rspamd's default task time limit of 8s seems to be quite adequate, but it turns out exim's timeout can be exhausted during the time it spends transmitting the request. rspamd's logging wasn't helpful in figuring this out.

### Steps to Reproduce
When sending a request to rspamd, exim expands $sender_host_name in order to populate the "Hostname: " line in the request. If the client's PTR record failed to resolve previously, it wouldn't be cached and exim will hang for a while attempting to resolve it again. This has taken 20 seconds in cases I've tested. All this occurs after the connection to rspamd has already been opened.
In this example, rspamd starts logging at 2021-03-05 07:28:27 'rspamd_worker_body_handler: accepted connection from ...' while the connection was actually established ~ 07:28:10.

**Expected behavior**
In such unusual situations, it would provide a very useful added clarity if rspamd logged new incoming connections as soon as they came in.

### Versions

2.7
```Debian linux 5.10.0-3-amd64 #1 SMP Debian 5.10.13-1```

### Additional Information
(WIP) https://bugs.exim.org/show_bug.cgi?id=956

**Comment by gadall** [comment]
Perhaps I should add, just for the record, that in the case when exim exceeded its own timeout in sending the request, we get the line on rspamd:
```rspamd_worker_guard_handler: workaround for shutdown enabled, please update your client, this support might be removed in future```
The timeout isn't checked as long as the socket is ready, so exim ends up sending the request in full and then as soon as it starts waiting for the response, it times out and closes the connection.
This is however not at all related to the bug exim had before with shutdown(), the only thing exim could do better here is be better prepared to send the request more quickly. Also this is very unlikely to happen with the default timeout of 2 minutes for spamd/rspamd servers.

**Comment by vstakhov** [comment]
As it was discussed many times: Exim integration is very limited and often wrong. I don't have enough time to work on the proper integration. Exim developers are also not very interested. So...
