### ISSUE TITLE
Be able to download external resources through http proxy

### ISSUE THREAD

**Issue by smutel** [rspamd/rspamd#3674]
## Summary

Currently it's not possible to setup a http proxy in the rspamd configuration to download external resources (white lists).  
The workaround is to download files using cron + curl and to override config with path name but it's a pain.

## Motivation

Most the company are using a http proxy to go outside.

## Describe alternatives you've considered

We can consider the specific option in the main rspamd configuration.  
The best would be to read environment variables like `http_proxy / https_proxy / no_proxy`.

**Comment by vstakhov** [comment]
As it was discussed millions times here already: it would take a huge amount of work and I don't have time for that.

**Comment by smutel** [comment]
OK, sorry for that.

Could you please answer my question about the workaround you suggest me here: https://github.com/rspamd/rspamd/discussions/3624

**Comment by 3nprob** [comment]
@vstakhov IMO this is a pretty crucial functionality for something like rspamd. Would you be open to keeping this issue open even if you're not personally working on it? Or if not, mention it in the FAQ with a link to the closed issue? I'm sure this will keep resurfacing and maybe someone else will want to pick this up and submit a PR.

It would also be very helpful if you'd be willing to explain why this is not as trivial as it seems and what is missing/went wrong with the WIP started in #572.

There is more than one way to do proxying of HTTPS requests and I think just a single one would be a huge improvement. Ideally HTTP CONNECT, but even just using an HTTPS proxy that requires installing your own root certificate in the rspamd environment, or SOCKS, would at least provide an option.

**Comment by vstakhov** [comment]
It is not a crucial functionality for Anti-Spam engine, no way, you will not sell that to me. All external communications could be done by syncing those resources manually, aside Fuzzy, it will not work via the proxy apparently.

**Comment by 3nprob** [comment]
@vstakhov Due to security policy, our servers don't have direct outbound internet access.

I am sure we are not alone in this as it's a common practice.

I'll see if we can get to where we need with your provisioning suggestion.

**Comment by therealkevink** [comment]
If http proxy is a feature that can't be implemented, is there a doc with the list of URLs to manually retrieve along with their local location?
