### ISSUE TITLE
Rspamd failed to start after upgrade from 2.6 to 2.7

### ISSUE THREAD

**Issue by eds-ch** [rspamd/rspamd#3682]
Hi,

I've just updated OS on two of my CentOS 7 servers which running Rspamd, and rebooted. After that rspamd fails to start. On both of these servers rspamd was updated earlier, so the problem is in OS (I guess so). But I can not find out what is going on. There are no information why it fails in the logs. Please help to investigate what is the problem.

UPDATE:
I was wrong about rspamd version, it was updated with OS update. After downgrade rspamd to 2.6 it's running fine. So the problem is in 2.7 version. This is strange, as it states as 'mostly a bug-fixed' release.

These what i see in /var/log/messages

Mar 20 13:26:39 mxcgp2 systemd: Started rapid spam filtering system.
Mar 20 13:26:39 mxcgp2 systemd: rspamd.service: main process exited, code=exited, status=1/FAILURE
Mar 20 13:26:39 mxcgp2 systemd: Unit rspamd.service entered failed state.
Mar 20 13:26:39 mxcgp2 systemd: rspamd.service failed.
Mar 20 13:26:39 mxcgp2 systemd: rspamd.service holdoff time over, scheduling restart.

These from systemctl

● rspamd.service - rapid spam filtering system
   Loaded: loaded (/usr/lib/systemd/system/rspamd.service; enabled; vendor preset: enabled)
   Active: failed (Result: start-limit) since Сб 2021-03-20 13:26:42 MSK; 827ms ago
     Docs: https://rspamd.com/doc/
  Process: 10819 ExecStart=/usr/bin/rspamd -c /etc/rspamd/rspamd.conf -f (code=exited, status=1/FAILURE)
 Main PID: 10819 (code=exited, status=1/FAILURE)

I've turn on debug in rpamds, but there are no information in /var/log/rspamd.log about failure. The log just ends without any error. But in this log I can see that rspamd is starting and loading configs as usual, then nothing.

The system is :
cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
rspamd -v
Rspamd daemon version 2.7

**Comment by a16bitsysop** [comment]
you could try running in foreground from the command line to see what happens before if fails eg:
/usr/bin/rspamd -f

or depending on what your rspamd system user is:

/usr/bin/rspamd -f -u rspamd -g rspamd
