### ISSUE TITLE
Certificates has expired

### ISSUE THREAD

**Issue by michelsup** [rspamd/rspamd#3687]
Hi. There is an issue with your certificates.

`root@admin ~ [SIGINT]# openssl s_client -showcerts -connect updates.rspamd.com:443
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify error:num=10:certificate has expired
notAfter=Mar 17 16:40:46 2021 GMT
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
notAfter=Mar 17 16:40:46 2021 GMT
verify return:1
depth=0 CN = updates.rspamd.com
verify error:num=10:certificate has expired
notAfter=Jan 27 04:26:29 2021 GMT
verify return:1
depth=0 CN = updates.rspamd.com
notAfter=Jan 27 04:26:29 2021 GMT
verify return:1
`

**Comment by vstakhov** [comment]
No, there is an issue with your Rspamd version: it is outdated and no longer supported. Please do not use debian packages, use packages provided by the project.

**Comment by michelsup** [comment]
I use your repo as per [:](https://rspamd.com/downloads.html#system2) : Rspamd daemon version 2.8-git.a4238dce6
Do I need to compile from git to be updated ?

**Comment by vstakhov** [comment]
Then you need to disable updates plugin: it has been disabled by default long time ago, so I'm not sure why it is still in use in your configuration.

**Comment by michelsup** [comment]
Ok just got it. The module is `enabled = false;` since a long time ago too. But when I `rspamadm configdump rspamd_update` is says `enabled`. Anyway I just removed the file and it works as intended. Sorry to bother you.

**Comment by vstakhov** [comment]
No worries, I just receive quite a lot of complaints for updates.rspamd.com from users of old Rspamd versions and I'm a bit nervious about that...

**Comment by michelsup** [comment]
I understand. Maybe it would be helpful for everyone if you could state in the logs that the plugin has been disabled. 2 lines of code would save you many hours of hassle. Maybe another trick would be to deprecate the loading of these plugins directly in the engine instead of loading them as before. Many thanks anyway for your awesome work.
