### ISSUE TITLE
Integration SA

### ISSUE THREAD

**Issue by adjustGirl** [rspamd/rspamd#3698]
I have now tried to integrate SA into rspamd

/etc/rspamd/local.d/spamassassin.conf

	spamassassin {
	ruleset = "/etc/mail/spamassassin/local.cf";
	baseruleset = "/var/lib/spamassassin/3.004002/updatesspamassassin_org/*.cf";
	# Limit search size to 100 kilobytes for all regular expressions
	match_limit = 100k;
	# Those regexp atoms will not be passed through hyperscan:
	#pcreonly = ["RULE1", "_RULE2"];
	}

But then I get the following error message

2021-04-03 19:19:04 #25634(main) lua; luacfgtransform.lua:498: nested section: spamassassin { spamassassin { ... } }, it is likely a configuration error

What’s wrong?

**Comment by vstakhov** [comment]
Remove the outer `spamassassin` section as you have already pushed it into local.d/spamassassin.conf: https://rspamd.com/doc/faq.html#rspamd-configuration-nesting
