### ISSUE TITLE
[Feature] Redirect Resolve to u.to links

### ISSUE THREAD

**Issue by Kuzuto** [rspamd/rspamd#3719]
## Summary

Resolve URL Redirects on u.to URL shortner

## Motivation

When url_redirector.lua is trying to resolve u.to links, u.to returns 404.
Reason is u.to don't allow 'GET HEADER' information.
I don't know if others don't allow 'GET HEADER', but can be a "thing" some URL Shortners will do.
url_redirector.lua should be ready for this.

**Comment by Lekensteyn** [comment]
It looks like this service uses JavaScript for redirections instead of more conventional HTTP 3xx redirects. In theory it is possible to scan for `location.href=...`, but this will not work for more complex applications nor will it be always accurate.

Example with a redirection created for this issue:

```
$ curl -sD- https://u.to/a7RAGw
HTTP/1.1 200 OK
Server: nginx/1.8.0
Date: Sat, 17 Apr 2021 17:11:58 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Keep-Alive: timeout=15
Set-Cookie: lng=en; path=/; expires=Sun, 17-Apr-2022 17:11:58 GMT; domain=.u.to;
Cache-Control: no-cache
Cache-Control: no-store
Pragma: no-cache
Vary: host

<!DOCTYPE html>
<html>
<head><title>Redirecting</title></head>
<body>
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
        new Image().src = "//counter.yadro.ru/hit;utostat?r"+escape(document.referrer)+(screen&&";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth||screen.pixelDepth))+";u"+escape(document.URL)+";"+Date.now();
        (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
        m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
        (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");
        ym(51604940, "init", {
                id:51604940,
                clickmap:true,
                trackLinks:true,
                accurateTrackBounce:true
        });
        setTimeout(function(){window.location='https://github.com/rspamd/rspamd/issues/3719';},1000);
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/51604940" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
</body>
</html>
```

There also appear to be redirects that have a delay (the actual host has been replaced in case it is untrustworthy):

```
...
$ curl -sD- https://u.to/9xLv
...
    <div class="left">
        <h1>Redirection...</h1>
        <p>You will be redirected automatically after timer elapsed:</p>
        <p class="link"><b>http://(stripped)/shop/books/447677.html?partner=3748</b></p>
        
    </div>
...
    initTimers(10, function() {
        window.location='http://(stripped)/shop/books/447677.html?partner=3748';
    });
</script>
...
```
```

**Comment by Kuzuto** [comment]
Thanks for looking into this. I did not see it was based on Javascript.
I blocked all u.to links for now, until either u.to change their logic (to help prevent phishing) or a LUA script is made to lookup the Javascript.

**Comment by Kuzuto** [comment]
To add a new URL Shortner, that also uses Javascript on the list:
* soo.gd

**Comment by vstakhov** [comment]
Old perl redirector was able to deal with that at some extent, but I don't like the idea of how it was done. For now, I'd better add these retarded redirectors to a blocklist since they are luckily not too big to block for now...
