### ISSUE TITLE
[BUG] SA scores are not overriden

### ISSUE THREAD

**Issue by moritzfriedrich** [rspamd/rspamd#3720]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
The weight for spamassasin rules can no longer be adjusted, respectively the setting has no effect.
However, if I set the weight via API Call /savesymbols, it is applied.

I first noticed it with the update to 2.7.

### Steps to Reproduce

1. load a Spamassassin ruleset per `Spamassassin rules module` (local.d/spamassassin.conf)
For my example we use https://mcgrail.com/downloads/KAM.cf
```
ruleset = "$CONFDIR/sa-rules/*.cf";
```
2. set the weight in local.d/groups.conf
In this case we will disable the check, because same check is already implemented in rspamd, but we also tested with a score not equal to 0
```
symbols {
  KAM_HUGESUBJECT {
    weight = 0;
  }
}
```
3. Test it with a long subject, more than 500 characters.

**Expected behavior**
Actually, I expect the rule to be rated with 0 points.

### Versions

Rspamd daemon version 2.7

### Additional Information

If you need further informations, don't hesitiate to ask me.

**Comment by vstakhov** [comment]
Yes, SA scores has priority over Rspamd scores :( In theory, it will be easy to fix but I must keep backward compatibility.
https://github.com/rspamd/rspamd/blob/master/src/plugins/lua/spamassassin.lua#L1547
As you see, the priority is `2` while Rspamd base symbols have priority 0 and symbols scores from the config have priority `1` (dynamic conf has priority `10` btw). We can set this `2` configurable on the module level to something else.

**Comment by moritzfriedrich** [comment]
Thank you for the clarification.
What is the reason for the higher priority of the SA score?
For me it would be more logical if rspamd has the authority over the scores.

**Comment by vstakhov** [comment]
It was probably caused by some historical reasons for migration from SA.
