### ISSUE TITLE
help configuring rspamd to be used from remote postfix

### ISSUE THREAD

**Issue by klienn** [rspamd/rspamd#3726]
Good day!
my postfix is in different host from my dovecot and rspamd, and everytime a mail comes the postfix will deliver it to my dovecot. Now I am having a hard time configuring my postfix to use the remote rspamd.
 
I have searched and found nothing.
Setting these:
```
smtpd_milters = inet:localhost:11332
non_smtpd_milters = inet:localhost:11332
milter_protocol = 6
milter_mail_macros =  i {mail_addr} {client_addr} {client_name} {auth_authen}
milter_default_action = accept
```
to 
```
smtpd_milters = inet:<ip where my rspamd is>:11332
non_smtpd_milters = inet:<ip where my rspamd is>:11332
milter_protocol = 6
milter_mail_macros =  i {mail_addr} {client_addr} {client_name} {auth_authen}
milter_default_action = accept
```
doesn't work
Any suggestions would be much appreciated

**Comment by fatalbanana** [comment]
Please use [discussions](https://github.com/rspamd/rspamd/discussions) (or [the mailing list, IRC, Telegram](https://rspamd.com/support.html)) for support questions.

The default listening address for all workers (including the proxy) is the localhost; have you [set the listening interface](https://rspamd.com/doc/quickstart.html#setting-listening-interface) appropriately? Can you connect to this service remotely? What goes wrong?
