### ISSUE TITLE
[BUG] FORGED_MUA_THUNDERBIRD_MSGID with Thunderbird 31 on Mac

### ISSUE THREAD

**Issue by fpoulain** [rspamd/rspamd#3741]
Hi,

The following user agent found on a real Thunderbird activates the rule `FORGED_MUA_THUNDERBIRD_MSGID (4.00)` giving +4 points to the spam score.
```
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:31.0) Gecko/20100101 Thunderbird/31.4.0
```

### Steps to Reproduce

This output some garbage but also `Symbol: FORGED_MUA_THUNDERBIRD_MSGID (4.00)`:
```
rspamc << EOF
Message-ID: <608AD515.1060902@bling.org>
Date: Thu, 29 Apr 2021 17:47:33 +0200
From: User <user@bling.org>
Reply-To: user@bling.org
Organization: Bling
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:31.0) Gecko/20100101 Thunderbird/31.4.0
MIME-Version: 1.0
To: dest <dest@blang.org>
Subject: Test Rspamd TB Rule
EOF
```

### Versions

Found on Rspamd daemon version 1.9.4 ; reproduced on Rspamd daemon version 2.7.

Very thanks you for rspamd!

**Comment by moisseev** [comment]
It is already fixed. https://github.com/rspamd/rspamd/commit/4aebb2b5de725a1dd68714ca3e93bdf47f3f892e

**Comment by fpoulain** [comment]
Super :+1:
