### ISSUE TITLE
[BUG] rspamd cannot get SPF records

### ISSUE THREAD

**Issue by azurit** [rspamd/rspamd#3743]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
rspamd is unable to get SPF record of any domain:
```
# rspamadm dnstool spf -d google.com
Error getting SPF record: nil (unknown flag: 0 flag)

```

### Versions

```
# rspamd --version
Rspamd daemon version 2.7

```

Debian 10.9, 64 bit

### Additional Information

Attaching full verbose output from command above:
[spf.log](https://github.com/rspamd/rspamd/files/6406083/spf.log)

As you can see, SPF record is correctly retrieved and parsed but error is printed anyway. The same is happening for very domain i tried.

**Comment by vstakhov** [comment]
It is already fixed in the master branch. I believe that in 2.7 there is a workaround to use `--all` flag to spf subcommand.

**Comment by azurit** [comment]
Is this bug affecting also rspamd ability to perform SPF check?

I started to digging into this after one of our customers changed his DMARC policy to quarantine and, suddenly, his e-mails which were not signed with DKIM (autoreply) started to be marked as spam with information in headers that there's no valid DKIM (which was true) and also SPF (which wasn't true).

**Comment by vstakhov** [comment]
No.

**Comment by apuls** [comment]
Sorry forre-open this....

Debian 9.13 & Rspamd: 2.7-42
Debian 10.11 & rspamd 3.1.1
rspamd and the dnstool aren't able to perform a spf lookup if the TXT record contains a uppercase letter.

ex: 
`$ host -t txt vodafone.com
vodafone.com descriptive text "v=spf1 ip4:195.232.248.108/30 ip4:178.249.98.16/29 include:Spf.messagelabs.com ip4:203.109.136.0/24 ip4:65.254.253.0/24 ip4:195.232.248.240/28 ip4:195.232.245.160/28 include:spf1.vodafone.com ~all"
`
`$ rspamadm dnstool spf -d vodafone.com
Cannot get SPF record: no SPF record`

`$ rspamadm dnstool spf --all -d vodafone.com
Cannot get SPF record: no SPF record`

**Comment by vstakhov** [comment]
It works as intended here:

```
> rspamadm dnstool spf --all -d vodafone.com
Policy: pass
Network: 5.61.115.0/24
Original: ip4:5.61.115.0/24
------
Policy: pass
Network: 38.133.153.128/26
Original: ip4:38.133.153.128/26
------
Policy: pass
Network: 175.158.64.0/19
Original: ip4:175.158.64.0/19
...
```

**Comment by apuls** [comment]
Mhh ok,

I've tested it with three different Debian 9 / 10 hosts and with different nameserver entries in /etc/resolv.conf.
Thank you for comming back - will dig a bit deeper...
