### ISSUE TITLE
[BUG] SPF: false fail with external_relay option when multiple hops within relay provider

### ISSUE THREAD

**Issue by futzle** [rspamd/rspamd#3745]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
My incoming mail relay provider (mailguard.com.au) passes the message between several hosts internally before the message is submitted to my host. Each hop adds a Received: header.

Actual sender -> mailguard relay 1 -> mailguard relay 2 -> mailguard relay 3 -> me

I want to use the SPF plugin **external_relay** feature to check the SPF record from the Actual sender. I have put a complete list of Mailguard's relays in local.d/spf.conf:

```
external_relay = [
  "50.23.252.166",
  "108.168.255.216",
  "108.168.255.217",
  "203.21.125.33",
  "50.23.246.238",
  "203.21.125.32"
];
```

I have turned on Milter Headers to add an Authentication-Results: header.

### Steps to Reproduce

1. Send myself an email from an external host with correct SPF.
2. Check the Authentication-Results: header

### Sample output

In this sample, Mailguard has handled the message a few times.

```
Return-Path: <debbiep@icemoonprison.com>
Received: from mail-3175-1.polyfoam.com.au ([unix socket])
	 by mail-3175-1 (Cyrus 3.2.6-Debian-3.2.6-1~bpo10+1) with LMTPA;
	 Tue, 04 May 2021 10:16:37 +1000
X-Cyrus-Session-Id: cyrus-1620087397-93876-1-842724723631632020
X-Sieve: CMU Sieve 3.0
Received: from smtp-relay-saus-toddy.mailguard.com.au (smtp-relay-saus-toddy.mailguard.com.au [108.168.255.216])
	by mail-3175-1.polyfoam.com.au (Postfix) with ESMTPS id 378C47775BD
	for <debbiep@polyfoam.com.au>; Tue,  4 May 2021 10:16:35 +1000 (AEST)
Received: from mg-aaus-zeta.mailguard.com.au (mg-aaus-zeta.mailguard.com.au [13.210.188.175])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by smtp-relay-saus-toddy.mailguard.com.au (Postfix) with ESMTPS id 09C49F01233
	for <debbiep@polyfoam.com.au>; Tue,  4 May 2021 10:16:35 +1000 (AEST)
Received: from mg-aaus-zeta.mailguard.com.au (mg-aaus-zeta.mailguard.com.au [127.0.0.1])
	by mg-aaus-zeta.mailguard.com.au (Postfix) with ESMTP id E7A526481EE
	for <debbiep@polyfoam.com.au>; Tue,  4 May 2021 10:16:34 +1000 (AEST)
Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=64.147.123.18; helo=wnew4-smtp.messagingengine.com; envelope-from=debbiep@icemoonprison.com; receiver=<UNKNOWN>; mg=TWFpbEd1YXJkYXBwcm92ZWRTUEYK;
Received: from wnew4-smtp.messagingengine.com (wnew4-smtp.messagingengine.com [64.147.123.18])
	(using TLSv1.2 with cipher ADH-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by mg-aaus-zeta.mailguard.com.au (Postfix) with ESMTPS id 5ACF6648438
	for <debbiep@polyfoam.com.au>; Tue,  4 May 2021 10:16:14 +1000 (AEST)
Received: from compute2.internal (compute2.nyi.internal [10.202.2.42])
	by mailnew.west.internal (Postfix) with ESMTP id E9EFB1A9B
	for <debbiep@polyfoam.com.au>; Mon,  3 May 2021 20:15:49 -0400 (EDT)
Received: from mailfrontend2 ([10.202.2.163])
  by compute2.internal (MEProxy); Mon, 03 May 2021 20:15:50 -0400
...
To: Deborah Pickett <debbiep@polyfoam.com.au>
From: Deborah Pickett <debbiep@icemoonprison.com>
Subject: Test 1015
...
Authentication-Results: mail-3175-1.polyfoam.com.au;
	dkim=pass header.d=icemoonprison.com header.s=fm1 header.b=GSjAG48N;
	dkim=pass header.d=messagingengine.com header.s=fm2 header.b=HUCmr8P7;
	dmarc=pass (policy=none) header.from=icemoonprison.com;
	spf=neutral (mail-3175-1.polyfoam.com.au: 108.168.255.216 is neither permitted nor denied by domain of debbiep@icemoonprison.com) smtp.mailfrom=debbiep@icemoonprison.com
```

Verbose logging shows where the SPF plugin stopped looking through the Received: header:

```
2021-05-04 10:16:35 #93977(normal) <919cb9>; spf; spf.lua:97: found external relay {[get_key] = function, [__data] = rspamd{map}(00007F909F9DB250)} at received header number 1 -> 13.210.188.175
```

**Expected behavior**
I expected the external_relay option to detect the first hop in which my message entered the mail relay (i.e., the highest-indexed Received: header which matches the external_relay list), not the last hop.

**Workaround**

Commenting out this `break` in spf.lua works for me:

https://github.com/rspamd/rspamd/blob/60a806d99dd7c49bdfa2a50f0c1b70e3580b5385/src/plugins/lua/spf.lua#L105

But I don't know if this will cause false passes in other users' Received: chains. 

### Versions

Rspamd daemon version 2.7 on Debian 10 (but I can see that this code is unchanged on master as of today, 60a806d99dd7c49bdfa2a50f0c1b70e3580b5385)

**Comment by futzle** [comment]
This might be why #3176 was failing for the reporter?

**Comment by vstakhov** [comment]
The problem with this approach is that anybody can insert some bogus 'trusted relay' received header at the bottom of the received list. It oppens very bad attack opportunities tbh. One thing I can consider is to follow the chain of the received from `external_relay` since they are either local or belonging to the `external_relay` list:

```
while rcvd_ip in external_relay_set or rcvd_ip is local do 
 process_the_next_received
end
```
