### ISSUE TITLE
[BUG] CTYPE_MIXED_BOGUS does not reflect the definition of RFC1341: 7.2 The Multipart Content-Type

### ISSUE THREAD

**Issue by thaenig** [rspamd/rspamd#3748]
According to the definition one has to have a multipart Content-Type field if there are different sets of data combined within a single body.

Also a subtype is required and as multipart/mixed is the primary subtype intended for use when the body parts are independent and intended to be displayed serially, it is totally valid to have several (or even only one ("... is explicitly permitted.")) text-only parts which the function "rspamd_config.CTYPE_MIXED_BOGUS" in headers_checks.lua does not reflect.

This happens e.g. for mails (Content-Type: text/plain)  with an attachment (also Content-Type: text/plain) sent by Liunx's mail/mailx command.

**Comment by vstakhov** [comment]
Do you have any examples to test?

**Comment by thaenig** [comment]
Of course I have examples, please find an (already processed) one attached, sent as follows:

wwwupload@rade-mysql:~> mail -s "lorem ipsum" -a lorem_ipsum.txt haenig@cosifan.de
lorem ipsum
.
EOT

best regards
Thomas

[lorem_ipsum.txt](https://github.com/rspamd/rspamd/files/6508912/lorem_ipsum.txt)

**Comment by vstakhov** [comment]
Ok, it is now fixed, thank you!

**Comment by thaenig** [comment]
Thank YOU! :-)
