### ISSUE TITLE
[Feature] Support RockyLinux (repo/RPM - basically same as CentOS 8)

### ISSUE THREAD

**Issue by systemcrash** [rspamd/rspamd#3761]
Just an FYI. Some of you may know. 

CentOS went to sh!t when RedHat pulled the plug on v8 - mandating support contracts or something. 

But RockyLinux stepped in as a "bug for bug compatible" release. They're testing 8.3-RC1 now, and it's basically the same as CentOS. Don't think (m)any changes are necessary to migrate to or add support for RL >= 8.3

**Comment by systemcrash** [comment]
Because it's bug for bug compatible, it's only rebranding, and it's a drop-in replacement/cross-grade to change over. 

It's still the same EL under the hood.

**Comment by andryyy** [comment]
It's too early to call anything the successor of CentOS.
