### ISSUE TITLE
[BUG] web ui seems to ignore history_rows option

### ISSUE THREAD

**Issue by msoltyspl** [rspamd/rspamd#3779]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Increasing history lines under options, for example:
```
#local.d/options.inc
history_rows = 8000;
```

doesn't seem to have any effect on the amount of lines available in web ui under history tab - they seem hardcoded to 200 no matter what. Note that configdump confirms that history_rows uses custom value.

### Steps to Reproduce

1. Increase the `history_rows` option in local.d/options.inc
2. stop rspamd, wipe history file just in case
3. start rspamd, let it run for a while

**Expected behavior**

Being able to see all the messages in the history, as per history_rows setting.

### Versions

Rspamd daemon version 2.7
rspamd 2.7-1~bpo10+1
debian buster

### Additional Information

N/A

**Comment by moisseev** [comment]
For `redis history module` you should set `nrows` option.

local.d/history_redis.conf:
```
nrows = 8000
```

**Comment by msoltyspl** [comment]
Ah, indeed. I persume the option I used is only for redis-less installation case.
