### ISSUE TITLE
[BUG] symbols [] in settings.conf will not be applied unless apply {} is present

### ISSUE THREAD

**Issue by msoltyspl** [rspamd/rspamd#3783]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

If we create a settings.conf rule with the only purpose of adding some symbols, they will not be added unless `apply {}` is present.

So for example, this will not work:
```
msl_tests {
        id = "msl_test";
        priority = high;
        from = "some@address.com";
        symbols = [ symbol_1 ];
}
```

but this will work:

```
msl_tests {
        id = "msl_test";
        priority = high;
        from = "some@address.com";
        symbols = [ symbol_1 ];
        apply = {};
}
```

None the less - the documentation doesn't mention that `apply` is mandatory for the `symbols` to be applied (whether it's intended or not). And it's somewhat unexpected, as symbols table is outside apply block.

### Versions

Rspamd daemon version 2.7
rspamd 2.7-1~bpo10+1
debian buster

**Comment by vstakhov** [comment]
Apply is mandatory, yes.

**Comment by msoltyspl** [comment]
Would be nice to update the documentation at some point though, e.g.

`symbols - add symbols from the list if a rule has matched` -> `symbols - add symbols from the list if a rule has matched and apply statment is present (can be empty)`

**Comment by moisseev** [comment]
@msoltyspl Any chance for a pull request?
