### ISSUE TITLE
composites module matches partial symbol name?

### ISSUE THREAD

**Issue by silverasu** [rspamd/rspamd#3787]
While creating expression=LEAKED_PASSWORD_SCAM, it also matches LEAKED_PASSWORD_SCAM_RE symbol.
For example:
TEST123 {
    expression = "LEAKED_PASSWORD_SCAM"
    score = 0.01;
}

TEST123  is triggered, while LEAKED_PASSWORD_SCAM_RE matches.
How to force exact symbol name?

**Comment by vstakhov** [comment]
I cannot reproduce it and nothing in the code tells me that it's ever possible. `LEAKED_PASSWORD_SCAM` is also a composite symbol btw.

**Comment by silverasu** [comment]
problem was that default policy removed this LEAKED_PASSWORD_SCAM symbol. It is ok with policy = "leave";
