### ISSUE TITLE
[BUG] MIME_ARCHIVE_IN_ARCHIVE false positive with archived file in digidoc container (.asice)

### ISSUE THREAD

**Issue by silverasu** [rspamd/rspamd#3790]
When archived container is signed with digidoc, it will automatically get 5 points for MIME_ARCHIVE_IN_ARCHIVE symbol.

solution: .asice extension should be excluded?

Attached .zip contains .ascie file for testing.
[test.zip](https://github.com/rspamd/rspamd/files/6622429/test.zip)

**Comment by vstakhov** [comment]
Asice is some container which is zip. Why does include other zip files?
