### ISSUE TITLE
CONTENT_BLACKLISTED not working?

### ISSUE THREAD

**Issue by biztems** [rspamd/rspamd#3796]
Hi,

we're trying to stop receiving emails which contain specific words, but our multimap.conf setup doesn't seem to work.

----
this is our multimap.conf:

CONTENT_BLACKLISTED {
  type = "content";
  filter = "body";
  map = "${LOCAL_CONFDIR}/local.d/multimap.d/bl-content.map";
  symbols = ["CONTENT_BLACKLISTED1", "CONTENT_BLACKLISTED2"];
  regexp = true;
}

and this is the map content:

/\b(bonjour|merveilleux|fantastique|bonne|journée|agréable|vous|salut)\b/i

----

we're still getting emails containing those words, we can see them getting the "no action" label from the rspamd gui

can anyone help us figure this out if something is wrong or if there's another way to do it?

version: Rspamd 1.9 on Ubuntu 20.04.2 LTS

Thanks

**Comment by vstakhov** [comment]
I'm sorry but your Rspamd version is not supported, please upgrade it to the supported one.

**Comment by biztems** [comment]
> I'm sorry but your Rspamd version is not supported, please upgrade it to the supported one.

Hi, thanks for your quick reply. We would love to upgrade to the supported one, but it seems you guys are not providing arm64/aarch64 builds so we are limited to what Ubuntu provides in 20.04.2 - all of our servers are arm64, and IMHO, I think arm64/aarch64 should be a build target for the project in 2021 since it is cost effective and arguably it will become the prevalent architecture in the near future.

Any plans for arm64/aarch64 support?

Cheers!

**Comment by fatalbanana** [comment]
> Any plans for arm64/aarch64 support?

Not at this time.

> Otherwise I suppose we will build from sources

I recommend you do. Debian-specific hints about building from sources are [here](https://github.com/rspamd/rspamd/issues/3546#issuecomment-723446451) (see also [here](https://rspamd.com/downloads.html)). There are some rebuilds for exotic architectures [here](https://build.opensuse.org/package/show/home:susenerf:rspamd-exotic-debian/rspamd).

For best results you should probably run Rspamd on x86_64 (for benefit of a somewhat tested binary distribution & lesser chance to meet weird problems / better chance to get such problems fixed).
