### ISSUE TITLE
[BUG] if email address has "o." whitelist is ignored

### ISSUE THREAD

**Issue by yolorkit** [rspamd/rspamd#3806]
**Describe the bug**
An email address _nameo.like527@gmail.com_ is on the whitelist but
rspamd doesn't see the dot it sees it as _nameolike527@gmail.com_ and thus doesn't understand its on the whitelist
If i put the name without the dot it sees it and marks according to whitelist rule.

It happens only if the "o" letter followed by a dot. Every other name with dot is ok. I already have a list of a few mails that i had to make workaround that i described above.

### Steps to Reproduce

1. Create an email with "o." in its address like _nameo.like527@gmail.com_
2. Put this email address to whitelist
3. Send an email from this address to yours where rspamd checks it
4. rspamd doesn't follow the whitelist rule unless you put the address without the dot in it

**Expected behavior**
Sees an email with address that contains "o."

### Versions

Rspamd daemon version 2.6
System:    Host: xu-host Kernel: 4.15.0-137-generic x86_64 bits: 64 Desktop: N/A
           Distro: Ubuntu 18.04.5 LTS
CPU:       Dual core Intel Core2 Duo E8400 (-MCP-) cache: 6144 KB
           clock speeds: max: 2999 MHz 1: 2999 MHz 2: 2999 MHz

**Comment by fatalbanana** [comment]
GMail addresses are normalised by the `EMAIL_PLUS_ALIASES` rule, which might often be inconvenient (but is needed for [EBL in particular](https://msbl.org/ebl.html)).

You can access the original address in Multimap by using something like the following:
```
selector = "from({'smtp', 'orig'})";
```

**Comment by yolorkit** [comment]
Thanks. Couldn't get selector working so i disabled the rule. I'm using dnsbl so i shouldn't be effected by it?

**Comment by GieltjE** [comment]
If they are normalised, shouldn't the input from the whitelist be normalised too?
