### ISSUE TITLE
Certificate for 'updates.rspamd.com' has expired?

### ISSUE THREAD

**Issue by mejofi** [rspamd/rspamd#3811]
It looks like the certificate for 'updates.rspamd.com' expired at the end of January, and hasn't been renewed since? This leads to errors in the logs, such as;

`error reading https://updates.rspamd.com/rspamd-1.8.ucl(88.99.142.95:443): connection with http server terminated incorrectly: ssl connect error: ssl error: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed`

See also; https://www.ssllabs.com/ssltest/analyze.html?d=updates.rspamd.com

**Comment by moisseev** [comment]
Not a bug. See https://github.com/rspamd/rspamd/issues/3714#issuecomment-822050945

Please do not open issues for outdated Rspamd versions.

**Comment by mejofi** [comment]
Ah, so you were warned before, and didn't fix it then either. That's all I need to know, thanks!
