### ISSUE TITLE
[BUG] MX Check floods all IPs of MX domains with multiple A records

### ISSUE THREAD

**Issue by CptCharlesG** [rspamd/rspamd#3839]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

Some domains have large amount of MX servers listed, and MX Check wants to check all of them simultaneously (eg. 40 connection in 1 second). Most of the time for valid server a single check would be enough, so this function floods the network unnecessarily.

The problem is that some providers limit the amount of e-mails that can be sent over port 25 (our limit: 30 mail/minute), and this behavior triggers the limiter within a 1 second.

In our case the problem appeared with dhl.com that uses a strange MX setup that has multiple MX records (mx1.dhl.iphmx.com, mx2.dhl.iphmx.com) which is common for many domains, but both MX domains returns a long list of 20 IPs in a randomized order every time. MX Check sends 20+20 SYN to port 25 simultaneously, then 20+20 FIN, ACK but for the last 10 only the TCP tries to do its job as we are getting banned at our IPS.

### Steps to Reproduce

1. Enable MX Check module
2. Enable some tracking/logging/packet capture on your server/router.
3. Get an e-mail from dhl.com or another domain with similar setup (or set up a separate test mail server with 1-2 MX domains, assign 20+ A records to these domains)
4. Check the log/packet capture

**Expected behavior**
The module should check the first IP, if there is no mail server behind only then should check the next IP.
Or check only the first IP or a random IP etc. 
Or if it is parallelized for faster execution, then an option (like parallel/sequential, or concurrent connections limit) should be available for limited environments.

Bonus: every IP gets checked twice as they are listed for both MX domain - a check would be great to eliminate IP duplication if we have free CPU cycles...

### Versions

Rspamd daemon version 2.7
centos-release-7-9.2009.1.el7.centos.x86_64 (Nethserver 7.9.2009)
Proxmox VM with Intel CPU

### Additional Information

Our workaround was to add whitelists including dhl.com, so the problem is solved for now, but who knows how many other domains are configured this way - so the issue can appear again any time triggering the limiter again.

**Comment by vstakhov** [comment]
Hum, isn't it helping: https://github.com/rspamd/rspamd/commit/ac155317a5014716c9fb106f4feb54aeb16bbea6 ?

**Comment by vstakhov** [comment]
Ah, I see, so you mean that a single MX name has multiple IP addresses. That's not checked indeed, I will fix it.

**Comment by vstakhov** [comment]
It should be fixed now.

**Comment by CptCharlesG** [comment]
Thanks for the quick response @vstakhov !
I have tried the new file (only updated this one, no other file), but currently I am getting this error:

call to dns callback failed: /usr/share/rspamd/plugins/mx_check.lua:160: attempt to call field 'shuffle' (a nil value); trace: [1]:{/usr/share/rspamd/plugins/mx_check.lua:160 - [Lua]};

**Comment by vstakhov** [comment]
You cannot update a single file that's why you have issues. Please use experimental packages to test.
