### ISSUE TITLE
[BUG] Compile issues on rspamd 3.0

### ISSUE THREAD

**Issue by breisig** [rspamd/rspamd#3850]
When trying to compile rspamd 3.0 from source, [LuaJIT 2.0.5, ragel 6.10, gcc 11.2.1, glibc 2.34, binutils 2.37], I am getting the following error when compiling

```
[ 68%] Building CXX object src/CMakeFiles/rspamd-server.dir/libserver/html/html_entities.cxx.o
[ 68%] Building CXX object src/CMakeFiles/rspamd-server.dir/libserver/html/html_url.cxx.o
[ 69%] Building CXX object src/CMakeFiles/rspamd-server.dir/libserver/html/html.cxx.o
[ 69%] Building CXX object src/CMakeFiles/rspamd-server.dir/libserver/html/html_tests.cxx.o
[ 69%] Building CXX object src/CMakeFiles/rspamd-server.dir/libserver/css/css.cxx.o
In file included from /tmp/rspamd-3.0/src/libserver/css/css.cxx:26:
/tmp/rspamd-3.0/contrib/doctest/doctest/doctest.h:4299:47: error: size of array 'altStackMem' is not an integral constant-expression
 4299 |         static char             altStackMem[4 * SIGSTKSZ];
      |                                               ^
make[2]: *** [src/CMakeFiles/rspamd-server.dir/build.make:1084: src/CMakeFiles/rspamd-server.dir/libserver/css/css.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1432: src/CMakeFiles/rspamd-server.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

cmake command line parameters
-DCMAKE_INSTALL_PREFIX=/usr -DCONFDIR=/etc/rspamd -DWWWDIR=/var/www/nginx-chroot/html/rspamd -DFMT_WERROR=OFF -DCMAKE_LIBRARY_PATH=/usr/lib64

Didn't have issues with the same command on rspam 2.7. Any ideas?

**Comment by tomop-tg** [comment]
doctest is not compatible with glibc-2.34.

see https://github.com/onqtam/doctest/commit/099d5414e97244ec44cf46b14cd176b3a3dc52e3

**Comment by vstakhov** [comment]
Well, `SIGSTKSZ` is also used within Rspamd itself, but in Rspamd it is used as following:

```
ss.ss_size = MAX (SIGSTKSZ, 8192 * 4);
```

so replacement of `SIGSTKSZ` with `sysconf(_SC_SIGSTKSZ)` will not break anything I suppose. I can update bundled doctest but it will likely go to version 3.1 as glibc-2.34 is not so ubiquitous.

**Comment by breisig** [comment]
If it gets fixed in the master branch, I can either manually compile master or manually patch the 3.0 source with the commit from master that fixes it.

**Comment by vstakhov** [comment]
@tomop-tg has linked the fix from the doctest upstream, so you can use it before I would backport it to Rspamd.

**Comment by tomop-tg** [comment]
I successfully built and launched rspamd-3.0 with https://github.com/onqtam/doctest/commit/099d5414e97244ec44cf46b14cd176b3a3dc52e3 and PR https://github.com/rspamd/rspamd/pull/3852 applied.

environment: gcc-11.2.1 / glibc-2.34 / binutils-2.37 / lua-5.4
