### ISSUE TITLE
Read-only file system: '/var/lib/rspamd/.pyzor

### ISSUE THREAD

**Issue by cscholz** [rspamd/rspamd#3856]
### Prerequisites

- rspamd 3.0
- pyzor installed (https://rspamd.com/doc/modules/external_services.html#pyzor-specific-details)

**Describe the bug**
pyzor is not allowed to write into folder _/var/lib/rspamd/.pyzor_

**Log**
```
Aug 22 05:10:00 mx02.o-o-s.de rspamd[13819]: <f0410e>; lua; common.lua:170: pyzor (hash): #words is less then text_part_min_words: 2
Aug 22 05:10:00 mx02.o-o-s.de rspamd[13819]: <f0410e>; lua; common.lua:170: pyzor (hash): #words is less then text_part_min_words: 2
Aug 22 05:10:00 mx02.o-o-s.de systemd[1]: Started Pyzor Socket Service (127.0.0.1:40686).
Aug 22 05:10:00 mx02.o-o-s.de pyzor[19420]: Traceback (most recent call last):
Aug 22 05:10:00 mx02.o-o-s.de pyzor[19420]:   File "/usr/bin/pyzor", line 408, in <module>
Aug 22 05:10:00 mx02.o-o-s.de pyzor[19420]:     main()
Aug 22 05:10:00 mx02.o-o-s.de pyzor[19420]:   File "/usr/bin/pyzor", line 131, in main
Aug 22 05:10:00 mx02.o-o-s.de pyzor[19420]:     config, options, args = load_configuration()
Aug 22 05:10:00 mx02.o-o-s.de pyzor[19420]:   File "/usr/bin/pyzor", line 107, in load_configuration
Aug 22 05:10:00 mx02.o-o-s.de pyzor[19420]:     os.mkdir(options.homedir)
Aug 22 05:10:00 mx02.o-o-s.de pyzor[19420]: OSError: [Errno 30] Read-only file system: '/var/lib/rspamd/.pyzor'


```

### Steps to Reproduce

1. Install pyzor like described here https://rspamd.com/doc/modules/external_services.html#pyzor-specific-details
2. $ journalctl -f | grep -i pyzor
3.  Scan a spam message via rspam web mail interface

### Versions

**$ lsb_release -a**
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

**$ dpkg -l** 
`ii  rspamd                                3.0-1~buster                                                             amd64        Rapid spam filtering system`

### Fix
```
$ mkdir /var/lib/rspamd/.pyzor
$ chown _rspamd:_rspamd /var/lib/rspamd/.pyzor
```

**Comment by biji** [comment]
Probably different issue but related to pyzor. I have done `mkdir` and `chown` but `pyzor` not being checked. I'm using rspamd tandem with Spamassassin, while Spamassassin said pyzor detect spam

Thanks

**Comment by biji** [comment]
From: https://rspamd.com/doc/modules/external_services.html#pyzor-specific-details

Changing `ExecStart=-/usr/bin/pyzor check` to `ExecStart=/usr/bin/pyzor check`  solves my issue :laughing:

**Comment by cscholz** [comment]
Fixed as information have been added to documentation.

https://rspamd.com/doc/modules/external_services.html#pyzor-specific-details
