### ISSUE TITLE
[BUG] Oletools extended = true is ignored

### ISSUE THREAD

**Issue by GieltjE** [rspamd/rspamd#3857]
* [X] Put an X between the brackets on this line if you have done all of the following:

**Describe the bug**
Setting extended = true; in the oletools configuration doesn't result in the flags being added as described in https://rspamd.com/doc/modules/external_services.html#oletools-extended-mode

### Steps to Reproduce

1. Enable extended mode (see config below)
2. Send a malicious macro
3. View headers

**Expected behavior**
The header changing from something like:
```
OLETOOLS(1.00)[AutoExec + Suspicious (Document_open,Create,showwindow,CreateObject,Chr)];
```
to
```
OLETOOLS(1.00)[A-----S-, AutoExec + Suspicious (Document_open,Create,showwindow,CreateObject,Chr)];
```

### Versions
Rspamd daemon version 3.0, Debian bullseye, X64

### Additional Information
local.d/external_services.conf
```
oletools {
  servers = "127.0.0.1:10050";
  scan_mime_parts = true;
  extended = true;
}
```

**Comment by c-rosenberg** [comment]
My guess - you are seeing the cached result. Please try another file or delete the redis entry. 

Otherwise, please enable debugging for the external_services module and show us some logs.

**Comment by GieltjE** [comment]
Indeed a caching issue, but there don't seem to be any redis entries.
