### ISSUE TITLE
[BUG] Compile failure [clang, 32-bit] libserver/html/html.cxx

### ISSUE THREAD

**Issue by sthen** [rspamd/rspamd#3858]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

Build fails with 3.0 on OpenBSD i386. Doesn't appear to be OS-specific. 

```
/pobj/rspamd-3.0/rspamd-3.0/src/libserver/html/html.cxx:1216:48: error: non-constant-expression cannot be narrowed from type 'long long' to 'std::__1::basic_string_view::size_type' (aka 'unsigned long') in initializer list [-Wc++11-narrowing]
                                        {hc->parsed.data() + initial_dest_offset, written_len},
                                                                                  ^~~~~~~~~~~
/pobj/rspamd-3.0/rspamd-3.0/src/libserver/html/html.cxx:1216:48: note: insert an explicit cast to silence this issue
                                        {hc->parsed.data() + initial_dest_offset, written_len},
                                                                                  ^~~~~~~~~~~
                                                                                  static_cast<size_type>
( )
1 error generated.
ninja: build stopped: subcommand failed.
```

### Steps to Reproduce

Attempt to build.

**Expected behavior**

Build succeeds.

### Versions

OpenBSD -current i386. Compiler is clang 11.1.0. rspamd is 3.0 release version.

### Additional Information

Relevant code section:

```
   1212         if (is_visible) {
   1213                 if (tag->id == Tag_A) {
   1214                         auto written_len = hc->parsed.size() - initial_dest_offset;
   1215                         html_process_displayed_href_tag(pool, hc,
   1216                                         {hc->parsed.data() + initial_dest_offset, written_len},
   1217                                         tag, exceptions,
   1218                                         url_set, initial_dest_offset);
   1219                 }
```

**Comment by vstakhov** [comment]
It seems you are trying to build Rspamd with `-Werror` aren't you?

**Comment by sthen** [comment]
e4621c415e05593f0cdd83e56cf350dd25215821 fixed.
