### ISSUE TITLE
[Feature] Public release of lua_magic as separate library

### ISSUE THREAD

**Issue by msva** [rspamd/rspamd#3864]
Hi there!

Would you consider to release lua_magic as separate library (ideally, without dependencies on rspamd), and upload it on luarocks, please?

I'd (And, I think, many people would) very like to have possibility to use it in another projects instead of [lua-magic](https://github.com/mah0x211/lua-magic).

**Comment by vstakhov** [comment]
The main problem is that lua-magic relies on Hyperscan if it is available. Hyperscan is a large library that might be an overkill if you want it as a dependency. Otherwise, that might be a good idea as Rspamd lua-magic is very fast (much faster than the original libmagic).
