### ISSUE TITLE
Save/Send virus detected attachments

### ISSUE THREAD

**Issue by bikedevone** [rspamd/rspamd#3876]
Hi guys,

first of all, rspamd is def. the best. Congrats for your amazing work. 
I have "maybe" a simple question. 
Is it possible to save/send the virus (clamd) detected attachments.

e.x. 
**Virus detected -> send virus to mail address** 
**Virus detected -> save file in network path**

The idea is to automate the process and automatically analyze the attachment for IoC´s and other stuff.

thanks in advance

**Comment by dragoangel** [comment]
This possible with meta exporter module. You can Google rspamd quarantine examples. Don't know what you want analyze further, clamav detection isn't the best to be honest. And to note: clamav scan email as full file, it will not say where virus exactly and it trigger on sender domain in email body or on links there.

**Comment by Dzemik55** [comment]
ye
