### ISSUE TITLE
[BUG] x-spamd-bar is broken "number has no integer representation"

### ISSUE THREAD

**Issue by mebourne** [rspamd/rspamd#3879]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

x-spamd-bar is missing a math.floor when calling string.rep and fails with the error:
lua; milter_headers.lua:599: call to x-spamd-bar failed: /usr/share/rspamd/plugins/milter_headers.lua:361: bad argument #2 to 'rep' (number has no integer representation)

### Steps to Reproduce

1. Enable x-spamd-bar milter header
2. Receive email which has non-integer spam score
3. x-spamd-bar is not added to received email, error is present in rspamd.log

**Expected behavior**

x-spamd-bar should be present with a suitable value

### Versions

master

### Additional Information

The bug is here:
See: https://github.com/rspamd/rspamd/blob/master/src/plugins/lua/milter_headers.lua#L359-L361

x-spam-level does this correctly and is working, the equivalent correct code is here:
https://github.com/rspamd/rspamd/blob/master/src/plugins/lua/milter_headers.lua#L386

**Comment by vstakhov** [comment]
Fixed, thanks!
