### ISSUE TITLE
[BUG] rspmad 3.0 stable fails build with glibc 2.34:  size of array 'altStackMem' is not an integral constant-expression

### ISSUE THREAD

**Issue by sonic42** [rspamd/rspamd#3882]
**Describe the bug**
The build of rspamd 3.0 fails with glibc 2.34: error: size of array 'altStackMem' is not an integral constant-expression

Log:
FAILED: src/CMakeFiles/rspamd-server.dir/libserver/css/css.cxx.o
/tools_x86_64/ccache/bin/c++ -DDOCTEST_CONFIG_NO_MULTI_LANE_ATOMICS -DDOCTEST_CONFIG_USE_STD_HEADERS -DFMT_LOCALE -DHAVE_CONFIG_H -DSYS_ZSTD -DU_CHARSET_IS_UTF8 -Drspamd_server_EXPORTS -I../contrib/hiredis -I../ -I../src -I../src/libutil -I../src/libserver -I../src/libmime -I../src/libstat -I../src/libcryptobox -I../contrib/libucl -I../contrib/replxx/include -I../contrib/uthash -I../contrib/http-parser -I../contrib/fpconv -I../contrib/libottery -I../contrib/xxhash -I../contrib/cdb -I../contrib/snowball/include -I../contrib/librdns -I../contrib/aho-corasick -I../contrib/lc-btrie -I../contrib/lua-lpeg -I../contrib/frozen/include -I../contrib/fmt/include -I../contrib/doctest -I../contrib/fu2/include -Isrc -Isrc/libcryptobox -I/usr/include/luajit-2.1 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/hs -I../compat -O3 -pipe -Wall -fexceptions -fPIC -m64 -mtune=native -fstack-clash-protection -fcf-protection -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -fdiagnostics-color=always -O3 -DNDEBUG -O3 -funsafe-math-optimizations -fno-math-errno -fomit-frame-pointer -flto -fno-fat-lto-objects -fPIC -msse2 -m64 -D_GNU_SOURCE -DLINUX -Wextra -Wall -Wpointer-arith -Wno-unused-parameter -Wno-unused-function -Wunused-variable -Wno-strict-aliasing -fno-strict-aliasing -Wnull-dereference -Wduplicated-cond -Wno-unused-const-variable -Wno-sign-compare -Wno-implicit-fallthrough -Wmissing-noreturn -Wmissing-format-attribute -fPIC -std=gnu++17 -MD -MT src/CMakeFiles/rspamd-server.dir/libserver/css/css.cxx.o -MF src/CMakeFiles/rspamd-server.dir/libserver/css/css.cxx.o.d -o src/CMakeFiles/rspamd-server.dir/libserver/css/css.cxx.o -c ../src/libserver/css/css.cxx
In file included from ../src/libserver/css/css.cxx:26:
../contrib/doctest/doctest/doctest.h:4299:47: error: size of array 'altStackMem' is not an integral constant-expression
 4299 |         static char             altStackMem[4 * SIGSTKSZ];
      |                                               ^

### Steps to Reproduce
My build options:
cmake .. -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DSYSTEM_ZSTD=ON \
		-DENABLE_PCRE2=ON \
		-DENABLE_HYPERSCAN=ON
ninja
	
### Versions
Tested on Linux from Scratch Version r11.0-5

**Comment by vstakhov** [comment]
It is a doctest issue mentioned in  #3875. As a workaround, you can build Rspamd with an external doctest.

**Comment by arkamar** [comment]
This was fixed in commit 4dcee38fd372 - `[Minor] Update bundled doctest to the latest version`. You can close it.
