### ISSUE TITLE
[Feature] subject_privacy for redis data

### ISSUE THREAD

**Issue by JustKiddingCode** [rspamd/rspamd#3886]
## Summary

Right now, the subject is hidden only for the WebUI but saved in redis, if the history_redis module is used.
This has compliance drawbacks, e.g., GDPR issues, for anyone who can access the redis directly.

## Changes
As for my limited understanding of LUA, changes are not big.
It should be enough

``` 
# src/plugins/lua/history_redis.lua
-- Change this
  tbl.subject = task:get_header('subject') or 'unknown'
-- To:
  tbl.subject = lua_util.maybe_obfuscate_string(task:get_header('subject'), settings, 'subject')
```
and delete the `maybe_obfuscate_string` part later on.
Then newly stored files in the database will be obfuscated at insertion time.

**Comment by williamdes** [comment]
For people searching for this, it has been implemented: https://rspamd.com/doc/modules/history_redis.html#configuration

```ini
subject_privacy = true;
```
