### ISSUE TITLE
[Feature] mta-sts support

### ISSUE THREAD

**Issue by erialor** [rspamd/rspamd#3911]
## Summary
Would like support for mta-sts (https://www.rfc-editor.org/rfc/rfc8461.txt) - I *think* it should be there alongside ie. SPF, DKIM, DMARC, ARC?

## Motivation

Adds an extra layer of security/spam-protection?

## Describe alternatives you've considered

Just implemented/currently using  https://github.com/Snawoot/postfix-mta-sts-resolver alongside postfix to implement mta-sts.
Don't have much experience with it yet, apart from seeing;
Sep 22 22:51:54 mail.vlh.dk postfix/smtp Verified TLS connection established to gmail-smtp-in.l.google.com[173.194.79.27]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (P-256) server-digest SHA256
Sep 22 22:53:09 mail.vlh.dk postfix/smtp Verified TLS connection established to gmail-smtp-in.l.google.com[173.194.79.27]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (P-256) server-digest SHA256
Sep 23 10:22:13 mail.vlh.dk postfix/smtp Verified TLS connection established to aspmx.l.google.com[2a00:1450:4010:c1e::1b]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (P-256) server-digest SHA256

Instead of 'only' trusted...

## Additional context

The current implementation from https://github.com/Snawoot/postfix-mta-sts-resolver seems to work - but would rather like it to be incorporated into rspamd or (postfix?)

**Comment by vstakhov** [comment]
This seems to be doable indeed as Rspamd has already all components for this implementation in place.

**Comment by vstakhov** [comment]
On the other hand it seems to be useless for spam filtering :) Another story if Rspamd acts as a tls_policy_map for Postfix - this is doable in principle.

**Comment by PHPGangsta** [comment]
MTA-STS is used on outbound MTAs. It doesn't make sense in rspamd as a spam-filter, that's correct.
