### ISSUE TITLE
 Debian/Ubuntu repository is not running ok, so cannot update 

### ISSUE THREAD

**Issue by feanorknd** [rspamd/rspamd#3916]
Hi all,

just to note repository for ubuntu focal is not running, just giving following error while executing "apt update":

```
Ign:12 https://rspamd.com/apt-stable focal InRelease
Err:13 https://rspamd.com/apt-stable focal Release
 Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 135.181.136.158 443]
Reading package lists... Done
E: The repository 'http://rspamd.com/apt-stable focal Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

Followed instructions at:
https://rspamd.com/downloads.html
(for Ubuntu/Debian)

Thanks so much!

Regards!

**Comment by Disassembler0** [comment]
Looks like your Ubuntu doesn't have the current Let's Encrypt root certificate (ISRG Root X1). Make sure the ca-certificates package is up to date (version 20210119~18.04.2 or newer) and try again.

**Comment by feanorknd** [comment]
Hi....


`root@ispconfig:~# apt update
Hit:1 http://mirror.hetzner.de/ubuntu/packages focal InRelease
Hit:2 http://mirror.hetzner.de/ubuntu/packages focal-updates InRelease                                                 
Hit:3 http://mirror.hetzner.de/ubuntu/packages focal-backports InRelease                                               
Hit:4 http://mirror.hetzner.de/ubuntu/packages focal-security InRelease                                                
Hit:5 http://mirror.23media.de/mariadb/repo/10.5/ubuntu focal InRelease                                                
Hit:6 http://nginx.org/packages/ubuntu focal InRelease                                                                 
Hit:7 http://ppa.launchpad.net/ondrej/php/ubuntu focal InRelease                                                       
Hit:9 https://mirror.hetzner.com/ubuntu/packages focal InRelease                                                       
Hit:10 https://mirror.hetzner.com/ubuntu/packages focal-updates InRelease
Hit:11 https://mirror.hetzner.com/ubuntu/packages focal-backports InRelease
Hit:12 https://mirror.hetzner.com/ubuntu/security focal-security InRelease
Ign:8 https://rspamd.com/apt-stable focal InRelease 
Err:13 https://rspamd.com/apt-stable focal Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 135.181.136.158 443]
Reading package lists... Done                 
E: The repository 'http://rspamd.com/apt-stable focal Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
N: Skipping acquire of configured file 'nginx/binary-i386/Packages' as repository 'http://nginx.org/packages/ubuntu focal InRelease' doesn't support architecture 'i386'
root@ispconfig:~# 
root@ispconfig:~# 
root@ispconfig:~# cat /etc/apt/sources.list.d/rspamd.list 
deb [arch=amd64 signed-by=/etc/apt/keyrings/rspamd.gpg] http://rspamd.com/apt-stable/ focal main
root@ispconfig:~# 
root@ispconfig:~# 
root@ispconfig:~# dpkg -la | grep cace
root@ispconfig:~# dpkg -la | grep ca-cert
ii  ca-certificates                      20210119~20.04.1                                                   all          Common CA certificates
ii  ca-certificates-java                 20190405ubuntu1                                                    all          Common CA certificates (JKS keystore)
root@ispconfig:~# 
root@ispconfig:~# 
root@ispconfig:~# curl -o /dev/null -v https://rspamd.com/apt-stable
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 135.181.136.158:443...
* TCP_NODELAY set
* Connected to rspamd.com (135.181.136.158) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [88 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [155 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [25 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [3832 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [78 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=rspamd.com
*  start date: Sep  5 23:00:56 2021 GMT
*  expire date: Dec  4 23:00:55 2021 GMT
*  subjectAltName: host "rspamd.com" matched cert's "rspamd.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.`

please, check out my answer... here you can see the apt failing, the ca-certificates currently upgraded, and curl (using system ca-certificates) working with your domain without problems.

What could be then?

**Comment by feanorknd** [comment]
perl / GET is also working with your letsencrypt cert at https://rspamd.com without problems.

why apt not? It happens in every ubuntu focal I have (5).

**Comment by feanorknd** [comment]
ok... related:
https://forum.syncthing.net/t/apt-error-while-updating/17431/4

apt is not using server's ca-certificates. So needed to:
- disable rspamd repo from apt.sources.d
- apt update and upgrade
- enable rspamd repo
- apt update and upgrade

and everything is ok.

Thanks so much for your support and your excellent job!! :)
