### ISSUE TITLE
[Feature] Debian builds for bookworm/sid

### ISSUE THREAD

**Issue by skibbipl** [rspamd/rspamd#3928]
Last build of rspamd for sid is 2.7. Will there be any 3.x builds for next debian release - bookworm?

**Comment by vstakhov** [comment]
The stable packages for Debian Bookworm should now be available.

**Comment by skibbipl** [comment]
I can confirm that finally I was able to upgrade rspamd without dependency issues. However I will probably soon switch to next debian release and the packages will be outdated again.
