### ISSUE TITLE
[Feature] QR code decoder / reader

### ISSUE THREAD

**Issue by mucke5** [rspamd/rspamd#3945]
## Summary

This is a PHP library to detect and decode QR-codes.
This is the first and only QR code reader that works without extensions.
https://github.com/khanamiryan/php-qrcode-detector-decoder

## Motivation

Using a QR code is a great tactic to make sure that the email reaches the recipient instead of being automatically removed by email filters.
https://www.hoxhunt.com/blog/banking-phishing-qr-codes/

## Describe alternatives you've considered

Not available.

**Comment by vstakhov** [comment]
Do you have any email samples with QR codes used by spammers?

**Comment by mucke5** [comment]
Scanned online via [Web QR](https://webqr.com/) ⇨ Reference to spk-kundenumstellung[.]com

[QR-Code_Sample.pdf](https://github.com/rspamd/rspamd/files/7626313/QR-Code_Sample.pdf)

**Comment by GieltjE** [comment]
@vstakhov there is a whole QR code epidemic going on right now, attached is a first example, can send many more if needed (there are some different ones going around, e.g. with an image containing a whole teams message with an QR embedded somewhere in the middle).

**Comment by vstakhov** [comment]
Let's convert this to a discussion
