### ISSUE TITLE
cannot open control socket at path: /var/lib/rspamd/rspamd.sock mode=0600

### ISSUE THREAD

**Issue by NothingButStupid** [rspamd/rspamd#3950]
Hi  there, first of all thank you of the product "Rspamd" it's so nice  ,there is some problem when I used Rspamd
the "var/log/rspamd/rspmad.log" prints  these "cannot open control socket at path: /var/lib/rspamd/rspamd.sock mode=0600"
may I know why? and what will this affect  thank you 
good wish!

**Comment by vstakhov** [comment]
Not an issue, closing.
