### ISSUE TITLE
How can  my rspamd talk to   clamav

### ISSUE THREAD

**Issue by NothingButStupid** [rspamd/rspamd#3951]
hi there, there is a problem that has bothered me for seven days. I have read many articles and haven't solved it。
that is   how  could  I use clamAV to scan my attachments in email
my test email has a  virus  named  shell.elf
my antivirus cnf is this:
***************************************
 modules.d/antivirus.conf
antivirus {
 clamav {
    # If set force this action if any virus is found (default unset: no action is forced)
    # action = "reject";
    # message = '${SCANNER}: virus found: "${VIRUS}"';
    # Scan mime_parts separately - otherwise the complete mail will be transferred to AV Scanner
    #scan_mime_parts = true;
    # Scanning Text is suitable for some av scanner databases (e.g. Sanesecurity)
    #scan_text_mime = false;
    #scan_image_mime = false;
    # If `max_size` is set, messages > n bytes in size are not scanned
    #max_size = 20000000;
    # symbol to add (add it to metric if you want non-zero weight)
    symbol = "CLAM_VIRUS";
    # type of scanner: "clamav", "fprot", "sophos" or "savapi"
    type = "clamav";
    log_clean = true;
    action = "reject";
    attachments_only = false;
    message = '${SCANNER}: virus found: "${VIRUS}"'
    scan_mime_parts = true;
    scan_text_mime = true;
    scan_image_mime = true;
    patterns {
      JUST_EICAR = '^Eicar-Test-Signature$';
    }
    # For "savapi" you must also specify the following variable
    #product_id = 12345;
    # You can enable logging for clean messages
    #log_clean = true;
    # servers to query (if port is unspecified, scanner-specific default is used)
    # can be specified multiple times to pool servers
    # can be set to a path to a unix socket
    # Enable this in local.d/antivirus.conf
      servers = "127.0.0.1:3310";
     #servers = /var/run/clamav/clamd.ctl;
    # if `patterns` is specified virus name will be matched against provided regexes and the related
    # symbol will be yielded if a match is found. If no match is found, default symbol is yielded.
    #patterns {
      # symbol_name = "pattern";
    #  JUST_EICAR = '^Eicar-Test-Signature$';
    #}
    patterns_fail {
         JUST_EICAR = '^Eicar-Test-Signature$';
      # symbol_name = "pattern";
      #CLAM_PROTOCOL_ERROR = '^unhandled response';
    }
    # `whitelist` points to a map of IP addresses. Mail from these addresses is not scanned.
    #whitelist = "/etc/rspamd/antivirus.wl";
  }

  .include(try=true,priority=5) "${DBDIR}/dynamic/antivirus.conf"
  .include(try=true,priority=1,duplicate=merge) "$LOCAL_CONFDIR/local.d/antivirus.conf"
  .include(try=true,priority=10) "$LOCAL_CONFDIR/override.d/antivirus.conf"
}
***************************************************
my clamAV has not print any log:
****************************************************
clamav@c6f753054c7f:/$ tail /var/log/clamav/clamav.log 
Sat Oct 30 12:21:47 2021 -> Reading databases from /var/lib/clamav
Sat Oct 30 12:22:06 2021 -> Database correctly reloaded (8572871 signatures)
Sat Oct 30 12:22:06 2021 -> WARNING: lstat() failed on: /home/python/test
Sat Oct 30 12:23:10 2021 -> Reading databases from /var/lib/clamav
Sat Oct 30 12:23:29 2021 -> Database correctly reloaded (8572871 signatures)
Sat Oct 30 12:23:29 2021 -> WARNING: lstat() failed on: /home/python/test
Sat Oct 30 12:24:15 2021 -> Reading databases from /var/lib/clamav
Sat Oct 30 12:24:34 2021 -> Database correctly reloaded (8572871 signatures)
Sat Oct 30 12:24:34 2021 -> WARNING: lstat() failed on: /home/python/test
Sat Oct 30 13:54:18 2021 -> SelfCheck: Database status OK.
 ************************************************
What's wrong with me？
or there is anther setting I dont   notice？？
Looking forward to reply
thank you!

**Comment by vstakhov** [comment]
Not an issue, closing.

**Comment by NothingButStupid** [comment]
hi,  may I know the resason :)

**Comment by NothingButStupid** [comment]
> Not an issue, closing.

hi thank you for  your reply  but   can you  help me  :(
