### ISSUE TITLE
[Feature] Remove trailing spaces from DKIM signature

### ISSUE THREAD

**Issue by gemal** [rspamd/rspamd#3955]
if you have a DKIM signature and it contains a space after the DKIM public key like:

"k=rsa; p=MIGfxxxxxxxx "
note the trailing space

then "rspamd" marks the mails as spam

Technically the space is not supposed to be there but most only DKIM checkers will allow this so it's extremely hard to find this "error"

**Comment by flowerysong** [comment]
> Technically the space is not supposed to be there

This is incorrect; it might be prettier without it and the whitespace is not required, but it is allowed. The DKIM-Signature header is a tag-list. From RFC 6376 section 3.2:

>   tag-list  =  tag-spec *( ";" tag-spec ) [ ";" ]
 >  tag-spec  =  [FWS] tag-name [FWS] "=" [FWS] tag-value [FWS]

**Comment by vstakhov** [comment]
It is not about DKIM signature, it is about DKIM public key record.

**Comment by flowerysong** [comment]
My bad, I evidently cannot read. But the same thing applies, since the DNS record is also a tag-list.

**Comment by vstakhov** [comment]
Do you have a sample to test btw?
