### ISSUE TITLE
SETTINGS_CHECK failed after Update from 2.7 to 3.1

### ISSUE THREAD

**Issue by TomFuch** [rspamd/rspamd#3957]
After Update from Version 2.7 to 3.1 i got many of this Warnings / Errors...

`call to (SETTINGS_CHECK) failed (2): /usr/share/rspamd/plugins/settings.lua:45: invalid invocation: settings has been already set; trace: [1]:{[C]:-1 - set_settings [C]}; [2]:{/usr/share/rspamd/plugins/settings.lua:45 - apply_settings [Lua]}; [3]:{/usr/share/rspamd/plugins/settings.lua:372 - <unknown> [Lua]};`

Has anybody an Idea?

**Comment by vstakhov** [comment]
The idea is exactly in the error description.

**Comment by TomFuch** [comment]
I know the error description. The Problem is that I got many, really many spams from gmail.com ( undisclosed recipients ) . I wrote this custom user setting

`id = "reject_undisclosed_recipients";
priority = high;
from = "@gmail.com";
header = {
    "To" = '/^[<"]?undisclosed[- ]recipients?\b.*:/i';
}
apply {
    R_UNDISC_RCPT = 10.0;
}`

**Comment by kartoffelheinz** [comment]
I got the same error. How do I find out which setting causes this? The description/trace does unfortunately not hint at which custom settings file it cannot apply.

**Comment by TomFuch** [comment]
I compared the timestamp of the warning with the timestamp of the email in the history and tried to make an assignment. I think it is not an error message but a warning, because my custom settings are still applied. I am just asking myself, for example, how I can change the symbol R_UNDISC_RCPT in a custom setting without warning. The following rule is completely ignored. But WHY?

`id = "reject_undisclosed_recipients";
priority = 5;
from = "@gmail.com";
header = {
    "To" = '/^[<"]?undisclosed[- ]recipients?\b.*:/i';
}
apply {
    TFAMG_GMAIL_R_UNDISC_RCPT = 10;
}
symbols ["TFAMG_GMAIL_R_UNDISC_RCPT"]`

**Comment by fatalbanana** [comment]
> The Problem is that I got many, really many spams from gmail.com ( undisclosed recipients ) . I wrote this custom user setting

It's a misuse of settings module: you would want to use composites+multimap/rules or a rule for this.

> How do I find out which setting causes this?

Setting `debug_modules = ["settings"]` in `local.d/logging.inc` should help.

**Comment by TomFuch** [comment]
> > The Problem is that I got many, really many spams from gmail.com ( undisclosed recipients ) . I wrote this custom user setting
> 
> It's a misuse of settings module: you would want to use composites+multimap/rules or a rule for this.
> 
> > How do I find out which setting causes this?
> 
> Setting `debug_modules = ["settings"]` in `local.d/logging.inc` should help.

Thanks, but why misuse? I only would change the weight of the "R_UNDISC_RCPT" Symbol to 10 if a mail comes from @gmail.com. Isn't that the job of Custom Settings?

**Comment by kartoffelheinz** [comment]
Thanks for suggesting the debug_modules. We managed to find out that from 3.1 onwards, it seems only one single setting group can be applied (or it was like this before, but did not log any errors if multiple settings matched). 

We had one group with authenticated = yes and another with local = yes. And since we act as some kind of smarthost, we had authenticated mails which were also from localnets, thus triggering both groups and having rspamd log this error message.

Our solution for now was to set "authenticated = no;" in the localnet-group, but I'm not sure I like that workaround to be honest.

I am not able to assess whether this behaviour (only single group can match) is a bug or intentional. Would be glad to have clarification on that.

**Comment by TomFuch** [comment]
This User Setting also doesn't work:

`priority = high;
hostname = "/.*isp-cbl-smtp00(1|2).cablelink.at/";
apply {
    symbols_disabled = ["HFILTER_HOSTNAME_1", "HFILTER_HOSTNAME_2", "HFILTER_HOSTNAME_3"];
}`

**Error / Warning:**

call to (SETTINGS_CHECK) failed (2): /usr/share/rspamd/plugins/settings.lua:45: invalid invocation: settings has been already set; trace: [1]:{[C]:-1 - set_settings [C]}; [2]:{/usr/share/rspamd/plugins/settings.lua:45 - apply_settings [Lua]}; [3]:{/usr/share/rspamd/plugins/settings.lua:372 - <unknown> [Lua]};

**Comment by NulledUI** [comment]
> This User Setting also doesn't work:
> 
> `priority = high; hostname = "/.*isp-cbl-smtp00(1|2).cablelink.at/"; apply { symbols_disabled = ["HFILTER_HOSTNAME_1", "HFILTER_HOSTNAME_2", "HFILTER_HOSTNAME_3"]; }`
> 
> **Error / Warning:**
> 
> call to (SETTINGS_CHECK) failed (2): /usr/share/rspamd/plugins/settings.lua:45: invalid invocation: settings has been already set; trace: [1]:{[C]:-1 - set_settings [C]}; [2]:{/usr/share/rspamd/plugins/settings.lua:45 - apply_settings [Lua]}; [3]:{/usr/share/rspamd/plugins/settings.lua:372 - [Lua]};

Let's try to increase priority level to positive integer value than high (3), the idea is to your rule must be matched first than any of  your existing rules
