### ISSUE TITLE
[BUG,regression] rspamc learn_spam: HTTP error: 404, all learn conditions denied learning spam in default classifier

### ISSUE THREAD

**Issue by hildeb** [rspamd/rspamd#3961]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

After upgrade from 3.0-2\~focal to 3.1-1\~focal 

`% rspamc learn_spam $tempfile`
results in
```
Results for file: /tmp/tmp.0NQpmrIK2q (0.004 seconds)
HTTP error: 404, all learn conditions denied learning spam in default classifier
```
in 3.0.2 this worked as expected (i.e. learned as spam or not learned, when it's already know to be spam)

### Versions

Rspamd daemon version 3.1
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

**Comment by arusi01** [comment]
Same bug https://github.com/rspamd/rspamd/issues/3956

**Comment by vstakhov** [comment]
Duplicate of #3956
