### ISSUE TITLE
[Feature] [MX Check module] store cache under the mx domain instead of sender domain

### ISSUE THREAD

**Issue by prey87** [rspamd/rspamd#3966]
The "mx check" module checks if the MX servers entered for a domain are reachable. The result is then stored in Redis. As far as I have seen correctly, the value is stored for the sender domain and not under the mx domain.

So let's assume I get 100 emails from different domains, but they all have the same MX records ( maybe customers of a webhoster or an isp), then Rspamd also checks the same MX server 100 times.

Then wouldn't it be better to cache the result of the MX server instead of the sender domain?

Then I noticed that the connection to the MX server is established during the check and is held until the first reply of the MX server, but then the connection is simply closed without a quit, so on the MX server there is a "lost connection after CONNECT", is this so wanted and also useful?

**Comment by vstakhov** [comment]
The problem is that MX domain is unknown unless MX request is done. I've not even thought that the problem of many domains per one MX record is even possible to be honest. Another option is to store MX check results for both domains and MX records if they are different. That will increase Redis load but it will fix the problem as is.

In the meantime I have added `QUIT` command support.

**Comment by vstakhov** [comment]
Or no, that's quite a bad idea due to many servers that do smtp greeting tarpitting. It must be configured I suppose.

**Comment by prey87** [comment]
> The problem is that MX domain is unknown unless MX request is done. I've not even thought that the problem of many domains per one MX record is even possible to be honest. Another option is to store MX check results for both domains and MX records if they are different. That will increase Redis load but it will fix the problem as is.

Wouldn't it be possible to make a DNS query of the MX records of domain.com?

The result would be
MX mail01.hoster.com
MX mail02.hoster.com
After that it will be checked if there is an entry for the MX domains in Redis and if not, the MX check will be executed.

Or have I misunderstood your answer?
