### ISSUE TITLE
[Feature] Emjois in Maps

### ISSUE THREAD

**Issue by flaviozluca** [rspamd/rspamd#3970]
Dear masters!

I believe Emojis are not supported in maps, correct? 

I think it can help quite a bit to detect undesired messages, which usually use them.

Pls consider it?

PS - other older post about this: https://github.com/rspamd/rspamd/discussions/3834#discussioncomment-1086602

Thanks!

**Comment by vstakhov** [comment]
You can use unicode regexps in the maps as well. Not an issue, closing.
