### ISSUE TITLE
[BUG] delivery status notifications should not get BROKEN_HEADERS 

### ISSUE THREAD

**Issue by kasak87** [rspamd/rspamd#3983]
**Describe the bug**
When normal delivery status notifications is cheked, they always get BROKEN_HEADERS symbol, because of empty "mail from" in envelope. 

### Steps to Reproduce

1. Use default rspamd config.
2. Just wait for any delivery status notification. 

**Expected behavior**
Empty "mail from" header is not "broken", sometimes it should be empty. 

DSNs should have empty "mail from" as described in RFC3464 [https://datatracker.ietf.org/doc/html/rfc3464]()

>  The envelope sender address of the DSN SHOULD be chosen to ensure that no delivery status reports will be issued in response to the DSN itself, and MUST be chosen so that DSNs will not generate mail loops. Whenever an SMTP transaction is used to send a DSN, the MAIL FROM command MUST use a NULL return address, i.e., "MAIL FROM:<>".

### Versions

Rspamd daemon version 3.0 from OpenBSD 7.0 packages. 
Same behavior were in 2.7 from OpenBSD 6.9

**Comment by vstakhov** [comment]
The standard explains **envelope** from and not the `From` header. From **header** must be valid in all cases. From the same RFC:

```
The From field of the message header of the DSN SHOULD contain the
   address of a human who is responsible for maintaining the mail system
   at the Reporting MTA site (e.g., Postmaster), so that a reply to the
   DSN will reach that person. 
```

So there is nothing to fix on Rspamd side.

**Comment by kasak87** [comment]
> The standard explains **envelope** from and not the `From` header. From **header** must be valid in all cases. From the same RFC:
> 
> ```
> The From field of the message header of the DSN SHOULD contain the
>    address of a human who is responsible for maintaining the mail system
>    at the Reporting MTA site (e.g., Postmaster), so that a reply to the
>    DSN will reach that person. 
> ```
> 
> So there is nothing to fix on Rspamd side.

exactly! Here is sample message with filled "From" and empty "mail from"

`Return-Path: <>
Received: from mail.tvema.ru (LHLO mail.tvema.ru) (212.233.112.11) by
 mail.tvema.ru with LMTP; Thu, 18 Nov 2021 15:20:36 +0300 (MSK)
Received: from localhost (localhost [127.0.0.1])
	by mail.tvema.ru (Postfix) with ESMTP id 5A1CD426358D
	for <fedorova@tvema.ru>; Thu, 18 Nov 2021 15:20:36 +0300 (MSK)
Received: from mail.tvema.ru ([127.0.0.1])
	by localhost (mail.tvema.ru [127.0.0.1]) (amavisd-new, port 10026)
	with ESMTP id gC8Pb9Z2IuhW for <fedorova@tvema.ru>;
	Thu, 18 Nov 2021 15:20:36 +0300 (MSK)
Received: from gater.ugr.tvema.ru (gater.ugr.tvema.ru [172.16.0.1])
	by mail.tvema.ru (Postfix) with ESMTPS id 33665426351A
	for <fedorova@tvema.ru>; Thu, 18 Nov 2021 15:20:36 +0300 (MSK)
X-Spam: yes
X-Spam-Score: 9.899999 / 15
X-Spam-Status: Yes, score=9.900 required=15.000
	tests=[ARC_NA=0.000, ARC_SIGNED=0.000, ASN=0.000, BAYES_SPAM=5.100
	BOUNCE=-0.100, BROKEN_HEADERS=10.000, DMARC_POLICY_ALLOW=-0.500
	FROM_NO_DN=0.000, GREYLIST=0.000, MIME_GOOD=-0.100, MIME_TRACE=0.000
	NEURAL_SPAM=0.000, ONCE_RECEIVED=0.100, PREVIOUSLY_DELIVERED=0.000
	RCPT_COUNT_ONE=0.000, RCVD_COUNT_ONE=0.000, RCVD_IN_DNSWL_MED=-0.400
	RCVD_TLS_ALL=0.000, REPLY=-4.000, R_DKIM_NA=0.000, R_SPF_ALLOW=-0.200
	TO_DN_NONE=0.000, TO_MATCH_ENVRCPT_ALL=0.000]
X-Spam-Flag: YES
ARC-Seal: i=1; s=dkim; d=tvema.ru; t=1637238035; a=rsa-sha256; cv=none;
	b=NuEVfmmPlvd4pIdM2R9MWtnSRVL4+6pA/RB9AofDg/Z8AXOeonM+rjFoO+3CFZKeQ1USTv
	AphNBCLhPfKwO/LwldaxeHalJgUeob6eE65J37RP+AnmHxEr95JMsLF19gLYzqWdhFBRW6
	NhZgPfoaO6kr9zO/tkajEsSSM9t19eI=
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=tvema.ru;
	s=dkim; t=1637238035;
	h=from:from:reply-to:subject:subject:date:date:message-id:message-id:
	 to:to:cc:mime-version:mime-version:content-type:content-type:
	 in-reply-to:in-reply-to:references:references;
	bh=DSdCLAYL5LI7rIYBIMwI8CnzrXjj1X91sl6iUySR1+A=;
	b=RcbNtDXvloQy63tgZZJGVBiLc9mAkO5KGZPNc5Bj1j6mXC16maaUldmfKwshyo08pDZgJ4
	uD8/ZFux+/XF8tTVJ43Dh+4wFzKJ/WnayHw/XGKuq3o87JQfRPOtwejSzuKBYOMqv9geH7
	JjOBPImq1/jh15NjnvaC4boT+yAfulM=
ARC-Authentication-Results: i=1;
	tvema.ru;
	dkim=none;
	dmarc=pass (policy=reject) header.from=skbkontur.ru;
	spf=pass (tvema.ru: domain of ul-edge.skbkontur.ru designates 46.17.201.48 as permitted sender) smtp.helo=ul-edge.skbkontur.ru
Received: from ul-edge.skbkontur.ru (ul-edge.skbkontur.ru [46.17.201.48])
	by tvema.ru (OpenSMTPD) with ESMTPS id 2b8ba5af (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256:NO)
	for <fedorova@tvema.ru>;
	Thu, 18 Nov 2021 15:20:35 +0300 (MSK)
MIME-Version: 1.0
From: <postmaster@skbkontur.ru>
To: <fedorova@tvema.ru>`

**Comment by vstakhov** [comment]
I'm not sure it happens because of from header. Could your please share any of the problematic messages with me using my personal email?

**Comment by vstakhov** [comment]
Hum, you MTA sends an empty string for DSN instead of `<>`. I have added a workaround on Rspamd side but it looks weird.

**Comment by kasak87** [comment]
Thank you! I can assure you, this is not only my mta work like this, there are tons of similar mails, as you can see, bayes have autolearned from this messages and now consider them all as spam.

**Comment by kasak87** [comment]
no problems with new rspamd 3.2 in OpenBSD 7.1! 
Thanks a lot!
