### ISSUE TITLE
Web interface via https (ssl)

### ISSUE THREAD

**Issue by Talkabout** [rspamd/rspamd#3987]
## Summary

Any chance we will see https being supported for the web interface?

## Motivation

In my network I am trying to assure all web frontends are supporting https connections with certificates created by my own CA. Rspamd is an exception here as it is not possible to configure it to allow access via https.

## Describe alternatives you've considered

No real alternatives :)

## Additional context

None

**Comment by sriccio** [comment]
Maybe you should put it behind a reverse proxy (for example nginx ?)

There is an example nginx config for this in the docs.
https://rspamd.com/doc/quickstart.html#setting-up-the-webui

**Comment by Talkabout** [comment]
Thanks @sriccio 

was hoping for an integrated solution but yes, a reverse proxy is a possible solution. Is there a particular reason why rspamd allows http but not https?

**Comment by sriccio** [comment]
No idea, @vstakhov could probably answer this.

My guess is that it's maybe not worth the time for adding all the stack to handle https and certificates because rspamd is often used bundled on mailservers that already have a front http server (for webmail etc) that handle it perfectly ...

**Comment by Talkabout** [comment]
Viewing the statistics and configuring Rspamd wouldn't be possible via webmail :) I indeed have webmail set up but also require direct access to the Rspamd web frontend. Would be nice to have the option to use https here, but it is not a show stopper.

**Comment by vstakhov** [comment]
Not an issue.
