### ISSUE TITLE
[Feature] Allow disabling password auth on UNIX sockets

### ISSUE THREAD

**Issue by nbraud** [rspamd/rspamd#4000]
## Summary

Please allow disabling password-based authentication on the controller, when listening to a UNIX socket.

## Motivation

I have configured `rspamd` to only expose the controller on a UNIX socket, using a group to control which users may access it:

```
# /etc/rspamd/local.d/worker-controller.inc
bind_socket = "/var/run/rspamd/controller.sock mode=0660 owner=_rspamd group=rspamadm";
```

When exposing the administration interface to the Internet, Nginx handles the authentication; here's an example with password-based authentication, but it could also use client certificates, an SSO system, etc. :

```nginx
    location /rspamd/ {
        rewrite /rspamd(/.*) $1 break;
        proxy_pass http://unix:/var/run/rspamd/controller.sock;

        proxy_set_header Host      $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        auth_basic "Rspamd glasspane";
        auth_basic_user_file /etc/nginx/passwd/admins;
    }
```

In both cases, having Rspamd implement its own authentication mechanism is superfluous.

## Describe alternatives you've considered

I currently set a “dummy” password for Rspamd, but this still requires users of the WebUI to remember that password and input it.

## Additional context

I tried `trusted_ip`, but that doesn't quite do what I need:
- I cannot enumerate all possible IP addresses (the documentation doesn't mention CIDR support, and when I tried regardless it didn't work) ;
- Setting it to `unix:/var/run/rspamd/controller.sock` doesn't work despite the log message being
  > rspamd_controller_check_password: absent password has been specified; source ip: unix:/var/run/rspamd/controller.sock

  This is coherent with [the documentation](https://rspamd.com/doc/faq.html#how-to-use-the-webui-behind-a-proxy-server) but the log message should then mention the client's IP address:
  > When a connection comes from an IP listed in secure_ip or from a unix socket then Rspamd checks for two headers: X-Forwarded-For and, if that is not found- X-Real-IP. If one of those headers is found then Rspamd treats a connection as if it comes from the IP specified in that header. For example, X-Real-IP: 8.8.8.8 will trigger checks against secure_ip for 8.8.8.8.

**Comment by vstakhov** [comment]
As far as I see, this was adressed in Rspamd 1.0: https://github.com/rspamd/rspamd/commit/5217952d30e73c463f9f83c8c891c4c9bdc5881d

**Comment by vstakhov** [comment]
The only issue here is that Nginx actually passes the real client's IP, so the checks go through that ip and not unix socket. In fact, I don't understand what are you trying to solve: if you want some forwarded clients to authorise without a password, then add theirs **real ips** to the `trusted_ip` list. Nginx can use unix socket indeed but Rspamd can still understand that the real address is a different one due to forwarding logic.

**Comment by vstakhov** [comment]
Also, if you remove `X-Forwarded-For` header, then Rspamd will have no options but to use a unix socket trusted credentials.

**Comment by vstakhov** [comment]
Another option is to remove all passwords completely - it will also work, leaving nginx to deal with that stuff.

**Comment by nbraud** [comment]
> Another option is to remove all passwords completely - it will also work, leaving nginx to deal with that stuff.

That is exactly what I was trying to do  >_>'

**Comment by kevincox** [comment]
I was also trying to manage the auth in nginx and that removing the `X-Forwarded-For` header worked perfectly.

```nginx
proxy_set_header X-Forwarded-For "";
```
