### ISSUE TITLE
rate limit exclusion

### ISSUE THREAD

**Issue by mohammad-hachem** [rspamd/rspamd#4018]
I an using Rspamd rate limit module as per the below configuration:
rates {
    outgoing_limit = {
       selector = 'from:addr';
      bucket = {
        burst = 100;
        rate = "1 / 1m"; # leak 1 message per minute
      }
    }
  }

I need to exclude some email addresses form this rate_limit, I tried to use whitelisted_user as per the below:
whitelisted_user = [
  “broadcast@idm.net.lb”,
  “collection@idm.net.lb”
];

But it’s not working and I think this is due to the fact that whitelisted_user is for authenticated users and not email addresses as per the documentation.
If this is the case any way to exclude specific email addresses from the rate limit I am applying?

**Comment by vstakhov** [comment]
You might probably want to use [conditions](https://rspamd.com/doc/lua/rspamd_config.html#m75087) for `RATELIMIT_CHECK` symbol.
