### ISSUE TITLE
configwizard creates private DKIM keys world-readable

### ISSUE THREAD

**Issue by ThiefMaster** [rspamd/rspamd#4023]
I just use the config wizard to create a rspamd config, and let is generate DKIM keys. Those keys are created world-readable and neither are any of the parent directories restricted. Regardless of the active umask, creating private keys in such a manner is probably a bad idea...

In case it matters (since `/var/lib/rspamd` is created by the distribution's package manager), I'm using Gentoo, but regardless of the permissions the key file itself should probably be more restricted...

**Comment by vstakhov** [comment]
Well, I have redesigned it to use 0600 mode by default for private keys. I'm not quite sure it will significantly help though - a user would likely use their own Unix user whilst Rspamd will run using `_rspamd` user, so an extra `chown` will still likely be required. I don't know what to do with that aside of preloading private keys as `root` user in the master process. However, it will not cover many possibilities Rspamd has, such as dynamic maps for the private keys...

**Comment by moisseev** [comment]
I would use `0640` instead of `0600`. 
Private keys usually created by root and should be readable to rspamd.

As you can see in the example below, in case of `0600` an extra `chmod` (or `chown`) is required. With `0640` we would get desired permissions right after `dkim_keygen` execution.
```
moiseev@mx:/var/db/rspamd/dkim# rspamadm dkim_keygen -s dkim -d example.org -k example.org.dkim.key > example.org.key.pub
moiseev@mx:/var/db/rspamd/dkim# ll example*
-rw-------  1 root  rspamd  916 30 дек.  08:47 example.org.dkim.key
-rw-r--r--  1 root  rspamd  270 30 дек.  08:47 example.org.key.pub
```

**Comment by vstakhov** [comment]
I do agree with @moisseev, however, it will work merely if the target directory has owner `_rspamd` which is likely but not guaranteed.

**Comment by moisseev** [comment]
@vstakhov Package maintainers should always take care of setting correct directories permissions. There's not much we can do otherwise.
