### ISSUE TITLE
[BUG] Rspamd adds header instead of rejecting an email

### ISSUE THREAD

**Issue by denisfidel** [rspamd/rspamd#4035]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
We detected an example of message which should be rejected, but instead only header is added: `default: T (add header): [21.20/7.50] `. Since it is an outgoing message and clearly a spam, it later result in damaged reputation of our servers. We checked `force_actions` module, but it does not seem like it is the source of problem, since there is only one rule there and it almost certainly not related.

Here are the logs of related task:
```
Jan  9 02:40:17 <host> rspamd[607485]: <b7e477>; task; rspamd_worker_body_handler: accepted connection from ::1 port 45124, task ptr: 00007F8C8AF6ACE0
Jan  9 02:40:17 <host> rspamd[607485]: <b7e477>; task; rspamd_message_parse: loaded message; id: <message-id>; queue-id: <queue-id>; size: 3344; checksum: <bcdd2e10ff54a190ac6d7e73cd3e76a9>
Jan  9 02:40:17 <host> rspamd[607485]: <b7e477>; task; rspamd_mime_text_part_utf8_convert: converted text part from ISO-8859-1 ('iso-8859-1' announced) to UTF-8 inlen: 2875, outlen: 2875 (2875 UTF16 chars)
Jan  9 02:40:17 <host> rspamd[607485]: <b7e477>; task; rspamd_mime_part_detect_language: detected part language: en
Jan  9 02:40:17 <host> rspamd[607485]: <b7e477>; lua; settings.lua:367: <message-id> apply static settings outgoingAuth (id = 640072947); authenticated matched; priority low
Jan  9 02:40:17 <host> rspamd[607485]: <b7e477>; lua; greylist.lua:204: skip greylisting for local networks and/or authorized users
Jan  9 02:40:17 <host> rspamd[607485]: <b7e477>; lua; spf.lua:186: skip SPF checks for local networks and authorized users
Jan  9 02:40:17 <host> rspamd[607485]: <b7e477>; task; dkim_symbol_callback: skip DKIM checks for local networks and authorized users
Jan  9 02:40:17 <host> rspamd[607485]: <b7e477>; lua; dmarc.lua:349: skip DMARC checks as either SPF or DKIM were not checked
Jan  9 02:40:17 <host> rspamd[607485]: <b7e477>; lua; once_received.lua:99: Skipping once_received for authenticated user or local network
Jan  9 02:40:17 <host> rspamd[607485]: <b7e477>; task; dkim_module_load_key_format: cannot load dkim key <path>.key: cannot stat key file: '<key-path>' No such file or directory
Jan  9 02:40:21 <host> rspamd[607485]: <b7e477>; task; rspamd_symcache_finalize_item: slow rule: DCC_CHECK(230): 3921.28 ms; enable slow timer delay
Jan  9 02:40:21 <host> rspamd[607485]: <b7e477>; task; rspamd_redis_connected: skip obtaining bayes tokens for BAYES_SPAM of classifier bayes: not enough learns 10; 200 required
Jan  9 02:40:21 <host> rspamd[607485]: <b7e477>; task; rspamd_redis_connected: skip obtaining bayes tokens for BAYES_HAM of classifier bayes: not enough learns 0; 200 required
Jan  9 02:40:21 <host> rspamd[607485]: <b7e477>; task; rspamd_stat_classifiers_process: skip statistics as SPAM class is missing
Jan  9 02:40:21 <host> rspamd[607485]: <b7e477>; task; rspamd_task_write_log: id: <message-id>, qid: <queue-id>, ip: <IP>, user: <username>, from: <from>, (default: T (add header): [21.20/7.50] [BITCOIN_FREEMAIL(10.00){},LEAKED_PASSWORD_SCAM(7.00){},BITCOIN_ADDR(2.00){bc1q7ak5cfxg4ftzt4s2jaaa4vdy6ltwj4cupny2zu;},LEAKED_PASSWORD_SCAM_RE(2.00){},MIME_HTML_ONLY(0.20){},ARC_NA(0.00){},ASN(0.00){asn:20454, ipnet:<IP>/24, country:US;},FREEMAIL_TO(0.00){<domain>;},FROM_EQ_ENVFROM(0.00){},FROM_HAS_DN(0.00){},MID_RHS_MATCH_FROM(0.00){},MIME_TRACE(0.00){0:~;},RCPT_COUNT_ONE(0.00){1;},RCVD_COUNT_ZERO(0.00){0;},TO_DN_NONE(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){}]), len: 3344, time: 4031.774ms, dns req: 48, digest: <bcdd2e10ff54a190ac6d7e73cd3e76a9>, rcpts: <smtp-rcpt>, mime_rcpts: <mime-rcpt>, settings_id: outgoingAuth
```

### Steps to Reproduce

Don't know how to reporoduce it.

**Expected behavior**
Message should be rejected

### Versions
Rspamd version: `Rspamd daemon version 3.1`, we updated from 3.0, where there was no problems.
OS info: 
```
  Operating System: AlmaLinux 8.5 (Arctic Sphynx)
       CPE OS Name: cpe:/o:almalinux:almalinux:8::baseos
            Kernel: Linux 4.18.0-348.7.1.el8_5.x86_64
      Architecture: x86-64
```

**Comment by denisfidel** [comment]
We also detected problems with settings module, since updating to 3.1. Actually our problem is the same as described [here](https://github.com/rspamd/rspamd/issues/3957#issuecomment-961833881), except when setting `authenticated = no` in local group the problem preserves. 

The original problem might be connected to setting problems, since reject doesn't happen when user is authenticated i.e. when settings outgoingAuth is set.

**Comment by vstakhov** [comment]
There is something with your settings. I have no ideas of what's in your `outgoingAuth` settings, so I cannot help at all I'm afraid...

**Comment by denisfidel** [comment]
Our outhgoingAuth and outgoingLocal is just changing reject trashold (see below). As mentioned, I tried to add `authenticated = no` in outgoingLocal group, but the problem stays the same. 

```
outgoingAuth {
	id = "outgoingAuth";
	priority = low;
	authenticated = yes;
        apply {
                actions {
                        reject = 7.5;
                }
        }
}
outgoingLocal {
        id = "outgoingLocal";
        priority = low;
        local = yes;
        apply {
                actions {
                        reject = 10;
                }
        }
}
```

The thing that resolved the issue was changing the priority of outgoingAuth to medium. Now we don't get the settings error, and rejecting works as expected. But in my opinion it should work also if both priorities are the same.
