### ISSUE TITLE
[BUG] R_SUSPICIOUS_URL windows-1252 URL encoded link

### ISSUE THREAD

**Issue by lianee** [rspamd/rspamd#4045]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
legit mail flagged as R_SUSPICIOUS_URL

### Steps to Reproduce

1. [First Step]
send an email with the following link:
`<a href="https://www.example.com?source=d%E9mat%E9rialis%E9_TP">check</a>`
2. [Second Step]
 this email will be flagged as R_SUSPICIOUS_URL

**Expected behavior**
This email was not expected to trigger a R_SUSPICIOUS_URL

### Versions

\# rspamd --version
Rspamd daemon version 3.1
\# cat /etc/debian_version 
11.2

### Additional Information

While the link is windows-1252 encoded (the é character encoded as %E9) when it should probably be UTF-8 encoded (%C3%A9), it is legacy and perhaps it should not be flagged as high as R_SUSPICIOUS_URL, a 5 in default settings

**Comment by vstakhov** [comment]
I doubt this issue is worth to fix. Legacy encodings are rarely used for something meaningful nowadays, so penalising such emails in Rspamd might make world better. Aside that, it would be very hard to fix properly, as html encoding is a different beast comparing to mime encoding.

**Comment by iwikus** [comment]
Not sure, if this same issue, but from today I have seen legitimate emails rejected due high score and one matching rule is R_SUSPICIOUS_URL. It is email footer with image and url containing link to google search which did not changed and was not triggering before. URL code is

`<https://www.google.sk/maps/place/%C5%A0ustekova+3643%2F10,+851+04+Petr%C5%B
Ealka/@48.1294474,17.1218159,17z/data=!3m1!4b1!4m5!3m4!1s0x476c8911cb62a913:
0x487e8e0a490856bd!8m2!3d48.1294438!4d17.1240046>
`
