### ISSUE TITLE
[BUG] Yesterday's reports remain unsent

### ISSUE THREAD

**Issue by RealSebFox** [rspamd/rspamd#4053]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Reports with yesterday's date are not sent. Reports with the date of today have been sent. Reports with the date of yesterday remain where they are. This can be verified in redis and in the verbose output from `rspamadm dmarc_report`.

### Steps to Reproduce

1. After 00:00, list `SMEMBERS dmarc_idx;%YESTERDAYDATE%` in redis-cli.
2. Wait for the cron job to execute `rspamadm dmarc_report -v >> /tmp/dmarc.log` or execute manually.
3. list `SMEMBERS dmarc_idx;%YESTERDAYDATE%` in redis-cli again.

**Expected behavior**
I'd expect redis to show an empty list at step 3. However, the list is exactly the same as in step 1. 

### Versions

Rspamd daemon version 3.1

### Additional Information
/etc/rspamd/local.d/dmarc.conf
```
servers = "10.0.0.12";

actions = {
   quarantine = "add_header";
   reject = "add_header";
}

reporting {
  enabled = true;
  email = "REDACTED@REDACTED";
  org_name = "REDACTED";
  domain = "REDACTED";
  from_name = "REDACTED";
  helo = "REDACTED";
  bcc_addrs = ["REDACTED"]; # additional addresses to copy on reports
  msgid_from = REDACTED; # Msgid format
  max_entries = 1k; # Maxiumum amount of entries per domain
  keys_expire = 2d; # Expire date for Redis keys
}
```
* Redis has `bind 127.0.0.1 10.0.0.12` set.
* I have no intention to reject messages, not even when that's the policy.
* My cron job runs as root at 07:00 CET.

**Comment by RealSebFox** [comment]
Okay, it works if we create two cron jobs:

1. rspamadm dmarc_report $(date --date yesterday "+%Y%m%d")
1. rspamadm dmarc_report

That is still not quite as it's intended, because we don't want to send more than one report per domain every 24 hours at 07:00 CET. It's RFC compliant, but not very nice.

**Comment by vstakhov** [comment]
AFAIR, it is fixed in https://github.com/rspamd/rspamd/commit/cd9ba26ecb13c50fa3200f7d80394cdfd8b0089a
