### ISSUE TITLE
[BUG] lua_map maps are not loaded directly (documentation problem?), get_key not returning results.

### ISSUE THREAD

**Issue by eis-os** [rspamd/rspamd#4059]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

The lua api documentation doesn't mention lua maps aren't available while in plugin startup.
Queries simply fails until the map is loaded in the future. This may have undesired side affects.

The document should clarify: 

When is map data available after rspamd startup.
Is there a way to load maps directly.

If the loading is non deterministic, the documentation should need this information and rspamd should provide an option to load maps directly.

Sidenote, the comment in https://github.com/rspamd/rspamd/issues/3283#issuecomment-610338418 mentions that loading should work directly. This result in the same behaviour, as seen in the sample below:

### Steps to Reproduce
Create a new lua file plugin.d, enable it via config: 

```
local rspamd_logger = require "rspamd_logger"
local lua_maps = require "lua_maps"

local mimemap = lua_maps.rspamd_map_add('mime_types', 'file', 'map','mime types map')
local result = mimemap:get_key('application/json');
print("mimemap result:", result)

rspamd_logger.errx(rspamd_config, 'TEST TEST mimemap result: %1', result)
```

Even loading static maps via lua_maps.map_add_from_ucl by using 'file:///etc/rspamd/somemap.map' or '/etc/rspamd/somemap.map'  as source won't give results.

**Expected behavior**
If there is a local map or failback map, get_key should return results from data sources.

### Versions
Rspamd daemon version 3.1  
on Debian GNU/Linux 11 (bullseye))

**Comment by vstakhov** [comment]
Yes, you can query maps merely in `on_load` scripts as maps are actually loaded on per-worker base and each worker has it's own maps copy. It is especially true for `http` (remote) maps and some workers do not even load this sort of maps.

**Comment by eis-os** [comment]
For clarification, this means:

- Maps have to be defined when the plugin runs for the first time (not in a callback)
- Maps can be used only in callbacks (querying the data in a map), each worker has it's own copy
- A callback / worker will have local map data directly after startup? 

So it’s not possible to load a map, then use the map data to load additional maps...
