### ISSUE TITLE
[BUG] flagged PHISHING (4.00) on cyrillic domains xn--?.xn--p1ai

### ISSUE THREAD

**Issue by kitolori** [rspamd/rspamd#4065]
### Prerequisites

* [Х] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
legit mail flagged as PHISHING (4.00)

**Steps to Reproduce**
[First Step]
send an email with the following link:
`<a href="http://www.xn--80akgskdkd.xn--p1ai/">www.Спаморез.РФ</a>`

[Second Step]
this email will be flagged as PHISHING 

**Expected behavior**
This email was not expected to trigger a PHISHING 

Versions
# rspamd --version
Rspamd daemon version 3.2-git.0956f41e2

# uname -a
Linux h601 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Additional Information
Souce of email messsge 

From: <>
To: <>
Subject: test
MIME-Version: 1.0
X-Mailer: Yamail [ http://yandex.ru ] 5.0
Date: Tue, 08 Feb 2022 17:22:55 +0300
Content-Transfer-Encoding: base64
Content-Type: text/html; charset=utf-8

PGEgaHJlZj0iaHR0cDovL3d3dy54bi0tODBha2dza2RrZC54bi0tcDFhaS8iPnd3dy7QodC/0LDQ
vNC+0YDQtdC3LtCg0KQ8L2E+

**Comment by vstakhov** [comment]
It should be fixed in the master branch, thank you for the report!
