### ISSUE TITLE
[BUG] Confusing naming and usage of 'external_relay'

### ISSUE THREAD

**Issue by markv9401** [rspamd/rspamd#4080]
## Summary

Please clean up both the actual code and definitely the documentation for rspamd regarding external relays.

## Motivation

Currently, external_relay naming is used in both the SPF and External Relay modules.

SPF module's external_relay doesn't exactly work as expected or stated in the documentation. It created very false and invalid headers for SPF authentication, stating that the domain assigned the said relay ip address as a sender. Which is not true at all. This is useless, might as well disable SPF checking.

External Relay's external_relay option does exactly what SPF module's should've all along, and what it states. It ignores the known relay and checks for the next Received from header, validates that one. It actually works very well and results in valid & true Authentication headers.

External Relay's documentation is just bad, though. The doc states one needs to create a 'hostname map' but it isn't exactly stated how a hostname map looks like. Furthermore, after reading the actual lua module's source and doing debug logging, I realised you absolutely need a key-value map with the name of your relay's hostname and value of "direct". This absolutely critical information is stated nowhere in documentation. (And actually I don't even really understand why you need k-v pairs with a static value at all? What's the use / point? Why can't it just be a normal map aka list of hostname(s)?)

## Describe alternatives you've considered

I believe the SPF module's external_relay is obsolete, broken, extremely confusing and unnecessary.
The External Relay module's external_relay is great, but I wonder if it really needs a key-value map at all instead of just a normal map?
If it does need a k-v map, please update the documentation to reflect that and the static value it needs to have!

**Comment by vstakhov** [comment]
`external_relay` in SPF is an outdated option indeed. It was used as a hack before `external_relay` plugin has been created. So it is a good idea to reflect that in the documentation.

**Comment by vstakhov** [comment]
>  If it does need a k-v map, please update the documentation to reflect that and the static value it needs to have!

It doesn't and actually I see no reasons why does it check for `direct` there. As a short term fix I will remove this check totally as it looks completely meaningless to me in the current [implementation](https://github.com/rspamd/rspamd/blob/master/src/plugins/lua/external_relay.lua#L162). 

@fatalbanana, could you please comment on the above? I don't see any other value checks for the `hostname_map` in the plugin...

**Comment by vstakhov** [comment]
Ah, probably I see the point. You first check the hostname and ensure that the map entry specifies it as a `direct` relay of us and then look for the received headers finding any match, both direct and indirect. Well, you can imagine that this logic might be quite confusing ;) I would suggest to use separate maps to split that if needed. The vast majority of the plugin usage is a single external relay that forwards email to us. If some use cases are more complicated, it is better to add a separate map for indirect hits.

**Comment by fatalbanana** [comment]
Yes, the idea is to distinguish hosts who's mail we should apply munging to from hosts which may feature as intermediaries in the chain. The documentation is terrible on this point indeed.

**Comment by vstakhov** [comment]
I'd still suggest to use a separate map for indirect relays. It is a rare case, so it should not make the most common case more complicated or even affect it anyhow.

**Comment by fatalbanana** [comment]
Sure, it's likely not a useful distinction to make. If needed this behaviour could be achieved by adding a condition to the rule.

**Comment by markv9401** [comment]
Right, thanks @vstakhov  for the elaboration, makes sense to me too now why you'd need 'direct' :)
Thank you both for the replies / plans ahead, cheers

**Comment by markus-96** [comment]
Hello,
I am still encountering problems with this plugin. Here is my config:
```
### /etc/rspamd/local.d/external_relay.conf
enabled=true;

rules {
        EXTERNAL_RELAY_AUTHENTICATED {
                strategy = "hostname_map";
                hostname_map = [
                        "external1.relay.tld direct",
                        "external2.relay.tld direct",
                        "external3.relay.tld direct",
                        "external4.relay.tld direct",
                        "external5.relay.tld direct",
                        "external6.relay.tld direct",
                ];
        }
}
```
Another config I tried was:
```
### /etc/rspamd/local.d/external_relay.conf
enabled=true;

rules {
        EXTERNAL_RELAY_AUTHENTICATED {
                strategy = "hostname_map";
                hostname_map = "/etc/rspamd/maps.d/external_relay1.map";
        }
}
```
With a .map file:
```
### /etc/rspamd/maps.d/external_relay1.map
external1.relay.tld direct
external2.relay.tld direct
external3.relay.tld direct
external4.relay.tld direct
external5.relay.tld direct
external6.relay.tld direct
```
This shows up in the log:
```
external_relay; external_relay.lua:163: sending hostname (external4.relay.tld) is not a direct relay
```
