### ISSUE TITLE
[BUG] Incorrect Message-ID is returned for headers with comments

### ISSUE THREAD

**Issue by citrin** [rspamd/rspamd#4081]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

Text in `(` `)` is a comment according to RFC5322 and should be ignored in structured headers including `Message-ID` header:
```
comment         =   "(" *([FWS] ccontent) [FWS] ")"
CFWS            =   (1*([FWS] comment) [FWS]) / FWS
message-id      =   "Message-ID:" msg-id CRLF
msg-id          =   [CFWS] "<" id-left "@" id-right ">" [CFWS]
```

Rspamd as I can see tries to strip comments, but doesn't do this properly.

### Steps to Reproduce

1. Create a test message, e. g.:
```
MIME-Version: 1.0
Content-Type: text/plain
Content-Transfer-Encoding: 7bit
Message-ID: <test_id@example.net> (added by postmaster@example.net)

.
```
2. Scan with Rsapmd
3. Observe in logs:
`... rspamd_task_write_log: id: <test_id@example.net>?> ...`
and in rspamc output:
`Message-ID: test_id@example.net>?`

**Expected behavior**

`rspamd_task_write_log: id: <test_id@example.net>` in logs and `Message-ID: test_id@example.net` in rspamc output.

### Versions

```
Rspamd daemon version 3.1
```

**Comment by citrin** [comment]
One more observation - for header like:
`Message-ID: <(rfc)(ignorant)(id)@example.net>` rspamc shows `Message-ID: @example.net` which is not exactly what we want here because RFC allows `CFWS` before and after ID, but not inside.

I haven't looked how `CFWS` stripping is implemented but I would try to parse Message-ID in a following way:
* try to match `[CFWS] "<" id-left "@" id-right ">" [CFWS]` using ragel
* if we have a match -> return `id-left@id-right`
* if there is no match -> return original header content (with `<` `>` stripped if they are present)

**Comment by vstakhov** [comment]
No, I think the reason is in the space character. We have unit tests for `rspamd_strip_smtp_comments_inplace` and I have tested your sample, so I can say that it works properly. I will investigate further...

**Comment by vstakhov** [comment]
I have fixed one case but not the parsing itself. TBH, there is no dedicated state machine to parse Message-Id headers, so I'll leave it as a TODO when I would have some spare time.
