### ISSUE TITLE
[BUG] lua_tcp_push_data: callback call failed: /usr/share/rspamd/lualib/lua_scanners/spamassassin.lua:173: attempt to compare number with nil

### ISSUE THREAD

**Issue by kartoffelheinz** [rspamd/rspamd#4088]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
rspamd sometimes logs an error after calling external_service spamassassin. It seems to still work though.

### Steps to Reproduce

1. Configure rspamd to use external_service spamassassin
2. Produce enough traffic / scans
3. Observe sporadic error messages

`lua_tcp_push_data: callback call failed: /usr/share/rspamd/lualib/lua_scanners/spamassassin.lua:173: attempt to compare number with nil`

**Expected behavior**
No error shows up

### Versions
rspamd --version: 3.1
Running debian 10 using rspamd repository.

This might be related to https://github.com/rspamd/rspamd/issues/3141

**Comment by kartoffelheinz** [comment]
It seems this might have been fixed by https://github.com/rspamd/rspamd/commit/7e86036a5c271dcaf69892bab826b9a3c29a987e but since there was no new release, I do not know for sure.

**Comment by kartoffelheinz** [comment]
I modified my local /usr/share/rspamd/lualib/lua_scanners/spamassassin.lua and restarted rspamd, but the error still occurs. Do I need to compile something?

**Comment by kartoffelheinz** [comment]
I made more tests and made sure, rspamd was running with my modified code. It seems the fixed regex does not account for negative scores. I changed the score-regex to (%-?%d+%.%d+), no more errors. Full line 173 now looks like this:
`local pattern_symbols = "X%-Spam%-Status: %S+, score%=(%-?%d+%.%d+) .* tests=(.*,)(%s*%S+).*"`

It would be nice if you could make a new commit fix with it.

**Comment by kartoffelheinz** [comment]
It would be nice to get this actually fixed in upstream :)

**Comment by c-rosenberg** [comment]
sry, forgot to commit after testing
