### ISSUE TITLE
Ignore no action in history

### ISSUE THREAD

**Issue by dziurr** [rspamd/rspamd#4098]
Hallo,
I'm looking for a way to exclude `no action` from history log.

--------------^ Click "Preview" for a nicer view!
We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks!

---

* Mailing list: https://lists.rspamd.com/mailman/listinfo (you can subscribe on that page or browse the archives)
* Telegram channel: http://t.me/rspamd
* Also have a look at the following page for more information on how to get support:
  https://rspamd.com/support.html

**Comment by rubo77** [comment]
it would be great to enhance the selectbox in the webinterface on the top left for the search with "Any but no action"
