### ISSUE TITLE
[BUG] Multimap with regex does not reject when `action = "reject"` is defined in multimap.conf

### ISSUE THREAD

**Issue by SnejPro** [rspamd/rspamd#4099]
### Prerequisites

- Rspamd with postfix

**Describe the bug**
- Multimap with regex does not reject when `action = "reject"` is defined in multimap.conf

### Steps to Reproduce

1. Create multimap-config - /etc/rspamd/local.d/multimap.conf
`
CUSTOM_BLACKLIST_SUBJECT {
	type = "header";
	header = "Subject";
	map = "/etc/rspamd/custom_lists/blacklist_subject.map";
	regexp = true;
	description = "mmmgw subject blacklist";
	action = "reject";
}
`
2. Create map-file - /etc/rspamd/custom_lists/blacklist_subject.map
`/.*SubjectWithThisContentIsSpam.*/i`
3. Mail is not rejected
4. Change map-file - /etc/rspamd/custom_lists/blacklist_subject.map
`/.*SubjectWithThisContentIsSpam.*/i     REJECT`

**Expected behavior**
Mail should be rejected in both cases

### Versions

Rspamd daemon version 3.1

### Additional Information

Debian 11

**Comment by vstakhov** [comment]
It is working as intended in the both cases for me.
