### ISSUE TITLE
[BUG] Ratelimit plugin counts smtp recipients twice if list includes gmail addresses with dots

### ISSUE THREAD

**Issue by ialexiad** [rspamd/rspamd#4104]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
When applying a custom ratelimit rule to limit the number of recipients one can send mail to per time unit, the plugin counts double the number of envelope recipients whenever at least one of them is a gmail address with dots in the username part.

This is not a 'ratelimit plugin' bug per se, as the plugin gets the count of smtp recipients like so:

```lua
local _,nrcpt = task:has_recipients('smtp')
```
which btw is not documented in the task module documentation. Using the below fixes it for me:

```lua
local nrcpt = 1
if task:has_recipients('smtp') then
  nrcpt = #task:get_recipients('smtp')
end
```

### Steps to Reproduce

1. Enable debug logging for the ratelimit plugin (to log the redis queries for the relevant bucket)
2. Create a custom ratelimit rule along the lines of:
```lua
custom_keywords.customrl = function(task)
  local user = task:get_user()

  if user then
    local rlHash = "rs_customrl_rcptcount_" .. user
    local bucket = {
        burst = 10;
        rate = "10 / 1h";
        symbol = "TEST_RCPT_LIMIT";
        message = "recipient limit reached, please try again later";
    }

    return rlHash, bucket
  end
end
```
3. Send an email to a gmail address, adding a dot in the username part (gmail ignores dots so you can place one or more anywhere you want).
4. Check the bucket entry manually using the redis hash you'll see in the logs. It will have a burst value of 2 even though you sent to just one recipient. Instead of checking the redis db manually, you can send another mail, which will cause the plugin to log the current bucket state (ie before accepting the second email). It will show a burst value of 2, minus the leak.

**Expected behavior**
The correct number of recipients should be taken into account.

### Versions
3.1 on FreeeBSD

### Additional Information
The `smtp_rcpts` log variable also contains the addresses twice, once with dots and once without.

**Comment by vstakhov** [comment]
That's a good catch, thank you! The problem here is in the API compatibility indeed. Initially, `task:has_recipients` was a quirk to get a number of recipients quickly without having to push all of them to Lua (especially when there are number of recipients). However, with aliases and, in particular, with the inroduction of the aliases-preservation logic, this assumption is no longer valid. I will fix it, thanks again.

**Comment by ialexiad** [comment]
I installed version 3.2 which includes the fix, but the issue remains, nrcpt still gets double the number of recipients.

**Comment by ialexiad** [comment]
@vstakhov should I open a new issue for this?
