### ISSUE TITLE
[BUG] - Multimap symbols scores does not work.

### ISSUE THREAD

**Issue by TempleNode** [rspamd/rspamd#4117]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

### Steps to Reproduce

add in multimap.conf

# local.d/multimap.conf
CONTENT_BLACKLISTED {
  type = "content";
  filter = "body"; # can be headers, full, oneline, text, rawtext
  map = "${LOCAL_CONFDIR}/content.map";
  symbols = ["CONTENT_BLACKLISTED1", "CONTENT_BLACKLISTED2"];
  regexp = true;
}

in content.map
# Symbol + score
/re1/ CONTENT_BLACKLISTED1:10
# Symbol with default score
/re2/ CONTENT_BLACKLISTED2
# Just a default symbol: CONTENT_BLACKLISTED
/re3/

**Expected behavior**
In the score, we should see the score of 10 for CONTENT_BLACKLISTED1

We see
CONTENT_BLACKLISTED1(0.000)[];

### Versions

Rspamd daemon version 3.1
Centos7.9

**Comment by vstakhov** [comment]
You mess up with scores and weights. `10.0` is a weight that is multiplied by score `0` (unknown score is `0` by default but it is configurable).

**Comment by TempleNode** [comment]
I added a default score 1.0 I get the same result

CONTENT_BLACKLISTED {
  type = "content";
  filter = "body"; # can be headers, full, oneline, text, rawtext
  map = "$CONFDIR/maps.d/content.map";
  symbols = ["CONTENT_BLACKLISTED1", "CONTENT_BLACKLISTED2"];
  regexp = true;
  score = "1.0";
}

**Comment by vstakhov** [comment]
Again, it is not correct. You need to set scores in the metric and for each symbol separately.

**Comment by TempleNode** [comment]
This is a direct example taken from here https://rspamd.com/doc/modules/multimap.html
What I understand is that symbols and values are taken from content.map. 

What you say is that each symbol needs to be defined first and add a metric and cannot be taken automatically from the content.map? The values from content.map only identifies already defined symbol values and overwrites his value?

**Comment by vstakhov** [comment]
In fact, `score` should work here to define a default score. It doesn't work - initially, I've thought that it was becasuse you have specified it as a string not as a number apparently. But after some digging in the code I've realised that this value is totally ignored for virtual symbols. It looks like a bug.
