### ISSUE TITLE
[BUG] MIME_ENCRYPTED_ARCHIVE counted multiple times

### ISSUE THREAD

**Issue by Omega3113** [rspamd/rspamd#4118]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Encrypted Zip-Archive raises MIME_ENCRYPTED_ARCHIVE for each file in the filelist.

### Steps to Reproduce

1. Create an encrypted zip with e.g. 19 Files in in.
2. Mail it 
3. watch score to reach 19*6=114.   6 Is the Symbol-Score for this in our case

**Expected behavior**
Expected the score to be 6. Treated as one file not as 19.

### Versions
Rspamd daemon version 3.1 on Almalinux 8

**Comment by vstakhov** [comment]
This symbol is `one_shot`, so it shouldn't happen unless you mess your configuration badly.

**Comment by Omega3113** [comment]
Our config is very basic.

As I interpret the source code you loop over the files in the archive and check the encryption for each file and add the score and Filename of each file in the archive to the result.

[MIME_ENCRYPTED_ARCHIVE(24.00){1.pdf;2.pdf;3.pdf;4.pdf;}

If it was a one shot, there should be test.zip in the score and not the files.
I do not really understand how the encryption-check of the archive and the files in the archive really work.
In difference to other archives, the filelist of the encrypted zip is always readable.

Thanks for your help

**Comment by vstakhov** [comment]
The score for `one_shot` symbols is not added for subsequent additions: https://github.com/rspamd/rspamd/blob/master/conf/scores.d/mime_types_group.conf#L47

**Comment by Omega3113** [comment]
[Test.zip](https://github.com/rspamd/rspamd/files/8340289/Test.zip)
Feel free to test yourself.

**Comment by Omega3113** [comment]
Okay, found it. Global one_shot defaults to false in options.inc.
Changing it to true, resolves the problem, but makes the hint to the mime_types_group.conf a bit misunderstandable.
Still the filename logged is the first file in the archive and not the archivename itself.

Enabling one_shot globally ruins some other checks, so we need to set each of them to false.......

Thanks for your quick response.
