### ISSUE TITLE
[BUG] macOS Build Fails with Version 3.2 with implicit declaration error in rspamd_rrd_test.c

### ISSUE THREAD

**Issue by essandess** [rspamd/rspamd#4131]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

I'm trying to update [MacPorts rspamd](https://github.com/macports/macports-ports/blob/master/mail/rspamd/Portfile) from version 3.1 to 3.2. Version 3.2 fails to build on macOS, using the same build commands as a successfully built 3.1.  Please see the attached `main.log` file for full details.

This may be a simple issue of `clang`'s rules/flags for implicit functions, or a deeper issue.

Error summary:
```
/opt/local/var/macports/build/_opt_local_ports_mail_rspamd/rspamd/work/rspamd-3.2/test/rspamd_rrd_test.c:39:2: error: implicit declaration of function 'unlink' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        unlink (tmpfile);
        ^
/opt/local/var/macports/build/_opt_local_ports_mail_rspamd/rspamd/work/rspamd-3.2/test/rspamd_rrd_test.c:49:10: warning: incompatible pointer types assigning to 'gchar *' (aka 'char *') from 'struct rrd_rra_def [4]' [-Wincompatible-pointer-types]
        ar.data = rra;
                ^ ~~~
…
5 warnings and 1 error generated.
make[3]: *** [test/CMakeFiles/rspamd-test.dir/rspamd_rrd_test.c.o] Error 1
make[2]: *** [test/CMakeFiles/rspamd-test.dir/all] Error 2
make[1]: *** [CMakeFiles/run-test.dir/rule] Error 2
make: *** [run-test] Error 2
Command failed:  cd "/opt/local/var/macports/build/_opt_local_ports_mail_rspamd/rspamd/work/build" && /usr/bin/make run-test 
```
Log file:
[main.log.gz](https://github.com/rspamd/rspamd/files/8402395/main.log.gz)

### Steps to Reproduce

Configure and build steps (from log file):
```
:debug:configure system:  cd "/opt/local/var/macports/build/_opt_local_ports_mail_rspamd/rspamd/work/build" && /opt/local/bin/cmake -G "CodeBlocks - Unix Makefiles" -DCMAKE_BUILD_TYPE=MacPorts -DCMAKE_INSTALL_PREFIX="/opt/local" -DCMAKE_INSTALL_NAME_DIR="/opt/local/lib" -DCMAKE_SYSTEM_PREFIX_PATH="/opt/local;/usr" -DCMAKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_OBJC_COMPILER="$CC" -DCMAKE_OBJCXX_COMPILER="$CXX" -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_POLICY_DEFAULT_CMP0060=NEW -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_COLOR_MAKEFILE=ON -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_MAKE_PROGRAM=/usr/bin/make -DCMAKE_MODULE_PATH="/opt/local/share/cmake/Modules" -DCMAKE_PREFIX_PATH="/opt/local/share/cmake/Modules" -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON -DCMAKE_INSTALL_RPATH="/opt/local/lib" -Wno-dev -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_INSTALL_PREFIX=/opt/local -DCONFDIR=/opt/local/etc/rspamd -DDBDIR=/opt/local/var/lib/rspamd -DENABLE_FANN=ON -DENABLE_GD=ON -DENABLE_HYPERSCAN=ON -DENABLE_LIBUNWIND=ON -DENABLE_LUAJIT=ON -DENABLE_SNOWBALL=ON -DENABLE_TORCH=ON -DINSTALL_EXAMPLES=ON -DLIBDIR=/opt/local/lib -DLOGDIR=/opt/local/var/log/rspamd -DMANDIR=/opt/local/share/man -DNO_SHARED=ON -DPCRE_ROOT_DIR=/usr/lib -DRSPAMD_USER=_rspamd -DRUNDIR=/opt/local/var/run/rspamd -DPCRE_ROOT_DIR=/usr/lib -DCMAKE_OSX_DEPLOYMENT_TARGET="12.0" -DCMAKE_OSX_SYSROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk" /opt/local/var/macports/build/_opt_local_ports_mail_rspamd/rspamd/work/rspamd-3.2

:info:build Executing:  cd "/opt/local/var/macports/build/_opt_local_ports_mail_rspamd/rspamd/work/build" && /usr/bin/make -j12 -w all VERBOSE=ON
```

###### Tested on

macOS 12.3.1 21E258 x86_64
Xcode 13.3 13E113

**Expected behavior**
A successful build of `rspamd`.

### Versions

3.2

**Comment by essandess** [comment]
This appears to be a known Xcode 12+ issue that can be fixed by patching in the appropriate `#include`. See, e.g.
* https://trac.macports.org/ticket/61876
* https://github.com/macports/macports-ports/commit/227b1ebc657fb496aad668e1763cc11f7d87735e

**Comment by essandess** [comment]
A simple fix by patching in `#include <unistd.h>` is provided in this PR: https://github.com/macports/macports-ports/pull/14447

**Comment by vstakhov** [comment]
Well, this test is fairly outdated and it is not tested in the ci. Anyway, thank you for the proposed fix!
