### ISSUE TITLE
[BUG] bad_archive_extensions can be simple obfuscated

### ISSUE THREAD

**Issue by slavkoja** [rspamd/rspamd#4134]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:

**Describe the bug**

Currently, the ``bad_archive_extensions`` can be simple skipped by very simple technique -- putting file with particular extension into directory in archive, at least for RAR archives. Today i got message with RAR archive, which contains ``ПРАПАНОВА/bbe66543219.exe`` and i have ``exe`` in ``bad_archive_extensions``, but the symbol MIME_BAD_EXTENSION was not added.

After some investigation, i found in ``plugins/mime_types.lua`` (at line 326) condition:
```lua
    return extra_archive_table[e] or (nfiles < 2 and settings.bad_archive_extensions[e]) or
```
and it seems, that the directory is counted in ``nfiles``, after i remove that and change the condition to:
```lua
    return extra_archive_table[e] or settings.bad_archive_extensions[e] or
```
The symbol is triggered. I do not consider this as solution, but my lua knowledge do not allow me to do it better. IMO best solution will be to not count directories in ``nfiles``, if it is possible.

**Expected behavior**

IMO obvious, add MIME_BAD_EXTENSION symbol, when archive contains only one file with defined extension, ignoring of (sub)directories count.

### Versions

Debian 11.3, rspamd 3.2

**Comment by vstakhov** [comment]
Good catch, could you please attache a simple sample please so I can add that to the tests?

**Comment by slavkoja** [comment]
I manually removed some info, hope i didn't break something

[example.eml](https://github.com/rspamd/rspamd/files/8457289/spam.txt)

**Comment by vstakhov** [comment]
It should be fixed in the master branch, thank you!
