### ISSUE TITLE
[BUG] Unable to delist domain on Rspamd UriBL

### ISSUE THREAD

**Issue by dr4g0nBBT** [rspamd/rspamd#4170]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Similar situation as in https://github.com/rspamd/rspamd/issues/3922 can't delisting domain semenikhin.ru

### Steps to Reproduce

1 delist domain on https://bl.rspamd.com/ (now get '"semenikhin.ru" has already been removed from the Domain blacklist')
2 Check:
```
$ dig A semenikhin.ru.uribl.rspamd.com. +short
127.0.0.2
```

**Expected behavior**
expect domain semenikhin.ru to be removed from the Rspamd UriBL list

### Versions

```
rspamd --version
Rspamd daemon version 3.2
```

**Comment by vstakhov** [comment]
That should be resolved now, thank you!
