### ISSUE TITLE
[BUG] settings selector cannot use selector with args

### ISSUE THREAD

**Issue by aletheia7** [rspamd/rspamd#4181]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
A selector in settings cannot be used when the selector needs an argument.

### Example

Add the following as a user setting:
```
disable_sorbs_spam_freemail {

    # Fails because symbol needs a string argument
    selector = symbol;

    # Fails
    selector = symbol(FREEMAIL_ENVFROM);

    # Fails
    selector = symbol("FREEMAIL_ENVFROM");

    # Fails
    selector = header('Subject');

    # Succeeds because "to" does not need an argument
    selector = to;

    apply {
        SORBS_SPAM_DNSBL = 0.0;
    }   
}
```
### Steps to Reproduce

1. Add the above to settings
2. Add ```debug modules = ["settings"];``` to logging.inc
3. Watch log for various parse errors: "cannot parse expresion selector:symbol", "invalid arguments for symbol: expected type "string", go "nil", etc..

**Expected behavior**
I would like to use selectors that take arguments as the docs indicate.

### Versions
Rspamd daemon version 3.2
Debian Linux Testing amd64

**Comment by SurajDadral** [comment]
Faced same issue a few days ago. Adding `expression` in setting did the trick:

```
custom_setting {
  rcpt = "test@example.com";
  selector = "header('Subject')";

  expression = 'rcpt && selector:1';
  apply {
    actions {
      reject = -250;
    }
  }
}
```

**Comment by aletheia7** [comment]
@SurajDadral Thank you.

Adding "expression = " does silence debug errors. However, I cannot get it to match. Here is what I tried:
```disable_sorbs_spam_freemail {

    # fails, MX_GOOD is defined
    selector = "symbol(MX_GOOD)";

    # fails
    selector = symbol(MX_GOOD);

    # fails
    selector = symbol('MX_GOOD');

    # fails, FREEMIL_ENVFROM is defined
    selector = symbol('FREEMAIL_ENVFROM');

    # fails
    selector = symbol('FREEMAIL_ENVFROM');

    expression = 'selector:1';

    apply {
        SORBS_SPAM_DNSBL = 0.0;
    }   
}

```

**Comment by vstakhov** [comment]
It should be fixed now, thank you!

**Comment by aletheia7** [comment]
Thank you for the fix. I downloaded the master (101b8021a09eed4bdd5047c3dd1d4bc447ffddad) and was able to verify a selector with an argument matched. I used ```selector = ip.not_in("127.0.0.1");```. However I was not able to get the ```selector = symbol()``` to match. Here is what I tried:

MX_GOOD was defined.
```
disable_sorbs_spam_freemail {

    # fails
    # selector = "symbol(\"MX_GOOD\")";
    # selector = "symbol(MX_GOOD)";
    # selector = symbol(MX_GOOD);
    # selector = symbol("MX_GOOD");
    
    # works 
    # selector = "ip.not_in(\"127.0.0.1\")";
    # selector = ip.not_in("127.0.0.1");

    # fails, remove comment from "expression =" with any of the "selector =" lines
    # selector = "symbol(\"MX_GOOD\")";
    # selector = "symbol(MX_GOOD)";
    # selector = symbol("MX_GOOD");
    # expression = "selector:1";

    apply {
        SORBS_SPAM_DNSBL = 0.0;
    }   
}
```
Do I have a syntax problem? Does the symbol selector have a problem?

**Comment by vstakhov** [comment]
It won't work apparently. Settings module is called on the very beginning of a message processing when there are no symbols, so it cannot do what you want. And it seems you are trying to implement composite rules via settings, which does not work by design.

**Comment by aletheia7** [comment]
OK. Thank you.
