### ISSUE TITLE
[BUG] Segmentation Fault with icap integration

### ISSUE THREAD

**Issue by MohitRelaha** [rspamd/rspamd#4182]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
rspamd is crashing with segmentation fault when integrated with icap.
Crash is observed only if virus is detected and action is set to reject (action = "reject";). With other actions it works fine (no action / soft reject/ add header).

(gdb) bt
#0  0x00007feb6a4a3fed in void robin_hood::detail::Table<true, 80ul, unsigned int, unsigned int, robin_hood::hash<unsigned int, void>, std::equal_to<unsigned int> >::keyToIdx<unsigned int const&>(unsigned int const&, unsigned long*, unsigned int*) const () from /usr/lib/rspamd/librspamd-server.so
#1  0x00007feb6a4a39ca in unsigned long robin_hood::detail::Table<true, 80ul, unsigned int, unsigned int, robin_hood::hash<unsigned int, void>, std::equal_to<unsigned int> >::findIdx<unsigned int>(unsigned int const&) const () from /usr/lib/rspamd/librspamd-server.so
#2  0x00007feb6a4a3638 in robin_hood::detail::Table<true, 80ul, unsigned int, unsigned int, robin_hood::hash<unsigned int, void>, std::equal_to<unsigned int> >::find(unsigned int const&) const ()
   from /usr/lib/rspamd/librspamd-server.so
#3  0x00007feb6a4a32fe in std::optional<std::reference_wrapper<unsigned int const> > rspamd::find_map<robin_hood::detail::Table<true, 80ul, unsigned int, unsigned int, robin_hood::hash<unsigned int, void>, std::equal_to<unsigned int> >, int, unsigned int, false>(robin_hood::detail::Table<true, 80ul, unsigned int, unsigned int, robin_hood::hash<unsigned int, void>, std::equal_to<unsigned int> > const&, int const&) () from /usr/lib/rspamd/librspamd-server.so
#4  0x00007feb6a49fbe2 in rspamd::symcache::symcache_runtime::get_dynamic_item(int) const () from /usr/lib/rspamd/librspamd-server.so
#5  0x00007feb6a4a10b6 in rspamd::symcache::symcache_runtime::process_item_rdeps(rspamd_task*, rspamd::symcache::cache_item*) () from /usr/lib/rspamd/librspamd-server.so
#6  0x00007feb6a4a09e0 in rspamd::symcache::rspamd_symcache_delayed_item_cb(ev_loop*, ev_timer*, int) () from /usr/lib/rspamd/librspamd-server.so
#7  0x00007feb6abb573b in ev_invoke_pending () from /usr/lib/rspamd/librspamd-ev.so
#8  0x00007feb6abb6674 in ev_run () from /usr/lib/rspamd/librspamd-ev.so
#9  0x00005621101eb707 in ev_loop ()
#10 0x00005621101f194a in start_rspamd_proxy ()
#11 0x00007feb6a4bb124 in rspamd_handle_child_fork () from /usr/lib/rspamd/librspamd-server.so
#12 0x00007feb6a4bb58a in rspamd_fork_worker () from /usr/lib/rspamd/librspamd-server.so
#13 0x00005621101e7268 in spawn_worker_type ()
#14 0x00005621101e75bb in spawn_workers ()
#15 0x00005621101ea032 in main ()

### Steps to Reproduce

1. Integrate rspamd with icap. https://www.rspamd.com/doc/modules/external_services.html#:~:text=an%20arbitrary%20name-,icap,-%7B%0A%20%20servers%20%3D%20%22127.0.0.1%3A1344
2. Set action = "reject"; in /etc/rspamd/local.d/external_services.conf
3. Send mail with Eicar virus signature. Save the below string in a file, e.g. eicar.txt , then include this as attachment.
X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*

### Versions

Rspamd daemon version 3.3
Ubuntu 18.04 x86_64

**Comment by vstakhov** [comment]
Could you please use asan packages as your packages are lacking debug symbols, so it is hard (close to impossible) to tell what's going on.

**Comment by vstakhov** [comment]
Nevermind, I think the commit I've just pushed will fix your issue.

**Comment by MohitRelaha** [comment]
> Nevermind, I think the commit I've just pushed will fix your issue.

Tried again by pulling latest code. But still its crashing with Segmentation fault.

**Comment by vstakhov** [comment]
I have committed another change that will likely resolve the issue.

**Comment by MohitRelaha** [comment]
> I have committed another change that will likely resolve the issue.

It worked. Thanks @vstakhov for the fix.
