### ISSUE TITLE
[BUG] cannot exec invalidate script in redis

### ISSUE THREAD

**Issue by psa** [rspamd/rspamd#4198]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

Log entry:  #92900(controller) <guuto1>; lua; neural.lua:816: cannot exec invalidate script in redis: ERR Unknown Redis command called from script script: a43800941e2820ed8d764d50dfd9c142beddde68, on @user_script:7.

### Steps to Reproduce

Start rspamd

**Expected behavior**

No errors in log

### Versions

Rspamd daemon version 3.2
Redis 7.0.2
FreeBSD 13.0

**Comment by vstakhov** [comment]
This error is quite strange. I have added some more sanity checks to the script, so https://github.com/rspamd/rspamd/commit/3a8bb197fb08ef3832e45f7ee270cc66bc6ea224 might fix the issue.

**Comment by psa** [comment]
Unforunately, still a problem:

```
2022-06-20 21:08:48 #64916(controller) <ex3ezz>; lua; lua_redis.lua:1207: uploaded redis script to 127.0.0.1:6379 with id 3, sha: 3b7b7539e4555fa579ead520dcc3a85d8a25ceab
2022-06-20 21:08:48 #64916(controller) <ex3ezz>; lua; neural.lua:816: cannot exec invalidate script in redis: ERR Unknown Redis command called from script script: 0c1359992039c47c2ee3d9c1b656ae2397312b02, on @user_script:9.
2022-06-20 21:08:48 #64459(rspamd_proxy) <ex3ezz>; lua; neural.lua:487: loaded ANN for default:default from rn_default_default_b1kz15ra_2; 342489 bytes compressed; version=2
```

**Comment by vstakhov** [comment]
Ok, it looks like you have renamed `DEL` command in the redis configuration...

**Comment by psa** [comment]
Ah, thanks. That's embarrassing. Indeed, it was the problem.
