### ISSUE TITLE
[Feature] ARC trust map

### ISSUE THREAD

**Issue by PHPGangsta** [rspamd/rspamd#4200]
Inbound mails are already checked for valid ARC signatures. I'm searching for a possibility to create a list of domains (arc-signers) which I trust. If an email arrives, and I trust the ARC signer, then an invalid DKIM-Signature or "dmarc=fail" should give 0 score (because the valid ARC signatures negates it).

In this ARC document I find the following strategy:
https://dmarc.org/presentations/ARC-Overview-2016Q2-v03.pdf

```
Design Decisions for ARC
• Message recipient seeing an authentication failure under DMARC may choose to check ARC headers
• If ARC headers are intact, they can see and validate Authentication-Results: content reported by the first ARC participant
• Depending on reputation of intermediary/-ies and results, message recipient may choose to use ARC information as basis for a "local override" of authentication checks like DMARC
```

Maybe it would also be nice if rspamd would provide a map with big players already using ARC and which can be trusted.

**Comment by vstakhov** [comment]
Is there anything that is not covered by `whitelisted_signers_map` in the arc module?

**Comment by vstakhov** [comment]
E.g. it is currently removes failed DMARC when a message is signed by a trusted ARC forwarder.

**Comment by PHPGangsta** [comment]
Oh, yes, that seams to be the map I was looking for, but I didn't find it. It's on the documentation page if you know what to search for 😄

I guess I was searching for something like "trust" instead of "whitelist", because a whitelist normally means that a mail will go through, no matter what. But that's not the case here, it "just" removes/ignores a dmarc=fail result.

It currently says on the documentation page:
```
# map of trusted domains. Symbol ARC_ALLOW_TRUSTED is added to messages
# with valid ARC chains from these domains
```

So it's not just a symbol that is added, but it also removes a dmarc=fail, that's important to know I guess. I just created a PR.
