### ISSUE TITLE
[Feature] Managed Redis SSL/TLS Support

### ISSUE THREAD

**Issue by aleshaczech** [rspamd/rspamd#4201]
## Summary

SSL/TLS Support for Redis.
(related to but not duplicate of https://github.com/rspamd/rspamd/issues/3435)

## Motivation

When using Redis server managed by a Cloud provider (e.g. Digital Ocean), there's no way how to install stunnel on Redis side. Cloud providers do not support stunnel as it's a non-standard solution to the problem. The only feasible way how to achieve encryption with managed Redis is to have rspamd conform to the standard native SSL support in the Redis protocol.

## Describe alternatives you've considered

With managed Redis instances, there are really no alternatives. It's a tradeoff between security (not using encryption at all which is a major security concern) and installing and managing own Redis instances.

## Additional context

I commented in https://github.com/rspamd/rspamd/issues/3435, but I am not sure if anyone reads comments on closed issues, I thus decided to create this new issue.

As I said, every major protocol supports SSL/TLS and encrypted traffic should be nowadays considered a must, especially in the cloud environment. Not using the standard way and instead promoting workarounds (stunnel) disqualifies Rspamd from many usecases.

**Comment by vstakhov** [comment]
I could only wish a good luck to any brave soul who would like to dig into this issue :) 

For me personally, this is not an issue as there is a clear workaround that has proven to work better than Redis TLS (at the moment I have checked it, it even failed to use sesions resumption and hence sucked for any sane use case), so I will not invest my time in it.

**Comment by aleshaczech** [comment]
@vstakhov I got it, but can you please elaborate more on the clear workaround?
I am confused if I missed something, but do I get it right that this clear workaround actually does not work for the managed Redis? If so, can you please point me further? I don't have an issue with tunneling everything as long as it's possible.

**Comment by vstakhov** [comment]
https://www.digitalocean.com/community/tutorials/how-to-connect-to-managed-redis-over-tls-with-stunnel-and-redis-cli

**Comment by aleshaczech** [comment]
@vstakhov Would https://github.com/rspamd/rspamd.com/pull/567 work?

**Comment by vstakhov** [comment]
Yes, thank you for submitting the PR!
