### ISSUE TITLE
[BUG] DKIM signing is disabled if client/sender is whitelisted

### ISSUE THREAD

**Issue by jnorell** [rspamd/rspamd#4202]
When whitelisting based on client ip or sender email address, DKIM signing is disabled.  There are many use cases where you need the signing as well.

Eg. I whitelist my home ip address so system mail and various IoT device notifications get delivered, but I also send mail with authentication from my workstation or phone.  Currently the DKIM signing is bypassed for this, and I have mail delivery problems because I use a DMARC reject policy for our domain.

A sample whitelist rule which matches my IP and subsequently does not DKIM sign my authenticated mail is:

(multimap.conf):
```
ISPC_WHITELIST_IP {
  group = "ISPConfig";
  description = "Whitelisted ip address.";
  type = "selector";
  selector = "ip";
  map = [ "$LOCAL_CONFDIR/local.d/maps.d/ip_whitelist.inc.ispc", "$LOCAL_CONFDIR/local.d/maps.d/ip_whitelist.inc.local" ];
  score = -7.0;
}
```

(force_actions.conf):
```
  ISPC_WHITELIST_CLIENT_IP {
    expression = "ISPC_WHITELIST_IP and !CLAM_VIRUS and !JUST_EICAR";
    action = "no action";
    message = "Testing dkim signing with ip whitelist";
  }
```

I have tried playing with all the options I can find in the rule, and also setting `action="no action"` in the rule definition (not using force_actions), and have not found any solution for this.

I am using rspamd 3.2-1~bullseye from the rspamd.com repo.

Thanks...

**Comment by vstakhov** [comment]
Yes, all `sign` rules should indeed ignore passthrough result as they are quite special (maybe except `reject`).
