### ISSUE TITLE
[BUG] lld 14.0.0 build failure (ld.lld: error: undefined symbol: main)

### ISSUE THREAD

**Issue by kyx0r** [rspamd/rspamd#4212]
**Describe the bug**
Bleeding edge musl linux distro, fails to compile with this error:
```
[78/357] Linking CXX static library contrib/google-ced/librspamd-ced.a
ninja: job failed: : && /usr/local/bin/cc -O2 -fdiagnostics-color=always -O3 -DNDEBUG -O3 -funsafe-math-optimizations -fno-math-errno -fomit-frame-pointer -flto -fno-fat-lto-objects -fuse-ld=lld contrib/snowball/CMakeFiles/snowball.dir/compiler/space.c.o contrib/snowball/CMakeFiles/snowball.dir/compiler/tokeniser.c.o contrib/snowball/CMakeFiles/snowball.dir/compiler/analyser.c.o contrib/snowball/CMakeFiles/snowball.dir/compiler/generator.c.o contrib/snowball/CMakeFiles/snowball.dir/compiler/driver.c.o -o contrib/snowball/snowball   && :
ld.lld: error: undefined symbol: main
>>> referenced by /usr/lib/gcc/x86_64-pc-linux-musl/12.1.0/../../../../lib/Scrt1.o:(_start_c)
collect2: error: ld returned 1 exit status
```

Full log here:
https://0x0.st/oQJB.txt

### Steps to Reproduce

```
#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_FLAGS="$CFLAGS" \
    -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
    -DCONFDIR=/etc/rspamd \
    -DRUNDIR=/run/rspamd \
    -DRSPAMD_USER=rspamd \
    -DRSPAMD_GROUP=rspamd \
    -DENABLE_PCRE2=ON \
    -DENABLE_REDIRECTOR=ON \
    -DENABLE_URL_INCLUDE=ON \
    -G Ninja

ninja -C build
ninja -C build install

install -Dm755 rspamd.run "$1/etc/sv/rspamd/run"

```

### Versions

3.2 release

**Comment by vstakhov** [comment]
It doesn't look like an Rspamd issue. Could you try another linker (ld.bfd or even ld.mold) using `-DLINKER_NAME=` Cmake argument?

**Comment by kyx0r** [comment]
Indeed, it's a problem specific to llvm's lld.
With binutils's ld it goes further into the build but fails again.

https://0x0.st/oQJn.txt

This one probably has to do with libressl

**Comment by kyx0r** [comment]
I mean, this patch:

[2] https://0x0.st/oQyP.patch

Check should be < not <= since opaque types where instoduced then IIRC. Well it works for me either way

**Comment by kyx0r** [comment]
Ok, I checked git, since I was looking at 3.2 code, you already fixed libressl. Good job!
Now onty the ld isssue remains.

**Comment by kyx0r** [comment]
Ok, I have recompiled lld 14.0.0 and the problem has gone away, I swear some kind of lucid dream. Oh well, 14.0.06 also works with no problem btw.
