### ISSUE TITLE
[BUG] Wrong HTTP status code when unauthorized access to the RSPAMD HTTP endpoints

### ISSUE THREAD

**Issue by quantranhong1999** [rspamd/rspamd#4218]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Wrong HTTP status code when unauthorized access to the RSPAMD HTTP endpoints (e.g: POST `/checkv2`, POST `/learnham`, POST `/learnspam`,...) which currently returning `HTTP/1.1 403 Unauthorized`.
Response:
```
HTTP/1.1 403 Unauthorized
Connection: close
Server: rspamd/3.2
Date: Wed, 20 Jul 2022 09:12:22 GMT
Content-Length: 44
Content-Type: application/json
Cache-Control: no-store
Content-Encoding: gzip

{
    "error": "Unauthorized"
}
```

### Steps to Reproduce
Send HTTP requests to those endpoints with the wrong/empty `Password` header.

**Expected behavior**
Return `401 Unauthorized` (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401)

### Versions

Rspamd daemon version 3.2

**Comment by vstakhov** [comment]
Good catch, thanks!
