### ISSUE TITLE
Lost write access in webUI after upgrade with rspamd-3.3-78.git312c61532.x86_64.rpm 

### ISSUE THREAD

**Issue by hunter-nl** [rspamd/rspamd#4219]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
After upgrade from rspamd-3.2-77.gitc6d0f564e.x86_64.rpm to rspamd-3.3-78.git312c61532.x86_64.rpm, the WebUI is only in read-only mode, even using correct (enable_)password.
Before upgrade the used password gave write access.

### Steps to Reproduce
See above at "Describe the bug".

**Expected behavior**
After upgrade it should still give write access with the same config (password).

### Versions
Rspamd daemon version 3.3
OS: Rocky Linux 8.6 x86_64

### Additional Information
local.d/worker-controller.inc
```password = "$2$hashedpassword";```

Even when configured with 
local.d/worker-controller.inc
```password = "$2$hashedpassword";```
```enable_password = "$2$differenthashedpassword";```

the WebUI keeps in read-only mode.

When WebUI password prompt is being displayed, the following line in the rspamd.log appears:
```2022-07-20 14:13:07 #962391(controller) <28f41a>; csession; rspamd_controller_check_password: absent password has been specified; source ip: 127.0.0.1:54268```

When I enter the correct password, the following lines in the rspamd.log appears:
```2022-07-20 14:15:07 #962391(controller) <28f41a>; controller; rspamd_check_encrypted_password: incorrect or absent password has been specified```
```2022-07-20 14:15:07 #962391(controller) <28f41a>; controller; rspamd_check_encrypted_password: incorrect or absent password has been specified```
```2022-07-20 14:15:07 #962391(controller) <28f41a>; controller; rspamd_check_encrypted_password: incorrect or absent password has been specified```
```2022-07-20 14:15:07 #962391(controller) <28f41a>; controller; rspamd_check_encrypted_password: incorrect or absent password has been specified```

When I run rspamadm configdump it will show password and enable_password as defined in local.d/worker-controller.inc file.

Password hash has been generated by command: ```rspamadm pw```

**Comment by vstakhov** [comment]
Hum, could you please explain when this issue occurs, so I'd be able to reproduce it. Does it mean that if you have **both** `enable_password` and `password` the entering of the **`enable_password`** is still treated as read-only `pasword`?

**Comment by hunter-nl** [comment]
It happens in both situations. When I have only password in the config. Then this password still gives read only rights. Before upgrade it was working fine in this situation.
And I tried with both password and enable_password in the config. I then use the enable_password. This still gives read only rights.

**Comment by vstakhov** [comment]
I see, thank you. I will try to reproduce and fix it soon.

**Comment by hunter-nl** [comment]
Maybe caused by the commit 57c1030d1f46c830e019f63eaedc982c6d1589c3 ?

**Comment by hunter-nl** [comment]
@vstakhov Great thanks for the fix. When can I expect the new rpm 'experimental' package in the repo? So I can test it.

**Comment by vstakhov** [comment]
There should be fresh packages available that include this fix, so I would appreciate if you try them to estimate if the problem is fixed so far.

**Comment by hunter-nl** [comment]
@vstakhov Yes, this is now solved. Thank you!
