### ISSUE TITLE
[BUG] R_DKIM_ALLOW gives positive score

### ISSUE THREAD

**Issue by SuperTux88** [rspamd/rspamd#4234]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Mails with valid DKIM get a slightly positive `R_DKIM_ALLOW` symbol, which I expect should be negative, because there is nothing wrong with these mails. It's not too bad as these mails usually always get a pretty good score anyway, so the score is low enough, but it's still something that shouldn't happen.

Some examples:
* twitch notifications: `R_DKIM_ALLOW(0.39)[twitch.tv:s=uder6jfl2ivm6ra4d56gtvzkfaq2gr2v,amazonses.com:s=gdwg2y3kokkkj5a55z2ilkup5wp5hhxx];`
* github notification: `R_DKIM_ALLOW(0.30)[github.com:s=pf2014];`
* patreon notification: `R_DKIM_ALLOW(0.30)[mailgun.patreon.com:s=krs];`

Sometimes the score is 0, probably because of some composite rules, so that's normal I guess, but it should never be positive?

### Steps to Reproduce

1. have rspamd
2. receive a mail with valid DKIM

I didn't change any config regarding this symbol, that's what `rspamadm configdump` shows:
```
            R_DKIM_ALLOW {
                groups [
                    "dkim",
                ]
                description = "DKIM verification succeed";
                weight = -0.200000;
                one_shot = true;
            }
```

**Expected behavior**
Score for `R_DKIM_ALLOW` symbol should be negative if DKIM is valid (or 0 if removed by composite rule)

### Versions

`Rspamd daemon version 3.2` on debian `buster` using the rspamd apt-stable repo.

**Comment by vstakhov** [comment]
This issue is likely fixed in the master branch.

**Comment by SuperTux88** [comment]
I tested this with the new 3.3 release, and it looks like it's even worse now in some cases, as it has even higher positive scores: `R_DKIM_ALLOW(1.28)[gmail.com:s=20210112];`

**Comment by kartoffelheinz** [comment]
Can confirm, this has worsened with latest 3.3, which we just installed. Got positive scores up to 1.8. 

They seem to relate somewhat to IP_REPUTATION_SPAM and SPF_REPUTATION_SPAM, but I don't have a big enough sample size to make sure of that, so more of a hunch from examining a few cases.

**Comment by SuperTux88** [comment]
OK, I just noticed that `DKIM_REPUTATION` is expected to affect `DKIM_ALLOW` ([documentation](https://rspamd.com/doc/modules/reputation.html)) ... but the cases that had positive score for `R_DKIM_ALLOW` with 3.2 didn't have a positive `DKIM_REPUTATION` (they had a negative reputation score), and the `R_DKIM_ALLOW` is negative now for these with 3.3, as I would expect it.

Twitch with 3.2:
```
DKIM_REPUTATION(-1.99)[-1.9866724090073];
R_DKIM_ALLOW(0.39)[twitch.tv:s=uder6jfl2ivm6ra4d56gtvzkfaq2gr2v,amazonses.com:s=gdwg2y3kokkkj5a55z2ilkup5wp5hhxx];
```

Twitch with 3.3:
```
DKIM_REPUTATION(-1.00)[-1];
R_DKIM_ALLOW(-2.13)[twitch.tv:s=uder6jfl2ivm6ra4d56gtvzkfaq2gr2v,amazonses.com:s=gdwg2y3kokkkj5a55z2ilkup5wp5hhxx];
```

gmail with 3.2 (1 day before the update):
```
DKIM_REPUTATION(-0.95)[-0.95097713379361];
R_DKIM_ALLOW(-0.30)[gmail.com:s=20210112];
```

gmail with 3.3:
```
DKIM_REPUTATION(0.95)[0.95090361808035];
R_DKIM_ALLOW(1.28)[gmail.com:s=20210112];
```

So what I'm confused now how the `DKIM_REPUTATION` went from negative to positive for gmail in just one day (or related to the update?) ... but maybe the resulting score for `R_DKIM_ALLOW` is expected with the current reputation score and I just didn't remember that a positive `DKIM_REPUTATION` could lead to a positive `R_DKIM_ALLOW` and was confused to still see positive scores? :thinking:

But now I'm more confused what happened to the `DKIM_REPUTATION` with the update? The twitch reputation also dropped by ~1, is that just hard capped at +/- 1 now? :thinking:
