### ISSUE TITLE
Running RSPAMD on Raspberry Pi ARM64

### ISSUE THREAD

**Issue by Talkabout** [rspamd/rspamd#4245]
Hi,

Is anybody running RSPAMD successfully on a Raspberry Pi with 64 bit kernel (ARM64)? I tried to do so but was facing a bus error crash and thus went back to 32 bits. Building was successful though... Are there known issues with that constallation?

Thanks!

**Comment by a16bitsysop** [comment]
are you using luajit or Lua?

**Comment by Talkabout** [comment]
No, using mostly standard features, no special things:

- fuzzy
- bayes
- redis storage

**Comment by a16bitsysop** [comment]
when you build it you have to use one or the other,  what did you install to build it?

**Comment by Talkabout** [comment]
You are right, these are the commands I am using:

`sudo apt-get install -y ragel libevent-dev liblua5.1-0-dev cmake sqlite3 libmagic-dev libsqlite3-dev libicu-dev libluajit-5.1-dev libglib2.0-dev libcrypt-dev libssl-dev libsodium-dev libhiredis-dev
make clean
cmake ../rspamd -DENABLE_HYPERSCAN=OFF -DENABLE_LUAJIT=ON -DCMAKE_BUILD_TYPE=RelWithDebuginfo
make`

**Comment by a16bitsysop** [comment]
you have installed Lua and luajit and told it to use luajit, try `-DENABLE_LUAJIT=OFF`

**Comment by Talkabout** [comment]
Ok, will try. Can you explain how this relates to the initial problem with ARM64? Is there a known issue with LUA?

**Comment by a16bitsysop** [comment]
its not a problem with Lua it's a problem with old versions of luajit, or possibly the luajit package being built for too specific a processor?

what distro are you using?

**Comment by Talkabout** [comment]
I am using Debian 11 (Bullseye). One more question: what features will I "lose" by disabling lua? Want to make sure that it's nothing I really need without knowing it :)

**Comment by a16bitsysop** [comment]
you aren't disabling lua, you are disabling luajit.

you don't loose any features I know of, luajit is faster.

**Comment by Talkabout** [comment]
Thanks Duncan, I will try again to switch to ARM64, rebuild rspamd and see if it works.

**Comment by Talkabout** [comment]
Unfortunately it didn't help:

![image](https://user-images.githubusercontent.com/10157917/186226644-b07b3253-d51c-4a43-9555-ec915eb89a94.png)

It seems there is another issue somewhere....

**Comment by a16bitsysop** [comment]
before that it cannot connect to the fuzzy controller 
`rspamd_inet_address_connect: connect [::1]:11335 failed: 99`

you could try 
`rspamadm configwizard`
incase you have a configuration error

**Comment by Talkabout** [comment]
The whole thing works completely fine in 32bit mode, so I don't think it is a configuration error. As you can see in the last line it updates the fuzzy storage successfully. Can this crash be related to the fact that I am using redis as fuzzy/bayes storage?

**Comment by a16bitsysop** [comment]
wouldn't have thought it was redis, strange if it works in 32bit mode and 64bit mode it can't connect to fuzzy storage and crashes.

are you running in 64bit mode with a 32bit kernel?

You could try a 64bit Raspberry Pi OS image

**Comment by Talkabout** [comment]
On a Rapsberry PI there is no way to run 64bit mode with 32bit kernel. Only the opposite is possible: 64bit kernel, 32bit software. And this is also how I am running it.

**Comment by a16bitsysop** [comment]
try getting a core https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed 
and open with gdb
