### ISSUE TITLE
[BUG] RCPT TO parsing fails with \t\t inside the RCPT TO

### ISSUE THREAD

**Issue by dupondje** [rspamd/rspamd#4247]
We have a postfix setup running with rspamd as milter.

Now we noticed that sometimes rspamd was missing the rcpts field inside the metadata logging.
After some troubleshooting we found out it was caused by the following RCPT TO that was being send:
`RCPT TO: <test@mail.be\t\t>`

Postfix first parses the RCPT TO before checking it against various recipient checks, so Postfix allows the email just fine.
Also the postfix milter sends it to rspamd:
`milter8_rcpt_event: milter inet:localhost:11332: rcpt <test@mail.be??>` (Guess the ?? is just a logging error)

But seems like rspamd can't parse such a RCPT TO.

Is this something that can easily be fixed?

**Comment by vstakhov** [comment]
Is it an issue just for metadata logging or something else?

**Comment by dupondje** [comment]
It seems like for spam rating it has no effect because it uses the mime_rcpts then?
Or is `RCPT_COUNT_ONE(0.00)` added because of this also?

But it's just a bit annoying it has no rcpt in the metadata logging, as we can't archive the mails correctly then.

**Comment by vstakhov** [comment]
I think the proposed patch should fix the issue. I'm also thinking about the same replacement for `FWS` non-terminal in the grammar, but it could lead to some unpredictable consecuences in case of folded headers...
