### ISSUE TITLE
[BUG] rspamadm bayes_dump fails when using password with redis

### ISSUE THREAD

**Issue by stbuehler** [rspamd/rspamd#4255]
In [statistics_dump.lua:306-317](https://github.com/rspamd/rspamd/blob/66a6a02d0147dc7a5761bb812097561ae2dbf8c0/lualib/rspamadm/statistics_dump.lua#L306-L317) in `dump_handler` / `check_keys` the code runs `conn:add_cmd` and then `conn:exec` after establishing a connection; `exec` returns results from all pending commands, which includes AUTH and SELECT from `redis_connect_sync` (in [lua_redis.lua:1432-1440](https://github.com/rspamd/rspamd/blob/66a6a02d0147dc7a5761bb812097561ae2dbf8c0/lualib/lua_redis.lua#L1432-L1440)).

So when `AUTH` (i.e. a password) is used with redis, `check_keys` will see only the authentication result instead of the command it just executed.

The quick workaround is to add `conn:exec()` after all `conn:add_cmd(...)` lines in `redis_connect_sync`, but I think the API is designed rather unfortunately in the first place:
* the default usage is probably rather "synchronous", i.e. `conn:add_cmd` immediately followed by `conn:exec`, so there should be a direct method for this. the "bulk" interface should use rather explizit method names so they are not used accidentally
  * even for the bulk command variant I'd recommend having the "client" build the list of commands, and then use something like `conn:exec_many` to run them all in one step.
* AUTH and SELECT results should probably be checked in `redis_connect_sync`

**Comment by vstakhov** [comment]
> * AUTH and SELECT results should probably be checked in `redis_connect_sync`

I totally agree with this point, thank you! For async connections this issue is usually handled by `redis_pool`, but that's not true for sync API.

**Comment by vstakhov** [comment]
> The quick workaround is to add `conn:exec()` after all `conn:add_cmd(...)` lines in `redis_connect_sync`, but I think the API is designed rather unfortunately in the first place

Yes, that's also a good point: historically sync API has appeared after async one, trying to mimic it's behaviour. For now, I think is would be enough to patch `redis_connect_sync` as a minimum hassle workaround.
