### ISSUE TITLE
[BUG] HTTP map parsing fails if server response includes HTTP Upgrade header 

### ISSUE THREAD

**Issue by kartoffelheinz** [rspamd/rspamd#4261]
If http/https maps are configured in a multimap and the corresponding webserver responds with a http Upgrade header, the http_parser fails:

> rspamd_http_event_handler: got error after HTTP request is finished: HTTP parser internal error: success

### Steps to Reproduce

1. Create any simple map on a server which issues a http Upgrade header if protocol version is not 2 (most recent webservers will do so) OR use our testmap at http://rspam.sslh.net/test/whitelist.map
2. Append a simple mapping configuration, e.g. `testmap { map = "http://rspam.sslh.net/test/whitelist.map"; type = "from"; filter = "email"}` to local.d/multimap.conf
3. Set `debug_modules = ["multimap", "map", "http"];` in local.d/logging.inc
4. reload rspamd.service
5. Use Interface to scan message with Options from set to whitelisted from address
6. If you then disable the Upgrade header (e.g. via .htaccess `Header unset Upgrade`), rspamd parses the map just fine

**Expected behavior**
rspamd should successfully match values in the map. It should not log an HTTP parser internal error.

### Versions

Rspamd daemon version 3.2 on Debian 10

### Additional Information

I think rspamd should ignore or follow the Upgrade header. Either way, it should use the response's payload to match values against.

**Comment by vstakhov** [comment]
Hum, I really don't understand why a sane web server would send `Upgrade` header. Since Rspamd supports neither WebSocket (that is meaningless in this case) nor HTTP/2.0, I would say that the current behaviour is just right. So the easiest and the proper solution is not to send such a header in the first place.

**Comment by kartoffelheinz** [comment]
I'm unsure if you understood the problem. The header is just information, or advertising if you will. It simply says that the client MAY upgrade to another Protocol version. The client is under no technical obligation to do so if the header is present, it was simply informed about the webservers capabilities.

Many servers send such headers to inform clients about upgradeability.

The upgrade header is a specified header in HTTP/1.1 (see RFC). Thus I do not understand why rspamd will fail if such a valid header is present. Just make rspamd ignore the header, done.

**Comment by vstakhov** [comment]
> Just make rspamd ignore the header, done.

Pull requests are very wellcome.

**Comment by kartoffelheinz** [comment]
I thought it was probably just a line or two to change.

Problem is I have very little experience coding C. Will see if I can get my head around it.

**Comment by vstakhov** [comment]
I don't know either if that's two lines or more, as the logic for handling of `Upgrade` header does not live in Rspamd - it is implemented in the side library `contrib/http-parser`.

**Comment by vstakhov** [comment]
Ok, I have checked the code of that library, and it is definitely not a two line fix nor it cannot be `fixed` from the Rspamd side (I prefer not to modify external libraries where possible). So I would still suggest to fix your web server as a least effort choice.
