### ISSUE TITLE
errors trying to install on fedora FC36

### ISSUE THREAD

**Issue by mepreston** [rspamd/rspamd#4276]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
following install directions for fedora found here: https://rspamd.com/downloads.html
install fails with conflicts

### Steps to Reproduce
as root on a fedora FC36 server env:
curl https://rspamd.com/rpm-stable/centos-8/rspamd.repo > /etc/yum.repos.d/rspamd.repo # Uncomment 
rpm --import https://rspamd.com/rpm-stable/gpg.key
dnf update

# dnf install rspamd
Last metadata expiration check: 0:04:57 ago on Mon 19 Sep 2022 06:25:24 PM EDT.
Error: 
 Problem: conflicting requests
  - nothing provides libicudata.so.60()(64bit) needed by rspamd-3.2-1.x86_64
  - nothing provides libicui18n.so.60()(64bit) needed by rspamd-3.2-1.x86_64
  - nothing provides libicuio.so.60()(64bit) needed by rspamd-3.2-1.x86_64
  - nothing provides libicuuc.so.60()(64bit) needed by rspamd-3.2-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)

**Expected behavior**
to have rspamd install with no errors.
It looks like the build dependencies have not been updated for newer version of libicu which is now 69, not 60

### Versions

rspamd-3.2-1.x86_64
fedora server 36
 libicu- 69.1- 6.fc36. x86_64

### Additional Information

please update the dependencies for newer versions of fedora and packages.

**Comment by polarathene** [comment]
FWIW, there are [no results in Fedora package search for `rspamd`](https://packages.fedoraproject.org/search?query=rspamd).

I have raised an issue on the website repo: https://github.com/rspamd/rspamd.com/issues/604

**Comment by fatalbanana** [comment]
One should have been using something like `fedora-22` rather than `centos-8`.

Fedora is these days not a platform that packages are produced for, please consider using [Rspamd in Docker/Podman](https://hub.docker.com/r/rspamd/rspamd).
