### ISSUE TITLE
[BUG] fuzzy-worker listening on unix socket leads to assertion crash on learn

### ISSUE THREAD

**Issue by BtbN** [rspamd/rspamd#4278]
**Describe the bug**
When the fuzzy-worker is configured to listen on a Unix-Domain-Socket, rspamd logs an assertion error on rspamc fuzzy_add:
```
Sep 20 16:39:53 btbn.de rspamd[3822225]: <>; glib; rspamd_glib_printerr_function: **\x0AERROR:/var/tmp/portage/mail-filter/rspamd-3.2/work/rspamd-3.2/src/libutil/addr.c:1667:rspamd_inet_address_from_sa: assertion failed: (slen >= sizeof (struct sockaddr))\x0A
Sep 20 16:39:53 btbn.de rspamd[3822225]: <>; ; rspamd_crash_sig_handler: caught fatal signal 6(Aborted), pid: 3822225, trace:
Sep 20 16:39:53 btbn.de rspamd[3822225]: Bail out! ERROR:/var/tmp/portage/mail-filter/rspamd-3.2/work/rspamd-3.2/src/libutil/addr.c:1667:rspamd_inet_address_from_sa: assertion failed: (slen >= sizeof (struct sockaddr))
Sep 20 16:39:53 btbn.de rspamd[3822225]: <>; ; rspamd_crash_sig_handler: please see Rspamd FAQ to learn how to dump core files and how to fill a bug report
Sep 20 16:39:54 btbn.de rspamd[3669153]: <f11b89>; main; rspamd_check_termination_clause: fuzzy process 3822225 terminated abnormally by signal: Aborted and created core file; please see Rspamd FAQ to learn how to extract data from core file and fill a bug report
Sep 20 16:39:54 btbn.de rspamd[3669153]: <f11b89>; main; rspamd_cld_handler: respawn process fuzzy in lieu of terminated process with pid 3822225
Sep 20 16:39:55 btbn.de rspamd[3669244]: <218ed4>; task; fuzzy_controller_io_callback: got error in IO with server /run/rspamd/fuzzy.sock(unix:/run/rspamd/fuzzy.sock), 111, Connection refused
```

Unsurprisingly, adding the mail also fails with "HTTP error: 111, write socket error"

### Steps to Reproduce

1. Have fuzzy worker listening on unix domain socket. For example:
```
worker "fuzzy" {bind_socket = "/run/rspamd/fuzzy.sock mode=0660"; }
```
2. try to add a mail via rspamc fuzzy_add

**Expected behavior**
Well, not a crash.

### Versions

rspamd 3.2 on Gentoo Linux x86_64

**Comment by GieltjE** [comment]
Been getting the same, though trough the rspamc command ("/usr/bin/rspamc -S $2 -w 10 fuzzy_add <file>")

"HTTP error: 404, No content to generate fuzzy for flag 13"
and
"HTTP error: 111, write socket error"

**Comment by BtbN** [comment]
Do you get the same assertion error in your rspamd log as well?

**Comment by vstakhov** [comment]
I think it's somehow related to the `recvmmsg` syscall behaviour with Unix sockets. I'll check later.

**Comment by vstakhov** [comment]
Unfortunately, there is no simple solution of this issue (due to [this](https://stackoverflow.com/questions/26706584/c-unix-domain-sockets-recvfrom-doesnt-set-struct-sockaddr-src-addr) problem). Adding an ephemeral but managed client binding would introduce unnecessary burden on the complexity of the code. Hence, I'd suggest not to use fuzzy worker over Unix socket - we can state this in documentation and refuse to start. Other (non DGRAM) workers should work over Unix sockets just fine.

**Comment by BtbN** [comment]
I've stuck to unix sockets because they can be protected via normal file and directory permissions, while something listening on localhost can't.
The server it's running on has a bunch of people with user accounts that I don't neccesarily want to talk directly to rspamd.
So being unable to do that will mean I won't be running that worker sadly.

**Comment by GieltjE** [comment]
Sorry to hijack this one a bit, before making a new ticket.

worker "fuzzy" {
  bind_socket = "127.0.0.1:11335";
....
}

now results in:

/usr/bin/rspamc -S LOCAL_FUZZY_DENIED -w 10 fuzzy_add "/var/mail/-scripts/tmp/QVjn5ic9_qWEokaxSFgAaLi+emg="
Results for file: /var/mail/-scripts/tmp/QVjn5ic9_qWEokaxSFgAaLi+emg= (0.003 seconds)
HTTP error: 111, read socket error
