### ISSUE TITLE
[BUG] FORGED_RECIPIENTS reveals addresses in BCC

### ISSUE THREAD

**Issue by denisfidel** [rspamd/rspamd#4279]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
When user sends an email with multiple adresses in Bcc and the `FORGED_RECIPIENTS` is triggered all the addresses in bcc are revealed in `X-Spamd-Result`. Problem occurs when one of users successfully receives such an email and he can see all recipients in the header - which is not ok, because the recipients were added to Bcc with purpose to be hidden. Also this seems like an issue from user security standpoint.

Similar question was already asked here, but i was not able to find an answer: https://lists.rspamd.com/pipermail/users/2021-February/001951.html

### Steps to Reproduce

1. Send an email with multiple addresses in Bcc
2. Make sure the recipients are forged - the `FORGED_RECIPIENTS` is triggered.
3. Observe `X-Spamd-Result` header

**Expected behavior**
Recipients should not be visible in `X-Spamd-Result` in `FORGED_RECIPIENTS` when they are listed in Bcc header.

### Versions

```
$ rspamd --version
Rspamd daemon version 3.1
```
```
$ hostnamectl 
  Operating System: AlmaLinux 8.5 (Arctic Sphynx)
  CPE OS Name: cpe:/o:almalinux:almalinux:8::baseos
  Kernel: Linux 4.18.0-348.12.2.el8_5.x86_64
  Architecture: x86-64
```

### Additional Information

Relevant headers:
```
To: undisclosed-recipients:;
X-Spamd-Result: default: False [3.90 / 7.50]; R_UNDISC_RCPT(3.00)[]; FORGED_RECIPIENTS(1.00)[....  receivers addresses ....]; MIME_GOOD(-0.10)[multipart/mixed,multipart/alternative,text/plain]; RCVD_COUNT_ZERO(0.00)[0]; FROM_EQ_ENVFROM(0.00)[]; MIME_TRACE(0.00)[0:+,1:+,2:+,3:~,4:~]; MID_RHS_MATCH_FROM(0.00)[]; TO_DN_ALL(0.00)[]; HAS_ATTACHMENT(0.00)[]; FROM_HAS_DN(0.00)[]; RCPT_COUNT_ONE(0.00)[1]; FREEMAIL_ENVRCPT(0.00)[[gmail.com](http://gmail.com/),[yahoo.com](http://yahoo.com/),[hotmail.com](http://hotmail.com/)]; TAGGED_RCPT(0.00)[]; ARC_NA(0.00)[]
```

**Comment by Omega3113** [comment]
While I understand your concern, I don't understand when this happens. Do you filter outgoing mail?

**Comment by denisfidel** [comment]
Yes this case happens when filtering outgoing mail. Lets say that one of our users sends an email to multiple recipients in Bcc. For example let one of those recipients be a gmail account and lets assume FORGED_RECIPIENTS symbol is triggered. When gmail recipient checks email headers he can see all recipients listed in Bcc in FORGED_RECIPIENTS header. 

Hope I made it clear enough, if not feel free to ask.

**Comment by vstakhov** [comment]
Why do you insert your spam report when performing outbound scan? It doesn't make any sense. If you stop doing that, your problem will disappear I suppose.

**Comment by denisfidel** [comment]
You are right, it was a mistake on our side. Should just use `skip_local = true;` and `skip_authenticated = true;`. 

Thanks for help and quick response.

**Comment by Janfred** [comment]
The problem is not limited to outbound mails.

Following situation: Person A sends a mail to `a@domain1.example` with BCC `b@domain2.example`, `c@domain2.example` and `d@domain3.example`.

The mail server will probably send the Mails to `b@domain2.example` and `c@domain2.example` in bulk with multiple `RCPT TO`, so both mail addresses are envelope headers.
The `FORGED_RECIPIENTS` rule is triggered, and rspamd includes `s:b@domain2.example,s:c@domain2.example` in the header, so B and C know from each other that they also got the mail.

The problem is here, that the recipient mail server does not know about BCC, so there should be an option to hide the mail addresses in the explanation for the FORGED_RECIPIENT rule.
