### ISSUE TITLE
[BUG] Broken dependencies for ubuntu bionic 3.3-2 package 

### ISSUE THREAD

**Issue by Gronkdalonka** [rspamd/rspamd#4287]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
   * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
The dependencies of the official 3.3-2 packages for ubuntu 18.04 bionic are broken. On a fresh or existing system installing rspamd or updating to 3.3-2 leads to 

```
 The following information may help to resolve the situation:

The following packages have unmet dependencies:
 rspamd : Depends: libc++1-13 (>= 1:13.0.1~++20220120110844+75e33f71c2da) but it is not installable
          Depends: libc++abi1-13 (>= 1:13.0.1~++20220120110844+75e33f71c2da) but it is not installable
          Depends: libunwind-13 (>= 1:13.0.1~++20220120110844+75e33f71c2da) but it is not installable
E: Unable to correct problems, you have held broken packages.

```

### Steps to Reproduce

1.add rspamd sources
2. apt install rspamd

**Expected behavior**
Rspamd installs

### Versions

OS:
Ubuntu 18.04.6 LTS \n \l or Ubuntu 18.04.6 LTS \n \l via docker

You can get this information from copy and pasting the output of `rspamd --version` from the command line. Also, please include the **OS** and what version and architecture including the generation of CPU model (e.g. Haswell) where applicable,  of the OS you're running.

### Additional Information
for docker:

```
From ubuntu:18.04

RUN apt update && apt full-upgrade -y

RUN apt-get install -y lsb-release wget gpg redis-server
RUN CODENAME=`lsb_release -c -s`; mkdir -p /etc/apt/keyrings; wget -O- https://rspamd.com/apt-stable/gpg.key | gpg --dearmor | tee /etc/apt/keyrings/rspamd.gpg > /dev/null; echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rspamd.gpg] http://rspamd.com/apt-stable/ $CODENAME main" | tee /etc/apt/sources.list.d/rspamd.list; echo "deb-src [arch=amd64 signed-by=/etc/apt/keyrings/rspamd.gpg] http://rspamd.com/apt-stable/ $CODENAME main"  | tee -a /etc/apt/sources.list.d/rspamd.list

RUN cat /etc/issue
RUN apt-get update && apt-get --no-install-recommends install rspamd -y
```

**Comment by vstakhov** [comment]
I have the following lines in the `/etc/apt/sources.list`:

```
deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-13 main
deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-13 main
deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic main
```

The last one comes from `add-apt-repository ppa:ubuntu-toolchain-r/test` and is proably optional.

**Comment by Gronkdalonka** [comment]
> I have the following lines in the `/etc/apt/sources.list`:
> 
> ```
> deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-13 main
> deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-13 main
> ```

Adding this as additional sources is enough to be able to upgrade.

Maybe this should be added as additional dependencies since it's not available from default ubuntu repos and was not needed before 3.3

**Comment by DiveSurfer** [comment]
Great, that worked, thank you.

**Comment by nicorac** [comment]
You'll also need to import llvm repository public key, as documented [here](https://apt.llvm.org/):
```
wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
```

**Comment by vstakhov** [comment]
This is all now listed in the documentation. Thank you for your reports and hints!
