### ISSUE TITLE
Are you going to make an official 3.3 release?

### ISSUE THREAD

**Issue by zuzzurro** [rspamd/rspamd#4288]
Again, a pretty simple request, just like my previous one..

**Comment by vstakhov** [comment]
I'm sorry but what do you mean by `official`?

**Comment by zuzzurro** [comment]
I just mean, like for 3.2 a new github "Release". Sorry for not being more specific immediately

**Comment by zuzzurro** [comment]
But I see there's a 3.3 one there already . Thanks!
