### ISSUE TITLE
map permissions for config through web ui with 3.3

### ISSUE THREAD

**Issue by urmel1960** [rspamd/rspamd#4289]
I just upgraded to 3.3. 

I cannot configure my maps anymore using the web ui. That worked without any problem with 3.2 . None of the maps displayed under configuration in the web ui are writable. Action values are also not changeable.

I double checked the permissions on the user map files and they are  

>root@server /etc/rspamd/local.d/maps.d # ls -l *
-rw-r--r-- 1 _rspamd _rspamd   63 Jul 11 18:08 blacklist_body_content.map
-rw-r--r-- 1 _rspamd _rspamd   48 Dec 28  2021 blacklist_from_addr.map
-rw-r--r-- 1 _rspamd _rspamd  643 Oct  1 14:27 blacklist_from_domain.map
-rw-r--r-- 1 _rspamd _rspamd  224 Dec  7  2021 blacklist_from_tld.map
-rw-r--r-- 1 _rspamd _rspamd   46 Jul 12 09:43 blacklist_full_content.map
-rw-r--r-- 1 _rspamd _rspamd   27 Jul 12 09:37 blacklist_header_content.map
-rw-r--r-- 1 _rspamd _rspamd    0 Aug 16  2020 dkim_whitelist.inc.local
-rw-r--r-- 1 _rspamd _rspamd  121 Aug 16  2020 dmarc_whitelist.inc.local
-rw-r--r-- 1 _rspamd _rspamd   32 Aug 16  2020 greylist-whitelist-domains.inc
-rw-r--r-- 1 _rspamd _rspamd   70 Aug 16  2020 mid.inc
-rw-r--r-- 1 _rspamd _rspamd   84 Aug 16  2020 mime_types.inc.local
-rw-r--r-- 1 _rspamd _rspamd   46 Aug 16  2020 recipient_addr.map
-rw-r--r-- 1 _rspamd _rspamd   49 Mar 10  2021 spamtrap.map
-rw-r--r-- 1 _rspamd _rspamd   35 Aug 16  2020 spf_dkim_whitelist.inc.local
-rw-r--r-- 1 _rspamd _rspamd    0 Aug 16  2020 surbl-whitelist.inc.local
-rw-r--r-- 1 _rspamd _rspamd  365 Jun 30 15:42 whitelist_from_addr.map
-rw-r--r-- 1 _rspamd _rspamd 1592 Oct  2 15:29 whitelist_from_domain.map
-rw-r--r-- 1 _rspamd _rspamd   20 Aug  5  2021 whitelist_from_tld.map

Did I miss anything ? I have not found any changes to that in the docs so far.

**Comment by kartoffelheinz** [comment]
This might help you #4306

**Comment by wienfuchs** [comment]
> This might help you #4306

Just checked at my site: Yes. Changing config to single line "enable_password" with restarting webserver and rspamd brought back the web changeability for me. Thank's a lot for your investigation.

**Comment by urmel1960** [comment]
Indeed, that helped me too.  Thanks to @kartoffelheinz

**Comment by uschindler** [comment]
Sorry, can anybody tell me how to fix this? Where to place "enable_password" vs. "password"?

**Comment by uschindler** [comment]
Ah figured it out. In `worker-controller.inc` remove `enable_password = true;` and only leave password has there.
