### ISSUE TITLE
[BUG] URL with percent-encoded emoji tagged with ZERO_WIDTH_SPACE_URL

### ISSUE THREAD

**Issue by rmoehn** [rspamd/rspamd#4290]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Rspamd interpreted a URL containing a percent-encoded emoji (`%F0%9F%A4%B7%F0%9F%8F%BD%E2%80%8D%E2%99%80%EF%B8%8F`) as ZERO_WIDTH_SPACE_URL (https://github.com/rspamd/rspamd/issues/2725).

### Steps to Reproduce

Scan this sample email:

```
Date: Mon, 03 Oct 2022 08:32:30 +0000
From: Kellogg-Voom@guidedtrack.com
Reply-To: invite@guidedtrack.com
To: myemail@example.com
Message-ID: <633a9e1e945f4_42aff8dda5964427e7@f84edd15-6340-47d3-a892-f0a8ffe51136.mail>
Subject: Test
Mime-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: text/plain;
 charset=UTF-8

Kellogg Voom reached out to you!
He contacted you because: https://example.com/&myemoji=%F0%9F%A4%B7%F0%9F%8F%BD%E2%80%8D%E2%99%80%EF%B8%8F
```

**Expected behavior**
I expected this not to be tagged with ZERO_WIDTH_SPACE_URL.

### Versions

I don't know the version, but it was installed within the last twelve months and runs on Linux on AWS.

**Comment by vstakhov** [comment]
It seems that the problem is in [this character](https://www.compart.com/en/unicode/U+200D), commonly used to [join emoji](https://emojipedia.org/zero-width-joiner/) into another emoji semantically.

**Comment by rmoehn** [comment]
Cool. Thanks a lot for the quick fix!
