### ISSUE TITLE
[BUG] metadata_exporter with send_mail backend breaks rejecting mails with 3.3

### ISSUE THREAD

**Issue by SuperTux88** [rspamd/rspamd#4292]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

When a `metadata_exporter` with the `send_mail` backend is configured, and the selector is true, it somehow just stops working after calling the exporter. It just "timeouts" and doesn't provide a result anymore.

### Steps to Reproduce

Testing with a receiving mail:
1. have a `send_mail` exporter configured with a `is_spam` selector
2. Receive a spam mail that should be rejected

What happens:
1. The mail is marked as "reject" in the web UI (so the mail is scanned and detected correctly)
2. The mail is sent to the configured mail-address (so the `metadata_exporter` itself is working as it should)
3. Postfix doesn't get any result about the mail and just timeouts. Depending on how postfix is configured how to handle if the milter fails, this means the mail is either rejected with a temporary failure (the default), so it will be retried by the sender (so spam mails are just retried "forever"), or if the postfix should just ignore milter errors, the mail then gets delivered to the recipient even though it should have been rejected.
4. The following gets logged by rspamd:
    ```
    ...
    Oct 03 15:45:58 mail-1 rspamd[8651]: <aa454b>; metadata_exporter; metadata_exporter.lua:632: Message selected for processing
    Oct 03 15:46:57 mail-1 rspamd[8651]: <aa454b>; task; rspamd_worker_guard_handler: the peer has closed connection unexpectedly
    ```
    (So postfix just gives up after a 60 second timeout, it even retries the whole process 3 times, but it fails every time the same way)

When testing with `rspamc <message>`, it's basically the same as when receiving a spam mail. The mail also gets marked as rejected in the Web UI and also gets sent to the exporter email, but after 10 seconds the rspamc command fails with:
```
Results for file: /path/to/message (10 seconds)
IO timeout
```

The rspamd doesn't contain the `rspamd_worker_guard_handler: the peer has closed connection unexpectedly` line when the mail was scanned from `rspamc`, so the `metadata_exporter; metadata_exporter.lua:632: Message selected for processing` is the last line for that ID then.

Disabling the exporter and scanning the same mail results in this (so basically as it should be):
```
Results for file: /path/to/message (0.332 seconds)
[Metric: default]
Action: reject
Spam: true
...
```

**Expected behavior**

The mail is sent to the metadata_exporter AND then rejected as normally

### Versions

`Rspamd daemon version 3.3` on debian buster using the rspamd apt-stable repo.

### Additional Information

When disabling the `metadata_exporter` everything works normally and mails get rejected as they should. Also it looks like a `metadata_exporter` with a `http` backend seems to not cause the issue and mails are still rejected as they should (at least scanning with `rspamc` works after a quick test).

**Comment by moisseev** [comment]
Make sure the metadata_exporter e-mail reports are NOT scanned by Rspamd that leads to infinite loop.

**Comment by slavkoja** [comment]
I can confirm that problem with ``exim`` too. Disabling SMTP reports (make selector return ``false``) solves the problem, but disables reporting...

The loop doesn't happen in my case, thus cannot be part of problem (even if they would be scanned, my reports doesn't contains body).

**Comment by slavkoja** [comment]
> Make sure the metadata_exporter e-mail reports are NOT scanned by Rspamd that leads to infinite loop.

AFAIK, that was not problem, as when i start to use ``metadata_exporter`` (v 2.X) the mails was initially passed through ``rspamd`` (without body) and it was working. I setup my MTA to bypass spam checks of these reports after i got reports working.

Anyway, the problem is, that ``rspamd`` hangs after report is submitted, the scanned email appears only in WebUI history, but not in rspamd's log. Restarting rspamd after that tooks 16 sec, which corresponds to log line:

    main; rspamd_term_handler: catch termination signal, waiting for 4 children for 16.00 seconds

**Comment by vstakhov** [comment]
It's likely fixed by https://github.com/rspamd/rspamd/commit/cdbacf2b135fc49a84df1d0790c2ba77d6d763b7

**Comment by slavkoja** [comment]
seems, that it affects the DMARC reporting too, the cronjob hangs, remains running and eats significant amount of memory, which grows with every reporting process. Workaround is to use ``timeout`` command with it, i use 60 seconds timeout, but IMO can be shorter.
