### ISSUE TITLE
[BUG] FTBFS on OpenBSD, _L in symcache conflicts with macro in ctype.h

### ISSUE THREAD

**Issue by sthen** [rspamd/rspamd#4293]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Falls to build in OpenBSD. https://github.com/rspamd/rspamd/commit/c211ce57b9b3a7ddac08bc996ad3ca6a6ee28dac introduced use of _L in libserver/symcache which conflicts with a macro in ctype.h.

```
In file included from /usr/obj/ports/rspamd-3.3/rspamd-3.3/src/libserver/symcache/symcache_impl.cxx:18:
/usr/obj/ports/rspamd-3.3/rspamd-3.3/src/libserver/symcache/symcache_internal.hxx:142:72: error: expected ')'
        delayed_cache_condition(std::string_view _sym, int _cbref, lua_State *_L) :
                                                                              ^
/usr/include/ctype.h:46:12: note: expanded from macro '_L'
#define _L      0x02                                                                                    ^
/usr/obj/ports/rspamd-3.3/rspamd-3.3/src/libserver/symcache/symcache_internal.hxx:142:25: note: to match this '('                                                                       delayed_cache_condition(std::string_view _sym, int _cbref, lua_State *_L) :
                               ^
/usr/obj/ports/rspamd-3.3/rspamd-3.3/src/libserver/symcache/symcache_internal.hxx:143:29: error: cannot initialize a member subobject of type 'lua_State *' with an rvalue of type 'int'
sym(_sym), cbref(_cbref), L(_L) {}
                                          ^ ~~
2 errors generated.
ninja: build stopped: subcommand failed.
```

### Steps to Reproduce

Attempt to build on OpenBSD.

**Expected behavior**
Build succeeds.

### Versions

3.3, OpenBSD 7.2 amd64.

### Additional Information

-

**Comment by vstakhov** [comment]
Yes, that was very unfortunate as C standard reserves names starting from `_`. Apparently, that should be `L_` not `_L`.

**Comment by vstakhov** [comment]
BTW, thank you for maintaining Rspamd on OpenBSD! I have checked your local patches and I think some of them should be fixed in the upstream. I've started with `ffsll` support proper check.

**Comment by sthen** [comment]
I'm hitting an issue on 32-bit builds with the libutil/cxx/file_util.cxx changes in 3.4,

```
/pobj/rspamd-3.4/rspamd-3.4/src/libutil/cxx/file_util.cxx:209:49: error: non-constant-expression cannot be narrowed from type 'long long' to 'std::size_t' (aka 'unsigned long') in initializer list [-Wc++11-narrowing]
        return raii_mmaped_file{std::move(file), map,  file.get_size() - offset};
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~
/pobj/rspamd-3.4/rspamd-3.4/src/libutil/cxx/file_util.cxx:209:49: note: insert an explicit cast to silence this issue
        return raii_mmaped_file{std::move(file), map,  file.get_size() - offset};
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~
                                                       static_cast<size_t>(    )
1 error generated.
```

Sorry it's probably a simple fix but my C++ is not too great so I don't have a diff.

**Comment by dbaio** [comment]
> I'm hitting an issue on 32-bit builds with the libutil/cxx/file_util.cxx changes in 3.4,
> 
> ```
> /pobj/rspamd-3.4/rspamd-3.4/src/libutil/cxx/file_util.cxx:209:49: error: non-constant-expression cannot be narrowed from type 'long long' to 'std::size_t' (aka 'unsigned long') in initializer list [-Wc++11-narrowing]
>         return raii_mmaped_file{std::move(file), map,  file.get_size() - offset};
>                                                        ^~~~~~~~~~~~~~~~~~~~~~~~
> /pobj/rspamd-3.4/rspamd-3.4/src/libutil/cxx/file_util.cxx:209:49: note: insert an explicit cast to silence this issue
>         return raii_mmaped_file{std::move(file), map,  file.get_size() - offset};
>                                                        ^~~~~~~~~~~~~~~~~~~~~~~~
>                                                        static_cast<size_t>(    )
> 1 error generated.
> ```
> 
> Sorry it's probably a simple fix but my C++ is not too great so I don't have a diff.

Hi.

We are getting this error on FreeBSD/i386 as well.

**Comment by vstakhov** [comment]
I'm aware of this issue (and the fix is tirvial indeed).

**Comment by dbaio** [comment]
> I'm aware of this issue (and the fix is tirvial indeed).

Oh, that's nice... and thanks for your work.

Regards.
