### ISSUE TITLE
[BUG] Composite rules: weight not removed

### ISSUE THREAD

**Issue by uvelokk** [rspamd/rspamd#4295]
**OS:** Debian 11 x64
**Rspamd version:**  3.3-2~bullseye

**Description:** After upgrading Rspamd from 3.1 to 3.3 composite rules do not remove weight of all components.

### Example 1

**Rule:**
```lua
IP_REP_SPAM_WITH_WHITELIST_DMARC_DKIM {
    expression = "IP_REPUTATION_SPAM && WHITELIST_DMARC_DKIM";
    policy = "remove_weight";
    score = -7;
}
```
**Result:**
```
IP_REP_SPAM_WITH_WHITELIST_DMARC_DKIM(-7.00){},
IP_REPUTATION_SPAM(2.81){asn: xxxxx(0.39), country: US(0.01), ip: xx.xx.176.123(0.00);},
WHITELIST_DMARC_DKIM(0.00){foo.com:d:+;foo.com:D:+;}
```
**Expected result:** both ```IP_REPUTATION_SPAM``` and ```WHITELIST_DMARC_DKIM``` are set to 0.

### Example 2

**Rule:**
```lua
GENTLE_REL_IP_REP_SPAM {
  expression = "GENTLE_RELAY && IP_REPUTATION_SPAM";
  score = 0;
  policy = "remove_weight";
}
```

**Result:**
```
IP_REPUTATION_SPAM(1.30){asn: xxxxx(0.09), country: US(0.01), ip: xx.xx.167.172(0.09);},
GENTLE_RELAY(0.00){xx.xx.167.172;},
GENTLE_REL_IP_REP_SPAM(0.00){}
```

**Expected result:** both ```IP_REPUTATION_SPAM``` and ```GENTLE_RELAY``` are set to 0

**Comment by vstakhov** [comment]
It can happen if those symbols, specifically, `IP_REPUTATION_SPAM` and `WHITELIST_DMARC_DKIM` are listed in other composites that specify that this symbol should not be removed/rescored. In this case, a more conservative rule wins. To enforce removal, there is a prefix `^` that overrides and enforces removal of the **both** score and the symbol. There is no more fine-grained control so far.

**Comment by uvelokk** [comment]
Thank You. In this case - case closed.
