### ISSUE TITLE
[BUG] rspamadm dmarc_report does not terminate

### ISSUE THREAD

**Issue by Ultimator14** [rspamd/rspamd#4309]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
I'm using a cronjob to execute `rspamadm dmarc_report` on a daily basis. When there are no reports, this works as expected.

When there are reports to send, these reports are sent successfully and `Reporting collection has finished 1 dates processed, x reports: x completed, 0 failed` is printed.  
However the command does not terminate. When I check htop, I have many entries (one per day) of the type
```
└─ CROND
   ├─ rspamadm dmarc_report
   └─ sendmail -FCronDaemon -i -odi -oem -oi -t -f root
      └─ postdrop -r
```
This also happens when executing `rspamadm dmarc_report` manually via terminal. Pressing any key has no effect. To stop the process I have to manually CTRL+C it.

### Steps to Reproduce

1. Receive mail from a domain that specified a dmarc rua record
2. Wait for one day
3. Run the `rspamadm dmarc_report` command
4. CTRL+C is required to end the command

**Expected behavior**
The program should exit automatically after report sending has finished (like it does when there are not reports to be sent)

### Versions

Rspamd daemon version 3.3
OS: Gentoo Linux
Architecture: arm64 (Raspberry Pi 4 Model B)

### Additional Information

Mailserver: postfix 3.7.3

dmarc.conf
```# Enforce actions based on dmarc disposition
actions = {
  quarantine = "add_header";
  reject = "reject";
}

# DMARC reports
reporting = {
  # Enable
  enabled = true;
  # DMARC report src
  email = "dmarc_report@mydomain";
  # Domain (taken from AuthservID value of OpenDMARC)
  domain = "mydomain";
  # Organization name shown in DMARC report
  org_name = "mydomain";

  # Copy reports to mail
  bcc_addrs = ["dmarc@mydomain"];

  # SMTP settings
  helo = "mydomain";                       # Helo used in SMTP dialog
  smtp = "127.0.0.1";                      # SMTP server IP
  smtp_port = 25;                          # SMTP server Port
  from_name = "dmarc_report@mydomain";     # SMTP FROM
  msgid_from = "dmarc_report";             # Msgid format
  max_entries = 1k;                        # Maxiumum amount of entries per domain
  keys_expire = 2d;                        # Expire date for Redis keys
}
```

**Comment by PHPGangsta** [comment]
I have the same problem in my setup, I updated rspamd yesterday to `3.3-2~bullseye`, and today there is a hanging cronjob process:

```
root     3218187     755  0 02:17 ?        00:00:00 /usr/sbin/CRON -f
root     3218194 3218187  0 02:17 ?        00:00:00 /bin/sh -c /usr/bin/rspamadm dmarc_report -v >> /tmp/dmarc_report.log 2>&1
root     3218202 3218194  0 02:17 ?        00:00:10 /usr/bin/rspamadm dmarc_report -v
```

It looks like 8 days ago there was a bugfix: https://github.com/rspamd/rspamd/issues/4292#issuecomment-1270711284 Can someone confirm it fixes the problem?

Can we expect a new release soon? Otherwise a lot of existing systems will get problems the more processes are hanging and using memory (it's 85 MB per cronjob in my system). As a workaround I can restart rspamd every day, but others will not do this and run out-of-memory in a few days...

**Comment by Ultimator14** [comment]
I applied both cdbacf2b135fc49a84df1d0790c2ba77d6d763b7 and 5209f8541be49ddc3ca736cb336a5117bb32a971 and this seems to fix the problem.

**Comment by reinob** [comment]
I just noticed this today when updating to 3.4.1 (debian).
I'll keep an eye on it in the next few days.
