### ISSUE TITLE
[BUG] rspamd 3.3, /checkv2 proto, milter/add_header stanza has changed

### ISSUE THREAD

**Issue by andy-igoshin** [rspamd/rspamd#4315]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd

**Describe the bug**

In Rspamd 3.3 (/checkv2) the type of header data in milter/add_header has changed.
Is this an error or should it be so now?

### Steps to Reproduce

1. [First Step]
    switch on ARC and milter headers

2. [Second Step]
   check the message

### Versions

Rspamd daemon version 3.3
Ubuntu 20.04.5 LTS, x86_64
CPU Intel(R) Core(TM) i7-4790, CPU family: 6

### Additional Information

In milter/add_header, version before 3.3, the data type of a single header is a hash. In version 3.3 the data type of a single header is an array of hashes.

[517243400.msg.resp-3.3.txt](https://github.com/rspamd/rspamd/files/9844630/517243400.msg.resp-3.3.txt)
[517243400.msg.resp-pre3.3.txt](https://github.com/rspamd/rspamd/files/9844631/517243400.msg.resp-pre3.3.txt)
[517243400.txt](https://github.com/rspamd/rspamd/files/9844632/517243400.txt)

**Comment by andy-igoshin** [comment]
There is also an add_header inside milter/add_header.

  "milter": {
    "add_headers": {
...
      "add_headers": []
   }
}

**Comment by vstakhov** [comment]
It is related to the https://github.com/poolpOrg/filter-rspamd/issues/41 
I hope I have a fix at some extent at https://github.com/rspamd/rspamd/commit/ded2e51e60325a0e817362c6df0c341bb00d4b0e and the following commit. The issue with a duplicated `add_headers` is new to me. Could you please elaborate on how to reproduce it? In any case, I believe that the compatibility here must not be lost...

**Comment by andy-igoshin** [comment]
I attached arc.conf and milter_headers.conf
I didn't do anything else. I just checked the message.

[arc.conf.txt](https://github.com/rspamd/rspamd/files/9845432/arc.conf.txt)
[milter_headers.conf.txt](https://github.com/rspamd/rspamd/files/9845433/milter_headers.conf.txt)

**Comment by andy-igoshin** [comment]
without arc.conf and milter_headers.conf
Rspamd's answer looks like this. Full answer attached.

  "milter": {
    "add_headers": [],
    "remove_headers": {
      "X-Spam": 0
    }
  }


[517243400.msg.resp-3.3-wo-arc.txt](https://github.com/rspamd/rspamd/files/9845446/517243400.msg.resp-3.3-wo-arc.txt)

**Comment by andy-igoshin** [comment]
https://github.com/rspamd/rspamd/commit/ded2e51e60325a0e817362c6df0c341bb00d4b0e

**Comment by andy-igoshin** [comment]
I tested https://github.com/rspamd/rspamd/commit/ded2e51e60325a0e817362c6df0c341bb00d4b0e , the bug is fixed.

**Comment by gahr** [comment]
Any plans for a release?

**Comment by vstakhov** [comment]
I would appreciate if anybody can test the current experimental packages (or directly the master branch) to confirm that everything is working fine. I can cut a release at any moment thereafter.

**Comment by gahr** [comment]
Sure I can test master, although only on my limited use case, I'm not a power user...

**Comment by gahr** [comment]
Master works fine here.

**Comment by vstakhov** [comment]
Great, thank you for checking!

**Comment by andryyy** [comment]
Can confirm.
