### ISSUE TITLE
[BUG] history_redis stopped working w/password if specified in history_redis.conf

### ISSUE THREAD

**Issue by Player701** [rspamd/rspamd#4318]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
This is my configuration for the redis history module (```/etc/rspamd/local.d/history_redis.conf```):

```
servers = "127.0.0.1";
password = "<password hidden>";
key_prefix = "rs_history";
nrows = 1000;
compress = true;
subject_privacy = true;
```

Used to work perfectly until a few weeks ago, I suppose that's when rspamd was updated to 3.3. Since then, I've been finding messages of the following form in the log:

```Oct 25 17:26:39 mail.mydomain.com rspamd[2831172]: <4niw6e>; lua; history_redis.lua:277: history_redis: plugin is misconfigured: field "password": expected { "write_servers" = type "string", or array of type "string", "read_servers" = type "string", or array of type "string" }, { "servers" = type "string", or array of type "string" }, or { "server" = type "string", or array of type "string" }```

Moving the redis settings to ```/etc/rspamd/local.d/redis.conf``` appeared to fix the issue. Disregarding that some of the history was inevitably lost (unless it's still on the disk somewhere can be moved to Redis somehow, but I probably won't bother), the module now loads again, and the web UI appears to reflect that - I was wondering why I suddenly wasn't seeing detailed scores and from/to addresses anymore.

I'm not sure if the greylisting module is also affected since my settings do not let it trigger often. But the documentation implies that Redis servers must be specifically defined in ```/etc/rspamd/local.d/greylist.conf``` for it to work, so I guess it means that it cannot use global settings from ```/etc/rspamd/local.d/redis.conf```. Might be worth to check it also.

### Steps to Reproduce

See the configuration example and log output above.

**Expected behavior**
The configuration should work as it used to.

### Versions

Rspamd version 3.3

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Player701** [comment]
**UPD:** greylisting seems to work normally (confirmed by the Redis ```MONITOR``` command and the absence of unusual log messages).

**Comment by vstakhov** [comment]
Ok, I think the commit above should fix this and other similar issues...

**Comment by robert-cam** [comment]
Think this is supposed to be fixed in 3.4 but seeing the error since upgrading from 3.2 to 3.4:

2022-11-30 16:06:41 #33579(main) <uu4rjo>; lua; history_redis.lua:277: history_redis: plugin is misconfigured: field "read_servers": expected { "write_servers" = type "string", or array of type "string", "read_servers" = type "string", or array of type "string" }, { "servers" = type "string", or array of type "string" }, or { "server" = type "string", or array of type "string" }

**Comment by DL7BJ** [comment]
Same error here with 3.4. 

rspamd.log:2022-12-12 20:45:00 #13915(main) <3p8q3m>; lua; history_redis.lua:277: history_redis: plugin is misconfigured: field "history_redis": expected { "read_servers" = type "string", or array of type "string", "write_servers" = type "string", or array of type "string" }, { "servers" = type "string", or array of type "string" }, or { "server" = type "string", or array of type "string" }
rspamd.log:2022-12-12 20:45:00 #13915(main) <3p8q3m>; cfg; rspamd_init_lua_filters: init lua module history_redis from /usr/share/rspamd/plugins/history_redis.lua; digest: e8431001f0

**Comment by vstakhov** [comment]
I cannot reproduce it. If you report any misbehaviour please attach your configuration, as otherwise these reports are utterly useless.

**Comment by vstakhov** [comment]
Ok, I probably know how to reproduce it: 

```
read_servers = "localhost";
write_servers = "localhost";
```

**Comment by DL7BJ** [comment]
Since version 3.5 the problem is solved!

Thank you very much indeed!

**Comment by ajs124** [comment]
Still seems not to like all redis config fields:
```
rspamd[903]: <ze8eif>; lua; history_redis.lua:279: history_redis: plugin is misconfigured: field "sentinels": expected { "read_servers" = type "string", or array of type "string" }, { "write_servers" = type "string", or array of type "string" }, { "read_servers" = type "string", or array of type "string", "write_servers" = type "string", or array of type "string" }, { "servers" = type "string", or array of type "string" }, or { "server" = type "string", or array of type "string" }
rspamd[947]: <kkh9xr>; lua; history_redis.lua:279: history_redis: plugin is misconfigured: field "sentinel_watch_time": expected { "read_servers" = type "string", or array of type "string" }, { "write_servers" = type "string", or array of type "string" }, { "read_servers" = type "string", or array of type "string", "write_servers" = type "string", or array of type "string" }, { "servers" = type "string", or array of type "string" }, or { "server" = type "string", or array of type "string" }
```

tested on 3.4 and c0e967fcede63765cec4da3ce5cca047542cfc26. `local.d/history_redis.conf` looks roughly like this:
```
write_servers = "10.0.0.3:6381";
read_servers = "127.0.0.1:6381";
sentinels = "10.0.0.4:26379,10.0.0.3:26379,10.0.0.2:26379";
sentinel_watch_time = 30s;
sentinel_masters_pattern = "^rspamd$";
.include "/secrets/rspamd/redis-pass";
nrows = 5000;
```
