### ISSUE TITLE
[BUG] R_SUSPICIOUS_URL hit on sane URL http://i011-934:4326/regal

### ISSUE THREAD

**Issue by bauerstefan** [rspamd/rspamd#4344]
The above URl gets tagged as 

R_SUSPICIOUS_URL(5.00)\{i011-934;},

complete link in e-mail uses

http://i011-934:4326/regal

There seems to be a false positive. Can someone elaborate on this?

latest rspamd stable version on Debian/Ubuntu.

Thank you.

**Comment by TaaviE** [comment]
How is it a false positive? 

It is only usable with a local resolver that knows that hostname, it *is* very suspicious.

**Comment by bauerstefan** [comment]
valid point. Thank you.

**Comment by bauerstefan** [comment]
.
