### ISSUE TITLE
[BUG] GTUBE patterns are apparently not processed correctly

### ISSUE THREAD

**Issue by nightcn1080** [rspamd/rspamd#4379]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
When receiving a GTUBE pattern, rspamd does not show me a new entry in the webinterface. Modules such as the Metadata exporter are also not triggered when such a pattern is received. It does not matter which GTUBE pattern was sent. 

### Steps to Reproduce

1. Enable test patterns
2. Send a gtube pattern which triggers for example "add header"
3. Check in the rspamd web interface under history if the mail is listed 

**Expected behavior**
If you receive a GTUBE pattern to test the spam filter, the mail should be treated as any other mail. This seems to be no longer the case since an update. Since which version this behavior occurs I can not say. But I have used the gtube patterns in the past and everything worked as expected.

### Versions

Rspamd daemon version 3.4
Debian GNU/Linux 10 (buster)
Intel Xeon E3-1270 v6

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by vstakhov** [comment]
It is the expected behaviour that was mentioned many times.
