### ISSUE TITLE
[BUG] Rspamd struggling with wonky looking boundary

### ISSUE THREAD

**Issue by JasonStephenson** [rspamd/rspamd#4394]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Rspamd struggling to deal with a wonky email. Specifically an email which declares a multipart boundary but never defines it. 

### Steps to Reproduce

1. `rspamadm mime dump --json ./jst_redacted.eml`
2. Observe parts array is empty

```
"parts": [
        {
            "size": 0,
            "headers": [],
            "type": "multipart/mixed",
            "multipart_boundary": "-"
        }
    ],
```

**Expected behavior**
Rspamd correctly defines the parts array (by ignoring the undefined boundary?)

### Versions
3.2

### Additional Information
This is a real email seen in the wild, which I have redacted before submitting here. 
If the line `Content-Type: multipart/mixed; boundary="-"` was not present rspamd would function correctly.
Email clients still parse and display the .eml correctly, even when the wonky line is present.

Any additional information, configuration or data that might be necessary to reproduce the issue.
[jst_redacted.eml.txt](https://github.com/rspamd/rspamd/files/10742666/jst_redacted.eml.txt)

**Comment by vstakhov** [comment]
This problem is quite complicated, I'm afraid. Rspamd does not recognize boundaries that consist of merely dashes. It was done to improve the preprocessing speed to distinguish content from the boundaries themselves. I will try to fix this logic but it can break other messages somehow, so I need to test.

**Comment by vstakhov** [comment]
I have a fix but I need to test if it breaks something.

**Comment by JasonStephenson** [comment]
I have integrated your change within our codefix and can confirm this appears to fix our issue. If you are happy with your testing we can close this issue?
