### ISSUE TITLE
Rspamd configuration for specfic user

### ISSUE THREAD

**Issue by jatin0123** [rspamd/rspamd#4405]
Hello,

I have installed rspamd and integrated with exim configuration, help me to configure it for multiple users.

**Comment by fatalbanana** [comment]
Please use [discussions](https://github.com/rspamd/rspamd/discussions).

It's not a well-defined question; maybe what you want is some Exim ACL condition checking the value of `$authenticated_id` and/or you could do what you want with Rspamd's settings module.

https://rspamd.com/doc/configuration/settings.html
https://www.exim.org/exim-html-current/doc/html/spec_html/ch-access_control_lists.html
