### ISSUE TITLE
[BUG] rspamd keeps crashing after updating hyperscan from 5.4.0 to 5.4.1

### ISSUE THREAD

**Issue by Biosias** [rspamd/rspamd#4409]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
While using rspamd-3.4-r2 on Gentoo I updated hyperscan from version 5.4.0 to the newest 5.4.1. After the update finished rspamd kept crashing.

from rspamd log:

```
2023-02-23 13:03:33 #72294(main) rspamd_multipattern_try_save_hs: cannot serialize hyperscan cache to /var/lib/rspamd//a885fe9590ec5e9389de41485f63bde2cde2c9a3b3dc604afb48c367e626437f.hsmp.tmp: No such file or directory
2023-02-23 13:03:33 #72294(main) rspamd_multipattern_compile: fatal error: cannot allocate scratch space for hyperscan: -5
```

From [Hyperscan](https://github.com/intel/hyperscan/blob/c37166d52ba5634886cd5ae73dcc81bb2de95872/src/hs_common.h#L509-L512) we can see:
```
/**
 * The given database was built for a different version of Hyperscan.
 */
#define HS_DB_VERSION_ERROR     (-5)
```

There is a way I was able to mitigate the crashes:
1. Downgrade back to hyperscan 5.4.0
2. Stop rspamd
3. rm /var/lib/rspamd/\*.hs\*
4. Upgrade hyperscan to 5.4.1 again
5. Start rspamd

After this the crashes and errors disappeared.

### Steps to Reproduce

1. Upgrade hyperscan from 5.4.0 to 5.4.1
2. Restart rspamd

**Expected behavior**
Not crash.

### Versions

Rspamd daemon version 3.4
Gentoo Linux Kernel 6.2.0-gentoo-x86_64 x86_64 AMD EPYC 7601 32-Core Processor AuthenticAMD

**Comment by thesamesam** [comment]
cc @arkamar

**Comment by vstakhov** [comment]
It appears that Hyperscan does not include its version in the platform data, which is regrettable. Additionally, it seems that the hs_deserialise_database_at function lacks sufficient checks at that stage. As a result, the only method that fails is hs_allocate_scratch, which I expected to fail only in case of allocation failures.

I have some patches ready to fix this issue.

**Comment by vstakhov** [comment]
In the meantime, cleaning of the `/var/lib/rspamd` folder seems to be the easiest option.

**Comment by vstakhov** [comment]
Thank you @arkamar, I will investigate furhter. The first error is super fishy...

**Comment by arkamar** [comment]
> The first error is super fishy...

Yeah, I know, I have dug in the code a little bit :)

**Comment by vstakhov** [comment]
Fuck, the issue is clearly in hyperscan: `hs_deserialize_database_at` does not return any error in case of version mismatch, but the subsequent usage of the database is not possible.

**Comment by vstakhov** [comment]
I think it should work now, could you please check?

**Comment by arkamar** [comment]
Yes, it works now.

I have noticed another issue related to this which was introduced in (git bisected) commit 79044bfc0263 - `[Fix] Further checks for the hs_scratch_alloc`. `run-test` target fails with messages below. Steps to reproduce are
1. `cmake -DENABLE_HYPERSCAN=ON ..`
2. `make -j8 run-test`

It is not related to doctest version, bundled 2.4.6 produces the same error.
```
[62/62] cd /var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999_build && test/rspamd-test-cxx && sh -c 'LUA_PATH="/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/lualib/?.lua;/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/lualib/?/?.lua;/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/lualib/?/init.lua;/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/contrib/lua-?/?.lua" test/rspamd-test -p /rspamd/lua'
FAILED: CMakeFiles/run-test /var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999_build/CMakeFiles/run-test
cd /var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999_build && test/rspamd-test-cxx && sh -c 'LUA_PATH="/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/lualib/?.lua;/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/lualib/?/?.lua;/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/lualib/?/init.lua;/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/contrib/lua-?/?.lua" test/rspamd-test -p /rspamd/lua'
[doctest] doctest version is "2.4.9"
[doctest] run with "--help" for options
===============================================================================
/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/src/libserver/html/html_tests.cxx:34:
TEST SUITE: html
TEST CASE:  html parsing

/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/src/libserver/html/html_tests.cxx:34: ERROR: test case THREW exception: basic_string: construction from null is not valid

===============================================================================
/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/src/libserver/html/html_tests.cxx:68:
TEST SUITE: html
TEST CASE:  html text extraction

/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/src/libserver/html/html_tests.cxx:68: ERROR: test case THREW exception: basic_string: construction from null is not valid

===============================================================================
/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/src/libserver/html/html_tests.cxx:225:
TEST SUITE: html
TEST CASE:  html urls extraction

/var/tmp/portage/mail-filter/rspamd-9999/work/rspamd-9999/src/libserver/html/html_tests.cxx:225: ERROR: test case THREW exception: basic_string: construction from null is not valid

===============================================================================
[doctest] test cases:  34 |  31 passed | 3 failed | 0 skipped
[doctest] assertions: 612 | 612 passed | 0 failed |
[doctest] Status: FAILURE!
```

**Comment by vstakhov** [comment]
Interesting, I will check.

**Comment by vstakhov** [comment]
Ok, here is an issue: https://github.com/intel/hyperscan/blob/v5.4.1/src/scratch.c#L250

Indeed, we mmap that file and hyperscan fails when we try to `allocate` scratch. It is so late, so I really don't know how to fix it earlier.

**Comment by vstakhov** [comment]
I have added a workaround that will presumably help to deal with the version change earlier. If Hyperscan authors decide to make a public validation function, Rspamd will eventually use it.

**Comment by vstakhov** [comment]
I have added the final workaround and it all seems to be working now.

**Comment by arkamar** [comment]
Yes, I confirm that everything works as expected for me (in commit 1804b75af86ff346820860207f61451da6e1c772). Is there any plan to do a new release in near future?

**Comment by vstakhov** [comment]
I'm still working on a new package building system, so I have to postpone release until it's ready I'm afraid.

**Comment by vstakhov** [comment]
Done and released.

**Comment by GieltjE** [comment]
Still manualy had to clean the /var/lib/rspamd directory after debian (testing) upgraded from 4.5.0 to 4.5.2.
