### ISSUE TITLE
Block forged sender using multimap?

### ISSUE THREAD

**Issue by Dhanamerdeka** [rspamd/rspamd#4418]
hello guys
how do i block people when they mail is forged?

example
[010901869e31528a-46aa3856-4ded-4278-a96b-68f658035981-000000@ap-south-1.amazonses.com] info@aiplex.com

this mail come from aiplex, i already blocked them via multimap and works, but seems that "amazonses" is the sender if they are forged
so the question how can i block them without blocking other's amazon ses email?

i just want to get rid of this aiplex... they keep sending email everyday

**Comment by vstakhov** [comment]
It is not Rspamd issue, please do not use the issue tracker for support questions.
