### ISSUE TITLE
[BUG] fuzzy_check module does not seem to be working in 3.4?

### ISSUE THREAD

**Issue by nishils** [rspamd/rspamd#4425]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

The fuzzy_check module is not running in my normal rspamd 3.4 worker.

The symbols are registered as viewed through the webui which is connected to the normal rspamd worker.

I've tried adding `filters = "chartable,fuzzy_check,regexp,dkim"` and `filters = "fuzzy_check";` to `local.d/options.inc` as I believe fuzzy_check is still a C module and not a lua module.

However when sending messages of message bodies with at least 2300 characters, I do not see any `FUZZY` symbols being added so I do not believe that this is a ratelimit issue. The webui also does not report any fuzzy hashes server including the default rspamd.com one. 

I tried to enable extra logging for the fuzzy_check module but didn't see anything.

### Steps to Reproduce

1. Run the normal 3.4 worker with default settings.
2. Run the proxy 3.4 worker with default settings.
3. Run the webui 3.4 worker pointing to the normal worker in step 1.
4. Send an email as normal so that rspamd is processing.
5. View results in webui that message was scanned.
6. Note that no fuzzy symbols are present nor does the webui indicate any fuzzy servers are present.

**Expected behavior**
Expect the fuzzy_check to run by default with the rspamd.com filters AND the server shows up in the webui.

### Versions

You can get this information from copy and pasting the output of `rspamd --version` from the command line. Also, please include the **OS** and what version and architecture including the generation of CPU model (e.g. Haswell) where applicable,  of the OS you're running.

Rspamd daemon version 3.4 (https://pkgs.alpinelinux.org/packages?name=rspamd&branch=v3.17&repo=&arch=&maintainer=)
alpine 3.17 
ARM processor

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by a16bitsysop** [comment]
I have it running on arm64 on alpine 3.17, in my logs i get lots of slow rule messages:
`2023-03-08 14:09:20 #295220(normal) <54b1c7>; task; finalize_item: slow rule: FUZZY_CALLBACK(312): 348.99 ms`

also in message results:
`FUZZY_DENIED(8.31){1:b9917f50b7:0.62:txt;}`

In my web interface if I search for fuzzy in symbols it shows for group fuzzy:
```
FUZZY_DENIED
FUZZY_PROB
FUZZY_UNKNOWN
FUZZY_WHITE
FUZZY_CALLBACK
```

what do you get for:
`rspamadm configdump worker`

my webui does not show any fuzzy workers, in the `status` page it only shows the controller worker, it also has a `Fuzzy hashes` section with storage as `rsapmd.com` and a very big number for the number of hashes.

I think a good check would be do you get `FUZZY_CALLBACK` messages in your log, as this is very likely on an sbc?

**Comment by nishils** [comment]
@a16bitsysop thanks for the pointers! Very interesting that it is working for you. 

We have a webui that connects to the scanning workers directly but we use the proxy worker for load balancing (if that at all makes any difference).

I don't see the `FUZZY_CALLBACK` which is interesting but I do see the other `FUZZY_` symbols that you mentioned.

For the actual scanning worker, I ran `rspamadm configdump worker` and the following is the output. 

```
/ # rspamadm configdump worker
*** Section worker ***
controller {
    password = "<redacted password>";
    bind_socket = "*:8081";
    secure_ip [
        "<CIDR1>",
        "<CIDR2>",
        "<CIDR3",
        "<CIDR4>",
    ]
    static_dir = "/usr/share/rspamd/www";
    enabled = true;
    count = 1;
}

*** End of section worker ***
*** Section worker ***
normal {
    mime = true;
    bind_socket = "*:8080";
    max_tasks = 4;
}

*** End of section worker ***
```

I think that `FUZZY_CALLBACK` is a piece of the puzzle here.

**Comment by a16bitsysop** [comment]
I think you are missing the fuzzy worker, mine has one.

The default config is here: https://github.com/rspamd/rspamd/blob/master/conf/worker-fuzzy.inc

https://rspamd.com/doc/workers/fuzzy_storage.html

It could be because you are changing the ports, do you get any log messages about the fuzzy worker?

Or if the workers are on different machines it looks like the fuzzy check module has a server option to put the address of the fuzzy_storage

**Comment by nishils** [comment]
Hmmm. I went ahead and kept only the following two files and removed everything else.
```
local.d/worker-controller.inc
local.d/worker-normal.inc
```

The fuzzy_checks module is enabled by default according to the docs. I tried enabling fuzzy_workers on the same machine just to simplify the setup and get something working but was unable to.

The `fuzzy_checks` I believe is run by default based on the `filters` config option since it is still a C module.

I don't quite understand how to enable fuzzy_workers. I tried doing `enabled=true` in local/worker-fuzzy.conf` but that might be wrong as I couldn't find the documentation that states explicitly how to turn this module on

**Comment by nishils** [comment]
I turned on debug logs and found these interesting statements

```
2023-03-17 16:26:26 [info] #1(main) <meuged>; cfg; rspamd_config_is_module_enabled: internal module fuzzy_check is enabled but has not been configured
2023-03-17 16:26:26 [info] #1(main) <meuged>; cfg; rspamd_config_is_module_enabled: internal module fuzzy_check is enabled but has not been configured
2023-03-17 16:26:26 [info] #1(main) <meuged>; cfg; fuzzy_check_module_config: init internal fuzzy_check module, 0 rules loaded
```

I wonder what configuration is missing because from the docs, I thought this module was already enabled and configured to talk to rspamd.com

**Comment by a16bitsysop** [comment]
I think it might be because you haven’t installed the rspamd-fuzzy package, the alpine packaging is a bit unusual in that it separates out the workers.  Even though it’s only the configs.

I am the alpine maintainer, but the splitting up like that was done from the beginning and hasn’t been changed yet.

**Comment by a16bitsysop** [comment]
fuzzy_check.conf is in the rspamd-fuzzy package for alpine
https://pkgs.alpinelinux.org/contents?branch=edge&name=rspamd-fuzzy&arch=aarch64&repo=community

the split into rspamd-controller rspamd-fuzzy and rspamd-proxy has now been removed in alpine edge with the upgrade to 3.5, so from alpine-3.18 only the client `rspamc` and `rspamd_stats` are split out into sub packages

**Comment by nishils** [comment]
Thank you so much!! I had no idea there were additional packages to install. This fixed the issue!

**Comment by a16bitsysop** [comment]
great, yes it made it confusing like that.  The client is separate as it can run on a different host for ham/spam training via dovecot
