### ISSUE TITLE
[BUG] Version 3.5 RPM (CentOS 7) fails to start up

### ISSUE THREAD

**Issue by DavidAnderson684** [rspamd/rspamd#4441]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Overnight, an automatic update installed the RPM rspamd-3.5-1.el7.x86_64 (from the official repo at https://rspamd.com/rpm-stable/centos-7/x86_64/). Previously, rspamd-3.4-1.x86_64.rpm from the same repo was being run.

The script in the rpm calls `systemctl try-restart rspamd.service`. The result was that `rspamd` failed to restart. Attempts to restart manually also failed. 

[rspamd.log](https://github.com/rspamd/rspamd/files/11008067/rspamd.log)

Above is a link to the log file; the final 3 lines mention a fatal error, and are:

```
2023-03-18 08:46:34 #391(main) rspamd_url_init: start compiling of 9628 TLD suffixes; it might take a long time
2023-03-18 08:46:34 #391(main) rspamd_multipattern_compile: cannot allocate scratch space for hyperscan: error code -5
2023-03-18 08:46:34 #391(main) rspamd_url_init: cannot compile url matcher static patterns, fatal error: cannot allocate scratch space for hyperscan: error code -5
```

This happens every time. Downgrading back to 3.4 allowed rspamd to successfully start again.

### Versions

OS: CentOS Linux release 7.9.2009 (Core) running on AMD EPYC 7601 32-Core Processor

**Comment by vstakhov** [comment]
It's presumably because hyperscan in Centos 7 is teribly outdated. I'd suggest to upgrade your system to a more modern one. As a workaround, you can just remove all files matching the pattern `/var/lib/rspamd/*.hs*` and restart Rspamd. It will work fine after that.

**Comment by DavidAnderson684** [comment]
Thank you - I can confirm that after removing those files, rspamd 3.5 successfully restarted.

**Comment by DavidAnderson684** [comment]
Will there be a post coming about the new release at https://rspamd.com/blog/ ? (Latest post announces the release of 3.4).

**Comment by vstakhov** [comment]
It's not Rspamd issue, I'm afraid.

**Comment by matyasmatyas** [comment]
Hardware and OS  upgrade is the only solution?

**Comment by vstakhov** [comment]
I'm not very happy about making it a requirement. I'll see what can I do, probably, there will be a version with some fix.

**Comment by vstakhov** [comment]
Can you check `-3` version?

**Comment by matyasmatyas** [comment]
I can confirm that rspamd-3.5-3.el7 does not produce the issue on machines without AVX support.

Thank you so much for the quick fix.
