### ISSUE TITLE
[BUG] DMARC check false negative for messages with multiple DKIM-Signature headers

### ISSUE THREAD

**Issue by eugen-ukraine** [rspamd/rspamd#4450]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

Looks like DMARC check only considers first DKIM-Signature header for alignment checks. If message has a valid DKIM-Signature for aligned domain name, but not in the first DKIM-Signature header, then DMARC check will produce false DMARC_POLICY_REJECT symbol.

### Steps to Reproduce

Message: [84556194008E.txt](https://github.com/rspamd/rspamd/files/11116299/84556194008E.txt)

rspamc command, including emulated relevant smtp session params:

```
rspamc  -i 158.247.18.160 -F 1axcev2y4kw3jhjx2ars8o4dz32u8p3r5rodef-test=udevops.fun@bf06x.hubspotemail.net -r test@udevops.fun --helo bid46pe.bf06x.hubspotemail.net --hostname bid46pe.bf06x.hubspotemail.net symbols ./84556194008E.txt
```

result (trimmed):

```
Symbol: DKIM_TRACE (0.00)[bf06x.hubspotemail.net:+]
Symbol: DMARC_POLICY_REJECT (2.00)[right-hand.ai : SPF not aligned (strict), DKIM not aligned (strict)]
Symbol: R_DKIM_ALLOW (-0.20)[bf06x.hubspotemail.net:s=hs1]
Symbol: R_SPF_ALLOW (-0.20)[+ip4:158.247.18.160/28:c]
```

**Expected behavior**

Message should receive DMARC_POLICY_ACCEPT symbol instead of DMARC_POLICY_REJECT, as it contains a valid dkim signature for d=right-hand.ai, which is in alignment with sender domain right-hand.ai in strict mode.

### Versions

OS: AlmaLinux 8.7 (Stone Smilodon)
rspamd: Rspamd daemon version 3.5 (from https://rspamd.com/rpm-stable/centos-8/x86_64/rspamd-3.5-2.el8.x86_64.rpm)

**Comment by vstakhov** [comment]
I don't see a valid signature for `right-hand.ai` domain.

**Comment by vstakhov** [comment]
It might probably be related to the signatures expiration: their `t` and `x` parameters are the same. So it is most likely that your signing side has something wrong with signature expiration. Rspamd ignores expired signatures, but there could be probably a window of 1 second when this signature is valid. Anyway, it is clearly not an Rspamd fault - please check the expire of your signatures, as they are likely incorrect.

**Comment by eugen-ukraine** [comment]
Original message has expired DKIM signature. Unfortunately, I'm on receiving side here, so can't produce messages with longer ttl. Here's fresh example (I skipped SPF this time as it's not really relevant here):

Message: [2-headers.txt](https://github.com/rspamd/rspamd/files/11142524/2-headers.txt)

Scan result contains DMARC_POLICY_REJECT symbol with explanation `DKIM not aligned (relaxed)`

```
# rspamc  symbols ./2-headers.txt | egrep '(DKIM|DMARC)'
Symbol: DKIM_TRACE (0.00)[bf03.hubspotemail.net:+]
Symbol: DMARC_POLICY_REJECT (2.00)[grantcardone.com : No valid SPF, DKIM not aligned (relaxed)]
Symbol: R_DKIM_ALLOW (0.00)[bf03.hubspotemail.net:s=hs1]
```

And here's the same message with removed first DKIM-Signature header: [1-header.txt](https://github.com/rspamd/rspamd/files/11142534/1-header.txt)

This time scan result contains DMARC_POLICY_ALLOW symbol:

```
# rspamc  symbols ./1-header.txt | egrep '(DKIM|DMARC)'
Symbol: DKIM_TRACE (0.00)[grantcardone.com:+]
Symbol: DMARC_POLICY_ALLOW (0.00)[grantcardone.com]
Symbol: R_DKIM_ALLOW (0.00)[grantcardone.com:s=hs1-5802030]
```

I'm not familiar with rspamd internals, but it seems to me that the reason is that DMARC check relies on DKIM_TRACE symbols, which due to https://github.com/rspamd/rspamd/blob/master/src/plugins/dkim_check.c#L1030 is added only once per message. So any subsequent DKIM-Signature headers are ignored.

**Comment by eugen-ukraine** [comment]
> It might probably be related to the signatures expiration: their `t` and `x` parameters are the same

No, they aren't. Here's values from original example (one under another for clearer view):

```
t=1680210684
x=1680383484
```

So `x` is 172800 seconds greater than `t`. 

New examples also have the same 172800 seconds signature expiration time.

**Comment by vstakhov** [comment]
> I'm not familiar with rspamd internals, but it seems to me that the reason is that DMARC check relies on DKIM_TRACE symbols, which due to https://github.com/rspamd/rspamd/blob/master/src/plugins/dkim_check.c#L1030 is added only once per message. So any subsequent DKIM-Signature headers are ignored.

No, it cannot be the case: `DKIM_TRACE` is intended to be added multiple times as it is exactly the main symbol to track multiple DKIM signatures. We have a number of functional tests around this logic as well as the real messages volume.

**Comment by vstakhov** [comment]
For your particular samples I have `DMARC_POLICY_ALLOW` in both of the cases:

1-header:

```
Symbol: DKIM_TRACE (0.00)[grantcardone.com:+]
Symbol: DMARC_POLICY_ALLOW (-0.50)[grantcardone.com, reject]
```

2-header:

```
Symbol: DKIM_TRACE (0.00)[bf03.hubspotemail.net:+, grantcardone.com:+]
Symbol: DMARC_POLICY_ALLOW (-0.50)[grantcardone.com, reject]
```

I think that you have manualy redefined `DKIM_TRACE` symbol to be one shot or did something like that. With the out-of-the box settings, your issue seems to be unreproducible.

**Comment by eugen-ukraine** [comment]
> No, it cannot be the case: `DKIM_TRACE` is intended to be added multiple times

Sure, you're right. Didn't notice initialization.

> I think that you have manualy redefined `DKIM_TRACE` symbol to be one shot or did something like that

Yes, that's the case. I have redefined global  `one_shot = true`. With `false` issue is not reproducible. Thank you for clarification.

Consider ignoring `one_shot` for `DKIM_TRACE` as it breaks DMARC check for messages with multiple `DKIM-Signature` headers

**Comment by vstakhov** [comment]
It should be fixed by now.
