### ISSUE TITLE
[BUG] Rspamd 3.5 on ubuntu 18.04 - libunwind: bad fde

### ISSUE THREAD

**Issue by yo-hansolo** [rspamd/rspamd#4466]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Hi,
I installed the update today of rspamd to 3.5 on 2 identic unbuntu 18.04 TLS Bionic servers.
In fact I followed the complementary process requiring the addition of the llvm libraries for the stable branch.

Several dependencies have been modified
```
The following packages will be REMOVED:
  libc++1 libc++abi1
The following NEW packages will be installed:
  gcc-11-base libc++1-16 libc++abi1-16 libgcc-s1 libunwind-16
Update
  rspamd
```
At the time of this update, it was proposed to install 'clang' but I did not do it.

The Rspamd service seems to work normally. However, it regularly throws an error in its logs which you will find below. And it has something to do with this update above as the error is related to libunwind.

```
avril 24 19:06:09 ns343672 rspamd[15041]: libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE
avril 24 19:06:20 ns343672 rspamd[15041]: libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE
... same message 5 times, random time intervals
avril 24 20:48:45 ns343672 rspamd[15041]: libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE
avril 24 21:41:11 ns343672 rspamd[15041]: libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE
avril 24 21:51:40 ns343672 rspamd[15041]: libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE
```
Is there a missing dependencie on the two systems ?

### Steps to Reproduce
no idea because I followed the procedure exactly

**Expected behavior**
No error thrown by libunwind

### Versions
Update Rspamd 3.3 straigth to 3.5
Xeon CPU W3520 - 4c/8t | 16Gb RAM
Ubuntu 18.04.6 LTS Bionic, up to date, with Ubuntu Pro activated on each server.

### addtional
after writing this post, i did another apt update, upgrade and it turns out that there were 8 dependencies to update on each of the two servers (the same for both of them obviously).
I performed this update.
```
libquadmath0:amd64 (11.1.0-1ubuntu1~18.04.1) ...
libgomp1:amd64 (11.1.0-1ubuntu1~18.04.1) ...
libatomic1:amd64 (11.1.0-1ubuntu1~18.04.1) ...
libcc1-0:amd64 (11.1.0-1ubuntu1~18.04.1) ...
libobjc4:amd64 (11.1.0-1ubuntu1~18.04.1) ...
libtsan0:amd64 (11.1.0-1ubuntu1~18.04.1) ...
liblsan0:amd64 (11.1.0-1ubuntu1~18.04.1) ...
libitm1:amd64 (11.1.0-1ubuntu1~18.04.1) ...
```
I'll keep an eye out to see if the FDE errors continue after that.

Thank you.
CheerS/.

**Comment by yo-hansolo** [comment]
well, despite the last update I mentioned in "additionnal" in my first post, the warning messages continue:
```
avril 25 10:01:19 ns343672 rspamd[15041]: libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE
8 times the same message in journalctl
avril 25 10:47:50 ns343672 rspamd[15041]: libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE
avril 25 11:11:04 ns343672 rspamd[15041]: libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE
```
Nothing appear in the log that drives me to a clue
Rspamd seems to work fine by the way ^^'

CheerS/.

**Comment by vstakhov** [comment]
Ubuntu bionic is no longer supported. I do regret that the packages for this distributive were occasionally upgraded to 3.5 - it was a mistake.

**Comment by yo-hansolo** [comment]
Hello @vstakhov,
Thank you for your response.
Sorry to hear that the upgrade to 3.5 should not have happened. 

At this point, for the sake of our business with Rspamd, is the error that is generated really annoying or not?
Because from our point of view, it seems that the program is working nominally; the filters seem to be working, the rejection engines too.
But we are not experts in this field unfortunately.

Thank you in advance for your kind reply
