### ISSUE TITLE
cannot create tree of regexp when processing '####': Zero-width assertions are not supported.[BUG]

### ISSUE THREAD

**Issue by Code-TT** [rspamd/rspamd#4472]
I have a map to filter the subject. In the map I use this RegEx: `/sex(?!y|u)/i`
It filters out everything with sex, but not sexy and sexualkunde. It works fine. 

But in the logfile I get this error (main worker, module map):
`cannot create tree of regexp when processing 'sex(?!y|u)': Zero-width assertions are not supported.`

### Steps to Reproduce

1. Make a Map for subject filtering with regex
2. put regex in Map-File: `/sex(?!y|u)/i`
3. wait and check Logfile or reboot rspamd and check logfile

**Expected behavior**
The regex is working properly and subjects are filtered correctly. So I expect no error message in the Logfile.

### Versions

Rspamd daemon version 3.5

**Comment by vstakhov** [comment]
Not a bug: do not use this sort of regular expressions, the error is 100% clear. Everything that is not [supported by Hyperscan](https://intel.github.io/hyperscan/dev-reference/compilation.html#pattern-support) should not be used in Rspamd regular expressions in general.
