### ISSUE TITLE
[Feature] automated password hash output

### ISSUE THREAD

**Issue by msimerson** [rspamd/rspamd#4483]
## Summary

Permit rspamd password to be hashed via scripts

## Motivation

I'm setting up a system and the postmaster password is already defined and available. I want to store the hashed form of that password in `local.d/worker-controller.inc` instead of inserting it as plain text.

## Describe alternatives you've considered

- Try passing it on the command line: `rspamadm pw PASSWORD`, doesn't work
- Try passing it on stdin `echo 'PASSWORD' | rspamadm pw -`, doesn't work.
- pkg install apache24 && htpasswd -bnBC 10 "" PASSWORD | tr -d ':\n'. Yuck!
- pkg install py39-bcrypt && python -c 'import bcrypt; print(bcrypt.hashpw("PASSWORD", bcrypt.gensalt(log_rounds=10)))'

## Additional context

If I use an external utility to generate the hashes, I have to know the bcrypt params (or guess), and then keep them updated in the future when rspamd changes, or moves on from bcrypt to quantumCrypt.

**Comment by msimerson** [comment]
Another way to skin this cat: with a `rspamadm pw --update` or on server startup, if a plain text password is found and isn't q1 or q2, then hash it and update the plain text version.

**Comment by fatalbanana** [comment]
`rspamadm pw -p PASSWORD` works

**Comment by msimerson** [comment]
Okay, I have found a documentation issue. I had tried this (after following docs for syntax):

````
# rspamadm help pw
Rspamadm 3.5
Usage: rspamadm [global_options] command [command_options]

Showing help for pw command

Manipulate with passwords in rspamd

Usage: rspamadm pw [command]
Where commands are:

--encrypt: encrypt password (this is a default command)
--check: check encrypted password using encrypted password
--list: list available pbkdf algorithms
--type: select the specified pbkdf type
--help: shows available options and commands
````

No mention of the password option. But it does show up when you ask for help another way:

````
# rspamadm pw --help
Usage:
  rspamadm [OPTION…] pw [--encrypt | --check] - manage rspamd passwords

Summary:
  Rspamd administration utility version 3.5
  Release id: release

Help Options:
  -h, --help         Show help options

Application Options:
  -e, --encrypt      Encrypt password
  -c, --check        Check password
  -q, --quiet        Suppress output
  -p, --password     Input password
  -t, --type         PBKDF type
  -l, --list         List available algorithms

````

The feature I want exists, I'm happy. Maybe this issue relates to documentation?
