### ISSUE TITLE
[BUG] SSL error for reading maps with FIPS enabled

### ISSUE THREAD

**Issue by tdewolff** [rspamd/rspamd#4511]
When running CentOS Stream 9 with FIPS mode enabled, some (insecure) algorithms are disabled on the machine and is making Rspamd throw the following error:

> 2023-06-07 19:21:22 #1221988(controller) <7n3qic>; map; http_map_error: error reading https://maps.rspamd.com/rspamd/mid.inc.zst(88.198.198.21:443): connection with http server terminated incorrectly: ssl connect error: ssl error: error:1C8000E9:Provider routines::ems not enabled,ssl error: error:0A08010C:SSL routines::unsupported

The same happens when running cURL:

```
# curl -D - https://maps.rspamd.com/rspamd/mid.inc.zst
curl: (35) error:1C8000E9:Provider routines::ems not enabled
```

Using `wget` works though, which is probably circumventing the issue. Not sure if this is an issue of the server at rspamd.com or with the rspamd daemon.

**Comment by vstakhov** [comment]
Not Rspamd issue.

**Comment by breisig** [comment]
Im getting this EXACT same issue with Rocky Linux 9. This actually effects OTHER services too and I was surprised no one else had reported it. It's related to FIPS 140-3 and changes in https://lwn.net/Articles/935817/

After lots of testing, I have found my own workaround.

Edit /etc/crypto-policies/back-ends/opensslcnf.config and add this to the bottom of the file.
```
SSL_OP_NO_EXTENDED_MASTER_SECRET
```
