### ISSUE TITLE
Warnings from Rspamd

### ISSUE THREAD

**Issue by frzqwerty** [rspamd/rspamd#4516]
Greetings to Rspamd team.

On OpenBSD and Rspamd version rspamd-3.4p2-hyperscan, I get the following warning/error messages frequently in my log file:

`2023-06-19 02:43:30 #93038(main) <ngs8us>; symcache; save_items: cannot create file /var/rspamd/symbols.cache.new: No such file or directory`
(I created an empty symbols.cache.new file there, however the problem persists after reboots)

And I have really no idea about this one:
`2023-06-19 02:44:53 #11471(main) <ngs8us>; lua; neural.lua:821: use NN prefix for rule rn2_default_1_default; settings id "default"; symbols digest: "txka5x9wbgu93fj9zysa4x6tpxrix367z1pp3e89kk5j7tdswbpo6i36uwyxh4gzcdsn8jmp5rg8gb4dachh7zy`

How can I eliminate thos two messages from the log file, finding a solution to both of them?

Any idea would be much appreciated, many thanks!

**Comment by kasak87** [comment]
i'm also using openbsd and have never seed such warnings.
maybe some troubles with perms?
```
ls -ld /var/rspamd
drwxr-xr-x  4 _rspamd  _rspamd  12800 Jun 22 13:59 /var/rspamd
```
do you have any specific conf for neural module ? 
mine is: 
```
cat /etc/rspamd/local.d/neural.conf                                                                                                                            
enabled = true;
```

**Comment by frzqwerty** [comment]
Hi kasak, thanks a lot for your reply.

I don't even really have it enabled? See please:

> [root@mail:/etc/rspamd/local.d]# ls -al
> total 72
> drwxr-xr-x  2 root  wheel   512 Jun 19 10:37 .
> drwxr-xr-x  8 root  wheel  1024 Jun 19 11:29 ..
> -rw-r--r--  1 root  wheel   185 Jun 15 22:59 actions.conf
> -rw-r--r--  1 root  wheel    97 Jun 15 17:28 classifier-bayes.conf
> -rw-r--r--  1 root  wheel   100 Jun 15 22:46 dkim_signing.conf
> -rw-r--r--  1 root  wheel    46 Jun 15 17:29 logging.inc
> -rw-r--r--  1 root  wheel   284 Jun 15 17:29 multimap.conf
> -rw-r--r--  1 root  wheel    16 Jun 15 17:29 mx_check.conf
> -rw-r--r--  1 root  wheel    92 Jun 15 17:29 options.inc
> -rw-r--r--  1 root  wheel    52 Jun 15 17:30 phishing.conf
> -rw-r--r--  1 root  wheel    69 Jun 19 10:37 redis.conf
> -rw-r--r--  1 root  wheel    22 Jun 15 17:30 replies.conf
> -rw-r--r--  1 root  wheel    61 Jun 15 17:30 surbl.conf
> -rw-r--r--  1 root  wheel    16 Jun 15 17:31 url_reputation.conf
> -rw-r--r--  1 root  wheel    16 Jun 15 17:31 url_tags.conf
> -rw-r--r--  1 root  wheel   679 Jun 19 11:01 worker-controller.inc
> -rw-r--r--  1 root  wheel    17 Jun 15 17:32 worker-normal.inc
> -rw-r--r--  1 root  wheel   411 Jun 15 17:32 worker-proxy.inc
> 

And it seems it's not a perms trouble?

> [root@mail:/etc/rspamd/local.d]# ls -ld /var/rspamd/
> drwxr-xr-x  2 _rspamd  _rspamd  11776 Jun 23 22:26 /var/rspamd/

**Comment by vstakhov** [comment]
Version 3.4 is not supported, not a bug.
