### ISSUE TITLE
How to get more information about IO timeout errors?

### ISSUE THREAD

**Issue by vadz** [rspamd/rspamd#452]
I'm using `rspamc` from Exim as a pipe command and globally it works just fine but I've already got 3 times (for ~1000 messages) an apparently bogus timeout error, i.e. the received (spam) message has the following headers:

```
X-Spam-Scanner: rspamc 1.1.0
X-Spam-Scan-Time: 5.005
X-Spam-Error: IO timeout
```

and there is no trace of it in `rspamd.log` at all. Running `rspamc` with it on the comment line successfully recognizes it as spam and takes less than one second (I tried it several times and there is a pretty big variation which is also strange, but it's never close to 5s).

I suppose that there must have been some transient network problem which prevented an RBL lookup from completing or something like this, but how can I really know it? I.e. is there any way to get more information in case a timeout occurs, e.g. add some description of the operation that timed out to `X-Spam-Error` header? Otherwise I'm really not sure how am I supposed to prevent this from happening in the future...

**Comment by vstakhov** [comment]
Well, that's unfortunately exim issue. I don't know how to setup exim timeout for rspamd reply waiting to tell the truth. Obviously, high scan times could be caused by slow DNS replies, for example. There is also parameter called `task_timeout` that limits the overall processing time allowed for a single task. You might want to set it a bit lower than exim timeout, for example by the following configuration:

```
worker {
  type = "normal";
  ...
  task_timeout = 4s;
}
```

Please mention that you need to modify **worker's** section not `options` one. In future, the corresponding option might be added as well.

**Comment by fatalbanana** [comment]
Default timeout on Exim's pipe transport is `1h` which should be plenty. You can increase timeout used by `rspamc` by passing `-t` flag.

**Comment by vadz** [comment]
Thanks for the tip about `rspamc -t`, this does mitigate the problem somewhat, but it still happens, albeit more rarely. I think it would be much better if rspam could just skip the DNS lookup or whatever that is taking so long (I still have no idea what it is...) and use the other checks as it seems all but certain that most of the messages that now end up in my inbox with `X-Spam-Error: IO timeout` header would have been recognized as spam anyhow.

And I can confirm that it is definitely _not_ an Exim issue.

**Comment by vstakhov** [comment]
Well, I've added logic to remove delayed filters when timeouting a task. However, please mention that it won't work for post-filters.

**Comment by vadz** [comment]
Sorry, how does this work in practice? I.e. what exactly do I have to do to classify the message using the results of the checks that could be performed during a timeout instead of just letting it through? TIA!

**Comment by vstakhov** [comment]
I'm not with you I'm afraid. What do you want to classify? With this change, rspamd just stops all pending checks and go to the step of classification/postfilters. What to you suggest to do about the rules pending? I don't see anything useful about it besides of just ignoring such rules.

**Comment by vadz** [comment]
I thought some configuration changes were needed to enable it, I didn't realize it would be the case by default, sorry. I'll wait for the `.deb` with this commit to appear at https://rspamd.com/apt/pool/main/r/rspamd/ and try it when it does then, thanks!

**Comment by vstakhov** [comment]
It should be there in approx 10-15 mins.

**Comment by fatalbanana** [comment]
@vadz - I suppose you're systemd socket activation?

**Comment by vadz** [comment]
@fatalbanana No, this is an old Debian Wheezy system without systemd.

**Comment by fatalbanana** [comment]
Do you still see this issue in contemporary versions of rspamd?

**Comment by vadz** [comment]
I'm going to upgrade this system to Jessie soon and will use this as an opportunity to update rspam on it as well. I guess this can be closed if you think this should have been fixed by some (relatively) recent changes, I could reopen it later if I see it again. Thanks!

**Comment by Hello71** [comment]
I got this problem but using Postfix -> rspamd proxy selfscan, and now the timeout is apparently 10 seconds instead of 5. according to rspamd.log from "rspamd_message_parse: loaded message" to "rspamd_protocol_http_reply" took <1 second though, so I don't think `rspamc -t` will help too much (although I should probably make it more than 10 seconds).
