### ISSUE TITLE
[BUG] Greylist threshold in settings.conf ignored

### ISSUE THREAD

**Issue by bsdice** [rspamd/rspamd#4526]
Hey guys, I have checked current documentation, open and closed tickets, discussions, and multiple search engines for template syntax and configurations. Found little to nothing. Version of rspamd in use is from master as of today.

Goal is to apply a different greylisting threshold in settings.conf like -20, opposed to default = 4 from actions.conf, depending on mail sender's hostname. Setting is applied which I can see in log, but new greylist threshold is ignored.

Overall intention is to quench spam from Amazon SES spam service by delaying their e-mails long enough to give RBLs time to catch up. I assume these are hacked accounts. We do not get alot of these, so this is certainly all a very low priority. But it bugs me that stuff like this can sail into user mailboxes with score -4.8.

local.d/redis.conf:
```
servers = "127.0.0.1";
timeout = 10s;
```
local.d/greylist.conf:
```
timeout = 11min;
expire = 8d;
```
local.d/settings.conf:
```
amazonses {
    id = "amazonses";
    priority = medium;
    hostname = "/\.amazonses\.com$/i";
    apply {
        actions {
            greylist = -20;
        }
    }
    symbols [ "AMAZON_SES" ];
}
```
local.d/composites.conf (to have a symbol in mail header):
```
AMAZON_SES {
	expression = "0==1"; # Always false
	description = "Mail sent through Amazon SES";
}
```
local.d/groups.conf (to provoke a very low score when testing with rspamc):
```
symbols = {
	"AMAZON_SES" {
		weight = -20;
	}
}
```
Log says:
```
lua; greylist.lua:331: Score too low - skip greylisting
lua; greylist.lua:334: Downgrading metric action from "greylist" to "no action"
```
`echo bla | rspamc --hostname depp.amazonses.com`
```
Results for file: stdin (0.45 seconds)
[Metric: default]
Action: no action
Spam: false
Score: -12.10 / 15.00
Symbol: AMAZON_SES (-20.00)
Symbol: ARC_NA (0.00)
Symbol: DMARC_NA (0.00)[No From header]
Symbol: MIME_GOOD (-0.10)[text/plain]
Symbol: MIME_TRACE (0.00)[0:+]
Symbol: MISSING_DATE (0.00)
Symbol: MISSING_FROM (2.00)
Symbol: MISSING_MID (2.50)
Symbol: MISSING_SUBJECT (1.50)
Symbol: MISSING_TO (2.00)
Symbol: RCVD_COUNT_ZERO (0.00)[0]
Symbol: R_DKIM_NA (0.00)
Message-ID: undef
```

**Comment by vstakhov** [comment]
Settings are checked before all other symbols, so your assumptions are just invalid: it simply won't work.

**Comment by bsdice** [comment]
Thank you for looking into it, appreciate it. I will study documentation and source code again.

**Comment by vstakhov** [comment]
You need something like a postfilter for that purposes I suppose: they are executed after all other checks are done and they can modify the final result. Alternative is a normal filter with dependency on all other symbols involved (you can take a look at [force action module](https://rspamd.com/doc/modules/force_actions.html) as well).
