### ISSUE TITLE
[BUG] Error in fuzzy_lua_unlearn_handler()

### ISSUE THREAD

**Issue by mdierksen** [rspamd/rspamd#4531]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
https://github.com/rspamd/rspamd/blob/06f52fae3a0e57ee8d01aaa974139f3b31bf296c/src/plugins/fuzzy_check.c#L3870

Should be `flag = lua_tointeger (L, 2);`.

**Comment by vstakhov** [comment]
That's a good catch, thank you!
