### ISSUE TITLE
Android Gmail app (not using Gmail) messages trigger ` MISSING_MIMEOLE`

### ISSUE THREAD

**Issue by NicolasT** [rspamd/rspamd#4561]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
<details>
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch
</details>

**Describe the bug**
Messages sent using the default Google Android e-mail application ('Gmail'), but using an account on a private SMTP server (i.e., not actually using Gmail at all) trigger the `MISSING_MIMEOLE` rule (with score 2). Indeed, the following headers are (automatically) added to the submitted e-mail:

```
Importance: Normal
X-Priority: 3
X-MSMail-Priority: Normal
MIME-Version: 1.0
```

but there's no `X-MimeOLE` header to be found. This rule has some [whitelisting](https://github.com/rspamd/rspamd/blob/04c2886544ca562a0b9154974ecc491d14e0fba6/rules/regexp/headers.lua#L631) in place (checking `X-Mailer` for `SquirrelMail` and `Microsoft (Office) Outlook`), but the Android app doesn't seem to provide an `X-Mailer`. It does send a `X-Android-Message-ID` header, which could be matched on.

Oddly enough, when sending an e-mail using the very same app now using an actual Gmail account, the `Importance`/`X-Priority`/`X-MSMail-Priority` headers are *not* included in the resulting message and hence the `MISSING_MIMEOLE` rule is not triggered.

### Steps to Reproduce

1. Set up an account in the Android Gmail app using a non-Google SMTP server using `rspamd`, including filtering of outgoing messages
2. Send an e-mail using the Gmail app to some address
3. Check scoring of the outgoing message (e.g., in the web UI)

I assume (but didn't test yet) reproduction is possible by sending an e-mail using the Gmail app to a server using `rspamd` for incoming messages, then checking the report of said message.

**Expected behavior**
No increased score by sending a bonafide message using a fairly standard MUA which sets some header (but not another one).

### Versions

Rspamd daemon version 3.4, on Linux.

**Comment by fatalbanana** [comment]
Is it some sort of Microsoft-flavoured SMTP server?

Likely this rule doesn't make sense & should be dropped but I was unable to reproduce the issue at hand.

**Comment by NicolasT** [comment]
> Is it some sort of Microsoft-flavoured SMTP server?

No, a fairly standard setup with Postfix as MTA and Dovecot as MDA. The headers seem to be added by the Android/Google Mail client app directly.

> Likely this rule doesn't make sense & should be dropped but I was unable to reproduce the issue at hand.

I tend to agree the rule seems a bit arbitrary. FWIW, it appears SpamAssassin has something similar, [with a whole lot of special-cases in place](https://github.com/apache/spamassassin/blob/6cec9905d924275b2ee7a8d6e991c3be4c555da5/rules/20_head_tests.cf#L320) (though nothing about the Gmail app).

**Comment by fatalbanana** [comment]
I was able to reproduce this using the GMail app with a normal IMAP/SMTP account.

Its SpamAssassin's rule exactly more-or-less; many were carried over directly long ago.

**Comment by vstakhov** [comment]
> Its SpamAssassin's rule exactly more-or-less; many were carried over directly long ago.

Can/should we fix it?

**Comment by fatalbanana** [comment]
@citrin @moisseev et al.: Is this rule useful / worth fixing?

**Comment by NicolasT** [comment]
I think for now I'll add a `header_check` in my `submission`'s Postfix configuration to add the `X-MimeOLE` header when "necessary".

(Now, IMHO the rule should be either extended to "support" the Gmail app which is quite established, maybe though not often used with non-Gmail infrastructure, or dropped altogether since to me it seems very arbitrary, especially given all the existing special-cases for various MUAs already in place).
