### ISSUE TITLE
[BUG] Error cfg; rspamd_init_lua_filters during start

### ISSUE THREAD

**Issue by urmel1960** [rspamd/rspamd#4563]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
The folowing error is shown in the log

`2023-08-04 17:28:45 #513689(main) <zfwfcn>; cfg; rspamd_init_lua_filters: init of /usr/share/rspamd/plugins/dmarc.lua failed: /usr/share/rspamd/plugins/dmarc.lua:503: attempt to index field 'reporting' (a boolean value); trace: [1]:{/usr/share/rspamd/plugins/dmarc.lua:503 - <unknown> [main]};
`
### Steps to Reproduce

stop rspamd 
start rspamd 

### Versions

Rspamd daemon version 3.6

CPU architecture x86_64; features: avx2, avx, sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
Hyperscan enabled: TRUE
Jemalloc enabled: TRUE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.0-beta3)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE

Ubuntu 22.04 LTS
Linux 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vstakhov** [comment]
Your reporting module is misconfigured, please read the upgrading notes. Not a bug, closing.

**Comment by urmel1960** [comment]
On rspamd.com latest release announcement is 3.5
Upgrade notes end with Migration to Rspamd 3.3

Can you please provide the link to the upgrade notes ?


Am 07.08.2023 11:40:35, schrieb "Vsevolod Stakhov" 
***@***.***> :

**Comment by vstakhov** [comment]
https://rspamd.com/doc/migration.html#migration-to-rspamd-30
