### ISSUE TITLE
[BUG] since update to 3.6 - error mesage: invalid symbol types

### ISSUE THREAD

**Issue by urmel1960** [rspamd/rspamd#4565]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug*
updated to 3.6 - all running well so far except the error message:

`cannot add dependency from SPAMTRAP on FORCE_ACTION_BLOCK_WHITELISTED_TO_SPAMTRAP: invalid symbol types`

local.d/force_actions.conf:
```
rules {
BLOCK_WHITELISTED_TO_SPAMTRAP {
    # This is the action we want to force
    action = "reject";
    # If the following combination of symbols is present:
    expression = "SPAMTRAP & (SENDER_FROM_WHITELISTED_DOMAIN | SENDER_FROM_WHITELISTED_TLD | SENDER_FROM_WHITELISTED_ADDR)";
  }
}

```
This rule ran without error in previous versions. The symbols used in the expression above are used in other rules as well - without error message.

Removing this rule from force_actions.conf eliminates the error message. 

### Versions

Rspamd daemon version 3.6

CPU architecture x86_64; features: avx2, avx, sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
Hyperscan enabled: TRUE
Jemalloc enabled: TRUE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.0-beta3)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE

Ubuntu 22.04 LTS
Linux 5.15.0-78-generic https://github.com/rspamd/rspamd/issues/85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vstakhov** [comment]
Force action plugin works as a normal filter whilst spamtrap plugin works as postfilter. It just cannot work and it could not work previously either.
