### ISSUE TITLE
[Feature] Webui history better colors for action badges - hard to see a difference for dyschromatopsia

### ISSUE THREAD

**Issue by apuls** [rspamd/rspamd#4566]
## Summary

Have better colors / add alternative color scheme for action badges in webui / history for people with ex. dyschromatopsia

## Motivation

I have dyschromatopsia and it's realy hard for me now to see any difference in the "no action" and "rejected" badges. (Version 3.6)

## Describe alternatives you've considered

The colors in 3.5 where ok and it was easy to see the difference.

Screenshot from 3.6
![screenshot-rspamd_3 6](https://github.com/rspamd/rspamd/assets/64767541/f70d32d3-4de2-4247-8725-fcb06bcff334)

**Comment by moisseev** [comment]
Can you suggest a better color or it is good enough if we return `no action` badge background from 3.5?
So it will look like this:
![2023-08-08 18_43_47-Window](https://github.com/rspamd/rspamd/assets/2275981/b7d178ee-2e4d-44a7-adfb-2a1578292f51)

**Comment by apuls** [comment]
Hi,

I think (in my case) the problem isn't the "no action" button it's the color of the reject "button".

I've done some realy simple color changes today.
The success-rgb are minimal changes (not worthwhile) but the danger-rgb just contains red and no other color anymore.
```
bs-danger-rgb 255,0,0 (red)
bs-success-rgb 0,139,69 (springgreen 4) OR
bs-success-rgb 46,139,87 (seagreen) 
```

![rspamd-badges-new](https://github.com/rspamd/rspamd/assets/64767541/cced74d4-5766-40f7-98d6-5bd1f88ad601)

**Comment by moisseev** [comment]
IMO `red` looks too bright.
How about slightly darker `danger-rgb`?
```
    --bs-danger-rgb: 221, 0, 0;
    --bs-success-rgb: 0, 139, 69;
```

**Comment by apuls** [comment]
For me it's much better as the current settings because the greenish in ```danger-rgb``` is missing.
I would appreciate it if it could be changed as you suggested.
