### ISSUE TITLE
[BUG] Crash at startup with `local_addrs = [ [2001:db8::]/32 ];`

### ISSUE THREAD

**Issue by massar** [rspamd/rspamd#4571]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

Rspamd crashes at startup when unexpected config is given...

### Steps to Reproduce

Install clean new rspamd (`apt-get install rspamd`), put in /etc/rspamd/local.d/options.inc a mere:

```
local_addrs = [ [2001:db8::]/48 ];
```

Issue a restart: `systemctl restart rspamd`

```
[3375367.337457] rspamd[2810219]: segfault at 0 ip 00007f735a2ddd19 sp 00007ffe7be36b18 error 4 in libc.so.6[7f735a1ae000+155000] likely on CPU 0 (core 0, socket 0)
```

That does not really instil confidence... should be easy to reproduce and tackle though.

**Expected behavior**

Not crashing (segfault) when unexpected configuration is given.

### Versions

3.4-1

The current Debian Package in Bookworm.

### Additional Information

Nope, should be easy to replicate ;)

**Comment by vstakhov** [comment]
You need to insert quotes for that particular case, of course. How UCL is intended to distinguish array syntax from IPv6 address? However, a crash is undesired behaviour indeed.
