### ISSUE TITLE
while upgradr rspamd it will shown a dependencies issue

### ISSUE THREAD

**Issue by k04d01** [rspamd/rspamd#4635]
Hi,

if I do 
   apt upgrade rspamd 
it can't upgraded. Therfore  i do 
   apt install rspamd 
to force upgrade rspamd. Here it comes to the following output:

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 rspamd : Depends: libbinutils (< 2.34.1) but 2.38-4ubuntu2.3 is to be installed
E: Unable to correct problems, you have held broken packages.

what can i do to upgrade rspamd?

kind regard
k04d01

**Comment by fatalbanana** [comment]
Have you updated to `jammy` but failed to update `/etc/apt/sources.list.d/rspamd.list` accordingly?

**Comment by k04d01** [comment]
Yeah thats was the crucial hint. After i have corrected the source list, it works.
Thanks,

**Comment by k04d01** [comment]
Yeah thats was the crucial hint. After i have corrected the source list, it works.
Thanks,
