### ISSUE TITLE
ICAP Issues after 3.7.1 upgrade - ESET[BUG]

### ISSUE THREAD

**Issue by padrogass** [rspamd/rspamd#4643]
Hi!

ICAP sanning (ESET Server Security for Linux (version: 10.0.328.0)) is not working after RSPAMD 3.7.1 upgrade. 

My external_services.conf file is the same as it was working on previous versions or rspamd:

eset {
  servers = "127.0.0.1:1344";
  user_agent = "RSPM_Agent";
  # symbol to add (add it to metric if you want non-zero weight)
  symbol = "ESET_VIRUS";

  # type of scanner: "icap", "oletools", "dcc" or "vadesecure"
  type = "icap";
  scheme = "scan";
  # Scan mime_parts seperately - otherwise the complete mail will be transfered
  scan_mime_parts = true;
  scan_text_mime = true;
  scan_image_mime = true;

  # filter attachments by content-type, filename or filename extension
  # setting a filter will also enable scan_mime_parts = true;
  mime_parts_filter_regex {
    #FILE1 = "^invoice\.xls$"
    #DOC1 = "application\/msword";
  }
  mime_parts_filter_ext {
    #doc = "doc";
    #docx = "docx";
  }

  # If set force this action if any threat is found (default unset: no action is forced)
  #action = "reject";

  # If `max_size` is set, messages > n bytes in size are not scanned
  #max_size = 20000000;

  # If set true, log message is emitted for clean messages
  log_clean = true;

  # if `patterns` is specified threat name will be matched against provided regexes and the related
  # symbol will be yielded if a match is found. If no match is found, default symbol is yielded.
  patterns {
    # symbol_name = "pattern";
    JUST_EICAR = '^Eicar-Test-Signature$';
  }
  # same as above, but matching on the _FAIL symbol
  patterns_fail {
    # symbol_name = "pattern";
  }
  # In version 1.7.0+ patterns could be extended
  #patterns = {SANE_MAL = 'Sanesecurity\.Malware\.*', CLAM_UNOFFICIAL = 'UNOFFICIAL$'};

  # `whitelist` points to a map of IP addresses. Mail from these addresses is not scanned.
  whitelist = "/etc/rspamd/antivirus.wl";
}

RSPAMD shows this messages:

_2023-10-13 16:20:49 #79158(main) <b7x9e6>; lua; external_services.lua:193: registered external services rule: symbol ESET_VIRUS; type icap
2023-10-13 16:22:54 #79159(rspamd_proxy) <7ff231>; lua; icap.lua:574: eset (icap): ICAP ERROR: ICAP/1.0 400 Bad request
2023-10-13 16:22:54 #79159(rspamd_proxy) <7ff231>; lua; common.lua:113: eset (icap): result - FAILED with error: "ICAP/1.0 400 Bad request - score: 0"_

ESET shows this messages on log:

_13/10/2023, 16:22 ICAP Server Invalid request: Bad message eset-efs-icapd_

**Comment by bauerstefan** [comment]
+1. can confirm. Debian 11 with 3.7.1-1~af3e90f67~bullseye fails.
lua; common.lua:113: icap_eset (icap): result - FAILED with error: "ICAP/1.0 400 Bad request - score: 0".

No problem with 3.6-2~bbb8660e5~bullseye.

**Comment by grufocom** [comment]
same problem here, since 3.7.1 all icap scan's get an 400 bad request.

**Comment by grufocom** [comment]
As soon as the content type changes from "text/html" the ESET ICAP scanner will return that 400 bad request error.
The problem startet with the fix which included the filename in /lualib/lua_scanners/icap.lua line 245 - 251.
I changed the line 247 to:
`table.insert(http_headers, string.format('Content-Type: %s/%s\r\n', 'text/html'))`
and it is working again.

**Comment by vstakhov** [comment]
It's a different Lua version but I have a glue on this issue now.

**Comment by vstakhov** [comment]
Could you please test the patch above?

**Comment by padrogass** [comment]
> Could you please test the patch above?

it works!

**Comment by grufocom** [comment]
Works for me! Thank you for the patch.

**Comment by padrogass** [comment]
> > Could you please test the patch above?
> 
> it works!

seen 2 errors

23/10/2023, 15:03:13 | rspamd_proxy | 805035 | lua | 2f6ae3 | icap  (icap): failed to scan, maximum retransmits exceed - error: IO write  error while trying to write 0 bytes: Connection reset by peer

-- | -- | -- | -- | -- | --

23/10/2023, 15:03:13 | rspamd_proxy | 805035 | lua | 2f6ae3 | icap  (icap): failed to scan, maximum retransmits exceed - error: IO write  error while trying to write 0 bytes: Connection reset by peer

**Comment by padrogass** [comment]
and more:

ICAP Server Invalid request: Bad message eset-efs-icapd on ESET console

**Comment by grufocom** [comment]
This is my log:

2023-10-23 17:19:32 #852265(rspamd_proxy) <3a158c>; icap; icap.lua:358: icap (icap): icap_headers: {[preview] = 16384, [max-connections] = 1024, [icap] = ICAP/1.0 200 OK, [methods] = RESPMOD, [encapsulated] = null-body=0, [transfer-preview] = *, [istag] = "1a82cbe25ed2316b-1698064259"}
2023-10-23 17:19:32 #852265(rspamd_proxy) <3a158c>; icap; icap.lua:358: icap (icap): icap_headers: {[encapsulated] = res-hdr=0, res-body=97, [icap] = ICAP/1.0 200 OK, [istag] = "1a82cbe25ed2316b-1698064259"}
2023-10-23 17:19:32 #852265(rspamd_proxy) <3a158c>; icap; icap.lua:561: icap (icap): no ICAP virus header found - try HTTP headers
2023-10-23 17:19:32 #852265(rspamd_proxy) <3a158c>; icap; icap.lua:358: icap (icap): icap_headers: {[server] = Apache/2.4, [date] = Mon, 23 Oct 2023 15:19:32 GMT, [http] = HTTP/1.0 200 OK, [content-length] = 570}
2023-10-23 17:19:32 #852265(rspamd_proxy) <3a158c>; icap; common.lua:39: icap (icap): message or mime_part is clean
2023-10-23 17:19:32 #852265(rspamd_proxy) <3a158c>; icap; common.lua:304: icap (icap): saved cached result for rs_icap_0b99bd2dc1ec84d483812e545d0db6ba448f2c63d5e12fb4c9794cd13fb126ad13b159356bc3303838ebea0c564bf5db0fbaa4044264bf127ab67496be044fc4: OK - score 0 - ttl 7200

**Comment by padrogass** [comment]
> and more:
> 
> ICAP Server Invalid request: Bad message eset-efs-icapd on ESET console

still getting some icap errors:

icap (icap): ICAP ERROR: ICAP/1.0 400 Bad request

**Comment by droszler** [comment]
Hi Grufocom,

can you show us your configuration (external_services.conf)?
i'm getting icap errors:

Oct 26 11:47:49 mail rspamd[621792]: <a64a2b>; lua; icap.lua:583: icap (icap): ICAP ERROR: ICAP/1.0 400 Bad request
Oct 26 11:47:49 mail rspamd[621792]: <a64a2b>; lua; common.lua:113: icap (icap): result - FAILED with error: "ICAP/1.0 400 Bad request - score: 0"

and

Oct 26 11:47:57 mail rspamd[621792]: <189d45>; icap; icap.lua:215: icap (icap): icap_w_respond_cb Request Error: IO write error while trying to write 0 bytes: A kapcsolatot bontotta a távoli fél - retries left: 0

My config:
icap {
  scheme = "scan";
  servers = "81.93.xxx.yyy:1344";
  user_agent = "extended";
}

**Comment by walkfire** [comment]
Hi Grufocom,
I use your config but still have "icap (icap): ICAP ERROR: ICAP/1.0 400 Bad request".
Rspamd ver 3.7.3, Rocky 8 system, can  you help me diagnose problem ?

**Comment by grufocom** [comment]
Hi walkfire, is your ICAP service running and does it listen on port 1344?
try:
`netstat -apnt|grep LISTEN|grep 1344`
Commas in my config - I never thought about that, always worked for me with commas. :-)

**Comment by walkfire** [comment]
yes eset service started and poort active
`[root@mx1 rspamd]# netstat -apnt|grep LISTEN|grep 1344
tcp        0      0 0.0.0.0:1344            0.0.0.0:*               LISTEN      56362/startd
[root@mx1 rspamd]# telnet 127.0.0.1 1344
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
`

**Comment by grufocom** [comment]
Hi walkfire, I am sorry I can't help - my config from above works for me, I get the following message from eset-icap scanner:

2023-11-12 16:20:00 #824(rspamd_proxy) <74c9a0>; icap; icap.lua:358: icap (icap): icap_headers: {[server] = Apache/2.4, [date] = Sun, 12 Nov 2023 15:20:00 GMT, [http] = HTTP/1.0 200 OK, [content-length] = 591}
2023-11-12 16:20:00 #824(rspamd_proxy) <74c9a0>; icap; common.lua:39: icap (icap): message or mime_part is clean

I have installed version 10.1.176.0 from eset efs.

**Comment by walkfire** [comment]
Ok, last request, can you screenshot your eset config for remote scan - basic and threatsense.

**Comment by grufocom** [comment]
here are the screenshots:
![Screenshot_20231113_092421](https://github.com/rspamd/rspamd/assets/24227479/2915782b-7cd6-4a1b-acc1-cc55816e3049)
![Screenshot_20231113_092437](https://github.com/rspamd/rspamd/assets/24227479/22cd39ea-1bc7-4fd1-a594-ed7db0532116)

**Comment by walkfire** [comment]
Thx, my ICAP server seems to be working, only Rspamd is sending incorrect requests

[root@mx1 tmp]# /usr/bin/c-icap-client -i 127.0.0.1 -p 1344 -v -f /tmp/eicar.com -nopreview -o /tmp/eicar.com2.out
ICAP server:127.0.0.1, ip:127.0.0.1, port:1344


ICAP HEADERS:
	ICAP/1.0 200 OK
	ISTag: "xxxxxxxxxxxxxxxxxxxxx"
	Encapsulated: res-hdr=0, res-body=70
	X-Infection-Found: Type=0; Resolution=0; Threat=Eicar;
	X-Virus-ID: Test file
	X-Response-Info: Blocked

RESPMOD HEADERS:
	HTTP/1.1 403 Forbidden
	Content-Type: text/html
	Content-Length: 0

**Comment by padrogass** [comment]
I still getting some icap (icap): ICAP ERROR: ICAP/1.0 400 Bad request with version 3.7.3 the problem is still present.

**Comment by droszler** [comment]
mee too

**Comment by walkfire** [comment]
My working config, latest Eset server  security for RPM systems
icap {
servers = "127.0.0.1:1344";
type = "icap";
symbol = "ICAP_VIRUS";
scan_mime_parts = true;
scan_all_mime_parts = true;
scan_text_mime = false;
scan_image_mime = false;
scheme = "scan";
timeout = 10.0;
log_clean = false;
retransmits = 2;
cache_expire = 7200;
message = '${SCANNER}: threat found with icap scanner: "${VIRUS}"';
detection_category = "virus";
action = reject;
dynamic_scan = true;
user_agent = "none";
}

**Comment by droszler** [comment]
Hi,

i upgraded ESET to 10.1.176.0, and it's working now.

I use these configs

/etc/rspamd/local.d/external_services.conf:
icap {
    servers = "X.X.X.X:1344",
    type = "icap",
    symbol = "ICAP_VIRUS",
    scan_mime_parts = true,
    scan_all_mime_parts = true,
    scan_text_mime = false,
    scan_image_mime = false,
    scheme = "scan",
    default_port = 1344,
    timeout = 10.0,
    log_clean = true,
    retransmits = 2,
    cache_expire = 7200,
    message = '${SCANNER}: threat found with icap scanner: "${VIRUS}"',
    detection_category = "virus",
    default_score = 1,
    action = reject,
    dynamic_scan = true,
    user_agent = "none",
}

/etc/rspamd/local.d/external_services_group.conf:
symbols = {
    "ICAP_VIRUS" {
        weight = 10.0;
        description = "ICAP";
    }
}

**Comment by asdcq** [comment]
rspamd 3.7.4
ESET 10.1.176.0
icap (icap): ICAP ERROR: ICAP/1.0 400 Bad request
The problem is still not resolved

**Comment by bauerstefan** [comment]
I can confirm that ICAP works with different vendors (eset, avast) with 3.7.3 without problems.

**Comment by asdcq** [comment]
Still not working.
icap (icap): ICAP ERROR: ICAP/1.0 400 Bad request
Eset Server Security 10.2.41.0
Rspamd 3.8

external_services.conf
icap {
        servers = "127.0.0.1:1344";
        type = "icap";
        symbol = "ICAP_VIRUS";
        scan_mime_parts = true;
        scan_all_mime_parts = true;
        scan_text_mime = false;
        scan_image_mime = false;
        scheme = "scan";
        default_port = 1344;
        timeout = 10.0;
        log_clean = true;
        retransmits = 2;
        cache_expire = 7200;
        message = '${SCANNER}: threat found with icap scanner: "${VIRUS}"';
        detection_category = "virus";
        default_score = 1;
        action = reject;
        dynamic_scan = true;
        user_agent = "none";
}

**Comment by padrogass** [comment]
same here

> Still not working. icap (icap): ICAP ERROR: ICAP/1.0 400 Bad request Eset Server Security 10.2.41.0 Rspamd 3.8
> 
> external_services.conf icap { servers = "127.0.0.1:1344"; type = "icap"; symbol = "ICAP_VIRUS"; scan_mime_parts = true; scan_all_mime_parts = true; scan_text_mime = false; scan_image_mime = false; scheme = "scan"; default_port = 1344; timeout = 10.0; log_clean = true; retransmits = 2; cache_expire = 7200; message = '${SCANNER}: threat found with icap scanner: "${VIRUS}"'; detection_category = "virus"; default_score = 1; action = reject; dynamic_scan = true; user_agent = "none"; }

**Comment by mpgkb** [comment]
Hi.
Can you fix this bug?

**Comment by vstakhov** [comment]
Yes, I **can** fix the bug. But you probably intended to ask if I **will** fix it. So far, I have more urgent things to do but the patches are wellcome.

**Comment by oliyks** [comment]
Issue might be in spaces and other symbols read from the filename.

Fix would be to url encode the filename before sending to ICAP server.

to reproduce the issue:

```
$ c-icap-client -i 127.0.0.1 -p 11344 -v -f eicar -nopreview -s scan  -resp "http://127.0.0.1/eicar .txt"

ICAP HEADERS:
	ICAP/1.0 400 Bad request
```


Encoded query works:

```
$ c-icap-client -i 127.0.0.1 -p 11344 -v -f eicar -nopreview -s scan  -resp "http://127.0.0.1/eicar%20.txt"

ICAP HEADERS:
	ICAP/1.0 200 OK
```


Patch:

```
diff --git a/lualib/lua_scanners/icap.lua b/lualib/lua_scanners/icap.lua
index 682562d85..2e3ced034 100644
--- a/lualib/lua_scanners/icap.lua
+++ b/lualib/lua_scanners/icap.lua
@@ -245,7 +245,7 @@ local function icap_check(task, content, digest, rule, maybe_part)
         local req_hlen = 2
         if maybe_part then
           table.insert(req_headers,
-              string.format('GET http://%s/%s HTTP/1.0\r\n', in_client_ip, maybe_part:get_filename()))
+              string.format('GET http://%s/%s HTTP/1.0\r\n', in_client_ip, lua_util.url_encode_string(maybe_part:get_filename())))
           if rule.use_specific_content_type then
             table.insert(http_headers, string.format('Content-Type: %s/%s\r\n', maybe_part:get_detected_type()))
             --else
diff --git a/lualib/lua_util.lua b/lualib/lua_util.lua
index a64f8abc9..8f44e25f2 100644
--- a/lualib/lua_util.lua
+++ b/lualib/lua_util.lua
@@ -1687,6 +1687,24 @@ local function join_path(...)
 end
 exports.join_path = join_path
 
+---[[[
+-- @function lua_util.url_encode_string(str)
+-- URL encodes a string
+--
+-- @param {string} str string to encode
+-- @return {string} URL encoded string
+--
+---]]]
+local function url_encode_string(str)
+  str = string.gsub(str, "([^%w _%%%-%.~])",
+      function(c)
+        return string.format("%%%02X", string.byte(c))
+      end)
+  str = string.gsub(str, " ", "+")
+  return str
+end
+exports.url_encode_string = url_encode_string
+
 -- Short unit test for sanity
 if path_sep == '/' then
   assert(join_path('/path', 'to', 'file') == '/path/to/file')

```
