### ISSUE TITLE
[BUG] Cant use Wildcards in external_relay with strategy hostname_map

### ISSUE THREAD

**Issue by evan-hirschi** [rspamd/rspamd#4651]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Unsure if actually a bug or should be a feature request.

When creating a new rule in `/etc/rspamd/local.d/external_relay.conf` with the `strategy = "hostname_map"`. The hostname_map doesn't seem to work with Wildcards (eg. `hostname_map = ["*.host.name.com"];`). When sending a mail using a server that aligns with the wildcard (eg. `my.host.name.com`) the symbol isnt set.

### Steps to Reproduce

1. Create external_relay Rule with Wildcard in hostname_map in the File `/etc/rspamd/local.d/external_relay.conf`. Eg.:
```
enabled = true;
rules {
  EXTERNAL_RELAY_AUTHENTICATED {
    strategy = "hostname_map";
    # None of the 3 following Options work
    hostname_map = ["*.host.name.com",".host.name.com","host.name.com"];
  }
}
```
3. Send Mail using a Server that aligns with the Wildcard (eg. `my.host.name.com`)
4. Check if the Symbol (eg. `EXTERNAL_RELAY_AUTHENTICATED`) is set on the mail

**Expected behavior**
The Symbol (eg. `EXTERNAL_RELAY_AUTHENTICATED`) is set

### Versions

Rspamd daemon version 3.6
CentOS Linux 7

### Additional Information

We are trying to add `*.protection.outlook.com` and `*.prod.outlook.com` to our external_relay. Since not all of the necessary IP-Adresses of these hosts are shared by Microsoft (https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#exchange-online) we are unable to use the `strategy = "ip_map"`.

**Comment by fatalbanana** [comment]
The way to do it is to use regex maps:

~~~
# external_relay.conf
    hostname_map = "regex;/path/to/map";
~~~

~~~
# /path/to/map
/\.protection\.outlook\.com$/i
~~~

**Comment by evan-hirschi** [comment]
Thank you for the quick answer.
Using `regexp` worked.
