### ISSUE TITLE
[Feature] Support Redis sharding (hash slots) exclusively for per_user bayes

### ISSUE THREAD

**Issue by dragoangel** [rspamd/rspamd#4663]
## Summary

Support Redis sharding (hash slots) exclusively for per_user bayes (statistics)

## Motivation

Get a better level of statistics quality per_user by having the option to store it in shared Redis setups.

## Describe alternatives you've considered

While statistics `per_user = false;` is okay with a couple of GBs in Redis, for `per_user = true;` setup would require much more data to be stored in Redis. It's so because of 2 factors: 
- key name size includes full email address, which can be quite big 
- general nature, as we need to store statistics per user

From a logical perspective sharding in Redis for `per_user bayes` should fit flawlessly if all keys for one user will use the same `hash tag` and will be placed in the _same_ Redis shard.

## Additional context

I'm aware of https://github.com/rspamd/rspamd/issues/1883, but my request a bit more exact, it asks only sharding for place where it can fit without issues, at least from my view.

**Comment by dragoangel** [comment]
I also checked how [hash algorithm](https://rspamd.com/doc/configuration/upstream.html#hash-algorithm) works in the scope of Redis for Bayes (both peruser and common), from my tests, unfortunately, it doesn't work as expected. When it is used with the same eml body we can get learned in 2 different Bayes servers as ham\spam with different scores or return no learns, and RS key shows unsynced learns in different Redis masters.

**Comment by vstakhov** [comment]
I think the hash key is not properly specified, from what I see in the code. I have a plan to rework bayes redis backend soon where I plan to address this issue as well.

**Comment by dragoangel** [comment]
Also one point that if we have common read_servers and write_servers section which would have different set of servers (masters and multiple replicas per master) with basic hash based on count of servers in read/write they would be not aligned between each other

**Comment by dragoangel** [comment]
actually hash works good, at least with 1 replicas, thank you.

Will create PR to docs about it

**Comment by dragoangel** [comment]
https://github.com/rspamd/rspamd.com/pull/749
