### ISSUE TITLE
[BUG] After upgrading to 3.7.2 doesn't see hsmp files

### ISSUE THREAD

**Issue by swamp-fish** [rspamd/rspamd#4665]
**Describe the bug**
After upgrade to 3.7.2 i get false error messages about hsmp existence.

### Steps to Reproduce

1. Open Rspamd in the browser
2. Go to History tab
3. Observe many similar errors:
Worker type	PID	Module	Internal ID	Message

main	675030	hypersca	hsxxxx	invalid path: \"/var/lib/rspamd//f2c5df70f8667d7f08a23bc82ec6b26f7c687a4823d8d52ba16859c28f0602d4.hsmp\", error message: Success

rspamd_proxy	675032	hypersca	hsxxxx	invalid path: \"/var/lib/rspamd//f2c5df70f8667d7f08a23bc82ec6b26f7c687a4823d8d52ba16859c28f0602d4.hsmp\", error message: Success

Files themselves exist
-rw-r--r-- 1 _rspamd _rspamd 28K Oct 26 23:27 /var/lib/rspamd//f2c5df70f8667d7f08a23bc82ec6b26f7c687a4823d8d52ba16859c28f0602d4.hsmp

**Expected behavior**
I expect no such errors, in 3.7.1 thery didn't exist

### Versions

rspamd --version
Rspamd daemon version 3.7.2

CPU architecture x86_64; features: avx2, avx, sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
Hyperscan enabled: TRUE
Jemalloc enabled: TRUE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.1695653777)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE

Ubuntu 22.04.3 LTS

CPU: 8-core AMD Ryzen 7 5800X (-MT MCP-)

**Comment by vstakhov** [comment]
I think it's caused by https://github.com/rspamd/rspamd/commit/48fffd3548320827d8d65dcc258afd24ddc5aefe but I don't know yet why.

**Comment by vstakhov** [comment]
Do you set any custom DBDIR?

**Comment by DiveSurfer** [comment]
Hello,
I have the same behavior, I do not have a custom DBDIR, only the default ones from the system.

`etc/rspamd# grep -r DBDIR *
modules.d/forged_recipients.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/forged_recipients.conf"
modules.d/history_redis.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/history_redis.conf"
modules.d/regexp.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/regexp.conf"
modules.d/replies.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/replies.conf"
modules.d/maillist.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/maillist.conf"
modules.d/arc.conf:# path = "${DBDIR}/arc/$domain.$selector.key";
modules.d/arc.conf:  #path = "${DBDIR}/arc/$domain.$selector.key";
modules.d/arc.conf:  #    path = "${DBDIR}/arc/example.key";
modules.d/arc.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/arc.conf"
modules.d/mx_check.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/mx_check.conf"
modules.d/reputation.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/reputation.conf"
modules.d/spamassassin.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/spamassassin.conf"
modules.d/greylist.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/greylist.conf"
modules.d/neural.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/fann_redis.conf"
modules.d/neural.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/neural.conf"
modules.d/once_received.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/once_received.conf"
modules.d/hfilter.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/hfilter.conf"
modules.d/metadata_exporter.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/metadata_exporter.conf"
modules.d/spamtrap.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/spamtrap.conf"
modules.d/ratelimit.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/ratelimit.conf"
modules.d/trie.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/trie.conf"
modules.d/force_actions.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/force_actions.conf"
modules.d/antivirus.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/antivirus.conf"
modules.d/bimi.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/bimi.conf"
modules.d/mime_types.conf:    "${DBDIR}/mime_types.inc.local",
modules.d/mime_types.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/mime_types.conf"
modules.d/elastic.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/elastic.conf"
modules.d/milter_headers.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/rmilter_headers.conf"
modules.d/milter_headers.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/milter_headers.conf"
modules.d/multimap.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/multimap.conf"
modules.d/external_services.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/external_services.conf"
modules.d/fuzzy_check.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/fuzzy_check.conf"
modules.d/spf.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/spf.conf"
modules.d/mid.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/mid.conf"
modules.d/phishing.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/phishing.conf"
modules.d/known_senders.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/known_senders.conf"
modules.d/redis.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/redis.conf"
modules.d/chartable.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/chartable.conf"
modules.d/dkim_signing.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/dkim_signing.conf"
modules.d/clickhouse.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/clickhouse.conf"
modules.d/aws_s3.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/aws_s3.conf"
modules.d/external_relay.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/external_relay.conf"
modules.d/p0f.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/p0f.conf"
modules.d/emails.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/emails.conf"
modules.d/surbl.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/surbl.conf"
modules.d/rbl.conf:    "${DBDIR}/surbl-whitelist.inc.local",
modules.d/rbl.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/rbl.conf"
modules.d/dkim.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/dkim.conf"
modules.d/metric_exporter.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/metric_exporter.conf"
modules.d/dmarc.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/dmarc.conf"
modules.d/rspamd_update.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/rspamd_update.conf"
modules.d/asn.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/asn.conf"
modules.d/whitelist.conf:        "${DBDIR}/spf_whitelist.inc.local",
modules.d/whitelist.conf:        "${DBDIR}/dkim_whitelist.inc.local",
modules.d/whitelist.conf:        "${DBDIR}/spf_dkim_whitelist.inc.local",
modules.d/whitelist.conf:        "${DBDIR}/dmarc_whitelist.inc.local",
modules.d/whitelist.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/whitelist.conf"
modules.d/dcc.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/dcc.conf"
modules.d/http_headers.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/http_headers.conf"
modules.d/url_redirector.conf:  .include(try=true,priority=5) "${DBDIR}/dynamic/url_redirector.conf"
options.inc:cache_file = "$DBDIR/symbols.cache";
options.inc:dynamic_conf = "$DBDIR/rspamd_dynamic";
options.inc:history_file = "$DBDIR/rspamd.history";
options.inc:control_socket = "$DBDIR/rspamd.sock mode=0600";
options.inc:rrd = "${DBDIR}/rspamd.rrd";
options.inc:stats_file = "${DBDIR}/stats.ucl";
options.inc:hs_cache_dir = "${DBDIR}/";
worker-fuzzy.inc:#hash_file = "${DBDIR}/fuzzy.db";`

**Comment by DiveSurfer** [comment]
Thanks for the fix, sorry for the possibly stupid question, but will there be a new package for Ubuntu, or how can I apply the fix?

**Comment by vstakhov** [comment]
We'll check if that's a fix and I will make a new release.

**Comment by DiveSurfer** [comment]
Great, thanks a lot, also for the quick fix

**Comment by swamp-fish** [comment]
> Do you set any custom DBDIR?

No, only default one. But it seems you've already fixed it, thank you! I will wait for the new release.

**Comment by DiveSurfer** [comment]
solved, thank you

**Comment by swamp-fish** [comment]
Same, solved for me as well, thank you!

**Comment by vstakhov** [comment]
Let's close this one then.
