### ISSUE TITLE
[BUG] Depends: libbinutils (< 2.34.1) but 2.38-4ubuntu2.3 is to be installed

### ISSUE THREAD

**Issue by MachineITSvcs** [rspamd/rspamd#4671]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
I am unable to upgrade rspamd because of the unmet dependencies error: "rspamd : Depends: libbinutils (< 2.34.1) but 2.38-4ubuntu2.3 is to be installed" even though I currently have rspamd, version `3.6-2~bbb8660e5~focal`, installed with libbinutils version `2.38-4ubuntu2.3` without issue (which is a greater version than the dependency for the new version of rspamd).

### Steps to Reproduce

1. Use rspamd, version `3.6-2~bbb8660e5~focal`, on an Ubuntu/Debian OS with libbinutils version `2.38-4ubuntu2.3`
2. Try to upgrade rspamd using apt

**Expected behavior**
I'm not sure why the currently installed version of libbinutils would suddenly conflict with a newer version of rspamd, unless it wasn't used previously (or currently in my case) by rspamd, so the new rspamd version requires a downgrade. However, I'm unsure how that would affect other packages/software on my server.

### Versions

Rspamd: 3.6 (`3.6-2~bbb8660e5~focal`)
OS: Ubuntu 22.04.3 LTS
libbinutils: 2.38 (`2.38-4ubuntu2.3`)

**Comment by fatalbanana** [comment]
`/etc/apt/sources.list.d/rspamd.list` needs to be updated according to whichever release of the OS you're running, or upgrading to. (`focal` -> `jammy`)

**Comment by MachineITSvcs** [comment]
That was it! Thank you!
