### ISSUE TITLE
[BUG] Fuzzy Worker using not obvious disabling logic

### ISSUE THREAD

**Issue by dragoangel** [rspamd/rspamd#4677]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
All modules can be enabled and disabled by using `enabled` parameters, but fuzzy worker ignores it and works only when user set `count` parameter to positive values, aka `1`, without it fuzzy worker will disable itself even when `enable=true;`

### Steps to Reproduce
1. configure `worker-fuzzy.inc` as usual (with `enabled = true;`, all required settings like redis and etc filled) without `count = 1;`
2. check logs: worker will be disabled
3. controller worker will throw error on learn fuzzy as fuzzy not listen on desired port.

**Expected behavior**
All workers-*.inc honors `enabled=true;` or `enabled=false;` logic and not depends on another switches.

### Versions
Rspamd 3.5

### Additional Information
N/A

**Comment by vstakhov** [comment]
I'm not sure that `enabled` is honored by workers at all. It's probably something that needs to be improved indeed.

**Comment by dragoangel** [comment]
> I'm not sure that `enabled` is honored by workers at all. It's probably something that needs to be improved indeed.

It is honored, but not in all places as expected. Thank you :)

**Comment by vstakhov** [comment]
Workers are not modules...

**Comment by dragoangel** [comment]
> Workers are not modules...

I know, but docs states opposite: https://rspamd.com/doc/workers/#:~:text=enabled%20(1.6.2%2B)%20%2D%20a%20Boolean%20(true%20or%20false)%2C%20enabling%20or%20disabling%20a%20worker%20(true%20by%20default) and fuzzy document not mention `count` as mandatory to work: https://rspamd.com/doc/workers/fuzzy_storage.html#configuration

**Comment by vstakhov** [comment]
I guess, it is just a configuration confusion and I really don't know how to fix it without breaking compatibility. By default, it's count is set to `0`, so to enable the worker users just set `count` to some other value. If we switch to `enabled` behaviour, it will apparently break the existing configuration. I don't like breaking changes with no **very strong** reasons.

**Comment by dragoangel** [comment]
> I guess, it is just a configuration confusion and I really don't know how to fix it without breaking compatibility. By default, it's count is set to `0`, so to enable the worker users just set `count` to some other value. If we switch to `enabled` behaviour, it will apparently break the existing configuration. I don't like breaking changes with no **very strong** reasons.

You right, we would need put put `enabled=false` by default and users who not have `enabled=true` will get not working service. From my view I think this breaking change is acceptable to have same working behavior between workers logic, will require setting release to 3.8. But if rspamd.com docs will be fixed it is also acceptable as a solution :)
