### ISSUE TITLE
[BUG] groups_enabled makes force actions non functional

### ISSUE THREAD

**Issue by akinzler** [rspamd/rspamd#4684]
rspamd 3.6, on outgoing mails I use groups_enabled to limit checks. Checks are done correctly and appear correctly in rspamd web UI history. But force actions are no longer executed. On incoming, with no match in settings.conf force actions are executed. Config error? Bug?

force_actions.conf
```
rules {
  REJECT_MIME_BAD { 
    action = "reject";
    expression = "MIME_BAD_EXTENSION";
    message = "Your mail was rejected because it contains BANNED ATTACHMENTS"
  }
}
```
settings.conf
```
OUTGOING {
  request_header = {
    "MTA-Name" = "^outgoing$";
  }
  apply {
    groups_enabled = ["antivirus", "mime_types"];
  }
}
```

**Comment by fatalbanana** [comment]
It's somewhat expected; you'd need to add `symbols_enabled = ["FORCE_ACTION_REJECT_MIME_BAD"]` to settings.

**Comment by akinzler** [comment]
> It's somewhat expected; you'd need to add `symbols_enabled = ["FORCE_ACTION_REJECT_MIME_BAD"]` to settings.

That works. Thanks.
