### ISSUE TITLE
[BUG] task_get_headers(true) not returning ARC headers 

### ISSUE THREAD

**Issue by JasonStephenson** [rspamd/rspamd#4690]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
task:get_headers(true) not returning headers created by arc signing module if no ARC headers existed previously

### Steps to Reproduce

1. Rspamd configured to run via Postfix + milter
2. arc module configured to do signing
3. aws_s3 module configured to do writing
4. Receive an email which contains no ARC headers (ARC-Message-Signature, ARC-Authentication-Results, ARC-Seal)
5. Observe arc module correctly signing 
6. Observe `task:get_headers(true)` not returning the ARC headers
7. Observe `task:get_header_full` can return the ARC headers
8. Receive an email which **does** already contain ARC headers (ex:google)
9. Observe `task:get_headers` correctly returning ARC headers

**Expected behavior**

- `task:get_headers(true)` should return ARC headers created by arc module regardless of whether existing ARC headers are present
- raw attribute should consistantly start with the MIME header (see addtional notes)
- raw attribute should consistantly end with \r\n (see additional notes)

### Versions

- 3.2

### Additional notes
Also seeing differences between ARC headers created by rspamd and ARC headers already present in the email.

Already present:
```
    {
      "empty_separator": false,
      "order": 7,
      "separator": " ",
      "value": "i=1; a=rsa-sha256; t=1699365028; cv=none; d=google.com; s=arc-20160816; b=p2qTqClED7b4HJGECUr0DY64qb66In3dRXRtKp+wa7uTrtEqtUYtn+znAPil4fbR6k n0g9Yte3LdgIb7i8aV33f4GiE70yAd+uMl2g/qg5R9I1LKcxV81ZgBBl1SyGL60dY1fG XooI4E7+pG31kDtO3VX8RE8YmHIsITHBXf5EyHbBnOipx+X4laF0TyHhWH68S/86WpRp x84aRVzeCwPaJY/aYYz3DMxTDlualEz6P7F3zxvsPqCHSfh24IGU65UfJoVeLR82KKCe 4ZEcqGHObn6cr3sQPeTdAFuJrssvmFnov8AtMKAx4qHwuLTs10PxvilejYIvgllLFMs1 uhWw==",
      "tab_separated": false,
      "decoded": "i=1; a=rsa-sha256; t=1699365028; cv=none; d=google.com; s=arc-20160816; b=p2qTqClED7b4HJGECUr0DY64qb66In3dRXRtKp+wa7uTrtEqtUYtn+znAPil4fbR6k n0g9Yte3LdgIb7i8aV33f4GiE70yAd+uMl2g/qg5R9I1LKcxV81ZgBBl1SyGL60dY1fG XooI4E7+pG31kDtO3VX8RE8YmHIsITHBXf5EyHbBnOipx+X4laF0TyHhWH68S/86WpRp x84aRVzeCwPaJY/aYYz3DMxTDlualEz6P7F3zxvsPqCHSfh24IGU65UfJoVeLR82KKCe 4ZEcqGHObn6cr3sQPeTdAFuJrssvmFnov8AtMKAx4qHwuLTs10PxvilejYIvgllLFMs1 uhWw==",
      "name": "ARC-Seal",
      "raw": "ARC-Seal: i=1; a=rsa-sha256; t=1699365028; cv=none;\n        d=google.com; s=arc-20160816;\n        b=p2qTqClED7b4HJGECUr0DY64qb66In3dRXRtKp+wa7uTrtEqtUYtn+znAPil4fbR6k\n         n0g9Yte3LdgIb7i8aV33f4GiE70yAd+uMl2g/qg5R9I1LKcxV81ZgBBl1SyGL60dY1fG\n         XooI4E7+pG31kDtO3VX8RE8YmHIsITHBXf5EyHbBnOipx+X4laF0TyHhWH68S/86WpRp\n         x84aRVzeCwPaJY/aYYz3DMxTDlualEz6P7F3zxvsPqCHSfh24IGU65UfJoVeLR82KKCe\n         4ZEcqGHObn6cr3sQPeTdAFuJrssvmFnov8AtMKAx4qHwuLTs10PxvilejYIvgllLFMs1\n         uhWw==\r\n"
    },
```
Arc module created (Note missing header and \r\n in Raw):
```
    {
      "empty_separator": false,
      "order": 2,
      "value": "i=2; s=arc; d=redacted.com; t=1699365030; a=rsa-sha256;\n\tcv=pass;\n\tb=IVzKYgbJFSUgiksjXc39xlgEUX4Nw9fnMmTz4u/EzSF9/yZ1WZAnbmjidqBdTNJCC9E01L\n\tD6sEVyowniczzVQy/onq/WGPDWe//fwgQ3JyLY2JDMU4L3tQsctrBibJoP53VlgaRv0ni+\n\tiL7yR406Cn/soEns85agkVlxauKQpTGDqQJa+fHBnUJlFTxKSPUfJxo7x7zD+5+EPAGIOP\n\toj0WPZFtlMKdXbnPilfCyGqpR3RTKZbVhPOp4wqnSaE2BCqRLAZpy0/Zvj27z2HOlQ1VUu\n\t62UNPXD7IUJ+HcBjDZ7KMhJmUg22e+rrSvMbFT2sB1POEPkX4eXCv0rFpbS0iw==",
      "tab_separated": false,
      "decoded": "i=2; s=arc; d=redacted.com; t=1699365030; a=rsa-sha256;  cv=pass;  b=IVzKYgbJFSUgiksjXc39xlgEUX4Nw9fnMmTz4u/EzSF9/yZ1WZAnbmjidqBdTNJCC9E01L  D6sEVyowniczzVQy/onq/WGPDWe//fwgQ3JyLY2JDMU4L3tQsctrBibJoP53VlgaRv0ni+  iL7yR406Cn/soEns85agkVlxauKQpTGDqQJa+fHBnUJlFTxKSPUfJxo7x7zD+5+EPAGIOP  oj0WPZFtlMKdXbnPilfCyGqpR3RTKZbVhPOp4wqnSaE2BCqRLAZpy0/Zvj27z2HOlQ1VUu  62UNPXD7IUJ+HcBjDZ7KMhJmUg22e+rrSvMbFT2sB1POEPkX4eXCv0rFpbS0iw==",
      "name": "ARC-Seal",
      "raw": "i=2; s=arc; d=redacted.com; t=1699365030; a=rsa-sha256;\n\tcv=pass;\n\tb=IVzKYgbJFSUgiksjXc39xlgEUX4Nw9fnMmTz4u/EzSF9/yZ1WZAnbmjidqBdTNJCC9E01L\n\tD6sEVyowniczzVQy/onq/WGPDWe//fwgQ3JyLY2JDMU4L3tQsctrBibJoP53VlgaRv0ni+\n\tiL7yR406Cn/soEns85agkVlxauKQpTGDqQJa+fHBnUJlFTxKSPUfJxo7x7zD+5+EPAGIOP\n\toj0WPZFtlMKdXbnPilfCyGqpR3RTKZbVhPOp4wqnSaE2BCqRLAZpy0/Zvj27z2HOlQ1VUu\n\t62UNPXD7IUJ+HcBjDZ7KMhJmUg22e+rrSvMbFT2sB1POEPkX4eXCv0rFpbS0iw=="
    },
```

**Comment by vstakhov** [comment]
So the question is that the headers are not returned or that the headers are not correct?

**Comment by JasonStephenson** [comment]
Both.

1. headers created by rspamd arc module are not returned in `task:get_headers(true)` unless already present in the email
2. When they are returned using a work around (task:get_header_full) they are incorrect

**Comment by vstakhov** [comment]
The first thing is likely not possible to fix at all, as it returns the **original** headers of the message with no modifications (as Rspamd apparently does not do any modifications - it's the task for MTA). The second thing can probably be fixed.

**Comment by vstakhov** [comment]
Or wait, in fact I'm wrong, so modified headers should be there. Let me check... Are you sure that you call this function **after** ARC module has done it's signing job (e.g. by adding a dependency)?

**Comment by JasonStephenson** [comment]
I believe it is yes. Because although `task:get_headers(true)` does not return the ARC one's. `task:get_header_full` does

**Comment by vstakhov** [comment]
The resolution of this issue is a bit more complicated than I have imagined. I have created a tracking PR for the problems I have discovered.
