### ISSUE TITLE
[BUG] hyperscan/vectorscan is now required

### ISSUE THREAD

**Issue by a16bitsysop** [rspamd/rspamd#4701]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

after https://github.com/rspamd/rspamd/commit/145b2616883636d2e0b6e524c8d5ef4b0b5a6e65 hyperscan /vectorscan is now required or you getting missing symbol errors:
```
/usr/lib/gcc/i586-alpine-linux-musl/13.2.1/../../../../i586-alpine-linux-musl/bin/ld: src/librspamd-server.so: undefined reference to `rspamd_hyperscan_notice_loaded'
collect2: error: ld returned 1 exit status
```

### Steps to Reproduce

1. [First Step] compile without hyperscan/vectorscan
2. [Second Step]
3. [and so on...]

**Expected behavior**

hyperscan/vectorscan is optional still?

### Versions

You can get this information from copy and pasting the output of `rspamd --version` from the command line. Also, please include the **OS** and what version and architecture including the generation of CPU model (e.g. Haswell) where applicable,  of the OS you're running.

3.7.4
alpine linux edge

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by breisig** [comment]
I am getting the EXACT same error when compiling it from source.

**Comment by a16bitsysop** [comment]
https://github.com/rspamd/rspamd/commit/d907a95ac2e2cad6f7f65c4323f031f7931ae18b fixes it for me as well

**Comment by breisig** [comment]
Yup, It seems to compile now properly :-)
