### ISSUE TITLE
[BUG] Build of 3.7.4 fails on FreeBSD

### ISSUE THREAD

**Issue by yasuhirokimura** [rspamd/rspamd#4702]
I'm trying to update FreeBSD Rspamd port to 3.7.4.

https://github.com/yasuhirokimura/freebsd-ports/tree/rspamd/mail/rspamd

But build fails with following error.

```
ld.lld: error: src/librspamd-server.so: undefined reference to rspamd_hyperscan_notice_loaded [--no-allow-shlib-undefined]
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Full build log:
https://people.freebsd.org/~yasu/poudriere/data/logs/bulk/132amd64-default-rspamd/2023-11-15_04h12m23s/logs/rspamd-3.7.4.log

**Comment by sthen** [comment]
Builds OK with hyperscan enabled, but not otherwise. This is basically a dup of #4701

**Comment by vstakhov** [comment]
In fact, you should not use Rspamd without hyperscan. I'll probably fix that issue but in future I plan to make Hyperscan dependency mandatory.

**Comment by vstakhov** [comment]
> I'm trying to update FreeBSD Rspamd port to 3.7.4.

Let's probably hold on till 3.7.5

**Comment by yasuhirokimura** [comment]
> In fact, you should not use Rspamd without hyperscan. I'll probably fix that issue but in future I plan to make Hyperscan dependency mandatory.

IIUC hyperscan works only with x86_64/amd64. Do you mean you will make Rspamd work only with the architecture too?

**Comment by yasuhirokimura** [comment]
> Let's probably hold on till 3.7.5

By applying d907a95ac build scceeds without hyperscan.
Thanks for quick fix!

**Comment by arkamar** [comment]
@vstakhov do you plan to release 3.7.5 soon or should I backport the commit to Gentoo. There is a related bug reported in Gentoo bugzilla, see https://bugs.gentoo.org/917512.

**Comment by vstakhov** [comment]
The only thing that blocks me from 3.7.5 is #4703 I cannot reproduce this issue anywhere but it seems to be quite bad for many people.

**Comment by arkamar** [comment]
Ok, I'll wait a bit more, thanks for fast response!

**Comment by timtas** [comment]
> In fact, you should not use Rspamd without hyperscan. I'll probably fix that issue but in future I plan to make Hyperscan dependency mandatory.

Why not? Is it really that much faster, e.g. is rspamd unusable without it?
