### ISSUE TITLE
[BUG] Failing to parse mime part

### ISSUE THREAD

**Issue by japc** [rspamd/rspamd#4740]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

Having some messages where the last html part is not being scanned.

The scan skip must be know, and is being used with bad intentions, as we're seeing this a lot on recent messages.

The mime structure of the message is as follows:

HEADER:

```
Content-Type: multipart/related;
  boundary="----=_Part_4984651_8952671.96357522";

```
BODY:

```
------=_Part_4984651_8952671.96357522
Content-Type: multipart/alternative;
  boundary="----=_Part_4984652_8952672.96357522"

------=_Part_4984652_8952672.96357522
Content-Type: text/plain; charset=UTF-8



------=_Part_4984652_8952672.96357522
Content-Type: image/png; name="image001.png"
Content-Description: image001.png
Content-ID: <image001.png@01D89B8C.8D026220>
Content-Transfer-Encoding: base64

<base64>

------=_Part_4984652_8952672.96357522
Content-Type: multipart/related;
  boundary="----=_Part_4984653_8952673.96357522"

------=_Part_4984653_8952673.96357522
Content-Type: text/html; charset=utf-8

<html>

------=_Part_4984652_8952672.96357522--

------=_Part_4984653_8952673.96357522--

```
I'm guessing that because the Part_4984653_8952673.96357522 part ends after the Part_4984652_8952672.96357522 boundary this last text/html is never considered. 

With properly enclosed boundaries:

`2023-12-12 11:00:39 #175231(normal) <575b3f>; task; rspamd_message_parse: found 6 parts in message
`

With the example shown above:

`2023-12-12 11:12:50 #175231(normal) <b96a6c>; task; rspamd_message_parse: found 5 parts in message
`

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**

### Versions

```
$ rspamd --version
Rspamd daemon version 3.7.4

CPU architecture x86_64; features: avx2, avx, sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
Hyperscan enabled: TRUE
Jemalloc enabled: TRUE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.1699524327)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE


```
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by miss-ann-thrope** [comment]
Btw, this helps:

```
diff --git a/src/libmime/mime_parser.c b/src/libmime/mime_parser.c
index 562a9d7de..4bc2106f6 100644
--- a/src/libmime/mime_parser.c
+++ b/src/libmime/mime_parser.c
@@ -1099,6 +1099,7 @@ rspamd_multipart_boundaries_filter(struct rspamd_task *task,
                cur = &g_array_index(st->boundaries, struct rspamd_mime_boundary, i);

                if (cur->boundary > last_offset) {
+                       task->flags |= RSPAMD_TASK_FLAG_BROKEN_HEADERS;
                        break;
                }

```

It doesn't fix the parsing (and I'm unsure if that's the way to go)  but it signals the caller that something is broken, with minimal fuss.

**Comment by japc** [comment]
Btw, this helps:

```
diff --git a/src/libmime/mime_parser.c b/src/libmime/mime_parser.c
index 562a9d7de..4bc2106f6 100644
--- a/src/libmime/mime_parser.c
+++ b/src/libmime/mime_parser.c
@@ -1099,6 +1099,7 @@ rspamd_multipart_boundaries_filter(struct rspamd_task *task,
                cur = &g_array_index(st->boundaries, struct rspamd_mime_boundary, i);

                if (cur->boundary > last_offset) {
+                       task->flags |= RSPAMD_TASK_FLAG_BROKEN_HEADERS;
                        break;
                }

```

It does not fix the parsing (not sure if that's the way to go, probably not) but it signals the caller that something is broken, with minimal fuss.

**Comment by vstakhov** [comment]
This looks like a bad issue, I will investigate, thank you very much!

**Comment by vstakhov** [comment]
Thunderbird shows html part, so it's even worse!

**Comment by japc** [comment]
Yes, as I said, I've been seeing those for a while now, and am pretty sure (not tested though) that some MUAs show the part correctly, or else it wouldn't be of much use.
