### ISSUE TITLE
[BUG] Ratelimit bucket symbol cannot find dependency on symbol

### ISSUE THREAD

**Issue by heximcz** [rspamd/rspamd#4756]
I test ratelimit custom symbol as:
```
#./local.d/ratelimit.conf
rates {
    # Limit one mailbox
    my_bucket = {
        selector = "from";
        symbol = "R_REPETED_FROM";
        bucket = {
            burst = 20;
            rate = "10 / 1min";
        }
    }
}
```
groups is:
```
#./local.d/groups.conf
group "ratelimit" {
    max_score = 8.0;
    symbols = {
        "R_REPETED_FROM" {
            weight = 5.0;
            description = "Ratelimit from exceeded";
        }

    }
}
```
force action is:
```
#./local.d/force_actions.conf
rules {
    RATELIMIT_FROM {
        action = "reject";
        expression = "R_REPETED_FROM";
        # message setting sets SMTP message returned by mailer
        message = "(incident-id: ${queueid}) R_RTL_F. Rejected due too much spam, you are not welcome here.";
    }
} 
```

But rspamadm configtest show:
```
cannot find dependency on symbol R_REPETED_FROM for symbol FORCE_ACTION_RATELIMIT_FROM
syntax OK

```

Even if I don't use force_action, the symbol in the bucket is ignored and the weight from the group is not added to the report. Only when I use the global symbol in ratelimit.comf does group or force_action work.

Did I miss something in the [documentation](https://rspamd.com/doc/modules/ratelimit.html#changes-in-the-module) or is this a bug?

Another question is whether it is possible to ignore the authenticated user in the bucket?

Version of Rspamd is 3.7.5

Thank you and have a nice day.

**Comment by fatalbanana** [comment]
`symbol` should be set parallel to `rate` inside `bucket`. That should fix symbol registration.

Futher, you should either apply [this commit](https://github.com/rspamd/rspamd/commit/563198e11abe3b4084cf106de7e337a22f0e87b0) or set `skip_soft_reject = true`  inside `bucket` configuration as workaround for the symbol to actually be inserted.

**Comment by fatalbanana** [comment]
Yes, [these](https://github.com/rspamd/rspamd.com/pull/717) [PRs](https://github.com/rspamd/rspamd.com/pull/718) are relevant.
