### ISSUE TITLE
[BUG] Missing cryptographic signature on debian 12 apt-stable repo

### ISSUE THREAD

**Issue by mtissington** [rspamd/rspamd#4780]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
[Similar to this](https://github.com/rspamd/rspamd/issues/4319)

### Steps to Reproduce

    Install rspamd repo for debian 12  as described on the downloads page
    run apt update
    Get the following error

`Get:5 https://rspamd.com/apt-stable bookworm InRelease [3161 B]
Err:5 https://rspamd.com/apt-stable bookworm InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FFA232EDBF21E25E
Reading package lists... Done
W: GPG error: https://rspamd.com/apt-stable bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FFA232EDBF21E25E
E: The repository 'http://rspamd.com/apt-stable bookworm InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

**Comment by vstakhov** [comment]
You probably forgot to install the gpg key.

**Comment by fatalbanana** [comment]
It works for me; maybe something has gone wrong on steps about installing GPG key.

**Comment by mtissington** [comment]
Got it working - in the end I took the script for installing webmin and figured out what needed - being able to store the .`gpg` in `/usr/share/keyrings/` and the `.asc` in `/etc/apt/trusted.gpg.d/` - not sure if the `.asc` was needed.
