### ISSUE TITLE
[BUG] rspamd v3.8.0 fails to start with lua 5-1 (works with lua 5-3 and lua 5-4)

### ISSUE THREAD

**Issue by erialor** [rspamd/rspamd#4784]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
rspamd fail to start when using lua 5-1 with:

mail ~ # /etc/init.d/rspamd start
rcl parse error: cannot init lua file /usr/share/rspamd/rules/rspamd.lua: error loading module 'lua_maps' from file '/usr/share/rspamd/lualib/lua_maps.lua':
        /usr/share/rspamd/lualib/lua_maps.lua:564: nesting of [[...]] is deprecated near '['; trace: [1]:{[C]:-1 - <unknown> [C]}; [2]:{[C]:-1 - require [C]}; [3]:{/usr/share/rspamd/lualib/global_functions.lua:21 - <unknown> [main]}; [4]:{[C]:-1 - require [C]}; [5]:{rspamd.lua:19 - <unknown> [main]};
 * ERROR: rspamd failed to start
mail ~ #

### Steps to Reproduce

1. Make sure your using Lua 5.1
2. Compile rspamd 3.8.0
3. Start rspamd 3.8.0

**Expected behavior**
After changing to Lua 5.3 or Lua 5.4 it *just* starts:
mail ~ # /etc/init.d/rspamd start
 * Caching service dependencies ...                                                                                                                       [ ok ]
implicitly enabling luapattern returncodes_matcher for rule nil
implicitly enabling luapattern returncodes_matcher for rule nil
 * Starting rspamd ...
2024-01-20 14:51:04 #7788(main) <12d986>; main; main: rspamd 3.8.0 is loading configuration, build id: release                                            [ ok ]
mail ~ #

### Versions
mail ~ # rspamd --version
Rspamd daemon version 3.8.0

CPU architecture x86_64; features: avx2, avx, sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
Hyperscan enabled: TRUE
Jemalloc enabled: FALSE
LuaJIT enabled: FALSE (Lua version: Lua 5.1)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE

### Additional Information
https://bugs.gentoo.org/922522

**Comment by arkamar** [comment]
I have bisected it, the issue was introduced in commit b189c9fea633 ("[Minor] lua_maps docs: apply formatting"). I guess it is about nested comments.
