### ISSUE TITLE
[BUG] rspamd removes foreign Authentication-Results when told not to

### ISSUE THREAD

**Issue by Jajcus** [rspamd/rspamd#4827]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

rspamd milter_headers module seems to always remove existing Authentication-Results headers when adding its own. This is a problem as Authentication-Results headers added by other server may be valuable for debugging mail problem (sometimes on those other servers)

### Steps to Reproduce

1. Enable DKIM checking and adding Authentication-Results on the target mail server

``/etc/rspamd/local.d/milter_headers.conf``:
```
use = ["authentication-results"];
remove_upstream_spam_flag = true;

routines {
  authentication-results {
    # Do not remove existing headers
    remove = 0;
  }
}
```

3. Use a similar configuration on another mail server that will send mail to the target server
4. Send a DKIM-signed message through the second server to the first one

**Expected behavior**

Received message should contain ``Authentication-Results`` headers from both servers. Intermediate results should be removed only when I set ``remove = 1`` in ``authentication-results`` routine setting in ``milter_headers.conf``.

**Actual behavior**

Only ``Authentication-Results`` from the target server are included. I can see  ``Authentication-Results`` from the intermediate server only if I disable generating this header on the target one by removing ``"authentication-results"`` from ``use`` line in ``milter_headers.conf``.

### Versions

```
$ rspamd --version
Rspamd daemon version 3.8.1

CPU architecture x86_64; features: avx2, avx, sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
Hyperscan enabled: TRUE
Jemalloc enabled: TRUE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.1700008891)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE
```

on Debian GNU/Linux 12 (bookworm)

**Comment by fatalbanana** [comment]
https://github.com/rspamd/rspamd/pull/5003
