### ISSUE TITLE
[BUG] history error since update to 3.8.2

### ISSUE THREAD

**Issue by rseffner** [rspamd/rspamd#4828]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:

**Describe the bug**
Switching to history-tab in webui results in following error message and no history-results
`
Cannot receive history: {"error":"WRONGTYPE Operation against a key holding the wrong kind of value"}
`

### Steps to Reproduce
1. open webui
2. switch to history-tab || or press refesh there

**Expected behavior**
Loading the history without any errors

### Versions
ns1:~# rspamd --version
Rspamd daemon version 3.8.2

CPU architecture x86_64; features: avx2, avx, sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
Hyperscan enabled: TRUE
Jemalloc enabled: TRUE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.1700008891)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE

### Additional Information
- restarting rspamd or redis does not resolve the Problem
- changing browser or clearing brwosers cache does not resolve problem

**Comment by snetat** [comment]
I have the same problem.
The following is in the rspamd.log when calling the webui history:

`lua; history_redis.lua:261: got error WRONGTYPE Operation against a key holding the wrong kind of value when getting history: no value`

**Comment by fsyy** [comment]
same here.

**Comment by Metrax** [comment]
same here

**Comment by DiveSurfer** [comment]
The same error also occurs for me

**Comment by DiveSurfer** [comment]
it works for me if I set the key_prefix in local.d/history_redis.conf to `"rs_history{{HOSTNAME}}{{COMPRESS}}";` instead of `"rs_history";`.

**Comment by vstakhov** [comment]
echo 'DEL rs_history' | redis-cli
