### ISSUE TITLE
[BUG] Gmail accounts with dots in email addresses trigger ARC failed error

### ISSUE THREAD

**Issue by wangx404** [rspamd/rspamd#4833]
### Prerequisites

A gmail account with dot in username.

**Describe the bug**

Emails sent from gmail accounts, which looks like `username.arc@gmail.com` are marked as suspicious because of `ARC failed`.

`ARC_REJECT(2.00){signature check failed: fail, {[1] = sig:gmail.com:dns request to mail._domainkey.gmail.com failed: no records with this name};`

FYI, this error is NOT caused by firewall settings or DNS issues. `mail._domainkey.gmail.com` is NOT a valid DNS record.

### Steps to Reproduce

1. Send an email with a Gmail account, which looks like `username.suffix@gmail.com` to a system protected by `rspamd`
2. check logs in `rspamd` on the recipient side

**Expected behavior**

According to documents of Gmail (https://support.google.com/mail/answer/22370?hl=en&sjid=2441564382570344514-AP#zippy=%2Cfilter-using-your-gmail-alias), dot shall NOT be considered as a char to tag email addresses. 

For instance, emails sent to `username.suffix@gmail.com` would be received by `username.suffix@gmail.com` rather than `username@gmail.com`. 

We temporarily solved this issue by modifying `lualib/lua_util.lua`. `specific_domains` are set to empty to skip the following function of `check_gmail_user`

```
  local function check_gmail_user(addr)
    -- Remove all points
    local no_dots_user = string.gsub(addr.user, '%.', '')
    local cap, pluses = string.match(no_dots_user, '^([^%+][^%+]*)(%+.*)$')
    if cap then
      return cap, rspamd_str_split(pluses, '+'), nil
    elseif no_dots_user ~= addr.user then
      return no_dots_user, {}, nil
    end

    return nil
  end
```

### Versions

2.6

This bug exists in the latest version (3.8) as well

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by vstakhov** [comment]
> For instance, emails sent to `username.suffix@gmail.com` would be received by `username.suffix@gmail.com` rather than `username@gmail.com`.

It is not true: https://support.google.com/mail/answer/7436150?hl=en-GB

**Comment by wangx404** [comment]
You are right about the how it works with dots in username in https://support.google.com/mail/answer/7436150?hl=en-GB
But I still don't understand why it triggers the DNS issue I mentioned earlier. The ARC signature is pasted below:

```
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=gmail.com;
	s=mail; t=1708586517;
	h=from:from:reply-to:subject:subject:date:date:message-id:message-id:
	to:to:cc:mime-version:mime-version:content-type:content-type:
	in-reply-to:in-reply-to:references:references:dkim-signature;
	bh=6lF6x4/l8zgmUc1InsB9myJgzjfzTkRsVXryQ/lQFYQ=;
	b=NY85Al/9bC3Htu8y+24qu7wc3pX5F7lpMf580dC/ozuCqAR6/7BlWzU2zXmaIC4SUVBLqC
	0FEbX/inWEgSKRAmePhJT1pd5ng/Ig+v0nA8XIEdWoGGnkPhSZHxd68WMHo/iYlSiIBK8Y
	sTw//2OEw74ZcDCv+HTLDyjgdQ/V0oNCcH0SchGc+93CKexLGCs/Hc8M5Li/ZzCGWGZAFW
	/EGDe9NObU73+tLJKt9O1f9oIUlNuM4b4HgeH4np8O3ESszOE6KlK1ZLpQNDTq/W+7ByYk
	fjN4qlEjPbfG1zogmnArZvILxKKQVn9SX+1nFHBck7su568xxGO3Af8VDPD/yQ==
```

According to what I know, ARC checking shall check DNS records of `20230601._domainkey.gmail.com` rather than `mail._domainkey.gmail.com`, right? If you need more information, please let me know, thanks.

**Comment by vstakhov** [comment]
> According to what I know, ARC checking shall check DNS records of `20230601._domainkey.gmail.com` rather than `mail._domainkey.gmail.com`, right?

No, you are not right. It is <selector>._domainkey.<domain>. `s=mail` and `d=gmail.com`, so Rspamd correctly checks for `mail._domainkey.gmail.com`. How it could even come to `20230601._domainkey.gmail.com` is completely cryptic to me.

**Comment by wangx404** [comment]
Thank you for your clarification. I'll check the configuration file we use.
