### ISSUE TITLE
[BUG] Rspamd 3.8.2/3.8.3: History view in web interface fails with "Cannot receive history"

### ISSUE THREAD

**Issue by athletikworkout** [rspamd/rspamd#4835]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
After updating Debian from Rspamd version 3.8.1 to version 3.8.3, the History view in the web interface no longer works.
Pressing the update button results in an error message: "**Cannot receive history**".

The Logfile shows: #626(controller) **<1d043a>; lua; history_redis.lua:261: got error WRONGTYPE Operation against a key holding the wrong kind of value when getting history: no value**

Even the Reset button shows an error, that the history cannot be resetted.

If the two files [lua_util.lua](https://github.com/rspamd/rspamd/blob/master/lualib/lua_util.lua) and [history_redis.lua](https://github.com/rspamd/rspamd/blob/master/src/plugins/lua/history_redis.lua) are manually reset to the code of version 3.8.1, the view will work with the data up to the time of the update.
New messages no longer appear in the view.

### Steps to Reproduce

1. Update Debian via apt to the latest rspamd package (from a version < 3.8.2)
2. login to the Rspamd web interface
3. go to  the History view

**Expected behavior**
The history view should work with the data from older Rspamd versions.

### Versions

Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

Rspamd daemon version 3.8.3

CPU architecture x86_64; features: sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
Hyperscan enabled: TRUE
Jemalloc enabled: TRUE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.1700008891)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by DiveSurfer** [comment]
Double solution at https://github.com/rspamd/rspamd/issues/4828

**Comment by athletikworkout** [comment]
Which of the two solutions should be favoured?
What are the advantages and disadvantages of each?
