### ISSUE TITLE
[BUG] rspamadm: dmarc report: unknown filter "escape_xml"

### ISSUE THREAD

**Issue by tdewolff** [rspamd/rspamd#4836]
While running `rspamadm dmarc_report`, I'm receiving the following error back over e-mail:

> call to rspamadm lua script failed (2): Runtime Error in file "<string>" on line 4, column 44: unknown filter "escape_xml"; trace: [1]:{/usr/share/rspamd/lualib/lupa.lua:310 - env_assert [Lua]}; [2]:{/usr/share/rspamd/lualib/lupa.lua:345 - eval [Lua]}; [3]:{/usr/share/rspamd/lualib/lupa.lua:379 - evaluate [Lua]}; [4]:{/usr/share/rspamd/lualib/lupa.lua:736 - expand [Lua]}; [5]:{/usr/share/rspamd/lualib/lua_util.lua:218 - report_header [Lua]}; [6]:{/usr/share/rspamd/lualib/rspamadm//dmarc_report.lua:504 - prepare_report [Lua]}; [7]:{/usr/share/rspamd/lualib/rspamadm//dmarc_report.lua:600 - process_report_date [Lua]}; [8]:{/usr/share/rspamd/lualib/rspamadm//dmarc_report.lua:696 - <unknown> [Lua]};

And right, the `escape_xml` filter is not defined in `lupa.lua`. This is happening since a few days (presumably since the latest release).

Additionally, I'm running rspamd 3.8.3 for some reason, while 3.8.2 is the latest release. The repo says 3.8.3 is the latest (https://rspamd.com/rpm-stable/centos-8/x86_64/) while GitHub says 3.8.2 (https://github.com/rspamd/rspamd/releases). Not sure what that means? Is 3.8.3 more like `master` and not a proper release?

**Comment by vstakhov** [comment]
@fatalbanana :(

**Comment by reinob** [comment]
I have the same, and as far as I can tell it came with 3.8.2.
3.8.3 was just released this morning (CET), so it should soon be available in the repository. Whether that fixes the issue, I (still) don't know.

For completeness, the output of "rspamadm dmarc_report" looks like:
```
call to rspamadm lua script failed (2): Runtime Error in file "<string>" on line 4, column 44: unknown filter "escape_xml"; trace: [1]:{/usr/share/rspamd/lualib/lupa.lua:310 - env_assert [Lua]}; [2]:{/usr/share/rspamd/lualib/lupa.lua:345 - eval [Lua]}; [3]:{/usr/share/rspamd/lualib/lupa.lua:379 - evaluate [Lua]}; [4]:{/usr/share/rspamd/lualib/lupa.lua:736 - expand [Lua]}; [5]:{/usr/share/rspamd/lualib/lua_util.lua:218 - report_header [Lua]}; [6]:{/usr/share/rspamd/lualib/rspamadm//dmarc_report.lua:504 - prepare_report [Lua]}; [7]:{/usr/share/rspamd/lualib/rspamadm//dmarc_report.lua:600 - process_report_date [Lua]}; [8]:{/usr/share/rspamd/lualib/rspamadm//dmarc_report.lua:696 - <unknown> [Lua]};
```

**Comment by ol-iver** [comment]
I'm having the same issue 😞 
It began with the release of `3.8.3` which was about 2 days ago for Ubuntu and not this morning like the Github Release suggests.

**Comment by reinob** [comment]
Oh, you're right. The currently installed version (rspamd.com/apt-stable) is indeed 3.8.3.
So yes, it must have been with that release.
