### ISSUE TITLE
Rspamd Docker Redis Host server connection refused

### ISSUE THREAD

**Issue by stefanmcds-mnt** [rspamd/rspamd#4837]
Rspamd Docker latest.
Docker run:
docker \
 run \
 -v /var/lib/rspamd:/var/lib/rspamd \
 -v /etc/rspamd:/etc/rspamd \
 -v /var/log/rspamd:/var/log/rspamd \
 -p 127.0.0.1:11332:11332 \
 -p 127.0.0.1:11333:11333 \
 -p 127.0.0.1:11334:11334 \
 --name rspamd \
 --quiet \
 --rm \
 -d rspamd/rspamd

1. Log are not stored
2. Rspamd not connect to redis server on host running on 127.0.0.1:6379
- got error Connection refused when getting history: no value
- cannot upload script to 127.0.0.1:6379: Connection refused; registered from: /usr/share/rspamd/plugins/neural.lua:978, filename: neural_save_unlock.lua

and other error like below

Please wow can solve?

**Comment by fatalbanana** [comment]
Please use [Discussions](https://github.com/rspamd/rspamd/discussions).

Use [host networking](https://docs.docker.com/network/network-tutorial-host/) to access localhost on the host machine; or run Redis in a container on the same [network](https://docs.docker.com/network/#user-defined-networks) like the [docker compose example](https://github.com/rspamd/rspamd-docker/tree/main/examples/compose) is doing.

**Comment by stefanmcds-mnt** [comment]
with host networking now run all tnk
