### ISSUE TITLE
libbinutils 2.38

### ISSUE THREAD

**Issue by Veszter007** [rspamd/rspamd#4841]
Hi!

Unfortunately, I haven't been able to update rspamd for a while now, as it uses libbinutils 2.34, and under Ubuntu 22.04 version 2.38 can be installed.
Please help, update the app to work with libbinutils 2.38.

Thanks

**Comment by vstakhov** [comment]
Please take some time for making a proper issue describing your problem with all appropriate details. For now, I have no idea about what you are talking about.

**Comment by Veszter007** [comment]
I am using Ubuntu 22.04. When I update this happens:

sudo apt upgrade rspamd
Reading packing lists... Done
Building dependency tree... Done
Reading status information... Done
Calculating update... Done
Some packages could not be installed. This could mean that
requested an impossible state, or if the unstable distribution
use it, some requested packages have not yet been completed or are out
has been moved from Incoming.
The following information may help you resolve the issue:

The following packages have unfulfilled dependencies:
  rspamd : Depends on: libbinutils (< 2.34.1) but only 2.38-4ubuntu2.6 can be installed
E: Broken packages

The package version is no longer available since 20.04:
https://packages.ubuntu.com/search?keywords=libbinutils

**Comment by Veszter007** [comment]
Oh!!!
Thank you very much!
Focal was indeed included in the apt. I changed it to jammy and it updated immediately.
Grateful thanks!
