### ISSUE TITLE
[BUG] WRONGTYPE Operation against a key holding the wrong kind of value

### ISSUE THREAD

**Issue by fpaquet** [rspamd/rspamd#4850]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
Since latest update on RHEL8, we receive error message when opening "History" tab.

```
local > Cannot receive history: {"error": "WRONGTYPE Operation against a key holding the wrong kind of value"}
Request failed
```
All other tabs are working as expected

### Steps to Reproduce

1. Login to rspamd
2. open History tab

**Expected behavior**
No error

### Versions
Rspamd daemon version 3.8.4

CPU architecture x86_64; features: avx2, avx, sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
Hyperscan enabled: TRUE
Jemalloc enabled: TRUE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.1707061634)
ASAN enabled: FALSE
BLAS enabled: TRUE
Fasttext enabled: TRUE

[root@excelsior.opag.ch:/root] dnf list rspamd
rspamd.x86_64                                       3.8.4-1.el8                                       @rspamd

[root@excelsior.opag.ch:/root] cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.9 (Ootpa)

[root@excelsior.opag.ch:/root] uname -a
Linux excelsior.opag.ch 4.18.0-513.18.1.el8_9.x86_64 #1 SMP Thu Feb 1 03:51:05 EST 2024 x86_64 x86_64 x86_64 GNU/Linux

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by fpaquet** [comment]
[root@excelsior.opag.ch:/var/log/rspamd] tail -f rspamd.log

2024-03-02 11:54:38 #1851(controller) <1f7b5d>; lua; history_redis.lua:261: got error WRONGTYPE Operation against a key holding the wrong kind of value when getting history: no value
2024-03-02 11:54:38 #1851(controller) rspamd_controller_check_password: using password as enable_password for a privileged command

**Comment by vstakhov** [comment]
Duplicate, closing.

**Comment by fpaquet** [comment]
Double solution at #4828

Works for me.
