### ISSUE TITLE
[BUG] Weird behaviour on rspamd_regex search

### ISSUE THREAD

**Issue by japc** [rspamd/rspamd#4885]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

Following a report issued to the Spamhaus HBL URL integration with Rspamd, here: https://github.com/spamhaus/rspamd-dqs/issues/26

There seems to be a issue either with the rspam_regexp or with some missing url (path) sanitization. The search ends up eating a lot of memory to build the lookup tables (the callback fails with "not enough memory"/"table overflow"), and that memory never gets freed, at least not quickly.

The code that triggers the problem is

`    local hpart = urlspec.algre[alg]:search(upath)
`

where urlspec.algre[alg] is rspamd_re.create("^$|^[?].*|^[#].*|[^#?]+")

and upath is, por instance `https://cls21.bullhornstaffing.com/MailerUnsubscribe.cfm?privateLabelID=3D26028&email=xpto&updKey=3D%3B%28U%2B%2F%200T%3EI%3B%2FQEI%5E%29%25XR%3FZ%40%5B%2EGJY%3CF%23%3F%25%22%29%5D%2D%0A`

The problem seems to come from the LF (%0A) on the url tail.

### Steps to Reproduce

Call search with the previous regex and string. 

**Expected behavior**

Should not end up failing with "not enough memory".

### Versions

```
rspamd --version
Rspamd daemon version 3.9.0

CPU architecture x86_64; features: avx2, avx, sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
Hyperscan enabled: TRUE
Jemalloc enabled: FALSE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.0-beta3)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE
```

`Debian 11.6 x86_64 GNU/Linux 
`

**Comment by vstakhov** [comment]
This integration is bad and I've mentioned that several times trying to address this issue. If you check the [function documentation](https://rspamd.com/doc/lua/rspamd_regexp.html#fc9753) you'll be able to see that the regexp returned by `rspamd_regexp.create` is NOT automatically destroyed. Therefore, it introduces a memory leak. That was done on purpose to avoid abusing of the regexps creating in the callback which is a bad practice.

However, large companies don't ever care about things like that, and I won't like to be responsible for their faults as well. We have some proper integration with DQS services internally and we can provide it within commercial support package if you want.

**Comment by japc** [comment]
Ok, but if you remove from the picture who's using it, and where, the `rspamd_regexp` allocation of over 1GB for the example given doesn't seem ok.

**Comment by vstakhov** [comment]
If you create objects on each callback call (and you do) and never clear them, it is an apparent memory leak. Why do you believe it is something else? I have tried your regexp and your example and I cannot see anything bad about it.

**Comment by japc** [comment]
From what I see it does a search every call, but the creation is only when loading the yaml with regex definitions.

It seems to loop on

```
while (rspamd_regexp_search(re->re, data, len, &start, &end, raw,
                                                                                captures)) {
```

in `src/lua/lua_regexp.c`

with high CPU and ocasional memory usage doubling.

**Comment by vstakhov** [comment]
The whole logic is broken - you cannot call async functions from re_conditions or regexp rules. I don't know how that can even work tbh. It is also perfectly possible to create a regexp that can eat all memory/cpu due to backtracking (not sure about this particular one though).

**Comment by vstakhov** [comment]
Oh well, that's a different place I'm looking at - your suspection is indeed called from the proper function type.

**Comment by vstakhov** [comment]
It seems it is a real issue, so I'm sorry for the initial comments - it's really hard to overcome the bias when you observe some other fundamental issues with some code.

I'm curious why do you have `len=100` in your case, as it is is 104 in my synthetic test.

**Comment by vstakhov** [comment]
I see the difference - Github has eaten some stuff from re pattern...

**Comment by vstakhov** [comment]
Yes, I got it reproduced:

```
LuaJIT 2.1.0-beta3> r = require "rspamd_regexp"
LuaJIT 2.1.0-beta3> rr = r.create("^$|^[?].*|^[#].*|[^#?]+")
LuaJIT 2.1.0-beta3> u = require "rspamd_url"
LuaJIT 2.1.0-beta3> uu = u.create('https://cls21.bullhornstaffing.com/MailerUnsubscribe.cfm?privateLabelID=3D26028&email=xpto&updKey=3D%3B%28U%2B%2F%200T%3EI%3B%2FQEI%5E%29%25XR%3FZ%40%5B%2EGJY%3CF%23%3F%25%22%29%5D%2D%0A')
LuaJIT 2.1.0-beta3> rr:search('/' .. uu:get_path() .. '?' .. uu:get_query())
... badum-tsss
```

**Comment by vstakhov** [comment]
And the difference is that `^$|^[?].*|^[#].*|[^#?]+` got blown while `^$|^[?].|^[#].|[^#?]+` works just fine.

**Comment by vstakhov** [comment]
So it's still not Rspamd fault I believe: pcre just have backtracking blow up on this regexp.

**Comment by vstakhov** [comment]
`lldb` traces clearly shows that all memory/cpu waste is in pcre2.

**Comment by vstakhov** [comment]
Or no, forget it - in fact it is really my issue: start == end, so this function tries to calculate len via strlen, that is a mistake - a big mistake...

**Comment by japc** [comment]
> It seems it is a real issue, so I'm sorry for the initial comments - it's really hard to overcome the bias when you observe some other fundamental issues with some code.
> 
> I'm curious why do you have `len=100` in your case, as it is is 104 in my synthetic test.

No problem.

**Comment by vstakhov** [comment]
Ok, so it's actually a bit more complicated than I've thought. So Rspamd gets a regexp that is not multiline and pcre reports that `end` must be one byte before the actual end. But also `start` is at the same character. Rspamd calculates remaining length as `remain = len - (end - text);`, so if `end` is 1 character before the actual end, it will just stuck there, as `start` variable is not considered at all.

**Comment by vstakhov** [comment]
So the actual issue is that regexps that allow empty patterns are poorly processed with Rspamd in general. Interesting, that it's not an issue for hyperscan that (correctly) does not allow empty patterns by default.
