### ISSUE TITLE
[BUG] Re-learning bayes not work properly after migration to LUA scripts in Redis

### ISSUE THREAD

**Issue by dragoangel** [rspamd/rspamd#4928]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * [X] Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * [X] Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * [X] Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * [ ] Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * [X] Checked that there is not already an experimental package or master branch

**Describe the bug**
Re-learning bayes not work properly after migration to LUA scripts in Redis due to missing action to swap flag in `learned_ids` (`learned_idsX`, etc), allowing to learn email in opposite direction as much as you want, which should not be the case.

### Steps to Reproduce

1. Learn eml as spam
2. Learn eml as spam second time - get `status code 208` already learned
3. Learn eml as ham - get `status code 200`
4. Learn eml as ham multiply time (f.e.: 3x) - get `status code 200`
5. Check redis `RS` key, where element `learns_spam` will be negative value which is wrong and bayes will not work at all from this point.
6. Check redis `learned_ids` key for this eml - flag will be still set as "spam" - `1`, when should be swapped to `-1` (as old, pre 3.8 behavior) or `0` (as 3.8 key for ham)

This works same in both directions, so if swap spam to ham in above steps - results will be same.

**Expected behavior**
Re-learning should change flag on relearning in opposite direction and **move** eml hash to "fresh" `learned_ids` slot (key). By *move* I mean:
1. check if we have key in any of `learned_ids`
4. if there "no learns" of previous learn has "opposite flag" from what we tries to learn proceed >>
5. if previous learn is in latest `learned_ids` - replace it with new "flag"
6. if previous learn not in latest `learned_ids` - add it to latest `learned_ids` with new flag + replace element key name in "older" `learned_ids` to value that will be never correct "hash"
3. learn bayes for needed flag.

**Notes:** As rspamd "fills" not filled `learned_ids` to meet `cache_max_elt` we can't actually "delete" key from older `learned_ids`, but we can replace it with value that would never be a valid "hash" and add eml hash to latest `learned_ids` to achieve proper re-learning.

**Question:** is change of `-1` to `0` for ham `learned_ids` is backward compatible on update? I not fully get this

### Versions

Rspamd build from https://github.com/rspamd/rspamd/commit/e8b1fd0ec72556d2ab8f65f2f4172927b7d79cc0 aka v3.9.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by dragoangel** [comment]
@vstakhov another part of bug with `learned_ids` is that when learn requires to "delete" key as all keys are filled new key with element of learning doesn't created, it will be only created on **second** learn when there will become space to save it.

**Comment by dragoangel** [comment]
Hi @aduernberger @vstakhov mentioned PRs fixed relearning and aligned `0`, `-1`, but next cases still have place:

1. when we moving from one key to another email learning triggers delete and move of keys, but not creates new key with new element, it will be only created on next learn
2. relearning email that exist in older key doesn't move hash elements to more fresh key

I don't know how this is critical. @vstakhov what is expected time of protecting keys from relearning multiply times in one direction? 1d, 2-3d or a week for example?

**Comment by dragoangel** [comment]
Btw do we need mention in docs new configuration settings for `cache_max_elt` and `cache_max_keys` for users who have bigger learns to adjust them to some recommended values based on some expected timeframe of learns?

**Comment by aduernberger** [comment]
>     1. relearning email that exist in older key doesn't move hash elements to more fresh key, meaning relearning of email that was first learned couple of days ago will not protect it from deletion in quite few hours\day.

Hmm I don't really see an easy way to do this. Just removing the old `cache_id` from the `prefix` would make the prefix writable again. Which means that the next learn would be saved in an old prefix. I am also not sure that current behavior is
wrong. 

>     2. when we moving from one key to another email learning triggers delete and move of keys, but not creates new key with new element, it will be only created on next learn

You are right. It removes the first (oldest) `prefix` then adds the `cache_id` to the same `prefix`, then renames the newer prefix to the older prefix name, which effectively overwrites the just learned `cache_id`.

**Comment by dragoangel** [comment]
> Hmm I don't really see an easy way to do this. Just removing the old cache_id from the prefix would make the prefix writable again.

I propose rewrite old element with placeholder, like `RE_${hash}` in old key and properly learn it to the current key.
