### ISSUE TITLE
[BUG] rspamd_roll_history_load: assertion failed

### ISSUE THREAD

**Issue by mykeenu** [rspamd/rspamd#4947]
### Prerequisites

**Describe the bug**
I triggered the following assertion:
`Bail out! ERROR:./src/libserver/roll_history.c:201:rspamd_roll_history_load: assertion failed: (history != NULL)`

### Steps to Reproduce

1. set `history_rows = 0;` in [options.inc](https://github.com/rspamd/rspamd/blob/master/conf/options.inc)

(I did this in an attempt to disable history.)

**Expected behavior**
history disabled or warning message+continue

### Versions

present in master, see below

### Additional Information

`Bail out! ERROR:./src/libserver/roll_history.c:201:rspamd_roll_history_load: assertion failed: (history != NULL)`

Underlying case in the code:

- There is a NULL pointer being passed to `rspamd_roll_history_load()` triggering the assertion here: [https://github.com/rspamd/rspamd/blob/f719e0f329b2839869475bd2041de52ded7ab57f/src/libserver/roll_history.c#L201](https://github.com/rspamd/rspamd/blob/f719e0f329b2839869475bd2041de52ded7ab57f/src/libserver/roll_history.c#L201)
- The object `rspamd_main->history` gets created here: [https://github.com/rspamd/rspamd/blob/f719e0f329b2839869475bd2041de52ded7ab57f/src/rspamd.c#L1534](https://github.com/rspamd/rspamd/blob/f719e0f329b2839869475bd2041de52ded7ab57f/src/rspamd.c#L1534)
- However, the call to `rspamd_roll_history_new()` can return a NULL pointer here [https://github.com/rspamd/rspamd/blob/f719e0f329b2839869475bd2041de52ded7ab57f/src/libserver/roll_history.c#L38](https://github.com/rspamd/rspamd/blob/f719e0f329b2839869475bd2041de52ded7ab57f/src/libserver/roll_history.c#L38)
- This case is never checked for

I would create a pull request, however I'm not sure about the best way to resolve this. I have four ideas:

1. Check and abort on NULL after `rspamd_roll_history_new()` call at https://github.com/rspamd/rspamd/blob/f719e0f329b2839869475bd2041de52ded7ab57f/src/rspamd.c#L1534
2. Check for NULL at https://github.com/rspamd/rspamd/blob/f719e0f329b2839869475bd2041de52ded7ab57f/src/rspamd.c#L1613 and https://github.com/rspamd/rspamd/blob/f719e0f329b2839869475bd2041de52ded7ab57f/src/rspamd.c#L1696 which seem to be the only two uses of that object
3. Set `rspamd_main->cfg->history_file` to NULL if the `rspamd_roll_history_new()` call returns NULL, which triggers the two if()s above
4. Change the assertions to early exits, included in the immediately following `return TRUE;` blocks following https://github.com/rspamd/rspamd/blob/f719e0f329b2839869475bd2041de52ded7ab57f/src/libserver/roll_history.c#L201 and https://github.com/rspamd/rspamd/blob/f719e0f329b2839869475bd2041de52ded7ab57f/src/libserver/roll_history.c#L377

Additional improvements:
- Check all parameters before call at https://github.com/rspamd/rspamd/blob/f719e0f329b2839869475bd2041de52ded7ab57f/src/rspamd.c#L1534 (does not resolve the bug in general but could avoid my case)
- Log a debug message on NULL after call at https://github.com/rspamd/rspamd/blob/f719e0f329b2839869475bd2041de52ded7ab57f/src/rspamd.c#L1534

**Comment by vstakhov** [comment]
I don't like to describe a clear misconfiguration as a "bug". It is not a bug, just don't do it.

**Comment by mykeenu** [comment]
> I don't like to describe a clear misconfiguration as a "bug". It is not a bug, just don't do it.

The bug is that an assertion can be triggered due to misunderstandings about whether a variable can be NULL or not in different parts of the code. Therefore the detailed explanation about what is happening where.

The configuration variable and its possible values aren't really documented anywhere, so I tried out things, that's just how I found the problem by chance.

I created this issue in an attempt to find out which of the suggested improvements you think should be implemented, and then create a pull request with those. Of course "this is fine" can also be a response - if you think none of my suggestions are useful, feel free to close as wontfix.

**Comment by vstakhov** [comment]
I just mean that it can be really improved but it is not a bug, at least technically :)

**Comment by vstakhov** [comment]
I just mean that it can be really improved but it is not a bug, at least technically :)

**Comment by mykeenu** [comment]
okay, unfortunately I seem to be unable to change the "bug" label to something else, if you want to do that please go ahead.

**Comment by dragoangel** [comment]
Nice, I also want to have disable history as whole :)

**Comment by dragoangel** [comment]
Working, great, just one note - I think we need add extra handling this in controller as "history fully disabled" and not throw `500 internal error` `localhost:11334/history`

**Comment by mykeenu** [comment]
nice, thank you for the fix!
