### ISSUE TITLE
[BUG] Build Failure on macOS arm64 because build/contrib/snowball/snowball segfaults

### ISSUE THREAD

**Issue by essandess** [rspamd/rspamd#4958]
I'm the `rspamd` maintainer on MacPorts, and am working to create an `arm64` build with `vectorscan`. The `x86_64` builds of `rspamd`+`vectorscan` all work fine.

I'm running into the issue of the binary `snowball` compiled during the build segfaulting on `arm64` when `-DENABLE_SNOWBALL=ON` is set:

```sh
/opt/local/var/macports/build/_opt_local_ports_mail_rspamd/rspamd/work/build/contrib/snowball/snowball
Killed: 9
file /opt/local/var/macports/build/_opt_local_ports_mail_rspamd/rspamd/work/build/contrib/snowball/snowball
/opt/local/var/macports/build/_opt_local_ports_mail_rspamd/rspamd/work/build/contrib/snowball/snowball: Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>
```

When this binary is called later in the build, the crash obviously causes the build to fail.

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

The bug itself occurs when the binary `snowball` is called during the build:

```sh
cd /opt/local/var/macports/build/_opt_local_ports_mail_rspamd/rspamd/work/build/contrib/snowball && env ASAN_OPTIONS=detect_leaks=0 /opt/local/var/macports/build/_opt_local_ports_mail_rspamd/rspamd/work/build/contrib/snowball/snowball /opt/local/var/macports/build/_opt_local_ports_mail_rspamd/rspamd/work/rspamd-3.8.4/contrib/snowball/algorithms/turkish.sbl -o /opt/local/var/macports/build/_opt_local_ports_mail_rspamd/rspamd/work/build/contrib/snowball/libstemmer/stem_UTF_8_turkish -eprefix turkish_UTF_8_ -r ../runtime -u
Killed: 9
```

### Steps to Reproduce

Standard `cmake` build with `-DENABLE_SNOWBALL=ON`.

**Expected behavior**

A successful build of `rspamd`.

Note: A build with `-DENABLE_SNOWBALL=OFF` produces these linking errors:

```sh
:info:build Undefined symbols for architecture arm64:
:info:build   "_sb_stemmer_delete", referenced from:
:info:build       _rspamd_language_detector_init in lang_detection.c.o
:info:build   "_sb_stemmer_length", referenced from:
:info:build       _rspamd_stem_words in tokenizers.c.o
…
```

### Versions

You can get this information from copy and pasting the output of `rspamd --version` from the command line. Also, please include the **OS** and what version and architecture including the generation of CPU model (e.g. Haswell) where applicable,  of the OS you're running.

Same build formula on `x64_64`:

```sh
rspamd --version
Rspamd daemon version 3.8.4

CPU architecture x86_64; features: avx2, avx, sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
Hyperscan enabled: TRUE
Jemalloc enabled: FALSE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.1703358377)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE
```

### Additional Information

macOS 14.4.1 23E224 arm64
Xcode 15.3 15E204a

cmake --version
cmake version 3.29.2

**Comment by essandess** [comment]
Here's what I see from `lldb`:

```sh
lldb /opt/local/var/macports/build/_opt_local_ports_mail_rspamd/rspamd/work/build/contrib/snowball/snowball
(lldb) target create "/opt/local/var/macports/build/_opt_local_ports_mail_rspamd/rspamd/work/build/contrib/snowball/snowball"
Current executable set to '/opt/local/var/macports/build/_opt_local_ports_mail_rspamd/rspamd/work/build/contrib/snowball/snowball' (arm64).
(lldb) run
error: Malformed Mach-o file
```

**Comment by vstakhov** [comment]
I'm using Rspamd on Arm64 macbook - afair, this commit was needed: https://github.com/rspamd/rspamd/commit/db02d917d4a0d853938a02ce56b5c4d914fca50f

**Comment by essandess** [comment]
Thank you! This fixes the issue.
