### ISSUE TITLE
[Feature] Score if FROM and TO are exactly the same

### ISSUE THREAD

**Issue by flaviozluca** [rspamd/rspamd#4971]
[Feature] Score if FROM and TO are exactly the same

How about that idea?

See, major phish.

Thanks.
[Alerta de segurança. - (flavio@lucanet.com.br) - 2024-05-15 0457.zip](https://github.com/rspamd/rspamd/files/15323089/Alerta.de.seguranca.-.flavio%40lucanet.com.br.-.2024-05-15.0457.zip)

**Comment by moisseev** [comment]
I believe you can set a positive score to `TO_EQ_FROM` symbol.
