### ISSUE TITLE
[BUG] init of /usr/share/rspamd/lualib/lua_ffi/spf.lua failed: /usr/share/rspamd/lualib/lua_ffi/spf.lua:71: size of C type is unknown or too large at line 35

### ISSUE THREAD

**Issue by fhanzlik** [rspamd/rspamd#4977]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
"rspamadm configtest" prints several warning messages, the most serious one seems to be in the message header.
The mentioned symbols are probably those from the basic configuration of rspamd (not from my local one):

\# rspamadm configtest
duplicate symbol: CHECK_MID, skip registering
trying to add virtual symbol MID_BARE_IP as real (no parent)
trying to add virtual symbol MID_RHS_NOT_FQDN as real (no parent)
trying to add virtual symbol MID_MISSING_BRACKETS as real (no parent)
trying to add virtual symbol MID_RHS_IP_LITERAL as real (no parent)
trying to add virtual symbol MID_CONTAINS_FROM as real (no parent)
trying to add virtual symbol MID_RHS_MATCH_FROM as real (no parent)
trying to add virtual symbol MID_RHS_MATCH_FROMTLD as real (no parent)
trying to add virtual symbol MID_CONTAINS_TO as real (no parent)
trying to add virtual symbol MID_RHS_MATCH_TO as real (no parent)
duplicate symbol: MID_END_EQ_FROM_USER_PART, skip registering
init of /usr/share/rspamd/lualib/lua_ffi/spf.lua failed: /usr/share/rspamd/lualib/lua_ffi/spf.lua:71: size of C type is unknown or too large at line 35; trace: [1]:{[C]:-1 - cdef [C]}; [2]:{/usr/share/rspamd/lualib/lua_ffi/spf.lua:71 - <unknown> [main]};
syntax OK

**Expected behavior**
Failed module init message IMO should not be, other messages I not know...

### Versions
rspamd-3.8.4-2.fc39.x86_64 (my own build on Fedora 40 x86_64)

**Comment by fatalbanana** [comment]
The likely reason is that `PLUGINSDIR` is set incorrectly at build time (if you'd leave it unset the default should be right).

https://github.com/rspamd/rspamd/discussions/4819
https://github.com/rspamd/rspamd/discussions/4898

**Comment by WalterHof** [comment]
How to find out, if PLUGINSDIR was set incorrectly?

**Comment by fatalbanana** [comment]
> How to find out, if PLUGINSDIR was set incorrectly?

```shell
$ docker run -ti rspamd/rspamd sh
$ rspamadm lua # we can see PLUGINSDIR & LUALIBDIR here
LuaJIT 2.1.1713773202> rspamd_paths
{[LOGDIR] = /var/log/rspamd, [WWWDIR] = /usr/share/rspamd/www, [PLUGINSDIR] = /usr/share/rspamd/plugins, [SHAREDIR] = /usr/share/rspamd, [CONFDIR] = /usr/share/rspamd/config, [PREFIX] = /usr, [LOCAL_CONFDIR] = /etc/rspamd, [LUALIBDIR] = /usr/share/rspamd/lualib, [RUNDIR] = /run/rspamd, [RULESDIR] = /usr/share/rspamd/rules, [DBDIR] = /var/lib/rspamd}
LuaJIT 2.1.1713773202> 
$ ls /usr/share/rspamd/plugins  # these are executed on startup
antivirus.lua	  dkim_signing.lua	 fuzzy_collect.lua  maps_stats.lua	   once_received.lua  spamassassin.lua
arc.lua		  dmarc.lua		 gpt.lua	    metadata_exporter.lua  p0f.lua	      spamtrap.lua
asn.lua		  dynamic_conf.lua	 greylist.lua	    metric_exporter.lua    phishing.lua       spf.lua
aws_s3.lua	  elastic.lua		 hfilter.lua	    mid.lua		   ratelimit.lua      trie.lua
bayes_expiry.lua  emails.lua		 history_redis.lua  milter_headers.lua	   rbl.lua	      url_redirector.lua
bimi.lua	  external_relay.lua	 http_headers.lua   mime_types.lua	   replies.lua	      whitelist.lua
clickhouse.lua	  external_services.lua  ip_score.lua	    multimap.lua	   reputation.lua
clustering.lua	  force_actions.lua	 known_senders.lua  mx_check.lua	   rspamd_update.lua
dcc.lua		  forged_recipients.lua  maillist.lua	    neural.lua		   settings.lua
$ ls /usr/share/rspamd/lualib # these are not except on broken builds
ansicolors.lua	      lua_bayes_learn.lua    lua_ffi		       lua_mime.lua	   lua_stat.lua		 plugins_stats.lua
argparse.lua	      lua_bayes_redis.lua    lua_fuzzy.lua	       lua_mime_types.lua  lua_tcp_sync.lua	 redis_scripts
fun.lua		      lua_cfg_transform.lua  lua_lexer.lua	       lua_redis.lua	   lua_urls_compose.lua  rspamadm
global_functions.lua  lua_cfg_utils.lua      lua_magic		       lua_scanners	   lua_util.lua		 tableshape.lua
lpegre.lua	      lua_clickhouse.lua     lua_maps.lua	       lua_selectors	   lua_verdict.lua
lua_auth_results.lua  lua_content	     lua_maps_expressions.lua  lua_settings.lua    lupa.lua
lua_aws.lua	      lua_dkim_tools.lua     lua_meta.lua	       lua_smtp.lua	   plugins
~~~
