### ISSUE TITLE
[BUG] Only first key in worker-fuzzy.conf is usable

### ISSUE THREAD

**Issue by leahoswald** [rspamd/rspamd#4986]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
I tried to add multiple keypairs to worker-fuzzy.conf to enable a friend to use my fuzzy storage. While I got an error every few seconds for their connection, the local connection worked without problem. After some further debugging, I changed the order of keypairs and suddenly it worked on my friends server but the local connection was broken. It looks like only the first keypair is usable.

The error I got on the failing server (running the fuzzy storage) was:

> May 26 22:47:59 mx1 rspamd[1419718]: (fuzzy) rspamd_fuzzy_decrypt_command: decryption failed; ip=
> May 26 22:47:59 mx1 rspamd[1419718]: (fuzzy) accept_fuzzy_socket: invalid fuzzy command of size 1 received

The error on the non working client was:
> May 26 21:34:49 mx2 rspamd[21126]: <af7a82>; csession; fuzzy_check_timer_callback: got IO timeout with server example.com:11335(<ip>:11335), after 1/1 retransmits

### Steps to Reproduce
1. Enable `encrypted_only = true;` in worker-fuzzy.conf
2. Add more than two keypairs as generated by `rspamadm keypair -u`
3. Every keypair beside the first one isn't usable and generating errors.

**Expected behavior**
Every keypair works and enables a client to connect to the storage.

### Versions
Both servers run rspamd v3.8.4

**Comment by fatalbanana** [comment]
The way to specify multiple keypairs is as a list, e.g.

```
keypair = [
  {
    pubkey = "..."
    # ....
  },
  # ...
]
```

**Comment by leahoswald** [comment]
Opened a pull request for the docs: https://github.com/rspamd/rspamd.com/pull/754

This issue can be closed after merging.
