### ISSUE TITLE
maps.rspamd.com down?

### ISSUE THREAD

**Issue by ikt** [rspamd/rspamd#5005]
Just a small random issue I noticed, logs are full of:

Jun  4 23:22:00  named[784]: connection refused resolving '_.192.asn.rspamd.com/A/IN': 151.115.41.123#53
Jun  4 23:22:02  named[784]: connection refused resolving '35hr4egku9g1r3hdpqwao6kubzt95hr4.phishtank.rspamd.com/TXT/IN': 151.115.41.123#53
Jun  4 23:22:02  named[784]: connection refused resolving 'kgakzort5iien61gdzi4nwuyc8ueyw18.phishtank.rspamd.com/TXT/IN': 151.115.41.123#53
Jun  4 23:22:02  named[784]: connection refused resolving 'k6w16x13bbh9iw848fgsny44ws84zmfx.uribl.rspamd.com/A/IN': 151.115.41.123#53
Jun  4 23:32:19  named[784]: connection refused resolving '_.74.asn.rspamd.com/A/IN': 151.115.41.123#53
Jun  4 23:32:21  named[784]: connection refused resolving '_.24.91.74.asn.rspamd.com/A/IN': 151.115.41.123#53
Jun  5 00:02:07  named[784]: connection refused resolving '86.237.227.192.asn.rspamd.com/TXT/IN': 151.115.41.123#53
Jun  5 00:02:09  named[784]: connection refused resolving '5jdwdg5mo98gphz4kdmdexty8at4p3ce.phishtank.rspamd.com/TXT/IN': 151.115.41.123#53
Jun  5 00:02:09  named[784]: connection refused resolving '5tabtftwzhqzhzkujbef6wk7fpua999k.phishtank.rspamd.com/TXT/IN': 151.115.41.123#53
Jun  5 00:02:30  named[784]: connection refused resolving 'm6mrnyhtahqtedz9qazjbcxijhzew73r.phishtank.rspamd.com/TXT/IN': 151.115.41.123#53
Jun  5 00:02:30  named[784]: connection refused resolving 'wps315bwerxck6ea5murkigkinbtgfea.phishtank.rspamd.com/TXT/IN': 151.115.41.123#53
Jun  5 00:02:30  named[784]: connection refused resolving 'qitktn4b8t9u4r115899uhyoyrjnxwgc.phishtank.rspamd.com/TXT/IN': 151.115.41.123#53
Jun  5 00:02:30  named[784]: connection refused resolving 'aycjpsgbkxs1ytn6rtrxoy68673sgwok.phishtank.rspamd.com/TXT/IN': 151.115.41.123#53
Jun  5 00:02:30  named[784]: connection refused resolving 'jd6gr4unntk836w8o95bbqhinfox9ffb.phishtank.rspamd.com/TXT/IN': 151.115.41.123#53
Jun  5 00:02:30  named[784]: connection refused resolving 'xn31a7dmym6uezxfsq8kes69fiwziayy.phishtank.rspamd.com/TXT/IN': 151.115.41.123#53

etc

$ telnet 151.115.41.123 53
Trying 151.115.41.123...
telnet: Unable to connect to remote host: Connection refused

$ telnet 88.198.198.21 53
Trying 88.198.198.21...
telnet: Unable to connect to remote host: Connection refused

vs

$  telnet 8.8.8.8 53
Trying 8.8.8.8...
Connected to 8.8.8.8.
Escape character is '^]'.

So I assume there are issues with that server at the moment?

**Comment by hunter-nl** [comment]
I've the same issue.

**Comment by moisseev** [comment]
Telnet is useless for testing DNS connectivity, as DNS typically operates over **UDP,** which Telnet does not support. So, any test results from Telnet regarding DNS connectivity would not be valid.

**Comment by hunter-nl** [comment]
<img width="1838" alt="image" src="https://github.com/rspamd/rspamd/assets/5203309/6129f206-94ab-4480-9872-385997f08f79">

**Comment by ikt** [comment]
yes that's true, but useless testing aside just looking to confirm the server was overloaded or if there was another issue

**Comment by vstakhov** [comment]
88.198.198.21 is dead - that's the problem.

**Comment by hunter-nl** [comment]
> 88.198.198.21 is dead - that's the problem.

Will it be coming back to alive or DNS updated to a server which is alive?

**Comment by vstakhov** [comment]
I've redirected this question to our dedicated soothsayers team, please hold on tight. All I can say is that automatic reset has not helped...

**Comment by vstakhov** [comment]
Resolved, thanks for reporting!
