### ISSUE TITLE
[BUG] Cannot scan message trough web UI / "local > Cannot upload data; Request failed"

### ISSUE THREAD

**Issue by nagmat84** [rspamd/rspamd#5044]
I am unable to scan a message trough the Web UI. When I enter a raw email message into the text area and press "Scan Message", the web UI shows two red boxes with "local > Cannot upload data" on the first line and "Request fail" on the second line.

The developer console of the browser shows a HTTP POST request with the raw mail message as the body for the URL `checkv2` and a HTTP response with status code 400 and JSON content `{"error":"invalid command"}`.

This happens always for any message which I enter into the text area. However, everything else on the web UI seems to work fine, including the actions "Upload HAM" and "Upload SPAM".

### Steps to Reproduce

1. Open `#scan` on the Web UI
2. Paste a message into the text box
3. Press "Scan Message"

**Expected behavior**

I expect to see the scan result

### Versions

 * OS: Gentoo
 * Rspamd: 3.8.4
 * Redis: 7.2.5
 * Apache: 2.4.59-r1

### Additional Information

```
server ~ # rspamd --version
Rspamd daemon version 3.8.4

CPU architecture x86_64; features: avx2, avx, sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
Hyperscan enabled: TRUE
Jemalloc enabled: FALSE
LuaJIT enabled: FALSE (Lua version: Lua 5.1)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE
```

**Comment by moisseev** [comment]
> * Apache: 2.4.59-r1

It seems that the issue most likely related to the reverse proxy configuration. To determine if this is the case, I suggest to check if it functions correctly with a direct connection.

**Comment by nagmat84** [comment]
How do you suggest that I test a _direct_ connection?

**Comment by aduernberger** [comment]
Without having to open the port, the easiest way would be ssh with port forward. As far as I remember, it should also work with the Windows integrated ssh. 

Rspamd on remote machine:
 - `ssh user@rspamdserver -L 11334:localhost:11334` then you should be able to connect to localhost:11334 in your browser.
Rspamd on local machine:
 - `localhost:11334` in browser.

**Comment by nagmat84** [comment]
The controller worker only listens to a UNIX socket, hence I invoked

```
ssh apache@server.my-server.tld -N  -L 11334:/var/run/rspamd/controller.sock
```

on my client and then connected with Firefox to `http://localhost:11334`. It worked!

However, there was one notable difference. If I directly connect to rspamd via local port forwarding to remote socket, then rspamd does not ask for a password. However, if connect to rspamd via the Apache reverse proxy, then rspamd asks for a password.

The configuration `/etc/rspamd/override.d/worker-controller.inc` is

```
password = "$2$<my-password-hash>"
enable_password = "$2$<my-password-hash>"
bind_socket = "/run/rspamd/controller.sock mode=0777";
```

and the relevant Apache configuration is

```
<VirtualHost *:443>
  ServerName server.my-domain.tld
  ServerAdmin admin@my-domain.tld
  DocumentRoot /var/www/my-domain.tld/server/

  SSLEngine on
  SSLCertificateFile    /etc/letsencrypt/live/server.my-domain.tld:https/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/server.my-domain.tld:https/privkey.pem
  SSLCACertificatePath  /etc/ssl/certs/

  Header always set Strict-Transport-Security "max-age=31104000; includeSubDomains"

  <FilesMatch "\.(cgi|shtml|phtml|php)$">
    SSLOptions +StdEnvVars
  </FilesMatch>
  <Directory /usr/lib/cgi-bin>
    SSLOptions +StdEnvVars
  </Directory>

  ProxyPass        /rspamd        unix:/var/run/rspamd/controller.sock|http://localhost/
  ProxyPassReverse /rspamd        unix:/var/run/rspamd/controller.sock|http://localhost/
</VirtualHost>
```

**Comment by vstakhov** [comment]
Not Rspamd issue, please learn how to set a reverse proxy.

**Comment by nagmat84** [comment]
> Not Rspamd issue

Most likely.

But it would be extremely nice, if the official Rspamd documentation would contain a section on how to setup a reverse proxy correctly. Obviously, there seems to be something "special" about the `./checkv2` URL which makes the normal way to setup a reverse proxy non-functional. It is a little bit odd that everything works except this one command. There has been a similar issue, see #4188, which could be solved by a `RewriteRule` instead of the usual `ProxyPass` directive.

So, if there is something unusual about the `./checkv2` URL (I have no clue what that could be) which requires special care, then it would be extremely nice to have that documented.
