### ISSUE TITLE
[Feature] False negative phishing hard to detect.. Need to check SPF of FROM HEADER.

### ISSUE THREAD

**Issue by flaviozluca** [rspamd/rspamd#5049]
Friends,

Pls, see if you have any ideas. More and more phishing of this type is passing through. They get sent by legit systems.

We need a way to check the FROM email address against SPF/DKIM, as per other antispam solution I know of.
[Importante  Tentativa de Login Não Autorizado - Conta Bloqueada - Banco Santander (servico@sant-ander.br) - 2024-07-10 1113.zip](https://github.com/user-attachments/files/16164091/Importante.Tentativa.de.Login.Nao.Autorizado.-.Conta.Bloqueada.-.Banco.Santander.servico%40sant-ander.br.-.2024-07-10.1113.zip)

Example

servico@sant-ander.br

santander.com.br is the legit one.

Any ideas, pls? If not a feature, a way to program this?

Thanks.

**Comment by vstakhov** [comment]
I really don't understand the problem. You **cannot** use MIME from domain for SPF checks - never, nunca, jamais - it will just break everything.
On the contrary, you must use MIME from domain for DKIM/DMARC checks.
Furthermore, you can add more restrictions by `whitelist` module (as it can also blacklist) - for both SPF/DKIM and DMARC domains.
Hence, you actually have all tooling in Rspamd for your task.

**Comment by flaviozluca** [comment]
Thanks a lot for your reply.

I dont understand.

What Im saying is, we are receiving many false negatives of phishing of this type. One more attached for you to see. I can show you many examples.

Disney+ <info@dewagg.net>

Other systems do this. They go deeper and check FROM email addresses against SPF. I know its not usual, but it helps tremendously to avoid these FN.

Another antispam system I know of is able to check from email against a list of system.

For example,  you map it. If theres DISNEY in the from name, check the from email against SPF... And if it doesnt match, score it.

Its a really cool method to solve this problem and these false negatives. quite a few causing confusion with customers.

Tks.

**Comment by flaviozluca** [comment]
the sample.
[Failed to renew your subscription - Disney+ (info@dewagg.net) - 2024-07-08 2130.zip](https://github.com/user-attachments/files/16165122/Failed.to.renew.your.subscription.-.Disney%2B.info%40dewagg.net.-.2024-07-08.2130.zip)

**Comment by vstakhov** [comment]
> Other systems do this. They go deeper and check FROM email addresses against SPF. I know its not usual, but it helps tremendously to avoid these FN.

Then these systems are simply broken. I will not add something that is strongly against RFC and basic sanity. Apparently, there is DMARC that is intended to resolve issues like that.

**Comment by flaviozluca** [comment]
No, theyre not broken. They do a great job at detection. You dont need to follow RFC to score something... Its just a test, as many others that we have, to add up the score. A great idea imho.

DMARC isnt something that has caught on well. Proof is that its not fixing these false negatives.

It would be need to have a solution for these spams. Like I said, I can send you many samples of false negatives...

**Comment by flaviozluca** [comment]
so idea is, my colleague with his antispam does this.

check SPF and DKIM of from email header and if any of the 2 succeed, accept, or else score. or else, too many FP.

**Comment by flaviozluca** [comment]
So this one was refused, right? Can you take a look at many false negatives, pls?

**Comment by flaviozluca** [comment]
so idea is, my colleague with his antispam does this.

check SPF and DKIM of from email header and if any of the 2 succeed, accept, or else score. or else, too many FP. It's not going to reject, just another test to score. A really interesting, diferentiated test...

Notice, DMARC wont work, as these cases, they use a totally different FROM email address, understand what I mean?

Can you take a look at many false negatives, pls? Attached.

Thanks a lot!
[samples.zip](https://github.com/user-attachments/files/16177043/samples.zip)
