### ISSUE TITLE
[BUG] APT dependencies problem

### ISSUE THREAD

**Issue by t0rzz** [rspamd/rspamd#5057]
hey guys,
this is pretty easy issue.

`Unsatisfied dependencies:
 rspamd : Depends: libbinutils (< 2.40.1) but 2.42.50.20240710-1 is to be installed
`

I am running Debian Trixie.
Is there a testing version or an updated repository for rspamd?

Thank you!

**Comment by fatalbanana** [comment]
Builds haven't been rolling for Debian sid for some years - I suppose it's probably intentional.

You'd need to [build rspamd](https://rspamd.com/downloads.html#build-process) or [use docker](https://rspamd.com/downloads.html#docker).
