### ISSUE TITLE
Description of Symbols in rspamc

### ISSUE THREAD

**Issue by ameagle** [rspamd/rspamd#506]
Hello!
Is it possible to add description's symbol to rspamc for scan commands?
rspamc spam2.txt
Results for file: spam2.txt (0.205 seconds)
[Metric: default]
Spam: true
Score: 6.1 / 5.00
Action: reject
Symbol: BAYES_SPAM (4.00) [100.00%]  
Symbol: FORGED_OUTLOOK_TAGS (2.1)

I add this information to the message,in my header, user needs to know what it is
I'm using spamassassin now, it shows description.

spamc -t 180  -U /var/spool/spamd/spamd  < /var/qm/working/new/0391111111
1.2/3.5
Content analysis details:   (1.2 points, 3.5 required)
 pts rule name              description
/---- ---------------------- --------------------------------------------------/
 1.0 FREEMAIL_FROM          Sender email is commonly abused enduser mail provider
                            (fat[at]mail.ru)
-0.5 SPF_HELO_PASS          SPF: HELO matches SPF record
 0.7 HTML_TAG_BALANCE_BODY  BODY: HTML has unbalanced "body" tags
 0.0 HTML_MESSAGE           BODY: HTML included in message
 0.0 T_DKIM_INVALID         DKIM-Signature header exists but is not valid

I really need it .

**Comment by vstakhov** [comment]
There are no obstacles to add this but rmilter still uses legacy protocol (blame me for that!) and I need to rework this part of the code first.

**Comment by mozzan** [comment]
Follow the discussion above, can rspamd rbl description add what ip or domain is a black list?

**Comment by fatalbanana** [comment]
`surbl` module does it. `rbl` module could but currently does not.

**Comment by fatalbanana** [comment]
It looks like we have everything we need currently short of `rspamc` displaying `description` associated with the symbol(s) (as found in the protocol response). Perhaps we could add some command-line flag which would display these alongside the corresponding symbols.
