### ISSUE TITLE
[Feature] Phishing FP

### ISSUE THREAD

**Issue by flaviozluca** [rspamd/rspamd#5060]
Friends,

Can you kindly check if these FP are normal? Very legit emails, FP due to the links of these popular voting systems.

Thanks.
[phishfp.zip](https://github.com/user-attachments/files/16273177/phishfp.zip)

**Comment by fatalbanana** [comment]
They are normal, it works [as it's supposed to](https://rspamd.com/doc/modules/phishing.html#principles-of-phishing-detection).

**Comment by flaviozluca** [comment]
Thanks, Andrew. Can you detail a bit more what it does, why it was caught? I can try to tell the legit sender.

No way to avoid these FP or lower the score? They are very useful, I understand, right?

Tks.
