### ISSUE TITLE
[BUG] Conflicting behaviour for 'm' suffix

### ISSUE THREAD

**Issue by japc** [rspamd/rspamd#5064]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

The m suffix for numeric values doesn't behave as expected for time values.

Taking as example the url redirector documentation (https://rspamd.com/doc/modules/url_redirector.html).

The expire on the documentation is

`expire = 1d
`

which leads to the impression that all parse_time_interval() values (s, m, h, d, w, y) can be used, but the m ends up not being properly expanded as minutes but as millions. 

It seems to happen because the numeric value is processed by dehumanize_number() and parse_time_interval() has no effect.

Both parsers define the 'm' suffix. The expected end result comes from the setting being suffixed, not anywhere else (expire = time, m should be minutes, count = number, m should be millions).

Only happens for 'm' as all other suffixes are distinct between number and time.

Tried to fix it with a rule_schema = ts.shape{} but lua_util.override_defaults() returns the value processed and the transform does nothing.

Setting expire to a string value "fixes" the behaviour for the time value:

`expire = 1m
`

### Steps to Reproduce

Define a expire = 3m.

**Expected behavior**

The expire should be 180 seconds but is 3000000.

### Versions

Rspamd daemon version 3.9.0

```
CPU architecture x86_64; features: avx2, avx, sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
Hyperscan enabled: TRUE
Jemalloc enabled: FALSE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.0-beta3)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE
```

(git on commit https://github.com/rspamd/rspamd/commit/d18d5f811003554d3cdecdc1ffccf96b4ae569ba)

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by vstakhov** [comment]
Please read the docs: https://github.com/vstakhov/libucl?tab=readme-ov-file#convenient-numbers-and-booleans

It should be `min` not `m`.
