### ISSUE TITLE
[BUG] GPT Module doesn't support new gpt-4o-mini

### ISSUE THREAD

**Issue by alex081512** [rspamd/rspamd#5067]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
OpenAI launched the new gpt-4o-mini api, which is more affordable then gpt-4o and (maybe) better then gpt-3.5-turbo. Unfortunately every request generates following log entry and no symbol is added:

> cannot parse JSON gpt reply: error while parsing <unknown>: line: 1, column: 0 - 'key must begin with a letter', character: '`'

### Steps to Reproduce

1. Enable the gpt module
2. Set `model = "gpt-4o-mini";`

**Expected behavior**
The new api could be used. Btw, It's not really clear which api versions are supported.

### Versions

Rspamd daemon version 3.9.0
CPU architecture x86_64

**Comment by vstakhov** [comment]
I think it is now done. I will release 3.9.1 soon.

**Comment by alex081512** [comment]
It's working with 3.9.1, thx!
