### ISSUE TITLE
[BUG] GPT module also sent to OpenAI when it is already obviously SPAM/HAM.

### ISSUE THREAD

**Issue by hunter-nl** [rspamd/rspamd#5087]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
The default_condition function decides to process messages at OpenAI when it is already determined as SPAM/HAM. According to the comments in this Lua function, it should skip processing by GPT module.
```
local function default_condition(task)
  -- Check result
  -- 1) Skip passthrough
  -- 2) Skip already decided as spam
  -- 3) Skip already decided as ham
  local result = task:get_metric_result()
  if result then
    if result.passthrough then
      return false, 'passthrough'
    end
    local score = result.score
    local action = result.action

    if action == 'reject' and result.npositive > 1 then
      return true, 'already decided as spam'
    end

    if action == 'no action' and score < 0 then
      return true, 'negative score, already decided as ham'
    end
  end
```
The last 2 return lines in the code above, should be false, not true.

### Steps to Reproduce
Activate GPT module. HAM and SPAM messages are processed by GPT at OpenAI.

**Expected behavior**
It should skip SPAM/HAM messages to be processed. Unnecessary costs to process these messages by OpenAI.

### Versions
Rspamd daemon version 3.9.1

CPU architecture x86_64; features: avx2, avx, sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
Hyperscan enabled: TRUE
Jemalloc enabled: TRUE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.1720049189)
ASAN enabled: FALSE
BLAS enabled: TRUE
Fasttext enabled: TRUE

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by vstakhov** [comment]
Already fixed
