### ISSUE TITLE
How to actually query this filter as a person with a life?

### ISSUE THREAD

**Issue by Sainan** [rspamd/rspamd#5098]
Hello, we send account-related emails to our users, however it seems sometimes we get greeted with this nice message:
```
[6.801s] mailsec.protonmail.ch:25 --> 554 5.7.1 rejected by rspamd filter
```
Now, I've tried using rspamd.com, but there is no "lookup". I've submitted our details into the "removal" section, but it seems that did not actually resolve this issue. Do you just not care about false-positives, or what?

**Comment by Sainan** [comment]
I think it's a justified complaint; "rejected by rspamd filter" is a useless message, and rspamd.com is not much more useful.

**Comment by mkokoszkiewicz** [comment]
@Sainan no - it is not. It's the github project of the software. The developers have no power over the people who are using it on their mail servers.  Your complaining is like blaming the creators of Microsoft Outlook because someone sent you an ugly e-mail.

**Comment by Sainan** [comment]
Closed? You still haven't fixed the rspamd.com website. Useless as ever.
