### ISSUE TITLE
Provide prebuilt packages for ARM.

### ISSUE THREAD

**Issue by t-8ch** [rspamd/rspamd#510]
It would be nice to have prebuilt packages Debian armhf.

**Comment by Aloha911** [comment]
Is that possible? I'm interested too and there is still no response at the moment.

**Comment by vstakhov** [comment]
Cmake is a bit problematic for cross builds. There is a hack described here: https://github.com/vstakhov/rspamd/issues/332 but I have no experiences with debian cross builds I'm afraid...

**Comment by t-8ch** [comment]
It built fine on a native ARM machine from scaleway.com.
Unfortunately they don't allow new signups at the moment and I guess you don't want to build on one of my machines. I could invite you and as soon as there are new signups possible you could create native armhf buildhost.

**Comment by vstakhov** [comment]
I have scaleway access. I don't know how to use it in my build scripts: https://github.com/vstakhov/rspamd-build-scripts

**Comment by t-8ch** [comment]
Hm, what about your project on build.opensuse.org?
It seems to work (for i586 and x86_64), could you try to enable armv7?
I'll ask at work for more tips for Debian packaging...

**Comment by pboesch** [comment]
Yunohost provides a rspamd package for debian jessie arm : http://repo.yunohost.org/debian

**Comment by neuhaus** [comment]
I second this request, we could use official packages if a user wants to install sovereign on, say, a Raspberry Pi 3. See also sovereign#704

**Comment by Nizzlay** [comment]
Any update on this? 

I'm using Yunohost repo now, but it's stuck on 1.3.5-1

**Comment by neuhaus** [comment]
Also Yunohost doesn't offer packages for debian stretch :-1: which makes this issue even more important

**Comment by alexAubin** [comment]
@neuhaus Uh ? We do for armhf and armel, and more recently for arm64 since we managed to solve/workaround with https://github.com/vstakhov/rspamd/issues/2202#issuecomment-401545304

But YunoHost doesn't really aim to be a build provider, on the contrary :sweat_smile:

**Comment by neuhaus** [comment]
@alexAubin when I wrote my comment 10 days ago, the file http://repo.yunohost.org/debian/dists/jessie/stable/binary-armhf/Packages was 0 bytes long. Glad to see the packages are available now.

**Comment by helmut72** [comment]
rspamd runs on Raspberry using Alpine Linux:
https://pkgs.alpinelinux.org/packages?name=rspamd&branch=v3.9&arch=armhf
(untested)

Or running in a Docker Container (built with Alpine) if someone want to use Raspbian Linux.
(tested, works)

But a officical repository for Raspbian would be nice.

**Comment by TCB13** [comment]
+1 on this since I can't manage to get it to compile :P. https://github.com/rspamd/rspamd/issues/2953

**Comment by helmut72** [comment]
Should be reopened as there are many ARM boards out there and also Apple M1 CPU. Please rethink about providing at least arm64/aarch64 packages. Thank you.
