### ISSUE TITLE
Timeouts after ppp reconnect

### ISSUE THREAD

**Issue by github-k8n** [rspamd/rspamd#512]
I am running rspamd at home with a DSL connection that changes the IP every 24 hours.
As soon as the connection disconnects and reconnects, rspamd is running into timeouts (8 seconds), whereas it was around 1 second before.

This is on Gentoo with libevent-2.1.5 so it is not related to bug #135 
Both normal and controller are only bound to the localhost interface.

It also doesn't seem to be DNS related as it is getting RBL results back in time.

I will attach the debug log from a message that is passing through after the ppp interface was restarted and which shows the issue.

**Comment by github-k8n** [comment]
Debug log showing the issue
[issue.txt](https://github.com/vstakhov/rspamd/files/113623/issue.txt)

**Comment by vstakhov** [comment]
As far as I see, that's DNS issue. So I clearly can see a request that has been fired but never ever replied. That could happen as librdns uses internal pool of **binded** sockets which could cause issues on IP change. I'll make further investigations soon.

**Comment by github-k8n** [comment]
Some further information regarding DNS: The first two entries for my nameservers in resolv.conf should point to a nameserver on the same server, running on the internal network and should stay reachable (both ipv4 (192.168.0.x) and ipv6 (unique local address)) even when ppp was restarted.

**Comment by github-k8n** [comment]
regarding librdns, is there a way to point it to my nameserver instead of letting it resolve on its own?

**Comment by vstakhov** [comment]
It uses nameservers. By default, rspamd reads `/etc/resolv.conf` but you can specify custom servers as well: https://rspamd.com/doc/configuration/options.html

**Comment by github-k8n** [comment]
How do I enter an IPv6 address there?
When I enter an IPv6 address it just stops at the first colon and gives me
`2016-02-02T11:34:32+01:00 router rspamd[2177]: <hsbn7u>; cfg; dns_resolver_init: cannot parse ip address of nameserver: fd5e`

When using the brackets around the IPv6 address like in [xxxx:xxxx::xxxx] i just get the same error with
`2016-02-02T11:39:42+01:00 router rspamd[2522]: <hsbn7u>; cfg; dns_resolver_init: cannot parse ip address of nameserver: [fd5e`

**Comment by github-k8n** [comment]
Ok, I just entered ONLY my local nameserver IPv4 address in the config and it seems to work after a reconnect. 
In my resolv.conf I have one IPv4 address and 3 IPv6 addresses. How does rspamd parse the file? Does it use all of them with the same weight?

**Comment by bax-** [comment]
I seem to have the same problem with the new 1.6.0 version.

I have two IPv4 and two IPv6 addresses in my resolve.conf and I'm getting parsing errors.
When I manually add only the two IPv4 DNS addresses to Rspamd it works again.
If I then also add the two IPv6 addresses it only works if I put them in brackets.

**Comment by vstakhov** [comment]
I've seen no issues in parsing of the IPv6 nameservers in the recent Rspamd. 

(2) will not be fixed/changed ever: forget all hopes as you propose wrong things that do not play well with any performance considerations.

**Comment by github-k8n** [comment]
So regarding (1), is the IPv6 nameserver parsing dependend on LUA?
(using Gentoo here where LUA version is at 5.1.5)
Just wondering why it wouldn't accept any IPv6 nameserver entries in options.inc
(Were you talking about the rspamd config files or about /etc/resolv.conf when you said you see no issues?)

**Comment by github-k8n** [comment]
If I read https://rspamd.com/doc/configuration/options.html correctly and considering the output I got it seems that the namserver option does just use the colons for separating ports and priority, thus misinterpreting any specified IPv6 address. Not sure what the best way would be to address that while staying backwards compatible... maybe a nameserver_v6 option?

**Comment by vstakhov** [comment]
You can use square braces to fence IPv6 address, like `[fd00::ca0e:14ff:fef8:7ba2]`

**Comment by github-k8n** [comment]
Ah, ok, so the IPv6 nameserver entry issue was fixed (e.g. brackets now work), nice .. (it's been a while, I was using a local IPv4 address since then, so not even sure if the original issue still occurs, using a different network topology now..)

As there is a workaround (setting fixed nameserver), I'll close this issue.

And a BIG thanks for making email usable with rspamd !
