### ISSUE TITLE
[BUG] name/id breaks settings.conf

### ISSUE THREAD

**Issue by rseffner** [rspamd/rspamd#5138]
### Prerequisites
**Describe the bug**
Using "frx_0ba31014ba51a9fa2916fb3dd646fde8_rcpt" as name and id inside settings.conf results in 

`2024-09-12 12:48:59 #1858632(main) <pk6rhc>; cfg; rspamd_lua_run_config_post_init: cannot run config post init script: /usr/share/rspamd/lualib/lua_settings.lua:174: bad argument #1 to 'update' (string expected, got table); trace: [1]:{[C]:-1 - update [C]}; [2]:{/usr/share/rspamd/lualib/lua_settings.lua:174 - numeric_settings_id [Lua]}; [3]:{/usr/share/rspamd/lualib/lua_settings.lua:236 - register_settings_id [Lua]}; [4]:{/usr/share/rspamd/plugins/settings.lua:1152 - process_setting_elt [Lua]}; [5]:{/usr/share/rspamd/plugins/settings.lua:1215 - fun [Lua]}; [6]:{/usr/share/rspamd/lualib/fun.lua:34 - call_if_not_empty [Lua]}; [7]:{/usr/share/rspamd/lualib/fun.lua:192 - for_each [Lua]}; [8]:{/usr/share/rspamd/plugins/settings.lua:1207 - process_settings_table [Lua]}; [9]:{/usr/share/rspamd/plugins/settings.lua:1429 - <unknown> [Lua]};; priority = 100`

Don't ask how long it takes to find out of about 1.500 setting sections.

### Steps to Reproduce
1. e.g. create an apply-action block for seom rcpt in settings.conf or include file with name nad id as described
2. service rspamd reload and check log files

**Expected behavior**
As described in doku any combination of alphanumeric chars should be possible.

### Versions
root@ns1:/etc/rspamd/local.d# rspamd --version
Rspamd daemon version 3.9.1
CPU architecture x86_64; features: avx2, avx, sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
Hyperscan enabled: TRUE
Jemalloc enabled: TRUE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.1720049189)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE

vendor_id       : GenuineIntel
cpu family      : 6
model           : 158
model name      : Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

debian 12 bookworm amd64

**Comment by rseffner** [comment]
No duplicate.
Log says: "...(string expected, got table)..." - maybe some conversion or interpretation of the MD5 part between "frx_" and "_rcpt"?
Its reproducable here.

**Comment by fatalbanana** [comment]
Please provide a full configuration which could demonstrate the issue

**Comment by rseffner** [comment]
The error ist back again with manipulated name/id strings - so I think the reason seems to be something else.
Error is the same "... string expected, got table ..." at reading settings.conf and included files.

`2024-09-14 10:30:21 #434119(main) <ztm5zk>; cfg; rspamd_lua_run_config_post_init: cannot run config post init script: /usr/share/rspamd/lualib/lua_settings.lua:174: bad argument #1 to 'update' (string expected, got table); trace: [1]:{[C]:-1 - update [C]}; [2]:{/usr/share/rspamd/lualib/lua_settings.lua:174 - numeric_settings_id [Lua]}; [3]:{/usr/share/rspamd/lualib/lua_settings.lua:236 - register_settings_id [Lua]}; [4]:{/usr/share/rspamd/plugins/settings.lua:1152 - process_setting_elt [Lua]}; [5]:{/usr/share/rspamd/plugins/settings.lua:1215 - fun [Lua]}; [6]:{/usr/share/rspamd/lualib/fun.lua:34 - call_if_not_empty [Lua]}; [7]:{/usr/share/rspamd/lualib/fun.lua:192 - for_each [Lua]}; [8]:{/usr/share/rspamd/plugins/settings.lua:1207 - process_settings_table [Lua]}; [9]:{/usr/share/rspamd/plugins/settings.lua:1429 - <unknown> [Lua]};; priority = 100
`

`ns1:~# rspamadm configtest
syntax OK
`

rspamadm configdump attached
[rspamd.config.gz](https://github.com/user-attachments/files/17001634/rspamd.config.gz)

thanks for any help

**Comment by rseffner** [comment]
If I comment out the following part of settings.conf, the error is gone:

`# Email: @ptz-prototypen.de
frx_0ba31014ba51a9fa2916fb3dd646fde8Z_rcpt {
       id = "frx_0ba31014ba51a9fa2916fb3dd646fde8Z_rcpt";
       priority = low;
       rcpt = "@ptz-prototypen.de";
       apply {
               actions {
                       "add header" = 7;
                       rewrite_subject = 7;
                       reject = 14;
               }
       }
}
frx_0ba31014ba51a9fa2916fb3dd646fde8Z_from {
       id = "frx_0ba31014ba51a9fa2916fb3dd646fde8Z_from";
       priority = low;
       from = "@ptz-prototypen.de";
       apply {
               actions {
                       "add header" = 7;
                       rewrite_subject = 7;
                       reject = 14;
               }
       }
}
`

There must be some magic inside "frx_0ba31014ba51a9fa2916fb3dd646fde8Z_rcpt". The middle part is PHP md5() of "@ptz-prototypen.de".

**Comment by rseffner** [comment]
If I transfer this config part to another Server A, the error ist reproducable. If I copy to a third Server B, there is no error.
Now I have to figure out what equals at Source Server and Server A but differs to Server B.

**Comment by fatalbanana** [comment]
It looks like some settings are duplicated; they might be defined in different places & merged:

```
    frx_0ba31014ba51a9fa2916fb3dd646fde8Z_rcpt {
        priority = "low";
        priority = "low";
        id = "frx_0ba31014ba51a9fa2916fb3dd646fde8Z_rcpt";
        id = "frx_0ba31014ba51a9fa2916fb3dd646fde8Z_rcpt";
```

**Comment by vstakhov** [comment]
Exactly what I've said in the first comment.

**Comment by rseffner** [comment]
Now I can see it also - but only in "configdump" not "settings.conf". I've to check all includes an configdirs for the double. Thanks. This can be closed, I think.

**Comment by rseffner** [comment]
No bug. Special circumstances. Sorry.
