### ISSUE TITLE
[BUG] http://rspamd.com/rpm/rspamd.asc is 404

### ISSUE THREAD

**Issue by DSpeichert** [rspamd/rspamd#5168]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

The CentOS repository links to non-existent gpgkey: http://rspamd.com/rpm/rspamd.asc

### Steps to Reproduce

1. Install https://rspamd.com/rpm-stable/centos-9/rspamd.repo
2. dnf install rspamd
3. Error: Failed to retrieve GPG key for repo 'rspamd': Status code: 404 for https://rspamd.com/rpm/rspamd.asc (IP: 135.181.136.158)
failed to install rspamd RPM package

**Expected behavior**

Key needs to be available.

### Versions

N/A

### Additional Information

OS is AlmaLinux 9

**Comment by anatolinicolae** [comment]
Experiencing the same behaviour here.
```
[root@web2 playbooks]# curl -I https://rspamd.com/rpm/rspamd.asc
HTTP/1.1 404 Not Found
Server: nginx
Date: Tue, 01 Oct 2024 15:22:53 GMT
Content-Type: text/html
Content-Length: 146
Connection: keep-alive
```
