### ISSUE TITLE
[BUG] Extraction of 'Envelope From' and 'Envelope To' values for symbol processing fails with ARM64 Rspamd 3.10.0

### ISSUE THREAD

**Issue by johnheenan** [rspamd/rspamd#5172]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * [x] Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * [x] Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * [ ] Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * [ ] Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * [ ] Checked that there is not already an experimental package or master branch

**Describe the bug**
With upgrade on Debian Bookworm ARM64 to Rspamd 3.10.0, every single email now has an added spam score of 2 due to triggering a FROM_INVALID match. 

In Rspamd history web view, the value of '[Envelope From]' is always '[unknown]' and the value of '[Envelope To]' is always '[]'.

The output of any normal email to a `/checkv2` command shows:
```
curl -s --data-binary @- http://localhost:11333/checkv2 < file.eml| jq ' .symbols | .FROM_EQ_ENVFROM, .FROM_INVALID'
null
{
  "name": "FROM_INVALID",
  "score": 2,
  "metric_score": 2,
  "description": "From header does not have a valid format"
}
```

Investigation of logs with milter debug enabled show no change to values of mail_addr and rcpt_addr macros passed into milter from postfix.

Emails can be correctly read by email clients but have invalid spam score added (+2).

### Steps to Reproduce

1. Upgrade to rspamd 3.10.0 on an ARM64 server
2. Receive any email

**Expected behavior**
Normal emails processed with valid record of  [Envelope From], [Envelope To] values and valid symbol processing result with  spam score not invalidly increased..

Same result as with version 3.9.1 for ARM64 and for 3.10.0 for x86_64 from command with any normal email:
```
curl -s --data-binary @- http://localhost:11333/checkv2 < file.eml| jq ' .symbols | .FROM_EQ_ENVFROM, .FROM_INVALID'
{
  "name": "FROM_EQ_ENVFROM",
  "score": 0,
  "metric_score": 0,
  "description": "From address is the same as the envelope"
}
null
```

### Versions

```
rspamd -v
Rspamd daemon version 3.10.0

CPU architecture ARM64; features: 
Hyperscan enabled: TRUE
Jemalloc enabled: FALSE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.1725453128)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE
```

OS: Debian Linux 12 (Bookworm) for aaarch64
```
cat /etc/debian_version 
12.7
```

Kernel: Linux 6.1.0-23-arm64 on aarch64

VPS hosted

**Comment by johnheenan** [comment]
While the following is not directly relevant to the issue, it is relevant as a reference to myself, both for this issue and for Rspamd in general.

I have since found I could have extracted the same data as above two other different ways: with rspamc and with a regular curl https request over the internet. These are shown below.

I have also included this information in a table of workers below 

### Three different ways to extract symbol data for an email

#### With http curl to localhost path /checkv2 on ports 11333 and 11334
```
curl -s --data-binary @- http://localhost:11333/checkv2 < file.eml| jq ' .symbols | .FROM_EQ_ENVFROM, .FROM_INVALID'
```

#### With rspamc
```
rspamc -j file.eml | jq ' .symbols | .FROM_EQ_ENVFROM, .FROM_INVALID'
```

#### With https curl on internet
```
password="somepassword"
rspamd_site="example.com"
curl -s "https://$rspamd_site/checkv2" \
  -H "password: $password" \
  --data-binary @- <file.eml | jq ' .symbols | .FROM_EQ_ENVFROM, .FROM_INVALID'
```


###  Table of http workers, ports, purpose, access methods and what supports /checkv2

| http Workers  | Port    | Other Access      | /checkv2 | Purpose
| --------      | ------- | --------          | -------  | -------
| scanner       | 11333   | rspamc            | yes      | scan
| controller    | 11334   | rspamc, internet  | yes      | webui, learning, manage statistics
| rspamd_proxy  | 11332   |                   | no       | milter, small scan
| fuzzy         | 11335   |                   | no       | fuzzy storage using sqlite

The main rspamd process supervises the worker processes. There is an additional hs_helper process for hyperscanning (?).

Redis cache server used for key-value storage for various modules, including bayes statistics tokens

Redis server can be split into three three redis servers with two acting as slave servers to master bayes and fuzzy redis replication servers

**Comment by Nopel2020** [comment]
I am seeing the exact same on Gentoo on arm64 with rspamd 3.10.0.

**Comment by Grokenberger** [comment]
Just to prevent this thread from being closed automatically: Same behavior on ArchLinuxArm's aarch64 architecture, no issue on x86_64.

**Comment by johnheenan** [comment]
> Ok, so it's not only milter but also an http scan, right? If so, it's very interesting.

Yes. I pointedly went out of the way to factor out milter as an issue:
> Investigation of logs with milter debug enabled show no change to values of mail_addr and rcpt_addr macros passed into milter from postfix.

There is only one known way to reproduce the issue and it is 100% reliable no matter how mail is deliverd to the scanner (milter or directly to scanner with http or with rpsamc): upgrade to 3.10.0 on ARM64.

I have had a look at the list of changes from 3.9.1 to 3.10.0 and cannot identify a single listed change as possibly being repsonsible. The last rpsamd commit that mention ARM64 was in 2022. Three separate Linux distos have the problem with ARM64 and 3.10.0 (Debian, Gentoo and Arch). Entering luajit and ARM64 in github search produces nothing recent,

Don't know if following is relevant.

The only relevant information may be that upgraded LuaJIT 2.1.1725453128 may have a relevant bug in ARM64 but not in x86_64.

**Not OK:**
rspamd -v
Rspamd daemon version 3.10.0
CPU architecture ARM64; features: 
Hyperscan enabled: TRUE
Jemalloc enabled: FALSE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.1725453128)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE

**OK:**
rspamd -v
Rspamd daemon version 3.9.1
CPU architecture ARM64; features: 
Hyperscan enabled: TRUE
Jemalloc enabled: FALSE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.1720049189)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE

**OK:**
rspamd -v
Rspamd daemon version 3.10.0
CPU architecture x86_64; features: avx2, avx, sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
Hyperscan enabled: TRUE
Jemalloc enabled: TRUE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.1725453128)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE

**Comment by Nopel2020** [comment]
Just to add to the datapoints: on my Gentoo system I don't have LuaJIT installed, only Lua 5.1.5.

**Comment by johnheenan** [comment]
Is it possible there is an issue with a core library, such as glib2, that is currently in ARM64  but has not made its way into x86_64 yet?

openresty have their own branch of luajit. Open issue at
[Some test fails on Linux Debian 12 (amd64|arm64) with v2.1-20240626](https://github.com/openresty/luajit2/issues/238)
It points to an updated libc lacking libpthtreads.

Can't find anything relevant in other investgations:

luajit has a mirror on github. There were three commits mentioning ARM64 in August as shown at
https://github.com/search?q=repo%3ALuaJIT%2FLuaJIT+ARM64&type=commits&p=1

They were all to do with assembly language modifcations for floating point. Hardly seems relevant.

Searching PCR source code does not look encouraging either:
https://github.com/search?q=repo%3APCRE2Project%2Fpcre2+ARM64&type=commits

**Comment by johnheenan** [comment]
I have replaced 3.9.1 with the 3.10.1 rspamd-asan build. It is just something else to eliminate in case there is a memory use issue.

`rspamd -v` says asan is not enabled

How do I enable asan?

```
rspamd -v
Rspamd daemon version 3.10.0

CPU architecture ARM64; features: 
Hyperscan enabled: TRUE
Jemalloc enabled: FALSE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.1725453128)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE
```

Proof rspamd-asan is installed:
```
apt search rspamd-asan
Sorting... Done
Full Text Search... Done
rspamd-asan/unknown,now 3.10.0-1~eab554ec1~bookworm arm64 [installed]
  Rapid spam filtering system

rspamd-asan-dbg/unknown 3.10.0-1~eab554ec1~bookworm arm64
  debugging symbols for rspamd-asan
```

**Comment by biztems** [comment]
Same bug happening here on Ubuntu 22.04.5 LTS. Had to disable FROM_INVALID entirely.

```
❯ rspamd -v
Rspamd daemon version 3.10.0

CPU architecture ARM64; features:
Hyperscan enabled: TRUE
Jemalloc enabled: FALSE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.1725453128)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE
```

```
liblua5.1-0/jammy,now 5.1.5-8.1build4 arm64 [installed,automatic]
  Shared library for the Lua interpreter version 5.1

liblua5.3-0/jammy,now 5.3.6-1build1 arm64 [installed,automatic]
  Shared library for the Lua interpreter version 5.3
```

```
ii  libglib2.0-0:arm64               2.72.4-0ubuntu2.3                       arm64        GLib library of C routines
ii  libglib2.0-bin                   2.72.4-0ubuntu2.3                       arm64        Programs for the GLib library
ii  libglib2.0-data                  2.72.4-0ubuntu2.3                       all          Common files for GLib library
ii  libpackagekit-glib2-18:arm64     1.2.5-2ubuntu2                          arm64        Library for accessing PackageKit using GLib
ii  libpcre2-8-0:arm64               10.39-3ubuntu0.1                        arm64        New Perl Compatible Regular Expression Library- 8 bit runtime files
ii  libpcre3:arm64                   2:8.39-13ubuntu0.22.04.1                arm64        Old Perl 5 Compatible Regular Expression Library - runtime files
ii  postfix-pcre                     3.6.4-1ubuntu1.3                        arm64        PCRE map support for Postfix
```

**Comment by johnheenan** [comment]
Thanks @vstakhov 

Confirmed fixed using on Debian 12 on ARM64 using buld from source as documented on https://rspamd.com/downloads.html#build-rspamd-from-the-sources

Going though my ~/.bash_history , the library install was something like, with sudo removed:
```
apt install build-essential
apt install cmake
apt install libvectorscan5
apt install ragel
apt install pkg-config
apt install libluajit-5.1-2
apt install libluajit-5.1-dev
apt install libglib2.0-dev
apt install libsqlite3-dev
apt install libicu-dev
apt install libssl-dev
apt install libsodium-dev
apt install libarchive-dev
apt install libvectorscan-dev
```
Build instruction for ARM64:
```
 cmake ../rspamd -DENABLE_VECTORSCAN=ON -DENABLE_LUAJIT=ON -DCMAKE_BUILD_TYPE=RelWithDebuginfo
```
Start servers after conventional default install into /usr/loca/bin/
```
/usr/local/bin/rspamd -u _rspamd -c /etc//rspamd/rspamd.conf -f
```

Using github master with fix on ARM64:
```
rspamd -v
Rspamd daemon version 3.11.0

CPU architecture ARM64; features: 
Hyperscan enabled: TRUE
Jemalloc enabled: FALSE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.0-beta3)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE
```

Fix confirmed:
```
/usr/local/bin/rspamc -j file.eml | jq ' .symbols | .FROM_EQ_ENVFROM, .FROM_INVALID'
{
  "name": "FROM_EQ_ENVFROM",
  "score": 0,
  "metric_score": 0,
  "description": "From address is the same as the envelope"
}
null
```

Issue is closed but will leave issue open for a few days in case anyone wants to comments.

**Comment by johnheenan** [comment]
There is a new release (3.10.1) that includes the fix and there is an update to this version for Debian and Ubuntu.

Closing issue.
