### ISSUE TITLE
[BUG] false positiv SPAM due to RECEIVED_SPAMHAUS_PBL and authenticated SMTP 

### ISSUE THREAD

**Issue by degenkolb** [rspamd/rspamd#5185]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

So I'm not sure if this is a bug or a feature request or my stupidity but I try to describe as best as I can whats the problem. 

First of all thanks for the wonderful product that is rspamd. You keep my and my families inbox mostly clean of spam. 
I use a rspamd 3.9.1 as part of a mailcow installation https://github.com/mailcow/mailcow-dockerized

Lately near 100% of false positives in our SPAM folders are du to hits in RECEIVED_SPAMHAUS_PBL, RCVD_UNAUTH_PBL and BAD_REP_POLICIES. 
When I check the headers of this mails I find the following first Received header.

`Received: from dslb-XXXX.pools.vodafone-ip.de ([XX.YY.ZZ.252] helo=XXXX); authenticated
    by XXXX.XXXX.hosteurope.de running ExIM with esmtpa
    id 1sy7Tq-0005rZ-Un; Tue, 08 Oct 2024 12:30:17 +0200`

This mail was clearly send from a german Vodafone DSL line via authenticated SMTP to the server at XXXX.XXXX.hosteurope.de which put it forward to my mail server. 

In the X-Spamd-Result I find the following 

`RECEIVED_SPAMHAUS_PBL(4.00)[XX.YY.ZZ.252:received];`

with the IP from the DSL line. Which in conjunction with RCVD_UNAUTH_PBL, BAD_REP_POLICIES and one more check this puts those mails over the SPAM threshold. 
However the Received Header states this was authenticated SMTP so no public relay. 

Is it possible to handle this more graceful? Can you change the blacklist check to ignore landlines if the are authenticated?
Is there already some kind of configuration I can set to achieve this? I check the documentation but could not find something in https://rspamd.com/doc/modules/rbl.html

### Steps to Reproduce

1. Receive mail from server with landline IP in a Receive Header
2. rspamd checks all Receive Headers against DNSBL
3. land line IP triggers RECEIVED_SPAMHAUS_PBL and some more checks although it was authenticated SMTP
4. Mail lands in SPAM folder

**Expected behavior**

Better handling for mails send vie authenticated SMTP from a land line, if possible.

### Versions
rspamd in docker as part of a https://github.com/mailcow/mailcow-dockerized installation on last release https://github.com/mailcow/mailcow-dockerized/releases/tag/2024-08a
rspamd webinterface says its a version 3.9.1

### Additional Information

Thanks for your time.

**Comment by fatalbanana** [comment]
Default & recommended score for `RECEIVED_SPAMHAUS_PBL` is zero.

Messages from 'local' IPs and authenticated users are not subject to this check but I suppose neither is true.

**Comment by degenkolb** [comment]
Hi, 

thanks for your response. 

I don't know where the score of 4 comes from. 
Maybe Mailcow added it in or maybe I did but I can't remember playing around with the scores. 

I will set it to 0 as recommended but what is the point in having a check like that if the recommended score is 0?

Closing the bug since I don't think there will be another solution.
