### ISSUE TITLE
[BUG] Mail tagged as spam incorrectly because of SPF fail, while IP is present in SPF record

### ISSUE THREAD

**Issue by hapklaar** [rspamd/rspamd#5204]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
All mail from amazon.nl is tagged as spam because of SPF fail, when the sending IP is actually an allowed sending IP. Various sending IP's were observed in multiple mails, all were considered a failure. This seems to be the only sender experiencing this issue on my system.

According to the header and rspamd history:

R_SPF_FAIL (4.5) [-all]
VIOLATED_DIRECT_SPF (3.5)

One specific example:
- Sending IP: 54.240.1.123 (allowed via include amazonses.com)
- envelope-from <202410281147543384cfbf22b640bfa18a7942af80p0eu-C1CW9GL23B03D8@bounces.amazon.com>
- From: "Amazon.nl" <auto-bevestiging@amazon.nl>

### Versions
Rspamd daemon version 3.8.4

CPU architecture x86_64; features: avx2, avx, sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
Hyperscan enabled: TRUE
Jemalloc enabled: TRUE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.1700008891)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE

### Additional Information
Using Docker Mailserver 14.0.0

Could not find any information related to SPF processing in rspamd.log

**Comment by fatalbanana** [comment]
I can't reproduce that; unsure about a likely issue, maybe cache related.

The supported version of Rspamd is 3.10.2.

```
$ rspamadm dnstool spf --domain amazon.com -i 54.240.1.123
Policy: pass
Network: 54.240.0.0/18
Original: ip4:54.240.0.0/18
```
```
$ rspamc -F bla@amazonses.com -i 54.240.1.123 < /dev/null | grep SPF
Symbol: R_SPF_ALLOW (-0.20)[+ip4:54.240.0.0/18:c]
```

**Comment by hapklaar** [comment]
Unfortunately as I use a prefab DMS docker image, I can't upgrade to the last version, but I also haven't found anything in the changelogs related to this.

Trying your test I get the following results:

```
root@mail2:/# rspamadm dnstool spf --domain amazon.com -i 54.240.1.123
Cannot get SPF record: no SPF record
root@mail2:/# rspamc -F bla@amazon.com -i 54.240.1.123 < /dev/null | grep SPF
Symbol: R_SPF_NA (1.50)[no SPF record]
```

Strangly it determines an SPF fail for the same ip and the amazon.nl domain, which has as SFP record `v=spf1 include:amazon.com -all`
```
root@mail2:/# rspamadm dnstool spf --domain amazon.nl -i 54.240.1.123
Policy: reject
Network: any
Original: all
root@mail2:/# rspamc -F bla@amazon.nl -i 54.240.1.123 < /dev/null | grep SPF
Symbol: R_SPF_FAIL (4.50)[-all]

```
An example of a working SPF lookup:
```
root@mail2:/# rspamadm dnstool spf --domain dhlparcel.nl -i 185.189.237.204
Policy: pass
Network: 185.189.236.0/22
Original: ip4:185.189.236.0/22
```

It finding no SPF record for amazon.com and interpreting the one for amazon.nl incorrectly seems like it could be the issue, but why is this happening?

**Comment by fatalbanana** [comment]
I can neither reproduce on older versions so it should be somehow particular to your environment -& Amazon's bloated collection of TXT records. I'd suggest to check that your resolvers speak TCP.

**Comment by hapklaar** [comment]
Thanks for trying @fatalbanana 

My resolver is able to communicate over tcp. 
To get a bit more insight as to what I is happening, I tried increasing the log level for spf by adding the following to my /etc/rspamd/override.d/logging.inc: `debug_modules = ["spf"];`

Unfortunately that seems to have done nothing, no debug entries in rspamd.log. This is the correct way to do this right?

**Comment by fatalbanana** [comment]
> My resolver is able to communicate over tcp. To get a bit more insight as to what is happening, I tried increasing the log level for spf by adding the following to my /etc/rspamd/override.d/logging.inc: `debug_modules = ["spf"];`
> Unfortunately that seems to have done nothing also not after restarting, no debug entries in rspamd.log. This is the correct way to do this right?

Yes, that should get you debug logging for SPF module typically (and if you'd test SPF with `rspamc` you should see something).

**Comment by Nopel2020** [comment]
I am getting the same problem (R_SPF_FAIL and VIOLATED_DIRECT_SPF triggered) on legitimate mail from amazon.com.be with 3.11.0.

**Comment by japc** [comment]
> root@mail2:/# rspamadm dnstool spf --domain amazon.com -i 54.240.1.123
> Cannot get SPF record: no SPF record
...
> root@mail2:/# rspamadm dnstool spf --domain amazon.nl -i 54.240.1.123
> Policy: reject
> Network: any
> Original: all
...
> It finding no SPF record for amazon.com and interpreting the one for amazon.nl incorrectly seems like it could be the issue, but why is this happening?

If it doesn't find the include then the behaviour for the amazon.nl is just correct, because it ends up with "v=spf1 -all". 

That is because the lookup for amazon.com returns nothing ("no SPF record"). If it failed you should have a different behaviour.

You must have a DNS problem, maybe your DNS resolver vs the huge amount of amazon.com TXT records (could it be that it is not returning all TXT records, hence missing the spf?).

**Comment by japc** [comment]
@hapklaar sorry, late to the party and failed to see that you closed it already, and it seem to be related to a problem with the resolver not issuing a TCP query (needed for the size of the TXT response).

@Nopel2020 possibly the same issue?

**Comment by Nopel2020** [comment]
Yesterday I got two mails that were caught in the spam filter, but strangely enough another mail from amazon.com.be (sender IP 54.240.1.47) came through fine earlier today. When I try rspamadm dnstool now I can't reproduce the error anymore. I'll keep an eye on it but right now things work fine again.

**Comment by hapklaar** [comment]
I was eventually able to resolve my issue by removing one component in my DNS forwarder chain:

from:
rspamd > AdGuard > Unifi router > KPN (provider DNS server)
to:
rspamd  > AdGuard > KPN (provider DNS server)

afaik all hops are 53/TCP enabled, but for some reason with the Unifi rtr in the mix, amazon SPF lookups failed. Even when dig +tcp was able to query the txt records. I'll close this issue as for me its no longer present.

**Comment by japc** [comment]
> Yesterday I got two mails that were caught in the spam filter, but strangely enough another mail from amazon.com.be (sender IP 54.240.1.47) came through fine earlier today. When I try rspamadm dnstool now I can't reproduce the error anymore. I'll keep an eye on it but right now things work fine again.

The TXT response (for amazon.com, given the size and the problem description) must be truncated and, as the records are returned in no particular order, you may happen to have the spf on the response (where it should work) or not (spf fails). Check it by quering the dns resolver used by rspamd and comparing with the amazon.com response (either on the authoritative or a trustworthy public resolver).

Anyway, it's not a rspamd issue.
