### ISSUE TITLE
[BUG] url_redirector causing LUA error in lua_maps.lua

### ISSUE THREAD

**Issue by patschi** [rspamd/rspamd#5230]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

I do have checked the bug reporting notes and if I can find similar issues on Github issues. 

**Describe the bug**

I have found a weird error message when trying to use `url_redirector` module. I am using mailcow coming with rspamd rspamd_3.10.2-1~b8a232043. During the start of rspamd, following error is presented:

```text
rspamd-mailcow-1  | 2024-11-18 23:54:00 #1(main) <5okfgx>; lua; lua_redis.lua:605: use default Redis settings for url_redirector
rspamd-mailcow-1  | 2024-11-18 23:54:00 #1(main) <5okfgx>; cfg; rspamd_init_lua_filters: init of /usr/share/rspamd/plugins/url_redirector.lua failed: /usr/share/rspamd/lualib/lua_maps.lua:40: bad argument #1 to 'sub' (string expected, got table
); trace: [1]:{[C]:-1 - sub [C]}; [2]:{/usr/share/rspamd/lualib/lua_maps.lua:40 - starts [Lua]}; [3]:{/usr/share/rspamd/lualib/lua_maps.lua:49 - check_prefix [Lua]}; [4]:{/usr/share/rspamd/lualib/lua_maps.lua:80 - maybe_adjust_type [Lua]}; [5]:
{/usr/share/rspamd/lualib/lua_maps.lua:293 - map_add_from_ucl [Lua]}; [6]:{/usr/share/rspamd/plugins/url_redirector.lua:383 - <unknown> [main]};
```

The error in the `url_redirector.lua` corresponds with:
https://github.com/rspamd/rspamd/blob/41eab5b874721f7abc23144e5c3386392f1820f7/src/plugins/lua/url_redirector.lua#L383-L384

Which calls `rspamd_map_add_from_ucl()` in `lua_maps.lua`:
https://github.com/rspamd/rspamd/blob/41eab5b874721f7abc23144e5c3386392f1820f7/lualib/lua_maps.lua#L185-L195

What very interesting is, it specifies in the comments that either `string` or `table` is allowed:
```lua
-- @param {string or table} opt data for map (or URL)
```

The next error in `lua_maps.lua` corresponds with:
https://github.com/rspamd/rspamd/blob/41eab5b874721f7abc23144e5c3386392f1820f7/lualib/lua_maps.lua#L39-L41

The full config `local.d/url_redirector.conf` is:

```text
# How long to cache dereferenced links in Redis (default 1 day)
expire = 7d;
# Timeout for HTTP requests (10 seconds by default)
timeout = 5;
# How many nested redirects to follow (default 1)
nested_limit = 5;
# Check SSL certificates (default false)
check_ssl = false;
# How many urls to check
max_urls = 10;
# Maximum body to process
max_size = 10k;
# Insert symbol if redirected url has been found
redirector_symbol = "URL_REDIRECTOR";
redirector_symbol_nested = "URL_REDIRECTOR_NESTED";
# Follow merely redirectors
redirectors_only = true;
# Prefix for keys in redis (default "rdr:")
key_prefix = "rdr:";
# Redis key for top urls
top_urls_key = 'rdr:top_urls';
# How many top urls to save
top_urls_count = 200;
# Check only those redirectors
redirector_hosts_map = [
    "$CONFDIR/maps.d/redirectors.inc",
    "https://maps.rspamd.com/rspamd/redirectors.inc.zst"
];
# Which useragents to use
user_agent = [
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/121.0',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.2210.133',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 OPR/106.0.0.0'
];
```

I have narrowed it down to following config entry:
```text
redirector_hosts_map = [
    "$CONFDIR/maps.d/redirectors.inc",
    "https://maps.rspamd.com/rspamd/redirectors.inc.zst"
];
```

As the `.sub` lua syntax expects string, it seems to receive an array and hence presents an error. 

When I change this to (a string):
```text
redirector_hosts_map = "https://maps.rspamd.com/rspamd/redirectors.inc.zst";
```

The error is gone after the next restart.

Which would make sense, as even the docs only specify a single value as a string:
https://rspamd.com/doc/modules/url_redirector.html

### Steps to Reproduce

1. Use above config in `local.d/url_redirector.conf`
2. Restart rspamd
3. Check rspamd logs and above error is present

**Expected behavior**
Do not see above error message.

### Versions

rspamd version:
```
# rspamd --version
Rspamd daemon version 3.10.2

CPU architecture x86_64; features: avx2, avx, sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
Hyperscan enabled: TRUE
Jemalloc enabled: TRUE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.1725453128)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE
```

**OS**: `debian:bookworm-slim` in docker, Ubuntu 22.04 on host.
**CPU model**: Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz

### Additional Information

I have been having a chat with @dragoangel on Telegram and I have the base configuration for `url_redirector` from him. He states that the array, specifying multiple maps, does work fine for him. However it does not in my case and throws the error stated in the beginning.

Now I'm just confused what's right and expected and looking for clarification.

**Comment by fatalbanana** [comment]
I can't reproduce it. I'm not sure what to make of it. Perhaps effective configuration is not what's represented here.

**Comment by patschi** [comment]
I've been trying to get this information and reproduce the issue, and as embarrassing it is: I can't reproduce it. I don't know why. I tried the configuration several times (including rspamd restarts) to not file a crap issue here, so I'm certain it behaved this way. But it doesn't anymore.

Maybe something was cached, not properly restarted, some small bits like `;` missing somewhere... or something similar. Not sure. So I'll close this one. Sorry for waste your both time.

(Noteworthy - when doing the suggested `redirector_hosts_map` it indeed results in the error message as seen in my initial PR)
