### ISSUE TITLE
Why is the check_html_image function limited to embedded images?

### ISSUE THREAD

**Issue by moisseev** [rspamd/rspamd#525]
Is there a reason to this condition?
https://github.com/vstakhov/rspamd/blob/73373fe6130293dbb563be86f5f2d85c3c15ba6e/rules/html.lua#L36
Why not to remove it and catch linked images like that as well?

``` html
<a href="http://wikidrupal.ru/go/masterlittera.com/jexr/aHR0cDovL29jYnB=
hYy5wdy8/YXBrODV5bDQyejR6NjV2djMyYTB0eg=="><img src="https://pbs.tw=
img.com/media/CWX8-jZWEAIV1js.jpg"></a>
```

``` html
<a href="http://msichicago.org/exit.php?url=onsol.ru/dire
ct/go/aHR0cDovL3Byb3MucnBpb24ucnUvP2doM3htOG50bW5vNGdo" class="underline"><
img src="https://pbs.twimg.com/media/CWH4FYRWsAEohcC.jpg"
></a>
```

**Comment by vstakhov** [comment]
That was intended since the vast majority of email clients do not show external images unless explicitly requested by an user. Another reason to exclude external images from this check is to relax messages that contain just a single external image (e.g. a link to photo or a funny picture) that are regularly sent between legitimate users.

**Comment by moisseev** [comment]
It is a good thing that mail clients do not show such images, but they show message itself. I don't think it's a good reason for excluding from filtering.
About funny pictures. I guess users usually send just a link points to an image. Maybe it worth to add a rule for <img> element that is used as a link points to another object then?

**Comment by vstakhov** [comment]
That might work indeed. We could attach image to the enclosing tag and query if it's an `<a href>` tag pointing to some other TLD than the image itself.

**Comment by moisseev** [comment]
Do you really have evidence of such legitimate messages with  just a single external image that use an image as a link (`<img>` element inside `<a>`)? If you meant legitimate messages with a link to an image in `href` attribute but without an `<img>` element, it should be safe just remove the condition.

**Comment by vstakhov** [comment]
Of course I have: that's any image which is a thumbinal to a larger image.

**Comment by moisseev** [comment]
Hm. I don't know an easy way to create with MUA a link to remote image with a thumbnail. Maybe some MUA or network service does it for users, but I've really never seen such a message.

On the other hand if you drag-and-drop an image into the Thunderbird's mail composition window, it will create an imbedded image. So I don't see any reason to check only embedded images.

I've tried to send to myself an image that way (Thunderbird drag-and-drop) and got it into the `Junk` folder.
~~~
2016-02-15 16:56:50 #57637(normal) <4bae3c>; task; rspamd_task_write_log: id: <db0f6251-d394-3e9c-6c0b-5dc1bf8fd3ea@example.com>, qid: <6E16561FA6>, ip: 91.211.181.139, from: <test@example.com>, (default: F (add header): [11.16/15.00] [R_EMPTY_IMAGE,MIME_GOOD,MIME_UNKNOWN,R_SUSPICIOUS_IMAGES,BAYES_SPAM,R_SPF_ALLOW,HTML_SHORT_LINK_IMG_1]), len: 211599, time: 157.713ms real, 7.403ms virtual, dns req: 20
~~~

**Comment by vstakhov** [comment]
Ok, so what logic do you propose after all?

**Comment by moisseev** [comment]
[my email funny picture](https://paste.rspamd.com/fRBm/raw)
I've scanned it and got `R_EMPTY_IMAGE,...,R_SUSPICIOUS_IMAGES,...,HTML_SHORT_LINK_IMG_1`

1. `HTML_SHORT_LINK_IMG_1` There is no link at all in the message. The rule needs to be fixed.
2. Remove `embedded/not embedded` condition. Both should be treated the same way. For `R_EMPTY_IMAGE` is the same. BTW embedded thumbnails can exist too.
3. Legitimate image links. It is not a problem if they will be positively scored for ham messages if the score is not too high. Like `SUBJ_ALL_CAPS` or `MISSING_SUBJECT`. And as you proposed if TLDs of an `<a href>` tag and the `<img>` element is different we could add symbol with high score except messages with embedded `<img>` element.
4. I guess `R_SUSPICIOUS_IMAGES` is not intended to be triggered on a single image?

**Comment by vstakhov** [comment]
Well, I've reworked those rules. I've not done (3) and (4) however.

**Comment by moisseev** [comment]
Did you add  `<a>` tag checks to `R_EMPTY_IMAGE` and `R_SUSPICIOUS_IMAGES` rules on purpose?

**Comment by vstakhov** [comment]
Yes, to ensure that an image is enclosed within some link. That might help to avoid FP for attached images.

**Comment by moisseev** [comment]
Shouldn't symbol names and descriptions reflect that then?
It seems I don't understand what `R_SUSPICIOUS_IMAGES` intended for. I thought it supposed to catch messages with images that could be potentially used for textual information. That images are not always links.

**Comment by vstakhov** [comment]
I'm open for help in managing rules and symbols :) The current ruleset of rspamd is outdated, inconsistent and I'm not a mail admin to improve it constantly. I can add new methods to lua API, I can implement some ideas, but I definitely have neither time nor desire to write each rule by myself.

**Comment by moisseev** [comment]
~~~c
LUA_FUNCTION_DEF (html_tag, get_type);
/***
* @method html_tag:get_extra()
* Returns extra data associated with the tag
* @return {url|image|nil} extra data associated with the tag
*/
~~~
Would you explain what does html_tag:get_extra() return exactly? Is there a way to get url as string?

**Comment by vstakhov** [comment]
For `A` and `IFRAME` tags this could be a parsed URL (rspamd_url object). For img tags this is the same table returned by `html:get_images()` for a single image.

**Comment by moisseev** [comment]
> query if it's an `<a href>` tag pointing to some other TLD than the image itself

Turns out, this is not a very good idea. I went through a few emails and find out it's common for legitimate messages to have different TLDs for images and links.

**Comment by moisseev** [comment]
There are cases when image dimensions are not specified in html tag like in the sample below. I have an idea to get image dimensions from the embedded image itself, but I didn't find a way to get image object from mime part with specific `Content-Id` using Lua API. Would you suggest something?

~~~html
--0992c0ede5aa618af5cac3dff57a
Content-Type: text/html; charset="windows-1251"
Content-Transfer-Encoding: quoted-printable

<HTML><HEAD>
<META http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dwindows=
-1251">
</HEAD>
<BODY bgColor=3D#ffffff>
<DIV align=3Dleft><FONT size=3D2 face=3DArial><IMG border=3D0 hspace=3D0 =
alt=3D""=20
src=3D"cid:F206F97FED764ECD8D0916AE6AD53A88@tuontitukku.fi"></FONT></DIV>=
</BODY></HTML>

--0992c0ede5aa618af5cac3dff57a--

--15668bf5281e9afea008fc27c12b
Content-Type: image/gif; name="uwif.gif"
Content-Transfer-Encoding: base64
Content-ID: <F206F97FED764ECD8D0916AE6AD53A88@tuontitukku.fi>

R0lGODdhAgO4A3cAACwAAAAAAgO4A4cAAACAAAAAgACAgAAAAICAAIAAgIDAwMDA3MCmyvAAAAAY
GP8AsFD/AAD//wDDw//Pz//b2/////8AAHgAAAEAAAAAAAAY8lDB+jwAAAMAEAYY8zQp/IAAAAAA
AA8AAB4AAAABHmv////B+lYAAAEAATUAAADClH3OMiABHmv////ClIwBHmsBAACP2gj9sAAAAAAA
~~~

**Comment by moisseev** [comment]
@vstakhov can you explain in detail the idea behind `R_SUSPICIOUS_IMAGES`?
It triggers on legitimate messages. I guess it should be modified somehow, but I don't understand what `R_SUSPICIOUS_IMAGES` intended for.
