### ISSUE TITLE
[BUG] No Throughput Grafic in 3.11.0-0git67

### ISSUE THREAD

**Issue by cleicht** [rspamd/rspamd#5257]
14.12.2024, 20:41:29 | controller | 1087392 | csession | e4bbf9 | no rrd configured
-- | -- | -- | -- | -- | --
14.12.2024, 20:40:17 | controller | 1087385 | csession | 436d3e | no rrd configured
14.12.2024, 20:40:02 | controller | 1087409 | csession | 59aaf3 | no rrd configured
14.12.2024, 20:37:45 | controller | 1087392 | csession | 105a3d | no rrd configured
14.12.2024, 20:37:07 | controller | 784026 | csession | 7f60cd | no rrd configured
14.12.2024, 20:25:00 | controller | 784026 | csession | 5cec2f | http error occurred: IO read error: unexpected EOF
![grafik](https://github.com/user-attachments/assets/86444fad-aaed-4e9d-aed4-945dfd58cd1a)

**Comment by vstakhov** [comment]
Your issue is incomplete, please check how to make meaningful issue reports and to ask [smart questions](http://www.catb.org/esr/faqs/smart-questions.html)
