### ISSUE TITLE
[Feature] LDAP integration

### ISSUE THREAD

**Issue by falon** [rspamd/rspamd#570]
Hello, I would like to migrate from Amavis/Spamassassin/Dspam to rspamd.
Dspam has  a module to map all email aliases of an account. For instance:
- ExtLookupDB             "ou=base,c=fr"  # Can either be an LDAP search base or a database name (TODO).
- ExtLookupQuery          "(&(|(mail=%u)(mailalternateaddress=%u))(|(&(objectclass=mailrecipient)(mailUserStatus=active))(objectclass=mailgroup)))"       # Can either be an LDAP search filter or an SQL query (TODO)
- ExtLookupLDAPAttribute  "uid"                           # Attribute to be used when ExtLookupDriver is 'ldap'

The LDAP ldif is something like:
- dn: uid=username@domain,o=<domain>,...
- uid: username@domain
- mail: username@domain
- mailAlternateAddress: alias@domain

This feature is needed if I use a per-user statistics, to join tokens of same accounts's aliases.

More generally, with Amavis I can also define a user profile on LDAP. For instance, I can set whitelist/blackslit recipient lists, as:
- dn: uid=username@domain,o=<domain>,...
- uid: username@domain
- mail: username@domain
- mailAlternateAddress: alias@domain
- amavisWhitelistSender: wanted@example.com
- amavisBlacklistSender: unwanted@example.com

I would very appreciate something similar in rspamd.

Thank you very much

**Comment by denji** [comment]
Using Lua scripting, you can implement most of the functionality
* https://github.com/prosody-modules/mod_auth_ldap2/blob/master/mod_auth_ldap2.lua
* https://github.com/kvaps/kolabgr

**Comment by Mic92** [comment]
The official lualdap is not compatible with lua5.2 and lua5.3. I made a fork for my prosody server: https://github.com/Mic92/lualdap
