### ISSUE TITLE
per_user bayes not working in alias/group emails

### ISSUE THREAD

**Issue by jruffet** [rspamd/rspamd#571]
Hi,

I am using a dual BAYES configuration, with a system wide bayes and a user based bayes_user (see below).

If I send spam content (learned with `-c bayes_user`) to `me@domain.tld`, everything works fine, it shows `BAYES_SPAM_USER`.
If I create an alias, say `alias@domain.tld` that points to `me@domain.tld`, and resend the exact same content to that alias, then `BAYES_SPAM_USER` does not trigger.

I suppose that this happens because when rspamd receives the content from rmilter, the `Delivered-To` header does not exist yet, thus rspamd has no clue what the final destination is (apart from the original `rcpt to`).
Also, if the alias refers to multiple addresses (group email), we have the same issue, which makes sense.
And since rspamd is only triggered once per incoming email, there is no way it can apply a per_user bayesian score per actual recipient.

Is there a way to achieve a per_user bayesian score on those kind of emails ? 
I was thinking about something along those lines :
1. run rspamd via postfix without any per_user scoring.
2. re-run rspamd via dovecot (for example) for every instances of the same email, before sieve filters are applied but when we know each final destination, in a `only_apply_per_user_bayesian_score` mode, modifying rspamd headers and the overall score if need be.
This way the overhead would be minimal, and we could achieve per_user bayesian scoring on all emails.

With the idea that one email sent to a group email may not be considered the same, ham/spam wise, depending on the recipient. For example, our accountants receive a lof of invoices that are usually phishing for most of us.

If that's any useful, I am using this configuration :

```
classifier {
    tokenizer {
        name = "osb";
    }
    name = "bayes_user";
    min_tokens = 11;
    backend = "sqlite3";
    per_language = true;
    per_user = true;
    statfile {
        path = "${DBDIR}/bayes.spam.user.sqlite";
        symbol = "BAYES_SPAM_USER";
    }
    statfile {
        path = "${DBDIR}/bayes.ham.user.sqlite";
        symbol = "BAYES_HAM_USER";
    }
}
classifier {
    tokenizer {
        name = "osb";
    }
    name = "bayes";
    min_tokens = 11;
    backend = "sqlite3";
    per_language = true;
    statfile {
        path = "${DBDIR}/bayes.spam.sqlite";
        symbol = "BAYES_SPAM";
    }
    statfile {
        path = "${DBDIR}/bayes.ham.sqlite";
        symbol = "BAYES_HAM";
    }
}
```

**Comment by fatalbanana** [comment]
There's a newly-available API function: [task:set_recipients()](https://rspamd.com/doc/lua/task.html#m248af) which could be used to dereference aliases.

**Comment by TheIvanSusanin** [comment]
@jruffet did you manage to make it work with aliases ?
