### ISSUE TITLE
Feature request: add proxy support to HTTP-Client

### ISSUE THREAD

**Issue by dothebart** [rspamd/rspamd#572]
RSpamd tries to fetch http://rspamd.com/update/rspamd-1.2.ucl which may not work in a strict containered environment that doesn't allow access to external resources. 
Usually these environments offer http proxies for that purpose.

Implementing proxies isn't that hard for http clients; the request line needs to contain the full URI:

```
GET http://rspamd.com/update/rspamd-1.2.ucl HTTP/1.1
...
```

instead of 

```
GET /update/rspamd-1.2.ucl HTTP/1.1
Host: rspamd.com
...
```

and for shure connect the proxy ip/port instead of looking up the domain and connecting there.

usually these environments offer the environment variables http_proxy and https_proxy for the configuration.

**Comment by northalpha** [comment]
I would really like to configure an HTTP Proxy for list and general updates, therefore +1 :)

**Comment by vstakhov** [comment]
Actually I'm not sure about the status of this project. HTTPS proxying requires `CONNECT` method support which overcomplicates things. Why not use Nginx or other proxy in forward-proxy mode before Rspamd?
