### ISSUE TITLE
[Feature] want_spam = no for blacklist

### ISSUE THREAD

**Issue by Dmitry55** [rspamd/rspamd#582]
For now I use such config for blasklist
setting {
    user_bl {
        priority = "high";
        from = "sender@domain1.com";
        rcpt = "recipient@domain2.com";
        apply = "default";
        symbols [
            "USER_BLACKLIST",
        ]
    }
}

metric {
        symbol {
                weight = 200;
                name = "USER_BLACKLIST";
        }
}

Problems with this config:
1. autolearn will always learn such email as spam for all users
2. difficult to create more complicated rules on Lua (for example - store black and white lists on LDAP)

Can you add  want_spam = no to relolve this issues

**Comment by vstakhov** [comment]
I don't understand what do you want. If you want to disable autolearning for such messages then just write lua script for autolearn checks that detects this symbol. I don't also understand the second point at all.

**Comment by Dmitry55** [comment]
Correct me if I'm wrong
It is necessary to create post-filter and check tasks "has_flag" and "has_simbol" and then disable learning through set_flag.

About seconp part -
in doc i found that i can write something like this

settings {
from = "user@domain1.com"
rcpt = "user@domain2.com"
want_spam = <<EOD
return function(task)

some checks in ladp 

if whitelist return yes
else if blacklist return no
else return nil 

end
EOD
}

But looks like it is posible only in classifier module for per_user and per_language options.
