### ISSUE TITLE
integration project

### ISSUE THREAD

**Issue by Britomb2** [rspamd/rspamd#690]
Good afternoon!

We are users of its filtering mechanisms recently implemented in our gateways responsible for receiving emails, I wonder about the integration and the possibility of use on a specific project (I apologize for my English, I'm a little unaccustomed to its use ).

In some hosting environments with email service, we have the SpamAssassin, which works only locally, with the intention of moving the content of messages filtered by Rspamd, I wonder if there is an integration and possbilidade of both tools, or is, SpamAssasin somehow make the mechanism of Rspamd filter training, store this information locally (a shared basis) than it is spam or not classified by the potential users.

**Comment by vstakhov** [comment]
Rspamd cannot use SpamAssassin statistics, however, it can use SA regexp rules. I don't quite understand your issue, I'm afraid. If you mean whether is it possible to use rspamd and SA simultaneously, then yes it is possible. If you mean whether is it possible to move from SA to rspamd then it depends on how do you use SA. I can't tell more without more details.

**Comment by Britomb2** [comment]
We have different email platforms, postfix (in Debian machines with Plesk Panel) - Exim (cpanel CentOS) and MailEnable (Plesk Panel windows) - the initial idea is SpamAssassin, the idea is that somehow we could integrate the statistics SpamAssassin with gateway use to receive messages, which own the RspamD working on filtering, generating the filter capacity and RspamD and local basis, as it has no way to use the SpamAssim and statistics generated by users, we believe that this can be done in some other way? -
Thank you for the clarification.

**Comment by fatalbanana** [comment]
Question here is terribly unclear I'm afraid. You might find it easier to get help on [IRC or Telegram](https://rspamd.com/support.html).
