### ISSUE TITLE
HFILTER_URL_ONLY catches too much legitimate mail

### ISSUE THREAD

**Issue by moisseev** [rspamd/rspamd#747]
Some legitimate mails have huge amount of very long URLs. I think it' is pointless to compare total URL length and text part length. It might be better to calculate total `a tag` content (visible part) length instead. But I have no idea how to do that.

**Comment by samtuke** [comment]
Same issue here

**Comment by alexlehm** [comment]
I am experiencing that as well, especially on mails with a single line when the signature contains a profile url
