### ISSUE TITLE
rspamc produces different headers than rmilter+rspamd

### ISSUE THREAD

**Issue by foogod** [rspamd/rspamd#799]
Not sure if this really belongs on rspamd/rspamc or on rmilter, but:

I'm currently using rspamd with postfix via rmilter (with `spamd_never_reject = yes` so that it only adds headers, not actually bouncing mail, and then use additional filtering mechanisms during delivery (i.e. procmail) to filter messages based on the headers)..

I would like to also run a bunch of old email messages through the new rspamd setup and filter them using the same rules/process.  I can use rspamc to process each message and add headers, but unfortunately rspamc adds a somewhat-similar-but-not-the-same set of headers to the message to what I would get from rmilter (for example, "X-Spam:" instead of "X-Spam-Status:"), making any existing filtering rules (server side or client side) not work the same way with these messages.  (as far as I can tell, rspamc also doesn't appear to have any equivalent to the `extended_spam_headers` option in rmilter..)

It would be really nice if rspamc had the ability to produce the same set of email headers as rmilter does when processing an email, so the two could be used somewhat interchangeably..

**Comment by xpunkt** [comment]
spamassassin removes own headers is this what missing in rmilter/rspamd ?

rspamc --remove-headers --mime | sendmail .....

where --remove-headers still have to be added in c code

**Comment by xpunkt** [comment]
/etc/postfix/main.cf
# header_checks = pcre:/path/to/file.pcre
# here is headers from spamassassin removed in incomming
# if you like to just remove on outgoing, use smtp_header_checks instaed
#
/^X-Spam-Flag:/ IGNORE
/^X-Spam-Level:/ IGNORE
/^X-Spam-Report:/ IGNORE
/^X-Spam-Score:/ IGNORE
/^X-Spam-Status:/ IGNORE

**Comment by foogod** [comment]
No, I don't think that's what I'm talking about at all.  This has nothing to do with spamassassin or removing headers.

The problem is that the headers *added* by rspamc are not the same as the headers *added* by rmilter+rspamd.  For example, running the exact same message through both produces the following extra headers:

rmilter:
````
X-Spamd-Result: default: True [16.30 / 15.00]
 DATE_IN_FUTURE(4.00)[]
 ONCE_RECEIVED_STRICT(4.00)[]
 HFILTER_HOSTNAME_UNKNOWN(2.50)[]
 HFILTER_FROMHOST_NORES_A_OR_MX(1.50)[]
 RBL_SPAMHAUS_PBL1(2.00)[]
 HFILTER_HELO_NORES_A_OR_MX(0.30)[]
 ONCE_RECEIVED(0.10)[]
 MIME_GOOD(-0.10)[multipart/alternative, text/plain]
 RDNS_NONE(1.00)[]
 HFILTER_HELO_IP_A(1.00)[]
X-Spamd-Bar: ++++++++++++++++
X-Spam-Level: xxxxxxxxxxxxxxxx
X-Spam-Status: Yes, score=16.3
X-Spamd-Server: localhost
X-Spamd-Scan-Time: 0.53
X-Spamd-Queue-ID: 73A2340D963C
X-Spam: yes
````
rspamc:
````
X-Spam-Scanner: rspamc 1.3.1
X-Spam-Scan-Time: 0.266
X-Spam: yes
X-Spam-Action: reject
X-Spam-Score: 26.00 / 15.00
X-Spam-Level: **************************
X-Spam-Symbols: HFILTER_HELO_UNKNOWN,RDNS_NONE,HFILTER_FROMHOST_NORES_A_OR_MX,
        BROKEN_HEADERS,ONCE_RECEIVED_STRICT,RBL_SPAMHAUS_XBL_ANY,RBL_SPAMHAUS_PBL1,
        ONCE_RECEIVED,HFILTER_HOSTNAME_UNKNOWN,RBL_SPAMHAUS_XBL,MIME_GOOD,
        DATE_IN_FUTURE
````

**Comment by xpunkt** [comment]
so its not a mix of incomming headers and outgoind header problem ?

in that case i give up

**Comment by vstakhov** [comment]
BTW, bars and status have been removed from Rmilter. I decided to use a more flexible method by adding/removing headers in Rspamd and passing specific rules in `rmilter` block. I think `rspamc` can use it as well.

**Comment by foogod** [comment]
Yeah, I actually noticed that when I did a routine yum update on my mailhost yesterday and then my users suddenly started complaining that a bunch of the mail filters they'd created which use those headers were now not working anymore.  (I was able to get most of it straightened out, but it took a good portion of yesterday which I really wasn't planning on having to spend on broken mail systems..  Thanks a lot.)

If you're going to just remove useful things that people may be relying on, you really should give folks a bit of warning first.

**Comment by vstakhov** [comment]
I'm really sorry about the inconenience caused: I should have mentioned that in 1.3/1.9 upgrading notes (I just forgot about it). The problem was caused that I was asked by one user to add those headers, subsequently another user asked me to remove them as they caused issues when both Rspamd and SA were used. So I've decided to move this part to Rspamd where you can just define a simple script to restore the previous functionality (and I should have included a sample of such a script as well).

Again, I'm very sorry about this incident.

**Comment by foogod** [comment]
That's ok.. sorry, I was probably a bit more harsh than necessary (to be honest even if it was in the upgrade notes, I probably wouldn't have noticed it until after the fact anyway)..

The new approach does sound like a good one to me.. is that actually fully implemented now?  If so I'd love to start playing with it.. is there any info available on how to customize the headers in rspamd?

**Comment by fatalbanana** [comment]
Reading the [migration notes](https://rspamd.com/doc/migration.html) before updating is definitely a good idea as rspamd has been moving quite fast for a while & is showing no signs of slowing down (The [blog](https://rspamd.com/blog/) may also be of some casual interest). Consider marking rspamd/rmilter to be held back to avoid unplanned upgrades.

The migration notes should be updated soon- you can view proposed changes [here](https://github.com/vstakhov/rspamd.com/pull/109/files).

**Comment by myfreeweb** [comment]
> rspamc also doesn't appear to have any equivalent to the extended_spam_headers option in rmilter

Still a problem… According to migration notes, extended_spam_headers is now in the built-in milter support, but what about rspamc-as-LDA? I use OpenSMTPD and I'd like to have `X-Spamd-Result` for [the Thunderbird addon](https://github.com/moisseev/rspamd-spamness).
