### ISSUE TITLE
LMTP support ?

### ISSUE THREAD

**Issue by masenocturnal** [rspamd/rspamd#802]
I am currently using spamassassin acting as an LTMP server and this seems to work quite well as it allows me to bring down spamassassin and postfix will just queue the mail until i bring it up again.

Can you provide some insight as to why the Milter route was chosen, pros / cons and perhaps if there is a possibility of LTMP support in the future ?

Also would you be open to accepting a patch for caching support via mariadb / postgres as an option?

**Comment by fatalbanana** [comment]
Rspamd is not tied to milter (and indeed does not support it directly)- it speaks [plain HTTP](https://rspamd.com/doc/architecture/protocol.html). Rspamd works best with proper MTA integration (as this provides it with additional insight about messages- eg. host that sent it; SMTP FROM/RCPT addresses; if it was sent by an authenticated user, etc)- and the way to do this with most MTAs is milter. This also enables filtering at SMTP time: which allows you to reduce load on backend servers/avoid filling your queue with spam & to be transparent about your filtering decisions (so as to reduce potential harm done to good mail & maintain general confidence in e-mail as a viable communication platform).

I am not aware of any plans to add LMTP support. Rspamd should be somewhat easy to integrate with an existing LMTP proxy.

Not sure what you mean by 'caching'. Problem with these databases is generally that they don't play well with event-driven model.

**Comment by fatalbanana** [comment]
... You may also be interested in rspamd's proxying feature:

https://highsecure.ru/rspamd-testing.pdf
https://www.youtube.com/watch?v=aMJcry0u_HQ

**Comment by fatalbanana** [comment]
... Finally, I should probably mention that Rspamd has partial support for SpamAssassin-protocol (namely `SYMBOLS` method) so you _might_ be able to use it as a drop-in replacement (though this is definitely not preferred).

**Comment by masenocturnal** [comment]
Thanks a lot for the in-depth explanation. 
The rspamd proxy definitely would be advantageous. I guess so long as I can configure postfix to queue if there are any issues contacting rspamd (or proxy) it should be fine.

I'm not necessarily looking for a drop in replacement, just that the way spamassassin currently deals with it is not bad from a reliability perspective. 

WRT to caching, I am referring to using mariadb/postgres instead of redis. The reason for this is that both dovecot and postfix can perform lookup queries, record statistics and store additional attributes within mariadb and postgresql and I've personally been able to scale this quite well on very modest hardware. Currently I think dovecot has a redis plugin as part of it's upstream source but to my knowledge postfix is not currently able to do this. Innodb is quite efficient at handling lots of small updates / inserts to the database.  It is my understanding that for at least mariadb there is a non-blocking API which I could use if appropriate. However, I would not want to spend the time and effort doing so if the patch was unwelcome. 

At this stage I'm just looking at options and rspamd has some significant advantages over spamassassin. It's also a change to the way I have been (successfully) been doing things so I am just trying to better understand what possibilities exist.

Thank you for spending the time to help.
